import { BaseMovie } from '../../../models/movie-model';

/** Films vus par Marina – listes issues des captures d'écran (thrillers, Barbie, divers). */
export const baseMoviesFromMarina: BaseMovie[] = [
  /* Liste 1 – Thrillers / Horreur */
  {
    title: 'Wedding Nightmare',
    director: 'Tyler Gillett',
    actors: [
      { name: 'Samara Weaving' },
      { name: 'Adam Brody' },
      { name: "Mark O'Brien" },
      { name: 'Henry Czerny' },
    ],
    coverUrl: '/movies_pictures/f8fe5b1d0bd0.jpg',
    releaseDate: '2019-01-01',
    length: 87,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Jessie',
    director: 'Mike Flanagan',
    actors: [
      { name: 'Kate Bosworth' },
      { name: 'Thomas Jane' },
      { name: 'Jacob Tremblay' },
      { name: 'Annabeth Gish' },
    ],
    coverUrl: '/movies_pictures/a6b7bf1c8e17.jpg',
    releaseDate: '2017-01-01',
    length: 97,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Dans les hautes herbes',
    director: 'Vincenzo Natali',
    actors: [
      { name: 'Harrison Gilbertson' },
      { name: 'Laysla De Oliveira' },
      { name: 'Patrick Wilson' },
      { name: 'Avery Whitted' },
    ],
    coverUrl: '/movies_pictures/efc4348dc145.jpg',
    releaseDate: '2019-01-01',
    length: 101,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'La fracture',
    director: 'Catherine Corsini',
    actors: [
      { name: 'Valeria Bruni Tedeschi' },
      { name: 'Marina Foïs' },
      { name: 'Pio Marmaï' },
      { name: 'Aissatou Diallo Sagna' },
      { name: 'Jean-Louis Coulloc\'h' },
      { name: 'Léa Drucker' },
      { name: 'Lola Dewaere' },
    ],
    coverUrl: '/movies_pictures/0f3ae1f6a2e1.jpg',
    releaseDate: '2019-01-01',
    length: 107,
    genre: ['Drame'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Ghostland',
    director: 'Pascal Laugier',
    actors: [
      { name: 'Crystal Reed' },
      { name: 'Mylène Farmer' },
      { name: 'Anastasia Phillips' },
      { name: 'Emilia Jones' },
    ],
    coverUrl: '/movies_pictures/1d2a9b27f71e.jpg',
    releaseDate: '2018-01-01',
    length: 91,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
  },
  {
    title: "Don't Breathe",
    director: 'Fede Álvarez',
    actors: [
      { name: 'Jane Levy' },
      { name: 'Dylan Minnette' },
      { name: 'Stephen Lang' },
      { name: 'Daniel Zovatto' },
    ],
    coverUrl: '/movies_pictures/21bfc6532a80.jpg',
    releaseDate: '2016-01-01',
    length: 88,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'I Spit on Your Grave',
    director: 'Steven R. Monroe',
    actors: [
      { name: 'Sarah Butler' },
      { name: 'Jeff Branson' },
      { name: 'Andrew Howard' },
      { name: 'Daniel Spink' },
    ],
    coverUrl: '/movies_pictures/98aba15fdcfc.jpg',
    releaseDate: '2010-01-01',
    length: 108,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Black Phone',
    director: 'Scott Derrickson',
    actors: [
      { name: 'Ethan Hawke' },
      { name: 'Mason Thames' },
      { name: 'Madeleine McGraw' },
      { name: 'Jeremy Davies' },
    ],
    coverUrl: '/movies_pictures/b78fc57ea13b.jpg',
    releaseDate: '2021-01-01',
    length: 103,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Ma',
    director: 'Tate Taylor',
    actors: [
      { name: 'Octavia Spencer' },
      { name: 'Diana Silvers' },
      { name: 'Juliette Lewis' },
      { name: 'Luke Evans' },
    ],
    coverUrl: '/movies_pictures/8721d8136f4f.jpg',
    releaseDate: '2019-01-01',
    length: 99,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Lovely Bones',
    director: 'Peter Jackson',
    actors: [
      { name: 'Saoirse Ronan' },
      { name: 'Mark Wahlberg' },
      { name: 'Rachel Weisz' },
      { name: 'Stanley Tucci' },
    ],
    coverUrl: '/movies_pictures/3eddafceaeea.jpg',
    releaseDate: '2009-01-01',
    length: 135,
    genre: ['Drame'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Intrusion',
    director: 'Adam Salky',
    actors: [
      { name: 'Freida Pinto' },
      { name: 'Logan Marshall-Green' },
      { name: 'Robert John Burke' },
      { name: 'Megan Elisabeth Kelly' },
      { name: 'Sarah Minnich' },
      { name: 'Bonita King' },
      { name: 'Mark Sivertsen' },
    ],
    coverUrl: '/movies_pictures/2fc720108dfc.jpg',
    releaseDate: '2019-01-01',
    length: 92,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: "L'intrusion",
    director: 'Natalie E. James',
    actors: [
      { name: 'Emily Mortimer' },
      { name: 'Bella Heathcote' },
      { name: 'Robyn Nevin' },
      { name: 'Chris Bunton' },
      { name: 'Steve Rodgers' },
      { name: 'Robin Northover' },
      { name: 'Jeremy Stanford' },
    ],
    coverUrl: '/movies_pictures/2c5e33d85784.jpg',
    releaseDate: '2021-01-01',
    length: 92,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'The Weekend Away',
    director: 'Kim Farrant',
    actors: [
      { name: 'Leighton Meester' },
      { name: 'Christina Wolfe' },
      { name: 'Ziad Bakri' },
      { name: 'Luke Norris' },
    ],
    coverUrl: '/movies_pictures/917a6d22a9e9.jpg',
    releaseDate: '2022-01-01',
    length: 89,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'La femme à la fenêtre',
    director: 'Joe Wright',
    actors: [
      { name: 'Amy Adams' },
      { name: 'Gary Oldman' },
      { name: 'Julianne Moore' },
      { name: 'Anthony Mackie' },
    ],
    coverUrl: '/movies_pictures/fbe41b8934f5.jpg',
    releaseDate: '2021-01-01',
    length: 100,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Obsession secrète',
    director: 'Peter Sullivan',
    actors: [
      { name: 'Brenda Song' },
      { name: 'Mike Vogel' },
      { name: 'Dennis Haysbert' },
      { name: 'Ashley Scott' },
      { name: 'Paul Sloan' },
      { name: 'Daniel Booko' },
      { name: 'Scott Peat' },
    ],
    coverUrl: '/movies_pictures/b157dfe4ba46.jpg',
    releaseDate: '2019-01-01',
    length: 97,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Fatale',
    director: 'Deon Taylor',
    actors: [
      { name: 'Hilary Swank' },
      { name: 'Michael Ealy' },
      { name: 'Mike Colter' },
      { name: 'Danny Pino' },
    ],
    coverUrl: '/movies_pictures/569866547576.jpg',
    releaseDate: '2020-01-01',
    length: 91,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Rivales',
    director: 'Denise Di Novi',
    actors: [
      { name: 'Katherine Heigl' },
      { name: 'Rosario Dawson' },
      { name: 'Geoff Stults' },
      { name: 'Cheryl Ladd' },
    ],
    coverUrl: '/movies_pictures/4fc1969cb036.jpg',
    releaseDate: '2017-01-01',
    length: 100,
    genre: ['Drame'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Rencontre fatale',
    director: 'Deon Taylor',
    actors: [
      { name: 'Hilary Swank' },
      { name: 'Michael Ealy' },
      { name: 'Mike Colter' },
      { name: 'Danny Pino' },
      { name: 'Tyrin Turner' },
      { name: 'Damaris Lewis' },
      { name: 'Sam Daly' },
    ],
    coverUrl: '/movies_pictures/56e7f1f73fe2.jpg',
    releaseDate: '2020-01-01',
    length: 91,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Mea Culpa',
    director: 'Tyler Perry',
    actors: [
      { name: 'Kelly Rowland' },
      { name: 'Trevante Rhodes' },
      { name: 'Nick Sagar' },
      { name: 'Sean Sagar' },
    ],
    coverUrl: '/movies_pictures/9659ccd9b054.jpg',
    releaseDate: '2024-01-01',
    length: 120,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Double vice',
    director: 'André van Duren',
    actors: [
      { name: 'Bracha van Doesburgh' },
      { name: 'Elise Schaap' },
      { name: 'Walid Benmbarek' },
      { name: 'Nasrdin Dchar' },
      { name: 'Noortje Herlaar' },
      { name: 'Hannah Hoekstra' },
      { name: 'Yannick Jozefzoon' },
    ],
    coverUrl: '/movies_pictures/013d6ca72250.jpg',
    releaseDate: '2022-01-01',
    length: 96,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Liaison fatale',
    director: 'Adrian Lyne',
    actors: [
      { name: 'Michael Douglas' },
      { name: 'Glenn Close' },
      { name: 'Anne Archer' },
      { name: 'Ellen Hamilton Latzen' },
    ],
    coverUrl: '/movies_pictures/f27b36b93efe.webp',
    releaseDate: '1987-01-01',
    length: 119,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Fair Play',
    director: 'Chloe Domont',
    actors: [
      { name: 'Phoebe Dynevor' },
      { name: 'Alden Ehrenreich' },
      { name: 'Eddie Marsan' },
      { name: 'Rich Sommer' },
    ],
    coverUrl: '/movies_pictures/40e860ab19e2.jpg',
    releaseDate: '2023-01-01',
    length: 113,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'The Jane Doe Identity',
    director: 'André Øvredal',
    actors: [
      { name: 'Brian Cox' },
      { name: 'Emile Hirsch' },
      { name: 'Ophelia Lovibond' },
      { name: 'Michael McElhatton' },
      { name: 'Olwen Catherine Kelly' },
      { name: 'Parker Sawyers' },
      { name: 'Jane Perry' },
    ],
    coverUrl: '/movies_pictures/9cf6a1c08bc1.jpg',
    releaseDate: '2016-01-01',
    length: 95,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'La maison de cire',
    director: 'Jaume Collet-Serra',
    actors: [
      { name: 'Elisha Cuthbert' },
      { name: 'Chad Michael Murray' },
      { name: 'Brian Van Holt' },
      { name: 'Paris Hilton' },
    ],
    coverUrl: '/movies_pictures/e1c75dd0d057.jpg',
    releaseDate: '2005-01-01',
    length: 113,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Happy Death Day',
    director: 'Christopher Landon',
    actors: [
      { name: 'Jessica Rothe' },
      { name: 'Israel Broussard' },
      { name: 'Ruby Modine' },
      { name: 'Charles Aitken' },
    ],
    coverUrl: '/movies_pictures/52a131fe1f4f.png',
    releaseDate: '2017-01-01',
    length: 96,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Action ou vérité',
    director: 'Jeff Wadlow',
    actors: [
      {
        name: 'Lucy Hale',
      },
      {
        name: 'Tyler Posey',
      },
      {
        name: 'Violett Beane',
      },
      {
        name: 'Nolan Gerard Funk',
      },
    ],
    coverUrl: '/movies_pictures/43bdb09e65ab.jpg',
    releaseDate: '2018-01-01',
    length: 100,
    genre: ['Thriller', 'Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Play or Die',
    director: 'Jacques Kluger',
    actors: [
      { name: 'Fargo Tbakhi' },
      { name: 'Alison Wheeler' },
      { name: 'Victor Meutelet' },
      { name: 'Pierre Benoist' },
    ],
    coverUrl: '/movies_pictures/3e08c57a1064.jpg',
    releaseDate: '2019-01-01',
    length: 98,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Affamés',
    director: 'Robin Aubert',
    actors: [
      { name: 'Marc-André Grondin' },
      { name: 'Monique Spaziani' },
      { name: 'Jean-François Boudreau' },
      { name: 'Charlotte St-Martin' },
    ],
    coverUrl: '/movies_pictures/9bbe62194e94.jpg',
    releaseDate: '2017-01-01',
    length: 95,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'The Farm',
    director: 'Hans Stjernswärd',
    actors: [
      { name: 'Nora Yessayan' },
      { name: 'Jake Weary' },
      { name: 'Kelly Lou Dennis' },
      { name: 'Will Brittain' },
    ],
    coverUrl: '/movies_pictures/66f7789ed64b.jpg',
    releaseDate: '2019-01-01',
    length: 80,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Couple modèle',
    director: 'Peter Askin',
    actors: [
      { name: 'Mark Duplass' },
      { name: 'Elisabeth Moss' },
      { name: 'Ted Danson' },
      { name: 'Mary Steenburgen' },
    ],
    coverUrl: '/movies_pictures/3eb2cd4d11e5.jpg',
    releaseDate: '2014-01-01',
    length: 91,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Jamais plus',
    director: 'Justin Baldoni',
    actors: [
      { name: 'Blake Lively' },
      { name: 'Justin Baldoni' },
      { name: 'Brandon Sklenar' },
      { name: 'Jenny Slate' },
    ],
    coverUrl: '/movies_pictures/476548f83609.webp',
    releaseDate: '2024-01-01',
    length: 130,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'La maison des 1000 morts',
    director: 'Rob Zombie',
    actors: [
      { name: 'Sid Haig' },
      { name: 'Bill Moseley' },
      { name: 'Sheri Moon Zombie' },
      { name: 'Karen Black' },
    ],
    coverUrl: '/movies_pictures/8e8fed3f61ea.jpg',
    releaseDate: '2003-01-01',
    length: 88,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'The Grudge',
    director: 'Takashi Shimizu',
    actors: [
      { name: 'Sarah Michelle Gellar' },
      { name: 'Jason Behr' },
      { name: 'William Mapother' },
      { name: 'Clea DuVall' },
    ],
    coverUrl: '/movies_pictures/6b8879b12484.jpg',
    releaseDate: '2004-01-01',
    length: 91,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Annabelle',
    director: 'John R. Leonetti',
    actors: [
      { name: 'Annabelle Wallis' },
      { name: 'Ward Horton' },
      { name: 'Alfre Woodard' },
      { name: 'Tony Amendola' },
    ],
    coverUrl: '/movies_pictures/e587c18e1841.jpg',
    releaseDate: '2014-01-01',
    length: 99,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'La nonne',
    director: 'Corin Hardy',
    actors: [
      { name: 'Taissa Farmiga' },
      { name: 'Demián Bichir' },
      { name: 'Jonas Bloquet' },
      { name: 'Charlotte Hope' },
    ],
    coverUrl: '/movies_pictures/30dadb7e9225.jpg',
    releaseDate: '2018-01-01',
    length: 100,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'The Mortuary',
    director: 'Ryan Spindell',
    actors: [
      { name: 'Clancy Brown' },
      { name: 'Caitlin Custer' },
      { name: 'Christine Kilmer' },
      { name: 'Jacob Elordi' },
    ],
    coverUrl: '/movies_pictures/bcfff1f57081.jpg',
    releaseDate: '2020-01-01',
    length: 108,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Escape Room',
    director: 'Adam Robitel',
    actors: [
      { name: 'Taylor Russell' },
      { name: 'Logan Miller' },
      { name: 'Deborah Ann Woll' },
      { name: 'Jay Ellis' },
    ],
    coverUrl: '/movies_pictures/d9a82017ce67.jpg',
    releaseDate: '2017-01-01',
    length: 99,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Final Girl',
    director: 'Tyler Shields',
    actors: [
      { name: 'Abigail Breslin' },
      { name: 'Alexander Ludwig' },
      { name: 'Wes Bentley' },
      { name: 'Logan Huffman' },
    ],
    coverUrl: '/movies_pictures/5c2a9d9f267d.jpg',
    releaseDate: '2015-01-01',
    length: 90,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },

  /* Barbie 2001–2011 */

  /* Liste 2 – Autres films */
  {
    title: 'The Ugly Stepsister',
    director: 'Emilie Blichfeldt',
    actors: [
      { name: "Sofia Black-D'Elia" },
      { name: 'Sara Amini' },
      { name: 'Danielle Macdonald' },
      { name: 'Rebecca Henderson' },
    ],
    coverUrl: '/movies_pictures/a5001b7847bb.jpg',
    releaseDate: '2025-01-01',
    length: 95,
    genre: ['Drame'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Le cas 39',
    director: 'Christian Alvart',
    actors: [
      { name: 'Renée Zellweger' },
      { name: 'Jodelle Ferland' },
      { name: 'Ian McShane' },
      { name: 'Bradley Cooper' },
    ],
    coverUrl: '/movies_pictures/65a2b0895afd.jpg',
    releaseDate: '2009-01-01',
    length: 109,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Tin et Tina',
    director: 'Rubin Stein',
    actors: [
      { name: 'Jaime Lorente' },
      { name: 'Milena Smit' },
      { name: 'Carlos Santos' },
      { name: 'Teresa Rabal' },
    ],
    coverUrl: '/movies_pictures/24eb8a247381.jpg',
    releaseDate: '2023-01-01',
    length: 117,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['Espagne'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Run Rabbit Run',
    director: 'Daina Reid',
    actors: [
      { name: 'Sarah Snook' },
      { name: 'Lily LaTorre' },
      { name: 'Damon Herriman' },
      { name: 'Neil Melville' },
    ],
    coverUrl: '/movies_pictures/e633abdbe2a4.jpg',
    releaseDate: '2023-01-01',
    length: 100,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['Australie'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Eli',
    director: 'Ciarán Foy',
    actors: [
      { name: 'Charlie Shotwell' },
      { name: 'Kelly Reilly' },
      { name: 'Lili Taylor' },
      { name: 'Max Martini' },
    ],
    coverUrl: '/movies_pictures/b0ff17605bce.jpg',
    releaseDate: '2019-01-01',
    length: 98,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Autant en emporte le vent',
    director: 'Victor Fleming',
    actors: [
      { name: 'Vivien Leigh' },
      { name: 'Clark Gable' },
      { name: 'Olivia de Havilland' },
      { name: 'Leslie Howard' },
    ],
    coverUrl: '/movies_pictures/a9b1f1afbc30.jpg',
    releaseDate: '1939-01-01',
    length: 238,
    genre: ['Drame'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Barbare',
    director: 'Zach Cregger',
    actors: [
      { name: 'Georgina Campbell' },
      { name: 'Bill Skarsgård' },
      { name: 'Justin Long' },
      { name: 'Matthew Patrick Davis' },
    ],
    coverUrl: '/movies_pictures/7086cfc2645d.jpg',
    releaseDate: '2002-01-01',
    length: 102,
    genre: ['Drame'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Le coup du siècle',
    director: 'Chris Addison',
    actors: [
      { name: 'Anne Hathaway' },
      { name: 'Rebel Wilson' },
      { name: 'Alex Sharp' },
      { name: 'Ingrid Oliver' },
    ],
    coverUrl: '/movies_pictures/621d08062b84.jpg',
    releaseDate: '2019-01-01',
    length: 93,
    genre: ['Comédie'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['Royaume-Uni'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Us',
    director: 'Jordan Peele',
    actors: [
      { name: "Lupita Nyong'o" },
      { name: 'Winston Duke' },
      { name: 'Elisabeth Moss' },
      { name: 'Tim Heidecker' },
    ],
    coverUrl: '/movies_pictures/5e0de4e5772d.jpg',
    releaseDate: '2019-01-01',
    length: 116,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Les guetteurs',
    director: 'Ishana Shyamalan',
    actors: [
      { name: 'Dakota Fanning' },
      { name: 'Georgina Campbell' },
      { name: 'Olwen Fouéré' },
      { name: 'Alistair Brammer' },
    ],
    coverUrl: '/movies_pictures/8938b7839604.jpg',
    releaseDate: '2024-01-01',
    length: 102,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Midsommar',
    director: 'Ari Aster',
    actors: [
      { name: 'Florence Pugh' },
      { name: 'Jack Reynor' },
      { name: 'Will Poulter' },
      { name: 'William Jackson Harper' },
    ],
    coverUrl: '/movies_pictures/b1989bcbc8f3.jpg',
    releaseDate: '2019-01-01',
    length: 140,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'I See You',
    director: 'Adam Randall',
    actors: [
      { name: 'Helen Hunt' },
      { name: 'Jon Tenney' },
      { name: 'Judah Lewis' },
      { name: 'Libe Barer' },
    ],
    coverUrl: '/movies_pictures/017583c9b42f.jpg',
    releaseDate: '2019-01-01',
    length: 99,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },

  /* Liste 4 – Thrillers / divers */
  {
    title: 'Le monde de John',
    director: 'Pascual Sisto',
    actors: [
      { name: 'Charlie Shotwell' },
      { name: 'Taissa Farmiga' },
      { name: 'Michael C. Hall' },
      { name: 'Jennifer Ehle' },
    ],
    coverUrl: '/movies_pictures/256d5a138b87.jpg',
    releaseDate: '2022-01-01',
    length: 95,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Baba Yaga',
    director: 'Caradog W. James',
    actors: [
      { name: 'Niamh Algar' },
      { name: 'Jay O. Sanders' },
      { name: 'Noemie Merlant' },
      { name: 'Alec Secareanu' },
    ],
    coverUrl: '/movies_pictures/f95b1833e52f.jpg',
    releaseDate: '2017-01-01',
    length: 89,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Dans les angles morts',
    director: 'Shari Springer Berman, Robert Pulcini',
    actors: [
      { name: 'Isabelle Huppert' },
      { name: 'Chloë Grace Moretz' },
      { name: 'Callan McAuliffe' },
      { name: 'Maika Monroe' },
    ],
    coverUrl: '/movies_pictures/3d7c6b08c5c4.jpg',
    releaseDate: '2021-01-01',
    length: 95,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Identity',
    director: 'James Mangold',
    actors: [
      { name: 'John Cusack' },
      { name: 'Ray Liotta' },
      { name: 'Amanda Peet' },
      { name: 'John Hawkes' },
    ],
    coverUrl: '/movies_pictures/805408d7dd8d.jpg',
    releaseDate: '2003-01-01',
    length: 90,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Jeu intérieur',
    director: 'Greg Jardin',
    actors: [
      { name: 'Gillian Jacobs' },
      { name: 'John Gallagher Jr.' },
      { name: 'Azhy Robertson' },
      { name: 'Winslow Fegley' },
    ],
    coverUrl: '/movies_pictures/3bc92a3d4c72.jpg',
    releaseDate: '2024-01-01',
    length: 98,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Re Member',
    director: 'Eiichirō Hasumi',
    actors: [
      { name: 'Kanna Hashimoto' },
      { name: 'Win Morisaki' },
      { name: 'Minami Hamabe' },
      { name: 'Sota Fukushi' },
    ],
    coverUrl: '/movies_pictures/38b0fc6b8a9d.jpg',
    releaseDate: '2022-01-01',
    length: 102,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: "Ne t'endors pas",
    director: 'Mike Flanagan',
    actors: [
      { name: 'Kate Bosworth' },
      { name: 'Thomas Jane' },
      { name: 'Jacob Tremblay' },
      { name: 'Annabeth Gish' },
    ],
    coverUrl: '/movies_pictures/45a33c48943c.jpg',
    releaseDate: '2016-01-01',
    length: 97,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: "Don't Worry Darling",
    director: 'Olivia Wilde',
    actors: [
      { name: 'Florence Pugh' },
      { name: 'Harry Styles' },
      { name: 'Chris Pine' },
      { name: 'Olivia Wilde' },
    ],
    coverUrl: '/movies_pictures/e929d5e34dfe.jpg',
    releaseDate: '2022-01-01',
    length: 122,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Les couleurs du mal Rouge',
    director: 'Adrian Panek',
    actors: [
      { name: 'Thomas Schubert' },
      { name: 'Paula Beer' },
      { name: 'Enno Trebs' },
      { name: 'Langston Uibel' },
    ],
    coverUrl: '/movies_pictures/e929d5e34dfe.jpg',
    releaseDate: '2024-01-01',
    length: 111,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'The Privilege',
    director: 'Felix Fuchssteiner',
    actors: [
      { name: 'Max Schimmelpfennig' },
      { name: 'Lea van Acken' },
      { name: 'Roman Knizka' },
      { name: 'Daniel Holzberg' },
    ],
    coverUrl: '/movies_pictures/78d60976a1eb.jpg',
    releaseDate: '2022-01-01',
    length: 102,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Séminaire',
    director: 'Patrik Eklund',
    actors: [
      { name: 'Katia Winter' },
      { name: 'Amed Bozan' },
      { name: 'Eva Melander' },
      { name: 'Peter Eggers' },
    ],
    coverUrl: '/movies_pictures/3e16a1a46ddb.jpg',
    releaseDate: '2023-01-01',
    length: 100,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: "N'écoute pas",
    director: 'Ángel Gómez Hernández',
    actors: [
      { name: 'Mario Casas' },
      { name: 'Milena Smit' },
      { name: 'José Coronado' },
      { name: 'Ana Wagener' },
    ],
    coverUrl: '/movies_pictures/de85335d88bf.jpg',
    releaseDate: '2020-01-01',
    length: 98,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Creep',
    director: 'Patrick Brice',
    actors: [{ name: 'Mark Duplass' }, { name: 'Patrick Brice' }],
    coverUrl: '/movies_pictures/2a399b569f61.jpg',
    releaseDate: '2014-01-01',
    length: 77,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Hypnotique',
    director: 'Matt Angel, Suzanne Coote',
    actors: [
      { name: 'Kate Siegel' },
      { name: "Jason O'Mara" },
      { name: 'Dulé Hill' },
      { name: 'Jaime M. Callica' },
    ],
    coverUrl: '/movies_pictures/f496aa82d428.jpg',
    releaseDate: '2021-01-01',
    length: 88,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: "Don't Move",
    director: 'Adam Schindler, Brian Netto',
    actors: [
      { name: 'Finn Wittrock' },
      { name: 'Katherine McNamara' },
      { name: 'Patrick Schwarzenegger' },
      { name: 'Wendy Moniz' },
    ],
    coverUrl: '/movies_pictures/218ba2e93436.jpg',
    releaseDate: '2024-01-01',
    length: 90,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'La prison de verre',
    director: 'Daniel Sackheim',
    actors: [
      { name: 'Leelee Sobieski' },
      { name: 'Diane Lane' },
      { name: 'Stellan Skarsgård' },
      { name: 'Trevor Morgan' },
    ],
    coverUrl: '/movies_pictures/4d94d28212e4.jpg',
    releaseDate: '2001-01-01',
    length: 106,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Locked In',
    director: 'Carl Tibbetts',
    actors: [
      { name: 'Rose Williams' },
      { name: 'Alex Hassell' },
      { name: 'Famke Janssen' },
      { name: 'Anna Friel' },
    ],
    coverUrl: '/movies_pictures/0e80f4200dc5.jpg',
    releaseDate: '2023-01-01',
    length: 97,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['Royaume-Uni'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Brick',
    director: 'Rian Johnson',
    actors: [
      { name: 'Joseph Gordon-Levitt' },
      { name: 'Nora Zehetner' },
      { name: 'Lukas Haas' },
      { name: 'Emilie de Ravin' },
    ],
    coverUrl: '/movies_pictures/caa4286253c4.jpg',
    releaseDate: '2005-01-01',
    length: 110,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Irrémédiable',
    director: 'Carles Torras',
    actors: [
      { name: 'Laia Costa' },
      { name: 'Luis Tosar' },
      { name: 'Zorion Eguileor' },
      { name: 'Gorka Otxoa' },
    ],
    coverUrl: '/movies_pictures/40d5bf72ddd6.jpg',
    releaseDate: '2020-01-01',
    length: 88,
    genre: ['Drame'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Chez moi',
    director: 'David Pastor',
    actors: [
      { name: 'David Verdaguer' },
      { name: 'Bruna Cusí' },
      { name: 'Vicky Luengo' },
      { name: 'Pablo Derqui' },
    ],
    coverUrl: '/movies_pictures/fedea54fb058.jpg',
    releaseDate: '2020-01-01',
    length: 95,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Wounds',
    director: 'Babak Anvari',
    actors: [
      { name: 'Armie Hammer' },
      { name: 'Dakota Johnson' },
      { name: 'Zazie Beetz' },
      { name: 'Karl Glusman' },
    ],
    coverUrl: '/movies_pictures/d531eff43fe2.jpg',
    releaseDate: '2019-01-01',
    length: 95,
    genre: ['Horreur'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'The Perfection',
    director: 'Richard Shepard',
    actors: [
      { name: 'Allison Williams' },
      { name: 'Logan Browning' },
      { name: 'Steven Weber' },
      { name: 'Alaina Meyer' },
    ],
    coverUrl: '/movies_pictures/20769b471295.jpg',
    releaseDate: '2019-01-01',
    length: 90,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Eileen',
    director: 'William Oldroyd',
    actors: [
      { name: 'Thomasin McKenzie' },
      { name: 'Anne Hathaway' },
      { name: 'Shea Whigham' },
      { name: 'Marin Ireland' },
    ],
    coverUrl: '/movies_pictures/b8bbcd8f5e82.jpg',
    releaseDate: '2023-01-01',
    length: 97,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Escape Game 2',
    director: 'Adam Robitel',
    actors: [
      { name: 'Taylor Russell' },
      { name: 'Logan Miller' },
      { name: 'Indya Moore' },
      { name: 'Holland Roden' },
    ],
    coverUrl: '/movies_pictures/6f6aa1cc5b0a.jpg',
    releaseDate: '2021-01-01',
    length: 88,
    genre: ['Thriller'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Ma sorcière bien aimée',
    director: 'Nora Ephron',
    actors: [
      { name: 'Nicole Kidman' },
      { name: 'Will Ferrell' },
      { name: 'Michael Caine' },
      { name: 'Shirley MacLaine' },
    ],
    coverUrl: '/movies_pictures/3656abaf6c93.jpg',
    releaseDate: '2005-01-01',
    length: 102,
    genre: ['Comédie'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },

  {
    title: 'Le magasin des suicides',
    director: 'Patrice Leconte',
    actors: [
      { name: 'Bernard Alane' },
      { name: 'Kacey Mottet Klein' },
      { name: 'Isabelle Gélinas' },
      { name: 'François Morel' },
    ],
    coverUrl: '/movies_pictures/41df16ed6e6b.jpg',
    releaseDate: '2012-01-01',
    length: 79,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Charlie et la Chocolaterie',
    director: 'Mel Stuart',
    actors: [
      { name: 'Gene Wilder' },
      { name: 'Jack Albertson' },
      { name: 'Peter Ostrum' },
      { name: 'Roy Kinnear' },
    ],
    coverUrl: '/movies_pictures/761aca29f06f.jpg',
    releaseDate: '1971-01-01',
    length: 100,
    genre: ['Jeunesse'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },

  {
    title: 'Camp Rock',
    director: 'Matthew Diamond',
    actors: [
      { name: 'Demi Lovato' },
      { name: 'Joe Jonas' },
      { name: 'Nick Jonas' },
      { name: 'Kevin Jonas' },
    ],
    coverUrl: '/movies_pictures/1bbe71712521.jpg',
    releaseDate: '2008-01-01',
    length: 94,
    genre: ['Comédie musicale'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
  {
    title: 'Camp Rock 2',
    director: 'Paul Hoen',
    actors: [
      { name: 'Demi Lovato' },
      { name: 'Joe Jonas' },
      { name: 'Nick Jonas' },
      { name: 'Kevin Jonas' },
    ],
    coverUrl: '/movies_pictures/3c2b8f3bd281.jpg',
    releaseDate: '2010-01-01',
    length: 104,
    genre: ['Comédie musicale'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
  },
];
