import { BaseMovie, OscarEnum } from '../../../models/movie-model';

/**
 * Films manquants — années 2010-2014. Années entre parenthèses absentes des titres.
 * coverUrl laissé vide.
 */
export const baseMoviesMissingAnnees20102014: BaseMovie[] = [
  {
    title: 'Animal Kingdom',
    director: 'David Michôd',
    actors: [
      { name: 'James Frecheville' },
      { name: 'Ben Mendelsohn' },
      { name: 'Guy Pearce' },
      { name: 'Jacki Weaver' },
      { name: 'Joel Edgerton' },
    ],
    coverUrl: '/movies_pictures/e49186dba1e2.jpg',
    releaseDate: '2010-06-03',
    length: 113,
    genre: ['Policier', 'Thriller', 'Drame'],
    saga: '',
    description:
      'Animal Kingdom, ou La Loi du plus fort au Québec, est un film policier australien écrit et réalisé par David Michôd, sorti en 2010.',
    fromEntity: null,
    countryOrigin: ['Australie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Another Year',
    director: 'Mike Leigh',
    actors: [
      { name: 'Jim Broadbent' },
      { name: 'Ruth Sheen' },
      { name: 'Lesley Manville' },
      { name: 'Oliver Maltman' },
      { name: 'Peter Wight' },
    ],
    coverUrl: '/movies_pictures/7ee4e5f87a48.jpg',
    releaseDate: '2010-11-05',
    length: 129,
    genre: ['Drame', 'Comédie'],
    saga: '',
    description:
      'Another Year est un film britannique du réalisateur Mike Leigh, sorti en 2010.',
    fromEntity: null,
    countryOrigin: ['Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Biutiful',
    director: 'Alejandro González Iñárritu',
    actors: [
      { name: 'Javier Bardem' },
      { name: 'Maricel Álvarez' },
      { name: 'Hanaa Bouchaib' },
      { name: 'Guillermo Estrella' },
      { name: 'Diaryatou Daff' },
    ],
    coverUrl: '/movies_pictures/199398be65c6.jpg',
    releaseDate: '2010-10-20',
    length: 148,
    genre: ['Drame'],
    saga: '',
    description:
      'Biutiful est un film mexicano-espagnol réalisé par Alejandro González Iñárritu, sorti en 2010.',
    fromEntity: null,
    countryOrigin: ['Mexique', 'Espagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Blue Valentine',
    director: 'Derek Cianfrance',
    actors: [
      { name: 'Ryan Gosling' },
      { name: 'Michelle Williams' },
      { name: 'Faith Wladyka' },
      { name: 'John Doman' },
      { name: 'Mike Vogel' },
    ],
    coverUrl: '/movies_pictures/7fa960303022.jpg',
    releaseDate: '2010-12-29',
    length: 112,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      "Blue Valentine, ou Blue Valentine : Une histoire d'amour au Québec, est un film dramatique américain, réalisé par Derek Cianfrance en 2010.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Canine',
    director: 'Yorgos Lanthimos',
    actors: [
      { name: 'Christos Stergioglou' },
      { name: 'Michele Valley' },
      { name: 'Angeliki Papoulia' },
      { name: 'Mary Tsoni' },
      { name: 'Christos Passalis' },
    ],
    coverUrl:
      'https://cinedweller.com/movie/canine-la-critique-du-film/potemkine-canine-dvd/',
    releaseDate: '2009-10-23',
    length: 94,
    genre: ['Drame'],
    saga: '',
    description:
      'Canine est un drame psychologique grec co-écrit et réalisé par Yórgos Lánthimos, sorti en 2009.',
    fromEntity: null,
    countryOrigin: ['Grèce'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Carlos',
    director: 'Olivier Assayas',
    actors: [
      { name: 'Édgar Ramírez' },
      { name: 'Alexander Scheer' },
      { name: 'Nora von Waldstätten' },
      { name: 'Christoph Bach' },
      { name: 'Ahmad Kaabour' },
    ],
    coverUrl:
      '/movies_pictures/f0b8477d186b.jpg',
    releaseDate: '2010-10-11',
    length: 339,
    genre: ['Drame', 'Biographie', 'Thriller'],
    saga: '',
    description:
      "Biopic en trois parties sur Ilich Ramírez Sánchez, dit Carlos, terroriste international des années 1970-90, de ses attentats à sa traque jusqu'à son arrestation.",
    fromEntity: null,
    countryOrigin: ['France', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Conviction',
    director: 'Tony Goldwyn',
    actors: [
      { name: 'Hilary Swank' },
      { name: 'Sam Rockwell' },
      { name: 'Minnie Driver' },
      { name: 'Melissa Leo' },
      { name: 'Peter Gallagher' },
    ],
    coverUrl: '/movies_pictures/7e4f503863ed.jpg',
    releaseDate: '2010-10-15',
    length: 107,
    genre: ['Drame', 'Biographie'],
    saga: '',
    description:
      "Betty Anne Waters, serveuse devenue avocate, passe près de vingt ans à prouver l'innocence de son frère condamné à perpétuité pour meurtre.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Copacabana',
    director: 'Marc Fitoussi',
    actors: [
      { name: 'Isabelle Huppert' },
      { name: 'Aure Atika' },
      { name: 'Lolita Chammah' },
      { name: 'Jurgen Buchsberger' },
      { name: 'Luis Rego' },
    ],
    coverUrl: '/movies_pictures/feed51c7bcc0.jpg',
    releaseDate: '2010-07-07',
    length: 107,
    genre: ['Comédie', 'Drame'],
    saga: '',
    description:
      'Babou, mère célibataire au bord du gouffre, se retrouve guide pour un voyage organisé à Copacabana et tente de reprendre pied.',
    fromEntity: null,
    countryOrigin: ['France', 'Belgique'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Copie conforme',
    director: 'Abbas Kiarostami',
    actors: [
      { name: 'Juliette Binoche' },
      { name: 'William Shimell' },
      { name: 'Jean-Claude Carrière' },
      { name: 'Agathe Natanson' },
      { name: 'Gianna Giachetti' },
    ],
    coverUrl: '/movies_pictures/bba674ca93c5.jpg',
    releaseDate: '2010-05-18',
    length: 106,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      'Un écrivain britannique et une Française se rencontrent en Toscane ; leur journée oscille entre séduction, jeu de rôles et crise de couple.',
    fromEntity: null,
    countryOrigin: ['France', 'Italie', 'Belgique'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Des hommes et des dieux',
    director: 'Xavier Beauvois',
    actors: [
      { name: 'Lambert Wilson' },
      { name: 'Michael Lonsdale' },
      { name: 'Olivier Rabourdin' },
      { name: 'Philippe Laudenbach' },
      { name: 'Jacques Herlin' },
    ],
    coverUrl: '/movies_pictures/e05d592a832e.jpg',
    releaseDate: '2010-09-08',
    length: 122,
    genre: ['Drame', 'Historique', 'Biographie'],
    saga: '',
    description:
      'Dans un monastère cistercien en Algérie, huit moines français doivent choisir entre rester auprès des villageois ou fuir face à la menace islamiste.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Enter the Void',
    director: 'Gaspar Noé',
    actors: [
      { name: 'Nathaniel Brown' },
      { name: 'Paz de la Huerta' },
      { name: 'Cyril Roy' },
      { name: 'Olly Alexander' },
      { name: 'Masato Tanno' },
    ],
    coverUrl: '/movies_pictures/d8b1cf212792.jpg',
    releaseDate: '2010-05-12',
    length: 161,
    genre: ['Drame', 'Fantastique'],
    saga: '',
    description:
      "À Tokyo, un jeune dealer tué par la police revit sa vie et celle de sa sœur sous forme d'esprit errant, dans un trip visuel halluciné.",
    fromEntity: null,
    countryOrigin: ['France', 'Allemagne', 'Italie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Fair Game',
    director: 'Doug Liman',
    actors: [
      { name: 'Naomi Watts' },
      { name: 'Sean Penn' },
      { name: 'Sonya Walger' },
      { name: 'Noah Emmerich' },
      { name: 'Ty Burrell' },
    ],
    coverUrl: '/movies_pictures/be4c945fe017.jpg',
    releaseDate: '2010-10-01',
    length: 108,
    genre: ['Thriller', 'Drame', 'Biographie'],
    saga: '',
    description:
      "L'agente de la CIA Valerie Plame voit son identité révélée après que son mari ait contesté les justificatifs de la guerre en Irak.",
    fromEntity: {
      entityType: 'book',
      title: 'Fair Game',
      secondEntityKey: 'Valerie Plame',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Gainsbourg (Vie héroïque)',
    director: 'Joann Sfar',
    actors: [
      { name: 'Eric Elmosnino' },
      { name: 'Laetitia Casta' },
      { name: 'Lucy Gordon' },
      { name: 'Doug Jones' },
      { name: 'Anna Mouglalis' },
    ],
    coverUrl: '/movies_pictures/04f651379918.jpg',
    releaseDate: '2010-01-20',
    length: 135,
    genre: ['Drame', 'Biographie', 'Comédie musicale'],
    saga: '',
    description:
      "Portrait fantasmé de Serge Gainsbourg, de son enfance à Paris jusqu'à la gloire sulfureuse, peuplé de doubles et de démons intérieurs.",
    fromEntity: {
      entityType: 'bd',
      title: 'Gainsbourg',
      secondEntityKey: 'Joann Sfar',
    },
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Hors-la-loi',
    director: 'Rachid Bouchareb',
    actors: [
      { name: 'Jamel Debbouze' },
      { name: 'Roschdy Zem' },
      { name: 'Sami Bouajila' },
      { name: 'Chafia Boudraa' },
      { name: 'Bernard Blancan' },
    ],
    coverUrl: '/movies_pictures/cd58e0a94f20.jpg',
    releaseDate: '2010-09-21',
    length: 138,
    genre: ['Drame', 'Guerre', 'Historique', 'Policier'],
    saga: '',
    description:
      "Trois frères algériens émigrés en France après le massacre de Sétif s'engagent, chacun à sa manière, dans la lutte pour l'indépendance.",
    fromEntity: null,
    countryOrigin: ['France', 'Algérie', 'Belgique'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Immortel",
    director: 'Richard Berry',
    actors: [
      { name: 'Jean Reno' },
      { name: 'Kad Merad' },
      { name: 'Marina Foïs' },
      { name: 'Jean-Pierre Darroussin' },
      { name: 'Joey Starr' },
    ],
    coverUrl: '/movies_pictures/ac34bc4efa13.jpg',
    releaseDate: '2010-03-24',
    length: 93,
    genre: ['Policier', 'Action', 'Thriller'],
    saga: '',
    description:
      'Charly Matteï, ancien caïd marseillais sorti de prison, retrouve une ville changée et doit affronter ceux qui veulent sa peau.',
    fromEntity: {
      entityType: 'book',
      title: "L'Immortel",
      secondEntityKey: 'Franz-Olivier Giesbert',
    },
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Tête en friche',
    director: 'Jean Becker',
    actors: [
      { name: 'Gérard Depardieu' },
      { name: 'Gisèle Casadesus' },
      { name: 'Maurane' },
      { name: 'François-Xavier Demaison' },
      { name: 'Claire Maurier' },
    ],
    coverUrl: '/movies_pictures/044324ec63c9.jpg',
    releaseDate: '2010-03-03',
    length: 82,
    genre: ['Drame', 'Comédie'],
    saga: '',
    description:
      "Germain, cinquantenaire analphabète, se lie d'amitié avec Margueritte, une vieille dame qui lui fait découvrir la lecture sur un banc public.",
    fromEntity: {
      entityType: 'book',
      title: 'La Tête en friche',
      secondEntityKey: 'Marie-Sabine Roger',
    },
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Mammuth',
    director: 'Benoît Delépine',
    actors: [
      { name: 'Gérard Depardieu' },
      { name: 'Yolande Moreau' },
      { name: 'Isabelle Adjani' },
      { name: 'Miss Ming' },
      { name: 'Bouli Lanners' },
    ],
    coverUrl:
      'https://medias.unifrance.org/medias/88/170/43608/format_page/mammuth.jpg',
    releaseDate: '2010-04-21',
    length: 91,
    genre: ['Comédie', 'Drame'],
    saga: '',
    description:
      "À la retraite, un ancien ouvrier traverse la France à moto pour récupérer des bulletins de salaire manquants et croise un passé qu'il croyait oublié.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Never Let Me Go',
    director: 'Mark Romanek',
    actors: [
      { name: 'Carey Mulligan' },
      { name: 'Keira Knightley' },
      { name: 'Andrew Garfield' },
      { name: 'Charlotte Rampling' },
      { name: 'Sally Hawkins' },
    ],
    coverUrl: '/movies_pictures/faac9f1de05f.jpg',
    releaseDate: '2010-10-15',
    length: 103,
    genre: ['Drame', 'Science Fiction', 'Romance'],
    saga: '',
    description:
      "Trois amis élevés dans un internat anglais découvrent qu'ils sont des clones destinés à donner leurs organes, et tentent d'échapper à leur sort.",
    fromEntity: {
      entityType: 'book',
      title: 'Never Let Me Go',
      secondEntityKey: 'Kazuo Ishiguro',
    },
    countryOrigin: ['Royaume-Uni', 'États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Nowhere Boy',
    director: 'Sam Taylor-Johnson',
    actors: [
      { name: 'Aaron Taylor-Johnson' },
      { name: 'Kristin Scott Thomas' },
      { name: 'Anne-Marie Duff' },
      { name: 'Thomas Sangster' },
      { name: 'David Morrissey' },
    ],
    coverUrl: '/movies_pictures/37ec053a8bc8.jpg',
    releaseDate: '2009-12-26',
    length: 98,
    genre: ['Drame', 'Biographie', 'Comédie musicale'],
    saga: '',
    description:
      "Nowhere Boy is a 2009 British biographical drama film, directed by Sam Taylor-Johnson in her directorial debut. Written by Matt Greenhalgh, it is based on Julia Baird's biography of her half-brother, the musician John Lennon.",
    fromEntity: null,
    countryOrigin: ['Royaume-Uni', 'Canada'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Oncle Boonmee',
    director: 'Apichatpong Weerasethakul',
    actors: [
      { name: 'Thanapat Saisaymar' },
      { name: 'Jenjira Pongpas' },
      { name: 'Sakda Kaewbuadee' },
      { name: 'Natthakarn Aphaiwonk' },
      { name: 'Geerasak Kulhong' },
    ],
    coverUrl: '/movies_pictures/3037bf88572e.jpeg',
    releaseDate: '2010-05-21',
    length: 114,
    genre: ['Drame', 'Fantastique'],
    saga: '',
    description:
      "Dans la campagne thaïlandaise, un homme malade reçoit la visite de parents défunts et d'êtres surnaturels alors que sa fin approche.",
    fromEntity: null,
    countryOrigin: ['Thaïlande', 'Royaume-Uni', 'France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Poetry',
    director: 'Lee Chang-dong',
    actors: [
      { name: 'Yoon Jeong-hee' },
      { name: 'Lee David' },
      { name: 'Kim Hira' },
      { name: 'Ahn Nae-sang' },
      { name: 'Kim Yong-taek' },
    ],
    coverUrl:
      'https://resizing.flixster.com/1G3nD43dJ8isGbMJqm0MHj4FGyk=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2NiZTQ4MmYyLWY2NTUtNGZjOC04ZmY5LTlkZjhkMDliYWFlOC5qcGc=',
    releaseDate: '2010-05-13',
    length: 139,
    genre: ['Drame'],
    saga: '',
    description:
      "Les archives du film coréen ou Korea Film Archive, aussi appelées fédération coréenne des archives du film, est la seule cinémathèque de Corée du Sud bénéficiant d'une couverture nationale.",
    fromEntity: null,
    countryOrigin: ['Corée du Sud'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Potiche',
    director: 'François Ozon',
    actors: [
      { name: 'Catherine Deneuve' },
      { name: 'Gérard Depardieu' },
      { name: 'Fabrice Luchini' },
      { name: 'Karin Viard' },
      { name: 'Judith Godrèche' },
    ],
    coverUrl: '/movies_pictures/91a6d220e728.jpg',
    releaseDate: '2010-11-10',
    length: 103,
    genre: ['Comédie'],
    saga: '',
    description:
      "Dans les années 1970, une épouse de patron d'usine jusque-là invisible prend les rênes de l'entreprise pendant la grève et s'émancipe.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Rabbit Hole',
    director: 'John Cameron Mitchell',
    actors: [
      { name: 'Nicole Kidman' },
      { name: 'Aaron Eckhart' },
      { name: 'Dianne Wiest' },
      { name: 'Miles Teller' },
      { name: 'Tammy Blanchard' },
    ],
    coverUrl: '/movies_pictures/acb0f2e8caec.jpg',
    releaseDate: '2010-12-17',
    length: 91,
    genre: ['Drame'],
    saga: '',
    description:
      'Un couple tente de survivre au deuil de leur fils, entre thérapie de groupe, non-dits et rencontre troublante avec le jeune conducteur responsable.',
    fromEntity: {
      entityType: 'book',
      title: 'Rabbit Hole',
      secondEntityKey: 'David Lindsay-Abaire',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Debt',
    director: 'John Madden',
    actors: [
      { name: 'Helen Mirren' },
      { name: 'Sam Worthington' },
      { name: 'Jessica Chastain' },
      { name: 'Tom Wilkinson' },
      { name: 'Ciarán Hinds' },
    ],
    coverUrl:
      '/movies_pictures/eae59e4d785d.jpg',
    releaseDate: '2010-08-31',
    length: 113,
    genre: ['Thriller', 'Drame'],
    saga: '',
    description:
      'Trois agents du Mossad, après une mission secrète pour capturer un nazi, doivent confronter des décennies plus tard le mensonge qui a fondé leur légende.',
    fromEntity: {
      entityType: 'book',
      title: 'Rabbit Hole',
      secondEntityKey: 'David Lindsay-Abaire',
    },
    countryOrigin: ['États-Unis', 'Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Trois Prochains Jours',
    director: 'Paul Haggis',
    actors: [
      { name: 'Russell Crowe' },
      { name: 'Elizabeth Banks' },
      { name: 'Liam Neeson' },
      { name: 'Brian Dennehy' },
      { name: 'Olivia Wilde' },
    ],
    coverUrl: '/movies_pictures/a2c2485c3af7.jpg',
    releaseDate: '2010-11-19',
    length: 133,
    genre: ['Thriller', 'Drame', 'Action'],
    saga: '',
    description:
      "Un professeur prépare l'évasion de sa femme condamnée à perpétuité pour un meurtre qu'elle nie, avec l'aide de son frère ex-flic.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Runaways',
    director: 'Floria Sigismondi',
    actors: [
      { name: 'Kristen Stewart' },
      { name: 'Dakota Fanning' },
      { name: 'Michael Shannon' },
      { name: 'Stella Maeve' },
      { name: 'Scout Taylor-Compton' },
    ],
    coverUrl: '/movies_pictures/f691bc845485.jpg',
    releaseDate: '2010-03-19',
    length: 106,
    genre: ['Drame', 'Biographie', 'Comédie musicale'],
    saga: '',
    description:
      "Ascension et chute du groupe de rock The Runaways, vu à travers l'amitié explosive entre Joan Jett et Cherie Currie.",
    fromEntity: {
      entityType: 'book',
      title: 'Neon Angel',
      secondEntityKey: 'Cherie Currie',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Tournée',
    director: 'Mathieu Amalric',
    actors: [
      { name: 'Mathieu Amalric' },
      { name: 'Miranda Colclasure' },
      { name: 'Dirty Martini' },
      { name: 'Mimi Le Meaux' },
      { name: 'Kitten on the Keys' },
    ],
    coverUrl: '/movies_pictures/8a803e8aead2.jpg',
    releaseDate: '2010-07-07',
    length: 111,
    genre: ['Drame', 'Comédie'],
    saga: '',
    description:
      'Un producteur français ramène en tournée des showgirls américaines de burlesque à travers les salles de province, entre rêve et déclin.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Unstoppable',
    director: 'Tony Scott',
    actors: [
      { name: 'Denzel Washington' },
      { name: 'Chris Pine' },
      { name: 'Rosario Dawson' },
      { name: 'Ethan Suplee' },
      { name: 'Kevin Dunn' },
    ],
    coverUrl: '/movies_pictures/9b05b833a331.jpg',
    releaseDate: '2010-11-12',
    length: 98,
    genre: ['Action', 'Thriller', 'Catastrophe'],
    saga: '',
    description:
      "Deux cheminots tentent d'arrêter un train de marchandises sans conducteur chargé de produits toxiques qui fonce vers une zone peuplée.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Carnage',
    director: 'Roman Polanski',
    actors: [
      { name: 'Jodie Foster' },
      { name: 'Kate Winslet' },
      { name: 'Christoph Waltz' },
      { name: 'John C. Reilly' },
      { name: 'Elvis Polanski' },
    ],
    coverUrl: '/movies_pictures/e5c6013ec293.jpg',
    releaseDate: '2011-12-07',
    length: 80,
    genre: ['Comédie', 'Drame'],
    saga: '',
    description:
      "Après une bagarre entre leurs fils, deux couples bourgeois new-yorkais tentent de régler le conflit civilisé… et s'entre-déchirent.",
    fromEntity: {
      entityType: 'book',
      title: 'Le Dieu du carnage',
      secondEntityKey: 'Yasmina Reza',
    },
    countryOrigin: ['France', 'Allemagne', 'Pologne', 'Espagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Apollonide : Souvenirs de la maison close",
    director: 'Bertrand Bonello',
    actors: [
      { name: 'Hafsia Herzi' },
      { name: 'Céline Sallette' },
      { name: 'Jasmine Trinca' },
      { name: 'Adèle Haenel' },
      { name: 'Alice Barnole' },
    ],
    coverUrl: '/movies_pictures/6943f11a25b7.jpg',
    releaseDate: '2011-09-21',
    length: 122,
    genre: ['Drame', 'Historique'],
    saga: '',
    description:
      "Au début du XXe siècle, la vie quotidienne d'une maison close parisienne, entre sororité, exploitation et fin d'une époque.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Exercice de l'État",
    director: 'Pierre Schoeller',
    actors: [
      { name: 'Olivier Gourmet' },
      { name: 'Michel Blanc' },
      { name: 'Zabou Breitman' },
      { name: 'Laurent Stocker' },
      { name: 'Sylvain Deblé' },
    ],
    coverUrl: '/movies_pictures/ad22f586f432.jpg',
    releaseDate: '2011-10-26',
    length: 115,
    genre: ['Drame'],
    saga: '',
    description:
      "Immersion dans le quotidien d'un ministre des Transports français, entre crises, cabinets et solitude du pouvoir.",
    fromEntity: null,
    countryOrigin: ['France', 'Belgique'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Conquête',
    director: 'Xavier Durringer',
    actors: [
      { name: 'Denis Podalydès' },
      { name: 'Florence Pernel' },
      { name: 'Bernard Le Coq' },
      { name: 'Hippolyte Girardot' },
      { name: 'Samuel Labarthe' },
    ],
    coverUrl: '/movies_pictures/a0b4c4285abb.jpg',
    releaseDate: '2011-05-18',
    length: 105,
    genre: ['Drame', 'Biographie'],
    saga: '',
    description:
      "Chronique romancée de l'ascension de Nicolas Sarkozy jusqu'à l'Élysée, sur fond de rivalités politiques et de vie privée.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La guerre est déclarée',
    director: 'Valérie Donzelli',
    actors: [
      { name: 'Valérie Donzelli' },
      { name: 'Jérémie Elkaïm' },
      { name: 'César Desseix' },
      { name: 'Brigitte Sy' },
      { name: 'Elina Löwensohn' },
    ],
    coverUrl: '/movies_pictures/d9167d6f9511.jpg',
    releaseDate: '2011-08-31',
    length: 100,
    genre: ['Drame', 'Romance', 'Comédie'],
    saga: '',
    description:
      "Un jeune couple découvre que leur bébé est atteint d'une tumeur rare et transforme le combat médical en déclaration d'amour à la vie.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Cheval de Turin',
    director: 'Béla Tarr',
    actors: [
      { name: 'János Derzsi' },
      { name: 'Erika Bók' },
      { name: 'Mihály Kormos' },
      { name: 'Ricsi' },
      { name: 'Mihály Ráday' },
    ],
    coverUrl: '/movies_pictures/1f15a64b1f57.jpg',
    releaseDate: '2011-03-31',
    length: 146,
    genre: ['Drame'],
    saga: '',
    description:
      "Durant six jours, un cocher et sa fille survivent dans une ferme battue par le vent, tandis que le monde semble s'éteindre autour d'eux.",
    fromEntity: null,
    countryOrigin: ['Hongrie', 'France', 'Allemagne', 'Suisse'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Havre',
    director: 'Aki Kaurismäki',
    actors: [
      { name: 'André Wilms' },
      { name: 'Kati Outinen' },
      { name: 'Jean-Pierre Darroussin' },
      { name: 'Blondin Miguel' },
      { name: 'Elina Salo' },
    ],
    coverUrl: '/movies_pictures/a9607dca23ab.jpg',
    releaseDate: '2011-09-21',
    length: 93,
    genre: ['Drame', 'Comédie'],
    saga: '',
    description:
      'Au Havre, un vieux cirageur de chaussures protège un jeune migrant africain et mobilise son quartier pour le soustraire à la police.',
    fromEntity: null,
    countryOrigin: ['Finlande', 'France', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Femmes du 6e étage',
    director: 'Philippe Le Guay',
    actors: [
      { name: 'Fabrice Luchini' },
      { name: 'Natalia Verbeke' },
      { name: 'Sandrine Kiberlain' },
      { name: 'Carmen Maura' },
      { name: 'Lola Dueñas' },
    ],
    coverUrl: '/movies_pictures/068733174984.jpg',
    releaseDate: '2011-02-16',
    length: 104,
    genre: ['Comédie'],
    saga: '',
    description:
      'Dans le Paris des années 1960, un bourgeois découvre le monde des femmes de ménage espagnoles du sixième étage et bouleverse sa vie rangée.',
    fromEntity: null,
    countryOrigin: ['France', 'Espagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Lyonnais',
    director: 'Olivier Marchal',
    actors: [
      { name: 'Gérard Lanvin' },
      { name: 'Tchéky Karyo' },
      { name: 'Daniel Duval' },
      { name: 'Lionnel Astier' },
      { name: 'Patrick Catalifo' },
    ],
    coverUrl: '/movies_pictures/3e1407bf31a9.jpg',
    releaseDate: '2011-11-30',
    length: 102,
    genre: ['Policier', 'Drame'],
    saga: '',
    description:
      "Sur trente ans, l'ascension et la chute d'Edmond Vidal, figure du banditisme lyonnais, entre amitié, trahison et nostalgie.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Neiges du Kilimandjaro',
    director: 'Robert Guédiguian',
    actors: [
      { name: 'Jean-Pierre Darroussin' },
      { name: 'Ariane Ascaride' },
      { name: 'Gérard Meylan' },
      { name: 'Grégoire Leprince-Ringuet' },
      { name: 'Maryline Canto' },
    ],
    coverUrl: '/movies_pictures/c2e555afd0f1.jpg',
    releaseDate: '2011-11-16',
    length: 107,
    genre: ['Drame'],
    saga: '',
    description:
      'Un docker marseillais à la retraite, militant de gauche, voit son quotidien et ses convictions ébranlés après un cambriolage familial.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Limitless',
    director: 'Neil Burger',
    actors: [
      { name: 'Bradley Cooper' },
      { name: 'Robert De Niro' },
      { name: 'Abbie Cornish' },
      { name: 'Andrew Howard' },
      { name: 'Anna Friel' },
    ],
    coverUrl: '/movies_pictures/1617c7753f28.jpg',
    releaseDate: '2011-03-18',
    length: 105,
    genre: ['Thriller', 'Science Fiction'],
    saga: '',
    description:
      "Un écrivain en panne découvre une drogue qui démultiplie ses capacités cognitives, au prix d'une dépendance et d'ennemis dangereux.",
    fromEntity: {
      entityType: 'book',
      title: 'The Dark Fields',
      secondEntityKey: 'Alan Glynn',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Margin Call',
    director: 'J.C. Chandor',
    actors: [
      { name: 'Kevin Spacey' },
      { name: 'Paul Bettany' },
      { name: 'Jeremy Irons' },
      { name: 'Zachary Quinto' },
      { name: 'Penn Badgley' },
    ],
    coverUrl: '/movies_pictures/9a4bb365d6b5.jpg',
    releaseDate: '2011-10-21',
    length: 107,
    genre: ['Drame', 'Thriller'],
    saga: '',
    description:
      "Sur 24 heures, les cadres d'une banque d'investissement Wall Street découvrent un produit toxique qui peut faire s'effondrer la firme.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Martha Marcy May Marlene',
    director: 'Sean Durkin',
    actors: [
      { name: 'Elizabeth Olsen' },
      { name: 'Sarah Paulson' },
      { name: 'John Hawkes' },
      { name: 'Hugh Dancy' },
      { name: 'Julia Garner' },
    ],
    coverUrl: '/movies_pictures/1f3cbad1e31d.jpg',
    releaseDate: '2011-10-21',
    length: 102,
    genre: ['Drame', 'Thriller'],
    saga: '',
    description:
      "Après s'être échappée d'une secte, une jeune femme se réfugie chez sa sœur mais reste hantée par la paranoïa et les traumatismes.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Once Upon a Time in Anatolia',
    director: 'Nuri Bilge Ceylan',
    actors: [
      { name: 'Muhammet Uzuner' },
      { name: 'Yılmaz Erdoğan' },
      { name: 'Taner Birsel' },
      { name: 'Ahmet Mümtaz Taylan' },
      { name: 'Fırat Kanık' },
    ],
    coverUrl:
      '/movies_pictures/e6bbdfc20fac.jpg',
    releaseDate: '2011-09-23',
    length: 157,
    genre: ['Drame', 'Policier', 'Mystère'],
    saga: '',
    description:
      "Une nuit en Anatolie, procureurs et policiers cherchent un cadavre avec l'aide des suspects, dans une enquête lente et philosophique.",
    fromEntity: null,
    countryOrigin: ['Turquie', 'Bosnie-Herzégovine'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Pina',
    director: 'Wim Wenders',
    actors: [
      { name: 'Pina Bausch' },
      { name: 'Regina Advento' },
      { name: 'Malou Airaudo' },
      { name: 'Ruth Amarante' },
      { name: 'Jorge Puerta Armenta' },
    ],
    coverUrl: '/movies_pictures/657b07bd4c85.jpg',
    releaseDate: '2011-02-24',
    length: 103,
    genre: ['Documentaire', 'Comédie musicale'],
    saga: '',
    description:
      'Documentaire-hommage à la chorégraphe Pina Bausch, où danseurs du Tanztheater Wuppertal revisitent ses pièces dans la ville.',
    fromEntity: null,
    countryOrigin: ['Allemagne', 'France', 'Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Senna',
    director: 'Asif Kapadia',
    actors: [
      { name: 'Ayrton Senna' },
      { name: 'Alain Prost' },
      { name: 'Frank Williams' },
      { name: 'Ron Dennis' },
      { name: 'Viviane Senna' },
    ],
    coverUrl: '/movies_pictures/b06b7348a16a.jpg',
    releaseDate: '2010-10-07',
    length: 106,
    genre: ['Documentaire', 'Biographie'],
    saga: '',
    description:
      "Documentaire sur Ayrton Senna, génie de la Formule 1, de ses titres mondiaux jusqu'à sa mort à Imola, à travers archives et courses.",
    fromEntity: null,
    countryOrigin: ['Royaume-Uni', 'France', 'Brésil'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Guard',
    director: 'John Michael McDonagh',
    actors: [
      { name: 'Brendan Gleeson' },
      { name: 'Don Cheadle' },
      { name: 'Liam Cunningham' },
      { name: 'Mark Strong' },
      { name: 'Fionnula Flanagan' },
    ],
    coverUrl: '/movies_pictures/adf89b57c150.jpg',
    releaseDate: '2011-07-07',
    length: 96,
    genre: ['Comédie', 'Policier'],
    saga: '',
    description:
      'En Irlande, un flic provincial cynique et un agent du FBI trop droit collaborent pour démanteler un réseau de trafic de drogue.',
    fromEntity: null,
    countryOrigin: ['Irlande', 'Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Win Win',
    director: 'Thomas McCarthy',
    actors: [
      { name: 'Paul Giamatti' },
      { name: 'Amy Ryan' },
      { name: 'Jeffrey Tambor' },
      { name: 'Burt Young' },
      { name: 'Alex Shaffer' },
    ],
    coverUrl: '/movies_pictures/34b471ab60bd.jpg',
    releaseDate: '2011-03-18',
    length: 106,
    genre: ['Comédie', 'Drame'],
    saga: '',
    description:
      'Un avocat de province au bord de la faillite accueille un adolescent wrestler et tente un arrangement moralement glissant pour sauver son cabinet.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Young Adult',
    director: 'Jason Reitman',
    actors: [
      { name: 'Charlize Theron' },
      { name: 'Patton Oswalt' },
      { name: 'Patrick Wilson' },
      { name: 'Collette Wolfe' },
      { name: 'Elizabeth Reaser' },
    ],
    coverUrl: '/movies_pictures/8fb833a09329.jpg',
    releaseDate: '2011-12-09',
    length: 94,
    genre: ['Comédie', 'Drame'],
    saga: '',
    description:
      'Une auteure de jeunes adultes alcoolique revient dans sa ville natale pour reconquérir son ex, au mépris de la réalité et de son propre déclin.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Amour',
    director: 'Michael Haneke',
    actors: [
      { name: 'Jean-Louis Trintignant' },
      { name: 'Emmanuelle Riva' },
      { name: 'Isabelle Huppert' },
      { name: 'Alexandre Tharaud' },
      { name: 'William Shimell' },
    ],
    coverUrl: '/movies_pictures/a0085ef69005.jpg',
    releaseDate: '2012-10-24',
    length: 127,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      "Un couple de professeurs de musique octogénaires voit sa vie basculer quand la femme est frappée par une attaque ; l'amour devient aussi devoir et fin.",
    fromEntity: null,
    countryOrigin: ['Autriche', 'France', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_INTERNATIONAL_FEATURE, year: 2013 }],
  },
  {
    title: 'Beyond the Hills',
    director: 'Cristian Mungiu',
    actors: [
      { name: 'Cosmina Stratan' },
      { name: 'Cristina Flutur' },
      { name: 'Valeriu Andriuță' },
      { name: 'Dana Tapalagă' },
      { name: 'Călin Werner' },
    ],
    coverUrl: '/movies_pictures/6d487205d351.jpg',
    releaseDate: '2012-10-26',
    length: 150,
    genre: ['Drame'],
    saga: '',
    description:
      "Dans un monastère orthodoxe roumain, l'amitié entre deux jeunes femmes se heurte au dogme, à l'exorcisme et à la tragédie.",
    fromEntity: null,
    countryOrigin: ['Roumanie', 'France', 'Belgique'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Camille redouble',
    director: 'Noémie Lvovsky',
    actors: [
      { name: 'Noémie Lvovsky' },
      { name: 'Samir Guesmi' },
      { name: 'Judith Chemla' },
      { name: 'India Hair' },
      { name: 'Julia Faure' },
    ],
    coverUrl: '/movies_pictures/fbfced63f83c.jpg',
    releaseDate: '2012-09-12',
    length: 120,
    genre: ['Comédie', 'Drame', 'Fantastique'],
    saga: '',
    description:
      'Camille, après une rupture, se retrouve projetée dans son passé de lycéenne et tente de réécrire sa vie amoureuse.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Cloclo',
    director: 'Florent-Emilio Siri',
    actors: [
      { name: 'Jérémie Renier' },
      { name: 'Benoît Magimel' },
      { name: 'Monica Scattini' },
      { name: 'Sabrina Ouazani' },
      { name: 'Joséphine Japy' },
    ],
    coverUrl: '/movies_pictures/8246d95daa07.jpg',
    releaseDate: '2012-03-14',
    length: 148,
    genre: ['Drame', 'Biographie', 'Comédie musicale'],
    saga: '',
    description:
      "Biopic de Claude François, de l'Égypte de son enfance à la gloire des années yé-yé, jusqu'à sa mort accidentelle.",
    fromEntity: null,
    countryOrigin: ['France', 'Belgique'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Cosmopolis',
    director: 'David Cronenberg',
    actors: [
      { name: 'Robert Pattinson' },
      { name: 'Sarah Gadon' },
      { name: 'Paul Giamatti' },
      { name: 'Juliette Binoche' },
      { name: 'Samantha Morton' },
    ],
    coverUrl: '/movies_pictures/6a4659ac04d2.jpg',
    releaseDate: '2012-05-25',
    length: 109,
    genre: ['Drame', 'Thriller'],
    saga: '',
    description:
      "Dans un limousine à travers Manhattan, un jeune milliardaire voit sa fortune et son monde s'effondrer au fil d'une journée apocalyptique.",
    fromEntity: {
      entityType: 'book',
      title: 'Cosmopolis',
      secondEntityKey: 'Don DeLillo',
    },
    countryOrigin: ['Canada', 'France', 'Italie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Dans la maison',
    director: 'François Ozon',
    actors: [
      { name: 'Fabrice Luchini' },
      { name: 'Ernst Umhauer' },
      { name: 'Kristin Scott Thomas' },
      { name: 'Emmanuelle Seigner' },
      { name: 'Denis Ménochet' },
    ],
    coverUrl: '/movies_pictures/f7a771a7d967.jpg',
    releaseDate: '2012-10-10',
    length: 105,
    genre: ['Thriller', 'Drame', 'Comédie'],
    saga: '',
    description:
      "Un professeur de français s'entiche des devoirs d'un élève qui s'immisce dans une famille bourgeoise, brouillant fiction et réalité.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Flight',
    director: 'Robert Zemeckis',
    actors: [
      { name: 'Denzel Washington' },
      { name: 'Kelly Reilly' },
      { name: 'Don Cheadle' },
      { name: 'Bruce Greenwood' },
      { name: 'John Goodman' },
    ],
    coverUrl: '/movies_pictures/c71244306990.jpg',
    releaseDate: '2012-11-02',
    length: 138,
    genre: ['Drame', 'Thriller', 'Catastrophe'],
    saga: '',
    description:
      "Un pilote sauve un avion en panne par un exploit technique, puis doit affronter son alcoolisme quand l'enquête s'intéresse à son état.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Killing Them Softly',
    director: 'Andrew Dominik',
    actors: [
      { name: 'Brad Pitt' },
      { name: 'Scoot McNairy' },
      { name: 'Ben Mendelsohn' },
      { name: 'James Gandolfini' },
      { name: 'Ray Liotta' },
    ],
    coverUrl: '/movies_pictures/38441dda1ade.jpg',
    releaseDate: '2012-11-30',
    length: 97,
    genre: ['Policier', 'Thriller', 'Drame'],
    saga: '',
    description:
      "Pendant la crise de 2008, un tueur à gages est chargé de rétablir l'ordre dans le milieu après le braquage d'une partie de poker mafieuse.",
    fromEntity: {
      entityType: 'book',
      title: "Cogan's Trade",
      secondEntityKey: 'George V. Higgins',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Chasse',
    director: 'Thomas Vinterberg',
    actors: [
      { name: 'Mads Mikkelsen' },
      { name: 'Thomas Bo Larsen' },
      { name: 'Annika Wedderkopp' },
      { name: 'Lasse Fogelstrøm' },
      { name: 'Alexandra Rapaport' },
    ],
    coverUrl:
      '/movies_pictures/8f1fc29fab70.jpg',
    releaseDate: '2012-10-25',
    length: 115,
    genre: ['Drame', 'Thriller'],
    saga: '',
    description:
      "Dans un village danois, un instituteur adoré voit sa vie détruite par une fausse accusation d'abus sur une petite fille.",
    fromEntity: null,
    countryOrigin: ['Danemark', 'Suède'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Laurence Anyways',
    director: 'Xavier Dolan',
    actors: [
      { name: 'Melvil Poupaud' },
      { name: 'Suzanne Clément' },
      { name: 'Nathalie Baye' },
      { name: 'Monia Chokri' },
      { name: 'Yves Jacques' },
    ],
    coverUrl:
      '/movies_pictures/3a5ece090d34.jpg',
    releaseDate: '2012-05-18',
    length: 168,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      "Sur une décennie, l'amour tumultueux entre une femme et un homme qui décide de vivre en femme, dans le Montréal des années 1990.",
    fromEntity: null,
    countryOrigin: ['Canada', 'France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Bêtes du sud sauvage',
    director: 'Benh Zeitlin',
    actors: [
      { name: 'Quvenzhané Wallis' },
      { name: 'Dwight Henry' },
      { name: 'Levy Easterly' },
      { name: 'Lowell Landes' },
      { name: 'Pamela Harper' },
    ],
    coverUrl:
      '/movies_pictures/8b02e2f8f67b.jpg',
    releaseDate: '2012-06-27',
    length: 93,
    genre: ['Drame', 'Fantastique'],
    saga: '',
    description:
      'Dans le bayou, une petite fille et son père malade luttent pour rester sur leur terre isolée face aux éléments et aux autorités.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Infidèles',
    director: 'Jean Dujardin',
    actors: [
      { name: 'Jean Dujardin' },
      { name: 'Gilles Lellouche' },
      { name: 'Guillaume Canet' },
      { name: 'Sandrine Kiberlain' },
      { name: 'Lionel Abelanski' },
    ],
    coverUrl:
      '/movies_pictures/ec36d29ab038.png',
    releaseDate: '2012-02-29',
    length: 115,
    genre: ['Comédie'],
    saga: '',
    description:
      "Film à sketches sur l'infidélité masculine, entre comédie grinçante, mensonges conjugaux et crises de couple.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Kaïra',
    director: 'Franck Gastambide',
    actors: [
      { name: 'Franck Gastambide' },
      { name: 'Medi Sadoun' },
      { name: 'Jib Pocthier' },
      { name: 'Ramzy Bedia' },
      { name: 'Éric Judor' },
    ],
    coverUrl:
      'https://medias.unifrance.org/medias/34/50/78370/format_page/les-kaira.jpg',
    releaseDate: '2012-07-11',
    length: 98,
    genre: ['Comédie'],
    saga: '',
    description:
      "Trois amis de cité décident de se lancer dans le porno amateur pour s'enrichir, dans une comédie trash et absurde.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Saveurs du palais',
    director: 'Christian Vincent',
    actors: [
      { name: 'Catherine Frot' },
      { name: "Jean d'Ormesson" },
      { name: 'Hippolyte Girardot' },
      { name: 'Arthur Dupont' },
      { name: 'Jean-Marc Roulot' },
    ],
    coverUrl:
      '/movies_pictures/4ca27bf91920.jpg',
    releaseDate: '2012-09-19',
    length: 95,
    genre: ['Comédie', 'Drame', 'Biographie'],
    saga: '',
    description:
      "Une cuisinière périgourdine est engagée à l'Élysée pour préparer les repas du Président, entre tradition et protocole.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Populaire',
    director: 'Régis Roinsard',
    actors: [
      { name: 'Romain Duris' },
      { name: 'Déborah François' },
      { name: 'Bérénice Bejo' },
      { name: 'Shaun Benson' },
      { name: 'Eddy Mitchell' },
    ],
    coverUrl:
      '/movies_pictures/957a43f7f96d.jpg',
    releaseDate: '2012-11-28',
    length: 111,
    genre: ['Comédie', 'Romance'],
    saga: '',
    description:
      'Dans les années 1950, une jeune secrétaire douée en dactylographie est entraînée par son patron vers les championnats de vitesse.',
    fromEntity: null,
    countryOrigin: ['France', 'Belgique'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Quelques heures de printemps',
    director: 'Stéphane Brizé',
    actors: [
      { name: 'Vincent Lindon' },
      { name: 'Hélène Vincent' },
      { name: 'Ludivine Sagnier' },
      { name: 'Olivier Perrier' },
      { name: 'Silvia Kahn' },
    ],
    coverUrl:
      '/movies_pictures/5a930df406b1.jpg',
    releaseDate: '2012-09-19',
    length: 108,
    genre: ['Drame'],
    saga: '',
    description:
      'Un homme sorti de prison revient vivre chez sa mère malade et tente une coexistence difficile avant une éventuelle euthanasie.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Searching for Sugar Man',
    director: 'Malik Bendjelloul',
    actors: [
      { name: 'Sixto Rodriguez' },
      { name: 'Stephen Segerman' },
      { name: 'Craig Bartholomew Strydom' },
      { name: 'Dennis Coffey' },
      { name: 'Mike Theodore' },
    ],
    coverUrl: '/movies_pictures/479eb557b684.jpg',
    releaseDate: '2012-07-26',
    length: 86,
    genre: ['Documentaire', 'Biographie', 'Comédie musicale'],
    saga: '',
    description:
      'Deux fans sud-africains partent à la recherche de Sixto Rodriguez, auteur-compositeur américain devenu légende sans le savoir.',
    fromEntity: null,
    countryOrigin: ['Suède', 'Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2013 }],
  },
  {
    title: "Un bonheur n'arrive jamais seul",
    director: 'James Huth',
    actors: [
      { name: 'Gad Elmaleh' },
      { name: 'Sophie Marceau' },
      { name: 'Maurice Barthélémy' },
      { name: 'François Berléand' },
      { name: 'Michaël Youn' },
    ],
    coverUrl:
      '/movies_pictures/97e03fdc8ddb.jpg',
    releaseDate: '2012-06-27',
    length: 110,
    genre: ['Comédie', 'Romance'],
    saga: '',
    description:
      "Un chanteur sur le déclin tombe amoureux d'une business woman surmenée et père de trois enfants, entre comédie et romance.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Wadjda',
    director: 'Haifaa al-Mansour',
    actors: [
      { name: 'Waad Mohammed' },
      { name: 'Reem Abdullah' },
      { name: 'Abdullrahman Al Gohani' },
      { name: 'Ahd Kamel' },
      { name: 'Sultan Al Assaf' },
    ],
    coverUrl:
      'https://cdn1.cinenode.com/movie_poster/157/full/wadjda-157125.jpg',
    releaseDate: '2012-08-31',
    length: 98,
    genre: ['Drame', 'Jeunesse'],
    saga: '',
    description:
      "En Arabie saoudite, une fillette rêve d'acheter un vélo interdit aux filles et vend des objets pour y parvenir.",
    fromEntity: null,
    countryOrigin: ['Arabie saoudite', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: '9 mois ferme',
    director: 'Albert Dupontel',
    actors: [
      { name: 'Albert Dupontel' },
      { name: 'Sandrine Kiberlain' },
      { name: 'Philippe Uchan' },
      { name: 'Nicolas Marié' },
      { name: 'Bouli Lanners' },
    ],
    coverUrl:
      '/movies_pictures/f2ead95ab59d.jpg',
    releaseDate: '2013-10-16',
    length: 98,
    genre: ['Comédie'],
    saga: '',
    description:
      "Une juge aux mœurs strictes découvre qu'elle est enceinte sans se souvenir de la nuit en question, et mène l'enquête sur elle-même.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Alceste à bicyclette',
    director: 'Philippe Le Guay',
    actors: [
      { name: 'Fabrice Luchini' },
      { name: 'Lambert Wilson' },
      { name: 'Maya Sansa' },
      { name: 'Laurie Bordesoules' },
      { name: 'Gilles Cohen' },
    ],
    coverUrl:
      '/movies_pictures/41926c4055ea.jpg',
    releaseDate: '2013-04-16',
    length: 104,
    genre: ['Comédie', 'Drame'],
    saga: '',
    description:
      'Un acteur acariâtre à la retraite et une star de cinéma se retrouvent pour répéter Le Misanthrope dans une maison au bord de la mer.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'August: Osage County',
    director: 'John Wells',
    actors: [
      { name: 'Meryl Streep' },
      { name: 'Julia Roberts' },
      { name: 'Ewan McGregor' },
      { name: 'Chris Cooper' },
      { name: 'Margo Martindale' },
    ],
    coverUrl:
      '/movies_pictures/e65473689201.jpg',
    releaseDate: '2013-12-27',
    length: 121,
    genre: ['Drame', 'Comédie'],
    saga: '',
    description:
      'Après la disparition du patriarche, une famille du Oklahoma se déchire sous le regard acide et toxique de la mère.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Belle et Sébastien',
    director: 'Nicolas Vanier',
    actors: [
      { name: 'Félix Bossuet' },
      { name: 'Tchéky Karyo' },
      { name: 'Margaux Châtelier' },
      { name: 'Dimitri Storoge' },
      { name: 'Andreas Pietschmann' },
    ],
    coverUrl:
      '/movies_pictures/009fed6281de.jpg',
    releaseDate: '2013-12-18',
    length: 98,
    genre: ['Aventure', 'Jeunesse', 'Drame'],
    saga: 'Belle et Sébastien',
    description:
      "Dans les Alpes pendant l'Occupation, un enfant se lie d'amitié avec une chienne réputée dangereuse et aide des résistants.",
    fromEntity: {
      entityType: 'book',
      title: 'Belle et Sébastien',
      secondEntityKey: 'Cécile Aubry',
    },
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'En solitaire',
    director: 'Christophe Offenstein',
    actors: [
      { name: 'François Cluzet' },
      { name: 'Guillaume Canet' },
      { name: 'Virginie Efira' },
      { name: 'Samy Seghir' },
      { name: 'Arly Jover' },
    ],
    coverUrl:
      '/movies_pictures/8d02a15624b1.jpg',
    releaseDate: '2013-11-06',
    length: 96,
    genre: ['Aventure', 'Drame', 'Thriller'],
    saga: '',
    description:
      'Un skippeur en course autour du monde découvre un passager clandestin à bord et doit choisir entre règlement et humanité.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Frances Ha',
    director: 'Noah Baumbach',
    actors: [
      { name: 'Greta Gerwig' },
      { name: 'Mickey Sumner' },
      { name: 'Adam Driver' },
      { name: 'Michael Zegen' },
      { name: 'Grace Gummer' },
    ],
    coverUrl:
      '/movies_pictures/a907066affe8.jpg',
    releaseDate: '2013-05-17',
    length: 86,
    genre: ['Comédie', 'Drame'],
    saga: '',
    description:
      'À New York, une danseuse sans le sou navigue entre amitiés, colocations et rêves artistiques dans une comédie en noir et blanc.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Fruitvale Station',
    director: 'Ryan Coogler',
    actors: [
      { name: 'Michael B. Jordan' },
      { name: 'Octavia Spencer' },
      { name: 'Melonie Diaz' },
      { name: 'Kevin Durand' },
      { name: 'Chad Michael Murray' },
    ],
    coverUrl:
      '/movies_pictures/fdd7ba36ef67.jpg',
    releaseDate: '2013-07-12',
    length: 85,
    genre: ['Drame', 'Biographie'],
    saga: '',
    description:
      "Reconstruction des dernières 24 heures d'Oscar Grant, jeune Noir américain tué par la police dans une station de métro de Oakland.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Écume des jours",
    director: 'Michel Gondry',
    actors: [
      { name: 'Romain Duris' },
      { name: 'Audrey Tautou' },
      { name: 'Gad Elmaleh' },
      { name: 'Omar Sy' },
      { name: 'Aïssa Maïga' },
    ],
    coverUrl:
      '/movies_pictures/5fbd89a16e61.jpg',
    releaseDate: '2013-04-24',
    length: 125,
    genre: ['Romance', 'Fantastique', 'Drame'],
    saga: '',
    description:
      'Adaptation féerique et musicale du roman de Vian : Colin et Chloé vivent un amour menacé par une maladie absurde et poétique.',
    fromEntity: {
      entityType: 'book',
      title: "L'Écume des jours",
      secondEntityKey: 'Boris Vian',
    },
    countryOrigin: ['France', 'Belgique'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Inconnu du lac",
    director: 'Alain Guiraudie',
    actors: [
      { name: 'Pierre Deladonchamps' },
      { name: 'Christophe Paou' },
      { name: "Patrick d'Assumçao" },
      { name: 'Jérôme Chappatte' },
      { name: 'Mathieu Vervisch' },
    ],
    coverUrl:
      '/movies_pictures/f58eb06f82e2.jpg',
    releaseDate: '2013-06-12',
    length: 97,
    genre: ['Thriller', 'Drame', 'Romance'],
    saga: '',
    description:
      "Sur une plage gay isolée, un homme tombe amoureux d'un inconnu après avoir assisté à un meurtre, entre désir et danger.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Cage dorée',
    director: 'Ruben Alves',
    actors: [
      { name: 'Rita Blanco' },
      { name: 'Joaquim de Almeida' },
      { name: 'Roland Giraud' },
      { name: 'Chantal Lauby' },
      { name: 'Barbara Cabrita' },
    ],
    coverUrl:
      '/movies_pictures/ad781a17e804.jpg',
    releaseDate: '2013-04-24',
    length: 90,
    genre: ['Comédie'],
    saga: '',
    description:
      "Une famille portugaise installée en France depuis des années voit son équilibre menacé quand un héritage l'invite à rentrer au pays.",
    fromEntity: null,
    countryOrigin: ['France', 'Portugal'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Grande Bellezza',
    director: 'Paolo Sorrentino',
    actors: [
      { name: 'Toni Servillo' },
      { name: 'Carlo Verdone' },
      { name: 'Sabrina Ferilli' },
      { name: 'Carlo Buccirosso' },
      { name: 'Iaia Forte' },
    ],
    coverUrl: '/movies_pictures/a45241fc1f3d.jpg',
    releaseDate: '2013-05-21',
    length: 141,
    genre: ['Drame'],
    saga: '',
    description:
      "À Rome, un journaliste mondain sexagénaire repense sa vie vide de sens après la mort d'un amour de jeunesse.",
    fromEntity: null,
    countryOrigin: ['Italie', 'France'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_INTERNATIONAL_FEATURE, year: 2014 }],
  },
  {
    title: 'La Vénus à la fourrure',
    director: 'Roman Polanski',
    actors: [
      { name: 'Emmanuelle Seigner' },
      { name: 'Mathieu Amalric' },
      { name: 'Melvil Poupaud' },
    ],
    coverUrl:
      '/movies_pictures/a9bf1880ecb0.jpg',
    releaseDate: '2013-11-13',
    length: 96,
    genre: ['Drame', 'Thriller'],
    saga: '',
    description:
      'Dans un théâtre vide, un metteur en scène auditionne une actrice pour son adaptation de Sacher-Masoch ; le pouvoir change de camp.',
    fromEntity: {
      entityType: 'book',
      title: 'La Vénus à la fourrure',
      secondEntityKey: 'Leopold von Sacher-Masoch',
    },
    countryOrigin: ['France', 'Pologne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Passé',
    director: 'Asghar Farhadi',
    actors: [
      { name: 'Bérénice Bejo' },
      { name: 'Tahar Rahim' },
      { name: 'Ali Mosaffa' },
      { name: 'Pauline Burlet' },
      { name: 'Elyes Aguis' },
    ],
    coverUrl:
      '/movies_pictures/8a9d573a5359.jpg',
    releaseDate: '2013-05-17',
    length: 130,
    genre: ['Drame'],
    saga: '',
    description:
      "Un Iranien revient à Paris pour divorcer ; le passé et les non-dits d'une famille recomposée ressurgissent autour d'une adolescente.",
    fromEntity: null,
    countryOrigin: ['France', 'Italie', 'Iran'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Mandela : Un long chemin vers la liberté',
    director: 'Justin Chadwick',
    actors: [
      { name: 'Idris Elba' },
      { name: 'Naomie Harris' },
      { name: 'Tony Kgoroge' },
      { name: 'Riaad Moosa' },
      { name: 'Jamie Bartlett' },
    ],
    coverUrl:
      '/movies_pictures/9705dcd17318.jpg',
    releaseDate: '2013-11-28',
    length: 141,
    genre: ['Drame', 'Biographie', 'Historique'],
    saga: '',
    description:
      "Biopic de Nelson Mandela, de l'avocat militant à Robben Island jusqu'à la présidence et la fin de l'apartheid.",
    fromEntity: {
      entityType: 'book',
      title: 'Un long chemin vers la liberté',
      secondEntityKey: 'Nelson Mandela',
    },
    countryOrigin: ['Royaume-Uni', 'Afrique du Sud'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Quai d'Orsay",
    director: 'Bertrand Tavernier',
    actors: [
      { name: 'Thierry Lhermitte' },
      { name: 'Raphaël Personnaz' },
      { name: 'Niels Arestrup' },
      { name: 'Julie Gayet' },
      { name: 'Anaïs Demoustier' },
    ],
    coverUrl:
      '/movies_pictures/47ad478d7bbc.jpg',
    releaseDate: '2013-11-06',
    length: 113,
    genre: ['Comédie'],
    saga: '',
    description:
      "Un jeune normalien découvre les coulisses absurdes du Quai d'Orsay au service d'un ministre des Affaires étrangères théâtral.",
    fromEntity: {
      entityType: 'bd',
      title: "Quai d'Orsay",
      secondEntityKey: 'Abel Lanzac',
    },
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Spring Breakers',
    director: 'Harmony Korine',
    actors: [
      { name: 'James Franco' },
      { name: 'Vanessa Hudgens' },
      { name: 'Selena Gomez' },
      { name: 'Ashley Benson' },
      { name: 'Rachel Korine' },
    ],
    coverUrl:
      '/movies_pictures/0e8c12f81295.jpg',
    releaseDate: '2013-03-22',
    length: 94,
    genre: ['Drame', 'Thriller', 'Policier'],
    saga: '',
    description:
      "Quatre étudiantes américaines plongent dans le crime à Miami pour financer leurs vacances, sous l'emprise d'un rappeur louche.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Act of Killing',
    director: 'Joshua Oppenheimer',
    actors: [
      { name: 'Anwar Congo' },
      { name: 'Herman Koto' },
      { name: 'Syamsul Arifin' },
      { name: 'Ibrahim Sinik' },
      { name: 'Yapto Soelisto' },
    ],
    coverUrl:
      '/movies_pictures/e74478b3ec69.jpg',
    releaseDate: '2012-09-01',
    length: 117,
    genre: ['Documentaire'],
    saga: '',
    description:
      "Des assassins indonésiens rejouent leurs crimes de 1965 comme des scènes de cinéma, dans un documentaire saisissant sur l'impunité.",
    fromEntity: null,
    countryOrigin: ['Danemark', 'Norvège', 'Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Spectacular Now',
    director: 'James Ponsoldt',
    actors: [
      { name: 'Miles Teller' },
      { name: 'Shailene Woodley' },
      { name: 'Brie Larson' },
      { name: 'Jennifer Jason Leigh' },
      { name: 'Kyle Chandler' },
    ],
    coverUrl:
      '/movies_pictures/74a600b1ec43.jpg',
    releaseDate: '2013-08-02',
    length: 95,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      "Un lycéen charmeur et une fille sérieuse entament une romance fragile, entre alcool, maturité et choix d'avenir.",
    fromEntity: {
      entityType: 'book',
      title: 'The Spectacular Now',
      secondEntityKey: 'Tim Tharp',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Bande de filles',
    director: 'Céline Sciamma',
    actors: [
      { name: 'Karidja Touré' },
      { name: 'Assa Sylla' },
      { name: 'Lindsay Karamoh' },
      { name: 'Mariétou Touré' },
      { name: 'Cyril Mendy' },
    ],
    coverUrl:
      '/movies_pictures/6e821404dade.jpg',
    releaseDate: '2014-10-08',
    length: 112,
    genre: ['Drame'],
    saga: '',
    description:
      'Dans une cité de la banlieue parisienne, une adolescente rejoint un gang de filles pour échapper à la violence familiale et exister.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Calvary',
    director: 'John Michael McDonagh',
    actors: [
      { name: 'Brendan Gleeson' },
      { name: "Chris O'Dowd" },
      { name: 'Kelly Reilly' },
      { name: 'Aidan Gillen' },
      { name: 'Dylan Moran' },
    ],
    coverUrl:
      '/movies_pictures/8a691d7adb33.jpg',
    releaseDate: '2014-04-11',
    length: 102,
    genre: ['Drame', 'Thriller'],
    saga: '',
    description:
      "En Irlande, un prêtre apprend qu'il sera tué dans une semaine pour les péchés de l'Église, et continue d'aider son village.",
    fromEntity: null,
    countryOrigin: ['Irlande', 'Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Deux jours, une nuit',
    director: 'Jean-Pierre Dardenne',
    actors: [
      { name: 'Marion Cotillard' },
      { name: 'Fabrizio Rongione' },
      { name: 'Pili Groyne' },
      { name: 'Simon Caudry' },
      { name: 'Catherine Salée' },
    ],
    coverUrl:
      '/movies_pictures/5eb2d83aad01.jpg',
    releaseDate: '2014-05-21',
    length: 95,
    genre: ['Drame'],
    saga: '',
    description:
      "Sandra, remise d'une dépression, a un week-end pour convaincre ses collègues de renoncer à leur prime afin de sauver son emploi.",
    fromEntity: null,
    countryOrigin: ['Belgique', 'France', 'Italie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Diplomatie',
    director: 'Volker Schlöndorff',
    actors: [
      { name: 'André Dussollier' },
      { name: 'Niels Arestrup' },
      { name: 'Burghart Klaußner' },
      { name: 'Robert Stadlober' },
      { name: 'Charlie Nelson' },
    ],
    coverUrl:
      '/movies_pictures/07630957b3c9.jpg',
    releaseDate: '2014-03-05',
    length: 84,
    genre: ['Drame', 'Historique', 'Guerre', 'Thriller'],
    saga: '',
    description:
      'En août 1944, le consul suédois Nordling tente de dissuader le général allemand von Choltitz de détruire Paris.',
    fromEntity: null,
    countryOrigin: ['France', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Hippocrate',
    director: 'Thomas Lilti',
    actors: [
      { name: 'Vincent Lacoste' },
      { name: 'Reda Kateb' },
      { name: 'Jacques Gamblin' },
      { name: 'Marianne Denicourt' },
      { name: 'Félix Moati' },
    ],
    coverUrl:
      'https://medias.unifrance.org/medias/113/240/127089/format_page/hippocrate.jpg',
    releaseDate: '2014-09-03',
    length: 102,
    genre: ['Drame', 'Comédie'],
    saga: 'Hippocrate',
    description:
      "Un interne idéaliste découvre le chaos d'un service hospitalier public, entre manque de moyens, éthique et désillusion.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Combattants',
    director: 'Thomas Cailley',
    actors: [
      { name: 'Adèle Haenel' },
      { name: 'Kévin Azaïs' },
      { name: 'Antoine Laurent' },
      { name: 'Brigitte Roüan' },
      { name: 'William Lebghil' },
    ],
    coverUrl:
      '/movies_pictures/1a8477ad4839.jpg',
    releaseDate: '2014-08-20',
    length: 98,
    genre: ['Comédie', 'Romance', 'Drame'],
    saga: '',
    description:
      "Un jeune homme rencontre une survivaliste paranoïaque ; leur romance se noue autour de l'entraînement à la fin du monde.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Locke',
    director: 'Steven Knight',
    actors: [
      { name: 'Tom Hardy' },
      { name: 'Olivia Colman' },
      { name: 'Ruth Wilson' },
      { name: 'Andrew Scott' },
      { name: 'Tom Holland' },
    ],
    coverUrl:
      '/movies_pictures/73ac5e2eae33.jpg',
    releaseDate: '2014-04-18',
    length: 85,
    genre: ['Drame', 'Thriller'],
    saga: '',
    description:
      "En une nuit au téléphone, un chef de chantier voit sa vie personnelle et professionnelle s'effondrer pendant qu'il conduit vers Londres.",
    fromEntity: null,
    countryOrigin: ['Royaume-Uni', 'États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Pride',
    director: 'Matthew Warchus',
    actors: [
      { name: 'Bill Nighy' },
      { name: 'Imelda Staunton' },
      { name: 'Dominic West' },
      { name: 'Andrew Scott' },
      { name: 'Ben Schnetzer' },
    ],
    coverUrl: '/movies_pictures/90bc013b7551.jpg',
    releaseDate: '2014-09-12',
    length: 119,
    genre: ['Comédie', 'Drame', 'Historique', 'Biographie'],
    saga: '',
    description:
      'En 1984, des militants LGBT londoniens soutiennent les mineurs en grève au Pays de Galles, malgré les préjugés des deux côtés.',
    fromEntity: null,
    countryOrigin: ['Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Saint Laurent',
    director: 'Bertrand Bonello',
    actors: [
      { name: 'Gaspard Ulliel' },
      { name: 'Jérémie Renier' },
      { name: 'Louis Garrel' },
      { name: 'Léa Seydoux' },
      { name: 'Amira Casar' },
    ],
    coverUrl:
      '/movies_pictures/ad34db11e472.jpg',
    releaseDate: '2014-09-24',
    length: 150,
    genre: ['Drame', 'Biographie'],
    saga: '',
    description:
      "Portrait fictionnel de Yves Saint Laurent dans les années 1970, entre création, excès, amours et solitude de l'icône.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Snow Therapy',
    director: 'Ruben Östlund',
    actors: [
      { name: 'Johannes Kuhnke' },
      { name: 'Lisa Loven Kongsli' },
      { name: 'Clara Wettergren' },
      { name: 'Vincent Wettergren' },
      { name: 'Kristofer Hivju' },
    ],
    coverUrl:
      '/movies_pictures/30c4411e2e82.jpg',
    releaseDate: '2014-11-15',
    length: 118,
    genre: ['Drame', 'Comédie'],
    saga: '',
    description:
      'Une famille bourgeoise suédoise en ski voit ses non-dits exploser après une avalanche, dans une satire du couple et de la parentalité.',
    fromEntity: null,
    countryOrigin: ['Suède', 'France', 'Norvège', 'Danemark'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Babadook',
    director: 'Jennifer Kent',
    actors: [
      { name: 'Essie Davis' },
      { name: 'Noah Wiseman' },
      { name: 'Daniel Henshall' },
      { name: 'Hayley McFarlane' },
      { name: 'Barbara West' },
    ],
    coverUrl:
      '/movies_pictures/fe198d2bbe78.jpg',
    releaseDate: '2014-05-22',
    length: 94,
    genre: ['Horreur', 'Drame'],
    saga: '',
    description:
      "Une veuve et son fils sont hantés par une créature née d'un livre pour enfants, métaphore terrifiante du deuil et de la maternité.",
    fromEntity: null,
    countryOrigin: ['Australie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Interview',
    director: 'Seth Rogen',
    actors: [
      { name: 'James Franco' },
      { name: 'Seth Rogen' },
      { name: 'Lizzy Caplan' },
      { name: 'Randall Park' },
      { name: 'Diana Bang' },
    ],
    coverUrl: '',
    releaseDate: '2014-12-25',
    length: 112,
    genre: ['Comédie', 'Action'],
    saga: '',
    description:
      "Deux animateurs télé américains sont recrutés par la CIA pour assassiner Kim Jong-un lors d'une interview exclusive.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Timbuktu',
    director: 'Abderrahmane Sissako',
    actors: [
      { name: 'Ibrahim Ahmed' },
      { name: 'Toulou Kiki' },
      { name: 'Abel Jafri' },
      { name: 'Fatoumata Diawara' },
      { name: 'Hichem Yacoubi' },
    ],
    coverUrl:
      '/movies_pictures/f9e11296b4c8.jpg',
    releaseDate: '2014-12-10',
    length: 97,
    genre: ['Drame'],
    saga: '',
    description:
      "Dans une ville du nord du Mali sous occupation djihadiste, un éleveur et sa famille tentent de vivre malgré la terreur et l'arbitraire.",
    fromEntity: null,
    countryOrigin: ['France', 'Mauritanie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Under the Skin',
    director: 'Jonathan Glazer',
    actors: [
      { name: 'Scarlett Johansson' },
      { name: 'Jeremy McWilliams' },
      { name: 'Lynsey Taylor Mackay' },
      { name: 'Dougie McConnell' },
      { name: 'Kevin McAlinden' },
    ],
    coverUrl:
      '/movies_pictures/c01866131030.jpg',
    releaseDate: '2014-03-14',
    length: 108,
    genre: ['Science Fiction', 'Thriller', 'Horreur'],
    saga: '',
    description:
      "Une extraterrestre à l'apparence d'une femme parcourt l'Écosse pour séduire des hommes, jusqu'à ce que l'humanité la trouble.",
    fromEntity: {
      entityType: 'book',
      title: 'Under the Skin',
      secondEntityKey: 'Michel Faber',
    },
    countryOrigin: ['Royaume-Uni', 'États-Unis', 'Suisse'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Winter Sleep',
    director: 'Nuri Bilge Ceylan',
    actors: [
      { name: 'Haluk Bilginer' },
      { name: 'Melisa Sözen' },
      { name: 'Demet Akbag' },
      { name: 'Ayberk Pekcan' },
      { name: 'Serhat Kılıç' },
    ],
    coverUrl:
      '/movies_pictures/4846579e992b.jpg',
    releaseDate: '2014-06-13',
    length: 196,
    genre: ['Drame'],
    saga: '',
    description:
      'Dans un hôtel en Cappadoce, un ancien acteur devenu hôte aisé se heurte à sa jeune femme et à ses locataires pendant un long hiver.',
    fromEntity: null,
    countryOrigin: ['Turquie', 'France', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Yves Saint Laurent',
    director: 'Jalil Lespert',
    actors: [
      { name: 'Pierre Niney' },
      { name: 'Guillaume Gallienne' },
      { name: 'Charlotte Le Bon' },
      { name: 'Laura Smet' },
      { name: 'Marie de Villepin' },
    ],
    coverUrl:
      '/movies_pictures/42d0d6fdfa78.jpg',
    releaseDate: '2014-01-08',
    length: 106,
    genre: ['Drame', 'Biographie'],
    saga: '',
    description:
      "Biopic officiel d'Yves Saint Laurent, de ses débuts chez Dior à l'empire de la mode, avec Pierre Bergé à ses côtés.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Dog Pound',
    director: 'Kim Chapiron',
    actors: [
      { name: 'Adam Butcher' },
      { name: 'Shane Kippel' },
      { name: 'Mateo Morales' },
      { name: 'Taylor Poulin' },
      { name: 'Lawrence Bayne' },
    ],
    coverUrl: '/movies_pictures/f02b9bb2351b.jpg',
    releaseDate: '2010-06-23',
    length: 91,
    genre: ['Thriller', 'Drame'],
    saga: '',
    description:
      'Trois adolescents arrivent dans un centre de détention pour mineurs canadien et découvrent un système de violence entre détenus et gardiens.',
    fromEntity: null,
    countryOrigin: ['France', 'Canada'],
    selectDisplayOrder: 0,
    oscars: [],
  },
];
