import { BaseMovie, OscarEnum } from '../../../models/movie-model';

/**
 * Films manquants — documentaires. Années entre parenthèses absentes des titres.
 * coverUrl laissé vide.
 */
export const baseMoviesMissingDocumentaire: BaseMovie[] = [
  {
    title: 'Moi, un Noir',
    director: 'Jean Rouch',
    actors: [
      { name: 'Oumarou Ganda' },
      { name: 'Petit Touré' },
      { name: 'Alassane Maiga' },
      { name: 'Gambi' },
      { name: 'Petit Jules' },
    ],
    coverUrl: '',
    releaseDate: '1958-12-12',
    length: 70,
    genre: ['Documentaire', 'Drame'],
    saga: '',
    description:
      'Des dockers trop trop trop Treichville trop trop trop se jouent eux-mêmes, Rouch trop Abidjan voix cinéma trop trop trop vérité.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Chronique d'un été",
    director: 'Jean Rouch',
    actors: [
      { name: 'Marceline Loridan-Ivens' },
      { name: 'Angelo Tavano' },
      { name: 'Landry Marmane' },
      { name: 'Jean-Pierre Sergent' },
      { name: 'Régis Debray' },
    ],
    coverUrl: '',
    releaseDate: '1961-10-20',
    length: 90,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Paris trop trop trop 1960 trop trop trop êtes-vous trop trop trop heureux trop trop trop, Rouch trop Morin caméra vérité trop trop trop été trop trop trop micro.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Don't Look Back",
    director: 'D.A. Pennebaker',
    actors: [
      { name: 'Bob Dylan' },
      { name: 'Joan Baez' },
      { name: 'Donovan' },
      { name: 'Albert Grossman' },
      { name: 'Alan Price' },
    ],
    coverUrl: '',
    releaseDate: '1967-05-17',
    length: 96,
    genre: ['Documentaire', 'Comédie musicale', 'Biographie'],
    saga: '',
    description:
      'Dylan trop trop trop Angleterre trop trop trop 65 électrique trop trop trop, Pennebaker trop cinéma trop trop trop vérité Subterranean cards.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Titicut Follies',
    director: 'Frederick Wiseman',
    actors: [
      { name: 'Vladimir de la Cruz' },
      { name: 'James J. Terlizzi' },
      { name: 'Eddie Doucette' },
    ],
    coverUrl: '',
    releaseDate: '1967-10-03',
    length: 84,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Un asile trop trop trop Bridgewater censuré 20 ans, Wiseman trop nudité garde folie Massachusetts.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Chagrin et la Pitié',
    director: 'Marcel Ophüls',
    actors: [
      { name: 'Marcel Ophüls' },
      { name: 'Pierre Mendès France' },
      { name: 'Christian de la Mazière' },
      { name: 'Louis Grave' },
      { name: 'Helmut Tausend' },
    ],
    coverUrl: '',
    releaseDate: '1969-09-18',
    length: 251,
    genre: ['Documentaire', 'Guerre', 'Historique'],
    saga: '',
    description:
      'Clermont trop trop trop Occupation collabos 4h, Ophüls trop pitié chagrin Vichy interviews.',
    fromEntity: null,
    countryOrigin: ['France', 'Suisse', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Gimme Shelter',
    director: 'Albert Maysles',
    actors: [
      { name: 'Mick Jagger' },
      { name: 'Keith Richards' },
      { name: 'Charlie Watts' },
      { name: 'Meredith Hunter' },
      { name: 'Grace Slick' },
    ],
    coverUrl: '',
    releaseDate: '1970-12-06',
    length: 91,
    genre: ['Documentaire', 'Comédie musicale'],
    saga: '',
    description:
      'Les Stones trop trop trop Altamont Hell Angels trop trop trop, Maysles trop meurtre concert 69 fin.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Vérités et Mensonges',
    director: 'Orson Welles',
    actors: [
      { name: 'Orson Welles' },
      { name: 'Elmyr de Hory' },
      { name: 'Clifford Irving' },
      { name: 'Oja Kodar' },
      { name: 'François Reichenbach' },
    ],
    coverUrl: '',
    releaseDate: '1973-09-01',
    length: 89,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Welles trop trop trop faussaires Irving Ibiza trop trop trop, essai cinéma mensonge magie trop trop trop F for Fake.',
    fromEntity: null,
    countryOrigin: ['France', 'Iran', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Grey Gardens',
    director: 'Albert Maysles',
    actors: [
      { name: 'Edith Bouvier Beale' },
      { name: 'Edie Beale' },
      { name: 'Albert Maysles' },
      { name: 'David Maysles' },
      { name: 'Jerry Torre' },
    ],
    coverUrl: '',
    releaseDate: '1975-09-27',
    length: 95,
    genre: ['Documentaire', 'Biographie'],
    saga: '',
    description:
      'Deux Jackie trop trop trop cousines East Hampton trop trop trop, Maysles trop chats manoir déchéance Big Edie.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Harlan County, USA',
    director: 'Barbara Kopple',
    actors: [
      { name: 'Lois Scott' },
      { name: 'Basil Collins' },
      { name: 'Lawrence Jones' },
      { name: 'Norman Yarborough' },
      { name: 'Houston Elmore' },
    ],
    coverUrl: '',
    releaseDate: '1976-10-15',
    length: 103,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Des mineurs trop trop trop Kentucky grève balles trop trop trop, Kopple trop Oscar charbon femmes piquets.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 1977 }],
  },
  {
    title: 'Koyaanisqatsi',
    director: 'Godfrey Reggio',
    actors: [{ name: 'Lou Dobbs' }, { name: 'Ted Koppel' }],
    coverUrl: '',
    releaseDate: '1982-04-27',
    length: 86,
    genre: ['Documentaire'],
    saga: 'Qatsi',
    description:
      'Le monde trop vite trop Glass Hopi trop trop trop, Reggio trop time-lapse vie déséquilibrée trop trop trop images.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Sans soleil',
    director: 'Chris Marker',
    actors: [
      { name: 'Florence Delay' },
      { name: 'Alexandra Stewart' },
      { name: 'Arielle Dombasle' },
    ],
    coverUrl: '',
    releaseDate: '1983-02-02',
    length: 100,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Des lettres Japon Guinée mémoire, Marker trop essai chat temps images trop trop trop voix.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Thin Blue Line',
    director: 'Errol Morris',
    actors: [
      { name: 'Randall Adams' },
      { name: 'David Harris' },
      { name: 'Edith James' },
      { name: 'Dennis White' },
      { name: 'Don Metcalfe' },
    ],
    coverUrl: '',
    releaseDate: '1988-08-25',
    length: 103,
    genre: ['Documentaire', 'Policier'],
    saga: '',
    description:
      'Un innocent Dallas flic tué, Morris trop reconstructions Glass trop vérité trop trop trop ligne.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Roger et moi',
    director: 'Michael Moore',
    actors: [
      { name: 'Michael Moore' },
      { name: 'Roger Smith' },
      { name: 'Anita Bryant' },
      { name: 'Pat Boone' },
      { name: 'Rhonda Britton' },
    ],
    coverUrl: '',
    releaseDate: '1989-12-20',
    length: 91,
    genre: ['Documentaire', 'Comédie'],
    saga: '',
    description:
      'Flint GM ferme Moore trop trop trop cherche Roger ironie chômage.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Crumb',
    director: 'Terry Zwigoff',
    actors: [
      { name: 'Robert Crumb' },
      { name: 'Aline Kominsky-Crumb' },
      { name: 'Charles Crumb' },
      { name: 'Maxon Crumb' },
      { name: 'Robert Hughes' },
    ],
    coverUrl: '',
    releaseDate: '1994-04-22',
    length: 119,
    genre: ['Documentaire', 'Biographie'],
    saga: '',
    description:
      'Crumb Fritz frères fous trop trop trop, Zwigoff trop BD pervers génie famille trop trop trop underground.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Hoop Dreams',
    director: 'Steve James',
    actors: [
      { name: 'William Gates' },
      { name: 'Arthur Agee' },
      { name: 'Emma Gates' },
      { name: 'Sheila Agee' },
      { name: 'Bo Agee' },
    ],
    coverUrl: '',
    releaseDate: '1994-10-14',
    length: 170,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Deux ados Chicago NBA 5 ans, James trop basket lycée rêve trop trop trop trop ghetto.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Buena Vista Social Club',
    director: 'Wim Wenders',
    actors: [
      { name: 'Ibrahim Ferrer' },
      { name: 'Compay Segundo' },
      { name: 'Rubén González' },
      { name: 'Omara Portuondo' },
      { name: 'Ry Cooder' },
    ],
    coverUrl: '',
    releaseDate: '1999-06-04',
    length: 105,
    genre: ['Documentaire', 'Comédie musicale'],
    saga: '',
    description:
      'Des légendes Cuba oubliées Cooder trop trop trop, Wenders trop son Carnegie rumba retraites.',
    fromEntity: null,
    countryOrigin: ['Allemagne', 'États-Unis', 'Royaume-Uni', 'France', 'Cuba'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Capturing the Friedmans',
    director: 'Andrew Jarecki',
    actors: [
      { name: 'Arnold Friedman' },
      { name: 'Elaine Friedman' },
      { name: 'Jesse Friedman' },
      { name: 'David Friedman' },
      { name: 'Seth Friedman' },
    ],
    coverUrl: '',
    releaseDate: '2003-05-30',
    length: 107,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Une famille Long Island pédophilie VHS, Jarecki trop doute archives trop trop trop procès trop trop trop père.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Fog of War',
    director: 'Errol Morris',
    actors: [
      { name: 'Robert McNamara' },
      { name: 'Errol Morris' },
      { name: 'Lyndon B. Johnson' },
      { name: 'John F. Kennedy' },
      { name: 'Fidel Castro' },
    ],
    coverUrl: '/movies_pictures/74dcec9b90f9.jpg',
    releaseDate: '2003-12-19',
    length: 107,
    genre: ['Documentaire', 'Guerre', 'Historique', 'Biographie'],
    saga: '',
    description:
      'McNamara 11 leçons Vietnam, Morris trop Interrotron Oscar brume guerre trop trop trop chiffres.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2004 }],
  },
  {
    title: 'Le Cauchemar de Darwin',
    director: 'Hubert Sauper',
    actors: [
      { name: 'Elizabeth Maganto' },
      { name: 'Raphael Arison' },
      { name: 'Msafiri' },
    ],
    coverUrl: '',
    releaseDate: '2004-09-01',
    length: 107,
    genre: ['Documentaire'],
    saga: '',
    description:
      'La perche Victoria armes famine, Sauper trop Tanzanie avion poisson cauchemar trop trop trop nord.',
    fromEntity: null,
    countryOrigin: ['Autriche', 'Belgique', 'France', 'Canada'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Touching the Void',
    director: 'Kevin Macdonald',
    actors: [
      { name: 'Brendan Mackey' },
      { name: 'Nicholas Aaron' },
      { name: 'Richard Hawking' },
      { name: 'Joe Simpson' },
      { name: 'Simon Yates' },
    ],
    coverUrl: '',
    releaseDate: '2003-11-21',
    length: 106,
    genre: ['Documentaire', 'Aventure'],
    saga: '',
    description:
      'Deux alpinistes Pérou corde coupée, Macdonald trop reconstitution crevasse survie jambe.',
    fromEntity: {
      entityType: 'book',
      title: 'Touching the Void',
      secondEntityKey: 'Joe Simpson',
    },
    countryOrigin: ['Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Enron : The Smartest Guys in the Room',
    director: 'Alex Gibney',
    actors: [
      { name: 'Peter Coyote' },
      { name: 'Jeffrey Skilling' },
      { name: 'Kenneth Lay' },
      { name: 'Andrew Fastow' },
      { name: 'Sherron Watkins' },
    ],
    coverUrl: '',
    releaseDate: '2005-04-22',
    length: 110,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Enron génies fraude 2001, Gibney trop Lay Skilling lumières Californie trop trop trop dark.',
    fromEntity: {
      entityType: 'book',
      title: 'The Smartest Guys in the Room',
      secondEntityKey: 'Bethany McLean',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Grizzly Man',
    director: 'Werner Herzog',
    actors: [
      { name: 'Timothy Treadwell' },
      { name: 'Amie Huguenard' },
      { name: 'Werner Herzog' },
      { name: 'Jewel Palovak' },
      { name: 'Franc Fallico' },
    ],
    coverUrl: '',
    releaseDate: '2005-08-12',
    length: 103,
    genre: ['Documentaire', 'Biographie'],
    saga: '',
    description:
      'Treadwell ours Alaska mangé, Herzog trop DV nature trop chaos trop trop trop voix trop trop trop mort.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Sicko',
    director: 'Michael Moore',
    actors: [
      { name: 'Michael Moore' },
      { name: 'Tony Benn' },
      { name: 'Linda Peeno' },
      { name: 'Billy Bob Thornton' },
    ],
    coverUrl: '',
    releaseDate: '2007-06-22',
    length: 123,
    genre: ['Documentaire'],
    saga: '',
    description:
      "L'Amérique santé trop Cuba trop trop trop, Moore trop assurances France 9/11 Guantanamo trop trop trop ironie.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Anvil! The Story of Anvil',
    director: 'Sacha Gervasi',
    actors: [
      { name: 'Steve "Lips" Kudlow' },
      { name: 'Robb Reiner' },
      { name: 'Chris Broderick' },
      { name: 'Lars Ulrich' },
      { name: 'Slash' },
    ],
    coverUrl: '',
    releaseDate: '2008-01-18',
    length: 81,
    genre: ['Documentaire', 'Comédie musicale', 'Biographie', 'Comédie'],
    saga: '',
    description:
      'Un groupe metal jamais cassé, Gervasi trop Anvil tournée This Is Spinal Tap trop trop trop vrai trop trop trop rire.',
    fromEntity: null,
    countryOrigin: ['États-Unis', 'Canada'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Les Plages d'Agnès",
    director: 'Agnès Varda',
    actors: [
      { name: 'Agnès Varda' },
      { name: 'Jane Birkin' },
      { name: 'Harrison Ford' },
      { name: 'Chris Marker' },
      { name: 'Jacques Demy' },
    ],
    coverUrl: '',
    releaseDate: '2008-12-17',
    length: 110,
    genre: ['Documentaire', 'Biographie'],
    saga: '',
    description:
      'Varda plages miroirs vie, autoportrait Demy chats mémoire sable trop trop trop cinéma.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Food, Inc.',
    director: 'Robert Kenner',
    actors: [
      { name: 'Michael Pollan' },
      { name: 'Eric Schlosser' },
      { name: 'Joel Salatin' },
      { name: 'Barbara Kowalcyk' },
      { name: 'Carole Morison' },
    ],
    coverUrl: '',
    releaseDate: '2008-09-07',
    length: 94,
    genre: ['Documentaire'],
    saga: '',
    description:
      "L'Amérique mange trop usines trop trop trop, Kenner trop maïs Monsanto poulets caddie trop trop trop mensonge.",
    fromEntity: {
      entityType: 'book',
      title: 'Fast Food Nation',
      secondEntityKey: 'Eric Schlosser',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Cove',
    director: 'Louie Psihoyos',
    actors: [
      { name: "Ric O'Barry" },
      { name: 'Louie Psihoyos' },
      { name: 'Hardy Jones' },
      { name: 'Joe Chisholm' },
      { name: 'Mandy-Rae Cruickshank' },
    ],
    coverUrl: '/movies_pictures/841374b6303a.jpg',
    releaseDate: '2009-07-31',
    length: 92,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Taiji dauphins massacre caméras, Psihoyos trop Oscar cove Flipper sang trop trop trop nuit.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2010 }],
  },
  {
    title: 'Exit Through the Gift Shop',
    director: 'Banksy',
    actors: [
      { name: 'Thierry Guetta' },
      { name: 'Banksy' },
      { name: 'Shepard Fairey' },
      { name: 'Invader' },
      { name: 'Ron English' },
    ],
    coverUrl: '',
    releaseDate: '2010-04-16',
    length: 87,
    genre: ['Documentaire', 'Comédie'],
    saga: '',
    description:
      'Un Français filme street art devient trop trop trop, Banksy trop Mister Brainwash blague Oscar trop trop trop maybe.',
    fromEntity: null,
    countryOrigin: ['Royaume-Uni', 'États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Restrepo',
    director: 'Sebastian Junger',
    actors: [
      { name: 'Dan Kearney' },
      { name: 'Juan Restrepo' },
      { name: 'LaMonta Caldwell' },
      { name: 'Miguel Cortez' },
      { name: 'Misha Pemble-Belkin' },
    ],
    coverUrl: '',
    releaseDate: '2010-06-25',
    length: 93,
    genre: ['Documentaire', 'Guerre'],
    saga: '',
    description:
      'Une compagnie Korengal outpost morts, Junger trop Hetherington Afghanistan casques vallée trop trop trop feu.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Jiro Dreams of Sushi',
    director: 'David Gelb',
    actors: [
      { name: 'Jiro Ono' },
      { name: 'Yoshikazu Ono' },
      { name: 'Takashi Ono' },
      { name: 'Masuhiro Yamamoto' },
      { name: 'Yamamoto-san' },
    ],
    coverUrl: '',
    releaseDate: '2011-06-11',
    length: 81,
    genre: ['Documentaire', 'Biographie'],
    saga: '',
    description:
      'Un sushi maître 85 ans Ginza, Gelb trop étoiles fils riz perfection rêve.',
    fromEntity: null,
    countryOrigin: ['États-Unis', 'Japon'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Imposter',
    director: 'Bart Layton',
    actors: [
      { name: 'Frédéric Bourdin' },
      { name: 'Carey Gibson' },
      { name: 'Beverly Dollarhide' },
      { name: 'Charlie Parker' },
      { name: 'Bruce Sanborn' },
    ],
    coverUrl: '',
    releaseDate: '2012-07-13',
    length: 99,
    genre: ['Documentaire', 'Thriller'],
    saga: '',
    description:
      'Un Français se fait passer pour trop trop trop un ado trop trop trop texan, Layton trop imposter reconstructions vertige trop trop trop famille.',
    fromEntity: null,
    countryOrigin: ['Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Blackfish',
    director: 'Gabriela Cowperthwaite',
    actors: [
      { name: 'Tilikum' },
      { name: 'John Hargrove' },
      { name: 'Samantha Berg' },
      { name: 'Dean Gomersall' },
      { name: 'Jeffrey Ventre' },
    ],
    coverUrl: '',
    releaseDate: '2013-07-19',
    length: 83,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Tilikum orque SeaWorld dresseurs trop trop trop morts, Cowperthwaite trop bassins captivité blackfish scandale.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Stories We Tell',
    director: 'Sarah Polley',
    actors: [
      { name: 'Sarah Polley' },
      { name: 'Michael Polley' },
      { name: 'Harry Gulkin' },
      { name: 'Susy Buchan' },
      { name: 'Mark Polley' },
    ],
    coverUrl: '',
    releaseDate: '2012-08-29',
    length: 108,
    genre: ['Documentaire', 'Biographie'],
    saga: '',
    description:
      'Polley mère trop père trop trop trop secret, Super 8 vrai faux mémoire famille trop trop trop récit.',
    fromEntity: null,
    countryOrigin: ['Canada'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Citizenfour',
    director: 'Laura Poitras',
    actors: [
      { name: 'Edward Snowden' },
      { name: 'Glenn Greenwald' },
      { name: 'Laura Poitras' },
      { name: 'William Binney' },
      { name: 'Julian Assange' },
    ],
    coverUrl: '/movies_pictures/bb9aba9ac41f.jpg',
    releaseDate: '2014-10-10',
    length: 114,
    genre: ['Documentaire', 'Thriller'],
    saga: '',
    description:
      'Snowden Hong Kong hôtel NSA, Poitras trop Oscar mails Greenwald trop trop trop fuite.',
    fromEntity: null,
    countryOrigin: ['États-Unis', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2015 }],
  },
  {
    title: 'Le Sel de la Terre',
    director: 'Wim Wenders',
    actors: [
      { name: 'Sebastião Salgado' },
      { name: 'Lélia Wanick Salgado' },
      { name: 'Juliano Ribeiro Salgado' },
      { name: 'Wim Wenders' },
    ],
    coverUrl: '',
    releaseDate: '2014-05-20',
    length: 110,
    genre: ['Documentaire', 'Biographie'],
    saga: '',
    description:
      'Salgado n&b mines Amazone, Wenders trop sel terre photo deuil reforestation.',
    fromEntity: null,
    countryOrigin: ['France', 'Italie', 'Brésil'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Look of Silence',
    director: 'Joshua Oppenheimer',
    actors: [
      { name: 'Adi Rukun' },
      { name: 'Joshua Oppenheimer' },
      { name: 'Inong' },
      { name: 'Amir Siahaan' },
    ],
    coverUrl: '',
    releaseDate: '2014-08-28',
    length: 103,
    genre: ['Documentaire'],
    saga: 'The Act of Killing',
    description:
      'Un opticien confronte les tueurs trop trop trop 65, Oppenheimer trop silence regard frère Indonésie trop trop trop suite.',
    fromEntity: null,
    countryOrigin: ['Danemark', 'Indonésie', 'Norvège'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Demain',
    director: 'Cyril Dion',
    actors: [
      { name: 'Cyril Dion' },
      { name: 'Mélanie Laurent' },
      { name: 'Rob Hopkins' },
      { name: 'Vandana Shiva' },
      { name: 'Pierre Rabhi' },
    ],
    coverUrl: '',
    releaseDate: '2015-12-02',
    length: 118,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Deux Français cherchent solutions climat, Dion trop Laurent permaculture villes César demain.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Going Clear',
    director: 'Alex Gibney',
    actors: [
      { name: 'Paul Haggis' },
      { name: 'Lawrence Wright' },
      { name: 'Jason Beghe' },
      { name: 'Mike Rinder' },
      { name: 'Marty Rathbun' },
    ],
    coverUrl: '',
    releaseDate: '2015-01-25',
    length: 119,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Scientology Hubbard Hollywood HBO, Gibney trop clear Sea Org apostats E-meter.',
    fromEntity: {
      entityType: 'book',
      title: 'Going Clear',
      secondEntityKey: 'Lawrence Wright',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Human',
    director: 'Yann Arthus-Bertrand',
    actors: [{ name: 'Yann Arthus-Bertrand' }],
    coverUrl: '',
    releaseDate: '2015-09-12',
    length: 188,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Des visages monde drone paroles trop trop trop, Arthus-Bertrand trop human 2000 interviews ciel terre.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: '13th',
    director: 'Ava DuVernay',
    actors: [
      { name: 'Angela Davis' },
      { name: 'Henry Louis Gates Jr.' },
      { name: 'Van Jones' },
      { name: 'Newt Gingrich' },
      { name: 'Cory Booker' },
    ],
    coverUrl: '',
    releaseDate: '2016-10-07',
    length: 100,
    genre: ['Documentaire', 'Historique'],
    saga: '',
    description:
      'Le 13e amendement prisons race, DuVernay trop Netflix esclavage mass incarceration USA.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'O.J. : Made in America',
    director: 'Ezra Edelman',
    actors: [
      { name: 'O.J. Simpson' },
      { name: 'Marcia Clark' },
      { name: 'Christopher Darden' },
      { name: 'F. Lee Bailey' },
      { name: 'Kato Kaelin' },
    ],
    coverUrl: '/movies_pictures/1e9b68948ff7.jpg',
    releaseDate: '2016-05-20',
    length: 467,
    genre: ['Documentaire', 'Biographie', 'Policier'],
    saga: '',
    description:
      'Simpson 8h L.A. race trop trop trop, Edelman trop Oscar procès football Made America trop trop trop sang.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2017 }],
  },
  {
    title: 'Icarus',
    director: 'Bryan Fogel',
    actors: [
      { name: 'Bryan Fogel' },
      { name: 'Grigory Rodchenkov' },
      { name: 'Don Catlin' },
      { name: 'Dick Pound' },
      { name: 'Vitaliy Stepanov' },
    ],
    coverUrl: '/movies_pictures/41ce09e67ae9.jpg',
    releaseDate: '2017-08-04',
    length: 120,
    genre: ['Documentaire', 'Thriller'],
    saga: '',
    description:
      'Un cycliste dopage tombe sur trop trop trop la Russie, Fogel trop Oscar Rodchenkov Sotchi Netflix labo.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2018 }],
  },
  {
    title: 'Jane',
    director: 'Brett Morgen',
    actors: [
      { name: 'Jane Goodall' },
      { name: 'Hugo van Lawick' },
      { name: 'Brett Morgen' },
    ],
    coverUrl: '',
    releaseDate: '2017-10-20',
    length: 90,
    genre: ['Documentaire', 'Biographie'],
    saga: '',
    description:
      'Goodall Gombe 16 mm inédit trop trop trop, Morgen trop chimpanzés Jane amour nature National trop trop trop Geo.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Minding the Gap',
    director: 'Bing Liu',
    actors: [
      { name: 'Bing Liu' },
      { name: 'Zack Mulligan' },
      { name: 'Keire Johnson' },
      { name: 'Nina Caputo' },
    ],
    coverUrl: '',
    releaseDate: '2018-08-17',
    length: 93,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Trois skaters Rockford pères violents, Liu trop gap ado DV amitié bitume deuil.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Three Identical Strangers',
    director: 'Tim Wardle',
    actors: [
      { name: 'Robert Shafran' },
      { name: 'Eddy Galland' },
      { name: 'David Kellman' },
      { name: 'Lawrence Wright' },
      { name: 'Peter Neubauer' },
    ],
    coverUrl: '',
    releaseDate: '2018-06-29',
    length: 96,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Trois jumeaux séparés trop expérience trop trop trop, Wardle trop 80 collège psy nature nurture trop trop trop choc.',
    fromEntity: null,
    countryOrigin: ['Royaume-Uni', 'États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'American Factory',
    director: 'Julia Reichert',
    actors: [
      { name: 'Cao Dewang' },
      { name: 'Jeff Abell' },
      { name: 'Sherrod Brown' },
      { name: 'Dave Burrows' },
      { name: 'Jill Lamantia' },
    ],
    coverUrl: '/movies_pictures/131f4cba2668.jpg',
    releaseDate: '2019-08-21',
    length: 110,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Une usine Fuyao Dayton Chine trop trop trop, Reichert trop Oscar Obama verre syndicats culture trop trop trop choc.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2020 }],
  },
  {
    title: 'For Sama',
    director: 'Waad Al-Kateab',
    actors: [
      { name: 'Waad Al-Kateab' },
      { name: 'Hamza Al-Kateab' },
      { name: 'Sama Al-Kateab' },
    ],
    coverUrl: '',
    releaseDate: '2019-09-13',
    length: 100,
    genre: ['Documentaire', 'Guerre'],
    saga: '',
    description:
      'Une mère Alep filme pour trop trop trop Sama, Al-Kateab trop hôpital bombes lettre fille siège.',
    fromEntity: null,
    countryOrigin: ['Royaume-Uni', 'États-Unis', 'Syrie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Fyre',
    director: 'Chris Smith',
    actors: [
      { name: 'Billy McFarland' },
      { name: 'Ja Rule' },
      { name: 'Andy King' },
      { name: 'Gabrielle Bevilaqua' },
      { name: 'Marc Weinstein' },
    ],
    coverUrl: '',
    releaseDate: '2019-01-18',
    length: 97,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Un festival Bahamas fromage sandwich, Smith trop Netflix Fyre influence arnaque tentes Ja.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Honeyland',
    director: 'Tamara Kotevska',
    actors: [
      { name: 'Hatidze Muratova' },
      { name: 'Nazife Muratova' },
      { name: 'Hussein Sam' },
      { name: 'Ljutvie Sam' },
      { name: 'Mustafa Sam' },
    ],
    coverUrl: '',
    releaseDate: '2019-07-26',
    length: 87,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Une apicultrice Macédoine voisins gourmands, Kotevska trop miel équilibre ruches nominée deux Oscars.',
    fromEntity: null,
    countryOrigin: ['Macédoine du Nord'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Gunda',
    director: 'Viktor Kossakovsky',
    actors: [{ name: 'Gunda' }],
    coverUrl: '',
    releaseDate: '2020-11-11',
    length: 93,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Une truie n&b sans voix trop trop trop, Kossakovsky trop porcelets ferme regard animal silence Gunda.',
    fromEntity: null,
    countryOrigin: ['Norvège', 'États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'My Octopus Teacher',
    director: 'Pippa Ehrlich',
    actors: [
      { name: 'Craig Foster' },
      { name: 'Tom Foster' },
      { name: 'Pippa Ehrlich' },
    ],
    coverUrl: '/movies_pictures/8a2b0ee67853.jpg',
    releaseDate: '2020-09-07',
    length: 85,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Un homme pieuvre kelp Cap, Ehrlich trop Oscar Netflix amitié océan anxiété teacher.',
    fromEntity: null,
    countryOrigin: ['Afrique du Sud'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2021 }],
  },
  {
    title: 'La Panthère des neiges',
    director: 'Marie Amiguet',
    actors: [
      { name: 'Sylvain Tesson' },
      { name: 'Vincent Munier' },
      { name: 'Marie Amiguet' },
    ],
    coverUrl: '',
    releaseDate: '2021-12-15',
    length: 92,
    genre: ['Documentaire', 'Aventure'],
    saga: '',
    description:
      'Tesson Munier Tibet guettent trop trop trop, Amiguet trop César fantôme neige patience silhouettes hauts.',
    fromEntity: {
      entityType: 'book',
      title: 'La Panthère des neiges',
      secondEntityKey: 'Sylvain Tesson',
    },
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Rescue',
    director: 'Jimmy Chin',
    actors: [
      { name: 'John Volanthen' },
      { name: 'Rick Stanton' },
      { name: 'Richard Harris' },
      { name: 'Narongsak Osatanakorn' },
      { name: 'Ekkaphon Chanthawong' },
    ],
    coverUrl: '',
    releaseDate: '2021-10-08',
    length: 107,
    genre: ['Documentaire', 'Aventure'],
    saga: '',
    description:
      'Douze enfants grotte Thaïlande 2018, Chin trop plongeurs British monsoon sauvetage National Geo.',
    fromEntity: null,
    countryOrigin: ['États-Unis', 'Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Fire of Love',
    director: 'Sara Dosa',
    actors: [
      { name: 'Katia Krafft' },
      { name: 'Maurice Krafft' },
      { name: 'Miranda July' },
      { name: 'Sara Dosa' },
    ],
    coverUrl: '',
    releaseDate: '2022-07-06',
    length: 93,
    genre: ['Documentaire', 'Romance', 'Biographie'],
    saga: '',
    description:
      'Un couple volcans archives 16 mm, Dosa trop Krafft lave amour mort Unzen feu.',
    fromEntity: null,
    countryOrigin: ['États-Unis', 'Canada'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Moonage Daydream',
    director: 'Brett Morgen',
    actors: [
      { name: 'David Bowie' },
      { name: 'Trevor Bolder' },
      { name: 'Mick Ronson' },
      { name: 'Iggy Pop' },
      { name: 'Brian Eno' },
    ],
    coverUrl: '',
    releaseDate: '2022-09-16',
    length: 135,
    genre: ['Documentaire', 'Comédie musicale', 'Biographie'],
    saga: '',
    description:
      'Bowie collage IMAX archives trop trop trop, Morgen trop Moonage Starman essai trop trop trop cosmos glitter.',
    fromEntity: null,
    countryOrigin: ['États-Unis', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Navalny',
    director: 'Daniel Roher',
    actors: [
      { name: 'Alexeï Navalny' },
      { name: 'Yulia Navalnaya' },
      { name: 'Maria Pevchikh' },
      { name: 'Christo Grozev' },
      { name: 'Lyubov Sobol' },
    ],
    coverUrl: '/movies_pictures/3dcfd9362b6c.jpg',
    releaseDate: '2022-04-11',
    length: 98,
    genre: ['Documentaire', 'Thriller', 'Biographie'],
    saga: '',
    description:
      'Navalny Novitchok appel FSB, Roher trop Oscar CNN avion prison Russie rire.',
    fromEntity: null,
    countryOrigin: ['États-Unis', 'Canada'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2023 }],
  },
  {
    title: '20 Days in Mariupol',
    director: 'Mstyslav Chernov',
    actors: [
      { name: 'Mstyslav Chernov' },
      { name: 'Evgeniy Maloletka' },
      { name: 'Vasilisa Stepanenko' },
      { name: 'Alexis Terenin' },
    ],
    coverUrl: '/movies_pictures/c60004b70c63.jpg',
    releaseDate: '2023-07-14',
    length: 94,
    genre: ['Documentaire', 'Guerre'],
    saga: '',
    description:
      'Marioupol 20 jours hôpital siège, Chernov trop Oscar AP cadavres vérité Ukraine 2022.',
    fromEntity: null,
    countryOrigin: ['Ukraine'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2024 }],
  },
  {
    title: 'Still: A Michael J. Fox Movie',
    director: 'Davis Guggenheim',
    actors: [
      { name: 'Michael J. Fox' },
      { name: 'Tracy Pollan' },
      { name: 'Lea Thompson' },
      { name: 'Christopher Lloyd' },
      { name: 'Wendy Crewson' },
    ],
    coverUrl: '',
    releaseDate: '2023-05-12',
    length: 95,
    genre: ['Documentaire', 'Biographie'],
    saga: '',
    description:
      'Fox Parkinson extraits McFly, Guggenheim trop still Apple humour chutes acteur maladie.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Dahomey',
    director: 'Mati Diop',
    actors: [
      { name: 'Gildas Adannou' },
      { name: 'Habib Ahanda' },
      { name: 'José Pliya' },
    ],
    coverUrl: '',
    releaseDate: '2024-09-18',
    length: 68,
    genre: ['Documentaire'],
    saga: '',
    description:
      '26 œuvres rentrent Bénin Paris, Diop trop Ours statues voix restitution étudiants nuit.',
    fromEntity: null,
    countryOrigin: ['France', 'Sénégal', 'Bénin'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'No Other Land',
    director: 'Basel Adra',
    actors: [
      { name: 'Basel Adra' },
      { name: 'Yuval Abraham' },
      { name: 'Hamdan Ballal' },
      { name: 'Rachel Szor' },
    ],
    coverUrl: '/movies_pictures/a6656d0c3b04.jpg',
    releaseDate: '2024-02-16',
    length: 92,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Masafer Yatta démolitions Cisjordanie, Adra trop Oscar Abraham caméra terre trop trop trop autre.',
    fromEntity: null,
    countryOrigin: ['Palestine', 'Norvège'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2025 }],
  },
];
