import { BaseMovie, OscarEnum } from '../../../models/movie-model';

export const baseMoviesWestern: BaseMovie[] = [
  {
    title: 'True Grit',
    director: 'Joel Coen, Ethan Coen',
    actors: [
      {
        name: 'Jeff Bridges',
      },
      {
        name: 'Matt Damon',
      },
      {
        name: 'Josh Brolin',
      },
      {
        name: 'Hailee Steinfeld',
      },
      {
        name: 'Barry Pepper',
      },
      {
        name: 'Domhnall Gleeson',
      },
      {
        name: 'Leon Russom',
      },
    ],
    coverUrl:
      '/movies_pictures/MV5BMTU5MjU3MTI4OF5BMl5BanBnXkFtZTcwMTQxOTAxNA@@._V1_FMjpg_UX1000_.jpg',
    releaseDate: '2010-12-22',
    length: 110,
    genre: ['Western'],
    saga: '',
    description: '',
    fromEntity: {
      entityType: 'book',
      title: "True Grit",
      secondEntityKey: "Charles Portis",
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Mort ou vif',
    director: 'Sam Raimi',
    actors: [
      {
        name: 'Leonardo DiCaprio',
      },
      {
        name: 'Sharon Stone',
      },
      {
        name: 'Russell Crowe',
      },
      {
        name: 'Gene Hackman',
      },
      {
        name: 'Keith David',
      },
      {
        name: 'Tobin Bell',
      },
      {
        name: 'Pat Hingle',
      },
    ],
    coverUrl: '/movies_pictures/0495354.webp',
    releaseDate: '1995-09-08',
    length: 108,
    genre: ['Western'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: '3 h 10 pour Yuma',
    director: 'James Mangold',
    actors: [
      {
        name: 'Russell Crowe',
      },
      {
        name: 'Christian Bale',
      },
      {
        name: 'Logan Lerman',
      },
      {
        name: 'Dallas Roberts',
      },
      {
        name: 'Ben Foster',
      },
      {
        name: 'Alan Tudyk',
      },
      {
        name: 'Peter Fonda',
      },
    ],
    coverUrl: '/movies_pictures/18922562.jpg',
    releaseDate: '2007-09-07',
    length: 122,
    genre: ['Western'],
    saga: '',
    description: '',
    fromEntity: {
      entityType: 'book',
      title: "Three-Ten to Yuma",
      secondEntityKey: "Elmore Leonard",
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Hostiles',
    director: 'Scott Cooper',
    actors: [
      {
        name: 'Christian Bale',
      },
      {
        name: 'Rosamund Pike',
      },
      {
        name: 'Wes Studi',
      },
      {
        name: 'Jesse Plemons',
      },
      {
        name: 'Adam Beach',
      },
      {
        name: 'Rory Cochrane',
      },
      {
        name: 'Ben Foster',
      },
    ],
    coverUrl: '/movies_pictures/5152324.webp',
    releaseDate: '2017-12-22',
    length: 134,
    genre: ['Western'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Impitoyable',
    director: 'Clint Eastwood',
    actors: [
      {
        name: 'Gene Hackman',
      },
      {
        name: 'Morgan Freeman',
      },
      {
        name: 'Richard Harris',
      },
      {
        name: 'Saul Rubinek',
      },
      {
        name: 'Frances Fisher',
      },
      {
        name: 'Anna Thomson',
      },
      {
        name: 'Jaimz Woolvett',
      },
    ],
    coverUrl: '/movies_pictures/455505.jpg',
    releaseDate: '1992-08-03',
    length: 131,
    genre: ['Western'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_MOVIE, year: 1993 },
      { type: OscarEnum.OSCAR_BEST_DIRECTOR, year: 1993 },
      { type: OscarEnum.OSCAR_BEST_SUPPORTING_ACTOR, year: 1993 },
      { type: OscarEnum.OSCAR_BEST_FILM_EDITING, year: 1993 },
    ],
  },
  {
    title: 'Le Bon, la brute et le truand',
    director: 'Sergio Leone',
    actors: [
      {
        name: 'Clint Eastwood',
      },
      {
        name: 'Lee Van Cleef',
      },
      {
        name: 'Eli Wallach',
      },
      {
        name: 'Mario Brega',
      },
      {
        name: 'Aldo Giuffrè',
      },
      {
        name: 'Luigi Pistilli',
      },
      {
        name: 'Antonio Casale',
      },
    ],
    coverUrl: '/movies_pictures/237103.webp',
    releaseDate: '1966-12-23',
    length: 178,
    genre: ['Western'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Danse avec les loups',
    director: 'Kevin Costner',
    actors: [
      {
        name: 'Mary McDonnell',
      },
      {
        name: 'Rodney A. Grant',
      },
      {
        name: 'Kevin Costner',
      },
      {
        name: 'Graham Greene',
      },
      {
        name: 'Maury Chaykin',
      },
      {
        name: 'Floyd Westerman',
      },
      {
        name: 'Wes Studi',
      },
    ],
    coverUrl: '/movies_pictures/19672460.jpg',
    releaseDate: '1990-11-21',
    length: 181,
    genre: ['Western'],
    saga: '',
    description: '',
    fromEntity: {
      entityType: 'book',
      title: "Danse avec les loups",
      secondEntityKey: "Michael Blake",
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_MOVIE, year: 1991 },
      { type: OscarEnum.OSCAR_BEST_DIRECTOR, year: 1991 },
      { type: OscarEnum.OSCAR_BEST_ADAPTED_SCREENPLAY, year: 1991 },
      { type: OscarEnum.OSCAR_BEST_ORIGINAL_SCORE, year: 1991 },
      { type: OscarEnum.OSCAR_BEST_CINEMATOGRAPHY, year: 1991 },
      { type: OscarEnum.OSCAR_BEST_FILM_EDITING, year: 1991 },
      { type: OscarEnum.OSCAR_BEST_SOUND, year: 1991 },
    ],
  },
  {
    title: 'Et pour quelques dollars de plus',
    director: 'Sergio Leone',
    actors: [
      {
        name: 'Clint Eastwood',
      },
      {
        name: 'Lee Van Cleef',
      },
      {
        name: 'Gian Maria Volontè',
      },
      {
        name: 'Mario Brega',
      },
      {
        name: 'Luigi Pistilli',
      },
      {
        name: 'Klaus Kinski',
      },
      {
        name: 'Joseph Egger',
      },
    ],
    coverUrl: '/movies_pictures/19182254.jpg',
    releaseDate: '1965-12-18',
    length: 132,
    genre: ['Western'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Maverick',
    director: 'Richard Donner',
    actors: [
      {
        name: 'James Garner',
      },
      {
        name: 'Jack Kelly',
      },
      {
        name: 'Roger Moore',
      },
      {
        name: 'Robert Colbert',
      },
      {
        name: 'Roxane Berard',
      },
    ],
    coverUrl: '/movies_pictures/18868904.webp',
    releaseDate: '1994-01-01',
    length: 127,
    genre: ['Western'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Jane Got a Gun',
    director: "Gavin O'Connor",
    actors: [
      {
        name: 'Natalie Portman',
      },
      {
        name: 'Joel Edgerton',
      },
      {
        name: 'Ewan McGregor',
      },
      {
        name: 'Rodrigo Santoro',
      },
      {
        name: 'Noah Emmerich',
      },
      {
        name: 'Boyd Holbrook',
      },
      {
        name: 'Alex Manette',
      },
    ],
    coverUrl: '/movies_pictures/446034.webp',
    releaseDate: '2016-01-01',
    length: 98,
    genre: ['Western'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },

  {
    title: 'Les Huit Salopards',
    director: 'Quentin Tarantino',
    actors: [
      { name: 'Samuel L. Jackson' },
      { name: 'Kurt Russell' },
      { name: 'Jennifer Jason Leigh' },
      { name: 'Walton Goggins' },
      { name: 'Tim Roth' },
      { name: 'Michael Madsen' },
      { name: 'Bruce Dern' },
    ],
    coverUrl: '/movies_pictures/the_hateful_eight.jpg',
    releaseDate: '2016-01-06',
    length: 167,
    genre: ['Western'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 5,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_ORIGINAL_SCORE, year: 2016 },
    ],
  },
  {
    title: "Il était une fois dans l'Ouest",
    director: 'Sergio Leone',
    actors: [
      { name: 'Claudia Cardinale' },
      { name: 'Henry Fonda' },
      { name: 'Charles Bronson' },
      { name: 'Jason Robards' },
      { name: 'Gabriele Ferzetti' },
      { name: 'Paolo Stoppa' },
      { name: 'Frank Wolff' },
    ],
    coverUrl: '/movies_pictures/03454bc973db.jpg',
    releaseDate: '1969-08-27',
    length: 165,
    genre: ['Western'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 30,
    oscars: [],
  },
  {
    title: 'Cimarron',
    director: 'Wesley Ruggles',
    actors: [
      { name: 'Richard Dix' },
      { name: 'Irene Dunne' },
      { name: 'Estelle Taylor' },
      { name: "Nance O'Neil" },
      { name: 'William Collier Jr.' },
    ],
    coverUrl: '/movies_pictures/f7d443d36172.jpg',
    releaseDate: '1931-01-26',
    length: 123,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      "Un pionnier et sa femme suivent la ruée vers l'Oklahoma, de la terre promise aux compromis de la civilisation.",
    fromEntity: {
      entityType: 'book',
      title: 'Cimarron',
      secondEntityKey: 'Edna Ferber',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_MOVIE, year: 1931 },
      { type: OscarEnum.OSCAR_BEST_ADAPTED_SCREENPLAY, year: 1931 },
      { type: OscarEnum.OSCAR_BEST_PRODUCTION_DESIGN, year: 1931 },
    ],
  },
  {
    title: 'Femme ou démon',
    director: 'George Marshall',
    actors: [
      { name: 'Marlene Dietrich' },
      { name: 'James Stewart' },
      { name: 'Mischa Auer' },
      { name: 'Charles Winninger' },
      { name: 'Brian Donlevy' },
    ],
    coverUrl: '/movies_pictures/a70936fb6423.jpg',
    releaseDate: '1939-12-29',
    length: 94,
    genre: ['Western', 'Comédie'],
    saga: '',
    description:
      'Un shérif pacifique débarque à Bottleneck et croise Frenchy, chanteuse de saloon, entre vaches et revolvers.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Chevauchée fantastique',
    director: 'John Ford',
    actors: [
      { name: 'John Wayne' },
      { name: 'Claire Trevor' },
      { name: 'Thomas Mitchell' },
      { name: 'Andy Devine' },
      { name: 'John Carradine' },
    ],
    coverUrl: '/movies_pictures/8e2d35452f82.jpg',
    releaseDate: '1939-03-02',
    length: 96,
    genre: ['Western', 'Aventure'],
    saga: '',
    description:
      'Une diligence traverse le territoire apache : un outlaw, une prostituée, un ivrogne, un banquier et un joueur.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_SUPPORTING_ACTOR, year: 1940 },
      { type: OscarEnum.OSCAR_BEST_ORIGINAL_SCORE, year: 1940 },
    ],
  },
  {
    title: 'La Poursuite infernale',
    director: 'John Ford',
    actors: [
      { name: 'Henry Fonda' },
      { name: 'Linda Darnell' },
      { name: 'Victor Mature' },
      { name: 'Cathy Downs' },
      { name: 'Walter Brennan' },
    ],
    coverUrl: '/movies_pictures/7fc7bd8575a9.jpg',
    releaseDate: '1946-12-03',
    length: 97,
    genre: ['Western'],
    saga: '',
    description:
      "Wyatt Earp devient marshal de Tombstone et affronte le clan Clanton, jusqu'à O.K. Corral.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Rivière rouge',
    director: 'Howard Hawks',
    actors: [
      { name: 'John Wayne' },
      { name: 'Montgomery Clift' },
      { name: 'Joanne Dru' },
      { name: 'Walter Brennan' },
      { name: 'Coleen Gray' },
    ],
    coverUrl: '/movies_pictures/6366c93883b5.jpg',
    releaseDate: '1948-08-26',
    length: 133,
    genre: ['Western'],
    saga: '',
    description:
      'Un éleveur tyrannique mène un troupeau vers le Missouri ; son fils adoptif se révolte en chemin.',
    fromEntity: {
      entityType: 'book',
      title: 'La Rivière rouge',
      secondEntityKey: 'Borden Chase',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Massacre de Fort Apache',
    director: 'John Ford',
    actors: [
      { name: 'John Wayne' },
      { name: 'Henry Fonda' },
      { name: 'Shirley Temple' },
      { name: 'Pedro Armendáriz' },
      { name: 'Ward Bond' },
    ],
    coverUrl: '/movies_pictures/c4d98b463f75.jpg',
    releaseDate: '1948-03-27',
    length: 125,
    genre: ['Western'],
    saga: 'La Cavalerie',
    description:
      'Un colonel rigide arrive à Fort Apache et provoque un massacre en sous-estimant les Apache.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Charge héroïque',
    director: 'John Ford',
    actors: [
      { name: 'John Wayne' },
      { name: 'Joanne Dru' },
      { name: 'John Agar' },
      { name: 'Ben Johnson' },
      { name: 'Harry Carey Jr.' },
    ],
    coverUrl: '/movies_pictures/1f955707b5dc.jpg',
    releaseDate: '1949-10-22',
    length: 103,
    genre: ['Western'],
    saga: 'La Cavalerie',
    description:
      'Le capitaine Brittles, à la veille de la retraite, mène une dernière mission chez les Cheyennes.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_CINEMATOGRAPHY, year: 1950 }],
  },
  {
    title: 'Rio Grande',
    director: 'John Ford',
    actors: [
      { name: 'John Wayne' },
      { name: "Maureen O'Hara" },
      { name: 'Ben Johnson' },
      { name: 'Claude Jarman Jr.' },
      { name: 'Harry Carey Jr.' },
    ],
    coverUrl: '/movies_pictures/1af495a75a0f.jpg',
    releaseDate: '1950-11-15',
    length: 105,
    genre: ['Western'],
    saga: 'La Cavalerie',
    description:
      'Un colonel à la frontière mexicaine retrouve sa femme et son fils enrôlé, entre Apache et honneur.',
    fromEntity: {
      entityType: 'book',
      title: "Rashômon",
      secondEntityKey: "Ryunosuke Akutagawa",
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Winchester 73',
    director: 'Anthony Mann',
    actors: [
      { name: 'James Stewart' },
      { name: 'Shelley Winters' },
      { name: 'Dan Duryea' },
      { name: 'Stephen McNally' },
      { name: 'Millard Mitchell' },
    ],
    coverUrl: '/movies_pictures/da06ea784ea8.jpg',
    releaseDate: '1950-07-12',
    length: 92,
    genre: ['Western'],
    saga: '',
    description:
      'Un tireur poursuit son frère, qui lui a volé la carabine parfaite, à travers la Frontière.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le train sifflera trois fois',
    director: 'Fred Zinnemann',
    actors: [
      { name: 'Gary Cooper' },
      { name: 'Grace Kelly' },
      { name: 'Katy Jurado' },
      { name: 'Lloyd Bridges' },
      { name: 'Thomas Mitchell' },
    ],
    coverUrl: '/movies_pictures/e5e2f20a2eb8.jpg',
    releaseDate: '1952-07-24',
    length: 85,
    genre: ['Western'],
    saga: '',
    description:
      'Un marshal le jour de son mariage attend midi et le train qui ramène un tueur, abandonné par la ville.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_ACTOR, year: 1953 },
      { type: OscarEnum.OSCAR_BEST_ORIGINAL_SONG, year: 1953 },
      { type: OscarEnum.OSCAR_BEST_ORIGINAL_SCORE, year: 1953 },
      { type: OscarEnum.OSCAR_BEST_FILM_EDITING, year: 1953 },
    ],
  },
  {
    title: "L'Homme des vallées perdues",
    director: 'George Stevens',
    actors: [
      { name: 'Alan Ladd' },
      { name: 'Jean Arthur' },
      { name: 'Van Heflin' },
      { name: 'Brandon De Wilde' },
      { name: 'Jack Palance' },
    ],
    coverUrl: '/movies_pictures/824f22c4445b.jpg',
    releaseDate: '1953-04-23',
    length: 118,
    genre: ['Western'],
    saga: '',
    description:
      "Un pistoler solitaire défend une famille de colons contre un éleveur, sous les yeux d'un petit garçon.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_CINEMATOGRAPHY, year: 1954 }],
  },
  {
    title: 'Johnny Guitare',
    director: 'Nicholas Ray',
    actors: [
      { name: 'Joan Crawford' },
      { name: 'Sterling Hayden' },
      { name: 'Mercedes McCambridge' },
      { name: 'Scott Brady' },
      { name: 'Ward Bond' },
    ],
    coverUrl: '/movies_pictures/14a1decee0cc.jpg',
    releaseDate: '1954-05-26',
    length: 110,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Vienna, patronne de saloon, attend le chemin de fer ; une rivale et un pistolero nommé Johnny Guitare arrivent.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Rivière sans retour',
    director: 'Otto Preminger',
    actors: [
      { name: 'Robert Mitchum' },
      { name: 'Marilyn Monroe' },
      { name: 'Rory Calhoun' },
      { name: 'Tommy Rettig' },
      { name: 'Murvyn Vye' },
    ],
    coverUrl: '/movies_pictures/b6761085f5eb.jpg',
    releaseDate: '1954-04-29',
    length: 91,
    genre: ['Western', 'Aventure'],
    saga: '',
    description:
      'Un fermier et une chanteuse de saloon descendent une rivière du Nord-Ouest, poursuivis par un bandit.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Homme de la plaine",
    director: 'Anthony Mann',
    actors: [
      { name: 'James Stewart' },
      { name: 'Arthur Kennedy' },
      { name: 'Donald Crisp' },
      { name: "Cathy O'Donnell" },
      { name: 'Alex Nicol' },
    ],
    coverUrl: '/movies_pictures/c8a9613d977a.jpg',
    releaseDate: '1955-08-31',
    length: 104,
    genre: ['Western'],
    saga: '',
    description:
      "Un inconnu arrive à Laramie pour venger son frère ; le shérif et un clan d'éleveurs lui barrent la route.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Prisonnière du désert',
    director: 'John Ford',
    actors: [
      { name: 'John Wayne' },
      { name: 'Jeffrey Hunter' },
      { name: 'Vera Miles' },
      { name: 'Ward Bond' },
      { name: 'Natalie Wood' },
    ],
    coverUrl: '/movies_pictures/8cb0de668bd5.jpg',
    releaseDate: '1956-05-26',
    length: 119,
    genre: ['Western'],
    saga: '',
    description:
      'Ethan Edwards cherche pendant des années sa nièce enlevée par les Comanches, haine raciale comprise.',
    fromEntity: {
      entityType: 'book',
      title: 'The Searchers',
      secondEntityKey: 'Alan Le May',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Sept hommes à abattre',
    director: 'Budd Boetticher',
    actors: [
      { name: 'Randolph Scott' },
      { name: 'Gail Russell' },
      { name: 'Lee Marvin' },
      { name: 'Walter Reed' },
      { name: 'John Larch' },
    ],
    coverUrl: '/movies_pictures/80f034aaba92.jpg',
    releaseDate: '1956-08-04',
    length: 78,
    genre: ['Western'],
    saga: '',
    description:
      'Un shérif à la retraite escorte une diligence et venge sa femme, sept tueurs à abattre.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Homme de l'Arizona",
    director: 'Budd Boetticher',
    actors: [
      { name: 'Randolph Scott' },
      { name: 'Richard Boone' },
      { name: "Maureen O'Sullivan" },
      { name: 'Skip Homeier' },
      { name: 'Henry Silva' },
    ],
    coverUrl: '/movies_pictures/4263e9558430.jpg',
    releaseDate: '1957-04-09',
    length: 78,
    genre: ['Western'],
    saga: '',
    description:
      "Un cowboy rachète un relais de diligence et se retrouve otage d'un bandit charmeur dans un relais isolé.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Homme de l'Ouest",
    director: 'Anthony Mann',
    actors: [
      { name: 'Gary Cooper' },
      { name: 'Julie London' },
      { name: 'Lee J. Cobb' },
      { name: "Arthur O'Connell" },
      { name: 'Jack Lord' },
    ],
    coverUrl: '/movies_pictures/f266b8b8c7a9.jpg',
    releaseDate: '1958-10-01',
    length: 100,
    genre: ['Western'],
    saga: '',
    description:
      'Un ancien hors-la-loi, bloqué dans un relais, est reconnu par sa bande et forcé de reprendre le fusil.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Rio Bravo',
    director: 'Howard Hawks',
    actors: [
      { name: 'John Wayne' },
      { name: 'Dean Martin' },
      { name: 'Ricky Nelson' },
      { name: 'Angie Dickinson' },
      { name: 'Walter Brennan' },
    ],
    coverUrl: '/movies_pictures/98b6f6f38b87.jpg',
    releaseDate: '1959-04-04',
    length: 141,
    genre: ['Western'],
    saga: '',
    description:
      'Un shérif, un ivrogne, un jeune pistoler et un vieil estropié tiennent une prison contre un clan.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Sept Mercenaires',
    director: 'John Sturges',
    actors: [
      { name: 'Yul Brynner' },
      { name: 'Steve McQueen' },
      { name: 'Charles Bronson' },
      { name: 'James Coburn' },
      { name: 'Eli Wallach' },
    ],
    coverUrl: '/movies_pictures/ebe01c75c4cd.jpg',
    releaseDate: '1960-10-12',
    length: 128,
    genre: ['Western', 'Aventure'],
    saga: '',
    description:
      'Un village mexicain embauche sept pistoleros pour se défendre contre Calvera et ses bandits.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Coups de feu dans la Sierra',
    director: 'Sam Peckinpah',
    actors: [
      { name: 'Randolph Scott' },
      { name: 'Joel McCrea' },
      { name: 'Mariette Hartley' },
      { name: 'Ronald Starr' },
      { name: 'Edgar Buchanan' },
    ],
    coverUrl: '/movies_pictures/1331914ba7a1.jpg',
    releaseDate: '1962-06-20',
    length: 94,
    genre: ['Western'],
    saga: '',
    description:
      "Deux vieux cow-boys escortent de l'or et se heurtent à une bande dans les Sierras, crépuscule d'un genre.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Homme qui tua Liberty Valance",
    director: 'John Ford',
    actors: [
      { name: 'James Stewart' },
      { name: 'John Wayne' },
      { name: 'Vera Miles' },
      { name: 'Lee Marvin' },
      { name: "Edmond O'Brien" },
    ],
    coverUrl: '/movies_pictures/8ad8b6afaca9.jpg',
    releaseDate: '1962-04-22',
    length: 123,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      "Un sénateur revient ensevelir un ami : qui a vraiment tué Liberty Valance, la légende ou l'homme ?",
    fromEntity: {
      entityType: 'book',
      title: "The Man Who Shot Liberty Valance",
      secondEntityKey: "Dorothy M. Johnson",
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Pour une poignée de dollars',
    director: 'Sergio Leone',
    actors: [
      { name: 'Clint Eastwood' },
      { name: 'Gian Maria Volonté' },
      { name: 'Marianne Koch' },
      { name: 'Wolfgang Lukschy' },
      { name: 'Mario Brega' },
    ],
    coverUrl: '/movies_pictures/3000e7221b72.jpg',
    releaseDate: '1964-09-12',
    length: 100,
    genre: ['Western'],
    saga: 'Le Dollar',
    description:
      "L'Homme sans nom joue deux clans d'un village frontalier l'un contre l'autre, cigare et poncho.",
    fromEntity: null,
    countryOrigin: ['Italie', 'Espagne', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Major Dundee',
    director: 'Sam Peckinpah',
    actors: [
      { name: 'Charlton Heston' },
      { name: 'Richard Harris' },
      { name: 'Jim Hutton' },
      { name: 'James Coburn' },
      { name: 'Senta Berger' },
    ],
    coverUrl: '/movies_pictures/ef699f3cea35.jpg',
    releaseDate: '1965-04-07',
    length: 123,
    genre: ['Western', 'Guerre'],
    saga: '',
    description:
      "Un major de l'Union mène déserteurs et confédérés au Mexique pour châtier des Apache, au bord de la mutinerie.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Django',
    director: 'Sergio Corbucci',
    actors: [
      { name: 'Franco Nero' },
      { name: 'Loredana Nusciak' },
      { name: 'José Bódalo' },
      { name: 'Ángel Álvarez' },
      { name: 'Eduardo Fajardo' },
    ],
    coverUrl: '/movies_pictures/0a283538b159.jpg',
    releaseDate: '1966-04-06',
    length: 91,
    genre: ['Western'],
    saga: 'Django',
    description:
      'Un pistoler traîne un cercueil dans la boue, entre mexicains et racistes, mitrailleuse au final.',
    fromEntity: null,
    countryOrigin: ['Italie', 'Espagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'El Dorado',
    director: 'Howard Hawks',
    actors: [
      { name: 'John Wayne' },
      { name: 'Robert Mitchum' },
      { name: 'James Caan' },
      { name: 'Charlene Holt' },
      { name: 'Arthur Hunnicutt' },
    ],
    coverUrl: '/movies_pictures/e49df1ed6ae0.jpg',
    releaseDate: '1966-12-17',
    length: 126,
    genre: ['Western'],
    saga: '',
    description:
      'Un pistolero aide un shérif alcoolique à défendre un clan contre un éleveur, variation amicale de Rio Bravo.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Professionnels',
    director: 'Richard Brooks',
    actors: [
      { name: 'Burt Lancaster' },
      { name: 'Lee Marvin' },
      { name: 'Robert Ryan' },
      { name: 'Woody Strode' },
      { name: 'Claudia Cardinale' },
    ],
    coverUrl: '/movies_pictures/ff5eb570e925.jpg',
    releaseDate: '1966-11-02',
    length: 117,
    genre: ['Western', 'Aventure'],
    saga: '',
    description:
      "Quatre mercenaires enlèvent la femme d'un magnat au Mexique, puis découvrent qu'elle ne veut pas rentrer.",
    fromEntity: {
      entityType: 'book',
      title: 'A Mule for the Marquesa',
      secondEntityKey: "Frank O'Rourke",
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Grand Silence',
    director: 'Sergio Corbucci',
    actors: [
      { name: 'Jean-Louis Trintignant' },
      { name: 'Klaus Kinski' },
      { name: 'Vonetta McGee' },
      { name: 'Frank Wolff' },
      { name: 'Luigi Pistilli' },
    ],
    coverUrl: '/movies_pictures/f632292f914b.jpg',
    releaseDate: '1968-11-21',
    length: 105,
    genre: ['Western'],
    saga: '',
    description:
      'Un pistolero muet défend des hors-la-loi dans la neige ; le chasseur de primes gagne, fin noire.',
    fromEntity: null,
    countryOrigin: ['Italie', 'France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Butch Cassidy et le Kid',
    director: 'George Roy Hill',
    actors: [
      { name: 'Paul Newman' },
      { name: 'Robert Redford' },
      { name: 'Katharine Ross' },
      { name: 'Strother Martin' },
      { name: 'Jeff Corey' },
    ],
    coverUrl: '/movies_pictures/1a0ad77359b0.jpg',
    releaseDate: '1969-09-23',
    length: 110,
    genre: ['Western', 'Aventure', 'Comédie'],
    saga: '',
    description:
      "Deux hors-la-loi, amis jusqu'à la Bolivie, fuient un train de chasseurs et finissent en freeze-frame.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_ORIGINAL_SCREENPLAY, year: 1970 },
      { type: OscarEnum.OSCAR_BEST_CINEMATOGRAPHY, year: 1970 },
      { type: OscarEnum.OSCAR_BEST_ORIGINAL_SCORE, year: 1970 },
      { type: OscarEnum.OSCAR_BEST_ORIGINAL_SONG, year: 1970 },
    ],
  },
  {
    title: 'Cent dollars pour un shérif',
    director: 'Henry Hathaway',
    actors: [
      { name: 'John Wayne' },
      { name: 'Glen Campbell' },
      { name: 'Kim Darby' },
      { name: 'Robert Duvall' },
      { name: 'Dennis Hopper' },
    ],
    coverUrl: '/movies_pictures/e2e214d1912c.jpg',
    releaseDate: '1969-06-11',
    length: 128,
    genre: ['Western'],
    saga: '',
    description:
      'Rooster Cogburn, shérif borgne et soûl, aide une adolescente à venger son père.',
    fromEntity: {
      entityType: 'book',
      title: 'True Grit',
      secondEntityKey: 'Charles Portis',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_ACTOR, year: 1970 }],
  },
  {
    title: 'La Horde sauvage',
    director: 'Sam Peckinpah',
    actors: [
      { name: 'William Holden' },
      { name: 'Ernest Borgnine' },
      { name: 'Robert Ryan' },
      { name: "Edmond O'Brien" },
      { name: 'Warren Oates' },
    ],
    coverUrl: '/movies_pictures/b823e7bf557e.jpg',
    releaseDate: '1969-06-18',
    length: 145,
    genre: ['Western'],
    saga: '',
    description:
      'En 1913, un gang vieillissant braque une banque, fuit au Mexique et meurt dans un massacre au ralenti.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Little Big Man',
    director: 'Arthur Penn',
    actors: [
      { name: 'Dustin Hoffman' },
      { name: 'Faye Dunaway' },
      { name: 'Chief Dan George' },
      { name: 'Martin Balsam' },
      { name: 'Richard Mulligan' },
    ],
    coverUrl:
      '/movies_pictures/ef0452b3837d.jpg',
    releaseDate: '1970-12-14',
    length: 139,
    genre: ['Western', 'Comédie', 'Drame'],
    saga: '',
    description:
      'Un centenaire raconte sa vie entre colons et Cheyennes, de Custer à Little Bighorn.',
    fromEntity: {
      entityType: 'book',
      title: 'Little Big Man',
      secondEntityKey: 'Thomas Berger',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Il était une fois la révolution',
    director: 'Sergio Leone',
    actors: [
      { name: 'Rod Steiger' },
      { name: 'James Coburn' },
      { name: 'Romolo Valli' },
      { name: 'Maria Monti' },
      { name: 'Rik Battaglia' },
    ],
    coverUrl:
      '/movies_pictures/fa0c74180494.jpg',
    releaseDate: '1971-12-22',
    length: 154,
    genre: ['Western', 'Drame'],
    saga: 'Il était une fois',
    description:
      'Un bandit mexicain et un dynamiteur irlandais se croisent dans la révolution de 1913.',
    fromEntity: null,
    countryOrigin: ['Italie', 'Espagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'John McCabe',
    director: 'Robert Altman',
    actors: [
      { name: 'Warren Beatty' },
      { name: 'Julie Christie' },
      { name: 'René Auberjonois' },
      { name: 'William Devane' },
      { name: 'Keith Carradine' },
    ],
    coverUrl:
      '/movies_pictures/080a3c155fe3.jpg',
    releaseDate: '1971-06-24',
    length: 120,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Un baroudeur ouvre un saloon-bordel dans une ville minière du Nord-Ouest, sous la neige et Leonard Cohen.',
    fromEntity: {
      entityType: 'book',
      title: 'McCabe & Mrs. Miller',
      secondEntityKey: 'Edmund Naughton',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Jeremiah Johnson',
    director: 'Sydney Pollack',
    actors: [
      { name: 'Robert Redford' },
      { name: 'Will Geer' },
      { name: 'Delle Bolton' },
      { name: 'Josh Albee' },
      { name: 'Joaquín Martínez' },
    ],
    coverUrl:
      '/movies_pictures/96d983ace1b6.jpg',
    releaseDate: '1972-12-21',
    length: 108,
    genre: ['Western', 'Aventure'],
    saga: '',
    description:
      'Un soldat déserte pour devenir trappeur dans les Rocheuses, guerre crow et solitude comprise.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "On l'appelle Trinita",
    director: 'Enzo Barboni',
    actors: [
      { name: 'Terence Hill' },
      { name: 'Bud Spencer' },
      { name: 'Farley Granger' },
      { name: 'Steffen Zacharias' },
      { name: 'Dan Sturkie' },
    ],
    coverUrl:
      '/movies_pictures/4f0eca04c296.jpg',
    releaseDate: '1970-12-22',
    length: 113,
    genre: ['Western', 'Comédie'],
    saga: 'Trinita',
    description:
      'Un pistolero paresseux et son frère colosse débarquent dans une ville mormone, tartes à la crème et gifles.',
    fromEntity: null,
    countryOrigin: ['Italie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Homme des hautes plaines",
    director: 'Clint Eastwood',
    actors: [
      { name: 'Clint Eastwood' },
      { name: 'Verna Bloom' },
      { name: 'Marianna Hill' },
      { name: 'Mitchell Ryan' },
      { name: 'Jack Ging' },
    ],
    coverUrl:
      '/movies_pictures/d825dde2c14e.jpg',
    releaseDate: '1973-04-06',
    length: 105,
    genre: ['Western'],
    saga: '',
    description:
      'Un étranger sans nom arrive dans une ville de la Frontière et sème la terreur chez deux clans, cigare et chapeau.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Mon nom est Personne',
    director: 'Tonino Valerii',
    actors: [
      { name: 'Terence Hill' },
      { name: 'Henry Fonda' },
      { name: 'Jean Martin' },
      { name: 'Geoffrey Lewis' },
      { name: 'Wolfgang Lukschy' },
    ],
    coverUrl:
      'https://medias.unifrance.org/medias/49/101/222513/format_page/mon-nom-est-personne.jpg',
    releaseDate: '1973-12-13',
    length: 116,
    genre: ['Western', 'Comédie'],
    saga: '',
    description:
      'Un jeune admirateur veut offrir à un vieux pistolero une sortie mythique contre 150 hors-la-loi.',
    fromEntity: null,
    countryOrigin: ['Italie', 'France', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Pat Garrett et Billy le Kid',
    director: 'Sam Peckinpah',
    actors: [
      { name: 'James Coburn' },
      { name: 'Kris Kristofferson' },
      { name: 'Bob Dylan' },
      { name: 'Jason Robards' },
      { name: 'Rita Coolidge' },
    ],
    coverUrl:
      '/movies_pictures/a0fd4c103ea5.jpg',
    releaseDate: '1973-05-23',
    length: 106,
    genre: ['Western'],
    saga: '',
    description:
      'Pat Garrett, devenu shérif, doit tuer son ancien ami Billy, sur une musique de Dylan.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Josey Wales hors-la-loi',
    director: 'Clint Eastwood',
    actors: [
      { name: 'Clint Eastwood' },
      { name: 'Chief Dan George' },
      { name: 'Sondra Locke' },
      { name: 'Bill McKinney' },
      { name: 'John Vernon' },
    ],
    coverUrl:
      '/movies_pictures/40cc906f8525.jpg',
    releaseDate: '1976-06-30',
    length: 135,
    genre: ['Western'],
    saga: '',
    description:
      'Un fermier du Missouri, famille massacrée, devient hors-la-loi et rassemble une tribu de laissés-pour-compte.',
    fromEntity: {
      entityType: 'book',
      title: 'Gone to Texas',
      secondEntityKey: 'Forrest Carter',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Dernier des géants',
    director: 'Don Siegel',
    actors: [
      { name: 'John Wayne' },
      { name: 'Lauren Bacall' },
      { name: 'James Stewart' },
      { name: 'Ron Howard' },
      { name: 'Richard Boone' },
    ],
    coverUrl:
      '/movies_pictures/f46c64256b5f.jpg',
    releaseDate: '1976-08-20',
    length: 100,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Un pistolero cancéreux choisit sa dernière fusillade dans un salon de Carson City, 1901.',
    fromEntity: {
      entityType: 'book',
      title: 'The Shootist',
      secondEntityKey: 'Glendon Swarthout',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'True Grit',
    director: 'Joel Coen, Ethan Coen',
    actors: [
      { name: 'Jeff Bridges' },
      { name: 'Hailee Steinfeld' },
      { name: 'Matt Damon' },
      { name: 'Josh Brolin' },
      { name: 'Barry Pepper' },
      { name: 'Dakin Matthews' },
      { name: 'Domhnall Gleeson' },
    ],
    coverUrl: '/movies_pictures/787031cfa85c.jpg',
    releaseDate: '2010-12-22',
    length: 110,
    genre: ['Western', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Ballade de Buster Scruggs',
    director: 'Ethan Coen',
    actors: [
      { name: 'Tim Blake Nelson' },
      { name: 'James Franco' },
      { name: 'Zoe Kazan' },
      { name: 'Liam Neeson' },
      { name: 'Tom Waits' },
      { name: 'Brendan Gleeson' },
      { name: 'Tyne Daly' },
    ],
    coverUrl: '/movies_pictures/1bd28ddfc8b0.jpg',
    releaseDate: '2018-11-16',
    length: 132,
    genre: ['Western', 'Comédie'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Piste des géants',
    director: 'Raoul Walsh',
    actors: [
      { name: 'John Wayne' },
      { name: 'Marguerite Churchill' },
      { name: 'El Brendel' },
      { name: 'Tully Marshall' },
      { name: 'Tyrone Power Sr.' },
    ],
    coverUrl:
      '/movies_pictures/c534467ebabd.jpg',
    releaseDate: '1930-11-01',
    length: 125,
    genre: ['Western', 'Aventure'],
    saga: '',
    description:
      'Une caravane trop Oregon trop 1840 trop Wayne trop trop jeune, Walsh trop 70 mm trop Grande Piste pionniers.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Jesse James',
    director: 'Henry King',
    actors: [
      { name: 'Tyrone Power' },
      { name: 'Henry Fonda' },
      { name: 'Nancy Kelly' },
      { name: 'Randolph Scott' },
      { name: 'Henry Hull' },
    ],
    coverUrl:
      '/movies_pictures/a0729b2c64a5.jpg',
    releaseDate: '1939-01-27',
    length: 106,
    genre: ['Western', 'Biographie', 'Drame'],
    saga: 'Jesse James',
    description:
      'Jesse trop Frank railroad vengeance King, Power trop Fonda frères Fox 39.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Pacific Express',
    director: 'Cecil B. DeMille',
    actors: [
      { name: 'Barbara Stanwyck' },
      { name: 'Joel McCrea' },
      { name: 'Akim Tamiroff' },
      { name: 'Robert Preston' },
      { name: 'Lynne Overman' },
    ],
    coverUrl:
      '/movies_pictures/1d0697edd09d.jpg',
    releaseDate: '1939-05-05',
    length: 135,
    genre: ['Western', 'Aventure', 'Historique'],
    saga: '',
    description:
      'Le rail transcontinental Stanwyck DeMille 1869, Union Pacific indiens sabotage spectacle.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Étrange Incident",
    director: 'William A. Wellman',
    actors: [
      { name: 'Henry Fonda' },
      { name: 'Dana Andrews' },
      { name: 'Mary Beth Hughes' },
      { name: 'Anthony Quinn' },
      { name: 'Harry Morgan' },
    ],
    coverUrl:
      'https://assets.diverto.tv/media/remote/aHR0cHM6Ly9pbWFnZS50bWRiLm9yZy90L3AvL29yaWdpbmFsLy9iZ29HdGRkcndmaTFNbWFFbUhBNDhNSmpwZ1UuanBn?fit=contain&fm=webp&s=867cbdbf882c4ef85c3746ed86f67187',
    releaseDate: '1943-05-21',
    length: 75,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Un lynchage Nevada Fonda trop tard, Wellman trop n&b 75 min Ox-Bow injustice corde.',
    fromEntity: {
      entityType: 'book',
      title: 'The Ox-Bow Incident',
      secondEntityKey: 'Walter Van Tilburg Clark',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Duel au soleil',
    director: 'King Vidor',
    actors: [
      { name: 'Jennifer Jones' },
      { name: 'Gregory Peck' },
      { name: 'Joseph Cotten' },
      { name: 'Lionel Barrymore' },
      { name: 'Lillian Gish' },
    ],
    coverUrl:
      '/movies_pictures/676963257ab2.jpg',
    releaseDate: '1946-12-31',
    length: 145,
    genre: ['Western', 'Drame', 'Romance'],
    saga: '',
    description:
      'Une métisse Texas deux frères Peck Jones, Vidor trop Selznick lust soleil Duel trop trop opéra.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Fils du désert',
    director: 'John Ford',
    actors: [
      { name: 'John Wayne' },
      { name: 'Pedro Armendáriz' },
      { name: 'Harry Carey Jr.' },
      { name: 'Ward Bond' },
      { name: 'Mae Marsh' },
    ],
    coverUrl:
      '/movies_pictures/948ef1eb7522.jpg',
    releaseDate: '1948-12-01',
    length: 106,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Trois hors-la-loi bébé Noël Wayne Ford, Godfathers désert Monument Valley tendre 48.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Flèche brisée',
    director: 'Delmer Daves',
    actors: [
      { name: 'James Stewart' },
      { name: 'Jeff Chandler' },
      { name: 'Debra Paget' },
      { name: 'Basil Ruysdael' },
      { name: 'Will Geer' },
    ],
    coverUrl:
      '/movies_pictures/a300a670bf4c.jpg',
    releaseDate: '1950-07-21',
    length: 93,
    genre: ['Western', 'Drame', 'Historique'],
    saga: '',
    description:
      'Stewart Cochise paix Apache 1870, Daves trop Flèche brisée Chandler Paget Technicolor 50.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Gunfighter',
    director: 'Henry King',
    actors: [
      { name: 'Gregory Peck' },
      { name: 'Helen Westcott' },
      { name: 'Millard Mitchell' },
      { name: 'Jean Parker' },
      { name: 'Karl Malden' },
    ],
    coverUrl:
      '/movies_pictures/b4a9a74de46f.jpg',
    releaseDate: '1950-06-23',
    length: 85,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Un pistolero fatigué saloon trop trop jeune qui le cherche, King trop Peck 85 min n&b fatal Gunfighter.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Wagon Master',
    director: 'John Ford',
    actors: [
      { name: 'Ben Johnson' },
      { name: 'Harry Carey Jr.' },
      { name: 'Joanne Dru' },
      { name: 'Ward Bond' },
      { name: 'James Arness' },
    ],
    coverUrl:
      '/movies_pictures/f7e3ddf32d2c.jpg',
    releaseDate: '1950-04-19',
    length: 86,
    genre: ['Western'],
    saga: '',
    description:
      'Des Mormons Utah cow-boys Johnson Ford, Wagon Master chansons Navajo doux 50 piste.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Affameurs',
    director: 'Anthony Mann',
    actors: [
      { name: 'James Stewart' },
      { name: 'Arthur Kennedy' },
      { name: 'Rock Hudson' },
      { name: 'Julie Adams' },
      { name: 'Jay C. Flippen' },
    ],
    coverUrl:
      '/movies_pictures/1ba3510d7a95.jpg',
    releaseDate: '1952-01-23',
    length: 91,
    genre: ['Western', 'Aventure'],
    saga: '',
    description:
      'Stewart Oregon bétail Kennedy traître, Mann trop Bend of the River Hudson rivière 52.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Hondo',
    director: 'John Farrow',
    actors: [
      { name: 'John Wayne' },
      { name: 'Geraldine Page' },
      { name: 'Ward Bond' },
      { name: 'Michael Pate' },
      { name: 'James Arness' },
    ],
    coverUrl: '/movies_pictures/29e9542cc160.jpg',
    releaseDate: '1953-11-27',
    length: 83,
    genre: ['Western'],
    saga: '',
    description:
      'Wayne cavalerie veuve Apache 3D, Farrow trop Hondo Page chien Sam désert 53.',
    fromEntity: {
      entityType: 'book',
      title: 'The Gift of Cochise',
      secondEntityKey: "Louis L'Amour",
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Appât",
    director: 'Anthony Mann',
    actors: [
      { name: 'James Stewart' },
      { name: 'Janet Leigh' },
      { name: 'Robert Ryan' },
      { name: 'Ralph Meeker' },
      { name: 'Millard Mitchell' },
    ],
    coverUrl:
      '/movies_pictures/d77f1c4cf1c1.jpg',
    releaseDate: '1953-02-06',
    length: 91,
    genre: ['Western', 'Thriller'],
    saga: '',
    description:
      'Un chasseur primes Stewart Ryan montagnes, Mann trop Naked Spur Leigh neige appât 53 n&b.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Apache',
    director: 'Robert Aldrich',
    actors: [
      { name: 'Burt Lancaster' },
      { name: 'Jean Peters' },
      { name: 'John McIntire' },
      { name: 'Charles Bronson' },
      { name: 'John Dehner' },
    ],
    coverUrl:
      '/movies_pictures/32c8884cace3.jpg',
    releaseDate: '1954-07-09',
    length: 87,
    genre: ['Western', 'Drame', 'Guerre'],
    saga: '',
    description:
      'Lancaster Massai dernier Apache libre, Aldrich trop Bronson Peters Floride révolte 54.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Je suis un aventurier',
    director: 'Anthony Mann',
    actors: [
      { name: 'James Stewart' },
      { name: 'Ruth Roman' },
      { name: 'Corinne Calvet' },
      { name: 'Walter Brennan' },
      { name: 'John McIntire' },
    ],
    coverUrl:
      '/movies_pictures/455ed13531a9.jpg',
    releaseDate: '1954-02-12',
    length: 97,
    genre: ['Western', 'Aventure'],
    saga: '',
    description:
      'Stewart Alaska troupeau Brennan juge, Mann trop Far Country Yukon rivière 54 aventurier.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Vera Cruz',
    director: 'Robert Aldrich',
    actors: [
      { name: 'Gary Cooper' },
      { name: 'Burt Lancaster' },
      { name: 'Denise Darcel' },
      { name: 'Cesar Romero' },
      { name: 'Sara Montiel' },
    ],
    coverUrl: '/movies_pictures/1939a49bfb50.jpg',
    releaseDate: '1954-12-25',
    length: 94,
    genre: ['Western', 'Aventure'],
    saga: '',
    description:
      'Cooper Lancaster Mexique 1866 or, Aldrich trop Vera Cruz Juaristes Maxim 54 SuperScope.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Jubal',
    director: 'Delmer Daves',
    actors: [
      { name: 'Glenn Ford' },
      { name: 'Ernest Borgnine' },
      { name: 'Rod Steiger' },
      { name: 'Valerie French' },
      { name: 'Felicia Farr' },
    ],
    coverUrl:
      '/movies_pictures/85ff35f4a45f.jpg',
    releaseDate: '1956-04-06',
    length: 101,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Ford ranch Othello Wyoming Steiger, Daves trop Jubal Borgnine jalousie 56 CinemaScope.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Quarante tueurs',
    director: 'Samuel Fuller',
    actors: [
      { name: 'Barbara Stanwyck' },
      { name: 'Barry Sullivan' },
      { name: 'Dean Jagger' },
      { name: 'John Ericson' },
      { name: 'Gene Barry' },
    ],
    coverUrl:
      '/movies_pictures/1458766e6479.jpg',
    releaseDate: '1957-09-10',
    length: 80,
    genre: ['Western'],
    saga: '',
    description:
      'Stanwyck 40 hommes fusil whip, Fuller trop Forty Guns Scope 80 min 57 noir.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Règlement de comptes à O.K. Corral',
    director: 'John Sturges',
    actors: [
      { name: 'Burt Lancaster' },
      { name: 'Kirk Douglas' },
      { name: 'Rhonda Fleming' },
      { name: 'Jo Van Fleet' },
      { name: 'John Ireland' },
    ],
    coverUrl: '/movies_pictures/d55b3472a5ce.jpg',
    releaseDate: '1957-05-30',
    length: 122,
    genre: ['Western', 'Biographie', 'Historique'],
    saga: '',
    description:
      'Wyatt Doc Tombstone Lancaster Douglas, Sturges trop O.K. Corral 57 VistaVision Tiomkin duel.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Grands Espaces',
    director: 'William Wyler',
    actors: [
      { name: 'Gregory Peck' },
      { name: 'Jean Simmons' },
      { name: 'Charlton Heston' },
      { name: 'Burl Ives' },
      { name: 'Carroll Baker' },
    ],
    coverUrl: '/movies_pictures/062bad30deaf.jpg',
    releaseDate: '1958-10-01',
    length: 165,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Deux familles Texas terre Peck Heston, Wyler trop Big Country Ives Oscar 58 165 min espaces.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_SUPPORTING_ACTOR, year: 1959 }],
  },
  {
    title: 'Le Dernier Train de Gun Hill',
    director: 'John Sturges',
    actors: [
      { name: 'Kirk Douglas' },
      { name: 'Anthony Quinn' },
      { name: 'Carolyn Jones' },
      { name: 'Earl Holliman' },
      { name: 'Brad Dexter' },
    ],
    coverUrl:
      '/movies_pictures/8b8cc8fc7499.jpg',
    releaseDate: '1959-07-29',
    length: 94,
    genre: ['Western', 'Thriller'],
    saga: '',
    description:
      'Douglas marshal Quinn fils viol train, Sturges trop Gun Hill 94 min 59 ultimatum gare.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Alamo',
    director: 'John Wayne',
    actors: [
      { name: 'John Wayne' },
      { name: 'Richard Widmark' },
      { name: 'Laurence Harvey' },
      { name: 'Frankie Avalon' },
      { name: 'Patrick Wayne' },
    ],
    coverUrl:
      '/movies_pictures/2f95b5f07c4a.webp',
    releaseDate: '1960-10-24',
    length: 192,
    genre: ['Western', 'Guerre', 'Historique', 'Drame'],
    saga: '',
    description:
      'Wayne Crockett 1836 San Antonio, Alamo 192 min Oscar son 60 Widmark siège.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_SOUND, year: 1961 }],
  },
  {
    title: 'La Vengeance aux deux visages',
    director: 'Marlon Brando',
    actors: [
      { name: 'Marlon Brando' },
      { name: 'Karl Malden' },
      { name: 'Pina Pellicer' },
      { name: 'Katy Jurado' },
      { name: 'Ben Johnson' },
    ],
    coverUrl: '/movies_pictures/7e33a367ea2f.jpg',
    releaseDate: '1961-03-30',
    length: 141,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Brando unique film réalisé Malden ami flic, One-Eyed Jacks Monterey 61 141 min trahison.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "La Conquête de l'Ouest",
    director: 'Henry Hathaway',
    actors: [
      { name: 'James Stewart' },
      { name: 'John Wayne' },
      { name: 'Debbie Reynolds' },
      { name: 'Gregory Peck' },
      { name: 'Carroll Baker' },
    ],
    coverUrl:
      '/movies_pictures/e6313323ba7d.jpg',
    releaseDate: '1962-11-01',
    length: 164,
    genre: ['Western', 'Aventure', 'Historique'],
    saga: '',
    description:
      'Trois réalisateurs Cinerama Stewart Wayne 50 ans, Hathaway trop Ford Marshall Ouest 62 trois Oscars 64.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_ORIGINAL_SCREENPLAY, year: 1964 },
      { type: OscarEnum.OSCAR_BEST_FILM_EDITING, year: 1964 },
      { type: OscarEnum.OSCAR_BEST_SOUND, year: 1964 },
    ],
  },
  {
    title: 'Seuls sont les indomptés',
    director: 'David Miller',
    actors: [
      { name: 'Kirk Douglas' },
      { name: 'Gena Rowlands' },
      { name: 'Walter Matthau' },
      { name: 'Michael Kane' },
      { name: "Carroll O'Connor" },
    ],
    coverUrl:
      '/movies_pictures/29e66de7e9df.jpg',
    releaseDate: '1962-05-24',
    length: 107,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Douglas cowboy moderne hélicoptère Matthau, Miller trop Lonely Are the Brave 62 n&b last cowboy.',
    fromEntity: {
      entityType: 'book',
      title: 'The Brave Cowboy',
      secondEntityKey: 'Edward Abbey',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Grand McLintock',
    director: 'Andrew V. McLaglen',
    actors: [
      { name: 'John Wayne' },
      { name: "Maureen O'Hara" },
      { name: 'Patrick Wayne' },
      { name: 'Stefanie Powers' },
      { name: 'Chill Wills' },
    ],
    coverUrl:
      '/movies_pictures/6cd191e85069.jpg',
    releaseDate: '1963-11-13',
    length: 127,
    genre: ['Western', 'Comédie'],
    saga: '',
    description:
      "Wayne O'Hara ranch bagarre mud, McLaglen trop McLintock 63 comédie Taming of the Shrew far west.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Quatre Fils de Katie Elder',
    director: 'Henry Hathaway',
    actors: [
      { name: 'John Wayne' },
      { name: 'Dean Martin' },
      { name: 'Martha Hyer' },
      { name: 'Earl Holliman' },
      { name: 'Michael Anderson Jr.' },
    ],
    coverUrl:
      '/movies_pictures/02e862f53542.jpg',
    releaseDate: '1965-06-24',
    length: 122,
    genre: ['Western'],
    saga: '',
    description:
      'Quatre frères Wayne Martin mère morte ranch, Hathaway trop Katie Elder 65 Texas vengeance poker.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Nevada Smith',
    director: 'Henry Hathaway',
    actors: [
      { name: 'Steve McQueen' },
      { name: 'Karl Malden' },
      { name: 'Brian Keith' },
      { name: 'Arthur Kennedy' },
      { name: 'Suzanne Pleshette' },
    ],
    coverUrl:
      '/movies_pictures/e046a87a7285.jpg',
    releaseDate: '1966-06-10',
    length: 128,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'McQueen métis vengeance trois tueurs parents, Hathaway trop Nevada Smith 66 Malden Keith apprentissage.',
    fromEntity: {
      entityType: 'book',
      title: 'The Carpetbaggers',
      secondEntityKey: 'Harold Robbins',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Navajo Joe',
    director: 'Sergio Corbucci',
    actors: [
      { name: 'Burt Reynolds' },
      { name: 'Nicoletta Machiavelli' },
      { name: 'Aldo Sambrell' },
      { name: 'Fernando Rey' },
      { name: 'Tanya Lopert' },
    ],
    coverUrl:
      '/movies_pictures/5750e2b95c3a.jpg',
    releaseDate: '1966-11-25',
    length: 93,
    genre: ['Western'],
    saga: '',
    description:
      'Reynolds Navajo vengeance scalp village, Corbucci trop Morricone 66 spaghetti rouge Joe trop trop fusils.',
    fromEntity: null,
    countryOrigin: ['Italie', 'Espagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Face à face',
    director: 'Sergio Sollima',
    actors: [
      { name: 'Gian Maria Volonté' },
      { name: 'Tomas Milian' },
      { name: 'William Berger' },
      { name: 'Jolanda Modio' },
      { name: 'Carlotta Barilli' },
    ],
    coverUrl:
      '/movies_pictures/e72bd9a7b50b.jpeg',
    releaseDate: '1967-11-23',
    length: 112,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Un prof tuberculose bandit Milian Volonté, Sollima trop Faccia a faccia 67 politique spaghetti face.',
    fromEntity: null,
    countryOrigin: ['Italie', 'Espagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Mort était au rendez-vous',
    director: 'Giulio Petroni',
    actors: [
      { name: 'Lee Van Cleef' },
      { name: 'John Phillip Law' },
      { name: 'Mario Brega' },
      { name: 'Luigi Pistilli' },
      { name: 'Anthony Dawson' },
    ],
    coverUrl:
      '/movies_pictures/d2cc8299e514.jpg',
    releaseDate: '1967-08-31',
    length: 120,
    genre: ['Western'],
    saga: '',
    description:
      'Van Cleef enfant massacre Law blond, Petroni trop Morricone 67 Death Rides a Horse duel.',
    fromEntity: null,
    countryOrigin: ['Italie', 'Espagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Pendez-les haut et court',
    director: 'Ted Post',
    actors: [
      { name: 'Clint Eastwood' },
      { name: 'Inger Stevens' },
      { name: 'Ed Begley' },
      { name: 'Pat Hingle' },
      { name: 'Ben Johnson' },
    ],
    coverUrl:
      '/movies_pictures/7f7604a48d6f.jpg',
    releaseDate: '1968-07-31',
    length: 114,
    genre: ['Western'],
    saga: '',
    description:
      "Eastwood pendu survit marshal vengeance, Post trop Hang 'Em High 68 Leone USA première US western.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Sabata',
    director: 'Gianfranco Parolini',
    actors: [
      { name: 'Lee Van Cleef' },
      { name: 'William Berger' },
      { name: 'Ignazio Spalla' },
      { name: 'Aldo Canti' },
      { name: 'Linda Veras' },
    ],
    coverUrl: '/movies_pictures/a37c97d35831.jpg',
    releaseDate: '1969-09-16',
    length: 106,
    genre: ['Western'],
    saga: 'Sabata',
    description:
      'Van Cleef canne fusil banque complot, Parolini trop Sabata 69 spaghetti gadgets chapeau noir.',
    fromEntity: null,
    countryOrigin: ['Italie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Chisum',
    director: 'Andrew V. McLaglen',
    actors: [
      { name: 'John Wayne' },
      { name: 'Forrest Tucker' },
      { name: 'Christopher George' },
      { name: 'Ben Johnson' },
      { name: 'Glenn Corbett' },
    ],
    coverUrl:
      '/movies_pictures/24b453fc2a2e.jpg',
    releaseDate: '1970-07-29',
    length: 111,
    genre: ['Western', 'Biographie'],
    saga: '',
    description:
      'Wayne éleveur Lincoln County War Billy, McLaglen trop Chisum 70 Murphy ranch New Mexico.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Compañeros',
    director: 'Sergio Corbucci',
    actors: [
      { name: 'Franco Nero' },
      { name: 'Tomas Milian' },
      { name: 'Jack Palance' },
      { name: 'Fernando Rey' },
      { name: 'Iris Berben' },
    ],
    coverUrl: '/movies_pictures/337ae6594963.jpg',
    releaseDate: '1970-12-18',
    length: 119,
    genre: ['Western', 'Comédie', 'Aventure'],
    saga: '',
    description:
      'Nero Suédois Milian Mexique révolution Palance, Corbucci trop Compañeros 70 Morricone zapata rire fusils.',
    fromEntity: null,
    countryOrigin: ['Italie', 'Espagne', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'El Topo',
    director: 'Alejandro Jodorowsky',
    actors: [
      { name: 'Alejandro Jodorowsky' },
      { name: 'Mara Lorenzio' },
      { name: 'Brontis Jodorowsky' },
      { name: 'Alfonso Arau' },
      { name: 'Paula Romo' },
    ],
    coverUrl:
      '/movies_pictures/faaf371fa77b.jpg',
    releaseDate: '1970-12-18',
    length: 125,
    genre: ['Western', 'Fantastique', 'Drame'],
    saga: '',
    description:
      'Jodorowsky pistolero mystique désert nains sang, El Topo 70 midnight movie acid western bible.',
    fromEntity: null,
    countryOrigin: ['Mexique'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Rio Lobo',
    director: 'Howard Hawks',
    actors: [
      { name: 'John Wayne' },
      { name: 'Jorge Rivero' },
      { name: "Jennifer O'Neill" },
      { name: 'Jack Elam' },
      { name: 'Chris Mitchum' },
    ],
    coverUrl:
      'https://assets.diverto.tv/media/remote/aHR0cHM6Ly9pbWFnZS50bWRiLm9yZy90L3AvL29yaWdpbmFsLy9sUVNpRmlkSHZxbGxhMllPWlFqVU1nS1hHeFQuanBn?fit=contain&fm=webp&s=7cb3d493163ad733eb1fa0d35ceb7d83',
    releaseDate: '1970-12-17',
    length: 114,
    genre: ['Western'],
    saga: '',
    description:
      'Wayne colonel 1865 trahison Texas Hawks, Rio Lobo 70 dernier Hawks western Elam rire.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Sierra torride',
    director: 'Don Siegel',
    actors: [
      { name: 'Clint Eastwood' },
      { name: 'Shirley MacLaine' },
      { name: 'Manolo Fábregas' },
      { name: 'Alberto Morin' },
      { name: 'Armando Silvestre' },
    ],
    coverUrl:
      '/movies_pictures/4fb9e3b0e785.jpg',
    releaseDate: '1970-06-16',
    length: 116,
    genre: ['Western', 'Aventure', 'Comédie'],
    saga: '',
    description:
      'Eastwood mercenaire nonne MacLaine dynamite, Siegel trop Two Mules 70 Juaristes mule trop trop Sierra torride.',
    fromEntity: null,
    countryOrigin: ['États-Unis', 'Mexique'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Soldat bleu',
    director: 'Ralph Nelson',
    actors: [
      { name: 'Candice Bergen' },
      { name: 'Peter Strauss' },
      { name: 'Donald Pleasence' },
      { name: 'John Anderson' },
      { name: 'Jorge Rivero' },
    ],
    coverUrl:
      '/movies_pictures/dbddbe6e3e62.jpg',
    releaseDate: '1970-08-12',
    length: 112,
    genre: ['Western', 'Guerre', 'Drame'],
    saga: '',
    description:
      'Sand Creek massacre Bergen captive Cheyenne, Nelson trop Soldier Blue 70 Vietnam allégorie sang bleu.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Un homme nommé Cheval',
    director: 'Elliot Silverstein',
    actors: [
      { name: 'Richard Harris' },
      { name: 'Judith Anderson' },
      { name: 'Jean Gascon' },
      { name: 'Manu Tupou' },
      { name: 'Corinna Tsopei' },
    ],
    coverUrl:
      '/movies_pictures/6a355bad2fb5.jpg',
    releaseDate: '1970-04-28',
    length: 114,
    genre: ['Western', 'Aventure', 'Drame'],
    saga: 'Un homme nommé Cheval',
    description:
      'Harris lord Sioux initiation poitrine cordes, Silverstein trop Horse 70 Sun Dance western ethnographique pain.',
    fromEntity: {
      entityType: 'book',
      title: 'A Man Called Horse',
      secondEntityKey: 'Dorothy M. Johnson',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Big Jake',
    director: 'George Sherman',
    actors: [
      { name: 'John Wayne' },
      { name: 'Richard Boone' },
      { name: "Maureen O'Hara" },
      { name: 'Patrick Wayne' },
      { name: 'Christopher Mitchum' },
    ],
    coverUrl:
      '/movies_pictures/2b5f1f8a9e5f.jpg',
    releaseDate: '1971-05-26',
    length: 110,
    genre: ['Western'],
    saga: '',
    description:
      "Wayne 1909 petit-fils kidnap Boone rançon, Sherman trop Big Jake 71 mitrailleuse chien Dog trop trop fin d'une ère.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "On continue à l'appeler Trinita",
    director: 'Enzo Barboni',
    actors: [
      { name: 'Terence Hill' },
      { name: 'Bud Spencer' },
      { name: 'Yanti Somer' },
      { name: 'Enzo Fiermonte' },
      { name: 'Harry Carey Jr.' },
    ],
    coverUrl:
      '/movies_pictures/e20f8428d41a.jpg',
    releaseDate: '1971-10-21',
    length: 117,
    genre: ['Western', 'Comédie'],
    saga: 'Trinita',
    description:
      'Hill Spencer omelettes gifle Mormon suite, Barboni trop Trinita 71 spaghetti comédie box office trop trop italien.',
    fromEntity: null,
    countryOrigin: ['Italie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Valdez',
    director: 'Edwin Sherin',
    actors: [
      { name: 'Burt Lancaster' },
      { name: 'Susan Clark' },
      { name: 'Jon Cypher' },
      { name: 'Barton Heyman' },
      { name: 'Richard Jordan' },
    ],
    coverUrl: '/movies_pictures/192c5d844d40.jpg',
    releaseDate: '1971-04-09',
    length: 90,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Lancaster constable métis justice ranch raciste, Sherin trop Valdez 71 Leonard 90 min fusil trop trop dignité.',
    fromEntity: {
      entityType: 'book',
      title: 'Valdez Is Coming',
      secondEntityKey: 'Elmore Leonard',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Joe Kidd',
    director: 'John Sturges',
    actors: [
      { name: 'Clint Eastwood' },
      { name: 'Robert Duvall' },
      { name: 'John Saxon' },
      { name: 'Don Stroud' },
      { name: 'Stella Garcia' },
    ],
    coverUrl: '/movies_pictures/cdd960fa605e.jpg',
    releaseDate: '1972-07-14',
    length: 88,
    genre: ['Western'],
    saga: '',
    description:
      'Eastwood chasseur primes Duvall propriétaire Mexicains, Sturges trop Joe Kidd 72 train Siegel producteur 88 min.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Junior Bonner, le dernier bagarreur',
    director: 'Sam Peckinpah',
    actors: [
      { name: 'Steve McQueen' },
      { name: 'Robert Preston' },
      { name: 'Ida Lupino' },
      { name: 'Joe Don Baker' },
      { name: 'Ben Johnson' },
    ],
    coverUrl:
      '/movies_pictures/26bad612cc46.jpg',
    releaseDate: '1972-06-02',
    length: 100,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      "McQueen rodéo Arizona père Preston fin d'un monde, Peckinpah trop Junior Bonner 72 doux twilight western.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Grand Duel',
    director: 'Giancarlo Santi',
    actors: [
      { name: 'Lee Van Cleef' },
      { name: 'Alberto Dentice' },
      { name: 'Jess Hahn' },
      { name: 'Marc Mazza' },
      { name: 'Horst Frank' },
    ],
    coverUrl:
      '/movies_pictures/4b9cbad3025e.jpg',
    releaseDate: '1972-12-29',
    length: 98,
    genre: ['Western'],
    saga: '',
    description:
      'Van Cleef shérif jeune accusé Morricone, Santi trop Grand Duel 72 spaghetti 98 min pistolet trop trop train.',
    fromEntity: null,
    countryOrigin: ['Italie', 'Allemagne', 'France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Keoma',
    director: 'Enzo G. Castellari',
    actors: [
      { name: 'Franco Nero' },
      { name: 'Woody Strode' },
      { name: 'William Berger' },
      { name: 'Olga Karlatos' },
      { name: "Donald O'Brien" },
    ],
    coverUrl:
      '/movies_pictures/555782357bf7.jpg',
    releaseDate: '1976-11-25',
    length: 101,
    genre: ['Western'],
    saga: '',
    description:
      'Nero métis peste frères racistes Strode, Castellari trop Keoma 76 crépuscule spaghetti chant folk sang.',
    fromEntity: null,
    countryOrigin: ['Italie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Missouri Breaks',
    director: 'Arthur Penn',
    actors: [
      { name: 'Marlon Brando' },
      { name: 'Jack Nicholson' },
      { name: 'Randy Quaid' },
      { name: 'Kathleen Lloyd' },
      { name: 'Frederic Forrest' },
    ],
    coverUrl:
      '/movies_pictures/ca2a89c1b3b3.jpg',
    releaseDate: '1976-05-19',
    length: 126,
    genre: ['Western', 'Drame', 'Comédie'],
    saga: '',
    description:
      'Brando regulator Nicholson voleur chevaux robe, Penn trop Missouri Breaks 76 bizarre crépuscule Montana duo.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Cavalier électrique',
    director: 'Sydney Pollack',
    actors: [
      { name: 'Robert Redford' },
      { name: 'Jane Fonda' },
      { name: 'Valerie Perrine' },
      { name: 'Willie Nelson' },
      { name: 'John Saxon' },
    ],
    coverUrl:
      '/movies_pictures/485693c64e4f.jpg',
    releaseDate: '1979-12-21',
    length: 120,
    genre: ['Western', 'Romance', 'Comédie', 'Drame'],
    saga: '',
    description:
      'Redford cowboy pub Fonda journaliste cheval volé, Pollack trop Electric Horseman 79 Vegas contemporain western neon.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Silverado',
    director: 'Lawrence Kasdan',
    actors: [
      { name: 'Kevin Kline' },
      { name: 'Scott Glenn' },
      { name: 'Kevin Costner' },
      { name: 'Danny Glover' },
      { name: 'Brian Dennehy' },
    ],
    coverUrl:
      '/movies_pictures/a3b6d6f63480.jpg',
    releaseDate: '1985-07-10',
    length: 133,
    genre: ['Western', 'Aventure'],
    saga: '',
    description:
      'Quatre cowboys Kasdan Costner Glover 85, Silverado hommage classique 133 min Dennehy shérif trop trop fun.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Young Guns',
    director: 'Christopher Cain',
    actors: [
      { name: 'Emilio Estevez' },
      { name: 'Kiefer Sutherland' },
      { name: 'Lou Diamond Phillips' },
      { name: 'Charlie Sheen' },
      { name: 'Dermot Mulroney' },
    ],
    coverUrl:
      '/movies_pictures/708abc0682b9.jpg',
    releaseDate: '1988-08-12',
    length: 107,
    genre: ['Western', 'Biographie', 'Action'],
    saga: 'Young Guns',
    description:
      'Billy Kid Brat Pack Estevez 88, Cain trop Young Guns Lincoln County Sheen Sutherland trop trop jeunes.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Young Guns 2',
    director: 'Geoff Murphy',
    actors: [
      { name: 'Emilio Estevez' },
      { name: 'Kiefer Sutherland' },
      { name: 'Lou Diamond Phillips' },
      { name: 'Christian Slater' },
      { name: 'William Petersen' },
    ],
    coverUrl:
      '/movies_pictures/24edede70a90.jpg',
    releaseDate: '1990-08-01',
    length: 104,
    genre: ['Western', 'Biographie', 'Action'],
    saga: 'Young Guns',
    description:
      'Billy toujours en fuite Slater Pat Garrett, Murphy trop Young Guns 2 90 Bon Jovi chanson suite.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Geronimo',
    director: 'Walter Hill',
    actors: [
      { name: 'Wes Studi' },
      { name: 'Jason Patric' },
      { name: 'Gene Hackman' },
      { name: 'Robert Duvall' },
      { name: 'Matt Damon' },
    ],
    coverUrl:
      '/movies_pictures/c248c493e6f6.jpg',
    releaseDate: '1993-12-10',
    length: 115,
    genre: ['Western', 'Biographie', 'Guerre', 'Historique'],
    saga: '',
    description:
      'Studi Geronimo Apache Hill 93 cavalerie, Hackman Duvall Damon trop trop légende trop trop reddition trop trop désert.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Wyatt Earp',
    director: 'Lawrence Kasdan',
    actors: [
      { name: 'Kevin Costner' },
      { name: 'Dennis Quaid' },
      { name: 'Gene Hackman' },
      { name: 'Michael Madsen' },
      { name: 'Linden Ashby' },
    ],
    coverUrl:
      '/movies_pictures/9f49f36f5bb3.jpg',
    releaseDate: '1994-06-24',
    length: 191,
    genre: ['Western', 'Biographie', 'Drame'],
    saga: '',
    description:
      "Costner Earp 191 min Tombstone Quaid Doc, Kasdan trop 94 biopic trop trop long trop trop versus trop trop Kilmer trop trop l'autre.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Wild Bill',
    director: 'Walter Hill',
    actors: [
      { name: 'Jeff Bridges' },
      { name: 'Ellen Barkin' },
      { name: 'John Hurt' },
      { name: 'Diane Lane' },
      { name: 'Keith Carradine' },
    ],
    coverUrl:
      '/movies_pictures/ee1a9e5f2396.jpg',
    releaseDate: '1995-12-01',
    length: 98,
    genre: ['Western', 'Biographie', 'Drame'],
    saga: '',
    description:
      'Bridges Hickok Deadwood Barkin Calamity 95, Hill trop Wild Bill 98 min crépuscule cartes trop trop balle trop trop dos.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Claim',
    director: 'Michael Winterbottom',
    actors: [
      { name: 'Peter Mullan' },
      { name: 'Wes Bentley' },
      { name: 'Sarah Polley' },
      { name: 'Milla Jovovich' },
      { name: 'Nastassja Kinski' },
    ],
    coverUrl:
      '/movies_pictures/95ab42ee73fd.jpg',
    releaseDate: '2000-12-29',
    length: 120,
    genre: ['Western', 'Drame', 'Romance'],
    saga: '',
    description:
      'Un maire Sierra vend femme fille or, Winterbottom trop Claim 2000 Hardy neige 120 min trop trop frontière trop trop faute.',
    fromEntity: {
      entityType: 'book',
      title: 'The Mayor of Casterbridge',
      secondEntityKey: 'Thomas Hardy',
    },
    countryOrigin: ['Royaume-Uni', 'Canada', 'France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Open Range',
    director: 'Kevin Costner',
    actors: [
      { name: 'Robert Duvall' },
      { name: 'Kevin Costner' },
      { name: 'Annette Bening' },
      { name: 'Michael Gambon' },
      { name: 'Diego Luna' },
    ],
    coverUrl:
      '/movies_pictures/b2a615a72c31.jpg',
    releaseDate: '2003-08-15',
    length: 139,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Duvall Costner free range Gambon baron, Costner trop Open Range 2003 fusillade 139 min Bening trop trop troupeau.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Missing',
    director: 'Ron Howard',
    actors: [
      { name: 'Tommy Lee Jones' },
      { name: 'Cate Blanchett' },
      { name: 'Evan Rachel Wood' },
      { name: 'Jenna Boyd' },
      { name: 'Aaron Eckhart' },
    ],
    coverUrl:
      '/movies_pictures/7eaba3dff281.jpg',
    releaseDate: '2003-11-26',
    length: 137,
    genre: ['Western', 'Thriller', 'Drame'],
    saga: '',
    description:
      'Blanchett Jones fille kidnappée Apache 1885, Howard trop Missing 2003 137 min New Mexico trop trop chasse trop trop père.',
    fromEntity: {
      entityType: 'book',
      title: 'The Last Ride',
      secondEntityKey: 'Thomas Eidson',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Proposition',
    director: 'John Hillcoat',
    actors: [
      { name: 'Guy Pearce' },
      { name: 'Ray Winstone' },
      { name: 'Danny Huston' },
      { name: 'Emily Watson' },
      { name: 'John Hurt' },
    ],
    coverUrl:
      '/movies_pictures/d7d7e6ee6577.jpg',
    releaseDate: '2005-10-06',
    length: 104,
    genre: ['Western', 'Drame', 'Thriller'],
    saga: '',
    description:
      'Pearce outback 1880 tuer son frère ou pendu, Hillcoat trop Cave 2005 Proposition poussière trop trop sang trop trop soleil.',
    fromEntity: null,
    countryOrigin: ['Australie', 'Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Appaloosa',
    director: 'Ed Harris',
    actors: [
      { name: 'Ed Harris' },
      { name: 'Viggo Mortensen' },
      { name: 'Renée Zellweger' },
      { name: 'Jeremy Irons' },
      { name: 'Lance Henriksen' },
    ],
    coverUrl:
      '/movies_pictures/8c7a7e7a1227.jpg',
    releaseDate: '2008-09-19',
    length: 115,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Harris Mortensen marshals Irons rancher Zellweger, Appaloosa 2008 Parker 115 min amitié trop trop pistolets trop trop ville.',
    fromEntity: {
      entityType: 'book',
      title: 'Appaloosa',
      secondEntityKey: 'Robert B. Parker',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Meek's Cutoff",
    director: 'Kelly Reichardt',
    actors: [
      { name: 'Michelle Williams' },
      { name: 'Bruce Greenwood' },
      { name: 'Will Patton' },
      { name: 'Zoe Kazan' },
      { name: 'Paul Dano' },
    ],
    coverUrl: '/movies_pictures/f00b0bffd228.jpg',
    releaseDate: '2010-09-05',
    length: 104,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Une caravane Oregon 1845 guide perdu Williams, Reichardt trop Meek 2010 1.33 silence désert trop trop eau trop trop peur.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Homesman',
    director: 'Tommy Lee Jones',
    actors: [
      { name: 'Tommy Lee Jones' },
      { name: 'Hilary Swank' },
      { name: 'Grace Gummer' },
      { name: 'Miranda Otto' },
      { name: 'Meryl Streep' },
    ],
    coverUrl:
      '/movies_pictures/437259040e82.jpg',
    releaseDate: '2014-05-18',
    length: 122,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      'Swank Jones ramènent trois folles Nebraska Iowa, Homesman 2014 122 min hiver trop trop frontière trop trop dur.',
    fromEntity: {
      entityType: 'book',
      title: 'The Homesman',
      secondEntityKey: 'Glendon Swarthout',
    },
    countryOrigin: ['États-Unis', 'France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Salvation',
    director: 'Kristian Levring',
    actors: [
      { name: 'Mads Mikkelsen' },
      { name: 'Eva Green' },
      { name: 'Jeffrey Dean Morgan' },
      { name: 'Eric Cantona' },
      { name: 'Mikael Persbrandt' },
    ],
    coverUrl:
      '/movies_pictures/7c90927f9167.jpg',
    releaseDate: '2014-05-22',
    length: 92,
    genre: ['Western'],
    saga: '',
    description:
      'Mikkelsen Danois Ouest femme tuée Morgan gang, Levring trop Salvation 2014 92 min Cantona Green trop trop vengeance trop trop creux.',
    fromEntity: null,
    countryOrigin: ['Danemark', 'Royaume-Uni', 'Afrique du Sud'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Bone Tomahawk',
    director: 'S. Craig Zahler',
    actors: [
      { name: 'Kurt Russell' },
      { name: 'Patrick Wilson' },
      { name: 'Matthew Fox' },
      { name: 'Richard Jenkins' },
      { name: 'Lili Simmons' },
    ],
    coverUrl:
      '/movies_pictures/62f54b248dab.jpg',
    releaseDate: '2015-10-23',
    length: 132,
    genre: ['Western', 'Horreur'],
    saga: '',
    description:
      'Russell shérif canyon cannibales 132 min Zahler, Bone Tomahawk 2015 os scie trop trop western trop trop gore trop trop nuit.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Slow West',
    director: 'John Maclean',
    actors: [
      { name: 'Kodi Smit-McPhee' },
      { name: 'Michael Fassbender' },
      { name: 'Ben Mendelsohn' },
      { name: 'Caren Pistorius' },
      { name: 'Rory McCann' },
    ],
    coverUrl:
      '/movies_pictures/87f6e0f7f885.jpg',
    releaseDate: '2015-05-15',
    length: 84,
    genre: ['Western', 'Drame', 'Romance'],
    saga: '',
    description:
      'Un Écossais 16 ans Colorado Fassbender bounty 84 min, Maclean trop Slow West 2015 fable trop trop balle trop trop amour trop trop ouest.',
    fromEntity: null,
    countryOrigin: ['Royaume-Uni', 'Nouvelle-Zélande'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Frères Sisters',
    director: 'Jacques Audiard',
    actors: [
      { name: 'John C. Reilly' },
      { name: 'Joaquin Phoenix' },
      { name: 'Jake Gyllenhaal' },
      { name: 'Riz Ahmed' },
      { name: 'Rutger Hauer' },
    ],
    coverUrl:
      '/movies_pictures/490a5cbf708a.jpg',
    releaseDate: '2018-09-19',
    length: 122,
    genre: ['Western', 'Comédie', 'Drame'],
    saga: '',
    description:
      'Deux frères tueurs Reilly Phoenix or 1851, Audiard trop Sisters 2018 deWitt 122 min dents trop trop comédie trop trop crépuscule.',
    fromEntity: {
      entityType: 'book',
      title: 'The Sisters Brothers',
      secondEntityKey: 'Patrick deWitt',
    },
    countryOrigin: ['France', 'Belgique', 'Espagne', 'États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'News of the World',
    director: 'Paul Greengrass',
    actors: [
      { name: 'Tom Hanks' },
      { name: 'Helena Zengel' },
      { name: 'Michael Covino' },
      { name: 'Mare Winningham' },
      { name: 'Elizabeth Marvel' },
    ],
    coverUrl:
      '/movies_pictures/801ca9915792.jpg',
    releaseDate: '2020-12-25',
    length: 118,
    genre: ['Western', 'Drame', 'Aventure'],
    saga: '',
    description:
      'Hanks 1870 lit les journaux fille Kiowa, Greengrass trop News 2020 118 min Texas trop trop route trop trop deuil trop trop voix.',
    fromEntity: {
      entityType: 'book',
      title: 'News of the World',
      secondEntityKey: 'Paulette Jiles',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Old Henry',
    director: 'Potsy Ponciroli',
    actors: [
      { name: 'Tim Blake Nelson' },
      { name: 'Scott Haze' },
      { name: 'Gavin Lewis' },
      { name: 'Stephen Dorff' },
      { name: 'Trace Adkins' },
    ],
    coverUrl:
      '/movies_pictures/2aa248e30682.jpg',
    releaseDate: '2021-10-01',
    length: 99,
    genre: ['Western', 'Drame', 'Thriller'],
    saga: '',
    description:
      "Nelson fermier 1906 sac d'or fils twist, Ponciroli trop Old Henry 2021 99 min huis trop trop western trop trop légende trop trop fusil.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Harder They Fall',
    director: 'Jeymes Samuel',
    actors: [
      { name: 'Jonathan Majors' },
      { name: 'Idris Elba' },
      { name: 'Zazie Beetz' },
      { name: 'Regina King' },
      { name: 'Delroy Lindo' },
    ],
    coverUrl:
      '/movies_pictures/705823c56ce3.jpg',
    releaseDate: '2021-10-22',
    length: 131,
    genre: ['Western', 'Action'],
    saga: '',
    description:
      'Majors Elba western black Netflix 131 min, Samuel trop Harder They Fall 2021 vengeance trop trop style trop trop pistolets trop trop ost.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "The Dead Don't Hurt",
    director: 'Viggo Mortensen',
    actors: [
      { name: 'Viggo Mortensen' },
      { name: 'Vicky Krieps' },
      { name: 'Solly McLeod' },
      { name: 'Garret Dillahunt' },
      { name: 'Danny Huston' },
    ],
    coverUrl:
      'https://resizing.flixster.com/Y9aEPDXruSytR8Xx5S_HcXNMJ0s=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzYwZTlmZjI3LWFkZDQtNDljYy1hMjg5LWVhMGU0MzMyZWNiZi5qcGc=',
    releaseDate: '2023-09-08',
    length: 129,
    genre: ['Western', 'Drame', 'Romance'],
    saga: '',
    description:
      "Krieps indépendante Mortensen soldat 1860 129 min, Dead Don't Hurt 2023 western trop trop femme trop trop frontière trop trop guerre.",
    fromEntity: null,
    countryOrigin: ['Canada', 'Mexique', 'Danemark'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Horizon : Une saga américaine',
    director: 'Kevin Costner',
    actors: [
      { name: 'Kevin Costner' },
      { name: 'Sienna Miller' },
      { name: 'Sam Worthington' },
      { name: 'Jena Malone' },
      { name: 'Abbey Lee' },
    ],
    coverUrl:
      '/movies_pictures/cf7535e83f3a.jpg',
    releaseDate: '2024-06-28',
    length: 181,
    genre: ['Western', 'Drame', 'Aventure', 'Historique'],
    saga: 'Horizon',
    description:
      'Costner 1860 181 min chapitre 1 pionniers guerres, Horizon 2024 saga trop trop américaine trop trop Cannes trop trop western trop trop fleuve.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Porte du paradis',
    director: 'Michael Cimino',
    actors: [
      { name: 'Kris Kristofferson' },
      { name: 'Christopher Walken' },
      { name: 'Isabelle Huppert' },
      { name: 'Jeff Bridges' },
      { name: 'John Hurt' },
    ],
    coverUrl: '/movies_pictures/fe18896cd978.jpg',
    releaseDate: '1980-11-19',
    length: 219,
    genre: ['Western', 'Drame', 'Historique'],
    saga: '',
    description:
      'Wyoming 1890, un shérif harvardien voit les immigrés massacrés par les barons du bétail.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Cavalier solitaire',
    director: 'Clint Eastwood',
    actors: [
      { name: 'Clint Eastwood' },
      { name: 'Michael Moriarty' },
      { name: 'Carrie Snodgress' },
      { name: 'Christopher Penn' },
      { name: 'Richard Dysart' },
    ],
    coverUrl: '/movies_pictures/30d99fe6dab7.jpg',
    releaseDate: '1985-06-28',
    length: 115,
    genre: ['Western'],
    saga: '',
    description:
      "Un prédicateur à cheval défend des chercheurs d'or contre un trust, six-coups et collier clerical.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Tombstone',
    director: 'George P. Cosmatos',
    actors: [
      { name: 'Kurt Russell' },
      { name: 'Val Kilmer' },
      { name: 'Sam Elliott' },
      { name: 'Bill Paxton' },
      { name: 'Powers Boothe' },
    ],
    coverUrl:
      '/movies_pictures/892971b94a69.jpg',
    releaseDate: '1993-12-25',
    length: 130,
    genre: ['Western', 'Drame', 'Biographie'],
    saga: '',
    description:
      "Wyatt Earp à Tombstone, Doc Holliday tuberculeux, O.K. Corral et « I'm your huckleberry ».",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Dead Man',
    director: 'Jim Jarmusch',
    actors: [
      { name: 'Johnny Depp' },
      { name: 'Gary Farmer' },
      { name: 'Lance Henriksen' },
      { name: 'Michael Wincott' },
      { name: 'Robert Mitchum' },
    ],
    coverUrl: '/movies_pictures/74df63ead15b.jpg',
    releaseDate: '1995-12-23',
    length: 121,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      "Un comptable blessé traverse l'Ouest avec un Amérindien, noir et blanc, Neil Young à la guitare.",
    fromEntity: null,
    countryOrigin: ['États-Unis', 'Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'The Assassination of Jesse James',
    director: 'Andrew Dominik',
    actors: [
      { name: 'Brad Pitt' },
      { name: 'Casey Affleck' },
      { name: 'Sam Shepard' },
      { name: 'Mary-Louise Parker' },
      { name: 'Sam Rockwell' },
    ],
    coverUrl:
      '/movies_pictures/6f399b0df58b.jpg',
    releaseDate: '2007-09-21',
    length: 160,
    genre: ['Western', 'Drame', 'Biographie'],
    saga: '',
    description:
      'Robert Ford trop fan tue Jesse trop fatigué, hiver trop long, Dominik trop beau.',
    fromEntity: {
      entityType: 'book',
      title: 'The Assassination of Jesse James by the Coward Robert Ford',
      secondEntityKey: 'Ron Hansen',
    },
    countryOrigin: ['États-Unis', 'Canada', 'Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
];
