import { BaseMovie } from '../../../models/movie-model';

export const baseMoviesAnimated: BaseMovie[] = [
  {
    title: 'Dragons',
    director: 'Dean DeBlois, Chris Sanders',
    actors: [{ name: 'Jay Baruchel' }],
    coverUrl: '/movies_pictures/dragon.jpg',
    releaseDate: '2010-03-26',
    length: 98,
    genre: ['Animation'],
    saga: 'Dragons',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Dragons 2',
    director: 'Dean DeBlois',
    actors: [{ name: 'Jay Baruchel' }],
    coverUrl:
      '/movies_pictures/69142-how-to-train-your-dragon-2-0-150-0-225-crop.jpg',
    releaseDate: '2014-06-13',
    length: 102,
    genre: ['Animation'],
    saga: 'Dragons',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Dragons 3 : Le Monde caché',
    director: 'Dean DeBlois',
    actors: [
      {
        name: 'Jay Baruchel',
      },
    ],
    coverUrl:
      '/movies_pictures/123067-how-to-train-your-dragon-the-hidden-world-0-150-0-225-crop.jpg',
    releaseDate: '2019-02-22',
    length: 104,
    genre: ['Animation'],
    saga: 'Dragons',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Spider-Man: Into the Spider-Verse',
    director: 'Bob Persichetti, Peter Ramsey, Rodney Rothman',
    actors: [
      {
        name: 'Shameik Moore',
      },
    ],
    coverUrl:
      '/movies_pictures/251943-spider-man-into-the-spider-verse-0-150-0-225-crop.jpg',
    releaseDate: '2018-12-14',
    length: 117,
    genre: ['Animation'],
    saga: 'Spider-Verse',
    description: '',
    fromEntity: {
      entityType: 'comic',
      title: 'Spider-Man',
      secondEntityKey: 'J. Michael Straczynski',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Spider-Man : À Travers le Spider-Verse',
    director: 'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson',
    actors: [
      {
        name: 'Shameik Moore',
      },
    ],
    coverUrl:
      '/movies_pictures/497631-spider-man-across-the-spider-verse-0-150-0-225-crop.jpg',
    releaseDate: '2023-06-02',
    length: 140,
    genre: ['Animation'],
    saga: 'Spider-Verse',
    description: '',
    fromEntity: {
      entityType: 'comic',
      title: 'Spider-Man',
      secondEntityKey: 'J. Michael Straczynski',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Les Mondes de Ralph',
    director: 'Rich Moore',
    actors: [{ name: 'John C. Reilly' }],
    coverUrl: '/movies_pictures/69154-wreck-it-ralph-0-150-0-225-crop.jpg',
    releaseDate: '2012-11-02',
    length: 101,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Ralph Breaks the Internet',
    director: 'Rich Moore, Phil Johnston',
    actors: [
      {
        name: 'John C. Reilly',
      },
    ],
    coverUrl:
      '/movies_pictures/338883-ralph-breaks-the-internet-0-150-0-225-crop.jpg',
    releaseDate: '2018-11-21',
    length: 112,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Super Mario Bros. le Film',
    director: 'Aaron Horvath, Michael Jelenic',
    actors: [
      {
        name: 'Chris Pratt',
      },
    ],
    coverUrl:
      '/movies_pictures/432302-the-super-mario-bros-movie-0-150-0-225-crop.jpg',
    releaseDate: '2023-04-05',
    length: 92,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Super Mario Bros.',
      secondEntityKey: 'Nintendo',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Encanto',
    director: 'Jared Bush, Byron Howard',
    actors: [
      {
        name: 'Stephanie Beatriz',
      },
    ],
    coverUrl: '/movies_pictures/496592-encanto-0-150-0-225-crop.jpg',
    releaseDate: '2021-11-24',
    length: 102,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Cars',
    director: 'John Lasseter',
    actors: [{ name: 'Owen Wilson' }],
    coverUrl:
      '/movies_pictures/dWg33ektXuHmxjSjEulwDPTWbC2-0-150-0-225-crop.jpg',
    releaseDate: '2006-06-09',
    length: 116,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Cars 2',
    director: 'John Lasseter, Brad Lewis',
    actors: [{ name: 'Owen Wilson' }],
    coverUrl: '/movies_pictures/Cars-2-movie-poster-cast-hi-res-01.webp',
    releaseDate: '2011-06-24',
    length: 106,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Cars 3',
    director: 'Brian Fee',
    actors: [{ name: 'Owen Wilson' }],
    coverUrl: '/movies_pictures/184062-cars-3-0-150-0-225-crop.jpg',
    releaseDate: '2016-06-16',
    length: 102,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Baby boss',
    director: 'Tom McGrath',
    actors: [{ name: 'Alec Baldwin' }],
    coverUrl: '/movies_pictures/223050-the-boss-baby-0-150-0-225-crop.jpg',
    releaseDate: '2017-03-31',
    length: 97,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Vaiana',
    director: 'Ron Clements, John Musker',
    actors: [{ name: "Auli'i Cravalho" }],
    coverUrl: '/movies_pictures/201909-moana-0-150-0-225-crop.jpg',
    releaseDate: '2016-11-23',
    length: 107,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Vaiana 2',
    director: 'David G. Derrick Jr., Jason Hand, Dana Ledoux Miller',
    actors: [
      {
        name: 'Timothée Chalamet',
      },
      {
        name: 'Edward Norton',
      },
      {
        name: 'Elle Fanning',
      },
      {
        name: 'Monica Barbaro',
      },
      {
        name: 'Boyd Holbrook',
      },
    ],
    coverUrl: '/movies_pictures/vaiana_2.jpg',
    releaseDate: '2024-11-27',
    length: 100,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Vice-Versa',
    director: 'Pete Docter',
    actors: [{ name: 'Amy Poehler' }],
    coverUrl: '/movies_pictures/113284-inside-out-0-150-0-225-crop.jpg',
    releaseDate: '2015-06-19',
    length: 95,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Les Nouveaux Héros',
    director: 'Don Hall, Chris Williams',
    actors: [{ name: 'Ryan Potter' }],
    coverUrl: '/movies_pictures/les_nouveaux_heros.jpg',
    releaseDate: '2014-11-07',
    length: 102,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'La Reine des Neiges',
    director: 'Chris Buck, Jennifer Lee',
    actors: [{ name: 'Kristen Bell' }],
    coverUrl: '/movies_pictures/reine_des_neiges.jpg',
    releaseDate: '2013-11-27',
    length: 102,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Moi, Moche et Méchant',
    director: 'Pierre Coffin, Chris Renaud',
    actors: [{ name: 'Steve Carell' }],
    coverUrl: '/movies_pictures/39067-despicable-me-0-150-0-225-crop.jpg',
    releaseDate: '2010-07-09',
    length: 95,
    genre: ['Animation'],
    saga: 'Moi, Moche et Méchant',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Moi, Moche et Méchant 2',
    director: 'Pierre Coffin, Chris Renaud',
    actors: [{ name: 'Steve Carell' }],
    coverUrl: '/movies_pictures/moi_moi_mechant_2.jpg',
    releaseDate: '2013-07-03',
    length: 98,
    genre: ['Animation'],
    saga: 'Moi, Moche et Méchant',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Les Cinq Légendes',
    director: 'Peter Ramsey',
    actors: [{ name: 'Chris Pine' }],
    coverUrl: '/movies_pictures/les_cinq_legendes.jpg',
    releaseDate: '2012-11-21',
    length: 97,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: "L'Âge de Glace",
    director: 'Chris Wedge, Carlos Saldanha',
    actors: [{ name: 'Ray Romano' }],
    coverUrl: '/movies_pictures/51670-ice-age-0-150-0-225-crop.jpg',
    releaseDate: '2002-03-15',
    length: 81,
    genre: ['Animation'],
    saga: "L'Age de Glace",
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: "L'Âge de Glace 2",
    director: 'Carlos Saldanha',
    actors: [{ name: 'Ray Romano' }],
    coverUrl: '/movies_pictures/age_de_glace_2.jpg',
    releaseDate: '2006-03-31',
    length: 91,
    genre: ['Animation'],
    saga: "L'Age de Glace",
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: "L'Âge de Glace 3 : Le Temps des Dinosaures",
    director: 'Carlos Saldanha',
    actors: [{ name: 'Ray Romano' }],
    coverUrl:
      '/movies_pictures/47781-ice-age-dawn-of-the-dinosaurs-0-150-0-225-crop.jpg',
    releaseDate: '2009-07-01',
    length: 94,
    genre: ['Animation'],
    saga: "L'Age de Glace",
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: "L'Âge de Glace 4 : La Dérive des Continents",
    director: 'Steve Martino, Mike Thurmeier',
    actors: [{ name: 'Ray Romano' }],
    coverUrl: '/movies_pictures/age_de_glace_4.jpg',
    releaseDate: '2012-07-13',
    length: 88,
    genre: ['Animation'],
    saga: "L'Age de Glace",
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Rebelle',
    director: 'Mark Andrews, Brenda Chapman',
    actors: [{ name: 'Kelly Macdonald' }],
    coverUrl: '/movies_pictures/rebelle.jpg',
    releaseDate: '2012-06-22',
    length: 93,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Arthur et les Minimoys',
    director: 'Luc Besson',
    actors: [
      {
        name: 'Freddie Highmore',
      },
    ],
    coverUrl:
      '/movies_pictures/46649-arthur-and-the-invisibles-0-150-0-225-crop.jpg',
    releaseDate: '2006-12-13',
    length: 94,
    genre: ['Fantastique'],
    saga: 'Minimoys',
    description: '',
    fromEntity: null,
    countryOrigin: ['France'],
  },
  {
    title: 'Arthur et la Vengeance de Maltazard',
    director: 'Luc Besson',
    actors: [
      {
        name: 'Freddie Highmore',
      },
    ],
    coverUrl:
      '/movies_pictures/35270-arthur-and-the-revenge-of-maltazard-0-150-0-225-crop.jpg',
    releaseDate: '2009-12-02',
    length: 94,
    genre: ['Aventure'],
    saga: 'Minimoys',
    description: '',
    fromEntity: null,
    countryOrigin: ['France'],
  },
  {
    title: 'Arthur 3 : La Guerre des Deux Mondes',
    director: 'Luc Besson',
    actors: [
      {
        name: 'Freddie Highmore',
      },
    ],
    coverUrl:
      '/movies_pictures/22170-arthur-3-the-war-of-the-two-worlds-0-150-0-225-crop.jpg',
    releaseDate: '2010-10-13',
    length: 101,
    genre: ['Aventure'],
    saga: 'Minimoys',
    description: '',
    fromEntity: null,
    countryOrigin: ['France'],
  },
  {
    title: 'La Princesse et la Grenouille',
    director: 'Ron Clements, John Musker',
    actors: [{ name: 'Anika Noni Rose' }],
    coverUrl:
      '/movies_pictures/bVRHirC6uIZL9VtRqYRxdedYnOG-0-150-0-225-crop.jpg',
    releaseDate: '2009-12-11',
    length: 97,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Tempête de Boulettes Géantes',
    director: 'Phil Lord, Christopher Miller',
    actors: [{ name: 'Bill Hader' }],
    coverUrl:
      '/movies_pictures/37696-cloudy-with-a-chance-of-meatballs-0-150-0-225-crop.jpg',
    releaseDate: '2009-09-18',
    length: 90,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Monstres contre Aliens',
    director: 'Rob Letterman, Conrad Vernon',
    actors: [{ name: 'Reese Witherspoon' }],
    coverUrl: '/movies_pictures/42315-monsters-vs-aliens-0-150-0-225-crop.jpg',
    releaseDate: '2009-03-27',
    length: 94,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'WALL-E',
    director: 'Andrew Stanton',
    actors: [{ name: 'Ben Burtt' }],
    coverUrl: '/movies_pictures/45994-walle-0-150-0-225-crop.jpg',
    releaseDate: '2008-06-27',
    length: 98,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },

  {
    title: "Bee Movie : Drôle d'Abeille",
    director: 'Steve Hickner, Simon J. Smith',
    actors: [{ name: 'Jerry Seinfeld' }],
    coverUrl: '/movies_pictures/48791-bee-movie-0-150-0-225-crop.jpg',
    releaseDate: '2007-11-02',
    length: 91,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Les Simpson, le Film',
    director: 'David Silverman',
    actors: [
      {
        name: 'Dan Castellaneta',
      },
    ],
    coverUrl: '/movies_pictures/2684-the-simpsons-movie-0-150-0-225-crop.jpg',
    releaseDate: '2007-07-27',
    length: 87,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: {
      entityType: 'serie',
      title: 'Les Simpsons',
      secondEntityKey: 'Matt Groening',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Ratatouille',
    director: 'Brad Bird',
    actors: [{ name: 'Patton Oswalt' }],
    coverUrl: '/movies_pictures/ratatouille.jpg',
    releaseDate: '2007-06-29',
    length: 111,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Shrek',
    director: 'Andrew Adamson, Vicky Jenson',
    actors: [{ name: 'Mike Myers' }],
    coverUrl: '/movies_pictures/51344-shrek-0-150-0-225-crop.jpg',
    releaseDate: '2001-05-18',
    length: 90,
    genre: ['Animation'],
    saga: 'Shrek',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Shrek 2',
    director: 'Andrew Adamson, Kelly Asbury, Conrad Vernon',
    actors: [{ name: 'Mike Myers' }],
    coverUrl: '/movies_pictures/shrek_2.jpg',
    releaseDate: '2004-05-19',
    length: 93,
    genre: ['Animation'],
    saga: 'Shrek',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Shrek le Troisième',
    director: 'Chris Miller',
    actors: [{ name: 'Mike Myers' }],
    coverUrl: '/movies_pictures/shrek_3.jpg',
    releaseDate: '2007-05-18',
    length: 93,
    genre: ['Animation'],
    saga: 'Shrek',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Shrek 4 : Il Était une Fois',
    director: 'Mike Mitchell',
    actors: [{ name: 'Mike Myers' }],
    coverUrl: '/movies_pictures/shrek_4.jpg',
    releaseDate: '2010-05-21',
    length: 93,
    genre: ['Animation'],
    saga: 'Shrek',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Les Indestructibles',
    director: 'Brad Bird',
    actors: [{ name: 'Craig T. Nelson' }],
    coverUrl: '/movies_pictures/46806-the-incredibles-0-150-0-225-crop.jpg',
    releaseDate: '2004-11-05',
    length: 115,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Les Indestructibles 2',
    director: 'Brad Bird',
    actors: [
      {
        name: 'Craig T. Nelson',
      },
    ],
    coverUrl: '/movies_pictures/184061-incredibles-2-0-150-0-225-crop.jpg',
    releaseDate: '2018-06-15',
    length: 118,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le monde de Nemo',
    director: 'Andrew Stanton',
    actors: [{ name: 'Albert Brooks' }],
    coverUrl: '/movies_pictures/monde_de_nemo.webp',
    releaseDate: '2003-05-30',
    length: 100,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le monde de Dory',
    director: 'Andrew Stanton, Angus MacLane',
    actors: [{ name: 'Ellen DeGeneres' }],
    coverUrl: '/movies_pictures/478890.webp',
    releaseDate: '2016-06-17',
    length: 97,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Planes',
    director: 'Klay Hall',
    actors: [{ name: 'Dane Cook' }],
    coverUrl: '/movies_pictures/21010313_20130604174723216.webp',
    releaseDate: '2013-07-17',
    length: 84,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Planes 2',
    director: 'Roberts Gannaway',
    actors: [{ name: 'Dane Cook' }],
    coverUrl: '/movies_pictures/218398.jpg',
    releaseDate: '2018-08-03',
    length: 102,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Monstres et Cie',
    director: 'Pete Docter',
    actors: [{ name: 'John Goodman' }],
    coverUrl: '/movies_pictures/monstres_et_compagnie.jpg',
    releaseDate: '2001-11-02',
    length: 92,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Toy Story',
    director: 'John Lasseter',
    actors: [{ name: 'Tom Hanks' }],
    coverUrl: '/movies_pictures/51290-toy-story-0-150-0-225-crop.jpg',
    releaseDate: '1995-11-22',
    length: 81,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Toy Story 2',
    director: 'John Lasseter',
    actors: [{ name: 'Tom Hanks' }],
    coverUrl: '/movies_pictures/51289-toy-story-2-0-150-0-225-crop.jpg',
    releaseDate: '1999-11-24',
    length: 92,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Toy Story 3',
    director: 'Lee Unkrich',
    actors: [{ name: 'Tom Hanks' }],
    coverUrl: '/movies_pictures/46458-toy-story-3-0-150-0-225-crop.jpg',
    releaseDate: '2010-06-18',
    length: 103,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Toy Story 4',
    director: 'Josh Cooley',
    actors: [
      {
        name: 'Tom Hanks',
      },
      {
        name: 'Tim Allen',
      },
      {
        name: 'Annie Potts',
      },
    ],
    coverUrl: '/movies_pictures/toy_story_4.jpg',
    releaseDate: '2019-06-26',
    length: 100,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'South Park, le Film',
    director: 'Trey Parker',
    actors: [
      {
        name: 'Trey Parker',
      },
    ],
    coverUrl:
      '/movies_pictures/47125-south-park-bigger-longer-uncut-0-150-0-225-crop.jpg',
    releaseDate: '1999-06-30',
    length: 81,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: {
      entityType: 'serie',
      title: 'South Park',
      secondEntityKey: 'Trey Parker, Matt Stone',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Tarzan',
    director: 'Chris Buck, Kevin Lima',
    actors: [{ name: 'Tony Goldwyn' }],
    coverUrl: '/movies_pictures/tarzan.jpg',
    releaseDate: '1999-06-18',
    length: 88,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'La Légende de Tarzan et Jane',
    director: 'Steve Loter, Victor Cook',
    actors: [
      {
        name: 'Michael T. Weiss',
      },
      {
        name: "Olivia d'Abo",
      },
      {
        name: 'Jim Cummings',
      },
    ],
    coverUrl: '/movies_pictures/tarzan_jane.jpg',
    releaseDate: '2002-07-03',
    length: 72,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Fourmiz',
    director: 'Eric Darnell, Tim Johnson',
    actors: [{ name: 'Woody Allen' }],
    coverUrl: '/movies_pictures/47511-antz-0-150-0-225-crop.jpg',
    releaseDate: '1998-10-02',
    length: 83,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Mulan',
    director: 'Tony Bancroft, Barry Cook',
    actors: [{ name: 'Ming-Na Wen' }],
    coverUrl:
      '/movies_pictures/225c87f4348a.jpg',
    releaseDate: '1998-06-19',
    length: 87,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Princesse Mononoké',
    director: 'Hayao Miyazaki',
    actors: [{ name: 'Yôji Matsuda' }],
    coverUrl:
      '/movies_pictures/mNqZOtJIQfFQPjo3hmYLIn8Qqhf-0-150-0-225-crop.jpg',
    releaseDate: '1997-07-12',
    length: 134,
    genre: ['Animation'],
    saga: 'Ghibli',
    description: '',
    fromEntity: null,
    countryOrigin: ['Japon'],
  },
  {
    title: 'Hercule',
    director: 'Ron Clements, John Musker',
    actors: [{ name: 'Tate Donovan' }],
    coverUrl: '/movies_pictures/44838-hercules-0-150-0-225-crop.jpg',
    releaseDate: '1997-06-27',
    length: 93,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Pocahontas',
    director: 'Mike Gabriel, Eric Goldberg',
    actors: [{ name: 'Irene Bedard' }],
    coverUrl: '/movies_pictures/pocahontas.jpg',
    releaseDate: '1995-06-23',
    length: 81,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Space Jam',
    director: 'Joe Pytka',
    actors: [{ name: 'Michael Jordan' }],
    coverUrl: '/movies_pictures/space_jam.jpg',
    releaseDate: '1996-11-15',
    length: 88,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le Roi Lion',
    director: 'Roger Allers, Rob Minkoff',
    actors: [{ name: 'Matthew Broderick' }],
    coverUrl: '/movies_pictures/le roi lion.jpg',
    releaseDate: '1994-06-24',
    length: 88,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Aladdin',
    director: 'Ron Clements, John Musker',
    actors: [{ name: 'Scott Weinger' }],
    coverUrl: '/movies_pictures/aladdin_film.jpg',
    releaseDate: '1992-11-25',
    length: 90,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'La Belle et la Bête',
    director: 'Gary Trousdale, Kirk Wise',
    actors: [{ name: 'Paige O\'Hara' }],
    coverUrl:
      '/movies_pictures/10020-beauty-and-the-beast-1991-animated-0-150-0-225-crop.jpg',
    releaseDate: '1991-11-22',
    length: 84,
    genre: ['Animation', 'Comédie musicale'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'La petite sirène',
    director: 'Ron Clements, John Musker',
    actors: [{ name: 'Jodi Benson' }],
    coverUrl: '/movies_pictures/la_petite_sirene.jpg',
    releaseDate: '1989-11-17',
    length: 83,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Peter Pan',
    director: 'Clyde Geronimi, Wilfred Jackson, Hamilton Luske',
    actors: [{ name: 'Bobby Driscoll' }],
    coverUrl: '/movies_pictures/45983-peter-pan-0-150-0-225-crop.jpg',
    releaseDate: '1953-02-05',
    length: 77,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Pinocchio',
    director:
      'Norman Ferguson, T. Hee, Wilfred Jackson, Jack Kinney, Hamilton Luske, Bill Roberts, Ben Sharpsteen',
    actors: [
      {
        name: 'Dickie Jones',
      },
    ],
    coverUrl: '/movies_pictures/45797-pinocchio-0-150-0-225-crop.jpg',
    releaseDate: '1940-02-07',
    length: 88,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Megamind',
    director: 'Tom McGrath',
    actors: [{ name: 'Will Ferrell' }],
    coverUrl: '/movies_pictures/26476-megamind-0-150-0-225-crop.jpg',
    releaseDate: '2010-11-05',
    length: 95,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Horton',
    director: 'Jimmy Hayward, Steve Martino',
    actors: [{ name: 'Jim Carrey' }],
    coverUrl: '/movies_pictures/horton.jpg',
    releaseDate: '2008-03-14',
    length: 86,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Raya et le Dernier Dragon',
    director: 'Don Hall, Carlos López Estrada',
    actors: [
      {
        name: 'Kelly Marie Tran',
      },
    ],
    coverUrl:
      '/movies_pictures/457180-raya-and-the-last-dragon-0-150-0-225-crop.jpg',
    releaseDate: '2021-03-05',
    length: 107,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'One Piece : Le film',
    director: 'Junji Shimizu',
    actors: [],
    coverUrl: '/movies_pictures/One_Piece_Le_Film.webp',
    releaseDate: '2000-03-04',
    length: 52,
    genre: ['Animation'],
    saga: 'One Piece OAV',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'One Piece',
      secondEntityKey: 'Eiichirō Oda',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: "One Piece : L'Aventure de l'île de l'horloge",
    director: 'Atsuji Shimizu',
    actors: [],
    coverUrl:
      '/movies_pictures/MV5BNDRjN2NmNDAtZDE3Mi00ZDJlLTkwODktMmNkMTBkYTRjMTY3XkEyXkFqcGc@._V1_.jpg',
    releaseDate: '2001-03-03',
    length: 55,
    genre: ['Animation'],
    saga: 'One Piece OAV',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'One Piece',
      secondEntityKey: 'Eiichirō Oda',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: "One Piece : Le Royaume de Chopper, l'île des bêtes étranges",
    director: 'Atsuji Shimizu',
    actors: [],
    coverUrl: '/movies_pictures/Film_3_Poster_Alternatif.webp',
    releaseDate: '2002-03-02',
    length: 55,
    genre: ['Animation'],
    saga: 'One Piece OAV',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'One Piece',
      secondEntityKey: 'Eiichirō Oda',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: "One Piece : L'Aventure sans issue",
    director: 'Kōnosuke Uda',
    actors: [],
    coverUrl:
      '/movies_pictures/MV5BOGI3ZDRhMmUtZjdlYy00OTJlLTk5OTYtYmViNTU2ODhjNzQ5XkEyXkFqcGc@._V1_.jpg',
    releaseDate: '2003-03-01',
    length: 95,
    genre: ['Animation'],
    saga: 'One Piece OAV',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'One Piece',
      secondEntityKey: 'Eiichirō Oda',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: "One Piece : La Malédiction de l'épée sacrée",
    director: 'Kazuhisa Takenouchi',
    actors: [],
    coverUrl: '/movies_pictures/910Srb-MFTL._AC_UF1000,1000_QL80_.jpg',
    releaseDate: '2004-03-06',
    length: 95,
    genre: ['Animation'],
    saga: 'One Piece OAV',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'One Piece',
      secondEntityKey: 'Eiichirō Oda',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: "One Piece : Le baron Omatsuri et l'île secrète",
    director: 'Mamoru Hosoda',
    actors: [],
    coverUrl: '/movies_pictures/Affiche_Film_6.webp',
    releaseDate: '2005-03-05',
    length: 92,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'One Piece',
      secondEntityKey: 'Eiichirō Oda',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'One Piece : Le Mecha géant du château Karakuri',
    director: 'Kōnosuke Uda',
    actors: [],
    coverUrl: '/movies_pictures/91m0qFuWRXL.jpg',
    releaseDate: '2006-03-04',
    length: 94,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'One Piece',
      secondEntityKey: 'Eiichirō Oda',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'One Piece Film: Strong World',
    director: 'Munehisa Sakai',
    actors: [
      {
        name: 'Bruce Campbell',
      },
      {
        name: 'Ellen Sandweiss',
      },
      {
        name: 'Richard DeManincor',
      },
    ],
    coverUrl: '/movies_pictures/one_piece_film_strong_world.jpg',
    releaseDate: '2011-08-24',
    length: 113,
    genre: ['Animation'],
    saga: 'One Piece OAV',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'One Piece',
      secondEntityKey: 'Eiichirō Oda',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'One Piece Film Z',
    director: 'Tatsuya Nagamine',
    actors: [
      {
        name: 'Mayumi Tanaka',
      },
      {
        name: 'Kazuya Nakai',
      },
      {
        name: 'Akemi Okamura',
      },
    ],
    coverUrl: '/movies_pictures/one_piece_film_z.jpg',
    releaseDate: '2013-05-15',
    length: 107,
    genre: ['Animation'],
    saga: 'One Piece OAV',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'One Piece',
      secondEntityKey: 'Eiichirō Oda',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'One Piece : Gold',
    director: 'Hiroaki Miyamoto',
    actors: [],
    coverUrl: '/movies_pictures/227162.jpg',
    releaseDate: '2016-07-23',
    length: 120,
    genre: ['Animation'],
    saga: 'One Piece OAV',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'One Piece',
      secondEntityKey: 'Eiichirō Oda',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'One Piece: Stampede',
    director: 'Takashi Otsuka',
    actors: [],
    coverUrl: '/movies_pictures/91rrgo7knjL._AC_UF894,1000_QL80_.jpg',
    releaseDate: '2019-08-09',
    length: 101,
    genre: ['Animation'],
    saga: 'One Piece OAV',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'One Piece',
      secondEntityKey: 'Eiichirō Oda',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'One Piece Film: Red',
    director: 'Gorō Taniguchi',
    actors: [
      {
        name: 'Mayumi Tanaka',
      },
      {
        name: 'Kaori Nazuka',
      },
      {
        name: 'Ado',
      },
    ],
    coverUrl: '/movies_pictures/one_piece_film_red.jpg',
    releaseDate: '2022-08-10',
    length: 115,
    genre: ['Animation'],
    saga: 'One Piece OAV',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'One Piece',
      secondEntityKey: 'Eiichirō Oda',
    },
    countryOrigin: ['Japon'],
  },

  {
    title: 'Élémentaire',
    director: 'Peter Sohn',
    actors: [{ name: 'Leah Lewis' }, { name: 'Mamoudou Athie' }],
    coverUrl: '/movies_pictures/5709179.jpg',
    releaseDate: '2023-06-16',
    length: 102,
    genre: ['Animation', 'Romance'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'La Colline aux coquelicots',
    director: 'Gorō Miyazaki',
    actors: [
      {
        name: 'James Franco',
      },
      {
        name: 'Freida Pinto',
      },
      {
        name: 'Andy Serkis',
      },
    ],
    coverUrl: '/movies_pictures/from_up_on_poppy_hill.jpg',
    releaseDate: '2012-01-11',
    length: 91,
    genre: ['Animation'],
    saga: 'Ghibli',
    description: '',
    fromEntity: null,
    countryOrigin: ['Japon'],
  },
  {
    title: 'Superman/Batman : Apocalypse',
    director: 'Lauren Montgomery',
    actors: [
      {
        name: 'Tim Daly',
      },
      {
        name: 'Kevin Conroy',
      },
      {
        name: 'Summer Glau',
      },
    ],
    coverUrl: '/movies_pictures/superman_batman_apocalypse.jpg',
    releaseDate: '2010-10-27',
    length: 78,
    genre: ['Animation'],
    saga: 'DC Animated Universe',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Batman et Red Hood : Sous le masque rouge',
    director: 'Brandon Vietti',
    actors: [
      {
        name: 'Bruce Greenwood',
      },
      {
        name: 'Jensen Ackles',
      },
      {
        name: 'Neil Patrick Harris',
      },
    ],
    coverUrl: '/movies_pictures/batman_under_the_red_hood.jpg',
    releaseDate: '2010-09-01',
    length: 75,
    genre: ['Animation'],
    saga: 'DC Animated Universe',
    description: '',
    fromEntity: {
      entityType: 'comic',
      title: 'Batman',
      secondEntityKey: 'DC Comics',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Superman/Batman : Ennemis publics',
    director: 'Sam Liu',
    actors: [
      {
        name: 'Tim Daly',
      },
      {
        name: 'Kevin Conroy',
      },
      {
        name: 'Clancy Brown',
      },
    ],
    coverUrl: '/movies_pictures/superman_batman_public_enemies.jpg',
    releaseDate: '2010-09-01',
    length: 67,
    genre: ['Animation'],
    saga: 'DC Animated Universe',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'TMNT : Les Tortues Ninja',
    director: 'Kevin Munroe',
    actors: [
      {
        name: 'James Arnold Taylor',
      },
      {
        name: 'Nolan North',
      },
      {
        name: 'Sarah Michelle Gellar',
      },
    ],
    coverUrl: '/movies_pictures/tmnt.jpg',
    releaseDate: '2007-04-11',
    length: 86,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Astérix et les Vikings',
    director: 'Stefan Fjeldmark, Jesper Møller',
    actors: [
      {
        name: 'Roger Carel',
      },
      {
        name: 'Jacques Frantz',
      },
      {
        name: 'Lorànt Deutsch',
      },
    ],
    coverUrl: '/movies_pictures/asterix_and_the_vikings.jpg',
    releaseDate: '2006-04-12',
    length: 78,
    genre: ['Animation'],
    saga: 'Astérix',
    description: '',
    fromEntity: {
      entityType: 'comic',
      title: 'Astérix le Gaulois',
      secondEntityKey: 'René Goscinny',
    },
    countryOrigin: ['France'],
  },
  {
    title: 'Le Pôle Express',
    director: 'Robert Zemeckis',
    actors: [
      {
        name: 'Tom Hanks',
      },
      {
        name: 'Nona Gaye',
      },
      {
        name: 'Eddie Deezen',
      },
    ],
    coverUrl: '/movies_pictures/the_polar_express.jpg',
    releaseDate: '2004-12-01',
    length: 99,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Gang de requins',
    director: 'Vicky Jenson, Bibo Bergeron, Rob Letterman',
    actors: [
      {
        name: 'Will Smith',
      },
      {
        name: 'Robert De Niro',
      },
      {
        name: 'Renée Zellweger',
      },
    ],
    coverUrl: '/movies_pictures/shark_tale.jpg',
    releaseDate: '2004-10-13',
    length: 90,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le Château ambulant',
    director: 'Hayao Miyazaki',
    actors: [
      {
        name: 'Chieko Baishô',
      },
      {
        name: 'Takuya Kimura',
      },
      {
        name: 'Akihiro Miwa',
      },
    ],
    coverUrl: '/movies_pictures/howl_s_moving_castle.jpg',
    releaseDate: '2005-01-12',
    length: 119,
    genre: ['Animation'],
    saga: 'Ghibli',
    description: '',
    fromEntity: null,
    countryOrigin: ['Japon'],
  },
  {
    title: 'Batman : La Mystérieuse Batwoman',
    director: 'Curt Geda',
    actors: [
      {
        name: 'Kevin Conroy',
      },
      {
        name: 'Kyra Sedgwick',
      },
      {
        name: 'Kimberly Brooks',
      },
    ],
    coverUrl: '/movies_pictures/batman_mystery_of_the_batwoman.jpg',
    releaseDate: '2003-10-21',
    length: 75,
    genre: ['Animation'],
    saga: 'DC Animated Universe',
    description: '',
    fromEntity: {
      entityType: 'comic',
      title: 'Batman',
      secondEntityKey: 'DC Comics',
    },
    countryOrigin: ['États-Unis'],
  },

  {
    title: 'Le Robot sauvage',
    director: 'Chris Sanders',
    actors: [
      {
        name: "Lupita Nyong'o",
      },
      {
        name: 'Pedro Pascal',
      },
      {
        name: "Catherine O'Hara",
      },
      {
        name: 'Bill Nighy',
      },
      {
        name: 'Kit Connor',
      },
    ],
    coverUrl: '/movies_pictures/le_robot_sauvage.jpg',
    releaseDate: '2024-10-09',
    length: 102,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Batman vs. Robin',
    director: 'Jay Oliva',
    actors: [
      {
        name: "Jason O'Mara",
      },
      {
        name: 'Stuart Allan',
      },
      {
        name: 'Jeremy Sisto',
      },
    ],
    coverUrl: '/movies_pictures/batman_vs_robin.jpg',
    releaseDate: '2015-04-22',
    length: 76,
    genre: ['Animation'],
    saga: 'DC Animated Universe',
    description: '',
    fromEntity: {
      entityType: 'comic',
      title: 'Batman',
      secondEntityKey: 'DC Comics',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Astérix : Le Domaine des dieux',
    director: 'Louis Clichy, Alexandre Astier',
    actors: [
      {
        name: 'Roger Carel',
      },
      {
        name: 'Lorànt Deutsch',
      },
      {
        name: 'Laurent Lafitte',
      },
    ],
    coverUrl: '/movies_pictures/asterix_the_mansions_of_the_gods.jpg',
    releaseDate: '2014-11-26',
    length: 85,
    genre: ['Comédie', 'Fantastique', 'Aventure', 'Animation'],
    saga: 'Astérix',
    description: '',
    fromEntity: {
      entityType: 'bd',
      title: 'Le Domaine des dieux',
      secondEntityKey: 'René Goscinny',
    },
    countryOrigin: ['France'],
  },
  {
    title: 'Batman: The Dark Knight Returns, Part 2',
    director: 'Jay Oliva',
    actors: [
      {
        name: 'Peter Weller',
      },
      {
        name: 'Ariel Winter',
      },
      {
        name: 'Michael Emerson',
      },
    ],
    coverUrl: '/movies_pictures/batman_the_dark_knight_returns_part_2.jpg',
    releaseDate: '2013-05-02',
    length: 78,
    genre: ['Animation'],
    saga: 'DC Animated Universe',
    description: '',
    fromEntity: {
      entityType: 'comic',
      title: 'Batman',
      secondEntityKey: 'DC Comics',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Batman: The Dark Knight Returns, Part 1',
    director: 'Jay Oliva',
    actors: [
      {
        name: 'Peter Weller',
      },
      {
        name: 'Ariel Winter',
      },
      {
        name: 'David Selby',
      },
    ],
    coverUrl: '/movies_pictures/batman_the_dark_knight_returns_part_1.jpg',
    releaseDate: '2013-05-02',
    length: 76,
    genre: ['Animation'],
    saga: 'DC Animated Universe',
    description: '',
    fromEntity: {
      entityType: 'comic',
      title: 'Batman',
      secondEntityKey: 'DC Comics',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: "Superman contre l'Élite",
    director: 'Michael Chang',
    actors: [
      {
        name: 'Kelly Macdonald',
      },
      {
        name: 'Billy Connolly',
      },
      {
        name: 'Emma Thompson',
      },
    ],
    coverUrl: '/movies_pictures/superman_vs_the_elite.jpg',
    releaseDate: '2012-07-04',
    length: 76,
    genre: ['Animation'],
    saga: 'DC Animated Universe',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le Lorax',
    director: 'Chris Renaud, Kyle Balda',
    actors: [
      {
        name: 'Danny DeVito',
      },
      {
        name: 'Zac Efron',
      },
      {
        name: 'Taylor Swift',
      },
    ],
    coverUrl: '/movies_pictures/the_lorax.jpg',
    releaseDate: '2012-07-18',
    length: 86,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Batman: Year One',
    director: 'Sam Liu, Lauren Montgomery',
    actors: [
      {
        name: 'Ben McKenzie',
      },
      {
        name: 'Bryan Cranston',
      },
      {
        name: 'Eliza Dushku',
      },
    ],
    coverUrl: '/movies_pictures/batman_year_one.jpg',
    releaseDate: '2012-07-04',
    length: 64,
    genre: ['Animation'],
    saga: 'DC Animated Universe',
    description: '',
    fromEntity: {
      entityType: 'comic',
      title: 'Batman',
      secondEntityKey: 'DC Comics',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Wish : Asha et la Bonne Étoile',
    director: 'Chris Buck, Fawn Veerasunthorn',
    actors: [
      {
        name: 'Ariana DeBose',
      },
      {
        name: 'Chris Pine',
      },
      {
        name: 'Alan Tudyk',
      },
      {
        name: 'Angelique Cabral',
      },
      {
        name: 'Victor Garber',
      },
    ],
    coverUrl: '/movies_pictures/wish_asha_et_la_bonne_etoile.jpg',
    releaseDate: '2023-11-29',
    length: 95,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Teenage Mutant Ninja Turtles: Mutant Mayhem',
    director: 'Jeff Rowe, Kyler Spears',
    actors: [
      {
        name: 'Micah Abbey',
      },
      {
        name: 'Shamon Brown Jr.',
      },
      {
        name: 'Nicolas Cantu',
      },
      {
        name: 'Brady Noon',
      },
      {
        name: 'Jackie Chan',
      },
    ],
    coverUrl: '/movies_pictures/teenage_mutant_ninja_turtles_mutant_mayhem.jpg',
    releaseDate: '2023-08-09',
    length: 99,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Krypto et les Super-Animaux',
    director: 'Jared Stern, Sam Levine',
    actors: [
      {
        name: 'Dwayne Johnson',
      },
      {
        name: 'Kevin Hart',
      },
      {
        name: 'Kate McKinnon',
      },
    ],
    coverUrl: '/movies_pictures/krypto_et_les_super-animaux.jpg',
    releaseDate: '2022-07-27',
    length: 106,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le Monstre des mers',
    director: 'Chris Williams',
    actors: [
      {
        name: 'Karl Urban',
      },
      {
        name: 'Zaris-Angel Hator',
      },
      {
        name: 'Jared Harris',
      },
    ],
    coverUrl: '/movies_pictures/le_monstre_des_mers.jpg',
    releaseDate: '2022-07-08',
    length: 115,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Astérix : Le Secret de la potion magique',
    director: 'Louis Clichy, Alexandre Astier',
    actors: [
      {
        name: 'Christian Clavier',
      },
      {
        name: 'Guillaume Briat',
      },
      {
        name: 'Alexandre Astier',
      },
    ],
    coverUrl: '/movies_pictures/asterix_the_secret_of_the_magic_potion.jpg',
    releaseDate: '2018-12-05',
    length: 85,
    genre: ['Animation'],
    saga: 'Astérix',
    description: '',
    fromEntity: {
      entityType: 'book',
      title: 'Astérix le Gaulois',
      secondEntityKey: 'René Goscinny',
    },
    countryOrigin: ['France'],
  },
  {
    title: 'Lego Batman, le film',
    director: 'Chris McKay',
    actors: [
      {
        name: 'Will Arnett',
      },
      {
        name: 'Michael Cera',
      },
      {
        name: 'Rosario Dawson',
      },
    ],
    coverUrl: '/movies_pictures/the_lego_batman_movie.jpg',
    releaseDate: '2017-02-08',
    length: 104,
    genre: ['Animation'],
    saga: 'Lego',
    description: '',
    fromEntity: {
      entityType: 'comic',
      title: 'Batman',
      secondEntityKey: 'DC Comics',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Sing',
    director: 'Garth Jennings',
    actors: [
      {
        name: 'Matthew McConaughey',
      },
      {
        name: 'Reese Witherspoon',
      },
      {
        name: 'Seth MacFarlane',
      },
    ],
    coverUrl: '/movies_pictures/sing.jpg',
    releaseDate: '2017-01-25',
    length: 108,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
];
