import { BaseMovie, OscarEnum } from '../../../models/movie-model';

/**
 * Films manquants — patrimoine 1920-1939. Années entre parenthèses absentes des titres.
 * coverUrl laissé vide.
 */
export const baseMoviesMissingPatrimoine19201939: BaseMovie[] = [
  {
    title: 'Le Cabinet du docteur Caligari',
    director: 'Robert Wiene',
    actors: [
      { name: 'Werner Krauss' },
      { name: 'Conrad Veidt' },
      { name: 'Lil Dagover' },
      { name: 'Friedrich Feher' },
      { name: 'Hans Heinrich von Twardowski' },
    ],
    coverUrl:
      '/movies_pictures/6c96c94b03da.jpg',
    releaseDate: '1920-02-26',
    length: 76,
    genre: ['Horreur', 'Fantastique'],
    saga: '',
    description:
      "Un hypnotiseur présente un somnambule dans une foire, au cœur d'une ville expressionniste minée par une série de meurtres.",
    fromEntity: null,
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Trois Lumières',
    director: 'Fritz Lang',
    actors: [
      { name: 'Lil Dagover' },
      { name: 'Walter Janssen' },
      { name: 'Bernhard Goetzke' },
      { name: 'Hans Sternberg' },
      { name: 'Max Adalbert' },
    ],
    coverUrl:
      '/movies_pictures/b6d5f796c489.jpg',
    releaseDate: '1921-10-06',
    length: 105,
    genre: ['Fantastique', 'Drame'],
    saga: '',
    description:
      "Une jeune femme plaide auprès de la Mort pour sauver son fiancé, à travers trois récits d'époques différentes.",
    fromEntity: null,
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Docteur Mabuse le joueur',
    director: 'Fritz Lang',
    actors: [
      { name: 'Rudolf Klein-Rogge' },
      { name: 'Aud Egede-Nissen' },
      { name: 'Gertrude Welcker' },
      { name: 'Alfred Abel' },
      { name: 'Bernhard Goetzke' },
    ],
    coverUrl: '/movies_pictures/bfc4cac05cc6.jpg',
    releaseDate: '1922-04-27',
    length: 270,
    genre: ['Thriller', 'Policier'],
    saga: 'Docteur Mabuse',
    description:
      "Un maître du crime et de l'hypnose sème le chaos dans le Berlin de l'après-guerre, poursuivi par le procureur von Wenk.",
    fromEntity: null,
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Sorcellerie à travers les âges',
    director: 'Benjamin Christensen',
    actors: [
      { name: 'Benjamin Christensen' },
      { name: 'Maren Pedersen' },
      { name: 'Clara Pontoppidan' },
      { name: 'Oscar Stribolt' },
      { name: 'Astrid Holm' },
    ],
    coverUrl:
      '/movies_pictures/ceee36d0fdef.jpg',
    releaseDate: '1922-09-18',
    length: 91,
    genre: ['Horreur', 'Documentaire'],
    saga: '',
    description:
      'Docufiction sur la sorcellerie, de la chasse aux sorcières médiévale aux névroses modernes.',
    fromEntity: null,
    countryOrigin: ['Suède', 'Danemark'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Nanouk l'Esquimau",
    director: 'Robert J. Flaherty',
    actors: [
      { name: 'Allakariallak' },
      { name: 'Nyla' },
      { name: 'Cunayou' },
      { name: 'Allee' },
      { name: 'Allegoo' },
    ],
    coverUrl:
      '/movies_pictures/e08db181bfd6.jpg',
    releaseDate: '1922-06-11',
    length: 79,
    genre: ['Documentaire'],
    saga: '',
    description:
      "La vie quotidienne d'une famille inuit dans l'Arctique canadien, filmée comme un récit de survie.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Nosferatu le vampire',
    director: 'F. W. Murnau',
    actors: [
      { name: 'Max Schreck' },
      { name: 'Gustav von Wangenheim' },
      { name: 'Greta Schröder' },
      { name: 'Alexander Granach' },
      { name: 'John Gottowt' },
    ],
    coverUrl:
      '/movies_pictures/b75ed1ae5bfe.jpg',
    releaseDate: '1922-03-04',
    length: 94,
    genre: ['Horreur'],
    saga: '',
    description:
      'Le comte Orlok quitte les Carpates pour Wisborg, apportant avec lui la peste et la soif de sang.',
    fromEntity: {
      entityType: 'book',
      title: 'Dracula',
      secondEntityKey: 'Bram Stoker',
    },
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Opinion publique",
    director: 'Charlie Chaplin',
    actors: [
      { name: 'Edna Purviance' },
      { name: 'Adolphe Menjou' },
      { name: 'Carl Miller' },
      { name: 'Lydia Knott' },
      { name: 'Charles K. French' },
    ],
    coverUrl:
      '/movies_pictures/aaa6375f3981.jpg',
    releaseDate: '1923-09-26',
    length: 82,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      "À Paris, une jeune femme devient la maîtresse d'un homme riche, jusqu'à ce que le scandale éclate.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Roue',
    director: 'Abel Gance',
    actors: [
      { name: 'Séverin-Mars' },
      { name: 'Ivy Close' },
      { name: 'Gabriel de Gravone' },
      { name: 'Pierre Magnier' },
      { name: 'Georges Térof' },
    ],
    coverUrl: '/movies_pictures/1e8b3966fdef.jpg',
    releaseDate: '1923-02-17',
    length: 273,
    genre: ['Drame'],
    saga: '',
    description:
      "Un mécanicien de locomotive élève une orpheline et voit sa famille se déchirer autour d'un amour impossible.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Les Lois de l'hospitalité",
    director: 'Buster Keaton',
    actors: [
      { name: 'Buster Keaton' },
      { name: 'Natalie Talmadge' },
      { name: 'Joe Roberts' },
      { name: 'Joe Keaton' },
      { name: 'Craig Ward' },
    ],
    coverUrl:
      '/movies_pictures/1e238297dff4.jpg',
    releaseDate: '1923-11-19',
    length: 74,
    genre: ['Comédie'],
    saga: '',
    description:
      'Un jeune New-Yorkais découvre que sa fiancée appartient à une famille rivale, en pleine vendetta dans le Sud.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Monte là-dessus !',
    director: 'Fred C. Newmeyer, Sam Taylor',
    actors: [
      { name: 'Harold Lloyd' },
      { name: 'Mildred Davis' },
      { name: 'Bill Strother' },
      { name: 'Noah Young' },
      { name: 'Westcott Clarke' },
    ],
    coverUrl:
      '/movies_pictures/a72a77cf4a38.jpg',
    releaseDate: '1923-04-01',
    length: 73,
    genre: ['Comédie'],
    saga: '',
    description:
      "Un vendeur grimpe la façade d'un immeuble pour impressionner sa fiancée, suspendu aux aiguilles de l'horloge.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Croisière du Navigator',
    director: 'Buster Keaton, Donald Crisp',
    actors: [
      { name: 'Buster Keaton' },
      { name: 'Kathryn McGuire' },
      { name: 'Frederick Vroom' },
      { name: 'Clarence Burton' },
      { name: 'H. N. Clugston' },
    ],
    coverUrl:
      '/movies_pictures/91016be31c90.jpg',
    releaseDate: '1924-10-13',
    length: 59,
    genre: ['Comédie', 'Aventure'],
    saga: '',
    description:
      "Deux héritiers se retrouvent seuls à bord d'un paquebot à la dérive, et apprennent à survivre ensemble.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Dernier des hommes',
    director: 'F. W. Murnau',
    actors: [
      { name: 'Emil Jannings' },
      { name: 'Maly Delschaft' },
      { name: 'Max Hiller' },
      { name: 'Emilie Kurz' },
      { name: 'Hans Unterkirchen' },
    ],
    coverUrl:
      '/movies_pictures/cbaa1821a6b6.jpg',
    releaseDate: '1924-12-23',
    length: 90,
    genre: ['Drame'],
    saga: '',
    description:
      "Un portier d'hôtel prestigieux est rétrogradé aux toilettes et voit son prestige social s'effondrer.",
    fromEntity: null,
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Nibelungen',
    director: 'Fritz Lang',
    actors: [
      { name: 'Paul Richter' },
      { name: 'Margarete Schön' },
      { name: 'Hanna Ralph' },
      { name: 'Bernhard Goetzke' },
      { name: 'Theodor Loos' },
    ],
    coverUrl:
      '/movies_pictures/d94ed2a0abe5.jpg',
    releaseDate: '1924-02-14',
    length: 293,
    genre: ['Fantastique', 'Aventure'],
    saga: '',
    description:
      'Siegfried conquiert le trésor des Nibelungen avant que la vengeance de Kriemhild ne ravine le royaume burgonde.',
    fromEntity: {
      entityType: 'book',
      title: 'La Chanson des Nibelungen',
      secondEntityKey: 'Anonyme',
    },
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Rapaces',
    director: 'Erich von Stroheim',
    actors: [
      { name: 'Gibson Gowland' },
      { name: 'Zasu Pitts' },
      { name: 'Jean Hersholt' },
      { name: 'Dale Fuller' },
      { name: 'Tempe Pigott' },
    ],
    coverUrl:
      '/movies_pictures/0e2a286cab09.jpg',
    releaseDate: '1924-12-04',
    length: 140,
    genre: ['Drame'],
    saga: '',
    description:
      "Un dentiste de San Francisco, sa femme et un ami sombrent dans l'avidité après un gain à la loterie.",
    fromEntity: {
      entityType: 'book',
      title: 'McTeague',
      secondEntityKey: 'Frank Norris',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Sherlock Junior',
    director: 'Buster Keaton',
    actors: [
      { name: 'Buster Keaton' },
      { name: 'Kathryn McGuire' },
      { name: 'Joe Keaton' },
      { name: 'Erwin Connelly' },
      { name: 'Ward Crane' },
    ],
    coverUrl:
      '/movies_pictures/7323a634a044.jpg',
    releaseDate: '1924-04-21',
    length: 45,
    genre: ['Comédie'],
    saga: '',
    description:
      "Un projectionniste rêve qu'il entre dans l'écran pour résoudre un crime et reconquérir sa bien-aimée.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Grève',
    director: 'Sergueï Eisenstein',
    actors: [
      { name: 'Maksim Shtraukh' },
      { name: 'Grigori Aleksandrov' },
      { name: 'Mikhail Gomorov' },
      { name: 'I. Ivanov' },
      { name: 'Ivan Klyukvin' },
    ],
    coverUrl:
      '/movies_pictures/0aa946be15ae.png',
    releaseDate: '1925-04-28',
    length: 82,
    genre: ['Drame', 'Historique'],
    saga: '',
    description:
      "Les ouvriers d'une usine se mettent en grève ; la répression tsariste répond par le massacre.",
    fromEntity: null,
    countryOrigin: ['Russie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Cuirassé Potemkine',
    director: 'Sergueï Eisenstein',
    actors: [
      { name: 'Aleksandr Antonov' },
      { name: 'Vladimir Barsky' },
      { name: 'Grigori Aleksandrov' },
      { name: 'Ivan Bobrov' },
      { name: 'Mikhail Gomorov' },
    ],
    coverUrl:
      '/movies_pictures/e8ab5916eae4.jpg',
    releaseDate: '1925-12-21',
    length: 75,
    genre: ['Drame', 'Historique'],
    saga: '',
    description:
      "La mutinerie de l'équipage du Potemkine en 1905, et le massacre des civils sur les marches d'Odessa.",
    fromEntity: null,
    countryOrigin: ['Russie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Le Fantôme de l'Opéra",
    director: 'Rupert Julian',
    actors: [
      { name: 'Lon Chaney' },
      { name: 'Mary Philbin' },
      { name: 'Norman Kerry' },
      { name: 'Arthur Edmund Carewe' },
      { name: 'Gibson Gowland' },
    ],
    coverUrl:
      '/movies_pictures/f8632840212c.jpg',
    releaseDate: '1925-11-15',
    length: 93,
    genre: ['Horreur', 'Romance'],
    saga: '',
    description:
      "Un être défiguré hante l'Opéra de Paris et impose sa protégée comme cantatrice.",
    fromEntity: {
      entityType: 'book',
      title: "Le Fantôme de l'Opéra",
      secondEntityKey: 'Gaston Leroux',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Faust',
    director: 'F. W. Murnau',
    actors: [
      { name: 'Gösta Ekman' },
      { name: 'Emil Jannings' },
      { name: 'Camilla Horn' },
      { name: 'Frida Richard' },
      { name: 'William Dieterle' },
    ],
    coverUrl:
      '/movies_pictures/9fc3da645a10.jpg',
    releaseDate: '1926-10-14',
    length: 107,
    genre: ['Fantastique', 'Drame'],
    saga: '',
    description:
      "Méphisto parie avec un ange qu'il peut corrompre l'âme du savant Faust.",
    fromEntity: {
      entityType: 'book',
      title: 'Faust',
      secondEntityKey: 'Johann Wolfgang von Goethe',
    },
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Mère',
    director: 'Vsevolod Poudovkine',
    actors: [
      { name: 'Vera Baranovskaya' },
      { name: 'Nikolai Batalov' },
      { name: 'Aleksandr Chistyakov' },
      { name: 'Anna Zemtsova' },
      { name: 'Ivan Koval-Samborsky' },
    ],
    coverUrl:
      '/movies_pictures/b65022abe8a0.jpg',
    releaseDate: '1926-10-11',
    length: 89,
    genre: ['Drame'],
    saga: '',
    description:
      "Une mère ouvrière, d'abord soumise, rejoint la lutte révolutionnaire de son fils.",
    fromEntity: {
      entityType: 'book',
      title: 'La Mère',
      secondEntityKey: 'Maxime Gorki',
    },
    countryOrigin: ['Russie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Mécano de la General',
    director: 'Buster Keaton, Clyde Bruckman',
    actors: [
      { name: 'Buster Keaton' },
      { name: 'Marion Mack' },
      { name: 'Glen Cavender' },
      { name: 'Jim Farley' },
      { name: 'Frederick Vroom' },
    ],
    coverUrl:
      '/movies_pictures/5e0a8e2d13f1.jpg',
    releaseDate: '1926-12-31',
    length: 78,
    genre: ['Comédie', 'Aventure', 'Guerre'],
    saga: '',
    description:
      "Pendant la guerre de Sécession, un mécanicien poursuit l'armée nordiste qui a volé sa locomotive et sa fiancée.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Aurore",
    director: 'F. W. Murnau',
    actors: [
      { name: "George O'Brien" },
      { name: 'Janet Gaynor' },
      { name: 'Margaret Livingston' },
      { name: 'Bodil Rosing' },
      { name: 'J. Farrell MacDonald' },
    ],
    coverUrl:
      '/movies_pictures/098d3a642698.jpg',
    releaseDate: '1927-11-13',
    length: 94,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      "Un paysan, séduit par une citadine, envisage de tuer sa femme avant de se racheter au cours d'une journée en ville.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_CINEMATOGRAPHY, year: 1929 }],
  },
  {
    title: 'Le Chanteur de jazz',
    director: 'Alan Crosland',
    actors: [
      { name: 'Al Jolson' },
      { name: 'May McAvoy' },
      { name: 'Warner Oland' },
      { name: 'Eugenie Besserer' },
      { name: 'Otto Lederer' },
    ],
    coverUrl:
      '/movies_pictures/cc280646b1ea.jpg',
    releaseDate: '1927-10-06',
    length: 88,
    genre: ['Comédie musicale', 'Drame'],
    saga: '',
    description:
      "Fils d'un chantre, Jakie Rabinowitz brise avec sa tradition pour devenir star du jazz à Broadway.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Ailes',
    director: 'William A. Wellman',
    actors: [
      { name: 'Clara Bow' },
      { name: 'Charles Rogers' },
      { name: 'Richard Arlen' },
      { name: 'Gary Cooper' },
      { name: 'Jobyna Ralston' },
    ],
    coverUrl:
      '/movies_pictures/b74300663d7f.jpg',
    releaseDate: '1927-08-12',
    length: 144,
    genre: ['Guerre', 'Romance', 'Drame'],
    saga: '',
    description:
      "Deux amis d'enfance deviennent pilotes durant la Première Guerre mondiale et aiment la même femme.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_MOVIE, year: 1929 },
      { type: OscarEnum.OSCAR_BEST_VISUAL_EFFECTS, year: 1929 },
    ],
  },
  {
    title: 'Metropolis',
    director: 'Fritz Lang',
    actors: [
      { name: 'Brigitte Helm' },
      { name: 'Gustav Fröhlich' },
      { name: 'Rudolf Klein-Rogge' },
      { name: 'Alfred Abel' },
      { name: 'Heinrich George' },
    ],
    coverUrl:
      '/movies_pictures/7a2885c5e586.jpg',
    releaseDate: '1927-01-10',
    length: 153,
    genre: ['Science Fiction', 'Dystopie'],
    saga: '',
    description:
      "Dans une ville futuriste coupée en deux, le fils du maître découvre l'enfer des ouvriers et un robot à l'image de Maria.",
    fromEntity: null,
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Napoléon',
    director: 'Abel Gance',
    actors: [
      { name: 'Albert Dieudonné' },
      { name: 'Vladimir Roudenko' },
      { name: 'Gina Manès' },
      { name: 'Nicolas Koline' },
      { name: 'Annabella' },
    ],
    coverUrl:
      '/movies_pictures/e012c50c7800.jpg',
    releaseDate: '1927-04-07',
    length: 333,
    genre: ['Historique', 'Drame', 'Guerre', 'Biographie'],
    saga: '',
    description:
      "De Brienne à la campagne d'Italie, l'ascension de Bonaparte filmée en polyvision et en montage lyrique.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Cadet d'eau douce",
    director: 'Charles Reisner',
    actors: [
      { name: 'Buster Keaton' },
      { name: 'Tom McGuire' },
      { name: 'Ernest Torrence' },
      { name: 'Marion Byron' },
      { name: 'Tom Lewis' },
    ],
    coverUrl:
      '/movies_pictures/1f424063e322.jpg',
    releaseDate: '1928-05-20',
    length: 70,
    genre: ['Comédie'],
    saga: '',
    description:
      "Le fils d'un capitaine fluvial doit prouver sa virilité quand un cyclone s'abat sur le port.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Foule',
    director: 'King Vidor',
    actors: [
      { name: 'Eleanor Boardman' },
      { name: 'James Murray' },
      { name: 'Bert Roach' },
      { name: 'Estelle Clark' },
      { name: 'Daniel G. Tomlinson' },
    ],
    coverUrl:
      '/movies_pictures/7406c0f212a5.jpg',
    releaseDate: '1928-03-03',
    length: 98,
    genre: ['Drame'],
    saga: '',
    description:
      "Un couple ordinaire de New York voit ses rêves de réussite se briser dans l'anonymat de la grande ville.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "La Passion de Jeanne d'Arc",
    director: 'Carl Theodor Dreyer',
    actors: [
      { name: 'Renée Falconetti' },
      { name: 'Eugène Silvain' },
      { name: 'André Berley' },
      { name: 'Maurice Schutz' },
      { name: 'Antonin Artaud' },
    ],
    coverUrl:
      '/movies_pictures/b1e42f6ad7dd.png',
    releaseDate: '1928-04-21',
    length: 110,
    genre: ['Drame', 'Historique', 'Biographie'],
    saga: '',
    description:
      "Le procès et le bûcher de Jeanne d'Arc, filmés en plans serrés sur les visages.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Cameraman',
    director: 'Edward Sedgwick, Buster Keaton',
    actors: [
      { name: 'Buster Keaton' },
      { name: 'Marceline Day' },
      { name: 'Harold Goodwin' },
      { name: 'Sidney Bracey' },
      { name: 'Harry Gribbon' },
    ],
    coverUrl:
      '/movies_pictures/d42485b5e7a0.jpg',
    releaseDate: '1928-09-22',
    length: 67,
    genre: ['Comédie'],
    saga: '',
    description:
      "Un photographe de rue s'improvise caméraman d'actualités pour séduire une secrétaire de la MGM.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Octobre',
    director: 'Sergueï Eisenstein, Grigori Aleksandrov',
    actors: [
      { name: 'Vladimir Popov' },
      { name: 'Vasili Nikandrov' },
      { name: 'Layaschenko' },
      { name: 'Nikolai Podvoisky' },
      { name: 'Boris Livanov' },
    ],
    coverUrl:
      '/movies_pictures/9e8f0ad9cc7d.jpg',
    releaseDate: '1928-03-14',
    length: 104,
    genre: ['Drame', 'Historique'],
    saga: '',
    description:
      "Reconstitution du soulèvement d'octobre 1917 à Petrograd, de la chute de Kerenski à la prise du Palais d'Hiver.",
    fromEntity: null,
    countryOrigin: ['Russie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Homme à la caméra",
    director: 'Dziga Vertov',
    actors: [{ name: 'Mikhail Kaufman' }, { name: 'Elizaveta Svilova' }],
    coverUrl:
      '/movies_pictures/d0aad8a9aef4.jpg',
    releaseDate: '1929-01-08',
    length: 68,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Une journée dans une ville soviétique, filmée comme un manifeste du cinéma-œil, sans intertitres ni fiction.',
    fromEntity: null,
    countryOrigin: ['Russie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Loulou',
    director: 'Georg Wilhelm Pabst',
    actors: [
      { name: 'Louise Brooks' },
      { name: 'Fritz Kortner' },
      { name: 'Francis Lederer' },
      { name: 'Carl Goetz' },
      { name: 'Krafft-Raschig' },
    ],
    coverUrl:
      '/movies_pictures/811487f5616c.jpg',
    releaseDate: '1929-01-30',
    length: 133,
    genre: ['Drame'],
    saga: '',
    description:
      "Lulu, danseuse et courtisane, détruit les hommes qui l'aiment avant de sombrer à Londres.",
    fromEntity: null,
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Un chien andalou',
    director: 'Luis Buñuel',
    actors: [
      { name: 'Pierre Batcheff' },
      { name: 'Simone Mareuil' },
      { name: 'Luis Buñuel' },
      { name: 'Salvador Dalí' },
      { name: 'Jaime Miravilles' },
    ],
    coverUrl:
      '/movies_pictures/f97b84f64a4b.jpeg',
    releaseDate: '1929-06-06',
    length: 16,
    genre: ['Fantastique'],
    saga: '',
    description:
      "Court métrage surréaliste : un œil tranché, un piano chargé d'ânes, des amants qui ne se rejoignent jamais.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "À l'Ouest rien de nouveau",
    director: 'Lewis Milestone',
    actors: [
      { name: 'Lew Ayres' },
      { name: 'Louis Wolheim' },
      { name: 'John Wray' },
      { name: 'Arnold Lucy' },
      { name: 'Ben Alexander' },
    ],
    coverUrl:
      '/movies_pictures/075921197dea.jpg',
    releaseDate: '1930-04-21',
    length: 136,
    genre: ['Guerre', 'Drame'],
    saga: '',
    description:
      "Des lycéens allemands s'engagent en 1914 et découvrent l'horreur des tranchées.",
    fromEntity: {
      entityType: 'book',
      title: "À l'Ouest rien de nouveau",
      secondEntityKey: 'Erich Maria Remarque',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_MOVIE, year: 1930 },
      { type: OscarEnum.OSCAR_BEST_DIRECTOR, year: 1930 },
    ],
  },
  {
    title: 'Cœurs brûlés',
    director: 'Josef von Sternberg',
    actors: [
      { name: 'Marlene Dietrich' },
      { name: 'Gary Cooper' },
      { name: 'Adolphe Menjou' },
      { name: 'Ullrich Haupt' },
      { name: 'Eve Southern' },
    ],
    coverUrl: '/movies_pictures/4d7e6374be1f.jpg',
    releaseDate: '1930-11-14',
    length: 91,
    genre: ['Romance', 'Drame'],
    saga: '',
    description:
      'À Mogador, une chanteuse de cabaret joue avec un légionnaire et un riche mondain.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Âge d'or",
    director: 'Luis Buñuel',
    actors: [
      { name: 'Gaston Modot' },
      { name: 'Lya Lys' },
      { name: 'Caridad de Laberdesque' },
      { name: 'Max Ernst' },
      { name: 'Josep Llorens Artigas' },
    ],
    coverUrl:
      '/movies_pictures/91feb106cc50.jpg',
    releaseDate: '1930-11-28',
    length: 63,
    genre: ['Drame'],
    saga: '',
    description:
      "Deux amants sont sans cesse empêchés de s'unir, dans un pamphlet surréaliste contre l'Église et la bourgeoisie.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Ange bleu",
    director: 'Josef von Sternberg',
    actors: [
      { name: 'Marlene Dietrich' },
      { name: 'Emil Jannings' },
      { name: 'Kurt Gerron' },
      { name: 'Rosa Valetti' },
      { name: 'Hans Albers' },
    ],
    coverUrl:
      '/movies_pictures/7c2814b88374.jpg',
    releaseDate: '1930-04-01',
    length: 108,
    genre: ['Drame'],
    saga: '',
    description:
      "Un professeur respectable s'abîme d'amour pour Lola-Lola, chanteuse du cabaret L'Ange bleu.",
    fromEntity: {
      entityType: 'book',
      title: 'Professeur Unrat',
      secondEntityKey: 'Heinrich Mann',
    },
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Terre',
    director: 'Alexandre Dovjenko',
    actors: [
      { name: 'Stepan Shkurat' },
      { name: 'Semyon Svashenko' },
      { name: 'Yuliya Solntseva' },
      { name: 'Elena Maksimova' },
      { name: 'Nikolai Nademsky' },
    ],
    coverUrl: '/movies_pictures/d7d097209d5b.jpg',
    releaseDate: '1930-04-08',
    length: 75,
    genre: ['Drame'],
    saga: '',
    description:
      "Dans un village ukrainien, la collectivisation et la mort d'un jeune paysan se mêlent au cycle des saisons.",
    fromEntity: null,
    countryOrigin: ['Ukraine'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Million',
    director: 'René Clair',
    actors: [
      { name: 'Annabella' },
      { name: 'René Lefèvre' },
      { name: 'Louis Allibert' },
      { name: 'Vanda Gréville' },
      { name: 'Paul Ollivier' },
    ],
    coverUrl:
      '/movies_pictures/f90a3062f30d.jpg',
    releaseDate: '1931-04-15',
    length: 81,
    genre: ['Comédie', 'Comédie musicale'],
    saga: '',
    description:
      "Un artiste et son rival pourchassent une veste où s'est glissé un billet de loterie gagnant.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Sous les toits de Paris',
    director: 'René Clair',
    actors: [
      { name: 'Albert Préjean' },
      { name: 'Pola Illéry' },
      { name: 'Gaston Modot' },
      { name: 'Edmond T. Gréville' },
      { name: 'Paul Ollivier' },
    ],
    coverUrl:
      '/movies_pictures/72800dfd72a4.jpg',
    releaseDate: '1930-01-02',
    length: 96,
    genre: ['Comédie', 'Romance', 'Comédie musicale'],
    saga: '',
    description:
      "Un chanteur des rues, un voyou et une jeune Roumaine s'entrelacent dans le Paris populaire du parlant naissant.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'À nous la liberté',
    director: 'René Clair',
    actors: [
      { name: 'Henri Marchand' },
      { name: 'Raymond Cordy' },
      { name: 'Rolla France' },
      { name: 'Paul Ollivier' },
      { name: 'Jacques Shelly' },
    ],
    coverUrl:
      '/movies_pictures/615bdbb79140.jpg',
    releaseDate: '1931-12-18',
    length: 104,
    genre: ['Comédie'],
    saga: '',
    description:
      "Deux amis s'évadent du bagne : l'un devient un industriel, l'autre refuse la société-usine.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Cimarron',
    director: 'Wesley Ruggles',
    actors: [
      { name: 'Richard Dix' },
      { name: 'Irene Dunne' },
      { name: 'Estelle Taylor' },
      { name: "Nance O'Neil" },
      { name: 'William Collier Jr.' },
    ],
    coverUrl:
      '/movies_pictures/f7d443d36172.jpg',
    releaseDate: '1931-01-26',
    length: 123,
    genre: ['Western', 'Drame'],
    saga: '',
    description:
      "Un pionnier et sa femme suivent la ruée vers l'Oklahoma, de la terre promise aux compromis de la civilisation.",
    fromEntity: {
      entityType: 'book',
      title: 'Cimarron',
      secondEntityKey: 'Edna Ferber',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_MOVIE, year: 1931 },
      { type: OscarEnum.OSCAR_BEST_ADAPTED_SCREENPLAY, year: 1931 },
      { type: OscarEnum.OSCAR_BEST_PRODUCTION_DESIGN, year: 1931 },
    ],
  },
  {
    title: 'Docteur Jekyll et M. Hyde',
    director: 'Rouben Mamoulian',
    actors: [
      { name: 'Fredric March' },
      { name: 'Miriam Hopkins' },
      { name: 'Rose Hobart' },
      { name: 'Holmes Herbert' },
      { name: 'Halliwell Hobbes' },
    ],
    coverUrl:
      '/movies_pictures/2713bab4e976.jpg',
    releaseDate: '1931-12-31',
    length: 98,
    genre: ['Horreur', 'Science Fiction'],
    saga: '',
    description:
      "Un savant londonien libère son double maléfique par un sérum, jusqu'à ne plus pouvoir revenir.",
    fromEntity: {
      entityType: 'book',
      title: "L'Étrange Cas du docteur Jekyll et de M. Hyde",
      secondEntityKey: 'Robert Louis Stevenson',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_ACTOR, year: 1932 }],
  },
  {
    title: 'Dracula',
    director: 'Tod Browning',
    actors: [
      { name: 'Bela Lugosi' },
      { name: 'Helen Chandler' },
      { name: 'David Manners' },
      { name: 'Dwight Frye' },
      { name: 'Edward Van Sloan' },
    ],
    coverUrl:
      '/movies_pictures/0d8dff03975f.jpg',
    releaseDate: '1931-02-12',
    length: 75,
    genre: ['Horreur'],
    saga: 'Universal Monsters',
    description:
      "Le comte Dracula quitte la Transylvanie pour l'Angleterre et sème la terreur dans le manoir Seward.",
    fromEntity: {
      entityType: 'book',
      title: 'Dracula',
      secondEntityKey: 'Bram Stoker',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Frankenstein',
    director: 'James Whale',
    actors: [
      { name: 'Colin Clive' },
      { name: 'Mae Clarke' },
      { name: 'John Boles' },
      { name: 'Boris Karloff' },
      { name: 'Edward Van Sloan' },
    ],
    coverUrl:
      '/movies_pictures/f853a808d4cb.jpg',
    releaseDate: '1931-11-21',
    length: 71,
    genre: ['Horreur', 'Science Fiction'],
    saga: 'Frankenstein',
    description:
      'Le docteur Frankenstein donne vie à une créature assemblée, bientôt rejetée et meurtrière.',
    fromEntity: {
      entityType: 'book',
      title: 'Frankenstein',
      secondEntityKey: 'Mary Shelley',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Ennemi public",
    director: 'William A. Wellman',
    actors: [
      { name: 'James Cagney' },
      { name: 'Jean Harlow' },
      { name: 'Edward Woods' },
      { name: 'Joan Blondell' },
      { name: 'Donald Cook' },
    ],
    coverUrl:
      '/movies_pictures/65643f3ff6fd.jpg',
    releaseDate: '1931-04-23',
    length: 83,
    genre: ['Policier', 'Drame'],
    saga: '',
    description:
      "Deux amis d'enfance deviennent gangsters à Chicago, entre hold-up, pamplemousse et fusillades.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Opéra de quat'sous",
    director: 'Georg Wilhelm Pabst',
    actors: [
      { name: 'Rudolf Forster' },
      { name: 'Carola Neher' },
      { name: 'Reinhold Schünzel' },
      { name: 'Fritz Rasp' },
      { name: 'Lotte Lenya' },
    ],
    coverUrl:
      '/movies_pictures/a4e86ffb1c46.jpg',
    releaseDate: '1931-02-19',
    length: 112,
    genre: ['Drame', 'Comédie musicale'],
    saga: '',
    description:
      "Mackie Messer règne sur les bas-fonds de Londres, jusqu'à ce que Polly Peachum bouleverse l'équilibre du crime.",
    fromEntity: null,
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Chienne',
    director: 'Jean Renoir',
    actors: [
      { name: 'Michel Simon' },
      { name: 'Janie Marèse' },
      { name: 'Georges Flamant' },
      { name: 'Magdeleine Bérubet' },
      { name: 'Roger Gaillard' },
    ],
    coverUrl: '/movies_pictures/2163350f670c.jpg',
    releaseDate: '1931-11-19',
    length: 91,
    genre: ['Drame'],
    saga: '',
    description:
      "Un caissier amateur de peinture s'éprend d'une prostituée qui le dépouille, jusqu'au meurtre.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Petit César',
    director: 'Mervyn LeRoy',
    actors: [
      { name: 'Edward G. Robinson' },
      { name: 'Douglas Fairbanks Jr.' },
      { name: 'Glenda Farrell' },
      { name: 'William Collier Jr.' },
      { name: 'Sidney Blackmer' },
    ],
    coverUrl:
      '/movies_pictures/9774c5223302.jpg',
    releaseDate: '1931-01-25',
    length: 79,
    genre: ['Policier', 'Drame'],
    saga: '',
    description:
      "Rico Bandello gravit les échelons du crime organisé jusqu'à la chute, en demandant si c'est la fin de Rico.",
    fromEntity: {
      entityType: 'book',
      title: 'Little Caesar',
      secondEntityKey: 'W. R. Burnett',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Marius',
    director: 'Alexander Korda',
    actors: [
      { name: 'Pierre Fresnay' },
      { name: 'Orane Demazis' },
      { name: 'Raimu' },
      { name: 'Fernand Charpin' },
      { name: 'Alida Rouffe' },
    ],
    coverUrl:
      '/movies_pictures/093a55236232.jpg',
    releaseDate: '1931-10-09',
    length: 130,
    genre: ['Comédie', 'Drame', 'Romance'],
    saga: 'Marius, Fanny, César',
    description:
      'Sur le Vieux-Port, Marius aime Fanny mais rêve de partir en mer ; César, son père, tient le bar.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Tabou',
    director: 'F. W. Murnau',
    actors: [
      { name: 'Matahi' },
      { name: 'Reri' },
      { name: 'Hitu' },
      { name: 'Jean' },
      { name: 'Jules' },
    ],
    coverUrl:
      '/movies_pictures/59998215637c.jpg',
    releaseDate: '1931-08-01',
    length: 86,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      'À Bora-Bora, deux amants fuient un interdit sacré qui condamne la jeune femme à devenir vestale.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Boudu sauvé des eaux',
    director: 'Jean Renoir',
    actors: [
      { name: 'Michel Simon' },
      { name: 'Charles Granval' },
      { name: 'Marcelle Hainia' },
      { name: 'Sévérine Lerczinska' },
      { name: 'Jean Gehret' },
    ],
    coverUrl:
      'https://img.festival-cannes.com/eyJidWNrZXQiOiJtZWRpYSIsImtleSI6InVwbG9hZHNcLzIwMjNcLzAzXC85MTMxOS5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjE2MDAsImZpdCI6ImNvdmVyIn19fQ==',
    releaseDate: '1932-11-11',
    length: 85,
    genre: ['Comédie'],
    saga: '',
    description:
      "Un libraire sauve un clochard de la noyade et l'invite chez lui : Boudu sème le désordre bourgeois.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Fanny',
    director: 'Marc Allégret',
    actors: [
      { name: 'Orane Demazis' },
      { name: 'Raimu' },
      { name: 'Pierre Fresnay' },
      { name: 'Fernand Charpin' },
      { name: 'Alida Rouffe' },
    ],
    coverUrl: '/movies_pictures/e962f35a618e.jpg',
    releaseDate: '1932-10-28',
    length: 127,
    genre: ['Comédie', 'Drame', 'Romance'],
    saga: 'Marius, Fanny, César',
    description:
      "Fanny, enceinte de Marius parti sur les mers, accepte d'épouser le vieux Panisse.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Grand Hôtel',
    director: 'Edmund Goulding',
    actors: [
      { name: 'Greta Garbo' },
      { name: 'John Barrymore' },
      { name: 'Joan Crawford' },
      { name: 'Wallace Beery' },
      { name: 'Lionel Barrymore' },
    ],
    coverUrl:
      'https://upload.wikimedia.org/wikipedia/commons/c/c8/Grand_Hotel_poster.png?utm_source=fr.wikipedia.org&utm_campaign=index&utm_content=original',
    releaseDate: '1932-04-12',
    length: 112,
    genre: ['Drame'],
    saga: '',
    description:
      'Destins croisés dans un palace berlinois : danseuse, secrétaire, baron voleur, industriel et mourant.',
    fromEntity: {
      entityType: 'book',
      title: 'Menschen im Hotel',
      secondEntityKey: 'Vicki Baum',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_MOVIE, year: 1932 }],
  },
  {
    title: 'Haute Pègre',
    director: 'Ernst Lubitsch',
    actors: [
      { name: 'Herbert Marshall' },
      { name: 'Miriam Hopkins' },
      { name: 'Kay Francis' },
      { name: 'Edward Everett Horton' },
      { name: 'Charles Ruggles' },
    ],
    coverUrl:
      '/movies_pictures/e5aa3ff593b9.jpg',
    releaseDate: '1932-10-30',
    length: 83,
    genre: ['Comédie', 'Romance'],
    saga: '',
    description:
      "Deux voleurs élégants se rencontrent à Venise et visent une héritière, au risque de s'aimer pour de vrai.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Je suis un évadé',
    director: 'Mervyn LeRoy',
    actors: [
      { name: 'Paul Muni' },
      { name: 'Glenda Farrell' },
      { name: 'Helen Vinson' },
      { name: 'Noel Francis' },
      { name: 'Preston Foster' },
    ],
    coverUrl:
      '/movies_pictures/fbdb1d505ab0.jpg',
    releaseDate: '1932-11-10',
    length: 92,
    genre: ['Drame'],
    saga: '',
    description:
      "Un vétéran, condamné à tort, s'évade du bagne géorgien et devient un fugitif malgré sa réhabilitation.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Momie',
    director: 'Karl Freund',
    actors: [
      { name: 'Boris Karloff' },
      { name: 'Zita Johann' },
      { name: 'David Manners' },
      { name: 'Arthur Byron' },
      { name: 'Edward Van Sloan' },
    ],
    coverUrl:
      '/movies_pictures/e702704ca02d.jpeg',
    releaseDate: '1932-12-22',
    length: 73,
    genre: ['Horreur', 'Fantastique'],
    saga: 'La Momie',
    description:
      "Imhotep, prêtre momifié, ressuscite en Égypte et cherche à retrouver l'âme de sa bien-aimée.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Monstrueuse Parade',
    director: 'Tod Browning',
    actors: [
      { name: 'Wallace Ford' },
      { name: 'Leila Hyams' },
      { name: 'Olga Baclanova' },
      { name: 'Rosco Ates' },
      { name: 'Henry Victor' },
    ],
    coverUrl:
      '/movies_pictures/4c52eef02076.jpg',
    releaseDate: '1932-02-12',
    length: 64,
    genre: ['Horreur', 'Drame'],
    saga: '',
    description:
      'Une trapéziste épouse un nain pour sa fortune et découvre que la troupe des phénomènes se venge.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Testament du docteur Mabuse',
    director: 'Fritz Lang',
    actors: [
      { name: 'Rudolf Klein-Rogge' },
      { name: 'Otto Wernicke' },
      { name: 'Gustav Diessl' },
      { name: 'Oscar Beregi Sr.' },
      { name: 'Vera Liessem' },
    ],
    coverUrl:
      '/movies_pictures/23eafa81af59.jpg',
    releaseDate: '1933-04-21',
    length: 122,
    genre: ['Thriller', 'Policier'],
    saga: 'Docteur Mabuse',
    description:
      "Interné, Mabuse dicte encore un empire du crime ; l'inspecteur Lohmann tente de briser le réseau.",
    fromEntity: null,
    countryOrigin: ['Allemagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Scarface',
    director: 'Howard Hawks',
    actors: [
      { name: 'Paul Muni' },
      { name: 'Ann Dvorak' },
      { name: 'Karen Morley' },
      { name: 'Osgood Perkins' },
      { name: 'George Raft' },
    ],
    coverUrl:
      'https://upload.wikimedia.org/wikipedia/commons/e/e0/Scarface_%281932_film_poster%29.jpg?utm_source=fr.wikipedia.org&utm_campaign=index&utm_content=original',
    releaseDate: '1932-04-09',
    length: 93,
    genre: ['Policier', 'Drame'],
    saga: '',
    description:
      'Tony Camonte gravit le milieu de Chicago à coups de mitraillette, obsédé par sa sœur Cesca.',
    fromEntity: {
      entityType: 'book',
      title: 'Scarface',
      secondEntityKey: 'Armitage Trail',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Shanghai Express',
    director: 'Josef von Sternberg',
    actors: [
      { name: 'Marlene Dietrich' },
      { name: 'Clive Brook' },
      { name: 'Anna May Wong' },
      { name: 'Warner Oland' },
      { name: 'Eugene Pallette' },
    ],
    coverUrl:
      '/movies_pictures/f9915308bba9.jpg',
    releaseDate: '1932-02-12',
    length: 82,
    genre: ['Aventure', 'Drame', 'Romance'],
    saga: '',
    description:
      'À bord du train Pékin-Shanghai, une courtisane croise un ancien amant et un chef de guerre.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_CINEMATOGRAPHY, year: 1932 }],
  },
  {
    title: 'Vampyr',
    director: 'Carl Theodor Dreyer',
    actors: [
      { name: 'Nicolas de Gunzburg' },
      { name: 'Maurice Schutz' },
      { name: 'Rena Mandel' },
      { name: 'Sybille Schmitz' },
      { name: 'Jan Hieronimko' },
    ],
    coverUrl: '/movies_pictures/b5022ed760c6.jpg',
    releaseDate: '1932-05-06',
    length: 75,
    genre: ['Horreur', 'Fantastique'],
    saga: '',
    description:
      "Un voyageur s'arrête dans un village où les vivants et les morts se confondent, sous l'emprise d'une vampire.",
    fromEntity: null,
    countryOrigin: ['Allemagne', 'France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: '42e Rue',
    director: 'Lloyd Bacon',
    actors: [
      { name: 'Warner Baxter' },
      { name: 'Bebe Daniels' },
      { name: 'George Brent' },
      { name: 'Ruby Keeler' },
      { name: 'Ginger Rogers' },
    ],
    coverUrl:
      '/movies_pictures/49dc32f26d56.jpg',
    releaseDate: '1933-03-09',
    length: 89,
    genre: ['Comédie musicale'],
    saga: '',
    description:
      'Un metteur en scène usé monte un spectacle de Broadway ; la choriste Peg sauve la première.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'King Kong',
    director: 'Merian C. Cooper, Ernest B. Schoedsack',
    actors: [
      { name: 'Fay Wray' },
      { name: 'Robert Armstrong' },
      { name: 'Bruce Cabot' },
      { name: 'Frank Reicher' },
      { name: 'Sam Hardy' },
    ],
    coverUrl:
      'https://upload.wikimedia.org/wikipedia/commons/e/e1/King_Kong_1933_French_poster.jpg?utm_source=fr.wikipedia.org&utm_campaign=index&utm_content=original',
    releaseDate: '1933-03-02',
    length: 100,
    genre: ['Aventure', 'Fantastique'],
    saga: 'King Kong',
    description:
      "Une expédition ramène de l'île du Crâne un gorille géant qui sème la panique à New York.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Homme invisible",
    director: 'James Whale',
    actors: [
      { name: 'Claude Rains' },
      { name: 'Gloria Stuart' },
      { name: 'William Harrigan' },
      { name: 'Henry Travers' },
      { name: "Una O'Connor" },
    ],
    coverUrl:
      '/movies_pictures/ecceef2b17e2.jpg',
    releaseDate: '1933-11-13',
    length: 71,
    genre: ['Horreur', 'Science Fiction'],
    saga: 'Universal Monsters',
    description:
      "Un savant devenu invisible s'enfonce dans la folie et terrorise un village anglais.",
    fromEntity: {
      entityType: 'book',
      title: "L'Homme invisible",
      secondEntityKey: 'H. G. Wells',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Reine Christine',
    director: 'Rouben Mamoulian',
    actors: [
      { name: 'Greta Garbo' },
      { name: 'John Gilbert' },
      { name: 'Ian Keith' },
      { name: 'Lewis Stone' },
      { name: 'Elizabeth Young' },
    ],
    coverUrl:
      '/movies_pictures/669b64d48725.jpg',
    releaseDate: '1933-12-26',
    length: 99,
    genre: ['Drame', 'Romance', 'Historique', 'Biographie'],
    saga: '',
    description:
      'Christine de Suède abdique par amour pour un envoyé espagnol, au scandale de sa cour.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Soupe au canard',
    director: 'Leo McCarey',
    actors: [
      { name: 'Groucho Marx' },
      { name: 'Harpo Marx' },
      { name: 'Chico Marx' },
      { name: 'Zeppo Marx' },
      { name: 'Margaret Dumont' },
    ],
    coverUrl: '',
    releaseDate: '1933-11-17',
    length: 68,
    genre: ['Comédie'],
    saga: '',
    description:
      'Le président Firefly plonge la nation de Freedonia dans une guerre absurde, entre cacahuètes et miroirs.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Compagnons de la nouba',
    director: 'William A. Seiter',
    actors: [
      { name: 'Stan Laurel' },
      { name: 'Oliver Hardy' },
      { name: 'Charley Chase' },
      { name: 'Mae Busch' },
      { name: 'Dorothy Christy' },
    ],
    coverUrl: '',
    releaseDate: '1933-12-29',
    length: 68,
    genre: ['Comédie'],
    saga: '',
    description:
      "Laurel et Hardy jurent fidélité à leur loge, au grand dam de leurs épouses, lors d'un congrès à Chicago.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Quatre Filles du docteur March',
    director: 'George Cukor',
    actors: [
      { name: 'Katharine Hepburn' },
      { name: 'Joan Bennett' },
      { name: 'Paul Lukas' },
      { name: 'Frances Dee' },
      { name: 'Jean Parker' },
    ],
    coverUrl: '',
    releaseDate: '1933-11-16',
    length: 115,
    genre: ['Drame'],
    saga: '',
    description:
      'Quatre sœurs grandissent dans le Massachusetts de la guerre de Sécession, entre vocation, amour et deuil.',
    fromEntity: {
      entityType: 'book',
      title: 'Les Quatre Filles du docteur March',
      secondEntityKey: 'Louisa May Alcott',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Zéro de conduite',
    director: 'Jean Vigo',
    actors: [
      { name: 'Jean Dasté' },
      { name: 'Robert Le Flon' },
      { name: 'Louis Lefebvre' },
      { name: 'Gilbert Pruchon' },
      { name: 'Gérard de Bédarieux' },
    ],
    coverUrl: '',
    releaseDate: '1933-04-07',
    length: 44,
    genre: ['Comédie', 'Drame'],
    saga: '',
    description:
      "Dans un internat, des collégiens se révoltent contre l'autorité, jusqu'à un chahut sur les toits.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Atalante",
    director: 'Jean Vigo',
    actors: [
      { name: 'Dita Parlo' },
      { name: 'Jean Dasté' },
      { name: 'Michel Simon' },
      { name: 'Gilles Margaritis' },
      { name: 'Louis Lefebvre' },
    ],
    coverUrl: '',
    releaseDate: '1934-09-12',
    length: 89,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      "Une jeune mariée s'ennuie sur une péniche, part à Paris, et le père Jules aide le couple à se retrouver.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Impératrice rouge",
    director: 'Josef von Sternberg',
    actors: [
      { name: 'Marlene Dietrich' },
      { name: 'John Lodge' },
      { name: 'Sam Jaffe' },
      { name: 'Louise Dresser' },
      { name: 'C. Aubrey Smith' },
    ],
    coverUrl: '',
    releaseDate: '1934-09-15',
    length: 124,
    genre: ['Drame', 'Historique', 'Biographie'],
    saga: '',
    description:
      "Sophie d'Anhalt devient Catherine de Russie, entre mariage glacial et conquête du trône.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'New York-Miami',
    director: 'Frank Capra',
    actors: [
      { name: 'Clark Gable' },
      { name: 'Claudette Colbert' },
      { name: 'Walter Connolly' },
      { name: 'Roscoe Karns' },
      { name: 'Jameson Thomas' },
    ],
    coverUrl: '',
    releaseDate: '1934-02-22',
    length: 105,
    genre: ['Comédie', 'Romance'],
    saga: '',
    description:
      "Une héritière en fuite et un journalier cynique traversent l'Amérique en bus, et tombent amoureux.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_MOVIE, year: 1935 },
      { type: OscarEnum.OSCAR_BEST_DIRECTOR, year: 1935 },
      { type: OscarEnum.OSCAR_BEST_ACTOR, year: 1935 },
      { type: OscarEnum.OSCAR_BEST_ACTRESS, year: 1935 },
      { type: OscarEnum.OSCAR_BEST_ADAPTED_SCREENPLAY, year: 1935 },
    ],
  },
  {
    title: 'La Fiancée de Frankenstein',
    director: 'James Whale',
    actors: [
      { name: 'Boris Karloff' },
      { name: 'Colin Clive' },
      { name: 'Valerie Hobson' },
      { name: 'Elsa Lanchester' },
      { name: 'Ernest Thesiger' },
    ],
    coverUrl: '',
    releaseDate: '1935-04-19',
    length: 75,
    genre: ['Horreur', 'Science Fiction'],
    saga: 'Frankenstein',
    description:
      'Le docteur Pretorius force Frankenstein à créer une compagne pour la créature.',
    fromEntity: {
      entityType: 'book',
      title: 'Frankenstein',
      secondEntityKey: 'Mary Shelley',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Kermesse héroïque',
    director: 'Jacques Feyder',
    actors: [
      { name: 'Françoise Rosay' },
      { name: 'André Alerme' },
      { name: 'Jean Murat' },
      { name: 'Louis Jouvet' },
      { name: 'Lyne Clevers' },
    ],
    coverUrl: '',
    releaseDate: '1935-12-03',
    length: 110,
    genre: ['Comédie', 'Historique'],
    saga: '',
    description:
      "En Flandre occupée par les Espagnols, les femmes d'une ville reçoivent l'envahisseur à leur façon.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Danseur du dessus',
    director: 'Mark Sandrich',
    actors: [
      { name: 'Fred Astaire' },
      { name: 'Ginger Rogers' },
      { name: 'Edward Everett Horton' },
      { name: 'Erik Rhodes' },
      { name: 'Eric Blore' },
    ],
    coverUrl: '',
    releaseDate: '1935-08-29',
    length: 101,
    genre: ['Comédie musicale', 'Romance'],
    saga: '',
    description:
      'Un danseur américain poursuit à Londres une mannequin qui le prend pour un gigolo.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les 39 Marches',
    director: 'Alfred Hitchcock',
    actors: [
      { name: 'Robert Donat' },
      { name: 'Madeleine Carroll' },
      { name: 'Lucie Mannheim' },
      { name: 'Godfrey Tearle' },
      { name: 'Peggy Ashcroft' },
    ],
    coverUrl: '',
    releaseDate: '1935-06-06',
    length: 86,
    genre: ['Thriller', 'Aventure'],
    saga: '',
    description:
      "Un Canadien accusé à tort d'un meurtre fuit vers l'Écosse, menotté à une blonde récalcitrante.",
    fromEntity: {
      entityType: 'book',
      title: 'Les 39 Marches',
      secondEntityKey: 'John Buchan',
    },
    countryOrigin: ['Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Révoltés du Bounty',
    director: 'Frank Lloyd',
    actors: [
      { name: 'Charles Laughton' },
      { name: 'Clark Gable' },
      { name: 'Franchot Tone' },
      { name: 'Herbert Mundin' },
      { name: 'Eddie Quillan' },
    ],
    coverUrl: '',
    releaseDate: '1935-11-08',
    length: 132,
    genre: ['Aventure', 'Drame', 'Historique'],
    saga: '',
    description:
      "À bord du Bounty, l'équipage de Fletcher Christian se soulève contre la tyrannie du capitaine Bligh.",
    fromEntity: {
      entityType: 'book',
      title: 'Les Révoltés du Bounty',
      secondEntityKey: 'Charles Nordhoff',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_MOVIE, year: 1936 }],
  },
  {
    title: "Une nuit à l'Opéra",
    director: 'Sam Wood',
    actors: [
      { name: 'Groucho Marx' },
      { name: 'Chico Marx' },
      { name: 'Harpo Marx' },
      { name: 'Kitty Carlisle' },
      { name: 'Allan Jones' },
    ],
    coverUrl: '',
    releaseDate: '1935-11-15',
    length: 96,
    genre: ['Comédie', 'Comédie musicale'],
    saga: '',
    description:
      "Les Marx Brothers chamboulent le monde de l'opéra milanais et new-yorkais pour lancer deux jeunes chanteurs.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'César',
    director: 'Marcel Pagnol',
    actors: [
      { name: 'Raimu' },
      { name: 'Pierre Fresnay' },
      { name: 'Orane Demazis' },
      { name: 'André Fouché' },
      { name: 'Fernand Charpin' },
    ],
    coverUrl: '',
    releaseDate: '1936-11-13',
    length: 141,
    genre: ['Comédie', 'Drame'],
    saga: 'Marius, Fanny, César',
    description:
      'Vingt ans après, Césariot apprend qui est son vrai père ; Marius, Fanny et César se retrouvent.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Furie',
    director: 'Fritz Lang',
    actors: [
      { name: 'Spencer Tracy' },
      { name: 'Sylvia Sidney' },
      { name: 'Walter Abel' },
      { name: 'Bruce Cabot' },
      { name: 'Edward Ellis' },
    ],
    coverUrl: '',
    releaseDate: '1936-06-05',
    length: 92,
    genre: ['Drame', 'Thriller'],
    saga: '',
    description:
      'Un homme arrêté à tort survit à un lynchage et orchestre sa vengeance contre la ville entière.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Extravagant M. Deeds",
    director: 'Frank Capra',
    actors: [
      { name: 'Gary Cooper' },
      { name: 'Jean Arthur' },
      { name: 'George Bancroft' },
      { name: 'Lionel Stander' },
      { name: 'Douglass Dumbrille' },
    ],
    coverUrl: '',
    releaseDate: '1936-04-12',
    length: 115,
    genre: ['Comédie', 'Romance'],
    saga: '',
    description:
      "Un poète de province hérite d'une fortune new-yorkaise et refuse de se laisser corrompre.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DIRECTOR, year: 1937 }],
  },
  {
    title: 'La Belle Équipe',
    director: 'Julien Duvivier',
    actors: [
      { name: 'Jean Gabin' },
      { name: 'Charles Vanel' },
      { name: 'Viviane Romance' },
      { name: 'Raymond Aimos' },
      { name: 'Raphaël Medina' },
    ],
    coverUrl: '',
    releaseDate: '1936-09-15',
    length: 101,
    genre: ['Drame'],
    saga: '',
    description:
      'Cinq chômeurs gagnent à la loterie et ouvrent une guinguette, que la jalousie et une femme vont ruiner.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Crime de monsieur Lange',
    director: 'Jean Renoir',
    actors: [
      { name: 'René Lefèvre' },
      { name: 'Florelle' },
      { name: 'Jules Berry' },
      { name: 'Marcel Lévesque' },
      { name: 'Odette Talazac' },
    ],
    coverUrl: '',
    releaseDate: '1936-01-24',
    length: 80,
    genre: ['Comédie', 'Drame'],
    saga: '',
    description:
      "Les employés d'une imprimerie fondent une coopérative après la fuite de leur patron véreux, Arizona Jim aidant.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Grand Ziegfeld',
    director: 'Robert Z. Leonard',
    actors: [
      { name: 'William Powell' },
      { name: 'Myrna Loy' },
      { name: 'Luise Rainer' },
      { name: 'Frank Morgan' },
      { name: 'Fanny Brice' },
    ],
    coverUrl: '',
    releaseDate: '1936-03-22',
    length: 185,
    genre: ['Comédie musicale', 'Biographie', 'Drame'],
    saga: '',
    description:
      'La vie de Florenz Ziegfeld, producteur des Follies, entre faste, faillites et deux mariages.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_MOVIE, year: 1937 },
      { type: OscarEnum.OSCAR_BEST_ACTRESS, year: 1937 },
    ],
  },
  {
    title: "Le Roman d'un tricheur",
    director: 'Sacha Guitry',
    actors: [
      { name: 'Sacha Guitry' },
      { name: 'Marguerite Moreno' },
      { name: 'Serge Grave' },
      { name: 'Jacqueline Delubac' },
      { name: 'Roger Dumas' },
    ],
    coverUrl: '',
    releaseDate: '1936-09-18',
    length: 81,
    genre: ['Comédie'],
    saga: '',
    description:
      "Un tricheur raconte sa vie en voix off, des champignons vénéneux aux casinos, sans presque parler à l'image.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Roman de Marguerite Gautier',
    director: 'George Cukor',
    actors: [
      { name: 'Greta Garbo' },
      { name: 'Robert Taylor' },
      { name: 'Lionel Barrymore' },
      { name: 'Elizabeth Allan' },
      { name: 'Jessie Ralph' },
    ],
    coverUrl: '',
    releaseDate: '1936-12-12',
    length: 109,
    genre: ['Romance', 'Drame'],
    saga: '',
    description:
      "La courtisane Marguerite Gautier aime un jeune bourgeois que la société et la maladie séparent d'elle.",
    fromEntity: {
      entityType: 'book',
      title: 'La Dame aux camélias',
      secondEntityKey: 'Alexandre Dumas fils',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Bas-fonds',
    director: 'Jean Renoir',
    actors: [
      { name: 'Jean Gabin' },
      { name: 'Louis Jouvet' },
      { name: 'Suzy Prim' },
      { name: 'Vladimir Sokoloff' },
      { name: 'Junie Astor' },
    ],
    coverUrl: '',
    releaseDate: '1936-12-05',
    length: 93,
    genre: ['Drame'],
    saga: '',
    description:
      'Un baron ruiné et un voleur se croisent dans un asile de miséreux, entre révolte et compassion.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Mon homme Godfrey',
    director: 'Gregory La Cava',
    actors: [
      { name: 'William Powell' },
      { name: 'Carole Lombard' },
      { name: 'Alice Brady' },
      { name: 'Gail Patrick' },
      { name: 'Eugene Pallette' },
    ],
    coverUrl: '',
    releaseDate: '1936-09-17',
    length: 94,
    genre: ['Comédie', 'Romance'],
    saga: '',
    description:
      'Une héritière caprichosa ramène un « clochard » comme majordome, sans savoir qui il est vraiment.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Swing Time',
    director: 'George Stevens',
    actors: [
      { name: 'Fred Astaire' },
      { name: 'Ginger Rogers' },
      { name: 'Victor Moore' },
      { name: 'Helen Broderick' },
      { name: 'Eric Blore' },
    ],
    coverUrl: '',
    releaseDate: '1936-08-27',
    length: 103,
    genre: ['Comédie musicale', 'Romance'],
    saga: '',
    description:
      'Un danseur qui doit gagner 25000 dollars pour se marier tombe amoureux de son professeur de claquettes.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_ORIGINAL_SONG, year: 1937 }],
  },
  {
    title: 'Une partie de campagne',
    director: 'Jean Renoir',
    actors: [
      { name: 'Sylvia Bataille' },
      { name: 'Georges Darnoux' },
      { name: 'Jacques B. Brunius' },
      { name: 'Jane Marken' },
      { name: 'Paul Temps' },
    ],
    coverUrl: '',
    releaseDate: '1946-05-08',
    length: 40,
    genre: ['Romance', 'Drame'],
    saga: '',
    description:
      "Un dimanche au bord de l'eau, une jeune fille s'abandonne à un canotier, souvenir d'un été qui ne reviendra pas.",
    fromEntity: {
      entityType: 'book',
      title: 'Une partie de campagne',
      secondEntityKey: 'Guy de Maupassant',
    },
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Capitaines courageux',
    director: 'Victor Fleming',
    actors: [
      { name: 'Spencer Tracy' },
      { name: 'Freddie Bartholomew' },
      { name: 'Lionel Barrymore' },
      { name: 'Melvyn Douglas' },
      { name: 'Charley Grapewin' },
    ],
    coverUrl: '',
    releaseDate: '1937-05-14',
    length: 117,
    genre: ['Aventure', 'Drame'],
    saga: '',
    description:
      "Un gosse de riche tombe d'un paquebot et est recueilli par des pêcheurs de Gloucester qui lui apprennent le travail.",
    fromEntity: {
      entityType: 'book',
      title: 'Capitaines courageux',
      secondEntityKey: 'Rudyard Kipling',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_ACTOR, year: 1938 }],
  },
  {
    title: 'Cette vérité trop belle',
    director: 'Leo McCarey',
    actors: [
      { name: 'Irene Dunne' },
      { name: 'Cary Grant' },
      { name: 'Ralph Bellamy' },
      { name: "Alexander D'Arcy" },
      { name: 'Cecil Cunningham' },
    ],
    coverUrl: '',
    releaseDate: '1937-10-21',
    length: 91,
    genre: ['Comédie', 'Romance'],
    saga: '',
    description:
      "Un couple en instance de divorce rivalise de ruses pour empêcher l'autre de se remarier.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DIRECTOR, year: 1938 }],
  },
  {
    title: 'Drôle de drame',
    director: 'Marcel Carné',
    actors: [
      { name: 'Michel Simon' },
      { name: 'Louis Jouvet' },
      { name: 'Françoise Rosay' },
      { name: 'Jean-Pierre Aumont' },
      { name: 'Jean-Louis Barrault' },
    ],
    coverUrl: '',
    releaseDate: '1937-10-20',
    length: 94,
    genre: ['Comédie'],
    saga: '',
    description:
      'À Londres, un botaniste auteur de romans policiers sous pseudonyme est pris pour un assassin.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Gueule d'amour",
    director: 'Jean Grémillon',
    actors: [
      { name: 'Jean Gabin' },
      { name: 'Mireille Balin' },
      { name: 'Pierre Etchepare' },
      { name: 'Henri Poupon' },
      { name: 'Gaston Modot' },
    ],
    coverUrl: '',
    releaseDate: '1937-09-17',
    length: 93,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      "Un séducteur de garnison s'éprend d'une femme inaccessible et se détruit à Orange.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Horizons perdus',
    director: 'Frank Capra',
    actors: [
      { name: 'Ronald Colman' },
      { name: 'Jane Wyatt' },
      { name: 'Edward Everett Horton' },
      { name: 'John Howard' },
      { name: 'Thomas Mitchell' },
    ],
    coverUrl: '',
    releaseDate: '1937-03-02',
    length: 132,
    genre: ['Aventure', 'Fantastique', 'Drame'],
    saga: '',
    description:
      "Des rescapés d'un crash découvrent Shangri-La, vallée himalayenne où le temps s'est arrêté.",
    fromEntity: {
      entityType: 'book',
      title: 'Lost Horizon',
      secondEntityKey: 'James Hilton',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_FILM_EDITING, year: 1938 },
      { type: OscarEnum.OSCAR_BEST_PRODUCTION_DESIGN, year: 1938 },
    ],
  },
  {
    title: "J'ai le droit de vivre",
    director: 'Fritz Lang',
    actors: [
      { name: 'Sylvia Sidney' },
      { name: 'Henry Fonda' },
      { name: 'Barton MacLane' },
      { name: 'Jean Dixon' },
      { name: 'William Gargan' },
    ],
    coverUrl: '',
    releaseDate: '1937-01-29',
    length: 86,
    genre: ['Drame', 'Thriller'],
    saga: '',
    description:
      'Un ancien détenu tente de refaire sa vie avec Joan, mais la fatalité et la police le rattrapent.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Grande Illusion',
    director: 'Jean Renoir',
    actors: [
      { name: 'Jean Gabin' },
      { name: 'Pierre Fresnay' },
      { name: 'Erich von Stroheim' },
      { name: 'Marcel Dalio' },
      { name: 'Dita Parlo' },
    ],
    coverUrl: '',
    releaseDate: '1937-06-08',
    length: 114,
    genre: ['Guerre', 'Drame'],
    saga: '',
    description:
      "Officiers français prisonniers en Allemagne : l'évasion, la fraternité de classe et la fin d'un monde.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "La Vie d'Émile Zola",
    director: 'William Dieterle',
    actors: [
      { name: 'Paul Muni' },
      { name: 'Gale Sondergaard' },
      { name: 'Joseph Schildkraut' },
      { name: 'Gloria Holden' },
      { name: 'Donald Crisp' },
    ],
    coverUrl: '',
    releaseDate: '1937-08-11',
    length: 116,
    genre: ['Biographie', 'Drame', 'Historique'],
    saga: '',
    description:
      "Zola prend la défense de Dreyfus et publie J'accuse, au prix de son exil.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_MOVIE, year: 1938 },
      { type: OscarEnum.OSCAR_BEST_SUPPORTING_ACTOR, year: 1938 },
      { type: OscarEnum.OSCAR_BEST_ADAPTED_SCREENPLAY, year: 1938 },
    ],
  },
  {
    title: 'Pépé le Moko',
    director: 'Julien Duvivier',
    actors: [
      { name: 'Jean Gabin' },
      { name: 'Mireille Balin' },
      { name: 'Gabriel Gabrio' },
      { name: 'Lucas Gridoux' },
      { name: 'Saturnin Fabre' },
    ],
    coverUrl: '',
    releaseDate: '1937-01-28',
    length: 94,
    genre: ['Policier', 'Drame', 'Romance'],
    saga: '',
    description:
      "Un caïd caché dans la Casbah d'Alger s'éprend d'une Parisienne et se livre en quittant son refuge.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Place aux jeunes',
    director: 'Leo McCarey',
    actors: [
      { name: 'Victor Moore' },
      { name: 'Beulah Bondi' },
      { name: 'Thomas Mitchell' },
      { name: 'Fay Bainter' },
      { name: 'Porter Hall' },
    ],
    coverUrl: '',
    releaseDate: '1937-05-09',
    length: 91,
    genre: ['Drame'],
    saga: '',
    description:
      'Un couple de personnes âgées est séparé par ses enfants, trop occupés pour les garder ensemble.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Un carnet de bal',
    director: 'Julien Duvivier',
    actors: [
      { name: 'Marie Bell' },
      { name: 'Françoise Rosay' },
      { name: 'Louis Jouvet' },
      { name: 'Raimu' },
      { name: 'Harry Baur' },
    ],
    coverUrl: '',
    releaseDate: '1937-09-09',
    length: 144,
    genre: ['Drame'],
    saga: '',
    description:
      "Une veuve retrouve les hommes d'un bal de jeunesse et mesure ce que le temps a fait d'eux.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Un jour aux courses',
    director: 'Sam Wood',
    actors: [
      { name: 'Groucho Marx' },
      { name: 'Chico Marx' },
      { name: 'Harpo Marx' },
      { name: 'Allan Jones' },
      { name: "Maureen O'Sullivan" },
    ],
    coverUrl: '',
    releaseDate: '1937-06-11',
    length: 111,
    genre: ['Comédie'],
    saga: '',
    description:
      'Hugo Z. Hackenbush, faux vétérinaire, sème le chaos dans un sanatorium et sur un hippodrome.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Alexandre Nevski',
    director: 'Sergueï Eisenstein, Dmitri Vassiliev',
    actors: [
      { name: 'Nikolaï Tcherkassov' },
      { name: 'Nikolaï Okhlopkov' },
      { name: 'Andreï Abrikossov' },
      { name: 'Dmitri Orlov' },
      { name: 'Valentina Ivaševa' },
    ],
    coverUrl: '',
    releaseDate: '1938-12-01',
    length: 111,
    genre: ['Guerre', 'Historique', 'Drame'],
    saga: '',
    description:
      'En 1242, le prince Alexandre Nevski écrase les chevaliers teutoniques sur le lac Peïpous gelé.',
    fromEntity: null,
    countryOrigin: ['Russie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Anges aux figures sales',
    director: 'Michael Curtiz',
    actors: [
      { name: 'James Cagney' },
      { name: "Pat O'Brien" },
      { name: 'Humphrey Bogart' },
      { name: 'Ann Sheridan' },
      { name: 'George Bancroft' },
    ],
    coverUrl: '',
    releaseDate: '1938-11-26',
    length: 97,
    genre: ['Policier', 'Drame'],
    saga: '',
    description:
      "Deux amis d'enfance, l'un prêtre, l'autre gangster, se retrouvent quand Rocky va à la chaise électrique.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Hôtel du Nord',
    director: 'Marcel Carné',
    actors: [
      { name: 'Annabella' },
      { name: 'Jean-Pierre Aumont' },
      { name: 'Louis Jouvet' },
      { name: 'Arletty' },
      { name: 'Paulette Dubost' },
    ],
    coverUrl: '',
    releaseDate: '1938-12-17',
    length: 95,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      "Sur le canal Saint-Martin, un couple suicidaire croise les pensionnaires d'un hôtel populaire. Atmosphère, atmosphère.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Jezebel',
    director: 'William Wyler',
    actors: [
      { name: 'Bette Davis' },
      { name: 'Henry Fonda' },
      { name: 'George Brent' },
      { name: 'Margaret Lindsay' },
      { name: 'Donald Crisp' },
    ],
    coverUrl: '',
    releaseDate: '1938-03-10',
    length: 104,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      "À La Nouvelle-Orléans, une femme de tête porte une robe rouge au bal et brise son fiancé, jusqu'à l'épidémie.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_ACTRESS, year: 1939 },
      { type: OscarEnum.OSCAR_BEST_SUPPORTING_ACTRESS, year: 1939 },
    ],
  },
  {
    title: 'La Bête humaine',
    director: 'Jean Renoir',
    actors: [
      { name: 'Jean Gabin' },
      { name: 'Simone Simon' },
      { name: 'Fernand Ledoux' },
      { name: 'Julien Carette' },
      { name: 'Blanchette Brunoy' },
    ],
    coverUrl: '',
    releaseDate: '1938-12-23',
    length: 100,
    genre: ['Drame', 'Thriller'],
    saga: '',
    description:
      "Un mécanicien de locomotive, marqué par une tare familiale, s'éprend de la femme d'un sous-chef de gare assassin.",
    fromEntity: {
      entityType: 'book',
      title: 'La Bête humaine',
      secondEntityKey: 'Émile Zola',
    },
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Femme du boulanger',
    director: 'Marcel Pagnol',
    actors: [
      { name: 'Raimu' },
      { name: 'Ginette Leclerc' },
      { name: 'Charles Moulin' },
      { name: 'Robert Vattier' },
      { name: 'Charles Blavette' },
    ],
    coverUrl: '',
    releaseDate: '1938-09-07',
    length: 133,
    genre: ['Comédie', 'Drame'],
    saga: '',
    description:
      "Dans un village provençal, la jeune femme du boulanger s'enfuit ; le village n'a plus de pain.",
    fromEntity: {
      entityType: 'book',
      title: 'Jean le Bleu',
      secondEntityKey: 'Jean Giono',
    },
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Aventures de Robin des Bois',
    director: 'Michael Curtiz, William Keighley',
    actors: [
      { name: 'Errol Flynn' },
      { name: 'Olivia de Havilland' },
      { name: 'Basil Rathbone' },
      { name: 'Claude Rains' },
      { name: 'Patric Knowles' },
    ],
    coverUrl: '',
    releaseDate: '1938-05-14',
    length: 102,
    genre: ['Aventure'],
    saga: '',
    description:
      'Robin de Locksley défie le prince Jean, aime Marianne et affronte Guy de Gisborne dans la forêt de Sherwood.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_FILM_EDITING, year: 1939 },
      { type: OscarEnum.OSCAR_BEST_PRODUCTION_DESIGN, year: 1939 },
      { type: OscarEnum.OSCAR_BEST_ORIGINAL_SCORE, year: 1939 },
    ],
  },
  {
    title: 'Pygmalion',
    director: 'Anthony Asquith, Leslie Howard',
    actors: [
      { name: 'Leslie Howard' },
      { name: 'Wendy Hiller' },
      { name: 'Wilfrid Lawson' },
      { name: 'Marie Lohr' },
      { name: 'Scott Sunderland' },
    ],
    coverUrl: '',
    releaseDate: '1938-10-06',
    length: 96,
    genre: ['Comédie', 'Romance'],
    saga: '',
    description:
      'Le professeur Higgins parie de transformer une bouquetière cockney en lady de la haute société.',
    fromEntity: null,
    countryOrigin: ['Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_ADAPTED_SCREENPLAY, year: 1939 }],
  },
  {
    title: 'Une femme disparaît',
    director: 'Alfred Hitchcock',
    actors: [
      { name: 'Margaret Lockwood' },
      { name: 'Michael Redgrave' },
      { name: 'Paul Lukas' },
      { name: 'May Whitty' },
      { name: 'Cecil Parker' },
    ],
    coverUrl: '',
    releaseDate: '1938-10-07',
    length: 96,
    genre: ['Thriller', 'Mystère'],
    saga: '',
    description:
      "Dans un train pour l'Angleterre, une vieille dame disparaît ; une jeune femme est la seule à s'en souvenir.",
    fromEntity: {
      entityType: 'book',
      title: 'The Wheel Spins',
      secondEntityKey: 'Ethel Lina White',
    },
    countryOrigin: ['Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Vous ne l'emporterez pas avec vous",
    director: 'Frank Capra',
    actors: [
      { name: 'Jean Arthur' },
      { name: 'Lionel Barrymore' },
      { name: 'James Stewart' },
      { name: 'Edward Arnold' },
      { name: 'Mischa Auer' },
    ],
    coverUrl: '',
    releaseDate: '1938-08-23',
    length: 126,
    genre: ['Comédie', 'Romance'],
    saga: '',
    description:
      "Un banquier veut racheter une maison peuplée d'originaux ; son fils aime la petite-fille du clan.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_MOVIE, year: 1939 },
      { type: OscarEnum.OSCAR_BEST_DIRECTOR, year: 1939 },
    ],
  },
  {
    title: 'Au revoir Mr. Chips',
    director: 'Sam Wood',
    actors: [
      { name: 'Robert Donat' },
      { name: 'Greer Garson' },
      { name: 'Terry Kilburn' },
      { name: 'John Mills' },
      { name: 'Paul Henreid' },
    ],
    coverUrl: '',
    releaseDate: '1939-05-15',
    length: 114,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      "Un professeur timide d'un collège anglais traverse cinquante ans de vie, d'amour et de guerres.",
    fromEntity: {
      entityType: 'book',
      title: 'Goodbye, Mr. Chips',
      secondEntityKey: 'James Hilton',
    },
    countryOrigin: ['Royaume-Uni', 'États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_ACTOR, year: 1940 }],
  },
  {
    title: 'Femme ou démon',
    director: 'George Marshall',
    actors: [
      { name: 'Marlene Dietrich' },
      { name: 'James Stewart' },
      { name: 'Mischa Auer' },
      { name: 'Charles Winninger' },
      { name: 'Brian Donlevy' },
    ],
    coverUrl: '',
    releaseDate: '1939-12-29',
    length: 94,
    genre: ['Western', 'Comédie'],
    saga: '',
    description:
      'Un shérif pacifique débarque à Bottleneck et croise Frenchy, chanteuse de saloon, entre vaches et revolvers.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'La Chevauchée fantastique',
    director: 'John Ford',
    actors: [
      { name: 'John Wayne' },
      { name: 'Claire Trevor' },
      { name: 'Thomas Mitchell' },
      { name: 'Andy Devine' },
      { name: 'John Carradine' },
    ],
    coverUrl: '',
    releaseDate: '1939-03-02',
    length: 96,
    genre: ['Western', 'Aventure'],
    saga: '',
    description:
      'Une diligence traverse le territoire apache : un outlaw, une prostituée, un ivrogne, un banquier et un joueur.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_SUPPORTING_ACTOR, year: 1940 },
      { type: OscarEnum.OSCAR_BEST_ORIGINAL_SCORE, year: 1940 },
    ],
  },
  {
    title: 'La Règle du jeu',
    director: 'Jean Renoir',
    actors: [
      { name: 'Marcel Dalio' },
      { name: 'Nora Gregor' },
      { name: 'Jean Renoir' },
      { name: 'Roland Toutain' },
      { name: 'Paulette Dubost' },
    ],
    coverUrl: '',
    releaseDate: '1939-07-07',
    length: 110,
    genre: ['Comédie', 'Drame'],
    saga: '',
    description:
      'Une chasse en Sologne et un chassé-croisé amoureux dans un château, où chacun a ses raisons.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Jour se lève',
    director: 'Marcel Carné',
    actors: [
      { name: 'Jean Gabin' },
      { name: 'Jacqueline Laurent' },
      { name: 'Arletty' },
      { name: 'Jules Berry' },
      { name: 'Mady Berry' },
    ],
    coverUrl: '',
    releaseDate: '1939-06-09',
    length: 93,
    genre: ['Drame'],
    saga: '',
    description:
      "Barricadé après un meurtre, un ouvrier se souvient de l'amour et de la trahison qui l'ont mené là.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Hauts de Hurlevent',
    director: 'William Wyler',
    actors: [
      { name: 'Merle Oberon' },
      { name: 'Laurence Olivier' },
      { name: 'David Niven' },
      { name: 'Flora Robson' },
      { name: 'Donald Crisp' },
    ],
    coverUrl: '',
    releaseDate: '1939-04-13',
    length: 104,
    genre: ['Drame', 'Romance'],
    saga: '',
    description:
      "Heathcliff, enfant trouvé, aime Cathy Earnshaw d'une passion qui dévaste deux familles des landes du Yorkshire.",
    fromEntity: {
      entityType: 'book',
      title: 'Les Hauts de Hurlevent',
      secondEntityKey: 'Emily Brontë',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_CINEMATOGRAPHY, year: 1940 }],
  },
  {
    title: 'Monsieur Smith au Sénat',
    director: 'Frank Capra',
    actors: [
      { name: 'James Stewart' },
      { name: 'Jean Arthur' },
      { name: 'Claude Rains' },
      { name: 'Edward Arnold' },
      { name: 'Guy Kibbee' },
    ],
    coverUrl: '',
    releaseDate: '1939-10-19',
    length: 129,
    genre: ['Drame'],
    saga: '',
    description:
      'Un jeune sénateur naïf découvre la corruption de Washington et filibuste pour sauver un camp de jeunesse.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Ninotchka',
    director: 'Ernst Lubitsch',
    actors: [
      { name: 'Greta Garbo' },
      { name: 'Melvyn Douglas' },
      { name: 'Ina Claire' },
      { name: 'Bela Lugosi' },
      { name: 'Sig Ruman' },
    ],
    coverUrl: '',
    releaseDate: '1939-11-03',
    length: 110,
    genre: ['Comédie', 'Romance'],
    saga: '',
    description:
      "Une envoyée soviétique à Paris, glaciale, fond sous le charme d'un comte et du champagne.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Seuls les anges ont des ailes',
    director: 'Howard Hawks',
    actors: [
      { name: 'Cary Grant' },
      { name: 'Jean Arthur' },
      { name: 'Richard Barthelmess' },
      { name: 'Rita Hayworth' },
      { name: 'Thomas Mitchell' },
    ],
    coverUrl: '',
    releaseDate: '1939-05-15',
    length: 121,
    genre: ['Aventure', 'Drame', 'Romance'],
    saga: '',
    description:
      "Des pilotes de l'Amérique du Sud risquent leur vie pour le courrier ; une cabarettiste s'invite dans leur hangar.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Vers sa destinée',
    director: 'John Ford',
    actors: [
      { name: 'Henry Fonda' },
      { name: 'Alice Brady' },
      { name: 'Marjorie Weaver' },
      { name: 'Arleen Whelan' },
      { name: 'Eddie Collins' },
    ],
    coverUrl: '',
    releaseDate: '1939-06-09',
    length: 100,
    genre: ['Biographie', 'Drame', 'Historique'],
    saga: '',
    description:
      'Le jeune avocat Abraham Lincoln défend deux frères accusés de meurtre et affirme son sens de la justice.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
];
