import { BaseMovie } from '../../../models/movie-model';

export const baseMoviesPage1: BaseMovie[] = [
  {
    title: 'I, Robot',
    director: 'Alex Proyas',
    actors: [
      {
        name: 'Will Smith',
      },
    ],
    coverUrl: '/movies_pictures/i_robot.jpg',
    releaseDate: '2004-12-10',
    length: 115,
    genre: 'Science Fiction',
    saga: '',
    description: '',
  },

  {
    title: 'Mickey 17',
    director: 'Bong Joon-ho',
    actors: [
      {
        name: 'Robert Pattinson',
      },
    ],
    coverUrl: '/movies_pictures/620281-mickey-17-0-150-0-225-crop.jpg',
    releaseDate: '2025-01-31',
    length: 137,
    genre: 'Science Fiction',
    saga: '',
    description: '',
  },

  {
    title: 'Carry-On',
    director: 'Jaume Collet-Serra',
    actors: [
      {
        name: 'Taron Egerton',
      },
    ],
    coverUrl: '/movies_pictures/905876-carry-on-2024-0-150-0-225-crop.jpg',
    releaseDate: '2024-11-15',
    length: 119,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'Le Comte de Monte-Cristo',
    director: 'Alexandre de La Patellière, Matthieu Delaporte',
    actors: [
      {
        name: 'Pierre Niney',
      },
    ],
    coverUrl:
      '/movies_pictures/977835-the-count-of-monte-cristo-2024-0-150-0-225-crop.jpg',
    releaseDate: '2024-06-28',
    length: 178,
    genre: 'Adventure',
    saga: '',
    description: '',
  },
  {
    title: 'Challengers',
    director: 'Luca Guadagnino',
    actors: [
      {
        name: 'Zendaya',
      },
    ],
    coverUrl: '/movies_pictures/842301-challengers-0-150-0-225-crop.jpg',
    releaseDate: '2024-04-26',
    length: 131,
    genre: 'Drama',
    saga: '',
    description: '',
  },
  {
    title: 'Road House',
    director: 'Doug Liman',
    actors: [
      {
        name: 'Jake Gyllenhaal',
      },
    ],
    coverUrl: '/movies_pictures/291213-road-house-0-150-0-225-crop.jpg',
    releaseDate: '2024-03-21',
    length: 121,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'Damsel',
    director: 'Juan Carlos Fresnadillo',
    actors: [
      {
        name: 'Millie Bobby Brown',
      },
    ],
    coverUrl: '/movies_pictures/683451-damsel-0-150-0-225-crop.jpg',
    releaseDate: '2024-03-08',
    length: 110,
    genre: 'Fantasy',
    saga: '',
    description: '',
  },

  {
    title: 'Sly',
    director: 'Thom Zimny',
    actors: [
      {
        name: 'Sylvester Stallone',
      },
    ],
    coverUrl: '/movies_pictures/073f18caf5a23116b09d9b12d9828837.jpg',
    releaseDate: '2023-11-03',
    length: 95,
    genre: 'Documentary',
    saga: '',
    description: '',
  },
  {
    title: 'Gran Turismo',
    director: 'Neill Blomkamp',
    actors: [
      {
        name: 'Archie Madekwe',
      },
    ],
    coverUrl: '/movies_pictures/882718-gran-turismo-0-150-0-225-crop.jpg',
    releaseDate: '2023-08-25',
    length: 135,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'Oppenheimer',
    director: 'Christopher Nolan',
    actors: [
      {
        name: 'Cillian Murphy',
      },
      {
        name: 'Emily Blunt',
      },
      {
        name: 'Matt Damon',
      },
      {
        name: 'Robert Downey Jr.',
      },
    ],
    coverUrl: '/movies_pictures/784328-oppenheimer-0-150-0-225-crop.jpg',
    releaseDate: '2023-07-21',
    length: 180,
    genre: 'Drama',
    saga: '',
    description: '',
  },
  {
    title: 'Barbie',
    director: 'Greta Gerwig',
    actors: [
      {
        name: 'Margot Robbie',
      },
    ],
    coverUrl: '/movies_pictures/277064-barbie-0-150-0-225-crop.jpg',
    releaseDate: '2023-07-21',
    length: 114,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: 'Arnold',
    director: 'Lesley Chilcott',
    actors: [
      {
        name: 'Arnold Schwarzenegger',
      },
    ],
    coverUrl: '/movies_pictures/1014180-arnold-0-150-0-225-crop.jpg',
    releaseDate: '2023-06-07',
    length: 180,
    genre: 'Documentary',
    saga: '',
    description: '',
  },

  {
    title: 'Babylon',
    director: 'Damien Chazelle',
    actors: [
      {
        name: 'Brad Pitt',
      },
      {
        name: 'Margot Robbie',
      },
    ],
    coverUrl: '/movies_pictures/542773-babylon-0-150-0-225-crop.jpg',
    releaseDate: '2022-12-23',
    length: 189,
    genre: 'Drama',
    saga: '',
    description: '',
  },

  {
    title: "L'École du Bien et du Mal",
    director: 'Paul Feig',
    actors: [
      {
        name: 'Sofia Wylie',
      },
    ],
    coverUrl:
      '/movies_pictures/698765-the-school-for-good-and-evil-0-150-0-225-crop.jpg',
    releaseDate: '2022-10-19',
    length: 147,
    genre: 'Fantasy',
    saga: '',
    description: '',
  },
  {
    title: 'Samaritan',
    director: 'Julius Avery',
    actors: [
      {
        name: 'Sylvester Stallone',
      },
    ],
    coverUrl: '/movies_pictures/555588-samaritan-0-150-0-225-crop.jpg',
    releaseDate: '2022-08-26',
    length: 102,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'Prey',
    director: 'Dan Trachtenberg',
    actors: [
      {
        name: 'Amber Midthunder',
      },
    ],
    coverUrl: '/movies_pictures/686389-prey-0-150-0-225-crop.jpg',
    releaseDate: '2022-08-05',
    length: 100,
    genre: 'Action',
    saga: 'Predator',
    description: '',
  },
  {
    title: 'Bullet Train',
    director: 'David Leitch',
    actors: [
      {
        name: 'Brad Pitt',
      },
      {
        name: 'Joey King',
      },
      {
        name: 'Aaron Taylor-Johnson',
      },
      {
        name: 'Sandra Bullock',
      },
    ],
    coverUrl: '/movies_pictures/641961-bullet-train-0-150-0-225-crop.jpg',
    releaseDate: '2022-08-05',
    length: 126,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'Le haut du panier',
    director: 'Jeremiah Zagar',
    actors: [
      {
        name: 'Adam Sandler',
      },
    ],
    coverUrl: '/movies_pictures/629376-hustle-0-150-0-225-crop.jpg',
    releaseDate: '2022-06-08',
    length: 117,
    genre: 'Drama',
    saga: '',
    description: '',
  },
  {
    title: 'Top Gun : Maverick',
    director: 'Joseph Kosinski',
    actors: [
      {
        name: 'Tom Cruise',
      },
    ],
    coverUrl: '/movies_pictures/293465-top-gun-maverick-0-150-0-225-crop.jpg',
    releaseDate: '2022-05-27',
    length: 130,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'Everything Everywhere All at Once',
    director: 'Daniel Kwan, Daniel Scheinert',
    actors: [
      {
        name: 'Michelle Yeoh',
      },
    ],
    coverUrl:
      '/movies_pictures/474474-everything-everywhere-all-at-once-0-150-0-225-crop.jpg',
    releaseDate: '2022-03-25',
    length: 139,
    genre: 'Science Fiction',
    saga: '',
    description: '',
  },
  {
    title: 'The Adam Project',
    director: 'Shawn Levy',
    actors: [
      {
        name: 'Ryan Reynolds',
      },
    ],
    coverUrl: '/movies_pictures/620665-the-adam-project-0-150-0-225-crop.jpg',
    releaseDate: '2022-03-11',
    length: 106,
    genre: 'Science Fiction',
    saga: '',
    description: '',
  },
  {
    title: "Don't look up, déni cosmique",
    director: 'Adam McKay',
    actors: [
      {
        name: 'Leonardo DiCaprio',
      },
      {
        name: 'Jennifer Lawrence',
      },
      {
        name: 'Cate Blanchett',
      },
      {
        name: 'Ariana Grande',
      },
      {
        name: 'Timothée Chalamet',
      },
      {
        name: 'Meryl Streep',
      },
      {
        name: 'Chris Evans',
      },
      {
        name: 'Jonah Hill',
      },
    ],
    coverUrl: '/movies_pictures/572255-don-t-look-up-0-150-0-225-crop.jpg',
    releaseDate: '2021-12-24',
    length: 138,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: 'Red Notice',
    director: 'Rawson Marshall Thurber',
    actors: [
      {
        name: 'Dwayne Johnson',
      },
      {
        name: 'Gal Gadot',
      },
      {
        name: 'Ryan Reynolds',
      },
    ],
    coverUrl: '/movies_pictures/441858-red-notice-0-150-0-225-crop.jpg',
    releaseDate: '2021-11-12',
    length: 118,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'The Guilty',
    director: 'Antoine Fuqua',
    actors: [
      {
        name: 'Jake Gyllenhaal',
      },
    ],
    coverUrl: '/movies_pictures/496198-the-guilty-0-150-0-225-crop.jpg',
    releaseDate: '2021-10-01',
    length: 90,
    genre: 'Thriller',
    saga: '',
    description: '',
  },
  {
    title: 'La méthode Williams',
    director: 'Reinaldo Marcus Green',
    actors: [
      {
        name: 'Will Smith',
      },
    ],
    coverUrl: '/movies_pictures/541998-king-richard-0-150-0-225-crop.jpg',
    releaseDate: '2021-11-19',
    length: 144,
    genre: 'Drama',
    saga: '',
    description: '',
  },
  {
    title: 'Free Guy',
    director: 'Shawn Levy',
    actors: [
      {
        name: 'Ryan Reynolds',
      },
    ],
    coverUrl: '/movies_pictures/479814-free-guy-0-150-0-225-crop.jpg',
    releaseDate: '2021-08-13',
    length: 115,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: 'Jolt',
    director: 'Tanya Wexler',
    actors: [
      {
        name: 'Kate Beckinsale',
      },
    ],
    coverUrl: '/movies_pictures/544435-jolt-0-150-0-225-crop.jpg',
    releaseDate: '2021-07-23',
    length: 91,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'The Terminal',
    director: 'Steven Spielberg',
    actors: [{ name: 'Tom Hanks' }, { name: 'Zoe Saldana' }],
    coverUrl: '/movies_pictures/51527-the-terminal-0-150-0-225-crop.jpg',
    releaseDate: '2004-06-18',
    length: 128,
    genre: 'Drama',
    saga: '',
    description: '',
  },
  {
    title: 'Tanguy',
    director: 'Étienne Chatiliez',
    actors: [{ name: 'Éric Berger' }],
    coverUrl: '/movies_pictures/50585-tanguy-0-150-0-225-crop.jpg',
    releaseDate: '2001-12-19',
    length: 108,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: 'The One',
    director: 'James Wong',
    actors: [{ name: 'Jet Li' }],
    coverUrl: '/movies_pictures/45888-the-one-0-150-0-225-crop.jpg',
    releaseDate: '2001-11-02',
    length: 87,
    genre: 'Science Fiction',
    saga: '',
    description: '',
  },
  {
    title: 'Wasabi',
    director: 'Gérard Krawczyk',
    actors: [{ name: 'Jean Reno' }],
    coverUrl: '/movies_pictures/50516-wasabi-0-150-0-225-crop.jpg',
    releaseDate: '2001-10-31',
    length: 94,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'Training Day',
    director: 'Antoine Fuqua',
    actors: [{ name: 'Denzel Washington' }],
    coverUrl: '/movies_pictures/50580-training-day-0-150-0-225-crop.jpg',
    releaseDate: '2001-10-05',
    length: 122,
    genre: 'Crime',
    saga: '',
    description: '',
  },
  {
    title: 'Shaolin Soccer',
    director: 'Stephen Chow',
    actors: [{ name: 'Stephen Chow' }],
    coverUrl: '/movies_pictures/45025-shaolin-soccer-0-150-0-225-crop.jpg',
    releaseDate: '2001-07-12',
    length: 87,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: 'Mulholland Drive',
    director: 'David Lynch',
    actors: [{ name: 'Naomi Watts' }],
    coverUrl: '/movies_pictures/mulholland_drive.jpg',
    releaseDate: '2001-10-12',
    length: 147,
    genre: 'Enquête',
    saga: '',
    description: '',
  },
  {
    title: 'Replicant',
    director: 'Ringo Lam',
    actors: [{ name: 'Jean-Claude Van Damme' }],
    coverUrl: '/movies_pictures/46077-replicant-0-150-0-225-crop.jpg',
    releaseDate: '2001-05-04',
    length: 100,
    genre: 'Action',
    saga: '',
    description: '',
  },

  {
    title: 'Battle Royale',
    director: 'Kinji Fukasaku',
    actors: [{ name: 'Tatsuya Fujiwara' }],
    coverUrl: '/movies_pictures/49810-battle-royale-0-150-0-225-crop.jpg',
    releaseDate: '2000-12-16',
    length: 113,
    genre: 'Thriller',
    saga: '',
    description: '',
  },
  {
    title: 'Miss Détective',
    director: 'Donald Petrie',
    actors: [{ name: 'Sandra Bullock' }],
    coverUrl: '/movies_pictures/51006-miss-congeniality-0-150-0-225-crop.jpg',
    releaseDate: '2000-12-22',
    length: 109,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: "A l'aube du 6ème jour",
    director: 'Roger Spottiswoode',
    actors: [{ name: 'Arnold Schwarzenegger' }],
    coverUrl: '/movies_pictures/a_l_aube_du_sixieme_jour.jpg',
    releaseDate: '2000-11-17',
    length: 123,
    genre: 'Science Fiction',
    saga: '',
    description: '',
  },
  {
    title: 'Memento',
    director: 'Christopher Nolan',
    actors: [{ name: 'Guy Pearce' }],
    coverUrl: '/movies_pictures/memento-0-150-0-225-crop.jpg',
    releaseDate: '2000-09-05',
    length: 113,
    genre: 'Thriller',
    saga: '',
    description: '',
  },
  {
    title: 'Snatch',
    director: 'Guy Ritchie',
    actors: [
      {
        name: 'Jason Statham',
      },
      {
        name: 'Brad Pitt',
      },
    ],
    coverUrl: '/movies_pictures/snatch.jpg',
    releaseDate: '2000-09-01',
    length: 104,
    genre: 'Crime',
    saga: '',
    description: '',
  },
  {
    title: 'Requiem for a Dream',
    director: 'Darren Aronofsky',
    actors: [{ name: 'Ellen Burstyn' }],
    coverUrl: '/movies_pictures/requiem_for_a_dream.jpg',
    releaseDate: '2000-10-06',
    length: 102,
    genre: 'Drama',
    saga: '',
    description: '',
  },
  {
    title: 'Gladiator',
    director: 'Ridley Scott',
    actors: [{ name: 'Russell Crowe' }],
    coverUrl: '/movies_pictures/51952-gladiator-2000-0-150-0-225-crop.jpg',
    releaseDate: '2000-05-05',
    length: 155,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'Rebel Ridge',
    director: 'Jeremy Saulnier',
    actors: [{ name: 'John Boyega' }],
    coverUrl: '/movies_pictures/rebel_ridge.jpg',
    releaseDate: '2024-05-31',
    length: 120,
    genre: 'Thriller',
    saga: '',
    description: '',
  },
  {
    title: '84 m²',
    director: 'Kim Tae-joon',
    actors: [{ name: 'Acteur principal' }],
    coverUrl: '/movies_pictures/b8e7d5e682836c190da279d7aa0c23b4.webp',
    releaseDate: '2024-01-01',
    length: 90,
    genre: 'Drama',
    saga: '',
    description: '',
  },
  {
    title: 'Brick',
    director: 'Philip Koch',
    actors: [{ name: 'Matthias Schweighöfer' }, { name: 'Ruby O. Fee' }],
    coverUrl: '/movies_pictures/cdfeb09ef9b1b5e1d5b35269efd5735a.webp',
    releaseDate: '2025-07-10',
    length: 105,
    genre: 'Thriller, Science Fiction',
    saga: '',
    description: '',
  },
  {
    title: 'La carte qui mène à toi',
    director: 'Lasse Hallström',
    actors: [{ name: 'Madelyn Cline' }],
    coverUrl: '/movies_pictures/1254072.webp',
    releaseDate: '2024-01-01',
    length: 100,
    genre: 'Romance',
    saga: '',
    description: '',
  },
  {
    title: 'Les 4 fantastiques',
    director: 'Matt Shakman',
    actors: [
      {
        name: 'Pedro Pascal',
      },
      {
        name: 'Vanessa Kirby',
      },
      {
        name: 'Joseph Quinn',
      },
      {
        name: 'Ebon Moss-Bachrach',
      },
    ],
    coverUrl:
      '/movies_pictures/les-4-fantastiques-premiers-pas-affiche-officielle-scaled.jpg',
    releaseDate: '2025-07-25',
    length: 130,
    genre: 'Action, Adventure',
    saga: 'Marvel Cinematic Universe',
    description: '',
  },
  {
    title: 'Premier contact',
    director: 'Denis Villeneuve',
    actors: [
      { name: 'Amy Adams' },
      { name: 'Jeremy Renner' },
      { name: 'Forest Whitaker' },
    ],
    coverUrl: '/movies_pictures/109206907.webp',
    releaseDate: '2016-11-11',
    length: 116,
    genre: 'Science Fiction, Drama',
    saga: '',
    description: '',
  },
  {
    title: 'Sexe entre amis',
    director: 'Will Gluck',
    actors: [
      { name: 'Justin Timberlake' },
      { name: 'Mila Kunis' },
      { name: 'Patricia Clarkson' },
    ],
    coverUrl: '/movies_pictures/19757410.webp',
    releaseDate: '2011-07-22',
    length: 109,
    genre: 'Comedy, Romance',
    saga: '',
    description: '',
  },
  {
    title: 'Source Code',
    director: 'Duncan Jones',
    actors: [
      { name: 'Jake Gyllenhaal' },
      { name: 'Michelle Monaghan' },
      { name: 'Vera Farmiga' },
    ],
    coverUrl: '/movies_pictures/81JgsD1EoIL._UF894,1000_QL80_ .jpg',
    releaseDate: '2011-04-01',
    length: 93,
    genre: 'Science Fiction, Thriller',
    saga: '',
    description: '',
  },
  {
    title: 'Le témoin amoureux',
    director: 'Paul Weiland',
    actors: [
      { name: 'Patrick Dempsey' },
      { name: 'Michelle Monaghan' },
      { name: 'Kevin McKidd' },
    ],
    coverUrl: '/movies_pictures/18926251.jpg',
    releaseDate: '2008-05-02',
    length: 101,
    genre: 'Comedy, Romance',
    saga: '',
    description: '',
  },
  {
    title: 'Une femme en jeu',
    director: 'Anna Kendrick',
    actors: [{ name: 'Acteur principal' }],
    coverUrl: '/movies_pictures/96870dc4da3356ac6b13fb5359f5cd56.jpg',
    releaseDate: '2024-01-01',
    length: 95,
    genre: 'Drama',
    saga: '',
    description: '',
  },
  {
    title: 'Lettres à Juliette',
    director: 'Gary Winick',
    actors: [{ name: 'Amanda Seyfried' }, { name: 'Gael García Bernal' }],
    coverUrl: '/movies_pictures/19241233.webp',
    releaseDate: '2010-05-14',
    length: 105,
    genre: 'Romance',
    saga: '',
    description: '',
  },
  {
    title: 'My Oxford Year',
    director: 'Sarah Treem',
    actors: [{ name: 'Aisling Franciosi' }],
    coverUrl: '/movies_pictures/f1c06582c665ba69d863934d8b176d25.jpg',
    releaseDate: '2024-01-01',
    length: 113,
    genre: 'Romance',
    saga: '',
    description: '',
  },
  {
    title: 'Ordinary Angels',
    director: 'Jon Gunn',
    actors: [{ name: 'Hilary Swank' }, { name: 'Alan Ritchson' }],
    coverUrl: '/movies_pictures/1684889.jpg',
    releaseDate: '2024-02-23',
    length: 118,
    genre: 'Drama',
    saga: '',
    description: '',
  },
  {
    title: 'French Lover',
    director: 'Nina Rives',
    actors: [{ name: 'Omar Sy' }],
    coverUrl:
      '/movies_pictures/AAAABWVgN_6qNZk70MFWrIUY6kiYXI907aDytmsBt7M1eQ_o.jpg',
    releaseDate: '2025-01-01',
    length: 95,
    genre: 'Romance',
    saga: '',
    description: '',
  },
  {
    title: 'Thunderbolts',
    director: 'Jake Schreier',
    actors: [
      {
        name: 'Florence Pugh',
      },
      {
        name: 'Sebastian Stan',
      },
      {
        name: 'David Harbour',
      },
    ],
    coverUrl: '/movies_pictures/72b74175dd05a704ebed57975b0f6487.jpg',
    releaseDate: '2025-05-02',
    length: 126,
    genre: 'Action',
    saga: 'Marvel Cinematic Universe',
    description: '',
  },
  {
    title: 'Le silence des agneaux',
    director: 'Jonathan Demme',
    actors: [{ name: 'Jodie Foster' }, { name: 'Anthony Hopkins' }],
    coverUrl: '/movies_pictures/4218638.jpg',
    releaseDate: '1991-02-14',
    length: 118,
    genre: 'Thriller',
    saga: '',
    description: '',
  },
  {
    title: 'Maintenance Required',
    director: 'Lacey Uhlemeyer',
    actors: [{ name: 'Madelaine Petsch' }],
    coverUrl:
      '/movies_pictures/MV5BNGZlN2Y5ZGEtMmU0MS00ZWI0L_FMjpg_UX1000_.jpg',
    releaseDate: '2024-01-01',
    length: 95,
    genre: 'Drama',
    saga: '',
    description: '',
  },
  {
    title: 'Nocturnal Animals',
    director: 'Tom Ford',
    actors: [{ name: 'Amy Adams' }, { name: 'Jake Gyllenhaal' }],
    coverUrl: '/movies_pictures/415908.webp',
    releaseDate: '2016-11-04',
    length: 116,
    genre: 'Thriller',
    saga: '',
    description: '',
  },
  {
    title: 'Superman',
    director: 'Richard Donner',
    actors: [{ name: 'Christopher Reeve' }, { name: 'Margot Kidder' }],
    coverUrl: '/movies_pictures/Superman_affiche_film_1.webp',
    releaseDate: '1978-12-15',
    length: 143,
    genre: 'Action',
    saga: 'Superman',
    description: '',
  },
  {
    title: 'Superman II',
    director: 'Richard Lester',
    actors: [{ name: 'Christopher Reeve' }, { name: 'Margot Kidder' }],
    coverUrl: '/movies_pictures/61a2Wp8ylUL._AC_UF894,1000_QL80_.jpg',
    releaseDate: '1980-12-12',
    length: 127,
    genre: 'Action',
    saga: 'Superman',
    description: '',
  },
  {
    title: 'Superman Returns',
    director: 'Bryan Singer',
    actors: [{ name: 'Brandon Routh' }, { name: 'Kate Bosworth' }],
    coverUrl: '/movies_pictures/18648048.jpg',
    releaseDate: '2006-06-28',
    length: 154,
    genre: 'Action',
    saga: 'Superman',
    description: '',
  },
  {
    title: 'Enemy',
    director: 'Denis Villeneuve',
    actors: [{ name: 'Jake Gyllenhaal' }, { name: 'Mélanie Laurent' }],
    coverUrl: '/movies_pictures/317481.webp',
    releaseDate: '2013-09-08',
    length: 90,
    genre: 'Thriller',
    saga: '',
    description: '',
  },
  {
    title: 'Forever My Girl',
    director: 'Bethany Ashton Wolf',
    actors: [{ name: 'Alex Roe' }, { name: 'Jessica Rothe' }],
    coverUrl: '/movies_pictures/forever_my_girl.jpg',
    releaseDate: '2018-01-19',
    length: 104,
    genre: 'Romance',
    saga: '',
    description: '',
  },
  {
    title: 'Dans tes rêves',
    director: 'Denis Thybaud',
    actors: [
      { name: 'Disiz' },
      { name: 'Béatrice Dalle' },
      { name: 'Vincent Elbaz' },
    ],
    coverUrl: '/movies_pictures/18411781.jpg',
    releaseDate: '2005-10-05',
    length: 95,
    genre: 'Comedy, Drama',
    saga: '',
    description: '',
  },
  {
    title: 'DodgeBall: Même pas mal',
    director: 'Rawson Marshall Thurber',
    actors: [
      {
        name: 'Vince Vaughn',
      },
      {
        name: 'Ben Stiller',
      },
      {
        name: 'Justin Long',
      },
    ],
    coverUrl: '/movies_pictures/dodgeball.jpg',
    releaseDate: '2004-06-18',
    length: 92,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: 'Garfield',
    director: 'Peter Hewitt',
    actors: [{ name: 'Bill Murray' }],
    coverUrl: '/movies_pictures/47508-garfield-0-150-0-225-crop.jpg',
    releaseDate: '2004-06-11',
    length: 80,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: 'Harold & Kumar Go to White Castle',
    director: 'Danny Leiner',
    actors: [{ name: 'John Cho' }],
    coverUrl: '/movies_pictures/harold_et_kumar_white_castle.jpg',
    releaseDate: '2004-07-30',
    length: 88,
    genre: 'Comedy',
    saga: 'Harold & Kumar',
    description: '',
  },
  {
    title: 'The Day After Tomorrow',
    director: 'Roland Emmerich',
    actors: [
      {
        name: 'Dennis Quaid',
      },
      {
        name: 'Jake Gyllenhaal',
      },
    ],
    coverUrl: '/movies_pictures/le_jour_d_apres.jpg',
    releaseDate: '2004-05-28',
    length: 124,
    genre: 'Science Fiction',
    saga: '',
    description: '',
  },
  {
    title: 'Van Helsing',
    director: 'Stephen Sommers',
    actors: [
      {
        name: 'Hugh Jackman',
      },
      {
        name: 'Kate Beckinsale',
      },
    ],
    coverUrl: '/movies_pictures/48113-van-helsing-0-150-0-225-crop.jpg',
    releaseDate: '2004-05-07',
    length: 131,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'Man on Fire',
    director: 'Tony Scott',
    actors: [{ name: 'Denzel Washington' }],
    coverUrl: '/movies_pictures/man_on_fire.jpg',
    releaseDate: '2004-04-23',
    length: 146,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'Shaun of the Dead',
    director: 'Edgar Wright',
    actors: [{ name: 'Simon Pegg' }],
    coverUrl: '/movies_pictures/shaun_of_the_dead.jpg',
    releaseDate: '2004-04-09',
    length: 99,
    genre: 'Comedy',
    saga: 'Cornetto',
    description: '',
  },
  {
    title: 'Les choristes',
    director: 'Christophe Barratier',
    actors: [{ name: 'Gérard Jugnot' }],
    coverUrl: '/movies_pictures/les_choristes.jpg',
    releaseDate: '2004-03-17',
    length: 95,
    genre: 'Drama',
    saga: '',
    description: '',
  },
  {
    title: 'EuroTrip',
    director: 'Jeff Schaffer',
    actors: [{ name: 'Scott Mechlowicz' }, { name: 'Matt Damon' }],
    coverUrl: '/movies_pictures/47243-eurotrip-0-150-0-225-crop.jpg',
    releaseDate: '2004-02-20',
    length: 92,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: 'Les 11 commandements',
    director: 'François Desagnat, Thomas Sorriaux',
    actors: [{ name: 'François Desagnat' }],
    coverUrl: '/movies_pictures/40754-the-11-commandments-0-150-0-225-crop.jpg',
    releaseDate: '2004-02-11',
    length: 90,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: 'RRRrrrr!!!',
    director: 'Alain Chabat',
    actors: [{ name: 'Marion Cotillard' }],
    coverUrl: '/movies_pictures/38203-rrrrrrr--0-150-0-225-crop.jpg',
    releaseDate: '2004-01-28',
    length: 94,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: 'Saw',
    director: 'James Wan',
    actors: [{ name: 'Cary Elwes' }],
    coverUrl: '/movies_pictures/saw.jpg',
    releaseDate: '2004-10-29',
    length: 103,
    genre: 'Horror',
    saga: 'Saw',
    description: '',
  },
  {
    title: "L'effet papillon",
    director: 'Eric Bress, J. Mackye Gruber',
    actors: [{ name: 'Ashton Kutcher' }],
    coverUrl:
      '/movies_pictures/50654-the-butterfly-effect-0-150-0-225-crop.jpg',
    releaseDate: '2004-01-23',
    length: 113,
    genre: 'Science Fiction',
    saga: '',
    description: '',
  },
  {
    title: 'Oldboy',
    director: 'Park Chan-wook',
    actors: [{ name: 'Choi Min-sik' }],
    coverUrl: '/movies_pictures/51454-oldboy-0-150-0-225-crop.jpg',
    releaseDate: '2003-11-21',
    length: 120,
    genre: 'Thriller',
    saga: '',
    description: '',
  },
  {
    title: 'Bruce tout-puissant',
    director: 'Tom Shadyac',
    actors: [
      {
        name: 'Jim Carrey',
      },
      {
        name: 'Morgan Freeman',
      },
    ],
    coverUrl: '/movies_pictures/51749-bruce-almighty-0-150-0-225-crop.jpg',
    releaseDate: '2003-05-23',
    length: 101,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: 'Moi, Cesar, 10 ans et demi, 1m39',
    director: 'Richard Berry',
    actors: [{ name: 'Richard Berry' }],
    coverUrl: '/movies_pictures/6543-i-cesar-0-150-0-225-crop.jpg',
    releaseDate: '2003-04-30',
    length: 91,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: 'En sursis',
    director: 'Andrzej Bartkowiak',
    actors: [
      {
        name: 'Jet Li',
      },
      {
        name: 'DMX',
      },
    ],
    coverUrl: '/movies_pictures/46051-cradle-2-the-grave-0-150-0-225-crop.jpg',
    releaseDate: '2003-02-28',
    length: 101,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'La Beuze',
    director: 'Éric Rochant',
    actors: [
      {
        name: 'Vincent Lindon',
      },
      {
        name: 'Michael Youn',
      },
    ],
    coverUrl: '/movies_pictures/la_beuze.jpg',
    releaseDate: '2003-02-05',
    length: 95,
    genre: 'Drama',
    saga: '',
    description: '',
  },
  {
    title: 'Ong Bak',
    director: 'Prachya Pinkaew',
    actors: [{ name: 'Tony Jaa' }],
    coverUrl: '/movies_pictures/47277-ong-bak-0-150-0-225-crop.jpg',
    releaseDate: '2003-01-21',
    length: 108,
    genre: 'Action',
    saga: '',
    description: '',
  },
  {
    title: 'Arrête-moi si tu peux',
    director: 'Steven Spielberg',
    actors: [
      { name: 'Leonardo DiCaprio' },
      { name: 'Tom Hanks' },
      { name: 'Amy Adams' },
    ],
    coverUrl: '/movies_pictures/51484-catch-me-if-you-can-0-150-0-225-crop.jpg',
    releaseDate: '2002-12-25',
    length: 141,
    genre: 'Crime',
    saga: '',
    description: '',
  },
  {
    title: 'Equilibrium',
    director: 'Kurt Wimmer',
    actors: [{ name: 'Christian Bale' }],
    coverUrl: '/movies_pictures/equilibrium-0-150-0-225-crop.jpg',
    releaseDate: '2002-12-06',
    length: 107,
    genre: 'Science Fiction',
    saga: '',
    description: '',
  },
  {
    title: 'Opération antisèche',
    director: 'Andrew Gurland',
    actors: [{ name: 'Trevor Fehrman' }],
    coverUrl: '/movies_pictures/41348-cheats-0-150-0-225-crop.jpg',
    releaseDate: '2002-09-13',
    length: 86,
    genre: 'Comedy',
    saga: '',
    description: '',
  },
  {
    title: '28 jours plus tard',
    director: 'Danny Boyle',
    actors: [{ name: 'Cillian Murphy' }],
    coverUrl: '/movies_pictures/28_jours_plus_tard.jpg',
    releaseDate: '2002-11-01',
    length: 113,
    genre: 'Horror',
    saga: '28... plus tard',
    description: '',
  },
  {
    title: 'Le cercle : The ring',
    director: 'Gore Verbinski',
    actors: [{ name: 'Naomi Watts' }],
    coverUrl: '/movies_pictures/the-ring-0-150-0-225-crop.jpg',
    releaseDate: '2002-10-18',
    length: 115,
    genre: 'Horror',
    saga: '',
    description: '',
  },
  {
    title: 'Phone Game',
    director: 'Joel Schumacher',
    actors: [{ name: 'Colin Farrell' }, { name: 'Forest Whitaker' }],
    coverUrl: '/movies_pictures/phone_game.jpg',
    releaseDate: '2002-09-10',
    length: 81,
    genre: 'Thriller',
    saga: '',
    description: '',
  },
  {
    title: 'La femme de ménage',
    director: 'Paul Feig',
    actors: [
      { name: 'Sydney Sweeney' },
      { name: 'Amanda Seyfried' },
      { name: 'Brandon Sklenar' },
    ],
    coverUrl: '/movies_pictures/eda3bba832e22c79ea22117b058f84e5.webp',
    releaseDate: '2025-12-24',
    length: 150,
    genre: 'Thriller',
    saga: '',
    description: '',
  },
  {
    title: 'Eaux profondes',
    director: 'Adrian Lyne',
    actors: [
      { name: 'Ben Affleck' },
      { name: 'Ana de Armas' },
      { name: 'Jacob Elordi' },
    ],
    coverUrl:
      '/movies_pictures/c57fc0bb7f1b83e5f8f5c97bf2605a73727f3094c3aa077c88ac17f2e48dd864.jpg',
    releaseDate: '2022-03-18',
    length: 115,
    genre: 'Thriller',
    saga: '',
    description: '',
  },
  {
    title: 'Malavita',
    director: 'Luc Besson',
    actors: [
      {
        name: 'Robert De Niro',
      },
      {
        name: 'Michelle Pfeiffer',
      },
      {
        name: 'Tommy Lee Jones',
      },
    ],
    coverUrl: '/movies_pictures/21041261_20130918111051913.jpg',
    releaseDate: '2013-10-23',
    length: 111,
    genre: 'Comédie, Thriller',
    saga: '',
    description: '',
  },
  {
    title: 'La princesse de Montpensier',
    director: 'Bertrand Tavernier',
    actors: [
      {
        name: 'Mélanie Thierry',
      },
      {
        name: 'Lambert Wilson',
      },
      {
        name: 'Grégoire Leprince-Ringuet',
      },
    ],
    coverUrl: '/movies_pictures/19448509.jpg',
    releaseDate: '2010-11-03',
    length: 139,
    genre: 'Drame, Historique',
    saga: '',
    description: '',
  },
];
