import { BaseMovie } from '../../../models/movie-model';

export const baseMoviesLove: BaseMovie[] = [
  {
    title: 'Mon inconnue',
    director: 'Hugo Gélin',
    actors: [
      {
        name: 'François Civil',
      },
      {
        name: 'Joséphine Japy',
      },
    ],
    coverUrl:
      '/movies_pictures/498516-love-at-second-sight-0-150-0-225-crop.jpg',
    releaseDate: '2019-01-30',
    length: 118,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'France',
  },
  {
    title: 'The Princess Switch',
    director: 'Mike Rohl',
    actors: [
      {
        name: 'Vanessa Hudgens',
      },
    ],
    coverUrl:
      '/movies_pictures/485841-the-princess-switch-0-150-0-225-crop.jpg',
    releaseDate: '2018-11-16',
    length: 101,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Petits coups montés',
    director: 'Claire Scanlon',
    actors: [
      {
        name: 'Zoey Deutch',
      },
    ],
    coverUrl: '/movies_pictures/319550-set-it-up-0-150-0-225-crop.jpg',
    releaseDate: '2018-06-15',
    length: 105,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'The life list',
    director: 'Liz W. Garcia',
    actors: [
      {
        name: 'Katherine Heigl',
      },
    ],
    coverUrl: '/movies_pictures/1138997-the-life-list-0-150-0-225-crop.jpg',
    releaseDate: '2024-07-18',
    length: 104,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Champagne Problems',
    director: 'Mark Steven Johnson',
    actors: [
      {
        name: 'Minka Kelly',
      },
      {
        name: 'Tom Wozniczka',
      },
    ],
    coverUrl: '/movies_pictures/dce24faf4dfe1c86c2bb5ccf0f1a131f.webp',
    releaseDate: '2025-11-19',
    length: 104,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'People We Meet on Vacation',
    director: 'Brett Haley',
    actors: [
      {
        name: 'Emily Bader',
      },
      {
        name: 'Tom Blyth',
      },
    ],
    coverUrl: '/movies_pictures/people-we-meet-on-vacation-1.jpg',
    releaseDate: '2026-01-09',
    length: 118,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Tout le Bleu du Ciel',
    director: 'João Canijo',
    actors: [
      {
        name: 'Rita Blanco',
      },
    ],
    coverUrl:
      '/movies_pictures/1307347-tout-le-bleu-du-ciel-2025-0-150-0-225-crop.jpg',
    releaseDate: '2022-09-08',
    length: 127,
    genre: 'Drama',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'France',
  },
  {
    title: 'Nos coeurs meurtris',
    director: 'Elizabeth Allen Rosenbaum',
    actors: [
      {
        name: 'Sofia Carson',
      },
    ],
    coverUrl: '/movies_pictures/683195-purple-hearts-0-150-0-225-crop.jpg',
    releaseDate: '2022-07-29',
    length: 122,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Au plaisir de se faire trahir',
    director: 'Diego Freitas',
    actors: [
      {
        name: 'Giovanna Lancellotti',
      },
    ],
    coverUrl: '/movies_pictures/1060546-burning-betrayal-0-150-0-225-crop.jpg',
    releaseDate: '2023-10-25',
    length: 104,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: "La Probabilité statistique de l'amour au premier regard",
    director: 'Vanessa Caswill',
    actors: [
      {
        name: 'Haley Lu Richardson',
      },
    ],
    coverUrl: '/movies_pictures/1146306_300x450.webp',
    releaseDate: '2023-09-15',
    length: 91,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Ce sera toi',
    director: 'Alauda Ruiz de Azúa',
    actors: [
      {
        name: 'Silvia Alonso',
      },
    ],
    coverUrl: '/movies_pictures/735234-love-at-first-kiss-0-150-0-225-crop.jpg',
    releaseDate: '2023-02-10',
    length: 103,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Hello, goodbye and everything in between',
    director: 'Michael Lewen',
    actors: [
      {
        name: 'Talia Ryder',
      },
    ],
    coverUrl:
      '/movies_pictures/666928-hello-goodbye-and-everything-in-between-0-150-0-225-crop.jpg',
    releaseDate: '2022-07-06',
    length: 91,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Un Accord Parfait',
    director: 'Stuart McDonald',
    actors: [
      {
        name: 'Victoria Justice',
      },
    ],
    coverUrl: '/movies_pictures/839735-a-perfect-pairing-0-150-0-225-crop.jpg',
    releaseDate: '2022-05-19',
    length: 101,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'The In-between',
    director: 'Arie Posin',
    actors: [
      {
        name: 'Joey King',
      },
    ],
    coverUrl: '/movies_pictures/735089-the-in-between-0-150-0-225-crop.jpg',
    releaseDate: '2022-02-11',
    length: 116,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'À Travers Ma Fenêtre',
    director: 'Marçal Forés',
    actors: [
      {
        name: 'Julio Peña',
      },
    ],
    coverUrl: '/movies_pictures/735239-through-my-window-0-150-0-225-crop.jpg',
    releaseDate: '2022-02-04',
    length: 113,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Love Hard',
    director: 'Hernán Jiménez',
    actors: [
      {
        name: 'Nina Dobrev',
      },
    ],
    coverUrl: '/movies_pictures/656542-love-hard-0-150-0-225-crop.jpg',
    releaseDate: '2021-11-05',
    length: 104,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: "L'Amour complexe",
    director: 'Steven Tsuchida',
    actors: [
      {
        name: 'Christina Milian',
      },
    ],
    coverUrl: '/movies_pictures/704151-resort-to-love-0-150-0-225-crop.jpg',
    releaseDate: '2021-07-29',
    length: 101,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'La Belle et la Bête',
    director: 'Bill Condon',
    actors: [{ name: 'Emma Watson' }],
    coverUrl:
      '/movies_pictures/248708-beauty-and-the-beast-0-150-0-225-crop.jpg',
    releaseDate: '2017-03-17',
    length: 129,
    genre: 'Fantasy',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Un choix',
    director: 'Ross Katz',
    actors: [{ name: 'Benjamin Walker' }],
    coverUrl: '/movies_pictures/258147-the-choice-0-150-0-225-crop.jpg',
    releaseDate: '2016-02-05',
    length: 111,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: "L'agence",
    director: 'George Nolfi',
    actors: [{ name: 'Matt Damon' }],
    coverUrl:
      '/movies_pictures/the-adjustment-bureau-original-1-0-150-0-225-crop.jpg',
    releaseDate: '2011-03-04',
    length: 106,
    genre: 'Science Fiction',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Un jour',
    director: 'Lone Scherfig',
    actors: [{ name: 'Anne Hathaway' }],
    coverUrl: '/movies_pictures/un_jour.jpg',
    releaseDate: '2011-08-19',
    length: 107,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Sex Friends',
    director: 'Ivan Reitman',
    actors: [{ name: 'Natalie Portman' }, { name: 'Ashton Kutcher' }],
    coverUrl:
      '/movies_pictures/no-strings-attached-original-0-150-0-225-crop.jpg',
    releaseDate: '2011-01-21',
    length: 108,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Love & autres drogues',
    director: 'Edward Zwick',
    actors: [{ name: 'Jake Gyllenhaal' }, { name: 'Anne Hathaway' }],
    coverUrl: '/movies_pictures/21801-love-other-drugs-0-150-0-225-crop.jpg',
    releaseDate: '2010-11-24',
    length: 112,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Sexy Dance',
    director: 'Anne Fletcher',
    actors: [{ name: 'Channing Tatum' }],
    coverUrl: '/movies_pictures/46848-step-up-0-150-0-225-crop.jpg',
    releaseDate: '2006-08-11',
    length: 104,
    genre: 'Drama',
    saga: 'Sexy Dance',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Sexy Dance 2',
    director: 'Jon M. Chu',
    actors: [{ name: 'Briana Evigan' }],
    coverUrl: '/movies_pictures/47804-step-up-2-0-150-0-225-crop.jpg',
    releaseDate: '2008-02-14',
    length: 98,
    genre: 'Drama',
    saga: 'Sexy Dance',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Sexy Dance 3D',
    director: 'Jon M. Chu',
    actors: [{ name: 'Rick Malambri' }],
    coverUrl: '/movies_pictures/23784-step-up-3-0-150-0-225-crop.jpg',
    releaseDate: '2010-08-06',
    length: 107,
    genre: 'Drama',
    saga: 'Sexy Dance',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Sexy Dance 4 : Miami Heat',
    director: 'Scott Speer',
    actors: [
      {
        name: 'Ryan Guzman',
      },
      {
        name: 'Kathryn McCormick',
      },
      {
        name: 'Misha Gabriel Hamilton',
      },
    ],
    coverUrl: '/movies_pictures/step_up_revolution.jpg',
    releaseDate: '2012-08-08',
    length: 99,
    genre: 'Drame',
    saga: 'Sexy Dance',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: "L'Arnacœur",
    director: 'Pascal Chaumeil',
    actors: [{ name: 'Romain Duris' }],
    coverUrl: '/movies_pictures/23804-heartbreaker-0-150-0-225-crop.jpg',
    releaseDate: '2010-03-17',
    length: 105,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'France',
  },
  {
    title: 'Remember Me',
    director: 'Allen Coulter',
    actors: [{ name: 'Robert Pattinson' }],
    coverUrl: '/movies_pictures/37502-remember-me-0-150-0-225-crop.jpg',
    releaseDate: '2010-03-12',
    length: 113,
    genre: 'Drama',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: "Valentine's Day",
    director: 'Garry Marshall',
    actors: [{ name: 'Julia Roberts' }, { name: 'Anne Hathaway' }],
    coverUrl: '/movies_pictures/valentine_day.jpg',
    releaseDate: '2010-02-12',
    length: 125,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'La proposition',
    director: 'Anne Fletcher',
    actors: [{ name: 'Sandra Bullock' }, { name: 'Ryan Reynolds' }],
    coverUrl: '/movies_pictures/40479-the-proposal-0-150-0-225-crop.jpg',
    releaseDate: '2009-06-19',
    length: 108,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: '17 ans encore',
    director: 'Burr Steers',
    actors: [{ name: 'Zac Efron' }],
    coverUrl: '/movies_pictures/41276-17-again-0-150-0-225-crop.jpg',
    releaseDate: '2009-04-17',
    length: 102,
    genre: 'Comedy',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: '(500) Jours Ensemble',
    director: 'Marc Webb',
    actors: [{ name: 'Joseph Gordon-Levitt' }],
    coverUrl: '/movies_pictures/39350--500-days-of-summer-0-150-0-225-crop.jpg',
    releaseDate: '2009-07-17',
    length: 95,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Jackpot',
    director: 'Tom Vaughan',
    actors: [{ name: 'Ashton Kutcher' }],
    coverUrl:
      '/movies_pictures/47414-what-happens-in-vegas--0-150-0-225-crop.jpg',
    releaseDate: '2008-05-09',
    length: 99,
    genre: 'Comedy',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Juno',
    director: 'Jason Reitman',
    actors: [{ name: 'Ellen Page' }],
    coverUrl: '/movies_pictures/48051-juno-0-150-0-225-crop.jpg',
    releaseDate: '2007-12-25',
    length: 96,
    genre: 'Comedy',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Orgueil et Préjugés',
    director: 'Joe Wright',
    actors: [{ name: 'Keira Knightley' }],
    coverUrl: '/movies_pictures/orgueil_et_prejuges.jpg',
    releaseDate: '2005-09-16',
    length: 129,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Match Point',
    director: 'Woody Allen',
    actors: [{ name: 'Jonathan Rhys Meyers' }, { name: 'Scarlett Johansson' }],
    coverUrl: '/movies_pictures/match_point.jpg',
    releaseDate: '2005-05-12',
    length: 124,
    genre: 'Thriller',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Hitch : Expert en Séduction',
    director: 'Andy Tennant',
    actors: [
      { name: 'Will Smith' },
      { name: 'Eva Mendes' },
      { name: 'Kevin James' },
    ],
    coverUrl: '/movies_pictures/47699-hitch-0-150-0-225-crop.jpg',
    releaseDate: '2005-02-11',
    length: 118,
    genre: 'Comedy',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'First Daughter',
    director: 'Forest Whitaker',
    actors: [{ name: 'Katie Holmes' }],
    coverUrl: '/movies_pictures/43443-first-daughter-0-150-0-225-crop.jpg',
    releaseDate: '2004-09-24',
    length: 106,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Eternal Sunshine of the Spotless Mind',
    director: 'Michel Gondry',
    actors: [
      {
        name: 'Jim Carrey',
      },
      {
        name: 'Kate Winslet',
      },
      {
        name: 'Elijah Wood',
      },
      {
        name: 'Mark Ruffalo',
      },
      {
        name: 'Kirsten Dunst',
      }
    ],
    coverUrl: '/movies_pictures/eternal_sunchine_of_the_spotless_mind.jpg',
    releaseDate: '2004-03-19',
    length: 108,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'The Girl Next Door',
    director: 'Luke Greenfield',
    actors: [{ name: 'Emile Hirsch' }],
    coverUrl:
      '/movies_pictures/46081-the-girl-next-door-2004-0-150-0-225-crop.jpg',
    releaseDate: '2004-04-09',
    length: 109,
    genre: 'Comedy',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Amour & Amnésie',
    director: 'Peter Segal',
    actors: [{ name: 'Adam Sandler' }],
    coverUrl: '/movies_pictures/50773-50-first-dates-0-150-0-225-crop.jpg',
    releaseDate: '2004-02-13',
    length: 99,
    genre: 'Comedy',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Love Actually',
    director: 'Richard Curtis',
    actors: [
      { name: 'Hugh Grant' },
      { name: 'Emma Thompson' },
      { name: 'Keira Knightley' },
      { name: 'Liam Neeson' },
    ],
    coverUrl: '/movies_pictures/51602-love-actually-0-150-0-225-crop.jpg',
    releaseDate: '2003-11-07',
    length: 135,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'Royaume-Uni',
  },
  {
    title: "Le temps d'un automne",
    director: 'Adam Shankman',
    actors: [{ name: 'Mandy Moore' }],
    coverUrl: '/movies_pictures/46422-a-walk-to-remember-0-150-0-225-crop.jpg',
    releaseDate: '2002-01-25',
    length: 101,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Pearl Harbor',
    director: 'Michael Bay',
    actors: [
      { name: 'Ben Affleck' },
      { name: 'Josh Hartnett' },
      { name: 'Kate Beckinsale' },
    ],
    coverUrl: '/movies_pictures/51448-pearl-harbor-0-150-0-225-crop.jpg',
    releaseDate: '2001-05-25',
    length: 183,
    genre: 'Drama',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Ce que Veulent les Femmes',
    director: 'Nancy Meyers',
    actors: [{ name: 'Mel Gibson' }],
    coverUrl: '/movies_pictures/49539-what-women-want-0-150-0-225-crop.jpg',
    releaseDate: '2000-12-15',
    length: 127,
    genre: 'Comedy',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Coup de foudre à Notting Hill',
    director: 'Roger Michell',
    actors: [{ name: 'Julia Roberts' }],
    coverUrl: '/movies_pictures/notting-hill-0-150-0-225-crop.jpg',
    releaseDate: '1999-05-28',
    length: 124,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Rencontre avec Joe Black',
    director: 'Martin Brest',
    actors: [{ name: 'Brad Pitt' }],
    coverUrl: '/movies_pictures/51762-meet-joe-black-0-150-0-225-crop.jpg',
    releaseDate: '1998-11-13',
    length: 178,
    genre: 'Drama',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Pretty Woman',
    director: 'Garry Marshall',
    actors: [{ name: 'Julia Roberts' }],
    coverUrl: '/movies_pictures/51936-pretty-woman-0-150-0-225-crop.jpg',
    releaseDate: '1990-03-23',
    length: 119,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: "L'Amour puissance mille",
    director: 'Filip Zylber',
    actors: [
      {
        name: 'Adrianna Chlebicka',
      },
    ],
    coverUrl: '/movies_pictures/705695-squared-love-0-150-0-225-crop.jpg',
    releaseDate: '2021-02-11',
    length: 105,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'La La Land',
    director: 'Damien Chazelle',
    actors: [{ name: 'Ryan Gosling' }],
    coverUrl: '/movies_pictures/240344-la-la-land-0-150-0-225-crop.jpg',
    releaseDate: '2016-12-09',
    length: 128,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: "L'amour ouf",
    director: 'Gilles Lellouche',
    actors: [
      {
        name: 'François Civil',
      },
      {
        name: 'Adèle Exarchopoulos',
      },
    ],
    coverUrl:
      '/movies_pictures/863617-beating-hearts-2024-0-150-0-225-crop.jpg',
    releaseDate: '2024-01-31',
    length: 160,
    genre: 'Romance, Drame',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'France',
  },
  {
    title: 'The Princess Switch : Switched Again',
    director: 'Mike Rohl',
    actors: [
      {
        name: 'Vanessa Hudgens',
      },
    ],
    coverUrl:
      '/movies_pictures/569812-the-princess-switch-switched-again-0-150-0-225-crop.jpg',
    releaseDate: '2020-11-19',
    length: 97,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Holidate',
    director: 'John Whitesell',
    actors: [
      {
        name: 'Emma Roberts',
      },
    ],
    coverUrl: '/movies_pictures/542464-holidate-0-150-0-225-crop.jpg',
    releaseDate: '2020-10-28',
    length: 104,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Rich in Love',
    director: 'Bruno Garotti',
    actors: [
      {
        name: 'Maisa Silva',
      },
    ],
    coverUrl: '/movies_pictures/582011-rich-in-love-0-150-0-225-crop.jpg',
    releaseDate: '2020-06-19',
    length: 104,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Isi & Ossi',
    director: 'Oliver Kienle',
    actors: [
      {
        name: 'Lisa Vicari',
      },
    ],
    coverUrl: '/movies_pictures/584262-isi-ossi-0-150-0-225-crop.jpg',
    releaseDate: '2020-02-14',
    length: 113,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Last Christmas',
    director: 'Paul Feig',
    actors: [
      {
        name: 'Emilia Clarke',
      },
    ],
    coverUrl: '/movies_pictures/477863-last-christmas-0-150-0-225-crop.jpg',
    releaseDate: '2019-11-08',
    length: 103,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: '40 jours et 40 nuits',
    director: 'Michael Lehmann',
    actors: [{ name: 'Josh Hartnett' }],
    coverUrl: '/movies_pictures/40_jours_et_40_nuits.webp',
    releaseDate: '2002-03-01',
    length: 96,
    genre: 'Comedy',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Coup de foudre à Manhattan',
    director: 'Wayne Wang',
    actors: [
      {
        name: 'Jennifer Lopez',
      },
      {
        name: 'Ralph Fiennes',
      },
    ],
    coverUrl: '/movies_pictures/affiche_cooup_foudre.webp',
    releaseDate: '2002-12-13',
    length: 105,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Love again: un peu, beaucoup, passionnément',
    director: 'James C. Strouse',
    actors: [
      {
        name: 'Priyanka Chopra Jonas',
      },
      {
        name: 'Sam Heughan',
      },
      {
        name: 'Céline Dion',
      },
    ],
    coverUrl: '/movies_pictures/3006482.jpg',
    releaseDate: '2023-06-07',
    length: 105,
    genre: 'Romance',
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: 'États-Unis',
  },
];
