import { BaseMovie, OscarEnum } from '../../../models/movie-model';

export const baseMoviesDocumentaire: BaseMovie[] = [
  {
    title: 'Sly',
    director: 'Thom Zimny',
    actors: [
      {
        name: 'Sylvester Stallone',
      },
      {
        name: 'Arnold Schwarzenegger',
      },
      {
        name: 'Frank Stallone Jr.',
      },
      {
        name: 'Quentin Tarantino',
      },
      {
        name: 'Talia Shire',
      },
      {
        name: 'Henry Winkler',
      },
      {
        name: 'John Herzfeld',
      },
    ],
    coverUrl: '/movies_pictures/073f18caf5a23116b09d9b12d9828837.jpg',
    releaseDate: '2023-11-03',
    length: 95,
    genre: ['Documentaire'],
    saga: '',
    description: 'Portrait documentaire de Sylvester Stallone, de ses débuts difficiles à Hollywood jusqu\'à Rocky et sa carrière d\'icône de l\'action.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Magnifique désolation : marchons sur la lune',
    director: 'Mark Cowen',
    actors: [
      {
        name: 'Tom Hanks',
      },
      {
        name: 'Bill Paxton',
      },
      {
        name: 'Morgan Freeman',
      },
      {
        name: 'Scott Glenn',
      },
      {
        name: 'Paul Newman',
      },
      {
        name: 'John Travolta',
      },
      {
        name: 'Matthew McConaughey',
      },
    ],
    coverUrl: '/movies_pictures/18451313.jpg',
    releaseDate: '2005-06-03',
    length: 40,
    genre: ['Documentaire'],
    saga: '',
    description: 'Documentaire immersif retraçant les missions Apollo et les premiers pas de l\'homme sur la Lune, entre archives et reconstitutions.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Catching Fire: The Story of Anita Pallenberg',
    director: 'Alexis Bloom',
    actors: [
      {
        name: 'Anita Pallenberg',
      },
      {
        name: 'Keith Richards',
      },
      {
        name: 'Angela Richards',
      },
      {
        name: 'Marlon Richards',
      },
      {
        name: 'Marianne Faithfull',
      },
      {
        name: 'Kate Moss',
      },
      {
        name: 'Scarlett Johansson',
      },
    ],
    coverUrl: '/movies_pictures/dd3bea438c1c1e94d83d3cf36f9c4b8e.jpg',
    releaseDate: '2023-01-01',
    length: 113,
    genre: ['Documentaire'],
    saga: '',
    description: 'Portrait d\'Anita Pallenberg, muse et actrice liée aux Rolling Stones, entre rock, style et tourments des sixties.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Muganga - Celui qui soigne',
    director: 'Marie-Hélène Roux',
    actors: [
      {
        name: 'Isaach de Bankolé',
      },
      {
        name: 'Vincent Macaigne',
      },
      {
        name: 'Manon Bresch',
      },
      {
        name: 'Babetida Sadjo',
      },
      {
        name: 'Déborah Lukumuena',
      },
      {
        name: 'Joely Mbundu',
      },
      {
        name: 'Yves-Marina Gnahoua',
      },
    ],
    coverUrl: '/movies_pictures/6f60495595fe4650b54c1c4af165106c.jpg',
    releaseDate: '2025-01-01',
    length: 90,
    genre: ['Documentaire'],
    saga: '',
    description: 'Documentaire sur un médecin engagé auprès des populations vulnérables, entre vocation humanitaire et réalité du terrain.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Val',
    director: 'Ting Poo, Leo Scott',
    actors: [
      { name: 'Val Kilmer' },
      { name: 'Jack Kilmer' },
      { name: 'Mercedes Kilmer' },
      { name: 'Joanne Whalley' },
      { name: 'Tom Cruise' },
      { name: 'Robert Downey Jr.' },
      { name: 'Sean Penn' },
    ],
    coverUrl: '/movies_pictures/15bb8a3209be.jpg',
    releaseDate: '2021-08-06',
    length: 109,
    genre: ['Documentaire', 'Biographie'],
    saga: '',
    description: 'À travers des décennies d\'archives personnelles, Val Kilmer raconte sa carrière, sa maladie et sa relation à Hollywood.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Derrière nos écrans de fumée',
    director: 'Jeff Orlowski',
    actors: [
      { name: 'Tristan Harris' },
      { name: 'Jaron Lanier' },
      { name: 'Shoshana Zuboff' },
      { name: 'Justin Rosenstein' },
      { name: 'Roger McNamee' },
      { name: "Cathy O'Neil" },
      { name: 'Jeff Orlowski' },
    ],
    coverUrl:
      'https://assets.diverto.tv/media/remote/aHR0cHM6Ly9pbWFnZS50bWRiLm9yZy90L3AvL29yaWdpbmFsLy85V2JDVzJPN3g0WVdzem1hU3k5cVlIVE1hZmQuanBn?fit=contain&fm=webp&s=5c1709eda2c33844b2cdfc46df25ab1c',
    releaseDate: '2020-09-09',
    length: 94,
    genre: ['Documentaire'],
    saga: '',
    description: 'Enquête sur l\'économie de l\'attention des réseaux sociaux et la manipulation algorithmique des comportements humains.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Les Étoiles Vagabondes',
    director: 'Idriss Klait',
    actors: [
      { name: 'Nekfeu' },
      { name: 'JeanJass' },
      { name: 'Alpha Wann' },
      { name: 'Framal' },
      { name: 'Keny Arkana' },
      { name: 'Lomepal' },
      { name: 'Damso' },
    ],
    coverUrl: '/movies_pictures/70a1abfdad71.jpg',
    releaseDate: '2019-10-09',
    length: 82,
    genre: ['Documentaire'],
    saga: '',
    description: 'Documentaire sur la tournée et l\'univers de Nekfeu autour de l\'album Les Étoiles Vagabondes.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Pornhub : Gros plan sur le géant du sexe',
    director: 'Suzanne Hillinger',
    actors: [
      { name: 'Asa Akira' },
      { name: 'Siri Dahl' },
      { name: 'Cherie DeVille' },
      { name: 'Nicholas Kristof' },
      { name: 'Michael Stabile' },
      { name: 'Noelle Perdue' },
      { name: 'Wolf Hudson' },
    ],
    coverUrl:
      '/movies_pictures/6c0e44af5e26.jpg',
    releaseDate: '2023-03-15',
    length: 94,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Documentaire Netflix (Money Shot: The Pornhub Story) sur la plateforme Pornhub, ses succès et les scandales de modération du contenu.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Inside Job',
    director: 'Charles Ferguson',
    actors: [{ name: 'Matt Damon' }],
    coverUrl: '/movies_pictures/7d99c6782390.jpg',
    releaseDate: '2010-05-16',
    length: 108,
    genre: ['Documentaire'],
    saga: '',
    description: 'Analyse de la crise financière de 2008, de la dérégulation aux conflits d\'intérêts qui ont mené à l\'effondrement mondial.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2011 }],
  },
  {
    title: "Nanouk l'Esquimau",
    director: 'Robert J. Flaherty',
    actors: [
      { name: 'Allakariallak' },
      { name: 'Nyla' },
      { name: 'Cunayou' },
      { name: 'Allee' },
      { name: 'Allegoo' },
    ],
    coverUrl: '/movies_pictures/e08db181bfd6.jpg',
    releaseDate: '1922-06-11',
    length: 79,
    genre: ['Documentaire'],
    saga: '',
    description:
      "La vie quotidienne d'une famille inuit dans l'Arctique canadien, filmée comme un récit de survie.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "L'Homme à la caméra",
    director: 'Dziga Vertov',
    actors: [{ name: 'Mikhail Kaufman' }, { name: 'Elizaveta Svilova' }],
    coverUrl: '/movies_pictures/d0aad8a9aef4.jpg',
    releaseDate: '1929-01-08',
    length: 68,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Une journée dans une ville soviétique, filmée comme un manifeste du cinéma-œil, sans intertitres ni fiction.',
    fromEntity: null,
    countryOrigin: ['Russie'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Nuit et Brouillard',
    director: 'Alain Resnais',
    actors: [{ name: 'Michel Bouquet' }],
    coverUrl: '/movies_pictures/1716703f6d04.jpg',
    releaseDate: '1956-01-01',
    length: 32,
    genre: ['Documentaire', 'Historique'],
    saga: '',
    description:
      'Court métrage sur les camps nazis : le présent en couleur, les archives en noir et blanc, texte de Cayrol.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Monde du silence',
    director: 'Jacques-Yves Cousteau, Louis Malle',
    actors: [
      { name: 'Jacques-Yves Cousteau' },
      { name: 'François Saout' },
      { name: 'Frédéric Dumas' },
      { name: 'Albert Falco' },
    ],
    coverUrl: '/movies_pictures/le-monde-du-silence.jpg',
    releaseDate: '1956-05-26',
    length: 86,
    genre: ['Documentaire'],
    saga: '',
    description:
      'À bord de la Calypso, Cousteau filme les fonds marins en couleur, dauphins, épaves et chasse sous-marine.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 1957 }],
  },
  {
    title: 'Woodstock',
    director: 'Michael Wadleigh',
    actors: [
      { name: 'Jimi Hendrix' },
      { name: 'Joan Baez' },
      { name: 'The Who' },
      { name: 'Santana' },
      { name: 'Joe Cocker' },
    ],
    coverUrl:
      '/movies_pictures/4cd2604ef78a.jpg',
    releaseDate: '1970-03-26',
    length: 184,
    genre: ['Documentaire', 'Comédie musicale'],
    saga: '',
    description:
      "Trois jours de concert dans l'État de New York : boue, foule, Hendrix et The Star-Spangled Banner.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 1971 }],
  },
  {
    title: 'La Dernière Valse',
    director: 'Martin Scorsese',
    actors: [
      { name: 'The Band' },
      { name: 'Robbie Robertson' },
      { name: 'Rick Danko' },
      { name: 'Levon Helm' },
      { name: 'Bob Dylan' },
    ],
    coverUrl:
      '/movies_pictures/b942a2c2b87e.jpg',
    releaseDate: '1978-04-26',
    length: 117,
    genre: ['Documentaire', 'Comédie musicale'],
    saga: '',
    description:
      'Le dernier concert de The Band à San Francisco, invités, plans et adieux filmés par Scorsese.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Microcosmos : Le peuple de l'herbe",
    director: 'Claude Nuridsany',
    actors: [{ name: 'Kristin Scott Thomas' }, { name: 'Jacques Perrin' }],
    coverUrl: '/movies_pictures/6c470b323ba4.jpg',
    releaseDate: '1996-09-06',
    length: 80,
    genre: ['Documentaire'],
    saga: '',
    description: 'Plongée macroscopique dans la vie des insectes d\'une prairie, filmée comme une épopée miniature.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Larissa : L'autre facette d'Anitta",
    director: 'João Wainer',
    actors: [
      { name: 'Anitta' },
      { name: 'Larissa de Macedo Machado' },
      { name: 'João Wainer' },
      { name: 'Alessandro Oliveira' },
      { name: 'Viktor Chalup' },
      { name: 'Thiago Martins' },
      { name: 'Marília Mendonça' },
    ],
    coverUrl: '/movies_pictures/aef384c0be68.jpg',
    releaseDate: '2022-06-16',
    length: 91,
    genre: ['Documentaire'],
    saga: '',
    description: 'Portrait de la star brésilienne Anitta, entre succès international, identité et face plus intime de l\'artiste.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'J. K. Rowling : La Magie des mots',
    director: 'Paul A. Kaufman',
    actors: [
      { name: 'Poppy Montgomery' },
      { name: 'Emily Holmes' },
      { name: 'Antonio Cupo' },
      { name: 'Liz Alexander' },
      { name: 'Janet Wright' },
      { name: "John O'Callaghan" },
      { name: 'Hughier Ladines' },
    ],
    coverUrl: '/movies_pictures/2e283e1dad0a.jpg',
    releaseDate: '2011-07-18',
    length: 90,
    genre: ['Documentaire'],
    saga: '',
    description: 'Documentaire sur J. K. Rowling et la genèse de Harry Potter, de l\'écriture à l\'engouement mondial.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'This Is It',
    director: 'Kenny Ortega',
    actors: [
      { name: 'Michael Jackson' },
      { name: 'Orianthi' },
      { name: 'Kenny Ortega' },
      { name: 'Prince Jackson' },
      { name: 'Paris Jackson' },
      { name: 'Blanket Jackson' },
      { name: 'Travis Payne' },
    ],
    coverUrl: '/movies_pictures/8e22c390055a.jpg',
    releaseDate: '2009-10-28',
    length: 111,
    genre: ['Documentaire', 'Comédie musicale'],
    saga: '',
    description: 'Film construit à partir des répétitions de Michael Jackson pour sa série de concerts This Is It, interrompue par sa mort.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "Interstellar: Nolan's Odyssey",
    director: 'Dan Storey',
    actors: [
      { name: 'Matthew McConaughey' },
      { name: 'Christopher Nolan' },
      { name: 'Emma Thomas' },
      { name: 'Anne Hathaway' },
      { name: 'Jessica Chastain' },
      { name: 'Michael Caine' },
      { name: 'Hans Zimmer' },
    ],
    coverUrl: '/movies_pictures/94f242d80752.jpg',
    releaseDate: '2014-11-07',
    length: 52,
    genre: ['Documentaire'],
    saga: '',
    description: 'Making-of d\'Interstellar : Christopher Nolan, l\'équipe et les scientifiques derrière le voyage spatial du film.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: "La Marche de l'empereur",
    director: 'Luc Jacquet',
    actors: [
      { name: 'Charles Berling' },
      { name: 'Romane Bohringer' },
      { name: 'Jules Sitruk' },
      { name: 'Morgan Freeman' },
      { name: 'Isabelle Monnart' },
      { name: 'Hugues Pellerin' },
      { name: 'Luc Jacquet' },
    ],
    coverUrl: '/movies_pictures/07f22a8f32d5.jpg',
    releaseDate: '2005-02-02',
    length: 80,
    genre: ['Documentaire'],
    saga: '',
    description: 'Sur la banquise antarctique, le cycle de vie des manchots empereurs, entre migration, reproduction et survie.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2006 },
    ],
  },
  {
    title: 'Océans',
    director: 'Jacques Perrin',
    actors: [{ name: 'Jacques Perrin' }, { name: 'Pierce Brosnan' }],
    coverUrl: '/movies_pictures/12d3fcf4a486.jpg',
    releaseDate: '2010-01-27',
    length: 104,
    genre: ['Documentaire'],
    saga: '',
    description: 'Ode visuelle aux océans et à leurs habitants, filmée à travers le monde pour révéler la beauté et la fragilité du milieu marin.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Home',
    director: 'Yann Arthus-Bertrand',
    actors: [
      { name: 'Glenn Close' },
      { name: 'Jacques Gamblin' },
      { name: 'Salma Hayek' },
    ],
    coverUrl: '/movies_pictures/72c98da21da2.jpg',
    releaseDate: '2009-06-05',
    length: 120,
    genre: ['Documentaire'],
    saga: '',
    description: 'Survol de la planète et alerte écologique sur l\'impact de l\'humanité sur les écosystèmes, narré par Yann Arthus-Bertrand.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Bowling for Columbine',
    director: 'Michael Moore',
    actors: [
      { name: 'Michael Moore' },
      { name: 'Charlton Heston' },
      { name: 'Marilyn Manson' },
      { name: 'Matt Stone' },
    ],
    coverUrl: '/movies_pictures/e73a06b8eed0.jpg',
    releaseDate: '2002-10-09',
    length: 120,
    genre: ['Documentaire'],
    saga: '',
    description: 'Michael Moore interroge la culture des armes aux États-Unis à partir de la fusillade de Columbine.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2003 },
    ],
  },
  {
    title: 'Stop Making Sense',
    director: 'Jonathan Demme',
    actors: [
      { name: 'David Byrne' },
      { name: 'Tina Weymouth' },
      { name: 'Chris Frantz' },
      { name: 'Jerry Harrison' },
      { name: 'Bernie Worrell' },
    ],
    coverUrl:
      '/movies_pictures/c80e43e162ca.jpg',
    releaseDate: '1984-04-24',
    length: 88,
    genre: ['Documentaire', 'Comédie musicale'],
    saga: '',
    description:
      'Talking Heads en concert à Hollywood, Byrne en grand costume, lampadaire et once in a lifetime.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Shoah',
    director: 'Claude Lanzmann',
    actors: [
      { name: 'Claude Lanzmann' },
      { name: 'Simon Srebnik' },
      { name: 'Mordechaï Podchlebnik' },
      { name: 'Abraham Bomba' },
      { name: 'Franz Suchomel' },
    ],
    coverUrl:
      'https://www.yadvashem.org/sites/default/files/styles/main_image_1block/public/shoah-poster.jpg?itok=REFku4xW',
    releaseDate: '1985-04-30',
    length: 566,
    genre: ['Documentaire', 'Historique'],
    saga: '',
    description:
      "Neuf heures de témoignages, sans archives, sur l'extermination, rails, barbier de Treblinka, villages polonais.",
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Paris Is Burning',
    director: 'Jennie Livingston',
    actors: [
      { name: 'Pepper LaBeija' },
      { name: 'Dorian Corey' },
      { name: 'Angie Xtravaganza' },
      { name: 'Willi Ninja' },
      { name: 'Venus Xtravaganza' },
    ],
    coverUrl:
      '/movies_pictures/80ee1c2215ff.jpg',
    releaseDate: '1991-03-13',
    length: 78,
    genre: ['Documentaire'],
    saga: '',
    description:
      "Les balls de Harlem, houses, voguing : une communauté trans et gay se filme avant l'épidémie.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Le Peuple migrateur',
    director: 'Jacques Perrin',
    actors: [{ name: 'Jacques Perrin' }, { name: 'Philippe Labro' }],
    coverUrl:
      '/movies_pictures/10197fa675af.jpg',
    releaseDate: '2001-12-12',
    length: 89,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Des oiseaux migrateurs filmés à leur hauteur, ailes, vent, presque pas de commentaire.',
    fromEntity: null,
    countryOrigin: ['France', 'Allemagne', 'Italie', 'Espagne'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Être et avoir',
    director: 'Nicolas Philibert',
    actors: [{ name: 'Georges Lopez' }],
    coverUrl:
      '/movies_pictures/56d1af999aea.jpg',
    releaseDate: '2002-08-28',
    length: 104,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Une année dans une classe unique de campagne française, où un instituteur accompagne ses élèves vers le collège.',
    fromEntity: null,
    countryOrigin: ['France'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Fahrenheit 9/11',
    director: 'Michael Moore',
    actors: [
      { name: 'Michael Moore' },
      { name: 'George W. Bush' },
      { name: 'Donald Rumsfeld' },
      { name: 'Britney Spears' },
      { name: 'Ben Affleck' },
    ],
    coverUrl:
      'https://img.festival-cannes.com/eyJidWNrZXQiOiJtZWRpYSIsImtleSI6InVwbG9hZHNcLzIwMjNcLzAzXC8xOTU1Ny5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjE2MDAsImZpdCI6ImNvdmVyIn19fQ==',
    releaseDate: '2004-06-25',
    length: 122,
    genre: ['Documentaire'],
    saga: '',
    description:
      "Pamphlet de Michael Moore sur George W. Bush, le 11-Septembre et la guerre en Irak.",
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Super Size Me',
    director: 'Morgan Spurlock',
    actors: [
      { name: 'Morgan Spurlock' },
      { name: 'Alexandra Jamieson' },
      { name: 'Daryl Isaacs' },
      { name: 'Lisa Ganjhu' },
      { name: 'Stephen Siegel' },
    ],
    coverUrl:
      '/movies_pictures/1dda743d3c86.jpg',
    releaseDate: '2004-05-07',
    length: 100,
    genre: ['Documentaire', 'Comédie'],
    saga: '',
    description:
      'Morgan Spurlock se nourrit exclusivement de McDonald\'s pendant 30 jours pour mesurer les effets sur sa santé.',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [],
  },
  {
    title: 'Une vérité qui dérange',
    director: 'Davis Guggenheim',
    actors: [
      { name: 'Al Gore' },
      { name: 'Billy West' },
      { name: 'George Bush' },
      { name: 'Ronald Reagan' },
      { name: 'George Bush Sr.' },
    ],
    coverUrl: '/movies_pictures/957044bd6cba.jpg',
    releaseDate: '2006-05-24',
    length: 96,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Al Gore présente les enjeux du réchauffement climatique à travers conférences, données et appels à l\'action.',
    fromEntity: {
      entityType: 'book',
      title: 'An Inconvenient Truth',
      secondEntityKey: 'Al Gore',
    },
    countryOrigin: ['États-Unis'],
    selectDisplayOrder: 0,
    oscars: [
      { type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2007 },
      { type: OscarEnum.OSCAR_BEST_ORIGINAL_SONG, year: 2007 },
    ],
  },
  {
    title: 'Man on Wire',
    director: 'James Marsh',
    actors: [
      { name: 'Philippe Petit' },
      { name: 'Jean-Louis Blondeau' },
      { name: 'Annie Allix' },
      { name: 'Jean-François Heckel' },
      { name: 'Barry Greenhouse' },
    ],
    coverUrl: '/movies_pictures/483b709caf63.jpg',
    releaseDate: '2008-07-25',
    length: 94,
    genre: ['Documentaire'],
    saga: '',
    description:
      'Retour sur le funambulisme illégal de Philippe Petit entre les tours du World Trade Center en 1974.',
    fromEntity: {
      entityType: 'book',
      title: 'To Reach the Clouds',
      secondEntityKey: 'Philippe Petit',
    },
    countryOrigin: ['Royaume-Uni'],
    selectDisplayOrder: 0,
    oscars: [{ type: OscarEnum.OSCAR_BEST_DOCUMENTARY, year: 2009 }],
  },
];
