import { BaseMovie } from '../../../models/movie-model';

export const baseMoviesAnimated2: BaseMovie[] = [
  {
    title: 'Luca',
    director: 'Enrico Casarosa',
    actors: [{ name: 'Jacob Tremblay' }, { name: 'Jack Dylan Grazer' }],
    coverUrl: '/movies_pictures/2021-luca-01-big.jpg',
    releaseDate: '2021-06-18',
    length: 95,
    genre: ['Animation', 'Aventure'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Blanche-Neige et les Sept Nains',
    director: 'David Hand',
    actors: [{ name: 'Adriana Caselotti' }, { name: 'Lucille La Verne' }],
    coverUrl: '/movies_pictures/19681823.webp',
    releaseDate: '1937-12-21',
    length: 83,
    genre: ['Animation', 'Fantastique'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Cendrillon',
    director: 'Clyde Geronimi, Wilfred Jackson',
    actors: [{ name: 'Ilene Woods' }, { name: 'Eleanor Audley' }],
    coverUrl: '/movies_pictures/18429571.webp',
    releaseDate: '1950-02-15',
    length: 74,
    genre: ['Animation', 'Romance'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Pierre et le Loup',
    director: 'Clyde Geronimi',
    actors: [{ name: 'Sterling Holloway' }, { name: 'Ivan' }],
    coverUrl: '/movies_pictures/pierre-et-le-loup-1946-a.webp',
    releaseDate: '1946-08-15',
    length: 15,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Les Trois Caballeros',
    director: 'Norman Ferguson, Clyde Geronimi',
    actors: [{ name: 'Clarence Nash' }, { name: 'José Oliveira' }],
    coverUrl:
      '/movies_pictures/Les-3-caballeros-sort-en-franceles-trois-caballeros-.webp',
    releaseDate: '1944-12-21',
    length: 71,
    genre: ['Animation', 'Comédie musicale'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Saludos Amigos',
    director: 'Wilfred Jackson, Jack Kinney',
    actors: [{ name: 'Clarence Nash' }, { name: 'José Oliveira' }],
    coverUrl:
      '/movies_pictures/MV5BODc5ZjlhODYtMjFmMS00NGNhLTgxOTAtNjBhMDJkNzU5ZmVmXkEyXkFqcGc@._V1_.jpg',
    releaseDate: '1942-02-06',
    length: 42,
    genre: ['Animation', 'Comédie musicale'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Bambi',
    director: 'David Hand',
    actors: [{ name: 'Donnie Dunagan' }, { name: 'Hardie Albright' }],
    coverUrl: '/movies_pictures/Bambi_-_Affiche_VOD.webp',
    releaseDate: '1942-08-21',
    length: 70,
    genre: ['Animation', 'Drame'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Dumbo',
    director: 'Ben Sharpsteen',
    actors: [{ name: 'Edward Brophy' }, { name: 'Sterling Holloway' }],
    coverUrl: '/movies_pictures/2034393.webp',
    releaseDate: '1941-10-23',
    length: 64,
    genre: ['Animation', 'Jeunesse'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Fantasia',
    director: 'James Algar, Samuel Armstrong',
    actors: [
      {
        name: 'Deems Taylor',
      },
      {
        name: 'Leopold Stokowski',
      },
    ],
    coverUrl: '/movies_pictures/71MQJ6N1H9L._AC_UF894,1000_QL80_.jpg',
    releaseDate: '1940-11-13',
    length: 124,
    genre: ['Animation', 'Comédie musicale'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Alice au pays des merveilles',
    director: 'Clyde Geronimi, Wilfred Jackson',
    actors: [{ name: 'Kathryn Beaumont' }, { name: 'Ed Wynn' }],
    coverUrl: '/movies_pictures/2165756.webp',
    releaseDate: '1951-07-26',
    length: 75,
    genre: ['Animation', 'Fantastique'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'La Belle au bois dormant',
    director: 'Clyde Geronimi',
    actors: [{ name: 'Mary Costa' }, { name: 'Eleanor Audley' }],
    coverUrl: '/movies_pictures/6_9782014632682_1_75.jpg',
    releaseDate: '1959-01-29',
    length: 75,
    genre: ['Animation', 'Fantastique'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'La Belle et le Clochard',
    director: 'Clyde Geronimi, Wilfred Jackson',
    actors: [{ name: 'Barbara Luddy' }, { name: 'Larry Roberts' }],
    coverUrl: '/movies_pictures/18798038.jpg',
    releaseDate: '1955-06-22',
    length: 76,
    genre: ['Animation', 'Romance'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le Livre de la jungle',
    director: 'Wolfgang Reitherman',
    actors: [{ name: 'Phil Harris' }, { name: 'Bruce Reitherman' }],
    coverUrl: '/movies_pictures/91Tkd1W6MZL._AC_UF1000,1000_QL80_.jpg',
    releaseDate: '1967-10-18',
    length: 78,
    genre: ['Animation', 'Aventure'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Nausicaä de la Vallée du Vent',
    director: 'Hayao Miyazaki',
    actors: [{ name: 'Sumi Shimamoto' }, { name: 'Mahito Tsujimura' }],
    coverUrl: '/movies_pictures/18651925.jpg',
    releaseDate: '1984-03-11',
    length: 117,
    genre: ['Animation', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['Japon'],
  },
  {
    title: 'Le Château dans le ciel',
    director: 'Hayao Miyazaki',
    actors: [{ name: 'Mayumi Tanaka' }, { name: 'Keiko Yokozawa' }],
    coverUrl: '/movies_pictures/affiche (2).webp',
    releaseDate: '1986-08-02',
    length: 125,
    genre: ['Animation', 'Aventure'],
    saga: 'Ghibli',
    description: '',
    fromEntity: null,
    countryOrigin: ['Japon'],
  },
  {
    title: 'Oliver et Compagnie',
    director: 'George Scribner',
    actors: [{ name: 'Joey Lawrence' }, { name: 'Billy Joel' }],
    coverUrl: '/movies_pictures/Oliver29.webp',
    releaseDate: '1988-11-18',
    length: 74,
    genre: ['Animation', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le Tombeau des lucioles',
    director: 'Isao Takahata',
    actors: [
      {
        name: 'Tsutomu Tatsumi',
      },
      {
        name: 'Ayano Shiraishi',
      },
    ],
    coverUrl: '/movies_pictures/19079741.webp',
    releaseDate: '1988-04-16',
    length: 89,
    genre: ['Animation', 'Guerre'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['Japon'],
  },
  {
    title: 'Mon voisin Totoro',
    director: 'Hayao Miyazaki',
    actors: [
      {
        name: 'Noriko Hidaka',
      },
      {
        name: 'Chika Sakamoto',
      },
    ],
    coverUrl: '/movies_pictures/my_neighbor_totoro.jpg',
    releaseDate: '2002-08-28',
    length: 87,
    genre: ['Animation'],
    saga: 'Ghibli',
    description: '',
    fromEntity: null,
    countryOrigin: ['Japon'],
  },
  {
    title: 'Kiki la petite sorcière',
    director: 'Hayao Miyazaki',
    actors: [{ name: 'Minami Takayama' }, { name: 'Rei Sakuma' }],
    coverUrl: '/movies_pictures/4332138.jpg',
    releaseDate: '1989-07-29',
    length: 103,
    genre: ['Animation', 'Fantastique'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['Japon'],
  },
  {
    title: "L'Étrange Noël de monsieur Jack",
    director: 'Henry Selick',
    actors: [{ name: 'Chris Sarandon' }, { name: "Catherine O'Hara" }],
    coverUrl: '/movies_pictures/18923316.webp',
    releaseDate: '1993-10-29',
    length: 76,
    genre: ['Animation', 'Fantastique'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le retour de Jafar',
    director: 'Toby Shelton, Tad Stones',
    actors: [{ name: 'Scott Weinger' }, { name: 'Gilbert Gottfried' }],
    coverUrl: '/movies_pictures/LeRetourDeJafar.webp',
    releaseDate: '1994-05-20',
    length: 69,
    genre: ['Animation', 'Fantastique'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le Bossu de Notre-Dame',
    director: 'Gary Trousdale, Kirk Wise',
    actors: [{ name: 'Tom Hulce' }, { name: 'Demi Moore' }],
    coverUrl: '/movies_pictures/21011147_20130607174439608.jpg',
    releaseDate: '1996-06-21',
    length: 91,
    genre: ['Animation', 'Comédie musicale'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'James et la Pêche géante',
    director: 'Henry Selick',
    actors: [{ name: 'Paul Terry' }, { name: 'Joanna Lumley' }],
    coverUrl: '/movies_pictures/James_et_La_P3Fante.webp',
    releaseDate: '1996-04-12',
    length: 79,
    genre: ['Animation', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Les 101 Dalmatiens',
    director: 'Stephen Herek',
    actors: [{ name: 'Glenn Close' }, { name: 'Jeff Daniels' }],
    coverUrl: '/movies_pictures/20193459.jpg',
    releaseDate: '1996-11-27',
    length: 103,
    genre: ['Jeunesse', 'Comédie'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Anastasia',
    director: 'Don Bluth, Gary Goldman',
    actors: [{ name: 'Meg Ryan' }, { name: 'John Cusack' }],
    coverUrl: '/movies_pictures/anastasia-a-375x500.jpg',
    releaseDate: '1997-11-21',
    length: 94,
    genre: ['Animation', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le Monde magique de la Belle et la Bête',
    director: 'Bob Kline',
    actors: [{ name: "Paige O'Hara" }, { name: 'Robby Benson' }],
    coverUrl: '/movies_pictures/144274.webp',
    releaseDate: '1998-02-17',
    length: 92,
    genre: ['Animation', 'Fantastique'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: "Le Prince d'Égypte",
    director: 'Brenda Chapman, Steve Hickner',
    actors: [{ name: 'Val Kilmer' }, { name: 'Ralph Fiennes' }],
    coverUrl: '/movies_pictures/le-prince-degypte-a-350x500.jpg',
    releaseDate: '1998-12-18',
    length: 99,
    genre: ['Animation', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: '1001 Pattes',
    director: 'John Lasseter, Andrew Stanton',
    actors: [{ name: 'Dave Foley' }, { name: 'Julia Louis-Dreyfus' }],
    coverUrl: '/movies_pictures/1001-pattes-a.webp',
    releaseDate: '1998-11-25',
    length: 95,
    genre: ['Animation', 'Aventure'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: "Le Roi Lion 2 : L'Honneur de la tribu",
    director: 'Darrell Rooney, Rob LaDuca',
    actors: [{ name: 'Matthew Broderick' }, { name: 'Neve Campbell' }],
    coverUrl: '/movies_pictures/Leroilion2dvd.webp',
    releaseDate: '1998-11-24',
    length: 81,
    genre: ['Animation', 'Comédie musicale'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Pocahontas 2 : Un monde nouveau',
    director: 'Tom Ellery, Bradley Raymond',
    actors: [{ name: 'Irene Bedard' }, { name: 'Billy Zane' }],
    coverUrl: '/movies_pictures/Pocahontas_2.webp',
    releaseDate: '1998-05-05',
    length: 72,
    genre: ['Animation', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Dinosaure',
    director: 'Ralph Zondag, Eric Leighton',
    actors: [{ name: 'D.B. Sweeney' }, { name: 'Alfre Woodard' }],
    coverUrl: '/movies_pictures/dinosaure-a.webp',
    releaseDate: '2000-05-19',
    length: 82,
    genre: ['Animation', 'Aventure'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: "La Route d'Eldorado",
    director: 'Bibo Bergeron, Don Paul',
    actors: [{ name: 'Kevin Kline' }, { name: 'Kenneth Branagh' }],
    coverUrl: '/movies_pictures/5772692.jpg',
    releaseDate: '2000-03-31',
    length: 89,
    genre: ['Animation', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: "La Petite Sirène 2 : Retour à l'océan",
    director: 'Jim Kammerud, Brian Smith',
    actors: [{ name: 'Tara Strong' }, { name: 'Jodi Benson' }],
    coverUrl: '/movies_pictures/2000-sirene2-1.jpg',
    releaseDate: '2000-09-19',
    length: 75,
    genre: ['Animation', 'Jeunesse'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Fantasia 2000',
    director: 'James Algar, Gaëtan Brizzi',
    actors: [{ name: 'Steve Martin' }, { name: 'James Earl Jones' }],
    coverUrl: '/movies_pictures/Fantasia_2000.webp',
    releaseDate: '1999-12-17',
    length: 75,
    genre: ['Animation', 'Comédie musicale'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Chicken Run',
    director: 'Peter Lord, Nick Park',
    actors: [{ name: 'Julia Sawalha' }, { name: 'Mel Gibson' }],
    coverUrl: '/movies_pictures/1516243.jpg',
    releaseDate: '2000-06-23',
    length: 84,
    genre: ['Animation', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: "Kuzco, l'Empereur mégalo",
    director: 'Mark Dindal',
    actors: [{ name: 'David Spade' }, { name: 'John Goodman' }],
    coverUrl: '/movies_pictures/69197626_af.webp',
    releaseDate: '2000-12-15',
    length: 78,
    genre: ['Animation', 'Comédie'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: "Atlantis : L'Empire perdu",
    director: 'Gary Trousdale, Kirk Wise',
    actors: [{ name: 'Michael J. Fox' }, { name: 'Cree Summer' }],
    coverUrl: '/movies_pictures/510VvOPQrTL._AC_UF894,1000_QL80_.jpg',
    releaseDate: '2001-06-15',
    length: 96,
    genre: ['Animation', 'Aventure'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le Voyage de Chihiro',
    director: 'Hayao Miyazaki',
    actors: [{ name: 'Rumi Hiiragi' }, { name: 'Miyu Irino' }],
    coverUrl: '/movies_pictures/chihiro.webp',
    releaseDate: '2001-07-20',
    length: 125,
    genre: ['Animation', 'Fantastique'],
    saga: 'Ghibli',
    description: '',
    fromEntity: null,
    countryOrigin: ['Japon'],
  },
  {
    title: 'Le Royaume des chats',
    director: 'Hiroyuki Morita',
    actors: [{ name: 'Chizuru Ikewaki' }, { name: 'Yoshihiko Hakamada' }],
    coverUrl: '/movies_pictures/affiche.jpg',
    releaseDate: '2002-07-19',
    length: 75,
    genre: ['Animation', 'Fantastique'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Lilo et Stitch',
    director: 'Dean DeBlois, Chris Sanders',
    actors: [{ name: 'Daveigh Chase' }, { name: 'Chris Sanders' }],
    coverUrl: '/movies_pictures/unnamed.png',
    releaseDate: '2002-06-21',
    length: 85,
    genre: ['Animation', 'Comédie'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'La Planète au trésor',
    director: 'Ron Clements, John Musker',
    actors: [
      {
        name: 'Joseph Gordon-Levitt',
      },
      {
        name: 'Brian Murray',
      },
    ],
    coverUrl: '/movies_pictures/affiche2.jpg',
    releaseDate: '2002-11-27',
    length: 95,
    genre: ['Animation', 'Aventure'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: {
      entityType: 'book',
      title: "L'Île au trésor",
      secondEntityKey: 'Robert Louis Stevenson',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Frère des ours',
    director: 'Aaron Blaise, Robert Walker',
    actors: [{ name: 'Joaquin Phoenix' }, { name: 'Jeremy Suarez' }],
    coverUrl: '/movies_pictures/41mQjxrMetL._AC_UF1000,1000_QL80_.jpg',
    releaseDate: '2003-10-24',
    length: 85,
    genre: ['Animation', 'Aventure'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Mickey, Donald, Dingo : Les Trois Mousquetaires',
    director: 'Donovan Cook',
    actors: [{ name: 'Wayne Allwine' }, { name: 'Tony Anselmo' }],
    coverUrl:
      '/movies_pictures/Mickey_Donald_Dingo_Les_Trois_Mousquetaires.webp',
    releaseDate: '2004-08-17',
    length: 68,
    genre: ['Animation', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Mulan 2',
    director: 'Darrell Rooney, Lynne Southerland',
    actors: [{ name: 'Ming-Na Wen' }, { name: 'BD Wong' }],
    coverUrl: '/movies_pictures/71lTDe9zAnL.jpg',
    releaseDate: '2004-11-03',
    length: 79,
    genre: ['Animation', 'Jeunesse'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Les Noces funèbres',
    director: 'Tim Burton, Mike Johnson',
    actors: [
      {
        name: 'Johnny Depp',
      },
      {
        name: 'Helena Bonham Carter',
      },
    ],
    coverUrl: '/movies_pictures/corpse_bride.jpg',
    releaseDate: '2005-10-19',
    length: 76,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Madagascar',
    director: 'Eric Darnell, Tom McGrath',
    actors: [{ name: 'Ben Stiller' }, { name: 'Chris Rock' }],
    coverUrl: '/movies_pictures/aa1eztisz2rquk2qiugu1pxchrm-003.jpg',
    releaseDate: '2005-05-27',
    length: 86,
    genre: ['Animation', 'Aventure'],
    saga: 'Madagascar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Happy Feet',
    director: 'George Miller',
    actors: [{ name: 'Elijah Wood' }, { name: 'Brittany Murphy' }],
    coverUrl:
      '/movies_pictures/MV5BNjViZDZhNjctM2MwOS00MDdhLWIwMTYtNjNmNGY2OGMzZWZhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    releaseDate: '2006-11-17',
    length: 108,
    genre: ['Animation', 'Comédie musicale'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Bolt',
    director: 'Chris Williams, Byron Howard',
    actors: [{ name: 'John Travolta' }, { name: 'Miley Cyrus' }],
    coverUrl: '/movies_pictures/61gYdYv0eQL._AC_UF1000,1000_QL80_.jpg',
    releaseDate: '2008-11-21',
    length: 96,
    genre: ['Animation', 'Aventure'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Madagascar 2',
    director: 'Eric Darnell, Tom McGrath',
    actors: [{ name: 'Ben Stiller' }, { name: 'Chris Rock' }],
    coverUrl: '/movies_pictures/18995214.jpg',
    releaseDate: '2008-11-07',
    length: 89,
    genre: ['Animation', 'Comédie'],
    saga: 'Madagascar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: "Madagascar 3 : Bons Baisers d'Europe",
    director: 'Eric Darnell, Tom McGrath, Conrad Vernon',
    actors: [
      {
        name: 'Ben Stiller',
      },
      {
        name: 'Chris Rock',
      },
      {
        name: 'David Schwimmer',
      },
    ],
    coverUrl: '/movies_pictures/madagascar_3_europe_s_most_wanted.jpg',
    releaseDate: '2012-06-06',
    length: 93,
    genre: ['Animation'],
    saga: 'Madagascar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Ponyo',
    director: 'Hayao Miyazaki',
    actors: [{ name: 'Yuria Nara' }, { name: 'Hiroki Doi' }],
    coverUrl: '/movies_pictures/Ponyo_sur_la_falaise.webp',
    releaseDate: '2008-07-19',
    length: 101,
    genre: ['Animation', 'Fantastique'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['Japon'],
  },
  {
    title: 'Là-haut',
    director: 'Pete Docter',
    actors: [{ name: 'Edward Asner' }, { name: 'Jordan Nagai' }],
    coverUrl: '/movies_pictures/Lahaut.webp',
    releaseDate: '2009-05-29',
    length: 96,
    genre: ['Animation', 'Aventure'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Coraline',
    director: 'Henry Selick',
    actors: [{ name: 'Dakota Fanning' }, { name: 'Teri Hatcher' }],
    coverUrl: '/movies_pictures/81j25nie1TL._AC_UF1000,1000_QL80_.jpg',
    releaseDate: '2009-02-06',
    length: 100,
    genre: ['Animation', 'Fantastique'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Arrietty, le petit monde des chapardeurs',
    director: 'Hiromasa Yonebayashi',
    actors: [
      {
        name: 'Mirai Shida',
      },
      {
        name: 'Ryunosuke Kamiki',
      },
    ],
    coverUrl: '/movies_pictures/19597854.webp',
    releaseDate: '2010-07-17',
    length: 94,
    genre: ['Animation', 'Fantastique'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['Japon'],
  },
  {
    title: 'Rio',
    director: 'Carlos Saldanha',
    actors: [{ name: 'Jesse Eisenberg' }, { name: 'Anne Hathaway' }],
    coverUrl: '/movies_pictures/19699752.webp',
    releaseDate: '2011-04-15',
    length: 96,
    genre: ['Animation', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Rango',
    director: 'Gore Verbinski',
    actors: [{ name: 'Johnny Depp' }, { name: 'Isla Fisher' }],
    coverUrl: '/movies_pictures/19678966.jpg',
    releaseDate: '2011-03-04',
    length: 107,
    genre: ['Animation', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Raiponce',
    director: 'Byron Howard, Nathan Greno',
    actors: [
      {
        name: 'Anne Hathaway',
      },
      {
        name: 'Jim Sturgess',
      },
      {
        name: 'Patricia Clarkson',
      },
    ],
    coverUrl: '/movies_pictures/tangled.jpg',
    releaseDate: '2010-12-01',
    length: 101,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Kung Fu Panda',
    director: 'Mark Osborne, John Stevenson',
    actors: [{ name: 'Jack Black' }],
    coverUrl:
      '/movies_pictures/mk3UyyaLyXhgIhmLji25OUPXvGR-0-150-0-225-crop.jpg',
    releaseDate: '2008-06-06',
    length: 92,
    genre: ['Animation'],
    saga: 'Kung Fu Panda',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Kung Fu Panda 2',
    director: 'Jennifer Yuh Nelson',
    actors: [{ name: 'Jack Black' }, { name: 'Angelina Jolie' }],
    coverUrl: '/movies_pictures/19723216.webp',
    releaseDate: '2011-05-26',
    length: 90,
    genre: ['Animation', 'Action'],
    saga: 'Kung Fu Panda',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Kung Fu Panda 3',
    director: 'Jennifer Yuh Nelson, Alessandro Carloni',
    actors: [
      {
        name: 'Jack Black',
      },
      {
        name: 'Angelina Jolie',
      },
      {
        name: 'Dustin Hoffman',
      },
    ],
    coverUrl: '/movies_pictures/kung_fu_panda_3.jpg',
    releaseDate: '2016-03-30',
    length: 95,
    genre: ['Animation'],
    saga: 'Kung Fu Panda',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Kung Fu Panda 4',
    director: 'Mike Mitchell, Stephanie Ma Stine',
    actors: [
      {
        name: 'Jack Black',
      },
      {
        name: 'Awkwafina',
      },
      {
        name: 'Viola Davis',
      },
      {
        name: 'Dustin Hoffman',
      },
      {
        name: 'James Hong',
      },
    ],
    coverUrl: '/movies_pictures/kung_fu_panda_4.jpg',
    releaseDate: '2024-01-01',
    length: 94,
    genre: ['Animation'],
    saga: 'Kung Fu Panda',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Le Chat Potté',
    director: 'Chris Miller',
    actors: [{ name: 'Antonio Banderas' }, { name: 'Salma Hayek' }],
    coverUrl: '/movies_pictures/19830353.webp',
    releaseDate: '2011-10-28',
    length: 90,
    genre: ['Animation', 'Aventure'],
    saga: 'Shrek',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Hôtel Transylvanie',
    director: 'Genndy Tartakovsky',
    actors: [{ name: 'Adam Sandler' }, { name: 'Selena Gomez' }],
    coverUrl: '/movies_pictures/20366411.webp',
    releaseDate: '2012-09-28',
    length: 91,
    genre: ['Animation', 'Comédie'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Monsters University',
    director: 'Dan Scanlon',
    actors: [{ name: 'Billy Crystal' }, { name: 'John Goodman' }],
    coverUrl: '/movies_pictures/Monsters_University_poster_3.jpg',
    releaseDate: '2013-06-21',
    length: 104,
    genre: ['Animation', 'Comédie'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'The Lego Movie',
    director: 'Phil Lord, Christopher Miller',
    actors: [
      {
        name: 'Chris Pratt',
      },
      {
        name: 'Elizabeth Banks',
      },
    ],
    coverUrl: '/movies_pictures/The_Lego_Movie_poster.jpg',
    releaseDate: '2014-02-07',
    length: 100,
    genre: ['Animation', 'Aventure'],
    saga: 'Lego',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Lego Batman',
      secondEntityKey: 'Warner',
    },
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Zootopie',
    director: 'Byron Howard, Rich Moore',
    actors: [{ name: 'Ginnifer Goodwin' }, { name: 'Jason Bateman' }],
    coverUrl: '/movies_pictures/280851.jpg',
    releaseDate: '2016-03-04',
    length: 108,
    genre: ['Animation', 'Aventure'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Zootopie 2',
    director: 'Jared Bush, Byron Howard',
    actors: [
      {
        name: 'Ginnifer Goodwin',
      },
      {
        name: 'Jason Bateman',
      },
      {
        name: 'Shakira',
      },
      {
        name: 'Idris Elba',
      },
      {
        name: 'Alan Tudyk',
      },
    ],
    coverUrl: '/movies_pictures/zootopie_2.jpg',
    releaseDate: '2025-11-26',
    length: 108,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Piper',
    director: 'Alan Barillaro',
    actors: [{ name: 'Piper' }, { name: 'Maman bécasseau' }],
    coverUrl: '/movies_pictures/piper-a.webp',
    releaseDate: '2016-06-16',
    length: 6,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'La Reine des neiges 2',
    director: 'Chris Buck, Jennifer Lee',
    actors: [{ name: 'Idina Menzel' }, { name: 'Kristen Bell' }],
    coverUrl: '/movies_pictures/5952325.jpg',
    releaseDate: '2019-11-22',
    length: 103,
    genre: ['Animation', 'Fantastique'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Klaus',
    director: 'Sergio Pablos',
    actors: [{ name: 'Jason Schwartzman' }, { name: 'J.K. Simmons' }],
    coverUrl: '/movies_pictures/4323300.webp',
    releaseDate: '2019-11-15',
    length: 96,
    genre: ['Animation', 'Aventure'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['Espagne'],
  },
  {
    title: 'Le Chat Potté 2 : La Dernière Quête',
    director: 'Joel Crawford',
    actors: [
      {
        name: 'Antonio Banderas',
      },
    ],
    coverUrl:
      '/movies_pictures/242285-puss-in-boots-the-last-wish-0-150-0-225-crop.jpg',
    releaseDate: '2022-12-21',
    length: 102,
    genre: ['Animation'],
    saga: 'Shrek',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Coco',
    director: 'Lee Unkrich',
    actors: [{ name: 'Anthony Gonzalez' }],
    coverUrl: '/movies_pictures/cb8e1f58155a.jpeg',
    releaseDate: '2017-11-22',
    length: 105,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Bubble',
    director: 'Tetsurō Araki',
    actors: [{ name: 'Inconnu' }],
    coverUrl: '/movies_pictures/bubble-affiche.jpg',
    releaseDate: '2022-04-28',
    length: 100,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['Japon'],
  },
  {
    title: 'Vice-Versa 2',
    director: 'Kelsey Mann',
    actors: [{ name: 'Amy Poehler' }, { name: 'Maya Hawke' }],
    coverUrl: '/movies_pictures/f54c3310f101fe8ae4bba9e566bca1b5.jpg',
    releaseDate: '2024-06-14',
    length: 96,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Arco',
    director: 'Ugo Bienvenu',
    actors: [
      {
        name: 'Margot Ringard Oldra',
      },
      {
        name: 'Oscar Tresanini',
      },
    ],
    coverUrl: '/movies_pictures/4bb40b414c1d86022f4031676a309432.webp',
    releaseDate: '2025-10-22',
    length: 89,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['France'],
  },
  {
    title: 'KPop Demon Hunters',
    director: 'Maggie Kang, Chris Appelhans',
    actors: [
      {
        name: 'Arden Cho',
      },
      {
        name: 'May Hong',
      },
      {
        name: 'Ahn Hyo-seop',
      },
      {
        name: 'Ji-young Yoo',
      },
    ],
    coverUrl: '/movies_pictures/kpop-demon-hunters.jpg',
    releaseDate: '2025-06-20',
    length: 95,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Soul',
    director: 'Pete Docter, Kemp Powers',
    actors: [
      {
        name: 'Jamie Foxx',
      },
      {
        name: 'Tina Fey',
      },
      {
        name: 'Graham Norton',
      },
    ],
    coverUrl: '/movies_pictures/soul.jpg',
    releaseDate: '2020-12-25',
    length: 100,
    genre: ['Animation'],
    saga: 'Pixar',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Nimona',
    director: 'Nick Bruno, Troy Quane',
    actors: [
      {
        name: 'Chloë Grace Moretz',
      },
      {
        name: 'Riz Ahmed',
      },
      {
        name: 'Eugene Lee Yang',
      },
      {
        name: 'Frances Conroy',
      },
      {
        name: 'Beck Bennett',
      },
    ],
    coverUrl: '/movies_pictures/nimona.jpg',
    releaseDate: '2023-06-30',
    length: 101,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Les Trolls',
    director: 'Mike Mitchell, Walt Dohrn',
    actors: [
      {
        name: 'Anna Kendrick',
      },
      {
        name: 'Justin Timberlake',
      },
      {
        name: 'Zooey Deschanel',
      },
    ],
    coverUrl: '/movies_pictures/trolls.jpg',
    releaseDate: '2016-10-19',
    length: 92,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Dragon Ball : Salut ! Son Goku et ses amis sont de retour !!',
    director: ' Yoshihiro Ueda',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Ryō Horikawa',
      },
      {
        name: 'Mayumi Tanaka',
      },
      {
        name: 'Toshio Furukawa',
      },
    ],
    coverUrl: '/movies_pictures/fa9c940df3c7.jpg',
    releaseDate: '2008-09-21',
    length: 35,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z : La Menace de Namek',
    director: 'Mitsuo Hashimoto',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Toshio Furukawa',
      },
      {
        name: 'Mayumi Tanaka',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_lord_slug.jpg',
    releaseDate: '1994-09-01',
    length: 52,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z : Le Père de Sangoku',
    director: 'Mitsuo Hashimoto',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Ryûsei Nakao',
      },
      {
        name: 'Shō Hayami',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_bardock_the_father_of_goku.jpg',
    releaseDate: '1990-10-17',
    length: 48,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z: The Tree of Might',
    director: 'Daisuke Nishio',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Mayumi Tanaka',
      },
      {
        name: 'Tōru Furuya',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_the_tree_of_might.jpg',
    releaseDate: '1990-07-07',
    length: 61,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: "Dragon Ball Z : L'Attaque du dragon",
    director: 'Mitsuo Hashimoto',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Takeshi Kusao',
      },
      {
        name: 'Mayumi Tanaka',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_wrath_of_the_dragon.jpg',
    releaseDate: '1995-10-31',
    length: 51,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z : Fusions',
    director: 'Shigeyasu Yamauchi',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Ryô Horikawa',
      },
      {
        name: 'Takeshi Kusao',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_fusion_reborn.jpg',
    releaseDate: '1995-03-04',
    length: 51,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z : Bio-Broly',
    director: 'Yoshihiro Ueda',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Takeshi Kusao',
      },
      {
        name: 'Daisuke Gôri',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_bio_broly.jpg',
    releaseDate: '1994-07-09',
    length: 46,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z : Rivaux dangereux',
    director: 'Shigeyasu Yamauchi',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Takeshi Kusao',
      },
      {
        name: 'Yūko Minaguchi',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_broly_second_coming.jpg',
    releaseDate: '1994-03-12',
    length: 52,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z: Bojack Unbound',
    director: 'Yoshihiro Ueda',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Tesshō Genda',
      },
      {
        name: 'Ryō Horikawa',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_bojack_unbound.jpg',
    releaseDate: '1993-07-10',
    length: 51,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z : Broly le super guerrier',
    director: 'Shigeyasu Yamauchi',
    actors: [
      {
        name: 'Bin Shimada',
      },
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Ryō Horikawa',
      },
    ],
    coverUrl:
      '/movies_pictures/dragon_ball_z_broly_the_legendary_super_saiyan.jpg',
    releaseDate: '1993-03-06',
    length: 72,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: "Dragon Ball Z : L'Histoire de Trunks",
    director: 'Yoshihiro Ueda',
    actors: [
      {
        name: 'Takeshi Kusao',
      },
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Hiromi Tsuru',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_the_history_of_trunks.jpg',
    releaseDate: '1995-03-22',
    length: 47,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: "Dragon Ball Z : L'Offensive des cyborgs",
    director: 'Kazuhito Kikuchi',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Ryō Horikawa',
      },
      {
        name: 'Takeshi Kusao',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_super_android_13.jpg',
    releaseDate: '1992-07-11',
    length: 46,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z : Cent Mille Guerriers de métal',
    director: 'Daisuke Nishio',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Ryô Horikawa',
      },
      {
        name: 'Toshio Furukawa',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_the_return_of_cooler.jpg',
    releaseDate: '1992-03-07',
    length: 44,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z : La Revanche de Cooler',
    director: 'Mitsuo Hashimoto',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Ryūsei Nakao',
      },
      {
        name: 'Toshio Furukawa',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_cooler_s_revenge.jpg',
    releaseDate: '1994-12-01',
    length: 48,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z : Le Robot des glaces',
    director: 'Daisuke Nishio',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Toshio Furukawa',
      },
      {
        name: 'Hiromi Tsuru',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_the_world_s_strongest.jpg',
    releaseDate: '1994-10-17',
    length: 59,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z : À la poursuite de Garlic',
    director: 'Daisuke Nishio',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Toshio Furukawa',
      },
      {
        name: 'Mayumi Tanaka',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_dead_zone.jpg',
    releaseDate: '1989-07-15',
    length: 41,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Z: Battle of Gods',
    director: 'Masahiro Hosoda',
    actors: [],
    coverUrl: '/movies_pictures/dragon_ball_z_battle_of_gods.jpg',
    releaseDate: '2015-02-11',
    length: 85,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: "Dragon Ball Z : La Résurrection de 'F'",
    director: 'Tadayoshi Yamamuro',
    actors: [
      {
        name: 'Masako Nozawa',
      },
      {
        name: 'Ryo Horikawa',
      },
      {
        name: 'Toshio Furukawa',
      },
    ],
    coverUrl: '/movies_pictures/dragon_ball_z_resurrection_f.jpg',
    releaseDate: '2015-09-11',
    length: 94,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Super: Broly',
    director: 'Tatsuya Nagamine',
    actors: [{ name: 'Masako Nozawa' }, { name: 'Bin Shimada' }],
    coverUrl:
      '/movies_pictures/d040d049d297.jpg',
    releaseDate: '2018-12-14',
    length: 100,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Dragon Ball Super: Super Hero',
    director: 'Tetsuro Kodama',
    actors: [{ name: 'Masako Nozawa' }, { name: 'Toshio Furukawa' }],
    coverUrl: '/movies_pictures/909f22973c8a.jpg',
    releaseDate: '2022-06-11',
    length: 100,
    genre: ['Animation'],
    saga: 'Dragon Ball',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Dragon Ball',
      secondEntityKey: 'Akira Toriyama',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Akira',
    director: 'Katsuhiro Ōtomo',
    actors: [
      {
        name: 'Mitsuo Iwata',
      },
      {
        name: 'Nozomu Sasaki',
      },
      {
        name: 'Mami Koyama',
      },
    ],
    coverUrl: '/movies_pictures/akira.jpg',
    releaseDate: '1991-05-08',
    length: 124,
    genre: ['Science Fiction', 'Animation'],
    saga: '',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'AKIRA',
      secondEntityKey: 'Katsuhiro Otomo',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Astérix et les Indiens',
    director: 'Gerhard Hahn',
    actors: [
      {
        name: 'Roger Carel',
      },
      {
        name: 'Pierre Tornade',
      },
      {
        name: 'Henri Labussière',
      },
    ],
    coverUrl: '/movies_pictures/asterix_conquers_america.jpg',
    releaseDate: '1995-04-05',
    length: 85,
    genre: ['Animation'],
    saga: 'Astérix',
    description: '',
    fromEntity: {
      entityType: 'bd',
      title: 'Astérix le Gaulois',
      secondEntityKey: 'René Goscinny',
    },
    countryOrigin: ['France'],
  },
  {
    title: 'Le Livre de la jungle',
    director: 'Wolfgang Reitherman',
    actors: [
      {
        name: 'Phil Harris',
      },
      {
        name: 'Bruce Reitherman',
      },
    ],
    coverUrl: '/movies_pictures/the_jungle_book.jpg',
    releaseDate: '1968-12-11',
    length: 78,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'La Belle au bois dormant',
    director: 'Clyde Geronimi',
    actors: [
      {
        name: 'Mary Costa',
      },
      {
        name: 'Eleanor Audley',
      },
    ],
    coverUrl: '/movies_pictures/sleeping_beauty.jpg',
    releaseDate: '1959-12-16',
    length: 75,
    genre: ['Animation'],
    saga: 'Disney Classique',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },
  {
    title: 'Astérix et Cléopâtre',
    director: 'René Goscinny, Albert Uderzo',
    actors: [
      {
        name: 'Roger Carel',
      },
      {
        name: 'Jacques Morel',
      },
      {
        name: 'Micheline Dax',
      },
    ],
    coverUrl: '/movies_pictures/asterix_and_cleopatra.jpg',
    releaseDate: '1968-12-19',
    length: 72,
    genre: ['Animation'],
    saga: 'Astérix',
    description: '',
    fromEntity: {
      entityType: 'bd',
      title: 'Astérix et Cléopâtre',
      secondEntityKey: 'René Goscinny',
    },
    countryOrigin: ['France'],
  },
  {
    title: 'Un monstre à Paris',
    director: 'Bibo Bergeron',
    actors: [
      {
        name: 'Mathieu Chedid',
      },
      {
        name: 'Vanessa Paradis',
      },
      {
        name: 'Gad Elmaleh',
      },
    ],
    coverUrl: '/movies_pictures/a_monster_in_paris.jpg',
    releaseDate: '2011-10-12',
    length: 82,
    genre: ['Animation'],
    saga: '',
    description: '',
    fromEntity: null,
    countryOrigin: ['États-Unis'],
  },

  // --- Films Pokémon (saga cinéma, liés au catalogue jeux)
  {
    title: 'Pokémon, le film : Mewtwo contre-attaque',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/8756a2016129.jpg',
    releaseDate: '1998-07-18',
    length: 75,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Bleu',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon 2 : Le Pouvoir est en toi',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/f190b035e25d.jpg',
    releaseDate: '1999-07-17',
    length: 64,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Or',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon 3 : Le Sort des Zarbi',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/673bd9391efc.jpg',
    releaseDate: '2000-07-08',
    length: 74,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Or',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon 4 : Pokémon 4Ever',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/dcbad61a4769.jpg',
    releaseDate: '2001-07-07',
    length: 75,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Cristal',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon Heroes',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/53e70e6311c7.png',
    releaseDate: '2002-07-13',
    length: 72,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Rubis',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon : Jirachi, le génie des vœux',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/406592dbd685.jpg',
    releaseDate: '2003-07-19',
    length: 81,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Rubis',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon : La destinée de Deoxys',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/e40ce2160487.jpg',
    releaseDate: '2004-07-17',
    length: 98,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Rubis',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon : Lucario et le mystère de Mew',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/4d4b10dc9855.jpg',
    releaseDate: '2005-07-16',
    length: 100,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Émeraude',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon Ranger et le temple des mers',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/a1970869d25f.jpg',
    releaseDate: '2006-07-15',
    length: 107,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Bleu',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: "Pokémon : L'ascension de Darkrai",
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/c398b773a7fb.jpg',
    releaseDate: '2007-07-14',
    length: 90,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Diamant',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon : Giratina et le gardien du ciel',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/53f5ce0c7b4d.jpg',
    releaseDate: '2008-07-19',
    length: 96,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Platine',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon : Arceus et le joyau de vie',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/c48190a5e6ad.jpg',
    releaseDate: '2009-07-18',
    length: 94,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Platine',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon : Zoroark, le maître des illusions',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/8b7ca3fc7d34.jpg',
    releaseDate: '2010-07-10',
    length: 95,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Noir',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon, le film : Noir — Victini et Reshiram',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/35c1ee9c1b3d.jpg',
    releaseDate: '2011-07-16',
    length: 96,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Noir',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon, le film : Blanc — Victini et Zekrom',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl:
      'https://play-lh.googleusercontent.com/nO-AHDmgaPRvdL-ApuvpgjuCbrFT1Zbafm4B-s7SCb2lvZCJkZaOdj77d2HfYACqCIc',
    releaseDate: '2011-07-16',
    length: 96,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Blanc',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon : Kyurem contre la lame de la justice',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/2023f666c65c.jpg',
    releaseDate: '2012-07-14',
    length: 72,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Noir 2',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: "Pokémon : Genesect et l'éveil de la légende",
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/1c04241b1708.jpg',
    releaseDate: '2013-07-13',
    length: 72,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon X',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon : Diancie et le cocon destructeur',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/d715670f57a3.jpg',
    releaseDate: '2014-07-19',
    length: 75,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon X',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon : Hoopa et le choc des légendes',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/b955b1450386.jpg',
    releaseDate: '2015-07-18',
    length: 79,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Rubis Oméga',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon : Volcanion et la merveille mécanique',
    director: 'Kunihiko Yuyama',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/3f82405032c2.jpg',
    releaseDate: '2016-07-16',
    length: 95,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Soleil',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon, le film : Je te choisis !',
    director: 'Tetsuo Yajima',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/602598bde748.jpg',
    releaseDate: '2017-07-15',
    length: 97,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Soleil',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon, le film : Le pouvoir est en nous',
    director: 'Tetsuo Yajima',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/e193eb40be1c.jpeg',
    releaseDate: '2018-07-13',
    length: 97,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Soleil',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Mewtwo contre-attaque : Évolution',
    director: 'Kunihiko Yuyama, Motonari Sakakibara',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/eb9328344cf6.png',
    releaseDate: '2019-07-12',
    length: 98,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Bleu',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon, le film : Les secrets de la jungle',
    director: 'Tetsuo Yajima',
    actors: [{ name: 'Rica Matsumoto' }, { name: 'Ikue Ôtani' }],
    coverUrl: '/movies_pictures/b5e82e9904ef.jpg',
    releaseDate: '2020-12-25',
    length: 99,
    genre: ['Animation', 'Aventure', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Épée',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Pokémon : Détective Pikachu',
    director: 'Rob Letterman',
    actors: [{ name: 'Justice Smith' }, { name: 'Ryan Reynolds' }],
    coverUrl:
      '/movies_pictures/38e2acd94658.jpg',
    releaseDate: '2019-05-03',
    length: 104,
    genre: ['Action', 'Fantastique', 'Jeunesse'],
    saga: 'Pokémon',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Pokémon Bleu',
      secondEntityKey: 'Game Freak',
    },
    countryOrigin: ['États-Unis'],
  },
  // --- Films Yu-Gi-Oh! (animation)
  {
    title: 'Yu-Gi-Oh! (film, 1999)',
    director: 'Junji Shimizu',
    actors: [{ name: 'Inconnu' }],
    coverUrl:
      '/movies_pictures/69c15cfca883.webp',
    releaseDate: '1999-03-06',
    length: 30,
    genre: ['Animation', 'Action', 'Aventure'],
    saga: 'Yu-Gi-Oh!',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Yu-Gi-Oh!',
      secondEntityKey: 'Kazuki Takahashi',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Yu-Gi-Oh! : La pyramide de lumière',
    director: 'Hatsuki Tsuji',
    actors: [{ name: 'Inconnu' }],
    coverUrl:
      '/movies_pictures/33a69d09f5bd.jpg',
    releaseDate: '2004-11-03',
    length: 90,
    genre: ['Animation', 'Action', 'Aventure'],
    saga: 'Yu-Gi-Oh!',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Yu-Gi-Oh!',
      secondEntityKey: 'Kazuki Takahashi',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Yu-Gi-Oh! 3D : Bonds Beyond Time',
    director: 'Satoshi Kuwabara',
    actors: [{ name: 'Inconnu' }],
    coverUrl:
      '/movies_pictures/5acb3ce87c6a.jpg',
    releaseDate: '2010-01-23',
    length: 50,
    genre: ['Animation', 'Action', 'Aventure'],
    saga: 'Yu-Gi-Oh!',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Yu-Gi-Oh!',
      secondEntityKey: 'Kazuki Takahashi',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Yu-Gi-Oh! : The Dark Side of Dimensions',
    director: 'Satoshi Kuwabara',
    actors: [{ name: 'Inconnu' }],
    coverUrl:
      '/movies_pictures/94db5ace3c3e.jpg',
    releaseDate: '2016-04-23',
    length: 130,
    genre: ['Animation', 'Action', 'Aventure'],
    saga: 'Yu-Gi-Oh!',
    description: '',
    fromEntity: {
      entityType: 'manga',
      title: 'Yu-Gi-Oh!',
      secondEntityKey: 'Kazuki Takahashi',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Street Fighter II : The Animated Movie',
    director: 'Gisaburo Sugii',
    actors: [{ name: 'Kōji Tsujitani' }, { name: 'Tesshō Genda' }],
    coverUrl:
      '/movies_pictures/876330af9cbb.jpg',
    releaseDate: '1994-08-08',
    length: 94,
    genre: ['Animation', 'Action'],
    saga: 'Street Fighter',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Street Fighter / Fighting Street',
      secondEntityKey: 'Capcom',
    },
    countryOrigin: ['Japon'],
  },
  {
    title: 'Tekken: Blood Vengeance',
    director: 'Yoichi Mouri',
    actors: [{ name: 'Mamoru Miyano' }, { name: 'Yuki Matsuoka' }],
    coverUrl: '/movies_pictures/d431debdb14e.jpg',
    releaseDate: '2011-07-26',
    length: 100,
    genre: ['Animation', 'Action'],
    saga: 'Tekken',
    description: '',
    fromEntity: {
      entityType: 'game',
      title: 'Tekken',
      secondEntityKey: 'Bandai Namco',
    },
    countryOrigin: ['Japon'],
  },
];
