import { UserBooks } from '../../../../models/book-model';

export const ronanReadListBooks: UserBooks = [
  {
    title: 'Les Hauts de Hurlevent',
    author: 'Emily Brontë',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Voyage au centre de la terre',
    author: 'Jules Verne',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Le tour du monde en 80 jours',
    author: 'Jules Verne',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Vingt Mille Lieues sous les mers',
    author: 'Jules Verne',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "L'Île mystérieuse",
    author: 'Jules Verne',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'De la Terre à la Lune',
    author: 'Jules Verne',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Le Portrait de Dorian Gray',
    author: 'Oscar Wilde',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'La Ferme des animaux',
    author: 'George Orwell',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Orgueil et Préjugés',
    author: 'Jane Austen',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: '1984',
    author: 'George Orwell',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Fondation',
    author: 'Isaac Asimov',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Dracula',
    author: 'Bram Stoker',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Carrie',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Désolation',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Gatsby le magnifique',
    author: 'F. Scott Fitzgerald',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'La guerre des mondes',
    author: 'H.G. Wells',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'La machine à explorer le temps',
    author: 'H.G. Wells',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "L'homme invisible",
    author: 'H.G. Wells',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Alchemised',
    author: 'SenLinYu',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "L'Odyssée",
    author: 'Homère',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "L'Iliade",
    author: 'Homère',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Là où chantent les écrevisses',
    author: 'Delia Owens',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Les sortceliers',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Le livre interdit',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Le sceptre maudit',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Le dragon renégat',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Le continent interdit',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Dans le piège de Magister',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "Tara Duncan et l'invasion fantôme",
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "L'impératrice maléfique",
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Tara Duncan contre la reine noire',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Dragons contre Démons',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'La Guerre des planètes',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "L'Ultime Combat",
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Tara et Cal',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "Le Trône de fer, L'Intégrale Tome 1",
    author: 'George R.R. Martin',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "Le Trône de fer, L'Intégrale Tome 2",
    author: 'George R.R. Martin',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "Le Trône de fer, L'Intégrale Tome 3",
    author: 'George R.R. Martin',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Hunger Games',
    author: 'Suzanne Collins',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "L'Embrasement",
    author: 'Suzanne Collins',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'La Révolte',
    author: 'Suzanne Collins',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "La Ballade du serpent et de l'oiseau chanteur",
    author: 'Suzanne Collins',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Lever de soleil sur la moisson',
    author: 'Suzanne Collins',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Le Calice des dieux',
    author: 'Rick Riordan',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Le Labyrinthe',
    author: 'James Dashner',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Player One',
    author: 'Ernest Cline',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Ready Player Two',
    author: 'Ernest Cline',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Les secrets de la femme de ménage',
    author: 'Freida McFadden',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'La femme de ménage se marie',
    author: 'Freida McFadden',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'La femme de ménage voit tout',
    author: 'Freida McFadden',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Les Trois Mousquetaires',
    author: 'Alexandre Dumas',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Les filles du Docteur March',
    author: 'Louisa May Alcott',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Dark Shores',
    author: 'Danielle L. Jensen',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Notre-Dame de Paris',
    author: 'Victor Hugo',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Le vicomte de Bragelonne',
    author: 'Alexandre Dumas',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'La reine Margot',
    author: 'Alexandre Dumas',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "Le Trône de fer, L'Intégrale Tome 4",
    author: 'George R.R. Martin',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "Le Trône de fer, L'Intégrale Tome 5",
    author: 'George R.R. Martin',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Le Parfum',
    author: 'Patrick Süskind',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Cinq semaines en ballon',
    author: 'Jules Verne',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Autour de la Lune',
    author: 'Jules Verne',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'The Dead zone',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Gagner la guerre',
    author: 'Jean-Philippe Jaworski',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Le Nom du Vent',
    author: 'Patrick Rothfuss',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'La Peur du Sage (2/2)',
    author: 'Patrick Rothfuss',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'La Peur du Sage (1/2)',
    author: 'Patrick Rothfuss',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "L'étranger",
    author: 'Albert Camus',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Hamlet',
    author: 'William Shakespeare',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Macbeth',
    author: 'William Shakespeare',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
];
