import { UserMovie } from '../../../../models/movie-model';

export const emmanuelleMovies: UserMovie[] = [
  {
    title: 'Top Gun : Maverick',
    director: 'Joseph Kosinski',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Tanguy',
    director: 'Étienne Chatiliez',
    rating: 3.5,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Gladiator',
    director: 'Ridley Scott',
    rating: 4.5,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Le Comte de Monte-Cristo',
    director: 'Alexandre de La Patellière, Matthieu Delaporte',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Le silence des agneaux',
    director: 'Jonathan Demme',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Les Choristes',
    director: 'Christophe Barratier',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'A Star Is Born',
    director: 'Bradley Cooper',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'E.T. the Extra-Terrestrial',
    director: 'Steven Spielberg',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: "L'aile ou la cuisse",
    director: 'Claude Zidi',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'American Beauty',
    director: 'Sam Mendes',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'À la Recherche du Bonheur',
    director: 'Gabriele Muccino',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: "Le Diable s'Habille en Prada",
    director: 'David Frankel',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title:
      "Le Monde de Narnia : Le Lion, la Sorcière Blanche et l'Armoire Magique",
    director: 'Andrew Adamson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Mr. & Mrs. Smith',
    director: 'Doug Liman',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Leon',
    director: 'Luc Besson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Forrest Gump',
    director: 'Robert Zemeckis',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Le Dîner de Cons',
    director: 'Francis Veber',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Cinquante Nuances de Grey',
    director: 'Sam Taylor-Johnson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Dirty Dancing',
    director: 'Emile Ardolino',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Jumanji',
    director: 'Joe Johnston',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Seven',
    director: 'David Fincher',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Un indien dans la ville',
    director: 'Hervé Palud',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },

  {
    title: 'Black Swan',
    director: 'Darren Aronofsky',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
];
