import { BaseGame } from '../../../models/game-model';

export const baseGames: BaseGame[] = [
  // The Legend of Zelda
  {
    title: 'The Legend of Zelda: Ocarina of Time',
    editor: 'Nintendo',
    hero: 'Link',
    coverUrl: '/games_pictures/oot.jpg',
    releaseDate: '1998-11-21',
    averageTimeToFinish: 101,
    platform: 'Nintendo 64',
    saga: 'The Legend of Zelda',
  },
  {
    title: 'The Legend of Zelda: The Wind Waker',
    editor: 'Nintendo',
    hero: 'Link',
    coverUrl:
      '/games_pictures/MV5BOWFhZGZmMDctYjFmNC00YzQzLWE5ODktYTBhNmE1MmRiZTM4XkEyXkFqcGc@._V1_.jpg',
    releaseDate: '2002-12-13',
    averageTimeToFinish: 95,
    platform: 'GameCube',
    saga: 'The Legend of Zelda',
  },
  {
    title: 'The Legend of Zelda: Twilight Princess',
    editor: 'Nintendo',
    hero: 'Link',
    coverUrl:
      '/games_pictures/The_Legend_of_Zelda_Twilight_Princess_Game_Cover.jpg',
    releaseDate: '2006-11-19',
    averageTimeToFinish: 120,
    platform: 'Wii',
    saga: 'The Legend of Zelda',
  },
  {
    title: 'The Legend of Zelda: Skyward Sword',
    editor: 'Nintendo',
    hero: 'Link',
    coverUrl:
      '/games_pictures/MV5BOGMxMDRjMzUtN2FiYS00ZmFlLWJmM2ItY2VhY2RiMDdhNzViXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    releaseDate: '2011-11-18',
    averageTimeToFinish: 110,
    platform: 'Wii',
    saga: 'The Legend of Zelda',
  },
  {
    title: 'The Legend of Zelda: Breath of the Wild',
    editor: 'Nintendo',
    hero: 'Link',
    coverUrl: '/games_pictures/40519.jpg',
    releaseDate: '2017-03-03',
    averageTimeToFinish: 150,
    platform: 'Nintendo Switch',
    saga: 'The Legend of Zelda',
  },
  {
    title: 'The Legend of Zelda: A Link to the Past',
    editor: 'Nintendo',
    hero: 'Link',
    coverUrl: '/games_pictures/mixcollage-23-dec-2024-08-34-am-8166.avif',
    releaseDate: '1991-11-21',
    averageTimeToFinish: 45,
    platform: 'SNES',
    saga: 'The Legend of Zelda',
  },
  {
    title: "The Legend of Zelda: Link's Awakening",
    editor: 'Nintendo',
    hero: 'Link',
    coverUrl:
      '/games_pictures/MV5BZjg2MzY1ZDItOTUzNS00MTVjLTkyZTktMzVjMmM1NTZkMDdiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    releaseDate: '1993-06-06',
    averageTimeToFinish: 35,
    platform: 'Game Boy',
    saga: 'The Legend of Zelda',
  },
  {
    title: 'The Legend of Zelda: Oracle of Seasons',
    editor: 'Nintendo',
    hero: 'Link',
    coverUrl:
      '/games_pictures/10039_The_Legend_of_Zelda_Oracle_of_Seasons.webp',
    releaseDate: '2001-02-27',
    averageTimeToFinish: 40,
    platform: 'Game Boy Color',
    saga: 'The Legend of Zelda',
  },
  {
    title: 'The Legend of Zelda: Oracle of Ages',
    editor: 'Nintendo',
    hero: 'Link',
    coverUrl: '/games_pictures/10038_The_Legend_of_Zelda_Oracle_of_Ages.webp',
    releaseDate: '2001-02-27',
    averageTimeToFinish: 40,
    platform: 'Game Boy Color',
    saga: 'The Legend of Zelda',
  },
  {
    title: 'The Legend of Zelda: The Minish Cap',
    editor: 'Nintendo',
    hero: 'Link',
    coverUrl:
      '/games_pictures/MV5BODlmOTk0MzQtYzI1MS00MzYzLThiYTctNjFkOTY4ZDA1NDllXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    releaseDate: '2004-11-04',
    averageTimeToFinish: 50,
    platform: 'Game Boy Advance',
    saga: 'The Legend of Zelda',
  },
  // Call of Duty
  {
    title: 'Call of Duty 4: Modern Warfare',
    editor: 'Infinity Ward',
    hero: 'Captain Price',
    coverUrl: '/games_pictures/cod4pc0f.webp',
    releaseDate: '2007-11-05',
    averageTimeToFinish: 10,
    platform: 'PlayStation 3',
    saga: 'Call of Duty',
  },
  {
    title: 'Call of Duty: World at War',
    editor: 'Treyarch',
    hero: 'Captain Price',
    coverUrl: '/games_pictures/WAW_Cover_Art.jpg',
    releaseDate: '2008-11-11',
    averageTimeToFinish: 30,
    platform: 'PlayStation 3',
    saga: 'Call of Duty',
  },
  {
    title: 'Call of Duty: Modern Warfare 2',
    editor: 'Infinity Ward',
    hero: 'Captain Price',
    coverUrl: '/games_pictures/Call_of_Duty_Modern_Warfare_2_(2009)_cover.png',
    releaseDate: '2009-11-10',
    averageTimeToFinish: 15,
    platform: 'PlayStation 3',
    saga: 'Call of Duty',
  },
  {
    title: 'Call of Duty: Black Ops',
    editor: 'Treyarch',
    hero: 'Captain Price',
    coverUrl: '/games_pictures/CoD_Black_Ops_cover.png',
    releaseDate: '2010-11-09',
    averageTimeToFinish: 25,
    platform: 'PlayStation 3',
    saga: 'Call of Duty',
  },
  {
    title: 'Call of Duty: Modern Warfare 3',
    editor: 'Infinity Ward',
    hero: 'Captain Price',
    coverUrl:
      '/games_pictures/call-of-duty-modern-warfare-3_cover_original.webp',
    releaseDate: '2011-11-08',
    averageTimeToFinish: 60,
    platform: 'PlayStation 3',
    saga: 'Call of Duty',
  },
  {
    title: 'Call of Duty: Black Ops II',
    editor: 'Treyarch',
    hero: 'Captain Price',
    coverUrl: '/games_pictures/F9JqxCJQ0SaqaP-big.webp',
    releaseDate: '2012-11-13',
    averageTimeToFinish: 0,
    platform: 'PlayStation 3',
    saga: 'Call of Duty',
  },
  {
    title: 'Call of Duty: Black Ops III',
    editor: 'Treyarch',
    hero: 'Captain Price',
    coverUrl: '/games_pictures/BO301.webp',
    releaseDate: '2015-11-06',
    averageTimeToFinish: 80,
    platform: 'PlayStation 4',
    saga: 'Call of Duty',
  },
  {
    title: 'Call of Duty: Infinite Warfare',
    editor: 'Infinity Ward',
    hero: 'Captain Price',
    coverUrl: '/games_pictures/81Xel1A4iWL.jpg',
    releaseDate: '2016-11-04',
    averageTimeToFinish: 0,
    platform: 'PlayStation 4',
    saga: 'Call of Duty',
  },
  {
    title: 'Call of Duty: WWII',
    editor: 'Sledgehammer Games',
    hero: 'Captain Price',
    coverUrl:
      '/games_pictures/MV5BMTUyNDY4NDY5MF5BMl5BanBnXkFtZTgwMjg3NDQwNDI@._V1_.jpg',
    releaseDate: '2017-11-03',
    averageTimeToFinish: 0,
    platform: 'PlayStation 4',
    saga: 'Call of Duty',
  },
  {
    title: 'Call of Duty: Black Ops 4',
    editor: 'Treyarch',
    hero: 'Captain Price',
    coverUrl: '/games_pictures/61rUFXM8-DL._UF1000,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    averageTimeToFinish: 100,
    platform: 'PlayStation 4',
    saga: 'Call of Duty',
  },
  {
    title: 'Call of Duty: Black Ops Cold War',
    editor: 'Treyarch',
    hero: 'Captain Price',
    coverUrl: '/games_pictures/epqD0ZAsuCMkSYVBRMUp5bYk.avif',
    releaseDate: '2020-11-13',
    averageTimeToFinish: 0,
    platform: 'PlayStation 5',
    saga: 'Call of Duty',
  },
  {
    title: 'Call of Duty: Black Ops 6',
    editor: 'Treyarch',
    hero: 'Captain Price',
    coverUrl:
      '/games_pictures/call-of-duty-black-ops-6-smartcdkeys-cheap-cd-key-cover-390x580.webp',
    releaseDate: '2024-10-03',
    averageTimeToFinish: 0,
    platform: 'PlayStation 5',
    saga: 'Call of Duty',
  },
  // Pokémon
  {
    title: 'Pokémon Bleu',
    editor: 'Game Freak',
    hero: 'Dresseur',
    coverUrl: '/games_pictures/pokemon-bleu-gb-e106882.jpg',
    releaseDate: '1996-10-15',
    averageTimeToFinish: 30,
    platform: 'Game Boy',
    saga: 'Pokémon',
  },
  {
    title: 'Pokémon Or',
    editor: 'Game Freak',
    hero: 'Dresseur',
    coverUrl: '/games_pictures/1515055561-186-jaquette-avant.webp',
    releaseDate: '1999-11-21',
    averageTimeToFinish: 40,
    platform: 'Game Boy Color',
    saga: 'Pokémon',
  },
  {
    title: 'Pokémon Cristal',
    editor: 'Game Freak',
    hero: 'Dresseur',
    coverUrl: '/games_pictures/s-l640.jpg',
    releaseDate: '2000-12-14',
    averageTimeToFinish: 45,
    platform: 'Game Boy Color',
    saga: 'Pokémon',
  },
  {
    title: 'Pokémon Saphir',
    editor: 'Game Freak',
    hero: 'Dresseur',
    coverUrl: '/games_pictures/Pokemon-Version-Saphir.jpg',
    releaseDate: '2002-11-21',
    averageTimeToFinish: 50,
    platform: 'Game Boy Advance',
    saga: 'Pokémon',
  },
  {
    title: 'Pokémon Émeraude',
    editor: 'Game Freak',
    hero: 'Dresseur',
    coverUrl: '/games_pictures/1200px-Jaquette_de_Pokémon_Émeraude.png',
    releaseDate: '2004-09-16',
    averageTimeToFinish: 55,
    platform: 'Game Boy Advance',
    saga: 'Pokémon',
  },
  {
    title: 'Pokémon Rouge Feu',
    editor: 'Game Freak',
    hero: 'Dresseur',
    coverUrl: '/games_pictures/pkfrga0f.jpg',
    releaseDate: '2004-01-29',
    averageTimeToFinish: 45,
    platform: 'Game Boy Advance',
    saga: 'Pokémon',
  },
  {
    title: 'Pokémon Bouclier',
    editor: 'Game Freak',
    hero: 'Dresseur',
    coverUrl: '/games_pictures/819sd2k1sCL.jpg',
    releaseDate: '2019-11-15',
    averageTimeToFinish: 90,
    platform: 'Nintendo Switch',
    saga: 'Pokémon',
  },
  {
    title: 'Pokémon Violet',
    editor: 'Game Freak',
    hero: 'Dresseur',
    coverUrl: '/games_pictures/Pokemon-Violet-Nintendo-Switch.jpg',
    releaseDate: '2022-11-18',
    averageTimeToFinish: 100,
    platform: 'Nintendo Switch',
    saga: 'Pokémon',
  },
  // One Piece
  {
    title: 'One Piece: Unlimited Cruise Episode 1',
    editor: 'Ganbarion',
    hero: 'Monkey D. Luffy',
    coverUrl:
      '/games_pictures/jaquette-one-piece-unlimited-cruise-1-le-tresor-sous-les-flots-wii-cover-avant-g.jpg',
    releaseDate: '2008-09-11',
    averageTimeToFinish: 30,
    platform: 'Wii',
    saga: 'One Piece',
  },
  {
    title: 'One Piece: Unlimited Cruise Episode 2',
    editor: 'Ganbarion',
    hero: 'Monkey D. Luffy',
    coverUrl:
      '/games_pictures/one-piece-unlimited-cruise-episode-2-l-eveil-d-un-heros-wii.webp',
    releaseDate: '2009-02-26',
    averageTimeToFinish: 35,
    platform: 'Wii',
    saga: 'One Piece',
  },
  {
    title: 'One Piece: Pirate Warriors',
    editor: 'Omega Force',
    hero: 'Monkey D. Luffy',
    coverUrl:
      '/games_pictures/jaquette-one-piece-pirate-warriors-playstation-3-ps3-cover-avant-g-1348560699.webp',
    releaseDate: '2012-03-01',
    averageTimeToFinish: 50,
    platform: 'PlayStation 3',
    saga: 'One Piece',
  },
  {
    title: 'One Piece: Pirate Warriors 2',
    editor: 'Omega Force',
    hero: 'Monkey D. Luffy',
    coverUrl: '/games_pictures/71w8-P0uWQS._UF1000,1000_QL80_.jpg',
    releaseDate: '2013-03-20',
    averageTimeToFinish: 50,
    platform: 'PlayStation 3',
    saga: 'One Piece',
  },
  {
    title: 'One Piece: Unlimited World Red',
    editor: 'Ganbarion',
    hero: 'Monkey D. Luffy',
    coverUrl:
      '/games_pictures/One-piece-Unlimited-World-Red-Deluxe-edition-Nintendo-Switch.jpg',
    releaseDate: '2014-06-12',
    averageTimeToFinish: 80,
    platform: 'Nintendo 3DS',
    saga: 'One Piece',
  },
  {
    title: 'One Piece: Pirate Warriors 3',
    editor: 'Omega Force',
    hero: 'Monkey D. Luffy',
    coverUrl:
      '/games_pictures/9672f572e25f1eea69b2827641a2b59d9918485c1c8bfefe792fdcbff385c8a6.avif',
    releaseDate: '2015-03-26',
    averageTimeToFinish: 100,
    platform: 'PlayStation 4',
    saga: 'One Piece',
  },
  {
    title: 'One Piece: Burning Blood',
    editor: 'Spike Chunsoft',
    hero: 'Monkey D. Luffy',
    coverUrl: '/games_pictures/One Piece_ Burning Blood.jpg',
    releaseDate: '2016-04-21',
    averageTimeToFinish: 15,
    platform: 'PlayStation 4',
    saga: 'One Piece',
  },
  {
    title: 'One Piece: Treasure Cruise',
    editor: 'Ganbarion',
    hero: 'Monkey D. Luffy',
    coverUrl:
      '/games_pictures/efa276cc4b2d4cbc8299081963d464eae3ff6667-hq-1000x1244-1654756315.jpg',
    releaseDate: '2016-04-21',
    averageTimeToFinish: 0,
    platform: 'Android',
    saga: 'One Piece',
  },
  // Naruto Storm
  {
    title: 'Naruto: Ultimate Ninja Storm',
    editor: 'CyberConnect2',
    hero: 'Naruto Uzumaki',
    coverUrl:
      '/games_pictures/MV5BNzg5OTZhZjUtMmEwOC00ZGI1LTljOTgtNDMzMTA1YjlhNDA2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    releaseDate: '2008-11-04',
    averageTimeToFinish: 20,
    platform: 'PlayStation 3',
    saga: 'Naruto Storm',
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm 2',
    editor: 'CyberConnect2',
    hero: 'Naruto Uzumaki',
    coverUrl:
      '/games_pictures/MV5BMWMwMjMyZWYtZTJkOC00MzM0LTg3OGQtZmY3ZTBmNWRjNDhhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    releaseDate: '2010-10-19',

    averageTimeToFinish: 35,
    platform: 'PlayStation 3',
    saga: 'Naruto Storm',
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm 3',
    editor: 'CyberConnect2',
    hero: 'Naruto Uzumaki',
    coverUrl:
      '/games_pictures/Naruto_Ultimate_Ninja_Storm_3_Full_Burst_Standard_Edition_Packshot__88947.jpg',
    releaseDate: '2013-03-05',
    averageTimeToFinish: 20,
    platform: 'PlayStation 3',
    saga: 'Naruto Storm',
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm 4',
    editor: 'CyberConnect2',
    hero: 'Naruto Uzumaki',
    coverUrl: '/games_pictures/1428916387-2799-jaquette-avant.webp',
    releaseDate: '2016-02-09',

    averageTimeToFinish: 20,
    platform: 'PlayStation 4',
    saga: 'Naruto Storm',
  },
  // Infamous
  {
    title: 'Infamous',
    editor: 'Sucker Punch Productions',
    hero: 'Cole MacGrath',
    coverUrl:
      '/games_pictures/MV5BOGJlNmVkM2EtNjM5Ni00MTFkLTkwOTAtZjU3YTJkNWU1NjI2XkEyXkFqcGc@._V1_.jpg',
    releaseDate: '2009-05-26',

    averageTimeToFinish: 30,
    platform: 'PlayStation 3',
    saga: 'Infamous',
  },
  {
    title: 'Infamous 2',
    editor: 'Sucker Punch Productions',
    hero: 'Cole MacGrath',
    coverUrl:
      '/games_pictures/MV5BZTg1NDY1MzUtMGI1Mi00Nzg1LThhOGMtM2RlNTZkODJhNzQwXkEyXkFqcGc@._V1_.jpg',
    releaseDate: '2011-06-07',

    averageTimeToFinish: 25,
    platform: 'PlayStation 3',
    saga: 'Infamous',
  },
  {
    title: 'Infamous: Second Son',
    editor: 'Sucker Punch Productions',
    hero: 'Delsin Rowe',
    coverUrl: '/games_pictures/KXv6VplN1r1bNPdfR4r29w0m.webp',
    releaseDate: '2014-03-21',

    averageTimeToFinish: 20,
    platform: 'PlayStation 4',
    saga: 'Infamous',
  },
  {
    title: 'Infamous: First Light',
    editor: 'Sucker Punch Productions',
    hero: 'Abigail Walker',
    coverUrl:
      '/games_pictures/MV5BNWE2MGU3MzYtZjk4Yi00ZGU1LTk5MmMtMWMzY2MxY2IyYjc4XkEyXkFqcGc@._V1_QL75_UX190_CR0,4,190,281_.jpg',
    releaseDate: '2014-08-26',

    averageTimeToFinish: 12,
    platform: 'PlayStation 4',
    saga: 'Infamous',
  },
  // Super Smash Bros
  {
    title: 'Super Smash Bros. Melee',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/Super_Smash_Bros_Melee_box_art.png',
    releaseDate: '2001-12-03',

    averageTimeToFinish: 50,
    platform: 'GameCube',
    saga: 'Super Smash Bros',
  },
  {
    title: 'Super Smash Bros. Ultimate',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/81QiNb1LIjL._UF1000,1000_QL80_.jpg',
    releaseDate: '2018-12-07',

    averageTimeToFinish: 100,
    platform: 'Nintendo Switch',
    saga: 'Super Smash Bros',
  },
  // LittleBigPlanet
  {
    title: 'LittleBigPlanet',
    editor: 'Media Molecule',
    hero: 'Sackboy',
    coverUrl:
      '/games_pictures/MV5BNmFiNGYxMTQtMzE5Mi00MDZmLWFiZDgtNDNmMGViNDY1MzMwXkEyXkFqcGc@._V1_.jpg',
    releaseDate: '2008-10-27',
    averageTimeToFinish: 25,
    platform: 'PlayStation 3',
    saga: 'LittleBigPlanet',
  },
  // Brutal Legend
  {
    title: 'Brutal Legend',
    editor: 'Double Fine Productions',
    hero: 'Eddie Riggs',
    coverUrl: '/games_pictures/BrutalLegendCover.jpg',
    releaseDate: '2009-10-13',

    averageTimeToFinish: 30,
    platform: 'PlayStation 3',
    saga: 'Brutal Legend',
  },
  // Batman Arkham
  {
    title: 'Batman: Arkham Asylum',
    editor: 'Rocksteady Studios',
    hero: 'Batman',
    coverUrl: '/games_pictures/batman-arkham-asylum-i167596.jpg',
    releaseDate: '2009-08-25',

    averageTimeToFinish: 15,
    platform: 'PlayStation 3',
    saga: 'Batman Arkham',
  },
  // Spider-Man
  {
    title: 'The Amazing Spider-Man',
    editor: 'Beenox',
    hero: 'Spider-Man',
    coverUrl: '/games_pictures/71q1hH3EijL._UF1000,1000_QL80_.jpg',
    releaseDate: '2012-06-26',

    averageTimeToFinish: 20,
    platform: 'PlayStation 3',
    saga: 'Spider-Man',
  },
  {
    title: "Marvel's Spider-Man",
    editor: 'Insomniac Games',
    hero: 'Spider-Man',
    coverUrl: '/games_pictures/A28f38dd49ebd424aa41257fd9ae45f9dY.webp',
    releaseDate: '2018-09-07',

    averageTimeToFinish: 25,
    platform: 'PlayStation 4',
    saga: 'Spider-Man',
  },
  {
    title: "Marvel's Spider-Man: Miles Morales",
    editor: 'Insomniac Games',
    hero: 'Miles Morales',
    coverUrl: '/games_pictures/PRfYtTZQsuj3ALrBXGL8MjAH.avif',
    releaseDate: '2020-11-12',

    averageTimeToFinish: 15,
    platform: 'PlayStation 5',
    saga: 'Spider-Man',
  },
  {
    title: "Marvel's Spider-Man 2",
    editor: 'Insomniac Games',
    hero: 'Spider-Man',
    coverUrl:
      '/games_pictures/60eca3ac155247e21850c7d075d01ebf0f3f5dbf19ccd2a1.avif',
    releaseDate: '2023-10-20',

    averageTimeToFinish: 30,
    platform: 'PlayStation 5',
    saga: 'Spider-Man',
  },
  // Dead Nation
  {
    title: 'Dead Nation',
    editor: 'Housemarque',
    hero: 'Marco',
    coverUrl: '/games_pictures/1518686841-8541-jaquette-avant.webp',
    releaseDate: '2010-11-30',
    averageTimeToFinish: 30,
    platform: 'PlayStation 3',
    saga: 'Dead Nation',
  },
  // BioShock
  {
    title: 'BioShock Infinite',
    editor: 'Irrational Games',
    hero: 'Booker DeWitt',
    coverUrl:
      '/games_pictures/jaquette-bioshock-infinite-pc-cover-avant-g-1354632827.jpg',
    releaseDate: '2013-03-26',

    averageTimeToFinish: 30,
    platform: 'PlayStation 3',
    saga: 'BioShock',
  },
  // Brothers
  {
    title: 'Brothers: A Tale of Two Sons',
    editor: 'Starbreeze Studios',
    hero: 'Naiee & Naia',
    coverUrl:
      '/games_pictures/Brothers_Port_1200x1600_1200x1600-ee43c7558877b4470f607a0c140ee3d5.jpg',
    releaseDate: '2013-08-28',
    averageTimeToFinish: 4,
    platform: 'PlayStation 3',
    saga: 'Brothers',
  },
  // Injustice
  {
    title: 'Injustice: Gods Among Us Ultimate Edition',
    editor: 'NetherRealm Studios',
    hero: 'Superman',
    coverUrl: '/games_pictures/Injustice_Gods_Among_Us_cover_art.webp',
    releaseDate: '2013-11-12',
    averageTimeToFinish: 8,
    platform: 'PlayStation 3',
    saga: 'Injustice',
  },
  // Mirror's Edge
  {
    title: "Mirror's Edge",
    editor: 'DICE',
    hero: 'Faith Connors',
    coverUrl: "/games_pictures/Mirror's_Edge.jpg",
    releaseDate: '2008-11-11',

    averageTimeToFinish: 30,
    platform: 'PlayStation 3',
    saga: "Mirror's Edge",
  },
  // PlayStation All-Stars
  {
    title: 'PlayStation All-Stars Battle Royale',
    editor: 'SuperBot Entertainment',
    hero: 'Kratos',
    coverUrl: '/games_pictures/71JqJ1aj5fS.jpg',
    releaseDate: '2012-11-20',
    averageTimeToFinish: 15,
    platform: 'PlayStation 3',
    saga: 'PlayStation All-Stars',
  },
  // Stick It to the Man
  {
    title: 'Stick It to the Man',
    editor: 'Zoink Games',
    hero: 'Ray',
    coverUrl: '/games_pictures/s-l1200.jpg',
    releaseDate: '2013-11-19',
    averageTimeToFinish: 10,
    platform: 'PlayStation 3',
    saga: 'Stick It to the Man',
  },
  // Watch Dogs
  {
    title: 'Watch Dogs',
    editor: 'Ubisoft',
    hero: 'Aiden Pearce',
    coverUrl: '/games_pictures/56c494ae88a7e300458b4d72.jpg',
    releaseDate: '2014-05-27',

    averageTimeToFinish: 50,
    platform: 'PlayStation 4',
    saga: 'Watch Dogs',
  },
  // Super Meat Boy
  {
    title: 'Super Meat Boy',
    editor: 'Team Meat',
    hero: 'Meat Boy',
    coverUrl: '/games_pictures/cANQICFpF9rI44-medium.webp',
    releaseDate: '2010-10-20',

    averageTimeToFinish: 15,
    platform: 'PlayStation 4',
    saga: 'Super Meat Boy',
  },
  // J-Stars Victory
  {
    title: 'J-Stars Victory VS',
    editor: 'Spike Chunsoft',
    hero: 'Goku',
    coverUrl: '/games_pictures/kl2fcl0fcka71.jpg',
    releaseDate: '2014-03-19',
    averageTimeToFinish: 40,
    platform: 'PlayStation 3',
    saga: 'J-Stars Victory',
  },
  // Dragon Ball
  {
    title: 'Dragon Ball Z: Budokai 2',
    editor: 'Dimps',
    hero: 'Goku',
    coverUrl: '/games_pictures/dbz2p20f.webp',
    releaseDate: '2003-12-04',

    averageTimeToFinish: 12,
    platform: 'PlayStation 2',
    saga: 'Dragon Ball',
  },
  {
    title: 'Dragon Ball Z: Budokai 3',
    editor: 'Dimps',
    hero: 'Goku',
    coverUrl: '/games_pictures/71QBu0YcCcL.jpg',
    releaseDate: '2004-11-16',

    averageTimeToFinish: 15,
    platform: 'PlayStation 2',
    saga: 'Dragon Ball',
  },
  {
    title: 'Dragon Ball Z: Budokai Tenkaichi 2',
    editor: 'Spike',
    hero: 'Goku',
    coverUrl:
      '/games_pictures/dragon-ball-z-budokai-tenkaichi-2-i-2-3296580803279_0.jpg',
    releaseDate: '2006-10-03',

    averageTimeToFinish: 18,
    platform: 'PlayStation 2',
    saga: 'Dragon Ball',
  },
  {
    title: 'Dragon Ball Z: Dokkan Battle',
    editor: 'Bandai Namco',
    hero: 'Goku',
    coverUrl: '/games_pictures/Dragon-Ball-Z-Dokkan-Battle.jpg',
    releaseDate: '2015-03-19',

    averageTimeToFinish: 0,
    platform: 'Android',
    saga: 'Dragon Ball',
  },
  // Ratchet & Clank
  {
    title: 'Ratchet & Clank',
    editor: 'Insomniac Games',
    hero: 'Ratchet',
    coverUrl:
      '/games_pictures/MV5BYTJlYWY1M2EtMDlkOC00ZmViLTgyYWEtOWRhZWM0MmRkNzRjXkEyXkFqcGc@._V1_.jpg',
    releaseDate: '2002-11-04',

    averageTimeToFinish: 15,
    platform: 'PlayStation 2',
    saga: 'Ratchet & Clank',
  },
  // South Park
  {
    title: 'South Park: Le Bâton de la Vérité',
    editor: 'Obsidian Entertainment',
    hero: 'Le Nouveau',
    coverUrl: '/games_pictures/southparklebatondelaveritepccover0458778.jpg',
    releaseDate: '2014-03-04',

    averageTimeToFinish: 15,
    platform: 'PlayStation 3',
    saga: 'South Park',
  },
  // God of War
  {
    title: 'God of War',
    editor: 'Santa Monica Studio',
    hero: 'Kratos',
    coverUrl: '/games_pictures/85407.jpg',
    releaseDate: '2018-04-20',

    averageTimeToFinish: 45,
    platform: 'PlayStation 4',
    saga: 'God of War',
  },
  {
    title: 'God of War Ragnarök',
    editor: 'Santa Monica Studio',
    hero: 'Kratos',
    coverUrl: '/games_pictures/0711719409397_1.png',
    releaseDate: '2022-11-09',

    averageTimeToFinish: 40,
    platform: 'PlayStation 5',
    saga: 'God of War',
  },
  // Hogwarts Legacy
  {
    title: 'Hogwarts Legacy',
    editor: 'Avalanche Software',
    hero: 'Élève de Poudlard',
    coverUrl:
      '/games_pictures/f6b1e4512ee6061913f7d604da8f5f39566be56ca32a68ee.avif',
    releaseDate: '2023-02-10',

    averageTimeToFinish: 50,
    platform: 'PlayStation 5',
    saga: 'Hogwarts Legacy',
  },
  // Metroid
  {
    title: 'Metroid Fusion',
    editor: 'Nintendo',
    hero: 'Samus Aran',
    coverUrl:
      '/games_pictures/MV5BMjNhNGQyMjgtODAyZi00YTgzLTk3ZDMtNWFkNjI4MmJiZjdkXkEyXkFqcGc@._V1_.jpg',
    releaseDate: '2002-11-17',
    averageTimeToFinish: 15,
    platform: 'Game Boy Advance',
    saga: 'Metroid',
  },
  {
    title: 'Metroid: Zero Mission',
    editor: 'Nintendo',
    hero: 'Samus Aran',
    coverUrl:
      '/games_pictures/MV5BNGQ1MzY0NjktNGI1Yi00YTc4LWFkMWUtNGM2YmRiZWI4MDZkXkEyXkFqcGc@._V1_.jpg',
    releaseDate: '2004-02-09',
    averageTimeToFinish: 10,
    platform: 'Game Boy Advance',
    saga: 'Metroid',
  },
  {
    title: 'Metroid Prime',
    editor: 'Retro Studios',
    hero: 'Samus Aran',
    coverUrl: '/games_pictures/metroid-prime-wii.jpg',
    releaseDate: '2002-11-17',
    averageTimeToFinish: 20,
    platform: 'GameCube',
    saga: 'Metroid',
  },
  {
    title: 'Metroid Prime 2: Echoes',
    editor: 'Retro Studios',
    hero: 'Samus Aran',
    coverUrl: '/games_pictures/mep2gc0f.jpg',
    releaseDate: '2004-11-15',
    averageTimeToFinish: 25,
    platform: 'GameCube',
    saga: 'Metroid',
  },
  {
    title: 'Metroid Prime 3: Corruption',
    editor: 'Retro Studios',
    hero: 'Samus Aran',
    coverUrl: '/games_pictures/Metroidprime3corruption.webp',
    releaseDate: '2007-08-27',
    averageTimeToFinish: 22,
    platform: 'Wii',
    saga: 'Metroid',
  },
  {
    title: 'Metroid Dread',
    editor: 'MercurySteam',
    hero: 'Samus Aran',
    coverUrl: '/games_pictures/81ygZZVdUvS.jpg',
    releaseDate: '2021-10-08',
    averageTimeToFinish: 20,
    platform: 'Nintendo Switch',
    saga: 'Metroid',
  },
  // Super Mario
  {
    title: 'Super Mario 64',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/super_mario_64_2.webp',
    releaseDate: '1996-06-23',
    averageTimeToFinish: 20,
    platform: 'Nintendo 64',
    saga: 'Super Mario',
  },
  {
    title: 'Super Mario Galaxy',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/il_570xN.5937744444_j3z5.webp',
    releaseDate: '2007-11-12',
    averageTimeToFinish: 30,
    platform: 'Wii',
    saga: 'Super Mario',
  },
  {
    title: 'Super Mario Odyssey',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/81TksYoxfQL._UF1000,1000_QL80_.jpg',
    releaseDate: '2017-10-27',
    averageTimeToFinish: 40,
    platform: 'Nintendo Switch',
    saga: 'Super Mario',
  },

  // Mario Kart
  {
    title: 'Mario Kart: Double Dash!!',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/81e0IWNn5eL._UF1000,1000_QL80_.jpg',
    releaseDate: '2003-11-07',
    averageTimeToFinish: 12,
    platform: 'GameCube',
    saga: 'Mario Kart',
  },
  {
    title: 'Mario Kart Wii',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/mario-kart-wii-e2671.jpg',
    releaseDate: '2008-04-10',
    averageTimeToFinish: 15,
    platform: 'Wii',
    saga: 'Mario Kart',
  },
  {
    title: 'Mario Kart 8 Deluxe',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/81EdgFXOWWL._UF1000,1000_QL80_.jpg',
    releaseDate: '2017-04-28',
    averageTimeToFinish: 25,
    platform: 'Nintendo Switch',
    saga: 'Mario Kart',
  },
  // Mario Party
  {
    title: 'Mario Party 5',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/81byWQum9AL.jpg',
    releaseDate: '2003-11-10',
    averageTimeToFinish: 12,
    platform: 'GameCube',
    saga: 'Mario Party',
  },
  {
    title: 'Mario Party 6',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/Mario_Party_6_capa.png',
    releaseDate: '2004-12-06',
    averageTimeToFinish: 12,
    platform: 'GameCube',
    saga: 'Mario Party',
  },
  {
    title: 'Mario Party 7',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/Mario_Party_7_Coverart.png',
    releaseDate: '2005-11-07',
    averageTimeToFinish: 12,
    platform: 'GameCube',
    saga: 'Mario Party',
  },
  {
    title: 'Mario Party 8',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/91FQxPuzTQL.jpg',
    releaseDate: '2007-05-29',
    averageTimeToFinish: 10,
    platform: 'Wii',
    saga: 'Mario Party',
  },

  {
    title: 'Super Mario Party',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/81XdRd9UNZL.jpg',
    releaseDate: '2018-10-05',
    averageTimeToFinish: 12,
    platform: 'Nintendo Switch',
    saga: 'Mario Party',
  },
  // Paper Mario
  {
    title: 'Super Paper Mario',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/71GK7PP0tFL.jpg',
    releaseDate: '2007-04-09',
    averageTimeToFinish: 20,
    platform: 'Wii',
    saga: 'Paper Mario',
  },
  // Mario & Luigi
  {
    title: 'Mario & Luigi: Superstar Saga',
    editor: 'Nintendo',
    hero: 'Mario & Luigi',
    coverUrl: '/games_pictures/MarioAndLuigiSuperstarSagaGBACoverArtUS.jpg',
    releaseDate: '2003-11-17',
    averageTimeToFinish: 20,
    platform: 'Game Boy Advance',
    saga: 'Mario & Luigi',
  },

  // Need for Speed
  {
    title: 'Need for Speed: Most Wanted',
    editor: 'Electronic Arts',
    hero: 'Pilote',
    coverUrl: '/games_pictures/71-WJMXvaLL._UF1000,1000_QL80_.jpg',
    releaseDate: '2005-11-15',
    averageTimeToFinish: 30,
    platform: 'PlayStation 2',
    saga: 'Need for Speed',
  },
  {
    title: 'Need for Speed: Carbon',
    editor: 'Electronic Arts',
    hero: 'Pilote',
    coverUrl: '/games_pictures/nfs-carbon-psp-e7802 (1).jpg',
    releaseDate: '2006-10-31',
    averageTimeToFinish: 20,
    platform: 'PlayStation 2',
    saga: 'Need for Speed',
  },
  // Yu-Gi-Oh!
  {
    title: 'Yu-Gi-Oh! Duel des ténèbres',
    editor: 'Konami',
    hero: 'Yugi Muto',
    coverUrl: '/games_pictures/yugioh-duel-des-tenebres-e59476.jpg',
    releaseDate: '2002-03-08',
    averageTimeToFinish: 20,
    platform: 'Game Boy Advance',
    saga: 'Yu-Gi-Oh!',
  },
  {
    title: 'Yu-Gi-Oh! The Sacred Cards',
    editor: 'Konami',
    hero: 'Yugi Muto',
    coverUrl: '/games_pictures/91qzoCTEX4L._UF1000,1000_QL80_.jpg',
    releaseDate: '2003-10-28',
    averageTimeToFinish: 18,
    platform: 'Game Boy Advance',
    saga: 'Yu-Gi-Oh!',
  },
  {
    title: 'Yu-Gi-Oh! Reshef of Destruction',
    editor: 'Konami',
    hero: 'Yugi Muto',
    coverUrl: '/games_pictures/51EQWD3DTRL._UF1000,1000_QL80_.jpg',
    releaseDate: '2004-03-23',
    averageTimeToFinish: 20,
    platform: 'Game Boy Advance',
    saga: 'Yu-Gi-Oh!',
  },
  // Medal of Honor
  {
    title: 'Medal of Honor : En première ligne',
    editor: 'Electronic Arts',
    hero: 'Soldat',
    coverUrl: '/games_pictures/Medal-Of-Honor-En-premiere-ligne.jpg',
    releaseDate: '1999-10-31',
    averageTimeToFinish: 8,
    platform: 'PlayStation',
    saga: 'Medal of Honor',
  },
  // Guitar Hero
  {
    title: 'Guitar Hero III: Legends of Rock',
    editor: 'Activision',
    hero: 'Guitariste',
    coverUrl: '/games_pictures/81VZXSoqNbL.jpg',
    releaseDate: '2007-10-28',
    averageTimeToFinish: 15,
    platform: 'PlayStation 2',
    saga: 'Guitar Hero',
  },
  // Luigi's Mansion
  {
    title: "Luigi's Mansion",
    editor: 'Nintendo',
    hero: 'Luigi',
    coverUrl: '/games_pictures/Lmbox.jpg',
    releaseDate: '2001-11-18',
    averageTimeToFinish: 12,
    platform: 'GameCube',
    saga: "Luigi's Mansion",
  },
  // Tekken
  {
    title: 'Tekken: Dark Resurrection',
    editor: 'Bandai Namco',
    hero: 'Fighter',
    coverUrl: '/games_pictures/71kxx1mB1nL.jpg',
    releaseDate: '2006-07-25',
    averageTimeToFinish: 10,
    platform: 'PlayStation Portable',
    saga: 'Tekken',
  },
  // Grand Theft Auto
  {
    title: 'Grand Theft Auto: San Andreas',
    editor: 'Rockstar Games',
    hero: 'Carl Johnson',
    coverUrl: '/games_pictures/10_5026555302623_jm.jpg',
    releaseDate: '2004-10-26',
    averageTimeToFinish: 40,
    platform: 'PlayStation 2',
    saga: 'Grand Theft Auto',
  },
  {
    title: 'Grand Theft Auto: Vice City',
    editor: 'Rockstar Games',
    hero: 'Tommy Vercetti',
    coverUrl: '/games_pictures/61e6sU9SIzL._UF1000,1000_QL80_.jpg',
    releaseDate: '2002-10-27',
    averageTimeToFinish: 25,
    platform: 'PlayStation 2',
    saga: 'Grand Theft Auto',
  },
  {
    title: 'Grand Theft Auto: Vice City Stories',
    editor: 'Rockstar Games',
    hero: 'Tommy Vercetti',
    coverUrl: '/games_pictures/71qnLo5SrLS.jpg',
    releaseDate: '2002-10-27',
    averageTimeToFinish: 25,
    platform: 'PlayStation 2',
    saga: 'Grand Theft Auto',
  },
  {
    title: 'Grand Theft Auto: Liberty City Stories',
    editor: 'Rockstar Games',
    hero: 'Tommy Vercetti',
    coverUrl: '/games_pictures/71XZGiY69MS._UF1000,1000_QL80_.jpg',
    releaseDate: '2002-10-27',
    averageTimeToFinish: 25,
    platform: 'PlayStation 2',
    saga: 'Grand Theft Auto',
  },
  // Star Wars
  {
    title: 'Star Wars: Le Pouvoir de la Force',
    editor: 'LucasArts',
    hero: 'Jedi',
    coverUrl: '/games_pictures/81idoSKM3BL._UF1000,1000_QL80_.jpg',
    releaseDate: '2008-11-04',
    averageTimeToFinish: 20,
    platform: 'PlayStation 3',
    saga: 'Star Wars',
  },
  {
    title: 'Lego Star Wars',
    editor: 'LucasArts',
    hero: 'Luke Skywalker',
    coverUrl: '/games_pictures/51PIJcSrsnL._UF1000,1000_QL80_.jpg',
    releaseDate: '2005-04-02',
    averageTimeToFinish: 15,
    platform: 'PlayStation 2',
    saga: 'Star Wars',
  },
  {
    title: 'Star Wars: Rebel Strike',
    editor: 'LucasArts',
    hero: 'Pilote',
    coverUrl: '/games_pictures/rgs3gc0f.jpg',
    releaseDate: '2003-10-21',
    averageTimeToFinish: 18,
    platform: 'GameCube',
    saga: 'Star Wars',
  },
  // Wario Ware
  {
    title: 'WarioWare: Smooth Moves',
    editor: 'Nintendo',
    hero: 'Wario',
    coverUrl: '/games_pictures/813wBVf7BXL.jpg',
    releaseDate: '2007-01-15',
    averageTimeToFinish: 8,
    platform: 'Wii',
    saga: 'WarioWare',
  },
  // Gunbound
  {
    title: 'Gunbound World Champion',
    editor: 'Softnyx',
    hero: 'Artilleur',
    coverUrl: '/games_pictures/11820829.jpg',
    releaseDate: '2005-01-01',
    averageTimeToFinish: 5,
    platform: 'PC',
    saga: 'Gunbound',
  },
  // GoldenEye
  {
    title: 'GoldenEye 007',
    editor: 'Nintendo',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/MV5BZWIwYWJmNzQtNWZiNC00Njc3LWI2YTUtYTJiMDFlYTc2YWRhXkEyXkFqcGc@._V1_.jpg',
    releaseDate: '1997-08-25',
    averageTimeToFinish: 15,
    platform: 'Nintendo 64',
    saga: 'GoldenEye',
  },
  // Wii Sports
  {
    title: 'Wii Sports',
    editor: 'Nintendo',
    hero: 'Mii',
    coverUrl: '/games_pictures/wii-sport-e15224.jpg',
    releaseDate: '2006-11-19',
    averageTimeToFinish: 10,
    platform: 'Wii',
    saga: 'Wii Sports',
  },
  // Harry Potter
  {
    title: 'Harry Potter: Coupe du Monde de Quidditch',
    editor: 'Electronic Arts',
    hero: 'Harry Potter',
    coverUrl: '/games_pictures/hpqupc0f.jpg',
    releaseDate: '2003-10-28',
    averageTimeToFinish: 12,
    platform: 'GameCube',
    saga: 'Harry Potter',
  },
  // Les Simpsons
  {
    title: 'Les Simpsons: Le Jeu',
    editor: 'Electronic Arts',
    hero: 'Homer Simpson',
    coverUrl: '/games_pictures/lsljwi0f.webp',
    releaseDate: '2007-07-30',
    averageTimeToFinish: 15,
    platform: 'Wii',
    saga: 'Les Simpsons',
  },
  // Sonic
  {
    title: 'Sonic Adventure 2 Battle',
    editor: 'Sega',
    hero: 'Sonic',
    coverUrl:
      '/games_pictures/jaquette-sonic-adventure-2-battle-gamecube-ngc-cover-avant-g-1361810227.webp',
    releaseDate: '2001-12-20',
    averageTimeToFinish: 20,
    platform: 'GameCube',
    saga: 'Sonic',
  },
  {
    title: 'Sonic Unleashed',
    editor: 'Sega',
    hero: 'Sonic',
    coverUrl: '/games_pictures/71xgwF1QaLL.jpg',
    releaseDate: '2008-11-18',
    averageTimeToFinish: 18,
    platform: 'Wii',
    saga: 'Sonic',
  },
  // Super Smash Bros
  {
    title: 'Super Smash Bros. Brawl',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/71aV0SbNGCL.jpg',
    releaseDate: '2008-01-31',
    averageTimeToFinish: 25,
    platform: 'Wii',
    saga: 'Super Smash Bros',
  },
];
