import { BaseGame } from '../../../models/game-model';

const COVER = '/games_pictures/Yu_Yu_Hakusho_-_Tournament_Tactics_Coverart.png';

const fromManga = {
  entityType: 'manga' as const,
  title: 'Yu Yu Hakusho',
  secondEntityKey: 'Yoshihiro Togashi',
};

/**
 * Jeux *Yu Yu Hakusho* hors {@link base_games} (où figure *Tournament Tactics* GBA).
 */
export const baseGamesYuYuHakusho: BaseGame[] = [
  {
    title: 'Yu Yu Hakusho (Game Boy, 1993)',
    editor: 'Tomy',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '1993-08-01',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 0,
    platform: 'Game Boy',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho Dai-2-shoku : Ankoku Bujutsukai',
    editor: 'Tomy',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '1993-12-10',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 0,
    platform: 'Game Boy',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho Dai-3-shoku : Makai no Tobira',
    editor: 'Tomy',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '1994-06-03',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 0,
    platform: 'Game Boy',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho Dai-4-shoku : Makai Tōitsusen Final',
    editor: 'Tomy',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '1995-03-24',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 0,
    platform: 'Game Boy',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho (Super Famicom, 1993)',
    editor: 'Banpresto',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '1993-10-22',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 20,
    platform: 'Super Famicom',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho 2 : Gekitō ! Nanakyō Senshūketsu',
    editor: 'Banpresto',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '1994-06-17',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 20,
    platform: 'Super Famicom',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho Final : Makai Saikyō Retsuden',
    editor: 'Banpresto',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '1995-03-24',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 20,
    platform: 'Super Famicom',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho : Gekitō ! Makyū Tōitsusen',
    editor: 'Sega',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '1994-09-30',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 15,
    platform: 'Mega Drive',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho SUN',
    editor: 'Sega',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '1995-12-29',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 25,
    platform: 'Sega Saturn',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho (PlayStation, 1997)',
    editor: 'Banpresto',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '1997-08-22',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 30,
    platform: 'PlayStation',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho : Spirit Detective (GBA)',
    editor: 'Atari',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '2003-12-02',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 20,
    platform: 'Game Boy Advance',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho : Spirit Detective (PS2)',
    editor: 'Atari',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '2004-02-09',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 25,
    platform: 'PlayStation 2',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho : Dark Tournament',
    editor: 'Atari',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '2004-09-21',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 25,
    platform: 'PlayStation 2',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
  {
    title: 'Yu Yu Hakusho : Tournament Battle',
    editor: 'Atari',
    hero: 'Yusuke Urameshi',
    coverUrl: COVER,
    releaseDate: '2005-09-20',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 20,
    platform: 'PlayStation 2',
    saga: 'Yu Yu Hakusho',
    platineTime: 0,
    description: '',
    fromEntity: fromManga,
  },
];
