import { BaseGame } from '../../../models/game-model';

/**
 * Jeux James Bond hors {@link base_games} (où figure déjà GoldenEye 007 sur Nintendo 64).
 */
export const baseGamesBond: BaseGame[] = [
  {
    title: 'James Bond 007 (Atari 2600)',
    editor: 'Parker Brothers',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/beade3559f53.jpg',
    releaseDate: '1983-01-01',
    averageTimeToFinish: 2,
    averageTimeToHundredPercent: 0,
    platform: 'Atari 2600',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'book',
      title: 'Casino Royale',
      secondEntityKey: 'Ian Fleming',
    },
  },
  {
    title: 'James Bond 007 : A View to a Kill',
    editor: 'Mindscape',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/6997f9713b06.jpg',
    releaseDate: '1985-01-01',
    averageTimeToFinish: 4,
    averageTimeToHundredPercent: 0,
    platform: 'PC',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'movie' as const,
      title: 'James Bond : Dangereusement vôtre',
      secondEntityKey: 'John Glen',
    },
  },
  {
    title: 'James Bond : Goldfinger',
    editor: 'Mindscape',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/3c561a9f45de.jpg',
    releaseDate: '1986-01-01',
    averageTimeToFinish: 4,
    averageTimeToHundredPercent: 0,
    platform: 'PC',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'movie' as const,
      title: 'James Bond : Goldfinger',
      secondEntityKey: 'Guy Hamilton',
    },
  },
  {
    title: 'James Bond : The Living Daylights',
    editor: 'Domark',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/f240a6c58569.webp',
    releaseDate: '1987-01-01',
    averageTimeToFinish: 4,
    averageTimeToHundredPercent: 0,
    platform: 'PC, Commodore 64',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'movie' as const,
      title: "James Bond : Tuer n'est pas jouer",
      secondEntityKey: 'John Glen',
    },
  },
  {
    title: 'Live and Let Die: The Computer Game',
    editor: 'Domark',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/4a6e7ef9b33c.jpg',
    releaseDate: '1988-01-01',
    averageTimeToFinish: 4,
    averageTimeToHundredPercent: 0,
    platform: 'PC, Commodore 64',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'movie' as const,
      title: 'James Bond : Vivre et laisser mourir',
      secondEntityKey: 'Guy Hamilton',
    },
  },
  {
    title: '007: Licence to Kill',
    editor: 'Domark',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/a4720c399a45.jpg',
    releaseDate: '1989-01-01',
    averageTimeToFinish: 4,
    averageTimeToHundredPercent: 0,
    platform: 'PC, DOS',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'movie' as const,
      title: 'James Bond : Permis de tuer',
      secondEntityKey: 'John Glen',
    },
  },
  {
    title: 'The Spy Who Loved Me',
    editor: 'The Hit Squad',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/e942bf6ce3a8.jpg',
    releaseDate: '1990-01-01',
    averageTimeToFinish: 5,
    averageTimeToHundredPercent: 0,
    platform: 'PC',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'movie' as const,
      title: "James Bond : L'espion qui m'aimait",
      secondEntityKey: 'Lewis Gilbert',
    },
  },
  {
    title: 'James Bond Jr.',
    editor: 'THQ',
    hero: 'James Bond Jr.',
    coverUrl:
      'https://www.gamecash.fr/thumbnail-600/james-bond-jr-nes-e20783.jpg',
    releaseDate: '1992-01-01',
    averageTimeToFinish: 6,
    averageTimeToHundredPercent: 0,
    platform: 'NES, Super NES',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'book',
      title: 'Casino Royale',
      secondEntityKey: 'Ian Fleming',
    },
  },
  {
    title: 'James Bond: The Duel',
    editor: 'Domark',
    hero: 'James Bond',
    coverUrl: '/games_pictures/af2abd5da1ca.jpg',
    releaseDate: '1993-01-01',
    averageTimeToFinish: 3,
    averageTimeToHundredPercent: 0,
    platform: 'Mega Drive, Game Gear',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'book',
      title: 'Casino Royale',
      secondEntityKey: 'Ian Fleming',
    },
  },
  {
    title: 'James Bond 007 (Game Boy)',
    editor: 'Nintendo',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/dec41037d8de.png',
    releaseDate: '1998-02-09',
    averageTimeToFinish: 6,
    averageTimeToHundredPercent: 0,
    platform: 'Game Boy',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'book',
      title: 'Casino Royale',
      secondEntityKey: 'Ian Fleming',
    },
  },
  {
    title: '007: Tomorrow Never Dies',
    editor: 'Electronic Arts',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/a9b5d01f91c8.png',
    releaseDate: '1999-11-16',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 12,
    platform: 'PlayStation',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'movie' as const,
      title: 'James Bond : Demain ne meurt jamais',
      secondEntityKey: 'Roger Spottiswoode',
    },
  },
  {
    title: '007: The World Is Not Enough',
    editor: 'Electronic Arts',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/013fa0bed61f.jpg',
    releaseDate: '2000-11-17',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 12,
    platform: 'Nintendo 64',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'movie' as const,
      title: 'James Bond : Le monde ne suffit pas',
      secondEntityKey: 'Michael Apted',
    },
  },
  {
    title: '007 Racing',
    editor: 'Electronic Arts',
    hero: 'James Bond',
    coverUrl: '/games_pictures/dd664e03a9d9.jpg',
    releaseDate: '2000-11-21',
    averageTimeToFinish: 6,
    averageTimeToHundredPercent: 10,
    platform: 'PlayStation',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'book',
      title: 'Casino Royale',
      secondEntityKey: 'Ian Fleming',
    },
  },
  {
    title: 'James Bond 007: Agent Under Fire',
    editor: 'Electronic Arts',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/63440e9ff347.jpg',
    releaseDate: '2001-11-13',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 15,
    platform: 'PlayStation 2, Xbox, GameCube',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'book',
      title: 'Casino Royale',
      secondEntityKey: 'Ian Fleming',
    },
  },
  {
    title: 'James Bond 007: Nightfire',
    editor: 'Electronic Arts',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/81ae41d87ce7.jpg',
    releaseDate: '2002-11-18',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 18,
    platform: 'PlayStation 2, Xbox, GameCube, PC',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'book',
      title: 'Casino Royale',
      secondEntityKey: 'Ian Fleming',
    },
  },
  {
    title: 'James Bond 007: Everything or Nothing',
    editor: 'Electronic Arts',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/415dd22b02e3.jpg',
    releaseDate: '2004-02-17',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 20,
    platform: 'PlayStation 2, Xbox, GameCube',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'book',
      title: 'Casino Royale',
      secondEntityKey: 'Ian Fleming',
    },
  },
  {
    title: 'GoldenEye: Rogue Agent',
    editor: 'Electronic Arts',
    hero: 'Agent GoldenEye',
    coverUrl: '/games_pictures/c71a07629b15.jpg',
    releaseDate: '2004-11-02',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 15,
    platform: 'PlayStation 2, Xbox, GameCube',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'book',
      title: 'Casino Royale',
      secondEntityKey: 'Ian Fleming',
    },
  },
  {
    title: 'James Bond 007: From Russia with Love',
    editor: 'Electronic Arts',
    hero: 'James Bond',
    coverUrl: '/games_pictures/5de070c022d1.jpg',
    releaseDate: '2005-11-01',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 15,
    platform: 'PlayStation 2, Xbox',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'movie' as const,
      title: 'James Bond : Bons baisers de Russie',
      secondEntityKey: 'Terence Young',
    },
  },
  {
    title: 'James Bond : Quantum of Solace',
    editor: 'Activision',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/4933089919d1.jpg',
    releaseDate: '2008-10-31',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 14,
    platform: 'PlayStation 3, Xbox 360, Wii, PC, Nintendo DS',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'movie' as const,
      title: 'James Bond : Quantum of Solace',
      secondEntityKey: 'Marc Forster',
    },
  },
  {
    title: 'GoldenEye 007 (Wii)',
    editor: 'Activision',
    hero: 'James Bond',
    coverUrl: '/games_pictures/d3ece61ab07b.jpg',
    releaseDate: '2010-11-02',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 18,
    platform: 'Wii',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'movie' as const,
      title: 'GoldenEye',
      secondEntityKey: 'Martin Campbell',
    },
  },
  {
    title: 'James Bond 007: Blood Stone',
    editor: 'Activision',
    hero: 'James Bond',
    coverUrl: '/games_pictures/c6893a07676c.jpg',
    releaseDate: '2010-11-02',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 12,
    platform: 'PlayStation 3, Xbox 360, PC',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'book',
      title: 'Casino Royale',
      secondEntityKey: 'Ian Fleming',
    },
  },
  {
    title: 'GoldenEye 007: Reloaded',
    editor: 'Activision',
    hero: 'James Bond',
    coverUrl: '/games_pictures/08dd2cd417d7.jpg',
    releaseDate: '2011-11-01',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 18,
    platform: 'PlayStation 3, Xbox 360',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'movie' as const,
      title: 'GoldenEye',
      secondEntityKey: 'Martin Campbell',
    },
  },
  {
    title: '007 Legends',
    editor: 'Activision',
    hero: 'James Bond',
    coverUrl:
      '/games_pictures/264bbd1dbf01.jpg',
    releaseDate: '2012-10-16',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 15,
    platform: 'PlayStation 3, Xbox 360, PC',
    saga: 'James Bond',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'book',
      title: 'Casino Royale',
      secondEntityKey: 'Ian Fleming',
    },
  },
];
