import { BaseGame } from '../../../models/game-model';

/** Jeux dérivés de Lupin III (manga Monkey Punch). */
export const baseGamesLupin: BaseGame[] = [
  {
    title: 'Lupin III',
    editor: 'Taito',
    hero: 'Lupin III',
    coverUrl:
      '/games_pictures/5a4056de71ec.jpg',
    releaseDate: '1980-01-01',
    averageTimeToFinish: 1,
    averageTimeToHundredPercent: 0,
    platform: 'Arcade',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
  {
    title: 'Lupin III',
    editor: 'Epoch',
    hero: 'Lupin III',
    coverUrl:
      '/games_pictures/fdcd38cd0ca7.jpg',
    releaseDate: '1984-01-01',
    averageTimeToFinish: 2,
    averageTimeToHundredPercent: 0,
    platform: 'Super Cassette Vision',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
  {
    title: "Lupin III : L'Héritage de Pandora",
    editor: 'Bandai',
    hero: 'Lupin III',
    coverUrl:
      '/games_pictures/c8fce35e32da.jpg',
    releaseDate: '1987-06-03',
    averageTimeToFinish: 4,
    averageTimeToHundredPercent: 0,
    platform: 'Family Computer',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
  {
    title: 'Lupin III : Le Château de Cagliostro',
    editor: 'Thinking Rabbit',
    hero: 'Lupin III',
    coverUrl:
      '/games_pictures/5055ea0a2b26.jpg',
    releaseDate: '1985-12-15',
    averageTimeToFinish: 4,
    averageTimeToHundredPercent: 0,
    platform: 'MSX2',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
  {
    title: "Lupin III : La Légende de l'or de Babylone",
    editor: 'Bandai',
    hero: 'Lupin III',
    coverUrl:
      '/games_pictures/9d892a312eb4.png',
    releaseDate: '1988-12-02',
    averageTimeToFinish: 5,
    averageTimeToHundredPercent: 0,
    platform: 'Family Computer, MSX2',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
  {
    title: 'SD Lupin III : Opération cambriolage',
    editor: 'Epoch',
    hero: 'Lupin III',
    coverUrl:
      '/games_pictures/d6841226b37f.jpg',
    releaseDate: '1990-04-13',
    averageTimeToFinish: 3,
    averageTimeToHundredPercent: 0,
    platform: 'Game Boy',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
  {
    title: 'Lupin III : À la poursuite du trésor légendaire',
    editor: 'Banpresto',
    hero: 'Lupin III',
    coverUrl:
      '/games_pictures/15e0c6899e8c.jpg',
    releaseDate: '1994-12-22',
    averageTimeToFinish: 6,
    averageTimeToHundredPercent: 0,
    platform: 'Super Famicom',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
  {
    title: 'Lupin III : The Master File',
    editor: 'Banpresto',
    hero: 'Lupin III',
    coverUrl:
      '/games_pictures/dd57ecf1cd87.jpg',
    releaseDate: '1996-06-28',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 0,
    platform: 'Sega Saturn',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
  {
    title: 'Lupin III : Trésor du roi des sorciers',
    editor: 'Bandai',
    hero: 'Lupin III',
    coverUrl: '/games_pictures/c5a9a75a0b11.jpg',
    releaseDate: '2002-06-27',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 0,
    platform: 'PlayStation 2',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
  {
    title: "Lupin III : L'héritage de Colomb",
    editor: 'Banpresto',
    hero: 'Lupin III',
    coverUrl: '/games_pictures/7fdb96db680c.jpg',
    releaseDate: '2004-11-25',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 0,
    platform: 'PlayStation 2',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
  {
    title: 'Lupin III : Umi ni Kieta Hihō',
    editor: 'Namco',
    hero: 'Lupin III',
    coverUrl:
      '/games_pictures/48e15b2852b9.jpg',
    releaseDate: '2004-08-05',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 0,
    platform: 'GameCube',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
  {
    title: 'Lupin III : Lupin est mort, Zenigata est amoureux',
    editor: 'Banpresto',
    hero: 'Lupin III',
    coverUrl:
      '/games_pictures/8f10220575a2.jpg',
    releaseDate: '2007-02-22',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 0,
    platform: 'PlayStation 2',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
  {
    title: "Lupin III : Le plus grand duel intellectuel de l'histoire",
    editor: 'Banpresto',
    hero: 'Lupin III',
    coverUrl: '/games_pictures/d0fc612fbdc1.jpg',
    releaseDate: '2010-09-16',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 0,
    platform: 'Nintendo DS',
    saga: 'Lupin III',
    platineTime: 0,
    description: '',
    fromEntity: {
      entityType: 'manga' as const,
      title: 'Lupin III',
      secondEntityKey: 'Monkey Punch',
    },
  },
];
