import { BaseGame } from '../../../models/game-model';

/** Catalogue saga Mario (jeux déplacés depuis base_games / base_games_api + ajouts). */
export const baseGamesMario: BaseGame[] = ([] = [
  {
    title: 'Super Mario 64',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/super_mario_64_2.webp',
    releaseDate: '1996-06-23',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 20,
    platform: 'Nintendo 64',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Galaxy',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/il_570xN.5937744444_j3z5.webp',
    releaseDate: '2007-11-12',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 35,
    platform: 'Wii',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Odyssey',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/81TksYoxfQL._UF1000,1000_QL80_.jpg',
    releaseDate: '2017-10-27',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 60,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Kart: Double Dash!!',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/81e0IWNn5eL._UF1000,1000_QL80_.jpg',
    releaseDate: '2003-11-07',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 25,
    platform: 'GameCube',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Kart Wii',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/mario-kart-wii-e2671.jpg',
    releaseDate: '2008-04-10',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 30,
    platform: 'Wii',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Strikers Charged Football',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/61j6R67dWeL._AC_UF1000,1000_QL80_.jpg',
    releaseDate: '2007-05-25',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 35,
    platform: 'Wii',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Kart 8 Deluxe',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/81EdgFXOWWL._UF1000,1000_QL80_.jpg',
    releaseDate: '2017-04-28',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 50,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party 5',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/81byWQum9AL.jpg',
    releaseDate: '2003-11-10',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 30,
    platform: 'GameCube',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party 6',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/Mario_Party_6_capa.png',
    releaseDate: '2004-12-06',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 30,
    platform: 'GameCube',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party 7',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/Mario_Party_7_Coverart.png',
    releaseDate: '2005-11-07',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 30,
    platform: 'GameCube',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party 8',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/91FQxPuzTQL.jpg',
    releaseDate: '2007-05-29',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 30,
    platform: 'Wii',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Party',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/81XdRd9UNZL.jpg',
    releaseDate: '2018-10-05',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 30,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Paper Mario',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/71GK7PP0tFL.jpg',
    releaseDate: '2007-04-09',
    averageTimeToFinish: 20,
    averageTimeToHundredPercent: 50,
    platform: 'Wii',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: "Super Mario World 2: Yoshi's Island",
    editor: 'Nintendo',
    hero: 'Yoshi',
    coverUrl:
      '/games_pictures/MV5BMWMxZWIyMGQtODI4Yi00MWQxLWJjOTMtZTgzZGY0YjIxODlmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    releaseDate: '2002-09-20',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 25,
    platform: 'Game Boy Advance',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario & Luigi: Superstar Saga',
    editor: 'Nintendo',
    hero: 'Mario & Luigi',
    coverUrl: '/games_pictures/MarioAndLuigiSuperstarSagaGBACoverArtUS.jpg',
    releaseDate: '2003-11-17',
    averageTimeToFinish: 20,
    averageTimeToHundredPercent: 30,
    platform: 'Game Boy Advance',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Power Tennis',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/MarioPowerTennis-GBA-EUR.webp',
    releaseDate: '2005-10-21',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 40,
    platform: 'Game Boy Advance',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario & Sonic aux Jeux Olympiques',
    editor: 'Sega',
    hero: '',
    coverUrl: '/games_pictures/mario-sonic-jo.jpg',
    releaseDate: '2007-11-23',
    averageTimeToFinish: 13,
    averageTimeToHundredPercent: 0,
    platform: 'Nintendo DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario & Sonic JO Hiver',
    editor: 'Sega',
    hero: 'Mario',
    coverUrl: '/games_pictures/mario-sonic-jo-hiver.jpg',
    releaseDate: '2009-10-16',
    averageTimeToFinish: 13,
    averageTimeToHundredPercent: 0,
    platform: 'Nintendo DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Kart DS',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/mario-kart-ds.jpg',
    releaseDate: '2005-11-11',
    averageTimeToFinish: 19,
    averageTimeToHundredPercent: 0,
    platform: 'Nintendo DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party DS',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/mario-party-ds.jpg',
    releaseDate: '2007-11-23',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 0,
    platform: 'Nintendo DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Slam Basketball',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/mario-slam-basketball.jpg',
    releaseDate: '2006-05-12',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 0,
    platform: 'Nintendo DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Bros.',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/dada45d52f9a.jpg',
    releaseDate: '1985-09-13',
    averageTimeToFinish: 4,
    averageTimeToHundredPercent: 8,
    platform: 'NES',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Bros.: The Lost Levels',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/7993f98bc1a5.jpg',
    releaseDate: '1986-06-03',
    averageTimeToFinish: 5,
    averageTimeToHundredPercent: 10,
    platform: 'Famicom Disk System',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Bros. 2',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/621f84dfa0e9.jpg',
    releaseDate: '1988-10-09',
    averageTimeToFinish: 6,
    averageTimeToHundredPercent: 12,
    platform: 'NES',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Bros. 3',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/cfbdfdc8bb83.jpg',
    releaseDate: '1988-10-23',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 16,
    platform: 'NES',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Land',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/aac526169975.jpg',
    releaseDate: '1989-04-21',
    averageTimeToFinish: 5,
    averageTimeToHundredPercent: 10,
    platform: 'Game Boy',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario World',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/bc1b5b2eed19.jpg',
    releaseDate: '1990-11-21',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 20,
    platform: 'SNES',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Sunshine',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/5d1169e3e8c3.jpg',
    releaseDate: '2002-07-19',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 40,
    platform: 'GameCube',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'New Super Mario Bros.',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/8c2688069fea.jpg',
    releaseDate: '2006-05-15',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 25,
    platform: 'Nintendo DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'New Super Mario Bros. Wii',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/4601e7c3124c.jpg',
    releaseDate: '2009-11-12',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 35,
    platform: 'Wii',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Galaxy 2',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/4611bbac9a24.jpg',
    releaseDate: '2010-05-23',
    averageTimeToFinish: 18,
    averageTimeToHundredPercent: 45,
    platform: 'Wii',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario 3D Land',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/2cb5965bc25b.jpg',
    releaseDate: '2011-11-03',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 30,
    platform: 'Nintendo 3DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'New Super Mario Bros. 2',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/9a1fd7efc454.jpg',
    releaseDate: '2012-07-28',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 25,
    platform: 'Nintendo 3DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'New Super Mario Bros. U',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/2287e0fd6da2.jpg',
    releaseDate: '2012-11-18',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 35,
    platform: 'Wii U',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario 3D World',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/29e122d7a050.jpg',
    releaseDate: '2013-11-21',
    averageTimeToFinish: 14,
    averageTimeToHundredPercent: 40,
    platform: 'Wii U',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Maker',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/5cdc13dcea58.jpg',
    releaseDate: '2015-09-10',
    averageTimeToFinish: 20,
    averageTimeToHundredPercent: 80,
    platform: 'Wii U',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Run',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/35052f078dfe.jpg',
    releaseDate: '2016-12-15',
    averageTimeToFinish: 4,
    averageTimeToHundredPercent: 12,
    platform: 'iOS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Maker 2',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/0ddcbb484518.jpg',
    releaseDate: '2019-06-28',
    averageTimeToFinish: 25,
    averageTimeToHundredPercent: 90,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario 3D All-Stars',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/4c9c13cbccf9.jpg',
    releaseDate: '2020-09-18',
    averageTimeToFinish: 40,
    averageTimeToHundredPercent: 120,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Bros. Wonder',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/217f7974dba7.jpg',
    releaseDate: '2023-10-20',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 35,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario RPG',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/826ac0bd21fd.jpg',
    releaseDate: '1996-03-09',
    averageTimeToFinish: 18,
    averageTimeToHundredPercent: 35,
    platform: 'SNES',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Kart',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/87b823580280.jpg',
    releaseDate: '1992-08-27',
    averageTimeToFinish: 6,
    averageTimeToHundredPercent: 15,
    platform: 'SNES',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Kart 64',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/f72b358ef588.jpg',
    releaseDate: '1996-12-14',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 25,
    platform: 'Nintendo 64',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Kart: Super Circuit',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/65ffb42e4360.jpg',
    releaseDate: '2001-07-21',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 22,
    platform: 'Game Boy Advance',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Kart 7',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/2e2e6ef9bbea.jpg',
    releaseDate: '2011-12-01',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 30,
    platform: 'Nintendo 3DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Kart 8',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/02b877d06615.jpg',
    releaseDate: '2014-05-29',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 45,
    platform: 'Wii U',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/00d6f22b38bc.jpg',
    releaseDate: '1998-12-18',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 35,
    platform: 'Nintendo 64',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party 2',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/7adbe3bfdc8a.jpg',
    releaseDate: '1999-12-17',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 35,
    platform: 'Nintendo 64',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party 3',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/9d4e65943da7.jpg',
    releaseDate: '2000-12-07',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 35,
    platform: 'Nintendo 64',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party 4',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/fad6a82c15ac.jpg',
    releaseDate: '2002-10-21',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 35,
    platform: 'GameCube',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party Advance',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/c510ce87f1a8.jpg',
    releaseDate: '2005-03-28',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 20,
    platform: 'Game Boy Advance',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party 9',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/a3379a8da549.jpg',
    releaseDate: '2012-03-02',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 30,
    platform: 'Wii',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party 10',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/bd42f37b9396.jpg',
    releaseDate: '2015-03-12',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 30,
    platform: 'Wii U',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party: Island Tour',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/963c22e2e6a2.jpg',
    releaseDate: '2013-11-22',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 25,
    platform: 'Nintendo 3DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party: Star Rush',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/db8dcaaf6d2a.jpg',
    releaseDate: '2016-10-07',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 25,
    platform: 'Nintendo 3DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Party: The Top 100',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/83b3eca1a481.jpg',
    releaseDate: '2017-11-10',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 22,
    platform: 'Nintendo 3DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Party Jamboree',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/3d89c7b9473f.jpg',
    releaseDate: '2024-10-17',
    averageTimeToFinish: 14,
    averageTimeToHundredPercent: 32,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Paper Mario',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/6e5c629aab13.jpg',
    releaseDate: '2000-08-11',
    averageTimeToFinish: 25,
    averageTimeToHundredPercent: 45,
    platform: 'Nintendo 64',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Paper Mario: La porte millénaire',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      'https://www.gamecash.fr/thumbnail-600/gc-paper-mario-la-porte-millenaire-e10068.jpg',
    releaseDate: '2004-07-22',
    averageTimeToFinish: 30,
    averageTimeToHundredPercent: 55,
    platform: 'GameCube',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Paper Mario: La porte millénaire (Switch)',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/296f8434e756.jpg',
    releaseDate: '2024-05-23',
    averageTimeToFinish: 30,
    averageTimeToHundredPercent: 55,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Paper Mario: Sticker Star',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/e3127d0b0bc1.jpg',
    releaseDate: '2012-11-11',
    averageTimeToFinish: 22,
    averageTimeToHundredPercent: 40,
    platform: 'Nintendo 3DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Paper Mario: Color Splash',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/dde082c62210.jpg',
    releaseDate: '2016-10-07',
    averageTimeToFinish: 22,
    averageTimeToHundredPercent: 40,
    platform: 'Wii U',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Paper Mario: The Origami King',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/c4bad77849c1.jpg',
    releaseDate: '2020-07-17',
    averageTimeToFinish: 28,
    averageTimeToHundredPercent: 50,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: "Luigi's Mansion",
    editor: 'Nintendo',
    hero: 'Luigi',
    coverUrl:
      '/games_pictures/0c350e9900e4.jpg',
    releaseDate: '2001-09-14',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 15,
    platform: 'GameCube',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: "Luigi's Mansion: Dark Moon",
    editor: 'Nintendo',
    hero: 'Luigi',
    coverUrl: '/games_pictures/af4d1a822e2b.jpg',
    releaseDate: '2013-03-24',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 25,
    platform: 'Nintendo 3DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: "Luigi's Mansion 3",
    editor: 'Nintendo',
    hero: 'Luigi',
    coverUrl: '/games_pictures/0dcf0f684c82.jpg',
    releaseDate: '2019-10-31',
    averageTimeToFinish: 15,
    averageTimeToHundredPercent: 30,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario & Luigi: Partners in Time',
    editor: 'Nintendo',
    hero: 'Mario & Luigi',
    coverUrl: '/games_pictures/25d519ca39e6.jpg',
    releaseDate: '2005-11-28',
    averageTimeToFinish: 22,
    averageTimeToHundredPercent: 38,
    platform: 'Nintendo DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: "Mario & Luigi: Bowser's Inside Story",
    editor: 'Nintendo',
    hero: 'Mario & Luigi',
    coverUrl: '/games_pictures/0f79c7a19d22.jpg',
    releaseDate: '2009-02-11',
    averageTimeToFinish: 25,
    averageTimeToHundredPercent: 42,
    platform: 'Nintendo DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario & Luigi: Dream Team',
    editor: 'Nintendo',
    hero: 'Mario & Luigi',
    coverUrl: '/games_pictures/92c6c79fd666.jpg',
    releaseDate: '2013-07-12',
    averageTimeToFinish: 28,
    averageTimeToHundredPercent: 48,
    platform: 'Nintendo 3DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario & Luigi: Paper Jam',
    editor: 'Nintendo',
    hero: 'Mario & Luigi',
    coverUrl: '/games_pictures/a0188fbff8c1.jpg',
    releaseDate: '2015-12-04',
    averageTimeToFinish: 24,
    averageTimeToHundredPercent: 42,
    platform: 'Nintendo 3DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Golf',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/f850d6c14ed9.jpg',
    releaseDate: '1999-06-11',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 25,
    platform: 'Nintendo 64',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Golf: Advance Tour',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/030948f862a9.jpg',
    releaseDate: '2004-06-22',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 28,
    platform: 'Game Boy Advance',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Golf: Toadstool Tour',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/e8f2e6306374.jpg',
    releaseDate: '2003-07-28',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 30,
    platform: 'GameCube',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Golf: World Tour',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/5526dbbd04e2.jpg',
    releaseDate: '2014-05-02',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 35,
    platform: 'Nintendo 3DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Golf: Super Rush',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/fb8fff794643.jpg',
    releaseDate: '2021-06-25',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 28,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Tennis',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/de7266a60b8f.jpg',
    releaseDate: '2000-07-21',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 25,
    platform: 'Nintendo 64',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Tennis: Ultra Smash',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/1dc757dc5091.jpg',
    releaseDate: '2015-11-20',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 22,
    platform: 'Wii U',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Tennis Aces',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/b30247f1b065.jpg',
    releaseDate: '2018-06-22',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 28,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Mario Strikers',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/df93bd61dc80.jpg',
    releaseDate: '2005-07-21',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 25,
    platform: 'GameCube',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Strikers: Battle League',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/a1f523ee3d35.jpg',
    releaseDate: '2022-06-10',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 30,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Superstar Baseball',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/e248288b9fc3.jpg',
    releaseDate: '2005-07-21',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 30,
    platform: 'GameCube',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Super Sluggers',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/3e7d57860ee9.jpg',
    releaseDate: '2008-08-25',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 35,
    platform: 'Wii',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Hoops 3-on-3',
    editor: 'Square Enix',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/836d06297fb6.png',
    releaseDate: '2006-07-27',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 22,
    platform: 'Nintendo DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Sports Mix',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/38ead1fafdfe.jpg',
    releaseDate: '2010-11-25',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 28,
    platform: 'Wii',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Captain Toad: Treasure Tracker',
    editor: 'Nintendo',
    hero: 'Captain Toad',
    coverUrl: '/games_pictures/debb4159d914.jpg',
    releaseDate: '2014-11-13',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 20,
    platform: 'Wii U',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario + Rabbids Kingdom Battle',
    editor: 'Ubisoft',
    hero: 'Mario',
    coverUrl: '/games_pictures/562b9def2fec.jpg',
    releaseDate: '2017-08-29',
    averageTimeToFinish: 25,
    averageTimeToHundredPercent: 45,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario + Rabbids Sparks of Hope',
    editor: 'Ubisoft',
    hero: 'Mario',
    coverUrl: '/games_pictures/72dbd55cf34d.jpg',
    releaseDate: '2022-10-20',
    averageTimeToFinish: 30,
    averageTimeToHundredPercent: 55,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: "Super Mario World 2: Yoshi's Island (SNES)",
    editor: 'Nintendo',
    hero: 'Yoshi',
    coverUrl:
      '/games_pictures/27dce6a90a26.jpg',
    releaseDate: '1995-08-05',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 22,
    platform: 'SNES',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: "Yoshi's Story",
    editor: 'Nintendo',
    hero: 'Yoshi',
    coverUrl:
      '/games_pictures/08ede505ab2e.jpg',
    releaseDate: '1997-12-21',
    averageTimeToFinish: 6,
    averageTimeToHundredPercent: 15,
    platform: 'Nintendo 64',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: "Yoshi's New Island",
    editor: 'Nintendo',
    hero: 'Yoshi',
    coverUrl: '/games_pictures/81be552b530d.jpg',
    releaseDate: '2014-03-14',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 22,
    platform: 'Nintendo 3DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: "Yoshi's Woolly World",
    editor: 'Nintendo',
    hero: 'Yoshi',
    coverUrl: '/games_pictures/fe6db7028c4b.jpg',
    releaseDate: '2015-06-25',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 28,
    platform: 'Wii U',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: "Yoshi's Crafted World",
    editor: 'Nintendo',
    hero: 'Yoshi',
    coverUrl: '/games_pictures/c0647a89c290.jpg',
    releaseDate: '2019-03-29',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 28,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario vs. Donkey Kong',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/b312c72c7ec8.jpg',
    releaseDate: '2004-05-24',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 22,
    platform: 'Game Boy Advance',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario vs. Donkey Kong 2: March of the Minis',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/e8ee68140f6d.jpg',
    releaseDate: '2006-09-25',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 22,
    platform: 'Nintendo DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario vs. Donkey Kong: Mini-Land Mayhem!',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/30e07e587a62.jpg',
    releaseDate: '2010-11-14',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 22,
    platform: 'Nintendo DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario vs. Donkey Kong: Tipping Stars',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/3c28a73e09f9.jpg',
    releaseDate: '2015-03-05',
    averageTimeToFinish: 8,
    averageTimeToHundredPercent: 18,
    platform: 'Wii U',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario vs. Donkey Kong (Switch)',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: '/games_pictures/8d8531f09951.jpg',
    releaseDate: '2024-02-16',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 25,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Dr. Mario',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl: 'https://www.gamecash.fr/thumbnail-400-450/dr-mario-e59466.jpg',
    releaseDate: '1990-07-27',
    averageTimeToFinish: 3,
    averageTimeToHundredPercent: 10,
    platform: 'NES',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario Pinball Land',
    editor: 'Nintendo',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/4ba6e4aeb6e7.jpg',
    releaseDate: '2004-09-13',
    averageTimeToFinish: 6,
    averageTimeToHundredPercent: 15,
    platform: 'Game Boy Advance',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Super Princess Peach',
    editor: 'Nintendo',
    hero: 'Peach',
    coverUrl:
      '/games_pictures/531e75269a93.jpg',
    releaseDate: '2005-10-20',
    averageTimeToFinish: 10,
    averageTimeToHundredPercent: 20,
    platform: 'Nintendo DS',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Princess Peach: Showtime!',
    editor: 'Nintendo',
    hero: 'Princess Peach',
    coverUrl:
      '/games_pictures/c85901dba3ee.jpg',
    releaseDate: '2024-03-22',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 22,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario & Sonic aux Jeux Olympiques de Londres 2012',
    editor: 'Sega',
    hero: 'Mario',
    coverUrl: '/games_pictures/faf770fab958.jpg',
    releaseDate: '2011-11-15',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 30,
    platform: 'Wii',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario & Sonic aux Jeux Olympiques de Rio 2016',
    editor: 'Sega',
    hero: 'Mario',
    coverUrl: '/games_pictures/4882d7e01c53.jpg',
    releaseDate: '2016-06-23',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 30,
    platform: 'Wii U',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: 'Mario & Sonic aux Jeux Olympiques : Tokyo 2020',
    editor: 'Sega',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/211974fbaf74.jpg',
    releaseDate: '2019-11-01',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 35,
    platform: 'Nintendo Switch',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
  {
    title: "Mario & Sonic aux Jeux Olympiques d'hiver ",
    editor: 'Sega',
    hero: 'Mario',
    coverUrl:
      '/games_pictures/57e2b8eedbd2.jpg',
    releaseDate: '2009-10-13',
    averageTimeToFinish: 12,
    averageTimeToHundredPercent: 30,
    platform: 'Wii',
    saga: 'Mario',
    platineTime: 0,
    description: '',
    fromEntity: null,
  },
]);
