import { UserMusic } from '../../../../../models/music-model';

export const musicsOrelsan: UserMusic[] = [
  // Album : Perdu d'avance (2009)
  {
    title: 'Étoiles Invisibles',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 200,
  },
  {
    title: 'Changement',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'Soirée ratée',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'Différent',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'No Life',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 120,
  },
  {
    title: 'Pour le pire',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 200,
  },
  {
    title: "Perdu d'avance",
    artist: 'Orelsan',
    rating: 0,
    timesListened: 200,
  },
  {
    title: 'Gros poisson dans une petite mare',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 180,
  },
  {
    title: 'Logo dans le ciel',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 180,
  },
  {
    title: '50 pour cent',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 230,
  },
  {
    title: 'Jimmy Punchline',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 230,
  },
  {
    title: 'Entre bien et mal (feat. Gringe)',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'Courez courez',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 200,
  },
  {
    title: "La peur de l'échec (feat. Ron Thal)",
    artist: 'Orelsan',
    rating: 0,
    timesListened: 180,
  },

  // Album : Le Chant des sirènes (2011)
  {
    title: 'Raelsan',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'Le Chant des sirènes',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 120,
  },
  {
    title: "Plus rien ne m'étonne",
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'Mauvaise idée',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 120,
  },
  {
    title: 'Double vie',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'Finir mal',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 230,
  },
  {
    title: 'Si seul',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 200,
  },
  {
    title: 'Des trous dans la tête',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 180,
  },
  {
    title: 'La Petite Marchande de porte-clefs',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 20,
  },
  {
    title: '1990',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: '2010',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 180,
  },
  {
    title: 'La Morale',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 100,
  },
  {
    title: 'Elle viendra quand même',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'Suicide social',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'La Terre est ronde',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 180,
  },
  {
    title: 'Ils sont cools',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 250,
  },

  // Album : La fête est finie (2017)
  {
    title: 'San',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 200,
  },
  {
    title: 'La fête est finie',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 70,
  },
  {
    title: 'Basique',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 70,
  },
  {
    title: 'Tout va bien',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 80,
  },
  {
    title: 'Défaite de famille',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'La lumière',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 50,
  },
  {
    title: 'Bonne meuf',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'Zone',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'Dans ma ville, on traîne',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 100,
  },
  {
    title: 'La pluie',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 120,
  },
  {
    title: 'Paradis',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: "Quand est-ce que ça s'arrête",
    artist: 'Orelsan',
    rating: 0,
    timesListened: 100,
  },
  {
    title: 'Christophe',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 100,
  },
  {
    title: 'Notes pour trop tard',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 200,
  },

  // Album : La fête est finie - Épilogue (2018)
  {
    title: 'Rêves bizarres',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 50,
  },
  {
    title: 'Fantômes',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 100,
  },
  {
    title: 'Discipline',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 100,
  },
  {
    title: 'Adieu les filles',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 100,
  },
  {
    title: 'Tout ce que je sais',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 100,
  },
  {
    title: 'Épilogue',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 100,
  },
  {
    title: 'Mes grands-parents',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 150,
  },
  {
    title: 'Excuses ou mensonges',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 100,
  },
  {
    title: 'La famille, la famille',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 120,
  },
  {
    title: 'Dis-moi',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 100,
  },
  {
    title: 'Shonen',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 77,
  },
  {
    title: 'La Quête',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 66,
  },
  {
    title: "L'odeur de l'essence",
    artist: 'Orelsan',
    rating: 0,
    timesListened: 65,
  },
  {
    title: 'Du propre',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 67,
  },
  {
    title: 'Rêve mieux',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 48,
  },
  {
    title: 'Bébéboa',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 36,
  },
  {
    title: 'Manifeste',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 59,
  },
  {
    title: 'Dernier verre',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 32,
  },
  {
    title: 'Ensemble',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 46,
  },
  {
    title: 'Casseurs Flowters Infinity',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 46,
  },
  {
    title: 'Athéna',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 45,
  },
  {
    title: 'Baise le monde',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 55,
  },
  {
    title: 'Jour meilleur',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 40,
  },
  {
    title: 'Seul avec du monde autour',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 84,
  },
  {
    title: 'Civilisation',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 48,
  },

  // Album : Civilisation Perdue (Réédition 2022)
  {
    title: 'Intro Civilisation perdue',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 59,
  },
  {
    title: 'Les aventures de Minisan',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 21,
  },
  {
    title: 'Toujours perdu quand même',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 16,
  },
  {
    title: 'Juste un dernier',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 18,
  },
  {
    title: 'Ok... Super...',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 18,
  },
  {
    title: 'Ah la France',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 12,
  },
  {
    title: 'Point de rupture',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 14,
  },
  {
    title: 'Nous contre le monde',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 8,
  },
  {
    title: 'Évidemment',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 13,
  },
  {
    title: 'On a gagné',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 5,
  },

  // Album : La fuite en avant (2025)
  {
    title: 'Le pacte',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Plus rien (feat. Lilas)',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Ailleurs',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Boss',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 3,
  },
  {
    title: 'Deux et demi',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Osaka',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Encore une fois (feat. Yamê)',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Internet',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Dans quelques mois',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Oulalalala (feat. Fifty Fifty)',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: "Tellement d'amis",
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'La petite voix',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Sama',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Soleil levant (feat. SDM)',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Les monstres',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Épiphanie',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Yoroï (feat. Thomas Bangalter)',
    artist: 'Orelsan',
    rating: 0,
    timesListened: 1,
  },
  {
    title: 'Qui dit mieux (feat. Orelsan, Vald & Suikon Blaz AD)',
    artist: 'Gringe',
    rating: 0,
    timesListened: 12,
  },
];
