import { UserGames } from '../../../../models/game-model';

export const guillaumeGameListGames: UserGames = [
  {
    title: 'Black Myth : Wukong',
    editor: 'Game Science',
    rating: 0,
    timesFinished: 0,
    additionnalEstimatedTime: 0,
    timesFinishedHundredPercent: 0,
    platined: false,
    owned: false,
    gamelistPriority: 1,
    wantToPlayAgain: false,
    sessions: [],
  },
  {
    title: 'Clair Obscur : Expedition 33',
    editor: 'Sandfall Interactive',
    rating: 0,
    timesFinished: 0,
    additionnalEstimatedTime: 0,
    timesFinishedHundredPercent: 0,
    platined: false,
    owned: false,
    gamelistPriority: 3,
    wantToPlayAgain: false,
    sessions: [],
  },
  {
    title: 'Ratchet & Clank : Rift Apart',
    editor: 'Insomniac Games',
    rating: 0,
    timesFinished: 0,
    additionnalEstimatedTime: 0,
    timesFinishedHundredPercent: 0,
    platined: false,
    owned: false,
    gamelistPriority: 1,
    wantToPlayAgain: false,
    sessions: [],
  },
];
