import { UserGames } from '../../../../models/game-model';

export const guillaumeGameListGames: UserGames = [
  {
    title: 'Clair Obscur : Expedition 33',
    editor: 'Sandfall Interactive',
    rating: 0,
    owned: false,
    gamelistPriority: 3,
    wantToPlayAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    sessions: [],
  },

  {
    title: "The Legend of Zelda: Majora's Mask",
    editor: 'Nintendo',
    rating: 0,
    owned: false,
    gamelistPriority: 1,
    wantToPlayAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    sessions: [],
  },
  {
    title: 'The Legend of Zelda: A Link Between Worlds',
    editor: 'Nintendo',
    rating: 0,
    owned: false,
    gamelistPriority: 1,
    wantToPlayAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    sessions: [],
  },
  {
    title:
      'Cadence of Hyrule: Crypt of the NecroDancer Featuring The Legend of Zelda',
    editor: 'Brace Yourself Games',
    rating: 0,
    owned: false,
    gamelistPriority: 1,
    wantToPlayAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    sessions: [],
  },
  {
    title: 'BioShock Remastered (Complete Edition)',
    editor: '2K Games',
    rating: 0,
    owned: false,
    gamelistPriority: 1,
    wantToPlayAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    sessions: [],
  },
  {
    title: 'God of War III',
    editor: 'Santa Monica Studio',
    rating: 0,
    owned: false,
    gamelistPriority: 1,
    wantToPlayAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    sessions: [
      {
        finishedGame: false,
        finishedGameWithHundredPercent: false,
        platinedGame: false,
        additionnalEstimatedTime: 0,
        sessionStartDate: '',
        sessionEndDate: '',
        currentlyPlaying: true,
      },
    ],
  },
  {
    title: 'Resident Evil 4',
    editor: 'Capcom',
    rating: 0,
    owned: false,
    gamelistPriority: 1,
    wantToPlayAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    sessions: [],
  },
  {
    title: 'Portal',
    editor: 'Valve',
    rating: 0,
    owned: false,
    gamelistPriority: 1,
    wantToPlayAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    sessions: [],
  },
  {
    title: 'Uncharted 2 : Among Thieves',
    editor: 'Naughty Dog',
    rating: 0,
    owned: false,
    gamelistPriority: 1,
    wantToPlayAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    sessions: [],
  },
];
