import { BaseBook } from '../../../models/book-model';

export const baseBooksRomance: BaseBook[] = [
  {
    title: "La carte qui mène jusqu'à toi",
    author: 'Joseph Monninger',
    coverUrl: '/books_pictures/817fEwfe34L._AC_UF1000,1000_QL80_.jpg',
    pages: 368,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2020-08-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les liaisons dangereuses',
    author: 'Eny Heli',
    coverUrl: '/books_pictures/les-liaisons-dangereuses-5536921.jpg',
    pages: 400,
    genre: ['Dark Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Castel Boy',
    author: 'Eny Heli',
    coverUrl: '/books_pictures/71AGuHSj0mL.jpg',
    pages: 500,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Orgueil et Préjugés',
    author: 'Jane Austen',
    coverUrl: '/books_pictures/orgueil_et_prejuges.jpg',
    pages: 279,
    genre: ['Classiques', 'Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1813-01-28',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'Emma',
    author: 'Jane Austen',
    coverUrl: '/books_pictures/81vfJi+HAVL._AC_UF1000,1000_QL80_.jpg',
    pages: 474,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1815-12-23',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Raison et sentiments',
    author: 'Jane Austen',
    coverUrl: '/books_pictures/a33514c317d4.jpg',
    pages: 416,
    genre: ['Classiques', 'Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1811-10-30',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    coverUrl: '/books_pictures/jane_eyre.jpg',
    pages: 532,
    genre: ['Romance', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1847-10-16',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'Gatsby le magnifique',
    author: 'F. Scott Fitzgerald',
    coverUrl: '/books_pictures/9782246495512-T.webp',
    pages: 180,
    genre: ['Romance', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1925-04-10',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Les pages de notre amour',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/Les-pages-de-notre-amour.jpg',
    pages: 224,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1996-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Nos étoiles contraires',
    author: 'John Green',
    coverUrl: '/books_pictures/f2db9b91755d.jpg',
    pages: 336,
    genre: ['Romance', 'Jeunesse'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2012-01-10',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'À tout jamais',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/71uDPcPonsL._UF1000,1000_QL80_.jpg',
    pages: 240,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2004-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le porte bonheur',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/41TwzJl0j3L._SX195_.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2003-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Memento mori',
    author: 'Eny Heli',
    coverUrl: '/books_pictures/71E6TZcFrdL.jpg',
    pages: 300,
    genre: ['Dark Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un choix',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/Un-choix.jpg',
    pages: 280,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Une seconde chance',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/61dlBm9b5XL._AC_UF1000,1000_QL80_.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Adam',
    author: 'Eny Heli',
    coverUrl: '/books_pictures/61F72yE7irL.jpg',
    pages: 350,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Roméo et Juliette',
    author: 'William Shakespeare',
    coverUrl: '/books_pictures/71crcf7etvL._SY522_.jpg',
    pages: 256,
    genre: ['Romance', 'Classiques', 'Théâtre'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1597-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: "L'amour aux temps du choléra",
    author: 'Gabriel García Márquez',
    coverUrl: '/books_pictures/81d2fnWZbWL._AC_UF1000,1000_QL80_.jpg',
    pages: 479,
    genre: ['Romance', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1985-03-27',
    description: '',
    countryOrigin: 'Colombie',
    selectDisplayOrder: 30,
  },
  {
    title: 'Geisha',
    author: 'Arthur Golden',
    coverUrl: '/books_pictures/4a99ea23b752.jpg',
    pages: 512,
    genre: ['Romance', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1997-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Un jour',
    author: 'David Nicholls',
    coverUrl: '/books_pictures/bd549a2212a9.jpg',
    pages: 544,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2009-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 20,
  },
  {
    title: 'P.S. I Love You',
    author: 'Cecelia Ahern',
    coverUrl: '/books_pictures/06a7b7ddca6e.jpg',
    pages: 416,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2004-01-01',
    description: '',
    countryOrigin: 'Irlande',
    selectDisplayOrder: 20,
  },
  {
    title: 'Love, Actually',
    author: "Philip O'Connor",
    coverUrl: '/books_pictures/16354f0488d3.webp',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 20,
  },
  {
    title: 'Tout le bleu du ciel',
    author: 'Melissa Da Costa',
    coverUrl: '/books_pictures/56_9782253934103_1_75.jpg',
    pages: 840,
    genre: ['Romance', 'Aventure'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: "Le diable s'habille en Prada",
    author: 'Lauren Weisberger',
    coverUrl: '/books_pictures/7deb767d9518.jpg',
    pages: 448,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2003-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Vengeance en Prada : Le Retour du diable',
    author: 'Lauren Weisberger',
    coverUrl: '/books_pictures/9ba073d78563.jpg',
    pages: 512,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-06-04',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: "L'enfer est pavé de bonnes intentions",
    author: 'Lauren Weisberger',
    coverUrl: '/books_pictures/340dc7e9a0f1.jpg',
    pages: 384,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Le Journal de Bridget Jones',
    author: 'Helen Fielding',
    coverUrl: '/books_pictures/f00e0bc8adf0.jpg',
    pages: 416,
    genre: ['Romance'],
    saga: 'Bridget Jones',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '1996-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 20,
  },
  {
    title: "Bridget Jones : L'Âge de raison",
    author: 'Helen Fielding',
    coverUrl: '/books_pictures/6e59eb50dce6.jpg',
    pages: 432,
    genre: ['Romance'],
    saga: 'Bridget Jones',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '1999-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 20,
  },
  {
    title: 'Bridget Jones folle de lui',
    author: 'Helen Fielding',
    coverUrl: '/books_pictures/85bced2f2221.jpg',
    pages: 512,
    genre: ['Romance'],
    saga: 'Bridget Jones',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 20,
  },
  {
    title: 'Bridget Jones : Baby',
    author: 'Helen Fielding',
    coverUrl: '/books_pictures/a8070e810588.jpg',
    pages: 352,
    genre: ['Romance'],
    saga: 'Bridget Jones',
    sagaOrder: 4,
    sagaFinished: false,
    releaseDate: '2016-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 20,
  },
  {
    title: 'Quatre filles et un jean',
    author: 'Ann Brashares',
    coverUrl: '/books_pictures/ea6ffabc4d52.jpg',
    pages: 384,
    genre: ['Romance', 'Jeunesse'],
    saga: 'Quatre filles et un jean',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2001-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Autant en emporte le vent',
    author: 'Margaret Mitchell',
    coverUrl: '/books_pictures/Autant-en-emporte-le-vent.jpg',
    pages: 1037,
    genre: ['Romance', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1936-06-30',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Il était une fois: Tome 1 : Mon premier baiser',
    author: 'Chlore Smythe, Juliette Pierce',
    coverUrl: '/books_pictures/81CXdOT0uPL._UF350,350_QL50_.jpg',
    pages: 468,
    genre: ['Romance'],
    saga: 'Il était une fois',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Il était une fois: Tome 2 : Mon dernier amour',
    author: 'Chlore Smythe, Juliette Pierce',
    coverUrl: '/books_pictures/71tcmDP0HPL.jpg',
    pages: 533,
    genre: ['Dark Romance'],
    saga: 'Il était une fois',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2023-11-23',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les filles du Docteur March',
    author: 'Louisa May Alcott',
    coverUrl: '/books_pictures/9782381228365.jpg',
    pages: 400,
    genre: ['Romance', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1868-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: "L'écume des jours",
    author: 'Boris Vian',
    coverUrl: '/books_pictures/81WmGQbXiSL.jpg',
    pages: 250,
    genre: ['Romance', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1947-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Cyrano de Bergerac',
    author: 'Edmond Rostand',
    coverUrl: '/books_pictures/Cyrano-de-Bergerac.jpg',
    pages: 200,
    genre: ['Romance', 'Classiques', 'Théâtre'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1897-12-28',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'La dernière chanson',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/550x838.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2009-09-08',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Fais un voeu',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/61WDtAa9gxL._AC_UF1000,1000_QL80_.jpg',
    pages: 300,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2020-09-29',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Au rythme de ton souffle',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/au-rythme-de-ton-souffle.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-09-28',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un havre de paix',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/un-havre-de-paix-5444321.jpg',
    pages: 300,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-09-20',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Cinquante nuances de Grey',
    author: 'E. L. James',
    coverUrl: '/books_pictures/1271b5c6c624.jpg',
    pages: 528,
    genre: ['Romance', 'Dark Romance'],
    saga: 'Cinquante nuances',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '2012-05-02',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Cinquante nuances plus sombres',
    author: 'E. L. James',
    coverUrl: '/books_pictures/6c72b059e098.jpg',
    pages: 544,
    genre: ['Romance', 'Dark Romance'],
    saga: 'Cinquante nuances',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '2012-09-12',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Cinquante nuances plus claires',
    author: 'E. L. James',
    coverUrl: '/books_pictures/61bcadedb6e3.jpg',
    pages: 544,
    genre: ['Romance', 'Dark Romance'],
    saga: 'Cinquante nuances',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '2012-11-14',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Mange, prie, aime',
    author: 'Elizabeth Gilbert',
    coverUrl: '/books_pictures/64a1bf94536f.jpg',
    pages: 416,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2006-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Nos cœurs meurtris',
    author: 'Tess Wakefield',
    coverUrl: '/books_pictures/43e1724f9873.jpg',
    pages: 304,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
];
