import { BaseBook } from '../../../models/book-model';

/** Livres ajoutés depuis l'import Babelio de Laural (booksNotAdded). */
export const baseBooksFromLaural: BaseBook[] = [
  {
    title: '4.48 Psychose',
    author: 'Sarah Kane',
    coverUrl: '/books_pictures/2c26b9f2c0d7.jpg',
    pages: 206,
    genre: ['Théâtre'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2011-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: '54 minutes',
    author: 'Marieke Nijkamp',
    coverUrl: '/books_pictures/9d8cedbcaf32.jpg',
    pages: 304,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2004-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: '8,2 secondes',
    author: 'Maxime Chattam',
    coverUrl: '/books_pictures/cb57e57f33e5.jpg',
    pages: 384,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2005-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'À couper le souffle',
    author: 'Alexis Laipsker',
    coverUrl: '/books_pictures/32cd215f6bb6.jpg',
    pages: 125,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1997-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "À l'aube, les flammes",
    author: 'K. X. Song',
    coverUrl: '/books_pictures/8f71a53aaab4.jpg',
    pages: 432,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "À la recherche de l'esprit renard, tome 1 : Albans",
    author: 'Alix Naudot Guillerm',
    coverUrl: '/books_pictures/451f4745a8a1.jpg',
    pages: 415,
    genre: ['Fantasy'],
    saga: "À la recherche de l'esprit renard",
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2025-04-03',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Alex',
    author: 'Pierre Lemaitre',
    coverUrl: '/books_pictures/3383348ca163.jpg',
    pages: 353,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2011-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "All of us villains, tome 1 : Le tournoi d'Ilvernath",
    author: 'C. L. Herman',
    coverUrl: '/books_pictures/38a009b7c88c.jpg',
    pages: 432,
    genre: ['Fantasy'],
    saga: 'All of us villains',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2025-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Altérée',
    author: 'Charly Lemega',
    coverUrl: '/books_pictures/2a3cbeb832cb.jpg',
    pages: 181,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Anatomy',
    author: 'Dana Schwartz',
    coverUrl: '/books_pictures/a7e4a7bf9192.jpg',
    pages: 352,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Appleseed',
    author: 'Matt Bell',
    coverUrl: '/books_pictures/f95fbb492654.jpg',
    pages: 480,
    genre: ['Science Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Babel',
    author: 'R. F. Kuang',
    coverUrl: '/books_pictures/1311a463209d.jpg',
    pages: 560,
    genre: ['Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Beauté fatale',
    author: 'Mona Chollet',
    coverUrl: '/books_pictures/781741c6a655.jpg',
    pages: 235,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2012-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Beloved',
    author: 'Toni Morrison',
    coverUrl: '/books_pictures/097b29761666.jpg',
    pages: 330,
    genre: ['Fiction historique'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1987-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Better Than the Movies',
    author: 'Lynn Painter',
    coverUrl: '/books_pictures/240325fb6bc8.jpg',
    pages: 368,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Black girl unlimited',
    author: 'Echo Brown',
    coverUrl: '/books_pictures/87e4e80c4c0e.webp',
    pages: 304,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2020-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Bonjour tristesse',
    author: 'Françoise Sagan',
    coverUrl: '/books_pictures/e49c19cf8086.jpg',
    pages: 154,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1954-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Bonne nuit Punpun, tome 1',
    author: 'Inio Asano',
    coverUrl: '/books_pictures/3123dab13bd9.jpg',
    pages: 224,
    genre: ['Jeunesse'],
    saga: 'Bonne nuit Punpun',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2012-01-01',
    description: '',
    countryOrigin: 'Japon',
    selectDisplayOrder: 0,
  },
  {
    title: 'Boys of Tommen, tome 1 : Binding 13',
    author: 'Chloe Walsh',
    coverUrl: '/books_pictures/1c1873536fcd.jpg',
    pages: 636,
    genre: ['Romance'],
    saga: 'Boys of Tommen',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2020-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Boys of Tommen, tome 2 : Keeping 13',
    author: 'Chloe Walsh',
    coverUrl: '/books_pictures/3fb654ec21ec.jpg',
    pages: 636,
    genre: ['Romance'],
    saga: 'Boys of Tommen',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2020-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Breathe',
    author: 'Eva Sorn',
    coverUrl: '/books_pictures/20a47a3e5b82.jpg',
    pages: 120,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1996-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Bréviaire du chaos',
    author: 'Albert Caraco',
    coverUrl: '/books_pictures/15ebc9f82df4.jpg',
    pages: 126,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1982-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Bride',
    author: 'Ali Hazelwood',
    coverUrl: '/books_pictures/f4dd67437420.jpg',
    pages: 401,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Bunny',
    author: 'Mona Awad',
    coverUrl: '/books_pictures/13d77c594aa7.jpg',
    pages: 320,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'Canada',
    selectDisplayOrder: 0,
  },
  {
    title: 'Cadavre exquis',
    author: 'Agustina Bazterrica',
    coverUrl: '/books_pictures/88b4ce8363dd.jpeg',
    pages: 124,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'Argentine',
    selectDisplayOrder: 0,
  },
  {
    title: 'Caraval, tome 1',
    author: 'Stephanie Garber',
    coverUrl: '/books_pictures/27da0ae997ff.jpg',
    pages: 436,
    genre: ['Fantasy'],
    saga: 'Caraval',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: 'Espagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ce coeur empoisonné',
    author: 'Kalynn Bayron',
    coverUrl: '/books_pictures/1c8c73f77e6d.jpg',
    pages: 561,
    genre: ['Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ce que font les filles à la nuit tombée',
    author: 'Nora Lake',
    coverUrl: '/books_pictures/97296d491721.webp',
    pages: 320,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: "Cérémonie d'orage",
    author: 'Julia Armfield',
    coverUrl: '/books_pictures/b99aeb21f656.jpg',
    pages: 224,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ceux de la montagne évanouie',
    author: 'Anne-Claire Doly',
    coverUrl: '/books_pictures/040a1ee41c3e.jpg',
    pages: 256,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ceux qui changent et ceux qui meurent',
    author: 'Barbara Comyns',
    coverUrl: '/books_pictures/4410b456e3cd.jpg',
    pages: 190,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1981-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Check & Mate',
    author: 'Ali Hazelwood',
    coverUrl: '/books_pictures/7fef9d40e86e.jpg',
    pages: 368,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Cinq leçons sur la psychanalyse',
    author: 'Sigmund Freud',
    coverUrl: '/books_pictures/2e5dda29746b.jpg',
    pages: 157,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1975-01-01',
    description: '',
    countryOrigin: 'Autriche',
    selectDisplayOrder: 0,
  },
  {
    title: 'Clamser à Tataouine',
    author: 'Raphaël Quenard',
    coverUrl: '/books_pictures/7615cd520abd.jpg',
    pages: 224,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Comme si la fin n'existait pas",
    author: 'Brianna Bourne',
    coverUrl: '/books_pictures/a2aedf7e8ddb.jpg',
    pages: 368,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Comment voyager dans les Terres Oubliées',
    author: 'Sarah Brooks',
    coverUrl: '/books_pictures/66c47b02b49c.jpg',
    pages: 506,
    genre: ['Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1890-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Curious Tides, tome 1 : De la Lune et des Marées',
    author: 'Pascale Lacelle',
    coverUrl:
      '/books_pictures/curious-tides-tome-1-de-la-lune-et-des-marees-5348193.jpg',
    pages: 635,
    genre: ['Fantasy'],
    saga: 'Curious Tides',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Dans la forêt profonde',
    author: 'Kate Pearsall',
    coverUrl: '/books_pictures/a5e0293b0050.jpg',
    pages: 191,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Dans la vie des pantins',
    author: 'T. J. Klune',
    coverUrl: '/books_pictures/7fbd19fc7daa.jpg',
    pages: 359,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Dans notre univers, nous sommes infinis',
    author: 'Sarah Sprinz',
    coverUrl: '/books_pictures/8ef81d038440.jpg',
    pages: 464,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'Allemagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'Days',
    author: 'James Lovegrove',
    coverUrl: '/books_pictures/148b46dc71e4.jpg',
    pages: 333,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1997-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: "De l'inconvénient d'être né",
    author: 'Emil Cioran',
    coverUrl: '/books_pictures/6ecb5f5827c4.jpg',
    pages: 219,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1973-01-01',
    description: '',
    countryOrigin: 'Roumanie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Dernière soirée',
    author: 'Lisa Gardner',
    coverUrl: '/books_pictures/d71600bd2bf4.jpeg',
    pages: 251,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1961-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Deux vérités, un mensonge',
    author: 'Claire McGowan',
    coverUrl: '/books_pictures/a3f82b21f088.jpg',
    pages: 411,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1682-01-01',
    description: '',
    countryOrigin: 'Pays-Bas',
    selectDisplayOrder: 0,
  },
  {
    title: 'Devenir Fasciste : Ma Thérapie de conversion',
    author: 'Mark Fortier',
    coverUrl: '/books_pictures/9e0b57521c89.jpg',
    pages: 248,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1997-01-01',
    description: '',
    countryOrigin: 'Canada',
    selectDisplayOrder: 0,
  },
  {
    title: 'Devenir Zéro',
    author: 'Anthony McCarten',
    coverUrl: '/books_pictures/6c47623b1b9d.jpg',
    pages: 378,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2020-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Du thé pour les fantômes',
    author: 'Chris Vuklisevic',
    coverUrl: '/books_pictures/1973a33ab76c.jpg',
    pages: 416,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'Espagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'Duchess',
    author: 'Chris Whitaker',
    coverUrl: '/books_pictures/3a182727f2a5.jpg',
    pages: 519,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ecchymoses',
    author: 'Carelle. D',
    coverUrl: '/books_pictures/a39409463959.jpeg',
    pages: 172,
    genre: ['Poésie'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2010-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Éclosion',
    author: 'Ezekiel Boone',
    coverUrl: '/books_pictures/5fa0a6d5142d.jpg',
    pages: 56,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2001-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Écosse : Hadrien et la licorne',
    author: 'Assa Samaké-Roman',
    coverUrl: '/books_pictures/5d6fd2d08b41.jpg',
    pages: 96,
    genre: ['Jeunesse'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Entre leurs mains',
    author: 'Annelise Heurtier',
    coverUrl: '/books_pictures/a0e1e6113055.jpg',
    pages: 224,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1792-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Esprit d'hiver",
    author: 'Laura Kasischke',
    coverUrl: '/books_pictures/30723248e9d5.jpg',
    pages: 280,
    genre: ['Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Et si tu revenais',
    author: 'Coralie Janne',
    coverUrl: '/books_pictures/12bbe9942a3a.jpg',
    pages: 288,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2025-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Face à face (nouvelle)',
    author: 'Alexis Laipsker',
    coverUrl: '/books_pictures/a73b8efaf194.jpg',
    pages: 368,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2008-01-01',
    description: '',
    countryOrigin: 'Pays-Bas',
    selectDisplayOrder: 0,
  },
  {
    title: 'Faire mouche',
    author: 'Vincent Almendros',
    coverUrl: '/books_pictures/707fd16063e7.jpg',
    pages: 126,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Falling into pieces',
    author: 'Sheily Larash',
    coverUrl: '/books_pictures/a38eccaee5cb.jpg',
    pages: 280,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2014-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Fenêtre sur le rien',
    author: 'Emil Cioran',
    coverUrl: '/books_pictures/d0da45c6bcc5.jpg',
    pages: 150,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1990-01-01',
    description: '',
    countryOrigin: 'Roumanie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Hantise (Maison hantée)',
    author: 'Shirley Jackson',
    coverUrl: '/books_pictures/a97099cf9411.jpg',
    pages: 253,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1999-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Heartless Hunter, tome 1',
    author: 'Kristen Ciccarelli',
    coverUrl: '/books_pictures/2febefc31a11.jpg',
    pages: 410,
    genre: ['Fantasy'],
    saga: 'Heartless Hunter',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Histoire de la fille qui ne voulait tuer personne',
    author: 'Jérôme Leroy',
    coverUrl: '/books_pictures/eb24a8d3de3f.jpg',
    pages: 184,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Holly',
    author: 'Stephen King',
    coverUrl: '/books_pictures/8054cf8d6501.jpg',
    pages: 1168,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1986-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Hollywoodland',
    author: 'Zoe Brisby',
    coverUrl: '/books_pictures/780d3e906015.jpg',
    pages: 231,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2002-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Hôtel Magnifique',
    author: 'Emily J. Taylor',
    coverUrl: '/books_pictures/9924f0cfb8b2.jpg',
    pages: 400,
    genre: ['Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Idées reçues sur les phobies',
    author: 'Antoine Pelissolo',
    coverUrl: '/books_pictures/cdad3775bfc3.jpg',
    pages: 160,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2005-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Il faut qu'on parle de Kevin",
    author: 'Lionel Shriver',
    coverUrl: '/books_pictures/be3c519840a2.jpg',
    pages: 468,
    genre: ['Policier'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2003-01-01',
    description: '',
    countryOrigin: 'Allemagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ilos, tome 1',
    author: 'Marion Brunet',
    coverUrl: '/books_pictures/9dbc5820a0e0.jpg',
    pages: 162,
    genre: ['Littérature'],
    saga: 'Ilos',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '1988-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Into the deep',
    author: 'Sophie Griselle',
    coverUrl: '/books_pictures/385b7b927850.jpg',
    pages: 369,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1995-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Jake',
    author: 'Bryan Reardon',
    coverUrl: '/books_pictures/bdf756212463.jpg',
    pages: 264,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Je l'aimais",
    author: 'Anna Gavalda',
    coverUrl: '/books_pictures/5471889c9d49.jpg',
    pages: 156,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2002-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Je ne me lasse pas de vivre',
    author: 'Jaroslav Melnik',
    coverUrl: '/books_pictures/1738a8539a73.jpg',
    pages: 192,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'Ukraine',
    selectDisplayOrder: 0,
  },
  {
    title: 'Je suis Amélie Lenglet',
    author: 'Philippe Balland',
    coverUrl: '/books_pictures/00e872999d77.jpeg',
    pages: 259,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1992-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Je suis l'abysse",
    author: 'Donato Carrisi',
    coverUrl: '/books_pictures/c4c93159bc2d.jpg',
    pages: 384,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: "Je t'ai aimé dans une autre vie",
    author: 'David Arnold',
    coverUrl: '/books_pictures/ea98cdc19b65.jpg',
    pages: 342,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Killing me',
    author: 'Michelle Gagnon',
    coverUrl: '/books_pictures/3340aa3b7d93.jpg',
    pages: 360,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Knulp',
    author: 'Hermann Hesse',
    coverUrl: '/books_pictures/e07d0020ff6a.jpg',
    pages: 128,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1900-01-01',
    description: '',
    countryOrigin: 'Allemagne',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Amant de Lady Chatterley",
    author: 'D.H. Lawrence',
    coverUrl: '/books_pictures/890868f985cb.jpg',
    pages: 364,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1900-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: "L'arbre d'Halloween",
    author: 'Ray Bradbury',
    coverUrl: '/books_pictures/d2006d552c32.jpg',
    pages: 160,
    genre: ['Science Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1972-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'art du trompe-l'oeil",
    author: 'Océane Ghanem',
    coverUrl: '/books_pictures/e02412ef4706.jpg',
    pages: 399,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2010-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Écorchée",
    author: 'Donato Carrisi',
    coverUrl: '/books_pictures/9058f54b087e.jpg',
    pages: 249,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2009-01-01',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Education des papillons",
    author: 'Donato Carrisi',
    coverUrl: '/books_pictures/3714314d920b.jpeg',
    pages: 496,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-10-02',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: "L'égarée",
    author: 'Donato Carrisi',
    coverUrl: '/books_pictures/bcd4be5bba22.jpeg',
    pages: 336,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2018-10-02',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: "L'empire des ouragans",
    author: 'Alexiane de Lys',
    coverUrl: '/books_pictures/13714a6aa05d.png',
    pages: 363,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Encyclopédie féerique d'Emily Wilde",
    author: 'Heather Fawcett',
    coverUrl: '/books_pictures/0c4bd0ccecf9.jpg',
    pages: 325,
    genre: ['Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'énigme de Turnglass",
    author: 'Gareth Rubin',
    coverUrl: '/books_pictures/9c0c46bf64b8.jpg',
    pages: 448,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Épaisseur d'un cheveu",
    author: 'Claire Berest',
    coverUrl: '/books_pictures/f28d7db57409.jpg',
    pages: 250,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Été d'avant",
    author: 'Lisa Gardner',
    coverUrl: '/books_pictures/f8868336f2b8.jpg',
    pages: 415,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Etoile du soir",
    author: 'Siècle Vaëlban',
    coverUrl: '/books_pictures/00121afee318.jpg',
    pages: 344,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2006-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Hacienda",
    author: 'Isabel Cañas',
    coverUrl: '/books_pictures/ea5941d26d78.jpg',
    pages: 253,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "L'héritage de Judith Blackwood",
    author: 'Nathalie Somers',
    coverUrl: '/books_pictures/d0acc4a2df20.jpeg',
    pages: 332,
    genre: ['Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2009-01-01',
    description: '',
    countryOrigin: 'Belgique',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Homme des mille détours",
    author: 'Agnès Martin-Lugand',
    coverUrl: '/books_pictures/a212ac24a025.jpg',
    pages: 400,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "L'homme qui écoutait battre le coeur des chats",
    author: 'Mathias Malzieu',
    coverUrl:
      '/books_pictures/L-homme-qui-ecoutait-battre-le-coeur-des-chats.jpg',
    pages: 192,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Homme qui lisait des livres",
    author: 'Rachid Benzine',
    coverUrl: '/books_pictures/be7d86d96c91.jpg',
    pages: 288,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2004-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title:
      "L'homme qui prenait sa femme pour un chapeau et autres récits cliniques",
    author: 'Oliver Sacks',
    coverUrl: '/books_pictures/60aa0b45e5cd.jpg',
    pages: 308,
    genre: ['Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1980-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "L'homme qui rêvait d'aimer",
    author: 'Jean-Paul Delfino',
    coverUrl: '/books_pictures/c17f5cb5759c.jpg',
    pages: 272,
    genre: ['Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "L'horreur de Kill Creek",
    author: 'Scott Thomas',
    coverUrl: '/books_pictures/0fd1d998454a.jpg',
    pages: 414,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Île",
    author: 'Jérôme Loubry',
    coverUrl: '/books_pictures/cc1d7183fc74.jpeg',
    pages: 493,
    genre: ['Science Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1870-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Invitée surprise",
    author: 'Alison Espach',
    coverUrl: '/books_pictures/88b2db8af160.webp',
    pages: 384,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2011-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'océan au bout du chemin",
    author: 'Neil Gaiman',
    coverUrl: '/books_pictures/ca39d4b46d78.jpg',
    pages: 224,
    genre: ['Fantastique'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: "L'urgence et la patience",
    author: 'Jean-Philippe Toussaint',
    coverUrl: '/books_pictures/1ea74cce9f1c.jpg',
    pages: 106,
    genre: ['Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2012-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "La Ballade de l'impossible",
    author: 'Haruki Murakami',
    coverUrl: '/books_pictures/cd04ae17952b.jpg',
    pages: 389,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1987-01-01',
    description: '',
    countryOrigin: 'Japon',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Cagnotte',
    author: 'Janice Hallett',
    coverUrl: '/books_pictures/1fcdaa0044ac.jpg',
    pages: 165,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1990-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Dame de Reykjavik',
    author: 'Ragnar Jónasson',
    coverUrl: '/books_pictures/46e9732aa8a2.jpg',
    pages: 368,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'Islande',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Dame en blanc',
    author: 'William Wilkie Collins',
    coverUrl: '/books_pictures/d628fe2223c1.jpg',
    pages: 544,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1859-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'La demeure des Mah-Haut-Rels',
    author: 'Siècle Vaëlban',
    coverUrl: '/books_pictures/2388745e346d.jpg',
    pages: 412,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Déraison',
    author: 'Agnès Martin-Lugand',
    coverUrl: '/books_pictures/7d53650c2a9a.jpg',
    pages: 163,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Fille du bus 88',
    author: 'Freya Sampson',
    coverUrl: '/books_pictures/a2f1f7dae556.jpg',
    pages: 382,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La fille qui se noie',
    author: 'Caitlin R. Kiernan',
    coverUrl: '/books_pictures/e8ebfb1d328b.jpg',
    pages: 343,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2012-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La foire des ténèbres',
    author: 'Ray Bradbury',
    coverUrl: '/books_pictures/9782070309573_1.jpg',
    pages: 278,
    genre: ['Science Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1962-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Fugue',
    author: 'Aurélie Valognes',
    coverUrl: '/books_pictures/a5e3d9f13249.jpeg',
    pages: 379,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1900-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "La Geste d'Hamlet Evans",
    author: 'Rafael Marin',
    coverUrl: '/books_pictures/1e8719e25186.jpg',
    pages: 389,
    genre: ['Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1984-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Librairie disparue',
    author: 'Evie Woods',
    coverUrl: '/books_pictures/5a3dab5f431b.jpg',
    pages: 352,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Mâchoire de Caïn',
    author: 'Edward Powys Mathers',
    coverUrl: '/books_pictures/7ca69b7dd0d5.jpg',
    pages: 224,
    genre: ['Policier'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Maison aux lumières',
    author: 'Donato Carrisi',
    coverUrl: '/books_pictures/3dbaff58e5f5.jpeg',
    pages: 373,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2008-01-01',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Maison dans laquelle - Intégrale',
    author: 'Mariam Petrosyan',
    coverUrl: '',
    pages: 1074,
    genre: ['Littérature'],
    saga: 'La Maison dans laquelle',
    sagaOrder: 0,
    sagaFinished: true,
    releaseDate: '2016-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Maison dans les bois',
    author: 'Ana Reyes',
    coverUrl: '/books_pictures/771f475bcb0d.jpg',
    pages: 45,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2014-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Maison des voix',
    author: 'Donato Carrisi',
    coverUrl: '/books_pictures/7e2367c50148.jpeg',
    pages: 384,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2020-11-04',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Maison sans souvenirs',
    author: 'Donato Carrisi',
    coverUrl: '/books_pictures/c63dec7ad383.jpg',
    pages: 520,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-10-12',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: 'La mauvaise fille',
    author: 'Dandy Smith',
    coverUrl: '/books_pictures/2927956af6d1.jpg',
    pages: 288,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1991-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La mécanique du coeur',
    author: 'Mathias Malzieu',
    coverUrl: '/books_pictures/16b062584dde.jpg',
    pages: 176,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2010-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La nuit où les étoiles se sont éteintes',
    author: 'Nine Gorman',
    coverUrl: '/books_pictures/22d65a0ff7f4.jpg',
    pages: 496,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Là où gisent les endormies',
    author: 'Faridah Àbíké-Íyímídé',
    coverUrl: '/books_pictures/65c6a2484165.jpg',
    pages: 432,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Là où se cachent les âmes soeurs',
    author: 'Nathalie Hug',
    coverUrl: '/books_pictures/283e4d651d6c.jpeg',
    pages: 200,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2012-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Panne',
    author: 'Friedrich Dürrenmatt',
    coverUrl: '/books_pictures/d8ae9371c0a5.jpg',
    pages: 87,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1984-01-01',
    description: '',
    countryOrigin: 'Suisse',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Petite Boutique aux poisons',
    author: 'Sarah Penner',
    coverUrl: '/books_pictures/a8e4f3c71437.jpg',
    pages: 352,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La promesse',
    author: 'Friedrich Dürrenmatt',
    coverUrl: '/books_pictures/e7b4d4f6edf0.jpg',
    pages: 204,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1989-01-01',
    description: '',
    countryOrigin: 'Suisse',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Saison de la vertu',
    author: 'L. M. Nathan',
    coverUrl: '/books_pictures/3795b99f775d.jpg',
    pages: 285,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Septième Vague',
    author: 'Daniel Glattauer',
    coverUrl: '/books_pictures/5c201a598289.jpg',
    pages: 288,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2011-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La servante écarlate',
    author: 'Margaret Atwood',
    coverUrl: '/books_pictures/dba4f11ab8d0.jpg',
    pages: 350,
    genre: ['Dystopie'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1985-01-01',
    description: '',
    countryOrigin: 'Canada',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Truite et le perroquet: Confidences du peuple des rivières',
    author: 'Bill François',
    coverUrl: '/books_pictures/65f09052b4d0.jpg',
    pages: 208,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "La Voie de l'Oré, tome 1 : Le Maître de l'Anarchie",
    author: 'Marie Fabre (II)',
    coverUrl: '/books_pictures/8ab63f69c206.jpg',
    pages: 82,
    genre: ['Fantasy'],
    saga: "La Voie de l'Oré",
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '1972-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Labyrinthes',
    author: 'Franck Thilliez',
    coverUrl: '/books_pictures/37b62410deca.jpg',
    pages: 260,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1962-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Lapin maudit',
    author: 'Bora Chung',
    coverUrl: '/books_pictures/0c172b494aee.jpg',
    pages: 61,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2016-01-01',
    description: '',
    countryOrigin: 'Corée du Sud',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Bal des folles',
    author: 'Victoria Mas',
    coverUrl: '/books_pictures/1e85e6ab4c5b.jpeg',
    pages: 256,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Cercle occulte des gentlemen',
    author: 'Sarah Penner',
    coverUrl: '/books_pictures/b0fd62958d86.jpg',
    pages: 352,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le champ des soupirs',
    author: 'Elspeth Barker',
    coverUrl: '/books_pictures/74fa296379b0.jpeg',
    pages: 220,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1992-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le chant de la mutilation',
    author: 'Jason Hrivnak',
    coverUrl: '/books_pictures/dc6873be3004.jpg',
    pages: 250,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1898-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Chant du Troll',
    author: 'Pierre Bottero',
    coverUrl: '/books_pictures/72dfd3d4594f.jpg',
    pages: 192,
    genre: ['Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1893-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le chat qui reliait les âmes au Café Pont',
    author: 'Nagi Shimeno',
    coverUrl: '/books_pictures/6ddd59d7dc61.jpg',
    pages: 320,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Chuchoteur',
    author: 'Donato Carrisi',
    coverUrl: '/books_pictures/7cffb87d54cf.jpg',
    pages: 437,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2010-01-01',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Coeur synthétique',
    author: 'Chloé Delaume',
    coverUrl: '/movies_pictures/71qpPIGtmEL._SL1500_.jpg',
    pages: 208,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2020-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Le Courant d'air",
    author: 'Catherine Ryan Howard',
    coverUrl: '/books_pictures/cf97c048d454.jpg',
    pages: 238,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1913-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Démon de maître Prosper',
    author: 'K. J. Parker',
    coverUrl: '/books_pictures/96ec9e8374b6.jpg',
    pages: 104,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2020-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: "Le Fort Intérieur et la sorcière de l'île Moufle",
    author: 'Stella Benson',
    coverUrl: '/books_pictures/7360307867b0.jpg',
    pages: 256,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2020-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le jeu du Chuchoteur',
    author: 'Donato Carrisi',
    coverUrl: '/books_pictures/3380391367de.jpg',
    pages: 437,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2010-01-01',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Liseur',
    author: 'Bernhard Schlink',
    coverUrl: '/books_pictures/5de4ed36a1fa.jpg',
    pages: 206,
    genre: ['Policier'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1995-01-01',
    description: '',
    countryOrigin: 'Suisse',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Livre des portes',
    author: 'Gareth Brown',
    coverUrl: '/books_pictures/b4b10f98bfd7.jpg',
    pages: 358,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1939-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Loup des steppes',
    author: 'Hermann Hesse',
    coverUrl: '/books_pictures/11cc6cf900dd.jpeg',
    pages: 224,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1927-01-01',
    description: '',
    countryOrigin: 'Allemagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Magasin des suicides',
    author: 'Jean Teulé',
    coverUrl: '/books_pictures/1fc2a8cace22.jpg',
    pages: 169,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Le mec de la tombe d'à côté",
    author: 'Katarina Mazetti',
    coverUrl: '/books_pictures/fd8ba86595c8.jpg',
    pages: 256,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2011-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Métier de vivre',
    author: 'Cesare Pavese',
    coverUrl: '/books_pictures/097aefdedcfb.jpg',
    pages: 327,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1958-01-01',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le monde de Charlie',
    author: 'Stephen Chbosky',
    coverUrl: '/books_pictures/5ca9aa190f3e.jpg',
    pages: 231,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1999-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le monde de Sophie',
    author: 'Jostein Gaarder',
    coverUrl: '/books_pictures/2bc4bdd2d486.jpg',
    pages: 557,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1995-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le mythe de Sisyphe',
    author: 'Albert Camus',
    coverUrl: '/books_pictures/28c03276591e.jpg',
    pages: 169,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1941-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Nid du coucou',
    author: 'Camilla Läckberg',
    coverUrl: '/books_pictures/470763af111c.jpg',
    pages: 378,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1989-01-01',
    description: '',
    countryOrigin: 'Suède',
    selectDisplayOrder: 0,
  },
  {
    title: "Le Paris des merveilles, tome 1 : Les enchantements d'Ambremer",
    author: 'Pierre Pevel',
    coverUrl: '/books_pictures/bbce89d73ee6.jpg',
    pages: 384,
    genre: ['Fantasy'],
    saga: 'Le Paris des merveilles',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Passeur de Prospera',
    author: 'Justin Cronin',
    coverUrl: '/books_pictures/460199163c37.jpg',
    pages: 906,
    genre: ['Science Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2010-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Pavillon des Pivoines',
    author: 'Lisa See',
    coverUrl: '/books_pictures/019965a1-d14f-7595-9743-a4d175c64bb1.webp',
    pages: 454,
    genre: ['Fiction historique'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2008-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Le rêve d'un fou",
    author: 'Nadine Monfils',
    coverUrl: '/books_pictures/b532fe858a46.jpg',
    pages: 144,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le secret de Crickley Hall',
    author: 'James Herbert',
    coverUrl: '/books_pictures/9c42ed0f64b3.jpg',
    pages: 500,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2006-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le soleil se lèvera demain',
    author: 'Aurélie Massé',
    coverUrl: '/books_pictures/844edd9a6598.jpg',
    pages: 287,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le sort qui nous lie',
    author: 'Genevieve Gornichec',
    coverUrl: '/books_pictures/bc8f2a07ad95.jpg',
    pages: 368,
    genre: ['Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Le Temps d'après",
    author: 'Jean Hegland',
    coverUrl: '/books_pictures/650059cb9078.jpg',
    pages: 178,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2025-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Lemon',
    author: 'Kwon Yeo-sun',
    coverUrl: '/books_pictures/26c3e9765127.jpg',
    pages: 417,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'Corée du Sud',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les amoureux de la lune',
    author: 'Lizzie Felton',
    coverUrl: '/books_pictures/430596d6b566.jpg',
    pages: 189,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1883-01-01',
    description: '',
    countryOrigin: 'Canada',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Bouchères',
    author: 'Sophie Demange',
    coverUrl: '/books_pictures/2250c19650ef.jpg',
    pages: 75,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1991-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: "Les Brûleurs d'Or, tome 1 : Les apprentis de Mortcelieu",
    author: 'Alice Parriat',
    coverUrl: '/books_pictures/e88f84d01def.jpg',
    pages: 500,
    genre: ['Fantasy'],
    saga: "Les Brûleurs d'Or",
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2025-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Cahiers de Malte Laurids Brigge',
    author: 'Rainer Maria Rilke',
    coverUrl: '/books_pictures/637d9dc0e560.jpg',
    pages: 223,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1980-01-01',
    description: '',
    countryOrigin: 'Autriche',
    selectDisplayOrder: 0,
  },
  {
    title: "Les Carnets du sous-sol (Notes d'un souterrain)",
    author: 'Fiodor Dostoïevski',
    coverUrl: '',
    pages: 128,
    genre: ['Littérature'],
    saga: '/books_pictures/71Hl7TBBzwL._SL1491_.jpg',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1864-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Chats et 14 Histoires mystérieuses diaboliques cruelles',
    author: 'Bernard Minier',
    coverUrl: '/books_pictures/058f64039360.jpg',
    pages: 524,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les choses humaines',
    author: 'Karine Tuil',
    coverUrl: '/books_pictures/6de0070f421d.jpg',
    pages: 352,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Dangers de fumer au lit',
    author: 'Mariana Enriquez',
    coverUrl: '/books_pictures/694cc9a91baf.jpg',
    pages: 206,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2009-01-01',
    description: '',
    countryOrigin: 'Argentine',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Disparus du Pays imaginaire',
    author: 'Aiden Thomas',
    coverUrl: '/books_pictures/105b4ec5c196.jpg',
    pages: 356,
    genre: ['Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2020-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title:
      "Les féministes t'encouragent à quitter ton mari, tuer tes enfants, pratiquer la sorcellerie, détruire le capitalisme et devenir trans-pédé-gouine",
    author: 'Alex Tamécylia',
    coverUrl: '/books_pictures/0b60e6489729.jpg',
    pages: 64,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2025-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Indignes',
    author: 'Agustina Bazterrica',
    coverUrl: '/books_pictures/4494e51d8ce5.jpg',
    pages: 368,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1979-01-01',
    description: '',
    countryOrigin: 'Argentine',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Mots pour le dire',
    author: 'Marie Cardinal',
    coverUrl: '/books_pictures/1c66468a3615.jpg',
    pages: 304,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1975-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Mystères de la côte  : Le crime de la falaise',
    author: 'LJ Ross',
    coverUrl: '/books_pictures/88f9eabadfdc.jpg',
    pages: 314,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2016-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Les sept morts d'Evelyn Hardcastle",
    author: 'Stuart Turton',
    coverUrl: '/books_pictures/a5c57aa83d60.jpg',
    pages: 526,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Sirènes',
    author: 'Emilia Hart',
    coverUrl: '/books_pictures/71x1ow4iuHL._SL1311_.jpg',
    pages: 374,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2025-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Soeurs Carmines - Intégrale',
    author: 'Ariel Holzl',
    coverUrl: '/books_pictures/804563294910.png',
    pages: 272,
    genre: ['Fantasy'],
    saga: 'Les Soeurs Carmines',
    sagaOrder: 0,
    sagaFinished: true,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Les Voleurs d'innocence",
    author: 'Sarai Walker',
    coverUrl: '/books_pictures/2af96d02d223.jpg',
    pages: 254,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1994-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Whisperwicks, tome 1 : Le Labyrinthe sans fin',
    author: 'Jordan Lees',
    coverUrl: '/books_pictures/db98512afe18.jpg',
    pages: 448,
    genre: ['Fantasy'],
    saga: 'Les Whisperwicks',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Lettres à un jeune poète',
    author: 'Rainer Maria Rilke',
    coverUrl: '/books_pictures/578c2ce36139.jpeg',
    pages: 101,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1656-01-01',
    description: '',
    countryOrigin: 'Autriche',
    selectDisplayOrder: 0,
  },
  {
    title: 'Lolita',
    author: 'Vladimir Nabokov',
    coverUrl: '/books_pictures/222acb03acee.jpg',
    pages: 336,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1777-01-01',
    description: '',
    countryOrigin: 'Espagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'Love, Theoretically',
    author: 'Ali Hazelwood',
    coverUrl: '/books_pictures/95f6c17e3666.jpg',
    pages: 400,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ma chère Lise',
    author: 'Vincent Almendros',
    coverUrl: '/books_pictures/a8d03e31aa0b.jpg',
    pages: 156,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2011-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Mary',
    author: 'Anne Eekhout',
    coverUrl: '/books_pictures/8f2df9c8a9e5.jpg',
    pages: 400,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'Pays-Bas',
    selectDisplayOrder: 0,
  },
  {
    title: 'Même le froid tremble',
    author: 'Nicole Mersey Ortega',
    coverUrl: '/books_pictures/1d9dd73b7772.jpg',
    pages: 320,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Même pas morte',
    author: 'Geneviève Rioux',
    coverUrl: '/books_pictures/9ff39df5d3f8.webp',
    pages: 304,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Mémoires d'un expert psychiatre",
    author: 'Angélina Delcroix',
    coverUrl: '/books_pictures/e939340c3209.jpg',
    pages: 493,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2020-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Métro 2033',
    author: 'Dmitry Glukhovsky',
    coverUrl: '/books_pictures/da033d9b3d52.jpg',
    pages: 544,
    genre: ['Science Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'Russie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Mi-Mouche, tome 1 : Tu veux te battre ?',
    author: 'Véro Cazot',
    coverUrl: '/books_pictures/606b22853a0d.jpg',
    pages: 152,
    genre: ['Fantasy'],
    saga: 'Mi-Mouche',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Mile High',
    author: 'Liz Tomforde',
    coverUrl: '/books_pictures/be8cf55bc6ad.jpg',
    pages: 557,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Mon mari',
    author: 'Maud Ventura',
    coverUrl: '/books_pictures/457218338445.jpg',
    pages: 355,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Monstres ordinaires',
    author: 'Steven Price',
    coverUrl: '/books_pictures/e65a83f6d95b.jpg',
    pages: 316,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2002-01-01',
    description: '',
    countryOrigin: 'Canada',
    selectDisplayOrder: 0,
  },
  {
    title: 'Mort aux cons',
    author: 'Carl Aderhold',
    coverUrl: '/books_pictures/7f49adce5788.jpeg',
    pages: 410,
    genre: ['Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Mrs Dalloway',
    author: 'Virginia Woolf',
    coverUrl: '/books_pictures/1bc3ac63fcd2.jpg',
    pages: 224,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1925-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: "N'invite pas la forêt à entrer",
    author: 'C. G. Drews',
    coverUrl: '/books_pictures/fe28cdc16cb4.jpg',
    pages: 332,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ne raccroche pas',
    author: 'Julia Dessalles',
    coverUrl: '/books_pictures/614504b5eaf3.jpeg',
    pages: 406,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'No et moi',
    author: 'Delphine de Vigan',
    coverUrl: '/books_pictures/8af85ea71c02.jpeg',
    pages: 242,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Norferville',
    author: 'Franck Thilliez',
    coverUrl: '/books_pictures/f5afab9d9ae2.jpg',
    pages: 608,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Nos cœurs disparus',
    author: 'Celeste Ng',
    coverUrl: '/books_pictures/d328c5584062.jpg',
    pages: 364,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Nos constellations',
    author: 'Florence Quentin (II)',
    coverUrl: '/books_pictures/4a3797a2b549.png',
    pages: 36,
    genre: ['Théâtre'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2014-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Nos destins infinis',
    author: 'Laura Steven',
    coverUrl: '/books_pictures/641be8981c42.jpg',
    pages: 832,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Not in love',
    author: 'Ali Hazelwood',
    coverUrl: '/books_pictures/22ef44fa4991.jpg',
    pages: 450,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Notre part de nuit',
    author: 'Mariana Enriquez',
    coverUrl: '/books_pictures/9b07ebfe8769.jpg',
    pages: 640,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'Argentine',
    selectDisplayOrder: 0,
  },
  {
    title: 'Nous rêvions juste de liberté',
    author: 'Henri Loevenbruck',
    coverUrl: '/books_pictures/0199c4a6-0fd2-7100-a865-b07ecd2f7a58.webp',
    pages: 432,
    genre: ['Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Océan',
    author: 'Emma Emonds',
    coverUrl: '/books_pictures/46628eacbf22.jpg',
    pages: 217,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Où tu seras reine',
    author: 'Chrystel Duchamp',
    coverUrl: '/books_pictures/7989e3c98b9b.jpg',
    pages: 170,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ouvre-moi',
    author: 'Claire McGowan',
    coverUrl: '/books_pictures/4bdf62126373.jpg',
    pages: 24,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Parasites',
    author: 'Nicolas Framont',
    coverUrl: '/books_pictures/12df7df68949.jpeg',
    pages: 288,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Parmi les fleurs bruissent les secrets',
    author: 'Adrienne Young',
    coverUrl:
      '/books_pictures/parmi-les-fleurs-bruissent-les-secrets-5490118.jpg',
    pages: 352,
    genre: ['Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Poèmes saturniens - Fêtes galantes - Romances sans paroles',
    author: 'Paul Verlaine',
    coverUrl: '/books_pictures/4759698445d4.jpg',
    pages: 189,
    genre: ['Poésie'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2012-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Psychopathe',
    author: 'Keith Ablow',
    coverUrl: '/books_pictures/2ae9c3fef0cb.jpg',
    pages: 352,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2003-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Psychoses',
    author: 'Gilles Vincent',
    coverUrl: '/books_pictures/cc4493210514.jpg',
    pages: 352,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1920-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Puisque rien ne dure',
    author: 'Laurence Tardieu',
    coverUrl: '/books_pictures/f6da6a50deea.jpg',
    pages: 125,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2006-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Quand Haru était là',
    author: 'Dustin Thao',
    coverUrl: '/books_pictures/c021235860cd.jpg',
    pages: 304,
    genre: ['Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Quand nos os retourneront à la terre',
    author: 'V. E. Schwab',
    coverUrl: '/books_pictures/68952bda4add.jpg',
    pages: 504,
    genre: ['Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Quand souffle le vent du nord',
    author: 'Daniel Glattauer',
    coverUrl: '/books_pictures/40820e61a1a9.jpg',
    pages: 352,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2011-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Quatorze jours',
    author: 'Margaret Atwood',
    coverUrl: '/books_pictures/6feaec8b4be2.jpg',
    pages: 336,
    genre: ['Dystopie'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1988-01-01',
    description: '',
    countryOrigin: 'Canada',
    selectDisplayOrder: 0,
  },
  {
    title: 'Récitatif',
    author: 'Toni Morrison',
    coverUrl: '/books_pictures/59415f9e0597.jpg',
    pages: 80,
    genre: ['Fiction historique'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Regis',
    author: 'James Osmont',
    coverUrl: '/books_pictures/f35c2d170aec.jpg',
    pages: 274,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2016-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Résister à la culpabilisation',
    author: 'Mona Chollet',
    coverUrl: '/books_pictures/5072d2b72f23.jpg',
    pages: 267,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Rien n'est vrai",
    author: 'Lisa Jewell',
    coverUrl: '/books_pictures/bee3e523dcc9.jpg',
    pages: 84,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2011-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Sarek',
    author: 'Ulf Kvensler',
    coverUrl: '/books_pictures/01996b31-4b3b-7535-bd60-d6cf63ace50e.webp',
    pages: 428,
    genre: ['Science Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1994-01-01',
    description: '',
    countryOrigin: 'Suède',
    selectDisplayOrder: 0,
  },
  {
    title: "Se méfier de l'eau qui dort",
    author: 'Julia Richard',
    coverUrl: '/books_pictures/aef8dd7bab2e.jpg',
    pages: 176,
    genre: ['Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },

  {
    title: 'Serpent & Dove, tome 1',
    author: 'Shelby Mahurin',
    coverUrl: '/books_pictures/b357fb7318fa.jpg',
    pages: 524,
    genre: ['Fantasy'],
    saga: 'Serpent & Dove',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },

  {
    title: 'Songlight',
    author: 'Moira Buffini',
    coverUrl: '/books_pictures/0b18575beefd.jpg',
    pages: 390,
    genre: ['Science Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Sorcières : La puissance invaincue des femmes',
    author: 'Mona Chollet',
    coverUrl: '/books_pictures/d107a7cf1f94.jpg',
    pages: 240,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Sorrowsong University, tome 1 : Nightshade',
    author: 'Autumn Woods',
    coverUrl: '/books_pictures/a0f67070a875.jpg',
    pages: 416,
    genre: ['Fantasy'],
    saga: 'Sorrowsong University',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2025-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Stella Maris',
    author: 'Cormac McCarthy',
    coverUrl: '/books_pictures/6e149be0a160.jpg',
    pages: 624,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Strange Pictures',
    author: 'Uketsu',
    coverUrl: '/books_pictures/c8b6ae2466c6.jpg',
    pages: 239,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2025-01-01',
    description: '',
    countryOrigin: 'Japon',
    selectDisplayOrder: 0,
  },
  {
    title: 'Sur les cimes du désespoir',
    author: 'Emil Cioran',
    coverUrl: '/books_pictures/f3594369b3b3.jpeg',
    pages: 150,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1990-01-01',
    description: '',
    countryOrigin: 'Roumanie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Suzume (roman)',
    author: 'Makoto Shinkai',
    coverUrl: '/books_pictures/d771b73c1ab4.jpeg',
    pages: 165,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2008-01-01',
    description: '',
    countryOrigin: 'Japon',
    selectDisplayOrder: 0,
  },
  {
    title: "Syllogismes de l'amertume",
    author: 'Emil Cioran',
    coverUrl: '/books_pictures/3028223bcc60.jpg',
    pages: 169,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1952-01-01',
    description: '',
    countryOrigin: 'Roumanie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Termush, côte Atlantique',
    author: 'Sven Holm',
    coverUrl: '/books_pictures/560b28ea6fc4.jpg',
    pages: 110,
    genre: ['Science Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1969-01-01',
    description: '',
    countryOrigin: 'Danemark',
    selectDisplayOrder: 0,
  },
  {
    title: "Tes pas dans l'escalier",
    author: 'Antonio Muñoz Molina',
    coverUrl: '/books_pictures/5c61356c02ff.jpg',
    pages: 448,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1997-01-01',
    description: '',
    countryOrigin: 'Espagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Fallen Empire, tome 1 : Phoenix Unbound',
    author: 'Grace Draven',
    coverUrl: '/books_pictures/401410364f83.jpg',
    pages: 704,
    genre: ['Fantasy'],
    saga: 'The Fallen Empire',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Great Misfortune of Stella Sedgwick',
    author: 'Sophie Isabelle',
    coverUrl: '/books_pictures/0bbb23e63fb9.jpg',
    pages: 48,
    genre: ['Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Love Hypothesis',
    author: 'Ali Hazelwood',
    coverUrl: '/books_pictures/0442030a84cb.jpg',
    pages: 398,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Way I Am Now',
    author: 'Amber Smith',
    coverUrl: '/books_pictures/a150f5aadbf5.jpg',
    pages: 320,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Way I Used to Be',
    author: 'Amber Smith',
    coverUrl: '/books_pictures/b93d82b49707.jpg',
    pages: 384,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2016-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Westing Game',
    author: 'Ellen Raskin',
    coverUrl: '/books_pictures/096f17a25519.jpg',
    pages: 192,
    genre: ['Jeunesse'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1978-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Tokyo Rain',
    author: 'Yasmin Shakarami',
    coverUrl: '/books_pictures/886911db720c.jpeg',
    pages: 376,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2002-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Tomber sept fois, se relever huit',
    author: 'Philippe Labro',
    coverUrl: '/books_pictures/aa53e978bb36.jpg',
    pages: 252,
    genre: ['Biographie'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2003-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ton jour viendra',
    author: 'Kimberly McCreight',
    coverUrl: '/books_pictures/dbce093e7f66.jpg',
    pages: 400,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Transformations',
    author: 'Anne Sexton',
    coverUrl: '/books_pictures/81cd55ff1a86.jpg',
    pages: 112,
    genre: ['Poésie'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1971-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Troublemaker, tome 1',
    author: 'Laura Swan',
    coverUrl: '/books_pictures/046b0e51ee09.jpeg',
    pages: 272,
    genre: ['Romance'],
    saga: 'Troublemaker',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Troublemaker, tome 2',
    author: 'Laura Swan',
    coverUrl: '/books_pictures/8055c6490b6f.jpg',
    pages: 272,
    genre: ['Romance'],
    saga: 'Troublemaker',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Tu tueras l'ange",
    author: 'Sandrone Dazieri',
    coverUrl: '/books_pictures/1bbeb1d74f90.jpg',
    pages: 520,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Tu tueras le Père',
    author: 'Sandrone Dazieri',
    coverUrl: '/books_pictures/a3939ec99cb5.jpg',
    pages: 520,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Tu tueras le Roi',
    author: 'Sandrone Dazieri',
    coverUrl: '/books_pictures/685c714f9094.jpg',
    pages: 520,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Tu verras, les âmes se retrouvent toujours quelque part',
    author: 'Sabrina Philippe',
    coverUrl: '/books_pictures/64e330cffbf9.jpg',
    pages: 286,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ubik',
    author: 'Philip K. Dick',
    coverUrl: '/books_pictures/6ea1031b74b8.jpg',
    pages: 224,
    genre: ['Science Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1969-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un castor de dix-huit mètres',
    author: 'Antti Tuomainen',
    coverUrl: '/books_pictures/fc87c81d59ae.jpg',
    pages: 245,
    genre: ['Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un don',
    author: 'Toni Morrison',
    coverUrl: '/books_pictures/8fc7784596cb.jpg',
    pages: 192,
    genre: ['Fiction historique'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1998-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un été',
    author: 'Vincent Almendros',
    coverUrl: '/books_pictures/e494d12c6d99.jpg',
    pages: 94,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un homme à distance',
    author: 'Katherine Pancol',
    coverUrl: '/books_pictures/d519a008a75b.jpg',
    pages: 170,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2002-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Une chambre à soi (Un lieu à soi)',
    author: 'Virginia Woolf',
    coverUrl: '/books_pictures/a06dd6d1b9b3.jpg',
    pages: 143,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1929-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Une invitée particulière',
    author: 'Nelle Lamarr',
    coverUrl: '/books_pictures/b0bef1e2ae8b.webp',
    pages: 256,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Unfair, tome 1 : Moon',
    author: 'Océane Ghanem',
    coverUrl: '/books_pictures/33c79f0294db.jpg',
    pages: 317,
    genre: ['Théâtre'],
    saga: 'Unfair',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2003-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Veronika décide de mourir',
    author: 'Paulo Coelho',
    coverUrl: '/books_pictures/f00464882bd6.jpg',
    pages: 287,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: 'Brésil',
    selectDisplayOrder: 0,
  },
  {
    title: "Vingt-quatre heures de la vie d'une femme",
    author: 'Stefan Zweig',
    coverUrl: '/books_pictures/410eb13e1203.jpg',
    pages: 80,
    genre: ['Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'Autriche',
    selectDisplayOrder: 0,
  },
  {
    title: 'Virtuoses : Retour de flamme',
    author: 'Tess Corsac',
    coverUrl: '/books_pictures/183763e6e092.jpg',
    pages: 352,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Vivre avec les hommes : Réflexions sur le procès Pelicot',
    author: 'Manon Garcia',
    coverUrl: '/books_pictures/cb32f387a2d3.jpg',
    pages: 232,
    genre: ['Nonfiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2025-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Vous êtes cordialement invités, tome 1',
    author: 'Alex Sol',
    coverUrl: '/books_pictures/6775a5261a9c.jpg',
    pages: 320,
    genre: ['Thriller'],
    saga: 'Vous êtes cordialement invités',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Vue sur la mère',
    author: 'Julien Almendros',
    coverUrl: '/books_pictures/30fd828b9bf5.jpg',
    pages: 174,
    genre: ['Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2008-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Wayward Pines, tome 1 : Révélation',
    author: 'Blake Crouch',
    coverUrl: '/books_pictures/822b89c183ff.jpg',
    pages: 343,
    genre: ['Science Fiction'],
    saga: 'Wayward Pines',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
];
