import { BaseBook } from '../../../models/book-model';

export const baseBooksRomance: BaseBook[] = [
  {
    title: 'Roméo et Juliette',
    author: 'William Shakespeare',
    coverUrl: '/books_pictures/71crcf7etvL._SY522_.jpg',
    pages: 256,
    genre: ['Romance', 'Classiques', 'Théâtre'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1597-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'Raison et sentiments',
    author: 'Jane Austen',
    coverUrl: '/books_pictures/a33514c317d4.jpg',
    pages: 416,
    genre: ['Classiques', 'Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1811-10-30',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'Orgueil et Préjugés',
    author: 'Jane Austen',
    coverUrl: '/books_pictures/orgueil_et_prejuges.jpg',
    pages: 279,
    genre: ['Classiques', 'Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1813-01-28',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'Emma',
    author: 'Jane Austen',
    coverUrl: '/books_pictures/81vfJi+HAVL._AC_UF1000,1000_QL80_.jpg',
    pages: 474,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1815-12-23',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    coverUrl: '/books_pictures/jane_eyre.jpg',
    pages: 532,
    genre: ['Romance', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1847-10-16',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'Les filles du Docteur March',
    author: 'Louisa May Alcott',
    coverUrl: '/books_pictures/9782381228365.jpg',
    pages: 400,
    genre: ['Romance', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1868-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Cyrano de Bergerac',
    author: 'Edmond Rostand',
    coverUrl: '/books_pictures/Cyrano-de-Bergerac.jpg',
    pages: 200,
    genre: ['Romance', 'Classiques', 'Théâtre'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1897-12-28',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Gatsby le magnifique',
    author: 'F. Scott Fitzgerald',
    coverUrl: '/books_pictures/9782246495512-T.webp',
    pages: 180,
    genre: ['Romance', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1925-04-10',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Autant en emporte le vent',
    author: 'Margaret Mitchell',
    coverUrl: '/books_pictures/Autant-en-emporte-le-vent.jpg',
    pages: 1037,
    genre: ['Romance', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1936-06-30',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Now, Voyager',
    author: 'Olive Higgins Prouty',
    coverUrl: '/books_pictures/6164310f56d2.jpg',
    pages: 339,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1941-01-01',
    description:
      'Charlotte Vale, spinster brisée par sa mère, renaît en croisière et choisit un amour impossible.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'écume des jours",
    author: 'Boris Vian',
    coverUrl: '/books_pictures/81WmGQbXiSL.jpg',
    pages: 250,
    genre: ['Romance', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1947-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: "Murphy's Romance",
    author: 'Max Schott',
    coverUrl: '/books_pictures/6e10ac6ff34c.jpg',
    pages: 129,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1980-01-01',
    description:
      'Une cavalière divorcée s’installe dans l’Ouest et croise Murphy, vétérinaire veuf plus âgé.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'amour aux temps du choléra",
    author: 'Gabriel García Márquez',
    coverUrl: '/books_pictures/81d2fnWZbWL._AC_UF1000,1000_QL80_.jpg',
    pages: 479,
    genre: ['Romance', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1985-03-27',
    description: '',
    countryOrigin: 'Colombie',
    selectDisplayOrder: 30,
  },
  {
    title: 'Les pages de notre amour',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/Les-pages-de-notre-amour.jpg',
    pages: 224,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1996-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le porte bonheur',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/41TwzJl0j3L._SX195_.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2003-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'À tout jamais',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/71uDPcPonsL._UF1000,1000_QL80_.jpg',
    pages: 240,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2004-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Dear John',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/571cb4ccd408.jpg',
    pages: 288,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2006-01-01',
    description:
      'Un soldat et une étudiante s’aiment à distance jusqu’à devoir choisir.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un choix',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/Un-choix.jpg',
    pages: 280,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La dernière chanson',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/550x838.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2009-09-08',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Une seconde chance',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/61dlBm9b5XL._AC_UF1000,1000_QL80_.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Fais un voeu',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/61WDtAa9gxL._AC_UF1000,1000_QL80_.jpg',
    pages: 300,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2020-09-29',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Au rythme de ton souffle',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/au-rythme-de-ton-souffle.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-09-28',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un havre de paix',
    author: 'Nicholas Sparks',
    coverUrl: '/books_pictures/un-havre-de-paix-5444321.jpg',
    pages: 300,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-09-20',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Journal de Bridget Jones',
    author: 'Helen Fielding',
    coverUrl: '/books_pictures/f00e0bc8adf0.jpg',
    pages: 416,
    genre: ['Romance'],
    saga: 'Bridget Jones',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '1996-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 20,
  },
  {
    title: "Bridget Jones : L'Âge de raison",
    author: 'Helen Fielding',
    coverUrl: '/books_pictures/6e59eb50dce6.jpg',
    pages: 432,
    genre: ['Romance'],
    saga: 'Bridget Jones',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '1999-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 20,
  },
  {
    title: 'Bridget Jones folle de lui',
    author: 'Helen Fielding',
    coverUrl: '/books_pictures/85bced2f2221.jpg',
    pages: 512,
    genre: ['Romance'],
    saga: 'Bridget Jones',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 20,
  },
  {
    title: 'Bridget Jones : Baby',
    author: 'Helen Fielding',
    coverUrl: '/books_pictures/a8070e810588.jpg',
    pages: 352,
    genre: ['Romance'],
    saga: 'Bridget Jones',
    sagaOrder: 4,
    sagaFinished: false,
    releaseDate: '2016-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 20,
  },
  {
    title: 'Geisha',
    author: 'Arthur Golden',
    coverUrl: '/books_pictures/4a99ea23b752.jpg',
    pages: 512,
    genre: ['Romance', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1997-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Dans ses yeux',
    author: 'Alexandra Deguilhem',
    coverUrl: '/books_pictures/e89e7a1eebfa.jpg',
    pages: 358,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Love on the Brain',
    author: 'Ali Hazelwood',
    coverUrl: '/books_pictures/9e8ba5aef34b.jpg',
    pages: 442,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Love Hypothesis',
    author: 'Ali Hazelwood',
    coverUrl: '/books_pictures/0442030a84cb.jpg',
    pages: 398,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Check & Mate',
    author: 'Ali Hazelwood',
    coverUrl: '/books_pictures/7fef9d40e86e.jpg',
    pages: 368,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Love, Theoretically',
    author: 'Ali Hazelwood',
    coverUrl: '/books_pictures/95f6c17e3666.jpg',
    pages: 400,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Bride',
    author: 'Ali Hazelwood',
    coverUrl: '/books_pictures/f4dd67437420.jpg',
    pages: 401,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Not in love',
    author: 'Ali Hazelwood',
    coverUrl: '/books_pictures/22ef44fa4991.jpg',
    pages: 450,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'First-Time Caller (Heartstrings, #1)',
    author: 'B. K. Borison',
    coverUrl: '/books_pictures/92fbb1935854.jpg',
    pages: 448,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: "Les Coquillages ne s'ouvrent qu'en été",
    author: 'Camille Pagan',
    coverUrl: '/books_pictures/1acadcef17db.webp',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Cursed Crowns (Twin Crowns #2)',
    author: 'Catherine Doyle et Katherine Webber',
    coverUrl: '/books_pictures/4e4e6e46e7ab.jpeg',
    pages: 207,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Twin Crowns',
    author: 'Catherine Doyle et Katherine Webber',
    coverUrl: '/books_pictures/44d21357686e.jpg',
    pages: 480,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Bretzel Break',
    author: 'Cécile Chomin',
    coverUrl: '/books_pictures/9da0ae7b17b3.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un coeur pour Noël',
    author: 'Chloé Delaume',
    coverUrl: '/books_pictures/50522885df93.jpg',
    pages: 372,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Effet Boule de Neige",
    author: 'Clara Héraut',
    coverUrl: '/books_pictures/cf8b7f117f66.jpg',
    pages: 50,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le tourbillon des possibles',
    author: 'Clara Héraut',
    coverUrl: '/books_pictures/653ab60d3e17.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Nos plus belles années',
    author: 'Clara Héraut',
    coverUrl: '/books_pictures/8f8eb2fd1c0b.jpg',
    pages: 275,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Azalées fleurissent en hiver',
    author: 'Dahlia Blake',
    coverUrl: '/books_pictures/65d18b8d2d06.webp',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'The American Roommate Experiment (Spanish Love Deception, #2)',
    author: 'Elena Armas',
    coverUrl: '/books_pictures/508f4793486f.jpg',
    pages: 201,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Cour de la Haute Montagne (The Five Crowns, #1)',
    author: 'Katharine Corr',
    coverUrl: '/books_pictures/45a3d725ba8e.jpg',
    pages: 12,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Rebel Witch (Heartless Hunter, #2)',
    author: 'Kristen Ciccarelli',
    coverUrl: '/books_pictures/87cf59902b5f.jpg',
    pages: 464,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Recettes cubaines pour guérir un coeur brisé',
    author: 'Lynda Cohen Loigman',
    coverUrl: '/books_pictures/d9b10fb65136.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ainsi gèlent les bulles de savon',
    author: 'Marie Vareille',
    coverUrl: '/books_pictures/dd425a44ed99.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Tenir debout',
    author: 'Mélissa Da Costa',
    coverUrl: '/books_pictures/ef3a6777ab4c.jpg',
    pages: 201,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Tout le bleu du ciel',
    author: 'Melissa Da Costa',
    coverUrl: '/books_pictures/56_9782253934103_1_75.jpg',
    pages: 840,
    genre: ['Romance', 'Aventure'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Un automne pour te pardonner (Seasons, #1)',
    author: 'Morgane Moncomble',
    coverUrl: '/books_pictures/fdcbd37a001d.jpg',
    pages: 256,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un Été pour te retrouver (Seasons #4)',
    author: 'Morgane Moncomble',
    coverUrl: '/books_pictures/fd3d299aac71.jpg',
    pages: 407,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un hiver pour te résister (Seasons #2)',
    author: 'Morgane Moncomble',
    coverUrl: '/books_pictures/4b0468f7dee2.jpg',
    pages: 459,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un printemps pour te succomber (Seasons #3)',
    author: 'Morgane Moncomble',
    coverUrl: '/books_pictures/3061100b0694.jpg',
    pages: 400,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Break Up Artists',
    author: 'Philip Siegel',
    coverUrl: '/books_pictures/d07013d927aa.jpg',
    pages: 319,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Fourth Wing (The Empyrean, #1)',
    author: 'Rebecca Yarros',
    coverUrl: '/books_pictures/e50b742e97b4.jpg',
    pages: 530,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Société très secrète des Sorcières extraordinaires',
    author: 'Sangu Mandanna',
    coverUrl: '/books_pictures/3434590a2822.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: "A Witch's Guide to fake dating a demon",
    author: 'Sarah Hawley',
    coverUrl: '/books_pictures/c3043af6e0a4.jpeg',
    pages: 400,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Été où tout a fondu",
    author: 'Tiffany McDaniel',
    coverUrl: '/books_pictures/d984394ebdeb.jpg',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Tu comprendras quand tu seras plus grande',
    author: 'Virginie Grimaldi',
    coverUrl: '/books_pictures/c9acb10f665b.jpg',
    pages: 480,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Quatre filles et un jean',
    author: 'Ann Brashares',
    coverUrl: '/books_pictures/ea6ffabc4d52.jpg',
    pages: 384,
    genre: ['Romance', 'Jeunesse'],
    saga: 'Quatre filles et un jean',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2001-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: "Le diable s'habille en Prada",
    author: 'Lauren Weisberger',
    coverUrl: '/books_pictures/7deb767d9518.jpg',
    pages: 448,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2003-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Vengeance en Prada : Le Retour du diable',
    author: 'Lauren Weisberger',
    coverUrl: '/books_pictures/9ba073d78563.jpg',
    pages: 512,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-06-04',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: "L'enfer est pavé de bonnes intentions",
    author: 'Lauren Weisberger',
    coverUrl: '/books_pictures/340dc7e9a0f1.jpg',
    pages: 384,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'P.S. I Love You',
    author: 'Cecelia Ahern',
    coverUrl: '/books_pictures/06a7b7ddca6e.jpg',
    pages: 416,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2004-01-01',
    description: '',
    countryOrigin: 'Irlande',
    selectDisplayOrder: 20,
  },
  {
    title: 'Mange, prie, aime',
    author: 'Elizabeth Gilbert',
    coverUrl: '/books_pictures/64a1bf94536f.jpg',
    pages: 416,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2006-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Love, Actually',
    author: "Philip O'Connor",
    coverUrl: '/books_pictures/16354f0488d3.webp',
    pages: 320,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 20,
  },
  {
    title: 'Un jour',
    author: 'David Nicholls',
    coverUrl: '/books_pictures/bd549a2212a9.jpg',
    pages: 544,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2009-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 20,
  },
  {
    title: "La Probabilité statistique de l'amour au premier regard",
    author: 'Jennifer E. Smith',
    coverUrl: '/books_pictures/1b604f084a5c.jpg',
    pages: 336,
    genre: ['Romance', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2012-01-01',
    description:
      'Roman (inspiré du film) : trajectoires improbables et première rencontre sous le signe des statistiques.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Avant toi',
    author: 'Jojo Moyes',
    coverUrl: '/books_pictures/108336df8c94.jpg',
    pages: 480,
    genre: ['Romance', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2012-01-01',
    description:
      'Lou soigne Will, tétraplégique, et leur rencontre change tout.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Nos étoiles contraires',
    author: 'John Green',
    coverUrl: '/books_pictures/f2db9b91755d.jpg',
    pages: 336,
    genre: ['Romance', 'Jeunesse'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2012-01-10',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Cinquante nuances de Grey',
    author: 'E. L. James',
    coverUrl: '/books_pictures/1271b5c6c624.jpg',
    pages: 528,
    genre: ['Romance', 'Dark Romance'],
    saga: 'Cinquante nuances',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '2012-05-02',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Cinquante nuances plus sombres',
    author: 'E. L. James',
    coverUrl: '/books_pictures/6c72b059e098.jpg',
    pages: 544,
    genre: ['Romance', 'Dark Romance'],
    saga: 'Cinquante nuances',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '2012-09-12',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Cinquante nuances plus claires',
    author: 'E. L. James',
    coverUrl: '/books_pictures/61bcadedb6e3.jpg',
    pages: 544,
    genre: ['Romance', 'Dark Romance'],
    saga: 'Cinquante nuances',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '2012-11-14',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Hello Goodbye and Everything in Between',
    author: 'Jamie McGuire',
    coverUrl: '/books_pictures/8c8ed7b18dcd.jpg',
    pages: 320,
    genre: ['Romance', 'Jeunesse'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: 'Avant la fac, un couple décide de se séparer… ou presque.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Troublemaker, tome 1',
    author: 'Laura Swan',
    coverUrl: '/books_pictures/046b0e51ee09.jpeg',
    pages: 272,
    genre: ['Romance'],
    saga: 'Troublemaker',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Troublemaker, tome 2',
    author: 'Laura Swan',
    coverUrl: '/books_pictures/8055c6490b6f.jpg',
    pages: 272,
    genre: ['Romance'],
    saga: 'Troublemaker',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'À Travers Ma Fenêtre',
    author: 'Ariana Godoy',
    coverUrl: '/books_pictures/0a69cb592029.jpg',
    pages: 320,
    genre: ['Romance', 'Jeunesse'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2016-01-01',
    description:
      'Roman (inspiré du film) : regards croisés entre deux voisins sur trois étages.',
    countryOrigin: 'Venezuela',
    selectDisplayOrder: 0,
  },
  {
    title: 'It Ends with Us',
    author: 'Colleen Hoover',
    coverUrl: '/books_pictures/72a8372bbd8e.jpg',
    pages: 384,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2016-01-01',
    description:
      'Lily confronte l’amour, la violence conjugale et les cycles familiaux.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Nos cœurs meurtris',
    author: 'Tess Wakefield',
    coverUrl: '/books_pictures/43e1724f9873.jpg',
    pages: 304,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Boys of Tommen, tome 1 : Binding 13',
    author: 'Chloe Walsh',
    coverUrl: '/books_pictures/1c1873536fcd.jpg',
    pages: 636,
    genre: ['Romance'],
    saga: 'Boys of Tommen',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2020-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Boys of Tommen, tome 2 : Keeping 13',
    author: 'Chloe Walsh',
    coverUrl: '/books_pictures/3fb654ec21ec.jpg',
    pages: 636,
    genre: ['Romance'],
    saga: 'Boys of Tommen',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2020-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "La carte qui mène jusqu'à toi",
    author: 'Joseph Monninger',
    coverUrl: '/books_pictures/817fEwfe34L._AC_UF1000,1000_QL80_.jpg',
    pages: 368,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2020-08-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Comme si la fin n'existait pas",
    author: 'Brianna Bourne',
    coverUrl: '/books_pictures/a2aedf7e8ddb.jpg',
    pages: 368,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'People We Meet on Vacation',
    author: 'Emily Henry',
    coverUrl: '/books_pictures/c0390051f459.jpg',
    pages: 384,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description:
      'Deux amis d’enfance tentent de réparer leur amitié pendant des vacances.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Castel Boy',
    author: 'Eny Heli',
    coverUrl: '/books_pictures/71AGuHSj0mL.jpg',
    pages: 500,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Adam',
    author: 'Eny Heli',
    coverUrl: '/books_pictures/61F72yE7irL.jpg',
    pages: 450,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2025-11-26',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Lucas',
    author: 'Eny Heli',
    coverUrl: '/books_pictures/c5754d642e7a.jpg',
    pages: 554,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2026-07-10',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Better Than the Movies',
    author: 'Lynn Painter',
    coverUrl: '/books_pictures/240325fb6bc8.jpg',
    pages: 368,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les liaisons dangereuses',
    author: 'Eny Heli',
    coverUrl: '/books_pictures/les-liaisons-dangereuses-5536921.jpg',
    pages: 400,
    genre: ['Dark Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Memento mori',
    author: 'Eny Heli',
    coverUrl: '/books_pictures/71E6TZcFrdL.jpg',
    pages: 300,
    genre: ['Dark Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Mile High',
    author: 'Liz Tomforde',
    coverUrl: '/books_pictures/be8cf55bc6ad.jpg',
    pages: 557,
    genre: ['Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Il était une fois: Tome 1 : Mon premier baiser',
    author: 'Chlore Smythe, Juliette Pierce',
    coverUrl: '/books_pictures/81CXdOT0uPL._UF350,350_QL50_.jpg',
    pages: 468,
    genre: ['Romance'],
    saga: 'Il était une fois',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Il était une fois: Tome 2 : Mon dernier amour',
    author: 'Chlore Smythe, Juliette Pierce',
    coverUrl: '/books_pictures/71tcmDP0HPL.jpg',
    pages: 533,
    genre: ['Dark Romance'],
    saga: 'Il était une fois',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2023-11-23',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Vengeance de la Veuve Noire',
    author: 'Morgane Moncomble',
    coverUrl: '/books_pictures/4a4ed79bb571.jpg',
    pages: 592,
    genre: ['Romance', 'Fiction historique'],
    saga: 'Inheritance',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2026-09-02',
    description:
      'Londres 1812 : Wisteria, apothicaire le jour et Veuve Noire la nuit, s’allie à l’enquêteur William pour traquer Jack l’Égorgeur, entre poison et attirance interdite.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  }
];
