import { BaseBook } from '../../../models/book-model';

export const baseBooksClassiques: BaseBook[] = [
  {
    title: "L'epopée de Gilgamesh",
    author: 'Anonyme',
    coverUrl: '/books_pictures/47_9782070627615_1_75.jpg',
    pages: 200,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '0001-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Beowulf',
    author: 'Anonyme',
    coverUrl: '/books_pictures/64e76858b3e0.jpeg',
    pages: 160,
    genre: ['Classiques', 'Poésie'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1000-01-01',
    description: 'Le héros géant affronte Grendel, sa mère et un dragon.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Chanson des Nibelungen',
    author: 'Anonyme',
    coverUrl: '/books_pictures/8f90863a2ff5.webp',
    pages: 526,
    genre: ['Classiques', 'Poésie'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1200-01-01',
    description:
      'Épopée germanique médiévale : Siegfried, Kriemhild, Brunhild et la chute sanglante des Burgondes.',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Métamorphoses',
    author: 'Ovide',
    coverUrl: '/books_pictures/878b41197211.jpg',
    pages: 512,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '0008-01-01',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 30,
  },
  {
    title: 'Satyricon',
    author: 'Pétrone',
    coverUrl: '/books_pictures/f9da20e767df.jpg',
    pages: 192,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '0060-01-01',
    description:
      'Roman latin fragmentaire : Encolpe, Giton et Ascylte errent dans une Rome de festins, de sexe et de satire.',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Œdipe roi',
    author: 'Sophocle',
    coverUrl: '/books_pictures/97e263f391eb.jpg',
    pages: 96,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '0425-01-01',
    description: '',
    countryOrigin: 'Grèce',
    selectDisplayOrder: 30,
  },
  {
    title: "L'enfer",
    author: 'Dante Alighieri',
    coverUrl: '/books_pictures/9782330064617_1_75.jpg',
    pages: 400,
    genre: ['Classiques'],
    saga: 'La Divine Comédie',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '1320-01-01',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 30,
  },
  {
    title: 'La Divine Comédie',
    author: 'Dante Alighieri',
    coverUrl: '/books_pictures/La-Divine-Comedie.jpg',
    pages: 512,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1321-01-01',
    description: '',
    countryOrigin: 'Italie',
    selectDisplayOrder: 30,
  },
  {
    title: 'Le Décaméron',
    author: 'Boccace',
    coverUrl: '/books_pictures/88463a5b4202.jpg',
    pages: 724,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1353-01-01',
    description:
      'Dix jeunes gens fuient la peste à Florence et se racontent cent nouvelles, du sacré au grivois.',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Contes de Canterbury',
    author: 'Geoffrey Chaucer',
    coverUrl: '/books_pictures/a8a7a161c7b5.jpg',
    pages: 567,
    genre: ['Classiques', 'Poésie'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1400-01-01',
    description:
      'Pèlerins en route vers Canterbury se racontent des histoires : fabliaux, sermons, romances et satires.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Pantagruel',
    author: 'François Rabelais',
    coverUrl: '/books_pictures/9782757891889_1_75.jpg',
    pages: 500,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1532-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Gargantua',
    author: 'François Rabelais',
    coverUrl: '/books_pictures/9782081357754_1_75.jpg',
    pages: 500,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1534-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Hamlet',
    author: 'William Shakespeare',
    coverUrl: '/books_pictures/81ZTRJyMbTS._UF1000,1000_QL80_.jpg',
    pages: 250,
    genre: ['Classiques', 'Théâtre'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1603-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'Macbeth',
    author: 'William Shakespeare',
    coverUrl: '/books_pictures/macbeth-14.jpg',
    pages: 200,
    genre: ['Classiques', 'Théâtre'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1623-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'Le Cid',
    author: 'Corneille',
    coverUrl: '/books_pictures/J04974.jpg',
    pages: 160,
    genre: ['Théâtre', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1637-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Lettres à un jeune poète',
    author: 'Rainer Maria Rilke',
    coverUrl: '/books_pictures/578c2ce36139.jpeg',
    pages: 101,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1656-01-01',
    description: '',
    countryOrigin: 'Autriche',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Princesse de Montpensier',
    author: 'Madame de Lafayette',
    coverUrl: '/books_pictures/3b3e365632d2.jpg',
    pages: 96,
    genre: ['Classiques', 'Fiction historique'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1662-01-01',
    description:
      'Intrigues de cour, mariage arrangé et passions dangereuses au XVIe siècle.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Tartuffe',
    author: 'Molière',
    coverUrl: '/books_pictures/61TtXlF-diL._AC_UF1000,1000_QL80_.jpg',
    pages: 160,
    genre: ['Théâtre', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1664-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Le bourgeois Gentilshommes',
    author: 'Molière',
    coverUrl: '/books_pictures/9782378283841.jpg',
    pages: 160,
    genre: ['Théâtre', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1670-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Dom Juan',
    author: 'Molière',
    coverUrl: '/books_pictures/f4e44cd03f07.jpg',
    pages: 176,
    genre: ['Classiques', 'Théâtre'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1665-02-15',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Fables',
    author: 'Jean de La Fontaine',
    coverUrl: '/books_pictures/1cd6529ffca8.jpg',
    pages: 384,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1668-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Les Mille et Une Nuits',
    author: 'Anonymous',
    coverUrl: '/books_pictures/25481849.jpg',
    pages: 2029,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1706-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Tom Jones',
    author: 'Henry Fielding',
    coverUrl: '/books_pictures/492f74adf810.webp',
    pages: 1100,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1749-02-28',
    description:
      'Les aventures picaresques du bâtard Tom Jones, de la campagne anglaise aux alcôves londoniennes.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Candide',
    author: 'Voltaire',
    coverUrl: '/books_pictures/candide.jpg',
    pages: 129,
    genre: ['Classiques', 'Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1759-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Lolita',
    author: 'Vladimir Nabokov',
    coverUrl: '/books_pictures/222acb03acee.jpg',
    pages: 336,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1777-01-01',
    description: '',
    countryOrigin: 'Espagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les liaisons dangereuses',
    author: 'Pierre Choderlos de Laclos',
    coverUrl: '/books_pictures/9782381220529.jpg',
    pages: 400,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1782-03-23',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Les 120 Journées de Sodome',
    author: 'Marquis de Sade',
    coverUrl: '/books_pictures/5af998fad3e2.jpg',
    pages: 457,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1785-01-01',
    description:
      'Quatre libertins enferment victimes et narratrices au château de Silling pour cataloguer toutes les passions.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "La Marquise d'O",
    author: 'Heinrich von Kleist',
    coverUrl: '/books_pictures/fdb2933ea975.jpg',
    pages: 207,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1808-01-01',
    description:
      'Une veuve vertueuse se découvre enceinte sans souvenir d’amant ; un comte russe réclame sa main.',
    countryOrigin: 'Allemagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'Faust',
    author: 'Johann Wolfgang von Goethe',
    coverUrl: '/books_pictures/Faust.jpg',
    pages: 180,
    genre: ['Classiques', 'Poésie', 'Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1808-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Rob Roy',
    author: 'Walter Scott',
    coverUrl: '/books_pictures/e8151aa90c04.jpg',
    pages: 480,
    genre: ['Classiques', 'Aventure'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1817-01-01',
    description:
      'Intrigues écossaises autour du hors-la-loi Rob Roy MacGregor.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Persuasion',
    author: 'Jane Austen',
    coverUrl: '/books_pictures/b5a3e0eca29e.jpg',
    pages: 268,
    genre: ['Classiques', 'Romance'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1817-12-20',
    description:
      'Anne Elliot, persuadée jadis de rompre, revoit le capitaine Wentworth — l’amour a-t-il survécu ?',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Dernier des Mohicans',
    author: 'James Fenimore Cooper',
    coverUrl: '/books_pictures/3b34614839be.jpg',
    pages: 400,
    genre: ['Classiques', 'Aventure'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1826-01-01',
    description:
      'Hawkeye et Chingachgook escortent deux sœurs dans la forêt coloniale.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Le dernier jour d'un condamné",
    author: 'Victor Hugo',
    coverUrl: '/books_pictures/9782080473356_1_75.jpg',
    pages: 192,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1829-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Notre-Dame de Paris',
    author: 'Victor Hugo',
    coverUrl: '/books_pictures/9791039205511_1_75.jpg',
    pages: 600,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1831-01-16',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Le rouge et le noir',
    author: 'Stendhal',
    coverUrl: '/books_pictures/9782491801434_1_75.jpg',
    pages: 640,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1830-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Le Colonel Chabert',
    author: 'Honoré de Balzac',
    coverUrl: '/books_pictures/f22b79bd53d7.jpg',
    pages: 174,
    genre: ['Classiques', 'Fiction historique'],
    saga: 'La Comédie humaine',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1832-01-01',
    description:
      'Un colonel de Napoléon, laissé pour mort, revient réclamer son nom, sa femme et sa fortune.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Père Goriot',
    author: 'Honoré de Balzac',
    coverUrl: '/books_pictures/a0b7c2440be3.jpg',
    pages: 368,
    genre: ['Classiques', 'Littérature'],
    saga: 'La Comédie humaine',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1835-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Illusions perdues',
    author: 'Honoré de Balzac',
    coverUrl: '/books_pictures/60a6dea4b824.jpg',
    pages: 664,
    genre: ['Classiques'],
    saga: 'La Comédie humaine',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1837-01-01',
    description:
      'Lucien de Rubempré quitte Angoulême pour Paris et se brise sur le journalisme, l’édition et le monde.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Oliver Twist',
    author: 'Charles Dickens',
    coverUrl: '/books_pictures/oliver-twist-illustrated-edition.jpg',
    pages: 480,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1838-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Un chant de Noël',
    author: 'Charles Dickens',
    coverUrl: '/books_pictures/811de8153c2a.jpg',
    pages: 80,
    genre: ['Classiques', 'Conte'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1843-12-19',
    description:
      'L’avare Scrooge reçoit la visite de trois esprits qui lui montrent Noël passé, présent et à venir.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Mon oncle Benjamin',
    author: 'Claude Tillier',
    coverUrl: '/books_pictures/84f3fcbd8ee4.jpg',
    pages: 304,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1843-01-01',
    description:
      'Le médecin libertin Benjamin Rathery nargue les notables d’un bourg bourguignon, verre en main.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Carmen',
    author: 'Prosper Mérimée',
    coverUrl: '/books_pictures/f985325afbb8.jpg',
    pages: 112,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1845-01-01',
    description: 'Don José s’abîme dans la passion pour la gitane Carmen.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Hauts de Hurlevent',
    author: 'Emily Brontë',
    coverUrl: '/books_pictures/les_hauts_de_hurlevent.jpg',
    pages: 464,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1847-12-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'La Dame aux camélias',
    author: 'Alexandre Dumas fils',
    coverUrl: '/books_pictures/9782381222431.jpg',
    pages: 256,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1848-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Les Nuits blanches',
    author: 'Fiodor Dostoïevski',
    coverUrl: '/books_pictures/2a3091a296d2.jpg',
    pages: 36,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1848-01-01',
    description:
      'Un rêveur solitaire de Saint-Pétersbourg lie connaissance avec Nastenka pendant quatre nuits blanches.',
    countryOrigin: 'Russie',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Douce',
    author: 'Fiodor Dostoïevski',
    coverUrl: '/books_pictures/7d6867bc6d69.jpg',
    pages: 1886,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1876-01-01',
    description:
      'Un prêteur sur gages veille le cadavre de sa jeune femme et reconstitue le piège de leur mariage.',
    countryOrigin: 'Russie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Frères Karamazov',
    author: 'Fiodor Dostoïevski',
    coverUrl: '/books_pictures/9788726583298_1_75.jpg',
    pages: 796,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1880-01-01',
    description: '',
    countryOrigin: 'Russie',
    selectDisplayOrder: 30,
  },
  {
    title: 'Moby Dick',
    author: 'Herman Melville',
    coverUrl: '/books_pictures/71hoT+tt7CL._UF1000,1000_QL80_.jpg',
    pages: 635,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1851-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Billy Budd',
    author: 'Herman Melville',
    coverUrl: '/books_pictures/71e363c6933c.jpg',
    pages: 183,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1924-01-01',
    description:
      'Sur un navire de guerre, le beau marin Billy frappe le maître d’armes qui l’a calomnié — et doit mourir.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Madame Bovary',
    author: 'Gustave Flaubert',
    coverUrl: '/books_pictures/madame-bovary.jpg',
    pages: 528,
    genre: ['Classiques', 'Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1856-12-15',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Salammbô',
    author: 'Gustave Flaubert',
    coverUrl: '/books_pictures/ac3bb18c67a3.jpg',
    pages: 448,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1862-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: "L'Education sentimentale",
    author: 'Gustave Flaubert',
    coverUrl: '/books_pictures/c951e8b9ddab.jpeg',
    pages: 480,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1869-11-17',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Les Fleurs du Mal',
    author: 'Charles Baudelaire',
    coverUrl: '/books_pictures/e9fe982059d6.jpg',
    pages: 320,
    genre: ['Classiques', 'Poésie'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1857-06-25',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Les Misérables',
    author: 'Victor Hugo',
    coverUrl: '/books_pictures/9782075128063_1_75.jpg',
    pages: 1900,
    genre: ['Classiques'],
    saga: 'Les Misérables',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1862-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Guerre et Paix',
    author: 'Léon Tolstoï',
    coverUrl: '/books_pictures/91qq71ZKA0L._UF1000,1000_QL80_.jpg',
    pages: 1225,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1869-01-01',
    description: '',
    countryOrigin: 'Russie',
    selectDisplayOrder: 30,
  },
  {
    title: 'La Mort d’Ivan Ilitch',
    author: 'Léon Tolstoï',
    coverUrl: '/books_pictures/11b9fcc6a37e.jpg',
    pages: 128,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1886-01-01',
    description:
      'Un magistrat confronte sa mort et le vide d’une vie “comme il faut”.',
    countryOrigin: 'Russie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Robin des Bois',
    author: 'Alexandre Dumas',
    coverUrl:
      '/books_pictures/7a726fead355.jpg',
    pages: 400,
    genre: ['Classiques', 'Aventure'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1872-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Ben-Hur',
    author: 'Lew Wallace',
    coverUrl: '/books_pictures/1d91464aba42.jpg',
    pages: 700,
    genre: ['Classiques', 'Aventure'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1880-01-01',
    description:
      'Roman (inspiré du film) : vengeance, foi et rédemption sous l’Empire romain.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Une partie de campagne',
    author: 'Guy de Maupassant',
    coverUrl: '/books_pictures/f6e19bcc218c.jpg',
    pages: 92,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1881-01-01',
    description:
      'Un dimanche au bord de l’eau : une jeune femme cède à un rameur, souvenir d’un plaisir jamais égalé.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Plaisir',
    author: 'Guy de Maupassant',
    coverUrl: '/books_pictures/a5247e4c7bfe.jpg',
    pages: 272,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1884-01-01',
    description:
      'Trois contes du désir et de la mondanité, dont « La Maison Tellier » et le masque d’un vieil homme au bal.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Bel-Ami',
    author: 'Guy de Maupassant',
    coverUrl: '/books_pictures/bel_ami.jpg',
    pages: 432,
    genre: ['Classiques', 'Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1885-04-27',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'The Mayor of Casterbridge',
    author: 'Thomas Hardy',
    coverUrl: '/books_pictures/6518e3d71e03.jpg',
    pages: 363,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1886-01-01',
    description:
      'Ivrogne, Michael Henchard vend sa femme ; des années plus tard, maire, le passé le rattrape.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: "Tess d'Urberville",
    author: 'Thomas Hardy',
    coverUrl: '/books_pictures/21ac8139345f.jpeg',
    pages: 592,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1891-01-01',
    description:
      'Tess, paysanne séduite puis abandonnée, tente de se racheter dans l’Angleterre victorienne impitoyable.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Bête humaine',
    author: 'Émile Zola',
    coverUrl: '/books_pictures/342f1773a8da.jpg',
    pages: 448,
    genre: ['Classiques', 'Littérature'],
    saga: 'Les Rougon-Macquart',
    sagaOrder: 17,
    sagaFinished: false,
    releaseDate: '1890-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Tristana',
    author: 'Benito Pérez Galdós',
    coverUrl: '/books_pictures/7db5c7d039be.jpg',
    pages: 252,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1892-01-01',
    description:
      'Orpheline recueillie par don Lope, Tristana refuse le rôle de maîtresse et rêve d’indépendance.',
    countryOrigin: 'Espagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Sing-song Girls of Shanghai',
    author: 'Han Bangqing',
    coverUrl: '/books_pictures/3dda4c21b7f9.jpg',
    pages: 592,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1894-01-01',
    description:
      'Chronique des courtisanes de Shanghai à la fin des Qing, entre salons, dettes et illusions.',
    countryOrigin: 'Chine',
    selectDisplayOrder: 0,
  },
  {
    title: 'Tevye der milkhiker',
    author: 'Sholem Aleichem',
    coverUrl: '/books_pictures/1a36220fddd3097bdee64ba2976a88ec.jpg',
    pages: 170,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1894-01-01',
    description:
      'Tévié le laitier, ses filles et la tradition yiddish menacée — Un violon sur le toit.',
    countryOrigin: 'Ukraine',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Femme et le Pantin',
    author: 'Pierre Louÿs',
    coverUrl: '/books_pictures/fe9dd6426559.jpg',
    pages: 193,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1898-01-01',
    description:
      'À Séville, Conchita soumet un homme mûr à un jeu de désir et d’humiliation. Cet obscur objet du désir.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'McTeague',
    author: 'Frank Norris',
    coverUrl: '/books_pictures/9fb6896963ef.jpg',
    pages: 324,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1899-01-01',
    description:
      'Un dentiste de San Francisco bascule dans l’avarice, la jalousie et le meurtre, jusqu’au désert.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'éveil",
    author: 'Kate Chopin',
    coverUrl:
      '/books_pictures/01b73c51d191.jpg',
    pages: 220,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1899-04-22',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Knulp',
    author: 'Hermann Hesse',
    coverUrl: '/books_pictures/e07d0020ff6a.jpg',
    pages: 128,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1900-01-01',
    description: '',
    countryOrigin: 'Allemagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Loup des steppes',
    author: 'Hermann Hesse',
    coverUrl: '/books_pictures/11cc6cf900dd.jpeg',
    pages: 224,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1927-01-01',
    description: '',
    countryOrigin: 'Allemagne',
    selectDisplayOrder: 0,
  },
  {
    title: "Le Journal d'une femme de chambre",
    author: 'Octave Mirbeau',
    coverUrl: '/books_pictures/cc25275c6ec0.jpg',
    pages: 346,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1900-01-01',
    description:
      'Célestine, femme de chambre, observe et juge, dans ses carnets, la bourgeoisie, le vice et l’antisémitisme.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Professeur Unrat',
    author: 'Heinrich Mann',
    coverUrl: '/books_pictures/6d3311482853.jpg',
    pages: 288,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1905-01-01',
    description:
      'Un professeur tyrannique s’abîme d’amour pour une chanteuse de cabaret ; L’Ange bleu en naîtra.',
    countryOrigin: 'Allemagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Mère',
    author: 'Maxime Gorki',
    coverUrl: '/books_pictures/a0943f294f75.jpg',
    pages: 160,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1906-01-01',
    description:
      'Une mère analphabète s’éveille à la révolution en suivant son fils, ouvrier militant.',
    countryOrigin: 'Russie',
    selectDisplayOrder: 0,
  },
  {
    title: 'A Room with a View',
    author: 'E.M. Forster',
    coverUrl: '/books_pictures/ccfa637095e1.jpg',
    pages: 204,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1908-01-01',
    description:
      'À Florence puis en Angleterre, Lucy Honeychurch choisit entre convention victorienne et désir véritable.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Howards End',
    author: 'E.M. Forster',
    coverUrl: '/books_pictures/9fc2b9504bf3.jpg',
    pages: 342,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1910-01-01',
    description:
      'Les sœurs Schlegel, les Wilcox et Leonard Bast incarnent les classes anglaises qui se heurtent autour d’une maison.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Route des Indes',
    author: 'E.M. Forster',
    coverUrl: '/books_pictures/3ac1499f81a5.jpg',
    pages: 394,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1924-01-01',
    description:
      'Aux Indes coloniales, une accusation de viol dans les grottes de Marabar brise l’amitié anglo-indienne.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Martin Eden',
    author: 'Jack London',
    coverUrl: '/books_pictures/61T1v69uVgL._AC_UF1000,1000_QL80_.jpg',
    pages: 430,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1909-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: "Le Fantôme de l'Opéra",
    author: 'Gaston Leroux',
    coverUrl: '/books_pictures/4b4fcfb90c43.jpg',
    pages: 368,
    genre: ['Classiques', 'Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1910-01-01',
    description:
      'Dans les sous-sols de l’Opéra de Paris, Erik, défiguré, impose son génie et son amour à la cantatrice Christine.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Mort à Venise',
    author: 'Thomas Mann',
    coverUrl: '/books_pictures/03dd512c117c.jpg',
    pages: 199,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1912-01-01',
    description:
      'L’écrivain Aschenbach, à Venise, s’éprend du jeune Tadzio tandis que le choléra gagne la ville.',
    countryOrigin: 'Allemagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'À la recherche du temps perdu',
    author: 'Marcel Proust',
    coverUrl: '/books_pictures/71HfkGaLA+L._AC_UF1000,1000_QL80_.jpg',
    pages: 4211,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1913-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Un amour de Swann',
    author: 'Marcel Proust',
    coverUrl: '/books_pictures/47090ec0040e.jpg',
    pages: 277,
    genre: ['Classiques', 'Littérature'],
    saga: 'À la recherche du temps perdu',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '1913-01-01',
    description:
      'Charles Swann s’abîme dans la jalousie pour Odette de Crécy, entre sonates et salons du Faubourg.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Du côté de chez Swan',
    author: 'Marcel Proust',
    coverUrl: '/books_pictures/3a82ad288ffb.jpg',
    pages: 528,
    genre: ['Classiques', 'Littérature'],
    saga: 'À la recherche du temps perdu',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '1913-11-14',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Le Temps retrouvé',
    author: 'Marcel Proust',
    coverUrl: '/books_pictures/9e3ebbcf8d15.jpg',
    pages: 331,
    genre: ['Classiques', 'Littérature'],
    saga: 'À la recherche du temps perdu',
    sagaOrder: 7,
    sagaFinished: true,
    releaseDate: '1927-01-01',
    description:
      'Dernier volume de la Recherche : la guerre, le temps qui détruit et l’œuvre qui le sauve.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Métamorphose',
    author: 'Franz Kafka',
    coverUrl: '/books_pictures/9782378287412-scaled.jpg',
    pages: 80,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1915-01-01',
    description: '',
    countryOrigin: 'Autriche',
    selectDisplayOrder: 30,
  },
  {
    title: 'Le Procès',
    author: 'Franz Kafka',
    coverUrl: '/books_pictures/1327112.webp',
    pages: 256,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1925-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Rashômon',
    author: 'Ryunosuke Akutagawa',
    coverUrl: '/books_pictures/7cf6fa619e1b.jpg',
    pages: 80,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1915-01-01',
    description:
      'Plusieurs versions contradictoires d’un crime sous la pluie de Rashômon.',
    countryOrigin: 'Japon',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Magnificent Ambersons',
    author: 'Booth Tarkington',
    coverUrl: '/books_pictures/f7839acf0cc4.jpg',
    pages: 276,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1918-01-01',
    description:
      'Déclin d’une famille aristocratique du Midwest à l’heure de l’automobile et des nouveaux riches.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Lettre d'une inconnue",
    author: 'Stefan Zweig',
    coverUrl: '/books_pictures/lettre-d-une-inconnue-1.jpg',
    pages: 80,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1922-01-01',
    description: '',
    countryOrigin: 'Autriche',
    selectDisplayOrder: 30,
  },
  {
    title: 'An American Tragedy',
    author: 'Theodore Dreiser',
    coverUrl: '/books_pictures/82ff761fc92f.jpg',
    pages: 784,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1925-01-01',
    description:
      'Clyde Griffiths, ambitieux, laisse noyée la ouvrière qui le gêne ; A Place in the Sun.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Mrs Dalloway',
    author: 'Virginia Woolf',
    coverUrl: '/books_pictures/1bc3ac63fcd2.jpg',
    pages: 224,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1925-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Une chambre à soi (Un lieu à soi)',
    author: 'Virginia Woolf',
    coverUrl: '/books_pictures/a06dd6d1b9b3.jpg',
    pages: 143,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1929-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Killers',
    author: 'Ernest Hemingway',
    coverUrl: '/books_pictures/eac262a2bc55.jpg',
    pages: 20,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1927-01-01',
    description:
      'Deux tueurs attendent Ole Andreson dans un snack ; le boxeur refuse de fuir sa mort annoncée.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'To Have and Have Not',
    author: 'Ernest Hemingway',
    coverUrl: '/books_pictures/11029e098bc5.jpg',
    pages: 262,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1937-01-01',
    description:
      'Harry Morgan, pêcheur de Key West, bascule dans la contrebande pour nourrir les siens.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Vieil Homme et la Mer',
    author: 'Ernest Hemingway',
    coverUrl: '/books_pictures/9782378284398-scaled.jpg',
    pages: 127,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1952-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: "À l'Ouest rien de nouveau",
    author: 'Erich Maria Remarque',
    coverUrl: '/books_pictures/2686cd3e199e.jpg',
    pages: 95,
    genre: ['Classiques', 'Fiction historique'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1929-01-29',
    description:
      'Paul Bäumer, volontaire de 1914, décrit la boue, la camaraderie et l’anéantissement d’une génération.',
    countryOrigin: 'Allemagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'Voyage au bout de la nuit',
    author: 'Louis-Ferdinand Céline',
    coverUrl: '/books_pictures/71LUUEJG4dL._UF1000,1000_QL80_.jpg',
    pages: 624,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1932-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: "Journal d'un curé de campagne",
    author: 'Georges Bernanos',
    coverUrl: '/books_pictures/22bd1f26b30d.jpg',
    pages: 253,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1936-01-01',
    description:
      'Un jeune prêtre malade affronte l’indifférence d’un village, le doute et la grâce au quotidien.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Des souris et des hommes',
    author: 'John Steinbeck',
    coverUrl: '/books_pictures/9591cfd27461.jpg',
    pages: 192,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1937-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Les raisins de la colère',
    author: 'John Steinbeck',
    coverUrl: '/books_pictures/9782070501694_1_75.jpg',
    pages: 619,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1939-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: "À l'est d'Éden",
    author: 'John Steinbeck',
    coverUrl: '/books_pictures/44cc50910e63.jpg',
    pages: 631,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1952-09-19',
    description:
      'Deux familles de la vallée de Salinas rejouent Caïn et Abel, de la Bible à la Californie.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Rebecca',
    author: 'Daphné du Maurier',
    coverUrl: '/books_pictures/927ae7fad01e.jpg',
    pages: 386,
    genre: ['Classiques', 'Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1938-08-01',
    description:
      'Une jeune épouse arrive à Manderley et se heurte à l’ombre écrasante de Rebecca, la première femme.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Secret Life of Walter Mitty',
    author: 'James Thurber',
    coverUrl: '/books_pictures/77c2d5005fcb.jpg',
    pages: 32,
    genre: ['Classiques', 'Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1939-01-01',
    description: 'Un homme timide s’évade dans des rêveries héroïques.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Madame Miniver',
    author: 'Jan Struther',
    coverUrl: '/books_pictures/24192676b26d.jpg',
    pages: 320,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1939-01-01',
    description:
      'Roman (inspiré du film “Madame Miniver”) : une famille traverse les épreuves du Blitz.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Silence de la mer',
    author: 'Vercors',
    coverUrl: '/books_pictures/e230efe7c534.jpg',
    pages: 89,
    genre: ['Classiques', 'Fiction historique'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1942-01-01',
    description:
      'Sous l’Occupation, un oncle et sa nièce opposent le silence à l’officier allemand logé chez eux.',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Plus Belles Années de notre vie',
    author: 'MacKinlay Kantor',
    coverUrl: '/books_pictures/eb091c324d99.jpg',
    pages: 500,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1944-01-01',
    description:
      'Roman (inspiré du film) : des vétérans tentent de retrouver une vie civile.',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Au-dessous du volcan',
    author: 'Malcolm Lowry',
    coverUrl: '/books_pictures/3a057e429e1f.jpg',
    pages: 481,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1947-01-01',
    description:
      'Le consul Firmin, alcoolique, vit son dernier Jour des Morts à Quauhnahuac, entre mescal et damnation.',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Vipère au poing',
    author: 'Hervé Bazin',
    coverUrl: '/books_pictures/86439493fe68.jpg',
    pages: 256,
    genre: ['Classiques', 'Littérature'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1948-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: "L'attrape-cœurs",
    author: 'J.D. Salinger',
    coverUrl: '/books_pictures/couv50306888.jpg',
    pages: 277,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1951-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Bonjour tristesse',
    author: 'Françoise Sagan',
    coverUrl: '/books_pictures/e49c19cf8086.jpg',
    pages: 154,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1954-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Sa majesté des mouches',
    author: 'William Golding',
    coverUrl: '/books_pictures/J01711.jpg',
    pages: 224,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1954-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'Le Docteur Jivago',
    author: 'Boris Pasternak',
    coverUrl: '/books_pictures/8efd37d724e9.jpg',
    pages: 870,
    genre: ['Classiques', 'Fiction historique'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1957-01-01',
    description:
      'Le médecin-poète Iouri Jivago traverse révolutions et guerre civile, déchiré entre deux amours.',
    countryOrigin: 'Russie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Guépard',
    author: 'Giuseppe Tomasi di Lampedusa',
    coverUrl: '/books_pictures/c3eea4215f05.jpg',
    pages: 252,
    genre: ['Classiques', 'Fiction historique'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1958-01-01',
    description:
      'En Sicile, le prince Salina voit le Risorgimento emporter son monde : « il faut que tout change pour que rien ne change ».',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: "La promesse de l'aube",
    author: 'Romain Gary',
    coverUrl: '/books_pictures/71bzCCDvRqL._AC_UF1000,1000_QL80_.jpg',
    pages: 480,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1960-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: "Ne tirez pas sur l'oiseau moqueur",
    author: 'Harper Lee',
    coverUrl: '/books_pictures/ne_tirez_pas_sur_l_oiseau_moqueur.jpg',
    pages: 323,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1960-07-11',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Cent ans de solitude',
    author: 'Gabriel García Márquez',
    coverUrl: '/books_pictures/91dQd82Wx3L.jpg',
    pages: 471,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1967-01-01',
    description: '',
    countryOrigin: 'Colombie',
    selectDisplayOrder: 30,
  },
  {
    title: 'Belle du seigneur',
    author: 'Albert Cohen',
    coverUrl: '/books_pictures/51MMGT50H5L._AC_UF1000,1000_QL80_.jpg',
    pages: 848,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1968-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Parfum de femme',
    author: 'Giovanni Arpino',
    coverUrl: '/books_pictures/bcb2f9c203f8.jpg',
    pages: 240,
    genre: ['Classiques', 'Thriller'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1970-01-01',
    description:
      'Roman (inspiré du film) : un rendez-vous décisif autour du sens et de la dignité.',
    countryOrigin: 'Italie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Tristan et Iseult',
    author: 'René Louis',
    coverUrl: '/books_pictures/81V4p-YZ7dL.jpg',
    pages: 220,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1972-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Le nom de la rose',
    author: 'Umberto Eco',
    coverUrl: '/books_pictures/81W6mh0rv1L.jpg',
    pages: 640,
    genre: ['Classiques', 'Policier'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1980-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'La Liste de Schindler',
    author: 'Thomas Keneally',
    coverUrl: '/books_pictures/0b8e0317ffdd.jpg',
    pages: 432,
    genre: ['Classiques', 'Fiction historique'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1982-01-01',
    description: '',
    countryOrigin: 'Australie',
    selectDisplayOrder: 30,
  },
  {
    title: 'La voleuse de livres',
    author: 'Markus Zusak',
    coverUrl: '/books_pictures/71DShLz-d8L.jpg',
    pages: 584,
    genre: ['Fiction', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2005-01-01',
    description: '',
    countryOrigin: 'Australie',
    selectDisplayOrder: 30,
  },
  {
    title: "L'étranger",
    author: 'Albert Camus',
    coverUrl: '/books_pictures/25_9782070360024_1_75.jpg',
    pages: 159,
    genre: ['Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  }
];
