import { BaseBook } from '../../../models/book-model';

export const baseBooksHorreur: BaseBook[] = [
  {
    title: 'The Shining',
    author: 'Stephen King',
    coverUrl: '/books_pictures/81imcWAv6SL._AC_UF1000,1000_QL80_.jpg',
    pages: 447,
    genre: ['Horreur', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1977-01-28',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Frankenstein',
    author: 'Mary Shelley',
    coverUrl: '/books_pictures/frankenstein.jpg',
    pages: 260,
    genre: ['Horreur', 'Classiques', 'Science Fiction'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1818-01-01',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'Dracula',
    author: 'Bram Stoker',
    coverUrl: '/books_pictures/dracula.jpg',
    pages: 488,
    genre: ['Horreur', 'Classiques', 'Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1897-05-26',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'Carrie',
    author: 'Stephen King',
    coverUrl: '/books_pictures/carrie.jpg',
    pages: 240,
    genre: ['Horreur', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1974-04-05',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
  {
    title: 'Désolation',
    author: 'Stephen King',
    coverUrl: '/books_pictures/Desolation.jpg',
    pages: 574,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2016-09-06',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'étrange cas du docteur Jekyll et de Mr. Hyde",
    author: 'Robert Louis Stevenson',
    coverUrl: '/books_pictures/dr_jekyll_et_mr_hyde.jpg',
    pages: 144,
    genre: ['Horreur', 'Classiques', 'Fantasy'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1886-01-05',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 30,
  },
  {
    title: 'La Maison des feuilles',
    author: 'Mark Z. Danielewski',
    coverUrl: '/books_pictures/71E+2fNxsGL._AC_UF1000,1000_QL80_.jpg',
    pages: 978,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2000-03-07',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Katie',
    author: 'Michael McDowell',
    coverUrl: '/books_pictures/81Chytt7icL._SL1500_.jpg',
    pages: 288,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1982-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Lune froide sur babylone',
    author: 'Michael McDowell',
    coverUrl: '/books_pictures/9abb137a91af.jpg',
    pages: 256,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1978-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Les aiguilles d'or",
    author: 'Michael McDowell',
    coverUrl: '/books_pictures/3b379f493cf7.jpg',
    pages: 304,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1981-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'amulette",
    author: 'Michael McDowell',
    coverUrl: '/books_pictures/lamulette-5777777-264-432.jpg',
    pages: 256,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1979-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les contes interdits : Peter Pan',
    author: 'Simon Rousseau',
    coverUrl: '/books_pictures/0797da472eb0.webp',
    pages: 192,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Horla',
    author: 'Guy de Maupassant',
    coverUrl: '/books_pictures/le-horla-80.jpg',
    pages: 200,
    genre: ['Horreur', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1887-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 30,
  },
  {
    title: 'Le Parfum',
    author: 'Patrick Süskind',
    coverUrl: '/books_pictures/66_9782213630380_1_75.jpg',
    pages: 320,
    genre: ['Horreur', 'Fiction', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1985-01-01',
    description: '',
    countryOrigin: 'Allemagne',
    selectDisplayOrder: 30,
  },
  {
    title: "Le Fantôme d'à côté (Chair de poule #16)",
    author: 'R.L. Stine',
    coverUrl: '/books_pictures/818fZs80QuS._AC_UF1000,1000_QL80_.jpg',
    pages: 128,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1994-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Joyland',
    author: 'Stephen King',
    coverUrl: '/books_pictures/0bd2337764fb.jpg',
    pages: 288,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-06-04',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Salem',
    author: 'Stephen King',
    coverUrl: '/books_pictures/90d250f58068.jpg',
    pages: 439,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1975-10-17',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Simetierre',
    author: 'Stephen King',
    coverUrl: '/books_pictures/77bf0d05166d.jpg',
    pages: 416,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1983-11-14',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Misery',
    author: 'Stephen King',
    coverUrl: '/books_pictures/847dea961e8c.jpg',
    pages: 310,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1987-06-08',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Ligne verte',
    author: 'Stephen King',
    coverUrl: '/books_pictures/e56de663301e.jpg',
    pages: 496,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1996-08-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La peau sur les os',
    author: 'Stephen King',
    coverUrl: '/books_pictures/e2a0538eeedc.jpg',
    pages: 416,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1998-09-22',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: '22/11/63',
    author: 'Stephen King',
    coverUrl: '/books_pictures/b7acaa774439.jpg',
    pages: 849,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2011-11-08',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Docteur Sleep',
    author: 'Stephen King',
    coverUrl: '/books_pictures/3d9f85842ec2.jpg',
    pages: 544,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '2013-09-24',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Marche ou crève',
    author: 'Stephen King',
    coverUrl: '/books_pictures/811545e1be78.jpg',
    pages: 384,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1979-07-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Running man',
    author: 'Stephen King',
    coverUrl: '/books_pictures/9498990c7b1b.jpg',
    pages: 224,
    genre: ['Horreur'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1982-05-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Mr. Mercedes',
    author: 'Stephen King',
    coverUrl: '/books_pictures/3ffc2ff71e46.jpg',
    pages: 436,
    genre: ['Horreur'],
    saga: 'Trilogie Bill Hodges',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2014-06-03',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Carnets noirs',
    author: 'Stephen King',
    coverUrl: '/books_pictures/47d063659577.jpg',
    pages: 560,
    genre: ['Horreur'],
    saga: 'Trilogie Bill Hodges',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2015-06-02',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Fin de ronde',
    author: 'Stephen King',
    coverUrl: '/books_pictures/4e70c5a88d9c.jpg',
    pages: 496,
    genre: ['Horreur'],
    saga: 'Trilogie Bill Hodges',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '2016-06-07',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Montagnes hallucinées',
    author: 'H.P. Lovecraft',
    coverUrl: '',
    pages: 160,
    genre: ['Horreur', 'Science Fiction', 'Classiques'],
    saga: '',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1936-02-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 30,
  },
];
