import { BaseBook } from '../../../models/book-model';

export const baseBooksFromKevin: BaseBook[] = [
  {
    title: "L'étranger",
    author: 'Albert Camus',
    coverUrl: '/books_pictures/25_9782070360024_1_75.jpg',
    pages: 159,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
  },
  {
    title: "L'Alchimiste",
    author: 'Paulo Coelho',
    coverUrl: '/books_pictures/24_9782290258064_1_75.jpg',
    pages: 224,
    genre: 'Fiction',
    saga: '',
    sagaOrder: 0,
  },
  {
    title: 'Le porteur de lumière, tome 1 : Le prisme noir',
    author: 'Brent Weeks',
    coverUrl: '/books_pictures/9161wIQDCzL._AC_UF1000,1000_QL80_.jpg',
    pages: 688,
    genre: 'Fantasy',
    saga: 'Le porteur de lumière',
    sagaOrder: 1,
  },
  {
    title: "Héros de l'Olympe, tome 1 : Le héros perdu",
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/815Gg+369GL.jpg',
    pages: 640,
    genre: 'Fantasy',
    saga: "Héros de l'Olympe",
    sagaOrder: 1,
  },
  {
    title: 'Croc-Blanc',
    author: 'Jack London',
    coverUrl: '/books_pictures/A65190.jpg',
    pages: 288,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
  },
  {
    title: 'Robinson Crusoé',
    author: 'Daniel Defoe',
    coverUrl: '/books_pictures/61_9782011611536_1_75.jpg',
    pages: 352,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
  },
  {
    title: "L'Assassin royal, tome 1 : L'Apprenti assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal.jpg',
    pages: 576,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 1,
  },
  {
    title: "L'Assassin royal, tome 2 : L'Assassin du roi",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/50_9782290383353_1_75.jpg',
    pages: 640,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 2,
  },
  {
    title: "L'Assassin royal, tome 3 : La Nef du crépuscule",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/B17ujV8KQ3L._UF1000,1000_QL80_.jpg',
    pages: 608,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 3,
  },
  {
    title: "L'Assassin royal, tome 4 : Le Poison de la vengeance",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/71tHCd+juBL._AC_UF1000,1000_QL80_.jpg',
    pages: 560,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 4,
  },
  {
    title: "L'Assassin royal, tome 5 : La voie magique",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal (1).jpg',
    pages: 576,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 5,
  },
  {
    title: "L'Assassin royal, tome 6 : La Reine solitaire",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290383315.jpg',
    pages: 608,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 6,
  },
  {
    title: "L'Assassin royal, tome 7 : Le Prophète blanc",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290383360.jpg',
    pages: 528,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 7,
  },
  {
    title: "L'Assassin royal, tome 8 : La Secte maudite",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal (2).jpg',
    pages: 608,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 8,
  },
  {
    title: "L'Assassin royal, tome 9 : Les Secrets de Castelcerf",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/B1toxBHfsJL._UF1000,1000_QL80_.jpg',
    pages: 640,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 9,
  },
  {
    title: "L'Assassin royal, tome 10 : Serments et deuils",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/B1lUlSj6qbL._UF1000,1000_QL80_.jpg',
    pages: 624,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 10,
  },
  {
    title: "L'Assassin royal, tome 11 : Le Dragon des glaces",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/B1q-2ak7erL._UF1000,1000_QL80_.jpg',
    pages: 608,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 11,
  },
  {
    title: "L'Assassin royal, tome 12 : L'Homme noir",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal (3).jpg',
    pages: 640,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 12,
  },
  {
    title: "L'Assassin royal, tome 13 : Adieux et retrouvailles",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal (4).jpg',
    pages: 656,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 13,
  },
  {
    title: "Le Fou et l'Assassin, tome 1",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290403303_1_75.jpg',
    pages: 592,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 1,
  },
  {
    title: "Le fou et l'assassin, tome 2 : La fille de l'assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/La-fille-de-l-aain.jpg',
    pages: 608,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 2,
  },
  {
    title: "Le fou et l'assassin, tome 3 : En quête de vengeance",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290403341-475x500-1.webp',
    pages: 624,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 3,
  },
  {
    title: "Le fou et l'assassin, tome 4 : Le retour de l'assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290403327-475x500-1.jpg',
    pages: 640,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 4,
  },
  {
    title: "Le fou et l'assassin, tome 5 : Sur les rives de l'Art",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/Sur-les-rives-de-l-Art.jpg',
    pages: 656,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 5,
  },
  {
    title: "Le fou et l'assassin, tome 6 : Le destin de l'assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/Le-destin-de-l-aain.jpg',
    pages: 672,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 6,
  },
  {
    title: 'Quand vient la horde',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/61JJS7F1YLL._AC_UF1000,1000_QL80_.jpg',
    pages: 352,
    genre: 'Fantasy',
    saga: '',
    sagaOrder: 0,
  },
  {
    title: 'Les annales du Disque-Monde, tome 1 : La huitième couleur',
    author: 'Terry Pratchett',
    coverUrl: '/books_pictures/9782266211819_1_75.jpg',
    pages: 288,
    genre: 'Fantasy',
    saga: 'Les annales du Disque-Monde',
    sagaOrder: 1,
  },
  {
    title: "Nevernight, tome 1 : N'oublie jamais",
    author: 'Jay Kristoff',
    coverUrl: '/books_pictures/Nevernight-Tome-01-N-oublie-jamais-broche.jpg',
    pages: 512,
    genre: 'Fantasy',
    saga: 'Nevernight',
    sagaOrder: 1,
  },
  {
    title: 'Nevernight, tome 2 : Les grands jeux',
    author: 'Jay Kristoff',
    coverUrl: '/books_pictures/Nevernight-Tome-02-Les-grands-jeux-broche.jpg',
    pages: 576,
    genre: 'Fantasy',
    saga: 'Nevernight',
    sagaOrder: 2,
  },
  {
    title: "Nevernight, tome 3 : L'aube obscure",
    author: 'Jay Kristoff',
    coverUrl: '/books_pictures/83_9782378761615_1_75.jpg',
    pages: 608,
    genre: 'Fantasy',
    saga: 'Nevernight',
    sagaOrder: 3,
  },
  {
    title: "Fils des brumes, tome 1 : L'Empire ultime",
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/L-Empire-Ultime-Fils-des-Brumes.jpg',
    pages: 672,
    genre: 'Fantasy',
    saga: 'Fils des brumes',
    sagaOrder: 1,
  },
  {
    title: "Fils des brumes, tome 2 : Le puits de l'ascension",
    author: 'Brandon Sanderson',
    coverUrl:
      '/books_pictures/fils_des_brumes_tome_2_le_puits_de_lascension-997086-264-432.jpg',
    pages: 768,
    genre: 'Fantasy',
    saga: 'Fils des brumes',
    sagaOrder: 2,
  },
  {
    title: 'Fils des brumes, tome 3 : Le héros des siècles',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/Le-Heros-des-siecles-Fils-des-brumes.jpg',
    pages: 800,
    genre: 'Fantasy',
    saga: 'Fils des brumes',
    sagaOrder: 3,
  },
  {
    title: 'Les Voleurs de fumée, tome 1',
    author: 'Sally Green',
    coverUrl: '/books_pictures/81zTGf5yQtL._UF1000,1000_QL80_.jpg',
    pages: 480,
    genre: 'Fantasy',
    saga: 'Les Voleurs de fumée',
    sagaOrder: 1,
  },
  {
    title: 'Le Démon et mademoiselle Prym',
    author: 'Paulo Coelho',
    coverUrl: '/books_pictures/71kpyKFhtIL._AC_UF1000,1000_QL80_.jpg',
    pages: 224,
    genre: 'Fiction',
    saga: '',
    sagaOrder: 0,
  },
  {
    title: 'Les Maîtres enlumineurs, tome 1',
    author: 'David Moody',
    coverUrl:
      '/books_pictures/les_maitres_enlumineurs_tome_1-1482893-264-432.jpg',
    pages: 400,
    genre: 'Fantasy',
    saga: 'Les Maîtres enlumineurs',
    sagaOrder: 1,
  },
  {
    title: "L'Ange de la Nuit, Tome 1 : La Voie des ombres",
    author: 'Brent Weeks',
    coverUrl: '/books_pictures/61eW9gkl4ZL._AC_UF1000,1000_QL80_.jpg',
    pages: 672,
    genre: 'Fantasy',
    saga: "L'Ange de la Nuit",
    sagaOrder: 1,
  },
  {
    title: "Le royaume de Pierre d'Angle, tome 1 : L'art du naufrage",
    author: 'Mark Lawrence',
    coverUrl: '/books_pictures/9782072999123-475x500-1.webp',
    pages: 416,
    genre: 'Fantasy',
    saga: "Le royaume de Pierre d'Angle",
    sagaOrder: 1,
  },
  {
    title: 'Cycle de Tschai - Intégrale',
    author: 'Jack Vance',
    coverUrl: '/books_pictures/71ukooWJDFL._AC_UF1000,1000_QL80_.jpg',
    pages: 800,
    genre: 'Science Fiction',
    saga: '',
    sagaOrder: 0,
  },
  {
    title: 'Les salauds gentilshommes, tome 1 : Les mensonges de Locke Lamora',
    author: 'Scott Lynch',
    coverUrl: '/books_pictures/images.jpg',
    pages: 672,
    genre: 'Fantasy',
    saga: 'Les salauds gentilshommes',
    sagaOrder: 1,
  },
  {
    title: 'Les salauds gentilshommes, tome 2 : Des horizons rouge sang',
    author: 'Scott Lynch',
    coverUrl: '/books_pictures/817mO9uCDEL._UF1000,1000_QL80_.jpg',
    pages: 704,
    genre: 'Fantasy',
    saga: 'Les salauds gentilshommes',
    sagaOrder: 2,
  },
  {
    title: 'Les salauds gentilshommes, tome 3 : La république des voleurs',
    author: 'Scott Lynch',
    coverUrl: '/books_pictures/9791028117948_1_75.jpg',
    pages: 768,
    genre: 'Fantasy',
    saga: 'Les salauds gentilshommes',
    sagaOrder: 3,
  },
  {
    title: 'Les Annales de la Compagnie Noire, Tome 1 : La compagnie noire',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/71pAU06PgBL._UF1000,1000_QL80_.jpg',
    pages: 320,
    genre: 'Fantasy',
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 1,
  },
  {
    title: 'Les Annales de la Compagnie Noire, Tome 2 : Le château noir',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/Le-chateau-noir.jpg',
    pages: 352,
    genre: 'Fantasy',
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 2,
  },
  {
    title: 'Les Annales de la Compagnie Noire, Tome 3 : La rose blanche',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/9782290330685_1_75.jpg',
    pages: 384,
    genre: 'Fantasy',
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 3,
  },
  {
    title: "Le Cycle de Syffe, tome 1 : L'Enfant de poussière",
    author: 'Peter V. Brett',
    coverUrl: '/books_pictures/41INjyFCoVL._SX195_.jpg',
    pages: 624,
    genre: 'Fantasy',
    saga: 'Le Cycle de Syffe',
    sagaOrder: 1,
  },
  {
    title: 'Le cycle de Syffe, tome 2 : La peste et la vigne',
    author: 'Peter V. Brett',
    coverUrl: '/books_pictures/La-peste-et-la-vigne.jpg',
    pages: 656,
    genre: 'Fantasy',
    saga: 'Le Cycle de Syffe',
    sagaOrder: 2,
  },
  {
    title: 'Le cycle de Syffe, tome 3 : Les chiens et la charrue',
    author: 'Peter V. Brett',
    coverUrl: '/books_pictures/Les-chiens-et-la-charrue.jpg',
    pages: 688,
    genre: 'Fantasy',
    saga: 'Le Cycle de Syffe',
    sagaOrder: 3,
  },
  {
    title: 'Le cycle de Syffe, tome 4 : La Maison des veilleurs',
    author: 'Peter V. Brett',
    coverUrl: '/books_pictures/71Kz3M-hJAL._UF1000,1000_QL80_.jpg',
    pages: 720,
    genre: 'Fantasy',
    saga: 'Le Cycle de Syffe',
    sagaOrder: 4,
  },
  {
    title: 'Les faucons de Raverra, tome 1 : La sorcière captive',
    author: 'Melissa Caruso',
    coverUrl: '/books_pictures/81xvgxW2aXL._AC_UF1000,1000_QL80_.jpg',
    pages: 480,
    genre: 'Fantasy',
    saga: 'Les faucons de Raverra',
    sagaOrder: 1,
  },
  {
    title: "Les faucons de Raverra, tome 2 : L'héritière rebelle",
    author: 'Melissa Caruso',
    coverUrl: '/books_pictures/81ayZbT8cVL.jpg',
    pages: 512,
    genre: 'Fantasy',
    saga: 'Les faucons de Raverra',
    sagaOrder: 2,
  },
  {
    title: "Les faucons de Raverra, tome 3 : L'empire libéré",
    author: 'Melissa Caruso',
    coverUrl: '/books_pictures/81F4mKgR4iL._AC_UF1000,1000_QL80_.jpg',
    pages: 544,
    genre: 'Fantasy',
    saga: 'Les faucons de Raverra',
    sagaOrder: 3,
  },
  {
    title: 'Les archives de Roshar, tome 1 : La voie des rois (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/81pXYzQn+8L.jpg',
    pages: 608,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 1,
  },
  {
    title: 'Les archives de Roshar, tome 1 : La voie des rois (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/9782253191247_1_75.jpg',
    pages: 608,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 1,
  },
  {
    title: 'Les archives de Roshar, tome 2 : Le livre des Radieux (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/81EE84gozJL._AC_UF1000,1000_QL80_.jpg',
    pages: 640,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 2,
  },
  {
    title: 'Les archives de Roshar, tome 2 : Le livre des Radieux (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/couv43194286.jpg',
    pages: 640,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 2,
  },
  {
    title: 'Les archives de Roshar, tome 3 : Justicière (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/813UwoQCTXL.jpg',
    pages: 656,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 3,
  },
  {
    title: 'Les archives de Roshar, tome 3 : Justicière (2/2)',
    author: 'Brandon Sanderson',
    coverUrl:
      '/books_pictures/justiciere-brandon-sanderson-les-archives-de-roshar-tome-3-partie-2.jpg',
    pages: 656,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 3,
  },
  {
    title: 'Les archives de Roshar, tome 4 : Rythme de guerre (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/81slChiIC6L.jpg',
    pages: 720,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 4,
  },
  {
    title: 'Les archives de Roshar, tome 4 : Rythme de guerre (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/1_metadata-image-51642058.jpeg',
    pages: 720,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 4,
  },
  {
    title: 'La guilde des ombres, tome 1 : Le don de mort (1/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/81gPgtNVULL.jpg',
    pages: 400,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 1,
  },
  {
    title: 'La guilde des ombres, tome 1 : Le don de mort (2/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/La-Guilde-des-Ombres-T1P2.jpg',
    pages: 400,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 1,
  },
  {
    title: 'La guilde des ombres, tome 2 : Le don de vie (1/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/La-Guilde-des-Ombres-T2P1.jpg',
    pages: 432,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 2,
  },
  {
    title: 'La guilde des ombres, tome 2 : Le don de vie (2/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/La-Guilde-des-Ombres-T2P2.jpg',
    pages: 432,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 2,
  },
  {
    title: 'La guilde des ombres, tome 3 : La guerre céleste (1/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/81xnG84J08L.jpg',
    pages: 464,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 3,
  },
  {
    title: 'La guilde des ombres, tome 3 : La guerre céleste (2/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/81diNDSbQBL.jpg',
    pages: 464,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 3,
  },
  {
    title: 'Le Livre des Martyrs, tome 1 : Les Jardins de la Lune',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/81zDX6N6vnL._AC_UF1000,1000_QL80_.jpg',
    pages: 752,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 1,
  },
  {
    title: 'Le livre des martyrs, tome 2 : Les portes de la maison des morts',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/LELIVREDESMARTYRST2_CVR-scaled.jpg',
    pages: 976,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 2,
  },
  {
    title: 'Le Livre des Martyrs, tome 3 : Les Souvenirs de la Glace',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/81J7joBVIVL._AC_UF1000,1000_QL80_.jpg',
    pages: 1056,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 3,
  },
  {
    title: 'Le Livre des martyrs, tome 4 : La Maison des chaînes',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/81rNfvdkuOL._AC_UF1000,1000_QL80_.jpg',
    pages: 1072,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 4,
  },
  {
    title: 'Le Livre des martyrs, tome 5 : Les Marées de minuit',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/81tv6LF9r1L._AC_UF1000,1000_QL80_.jpg',
    pages: 1136,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 5,
  },
  {
    title: "Wax et Wayne, tome 1 : L'alliage de la justice",
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/libriweb.jpg',
    pages: 416,
    genre: 'Fantasy',
    saga: 'Wax et Wayne',
    sagaOrder: 1,
  },
  {
    title: 'Wax et Wayne, tome 2 : Jeux de masques',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/71xSe0x62eL._UF1000,1000_QL80_.jpg',
    pages: 448,
    genre: 'Fantasy',
    saga: 'Wax et Wayne',
    sagaOrder: 2,
  },
  {
    title: 'Wax et Wayne, tome 3 : Les bracelets des larmes',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/71mv6VCdFbL.jpg',
    pages: 480,
    genre: 'Fantasy',
    saga: 'Wax et Wayne',
    sagaOrder: 3,
  },
  {
    title: "Les Princes d'Ambre - Cycle 1",
    author: 'Roger Zelazny',
    coverUrl: '/books_pictures/81q5MDrRD5L._AC_UF1000,1000_QL80_.jpg',
    pages: 640,
    genre: 'Fantasy',
    saga: "Les Princes d'Ambre",
    sagaOrder: 1,
  },
  {
    title: "L'Arcane des Epées, tome 1 : Le trône du dragon",
    author: 'Tad Williams',
    coverUrl:
      '/books_pictures/larcane_des_epees_tome_1_le_trone_du_dragon-1161-264-432.jpg',
    pages: 768,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 1,
  },
  {
    title: "L'Arcane des Epées, tome 2 : Le roi de l'orage",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/9782266170147-475x500-1.webp',
    pages: 800,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 2,
  },
  {
    title: "L'Arcane des Epées, tome 3 : La maison de l'ancêtre",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/9782266169660_1_75.jpg',
    pages: 832,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 3,
  },
  {
    title: "L'arcane des épées, tome 4 : La pierre de l'adieu",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/71am-Hy+7QL._AC_UF1000,1000_QL80_.jpg',
    pages: 848,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 4,
  },
  {
    title: "L'Arcane des Epées, tome 5 : Le livre du nécromant",
    author: 'Tad Williams',
    coverUrl:
      '/books_pictures/CVT_cvt_LArcane-des-Epees-T5-le-Livre-du-Necromant_8686.webp',
    pages: 864,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 5,
  },
  {
    title: "L'Arcane des Epées, tome 6 : Le cri de Camaris",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/libriweb (1).jpg',
    pages: 880,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 6,
  },
  {
    title: "L'Arcane des Epées, tome 7 : L'ombre de la roue",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/9782266196796-475x500-1.webp',
    pages: 896,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 7,
  },
  {
    title: "L'Arcane des Epées, tome 8 : La tour de l'ange vert",
    author: 'Tad Williams',
    coverUrl:
      '/books_pictures/CVT_cvt_LArcane-des-Epees-T8-la-Tour-de-lAnge-Vert_1326.webp',
    pages: 912,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 8,
  },
  {
    title: "Une couronne d'épines, tome 1 : Tuer la reine",
    author: 'Jennifer Estep',
    coverUrl: '/books_pictures/71lmtW2SGuL._AC_UF1000,1000_QL80_.jpg',
    pages: 480,
    genre: 'Fantasy',
    saga: "Une couronne d'épines",
    sagaOrder: 1,
  },
  {
    title: "Une couronne d'épines, tome 2 : Défendre le prince",
    author: 'Jennifer Estep',
    coverUrl: '/books_pictures/81hqx4l8WSL._UF1000,1000_QL80_.jpg',
    pages: 496,
    genre: 'Fantasy',
    saga: "Une couronne d'épines",
    sagaOrder: 2,
  },
  {
    title: "Une couronne d'épines, tome 3 : Écraser le roi",
    author: 'Jennifer Estep',
    coverUrl: '/books_pictures/81mj9OqmjiL.jpg',
    pages: 512,
    genre: 'Fantasy',
    saga: "Une couronne d'épines",
    sagaOrder: 3,
  },
];
