import { BaseBook } from '../../../models/book-model';

export const baseBooksFantasySaga: BaseBook[] = [
  {
    title: "La Communauté de l'Anneau",
    author: 'J.R.R. Tolkien',
    coverUrl: '/books_pictures/61_9782266346764_1_75.jpg',
    pages: 576,
    genre: ['Fantasy'],
    saga: 'Le Seigneur des Anneaux',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '1954-07-29',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 25,
  },
  {
    title: 'Les deux tours',
    author: 'J.R.R. Tolkien',
    coverUrl: '/books_pictures/11_9782266346771_1_75.jpg',
    pages: 450,
    genre: ['Fantasy'],
    saga: 'Le Seigneur des Anneaux',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '1954-11-11',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 25,
  },
  {
    title: 'Le retour du roi',
    author: 'J.R.R. Tolkien',
    coverUrl: '/books_pictures/9782266346788_1_75.jpg',
    pages: 500,
    genre: ['Fantasy'],
    saga: 'Le Seigneur des Anneaux',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '1955-10-20',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 25,
  },
  {
    title: 'Bilbo le Hobbit',
    author: 'J.R.R. Tolkien',
    coverUrl: '/books_pictures/81kTSgycenL._AC_UF1000,1000_QL80_.jpg',
    pages: 320,
    genre: ['Fantasy'],
    saga: 'Le Seigneur des Anneaux',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1937-09-21',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 25,
  },
  {
    title: 'Le Silmarillon',
    author: 'J.R.R. Tolkien',
    coverUrl: '/books_pictures/17_9782266341240_1_75.jpg',
    pages: 480,
    genre: ['Fantasy'],
    saga: 'Le Seigneur des Anneaux',
    sagaOrder: 0,
    sagaFinished: false,
    releaseDate: '1977-09-15',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 25,
  },
  {
    title: 'Le Monde de Narnia (Tome 1) Le Neveu du Magicien',
    author: 'C.S. Lewis',
    coverUrl: '/books_pictures/810XsvEUR9L._UF1000,1000_QL80_.jpg',
    pages: 208,
    genre: ['Fantasy'],
    saga: 'Le Monde de Narnia',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '1955-05-02',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title:
      "Le Monde de Narnia (Tome 2) Le Lion, la Sorcière blanche et l'Armoire magique",
    author: 'C.S. Lewis',
    coverUrl: '/books_pictures/81bMOFj57eL._UF1000,1000_QL80_.jpg',
    pages: 224,
    genre: ['Fantasy'],
    saga: 'Le Monde de Narnia',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '1950-10-16',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le Monde de Narnia (Tome 3) Le Cheval et son Ecuyer',
    author: 'C. S. Lewis',
    coverUrl: '/books_pictures/narnia-3-cheval-ecuyer.png',
    pages: 240,
    genre: ['Fantasy'],
    saga: 'Le Monde de Narnia',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '1954-09-06',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le Monde de Narnia (Tome 4) Le Prince Caspian',
    author: 'C. S. Lewis',
    coverUrl: '/books_pictures/0636edfc34ef.png',
    pages: 240,
    genre: ['Fantasy'],
    saga: 'Le Monde de Narnia',
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '1951-10-15',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 15,
  },
  {
    title: "Le Monde de Narnia (Tome 5) L'Odyssée du Passeur d'Aurore",
    author: 'C. S. Lewis',
    coverUrl: '/books_pictures/fa70fb199a78.jpg',
    pages: 272,
    genre: ['Fantasy'],
    saga: 'Le Monde de Narnia',
    sagaOrder: 5,
    sagaFinished: true,
    releaseDate: '1952-09-15',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 15,
  },
  {
    title: "Le Monde de Narnia (Tome 6) Le Fauteuil d'Argent",
    author: 'C. S. Lewis',
    coverUrl: '/books_pictures/fab8a20076f0.jpg',
    pages: 271,
    genre: ['Fantasy'],
    saga: 'Le Monde de Narnia',
    sagaOrder: 6,
    sagaFinished: true,
    releaseDate: '1953-09-07',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le Monde de Narnia (Tome 7) La Dernière Bataille',
    author: 'C. S. Lewis',
    coverUrl: '/books_pictures/d38aa685ed3b.png',
    pages: 224,
    genre: ['Fantasy'],
    saga: 'Le Monde de Narnia',
    sagaOrder: 7,
    sagaFinished: true,
    releaseDate: '1956-09-04',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 15,
  },
  {
    title: "La Voie de l'Oré, tome 1 : Le Maître de l'Anarchie",
    author: 'Marie Fabre (II)',
    coverUrl: '/books_pictures/8ab63f69c206.jpg',
    pages: 82,
    genre: ['Fantasy'],
    saga: "La Voie de l'Oré",
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '1972-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le dernier voeu (The Witcher, #1)',
    author: 'Andrzej Sapkowski',
    coverUrl: '/books_pictures/Sorceleur-Witcher-T1-Le-Dernier-Voeu.jpg',
    pages: 384,
    genre: ['Fantasy'],
    saga: 'Sorceleur',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '1993-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: "L'épée de la providence (The Witcher, #2)",
    author: 'Andrzej Sapkowski',
    coverUrl: '/books_pictures/8_9791028103477_1_75.jpg',
    pages: 400,
    genre: ['Fantasy'],
    saga: 'Sorceleur',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '1992-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le sang des elfes (The Witcher, #3)',
    author: 'Andrzej Sapkowski',
    coverUrl: '/books_pictures/Sorceleur-Witcher-T3-Le-Sang-des-elfes.jpg',
    pages: 343,
    genre: ['Fantasy'],
    saga: 'Sorceleur',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '1994-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le temps du mépris (The Witcher, #4)',
    author: 'Andrzej Sapkowski',
    coverUrl: '/books_pictures/81DCJ27+IUL._AC_UF1000,1000_QL80_.jpg',
    pages: 480,
    genre: ['Fantasy'],
    saga: 'Sorceleur',
    sagaOrder: 4,
    sagaFinished: false,
    releaseDate: '1995-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le bapteme du feu (The Witcher, #5)',
    author: 'Andrzej Sapkowski',
    coverUrl:
      '/books_pictures/sorceleur_tome_5_le_bapteme_du_feu-1228316-264-432.jpg',
    pages: 480,
    genre: ['Fantasy'],
    saga: 'Sorceleur',
    sagaOrder: 5,
    sagaFinished: false,
    releaseDate: '1995-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: "La tour de l'hirondelle (The Witcher, #6)",
    author: 'Andrzej Sapkowski',
    coverUrl: '/books_pictures/ac9d6a8accc6.jpg',
    pages: 480,
    genre: ['Fantasy'],
    saga: 'Sorceleur',
    sagaOrder: 6,
    sagaFinished: false,
    releaseDate: '1995-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'La Dame du lac (The Witcher, #7)',
    author: 'Andrzej Sapkowski',
    coverUrl: '/books_pictures/40_9791028102623_1_75.jpg',
    pages: 531,
    genre: ['Fantasy'],
    saga: 'Sorceleur',
    sagaOrder: 7,
    sagaFinished: false,
    releaseDate: '1999-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'La saison des orages (The Witcher, #8)',
    author: 'Andrzej Sapkowski',
    coverUrl: '/books_pictures/dd6fa17a7f69.jpg',
    pages: 531,
    genre: ['Fantasy'],
    saga: 'Sorceleur',
    sagaOrder: 8,
    sagaFinished: false,
    releaseDate: '1999-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Les Royaumes du Nord (À la croisée des mondes, #1)',
    author: 'Philip Pullman',
    coverUrl: '/books_pictures/81ep-Tt8s0L._AC_UF1000,1000_QL80_.jpg',
    pages: 482,
    genre: ['Fantasy'],
    saga: 'À la croisée des mondes',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '1995-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 5,
  },
  {
    title: 'La Tour des anges (A la croisée des mondes, #2)',
    author: 'Philip Pullman',
    coverUrl: '/books_pictures/91Gvmp7c8FL._AC_UF1000,1000_QL80_.jpg',
    pages: 448,
    genre: ['Fantasy'],
    saga: 'À la croisée des mondes',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '1997-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 5,
  },
  {
    title: "Le Miroir d'ambre (À la croisée des mondes, #3)",
    author: 'Philip Pullman',
    coverUrl: '/books_pictures/Le-Miroir-d-ambre.jpg',
    pages: 598,
    genre: [],
    saga: 'À la croisée des mondes',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 5,
  },
  {
    title: "Le Trône de fer, L'Intégrale Tome 1",
    author: 'George R.R. Martin',
    coverUrl:
      '/books_pictures/le_trone_de_fer_integrale_tome_1-89278-264-432.jpg',
    pages: 835,
    genre: ['Fantasy'],
    saga: 'Le Trône de fer',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '1996-08-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: "Le Trône de fer, L'Intégrale Tome 2",
    author: 'George R.R. Martin',
    coverUrl:
      '/books_pictures/le_trone_de_fer_integrale_tome_2-1235271-264-432.jpg',
    pages: 960,
    genre: ['Fantasy'],
    saga: 'Le Trône de fer',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '1998-11-16',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: "Le Trône de fer, L'Intégrale Tome 3",
    author: 'George R.R. Martin',
    coverUrl:
      '/books_pictures/le_trone_de_fer_integrale_tome_3-4198983-264-432.jpg',
    pages: 1149,
    genre: ['Fantasy'],
    saga: 'Le Trône de fer',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '2000-08-08',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: "Le Trône de fer, L'Intégrale Tome 4",
    author: 'George R.R. Martin',
    coverUrl: '/books_pictures/616czALL-bL._AC_UF1000,1000_QL80_.jpg',
    pages: 800,
    genre: ['Fantasy'],
    saga: 'Le Trône de fer',
    sagaOrder: 4,
    sagaFinished: false,
    releaseDate: '2005-11-08',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: "Le Trône de fer, L'Intégrale Tome 5",
    author: 'George R.R. Martin',
    coverUrl: '/books_pictures/Le-trone-de-fer.jpg',
    pages: 800,
    genre: ['Fantasy'],
    saga: 'Le Trône de fer',
    sagaOrder: 5,
    sagaFinished: false,
    releaseDate: '2011-07-12',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Caraval, tome 1',
    author: 'Stephanie Garber',
    coverUrl: '/books_pictures/27da0ae997ff.jpg',
    pages: 436,
    genre: ['Fantasy'],
    saga: 'Caraval',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: 'Espagne',
    selectDisplayOrder: 0,
  },
  {
    title: 'The Fallen Empire, tome 1 : Phoenix Unbound',
    author: 'Grace Draven',
    coverUrl: '/books_pictures/401410364f83.jpg',
    pages: 704,
    genre: ['Fantasy'],
    saga: 'The Fallen Empire',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2000-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Arthur et la cité interdite (Arthur et les Minimoys, #2)',
    author: 'Intervista',
    coverUrl: '/books_pictures/000469078.webp',
    pages: 181,
    genre: ['Fantasy'],
    saga: 'Arthur et les Minimoys',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2003-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 5,
  },
  {
    title: 'Arthur et la vengeance de Maltazard (Arthur et les Minimoys, #3)',
    author: 'Intervista',
    coverUrl:
      '/books_pictures/Arthur-et-les-Minimoys-Tome-3-La-vengeance-de-Maltazard.jpg',
    pages: 176,
    genre: ['Fantasy'],
    saga: 'Arthur et les Minimoys',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '2004-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 5,
  },
  {
    title: 'Arthur et la guerre des deux mondes (Arthur et les Minimoys, #4)',
    author: 'Luc Besson',
    coverUrl: '/books_pictures/61MWXmfL4+L._AC_UF1000,1000_QL80_.jpg',
    pages: 219,
    genre: ['Fantasy'],
    saga: 'Arthur et les Minimoys',
    sagaOrder: 4,
    sagaFinished: false,
    releaseDate: '2005-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 5,
  },
  {
    title: "D'un monde à l'autre",
    author: 'Pierre Bottero',
    coverUrl:
      '/books_pictures/la_quete_dewilan_tome_1_dun_monde_a_lautre-605310-264-432.jpg',
    pages: 320,
    genre: ['Fantasy'],
    saga: 'Ewilan',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '2003-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 20,
  },
  {
    title: 'Les frontières de glace',
    author: 'Pierre Bottero',
    coverUrl:
      '/books_pictures/la_quete_dewilan_tome_2_les_frontieres_de_glace-605311-264-432.jpg',
    pages: 352,
    genre: ['Fantasy'],
    saga: 'Ewilan',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '2004-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 20,
  },
  {
    title: "L'île du destin",
    author: 'Pierre Bottero',
    coverUrl:
      '/books_pictures/la_quete_dewilan_tome_3_lile_du_destin-605313-264-432.jpg',
    pages: 352,
    genre: ['Fantasy'],
    saga: 'Ewilan',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '2005-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 20,
  },
  {
    title: 'La Forêt des captifs',
    author: 'Pierre Bottero',
    coverUrl:
      '/books_pictures/les_mondes_dewilan_tome_1_la_foret_des_captifs-686716-264-432.jpg',
    pages: 384,
    genre: ['Fantasy'],
    saga: 'Ewilan',
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '2006-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 20,
  },
  {
    title: "L'Œil d'Otolep",
    author: 'Pierre Bottero',
    coverUrl:
      '/books_pictures/les_mondes_dewilan_tome_2_loeil_dotolep-6550-264-432.jpg',
    pages: 384,
    genre: ['Fantasy'],
    saga: 'Ewilan',
    sagaOrder: 5,
    sagaFinished: true,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 20,
  },
  {
    title: 'Les Tentacules du mal',
    author: 'Pierre Bottero',
    coverUrl:
      '/books_pictures/les_mondes_dewilan_tome_3_les_tentacules_du_mal-6551-264-432.jpg',
    pages: 448,
    genre: ['Fantasy'],
    saga: 'Ewilan',
    sagaOrder: 6,
    sagaFinished: true,
    releaseDate: '2008-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 20,
  },
  {
    title: 'Ellana',
    author: 'Pierre Bottero',
    coverUrl:
      '/books_pictures/le_pacte_des_marchombres_tome_1_ellana-54302-264-432.jpg',
    pages: 448,
    genre: ['Fantasy'],
    saga: 'Ewilan',
    sagaOrder: 7,
    sagaFinished: true,
    releaseDate: '2006-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 20,
  },
  {
    title: "Ellana, l'Envol",
    author: 'Pierre Bottero',
    coverUrl:
      '/books_pictures/le_pacte_des_marchombres_tome_2_ellana_lenvol-6778-264-432.jpg',
    pages: 480,
    genre: ['Fantasy'],
    saga: 'Ewilan',
    sagaOrder: 8,
    sagaFinished: true,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 20,
  },
  {
    title: 'Ellana, la Prophétie',
    author: 'Pierre Bottero',
    coverUrl:
      '/books_pictures/le_pacte_des_marchombres_tome_3_ellana_la_prophetie-6781-264-432.jpg',
    pages: 640,
    genre: ['Fantasy'],
    saga: 'Ewilan',
    sagaOrder: 9,
    sagaFinished: true,
    releaseDate: '2008-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 20,
  },
  {
    title: 'Les sortceliers',
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_1_les_sortceliers-2285542-264-432.jpg',
    pages: 501,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '2003-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le livre interdit',
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_2_le_livre_interdit-52137-264-432.jpg',
    pages: 502,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '2004-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le sceptre maudit',
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_3_le_sceptre_maudit-236537-264-432.jpg',
    pages: 503,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '2005-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le dragon renégat',
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_4_le_dragon_renegat-9381-264-432.jpg',
    pages: 507,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '2006-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le continent interdit',
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_5_le_continent_interdit-39259-264-432.jpg',
    pages: 506,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 5,
    sagaFinished: true,
    releaseDate: '2007-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'Dans le piège de Magister',
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_6_dans_le_piege_de_magister-100912-264-432.jpg',
    pages: 508,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 6,
    sagaFinished: true,
    releaseDate: '2008-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: "Tara Duncan et l'invasion fantôme",
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_7_linvasion_fantome-118545-264-432.jpg',
    pages: 504,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 7,
    sagaFinished: true,
    releaseDate: '2009-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: "L'impératrice maléfique",
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_8_limperatrice_malefique-68463-264-432.jpg',
    pages: 505,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 8,
    sagaFinished: true,
    releaseDate: '2010-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'Tara Duncan contre la reine noire',
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_9_tara_duncan_contre_la_reine_noire-233246-264-432.jpg',
    pages: 503,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 9,
    sagaFinished: true,
    releaseDate: '2011-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'Dragons contre Démons',
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_10_dragons_contre_demons-2576032-264-432.jpg',
    pages: 527,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 10,
    sagaFinished: true,
    releaseDate: '2012-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'La Guerre des planètes',
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_11_la_guerre_des_planetes-323656-264-432.jpg',
    pages: 519,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 11,
    sagaFinished: true,
    releaseDate: '2013-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: "L'Ultime Combat",
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_12_lultime_combat-493535-264-432.jpg',
    pages: 518,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 12,
    sagaFinished: true,
    releaseDate: '2014-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'Tara et Cal',
    author: 'Sophie Audouin-Mamikonian',
    coverUrl:
      '/books_pictures/tara_duncan_tome_13_tara_et_cal-684594-264-432.jpg',
    pages: 520,
    genre: ['Fantasy'],
    saga: 'Tara Duncan',
    sagaOrder: 13,
    sagaFinished: true,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'Eragon (Eragon, #1)',
    author: 'Christopher Paolini',
    coverUrl: '/books_pictures/49_9791036313691_1_75.jpg',
    pages: 509,
    genre: ['Fantasy'],
    saga: 'Eragon',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2003-08-26',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: "L'aîné (Eragon, #2)",
    author: 'Christopher Paolini',
    coverUrl: '/books_pictures/Eragon-poche-Tome-02.jpg',
    pages: 704,
    genre: ['Fantasy'],
    saga: 'Eragon',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2005-08-23',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Brisingr (Eragon, #3)',
    author: 'Christopher Paolini',
    coverUrl: '/books_pictures/38_9791036313707_1_75.jpg',
    pages: 826,
    genre: ['Fantasy'],
    saga: 'Eragon',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '2008-09-20',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: "L'héritage (Eragon, #4)",
    author: 'Christopher Paolini',
    coverUrl: '/books_pictures/81Qk1KAq0kL._AC_UF1000,1000_QL80_.jpg',
    pages: 860,
    genre: ['Fantasy'],
    saga: 'Eragon',
    sagaOrder: 4,
    sagaFinished: false,
    releaseDate: '2011-11-08',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Murtagh',
    author: 'Christopher Paolini',
    coverUrl: '/books_pictures/1b72e74a7018.jpg',
    pages: 680,
    genre: ['Fantasy', 'Aventure'],
    saga: 'Eragon',
    sagaOrder: 5,
    sagaFinished: false,
    releaseDate: '2023-11-07',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Voleur de foudre',
    author: 'Rick Riordan',
    coverUrl:
      '/books_pictures/percy_jackson_tome_1_le_voleur_de_foudre-997184-264-432.jpg',
    pages: 377,
    genre: ['Fantasy'],
    saga: 'Percy Jackson',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '2005-06-28',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'La Mer des monstres',
    author: 'Rick Riordan',
    coverUrl:
      '/books_pictures/percy_jackson_tome_2_la_mer_des_monstres-48633-264-432.jpg',
    pages: 279,
    genre: ['Fantasy'],
    saga: 'Percy Jackson',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '2006-04-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Le Sort du titan',
    author: 'Rick Riordan',
    coverUrl:
      '/books_pictures/percy_jackson_tome_3_le_sort_du_titan-70591-264-432.jpg',
    pages: 312,
    genre: ['Fantasy'],
    saga: 'Percy Jackson',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '2007-05-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'La Bataille du labyrinthe',
    author: 'Rick Riordan',
    coverUrl:
      '/books_pictures/percy_jackson_tome_4_la_bataille_du_labyrinthe-380098-264-432.jpg',
    pages: 361,
    genre: ['Fantasy'],
    saga: 'Percy Jackson',
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '2008-05-06',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Le Dernier Olympien',
    author: 'Rick Riordan',
    coverUrl:
      '/books_pictures/percy_jackson_tome_5_le_dernier_olympien-77283-264-432.jpg',
    pages: 381,
    genre: ['Fantasy'],
    saga: 'Percy Jackson',
    sagaOrder: 5,
    sagaFinished: true,
    releaseDate: '2009-05-05',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Le Calice des dieux',
    author: 'Rick Riordan',
    coverUrl:
      '/books_pictures/percy_jackson_tome_6_le_calice_des_dieux-5319264-264-432.jpg',
    pages: 288,
    genre: ['Fantasy'],
    saga: 'Percy Jackson',
    sagaOrder: 6,
    sagaFinished: true,
    releaseDate: '2023-09-26',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'La Déesse aux trois visages',
    author: 'Rick Riordan',
    coverUrl:
      '/books_pictures/Couverture_VAngl_29_-_PJ_Wrath_of_the_Triple_Goddess.webp',
    pages: 288,
    genre: ['Fantasy'],
    saga: 'Percy Jackson',
    sagaOrder: 7,
    sagaFinished: false,
    releaseDate: '2025-09-23',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 20,
  },
  {
    title: 'Eon et le douxième dragon',
    author: 'Alison Goodman',
    coverUrl:
      '/books_pictures/a00d52e7f783.jpg',
    pages: 640,
    genre: ['Fantasy'],
    saga: 'Eon',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2008-01-01',
    description: '',
    countryOrigin: 'Australie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le prisme noir',
    author: 'Brent Weeks',
    coverUrl: '/books_pictures/9161wIQDCzL._AC_UF1000,1000_QL80_.jpg',
    pages: 688,
    genre: ['Fantasy'],
    saga: 'Le Porteur de Lumière',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2008-10-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Couteau Aveuglant',
    author: 'Brent Weeks',
    coverUrl:
      '/books_pictures/le_porteur_de_lumiere_tome_2_le_couteau_aveuglant-3750482-264-432.jpg',
    pages: 677,
    genre: ['Fantasy'],
    saga: 'Le Porteur de Lumière',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Oeil Brisé",
    author: 'Brent Weeks',
    coverUrl:
      '/books_pictures/le_porteur_de_lumiere_tome_3_loeil_brise-604491-264-432.jpg',
    pages: 672,
    genre: ['Fantasy'],
    saga: 'Le Porteur de Lumière',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Miroir de Sang',
    author: 'Brent Weeks',
    coverUrl:
      '/books_pictures/le_porteur_de_lumiere_tome_4_le_miroir_de_sang-905374-264-432.jpg',
    pages: 672,
    genre: ['Fantasy'],
    saga: 'Le Porteur de Lumière',
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Blanc Incandescent (1/2)',
    author: 'Brent Weeks',
    coverUrl:
      '/books_pictures/le_porteur_de_lumiere_tome_5_le_blanc_incandescent_premiere_partie-1330136-264-432.jpg',
    pages: 600,
    genre: ['Fantasy'],
    saga: 'Le Porteur de Lumière',
    sagaOrder: 5,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Blanc Incandescent (2/2)',
    author: 'Brent Weeks',
    coverUrl:
      '/books_pictures/le_porteur_de_lumiere_tome_6_le_blanc_incandescent_deuxieme_partie-1382619-264-432.jpg',
    pages: 648,
    genre: ['Fantasy'],
    saga: 'Le Porteur de Lumière',
    sagaOrder: 6,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Héros de l'Olympe, Tome 1 : Le Héros perdu",
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/81pjV-scHpL._AC_UF1000,1000_QL80_.jpg',
    pages: 580,
    genre: ['Fantasy'],
    saga: "Héros de l'Olympe",
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2010-10-12',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 10,
  },
  {
    title: "Héros de l'Olympe, Tome 2 : Le Fils de Neptune",
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/91PxmWrS7yL._AC_UF1000,1000_QL80_.jpg',
    pages: 540,
    genre: ['Fantasy'],
    saga: "Héros de l'Olympe",
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2011-10-04',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 10,
  },
  {
    title: "Héros de l'Olympe, Tome 3 : La Marque d'Athena",
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/91TfZ+Y1CyL._AC_UF1000,1000_QL80_.jpg',
    pages: 600,
    genre: ['Fantasy'],
    saga: "Héros de l'Olympe",
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '2012-10-02',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 10,
  },
  {
    title: "Héros de l'Olympe, Tome 4 : La Maison d'Hadès",
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/81rq9zjC08L.jpg',
    pages: 588,
    genre: ['Fantasy'],
    saga: "Héros de l'Olympe",
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '2013-10-08',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 10,
  },
  {
    title: "Héros de l'Olympe, Tome 5 : Le Sang de l'Olympe",
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/91QfZrtBilL._AC_UF1000,1000_QL80_.jpg',
    pages: 576,
    genre: ['Fantasy'],
    saga: "Héros de l'Olympe",
    sagaOrder: 5,
    sagaFinished: true,
    releaseDate: '2014-10-07',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 10,
  },
  {
    title: 'Martyrs - Livre 1',
    author: 'Oliver Peru',
    coverUrl: '/books_pictures/45cd84001736.jpg',
    pages: 700,
    genre: ['Fantasy', 'Aventure'],
    saga: 'Martyrs',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '2013-03-26',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Martyrs - Livre 2',
    author: 'Oliver Peru',
    coverUrl: '/books_pictures/6f0a28b7e9f3.jpg',
    pages: 638,
    genre: [],
    saga: 'Martyrs',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '2014-08-27',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Le Paris des merveilles, tome 1 : Les enchantements d'Ambremer",
    author: 'Pierre Pevel',
    coverUrl: '/books_pictures/bbce89d73ee6.jpg',
    pages: 384,
    genre: ['Fantasy'],
    saga: 'Le Paris des merveilles',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2015-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Soeurs Carmines - Intégrale',
    author: 'Ariel Holzl',
    coverUrl: '/books_pictures/804563294910.png',
    pages: 272,
    genre: ['Fantasy'],
    saga: 'Les Soeurs Carmines',
    sagaOrder: 0,
    sagaFinished: true,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Cour des ténèbres (Vampyria : le cycle de Jeanne, #1)',
    author: 'Victor Dixen',
    coverUrl: '/books_pictures/9782221250570.jpg',
    pages: 528,
    genre: ['Fantasy'],
    saga: 'Vampyria : le cycle de Jeanne',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2017-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 5,
  },
  {
    title: 'La Cour des Miracles (Vampyria : le cycle de Jeanne, #2)',
    author: 'Victor Dixen',
    coverUrl:
      '/books_pictures/La-Cour-des-Miracles-Vampyria-le-cycle-de-Jeanne-2.jpg',
    pages: 528,
    genre: ['Fantasy'],
    saga: 'Vampyria : le cycle de Jeanne',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 5,
  },
  {
    title: 'La Cour des Ouragans (Vampyria : le cycle de Jeanne, #3)',
    author: 'Victor Dixen',
    coverUrl:
      '/books_pictures/La-Cour-des-Ouragans-Vampyria-le-cycle-de-Jeanne-3.jpg',
    pages: 608,
    genre: ['Fantasy'],
    saga: 'Vampyria : le cycle de Jeanne',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 5,
  },
  {
    title: 'Mi-Mouche, tome 1 : Tu veux te battre ?',
    author: 'Véro Cazot',
    coverUrl: '/books_pictures/606b22853a0d.jpg',
    pages: 152,
    genre: ['Fantasy'],
    saga: 'Mi-Mouche',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Terres brisées',
    author: 'Victoria Aveyard',
    coverUrl: '/books_pictures/e7c3f97219ac.jpg',
    pages: 400,
    genre: ['Fantasy', 'Dystopie'],
    saga: 'Victoria Aveyard — tomes annexes',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Lame brisée',
    author: 'Victoria Aveyard',
    coverUrl:
      '/books_pictures/2a01497a94cf.jpg',
    pages: 400,
    genre: ['Fantasy', 'Dystopie'],
    saga: 'Victoria Aveyard — tomes annexes',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Destin brisé',
    author: 'Victoria Aveyard',
    coverUrl:
      '/books_pictures/382af20813c3.jpg',
    pages: 400,
    genre: ['Fantasy', 'Dystopie'],
    saga: 'Victoria Aveyard — tomes annexes',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '2018-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Les Enfants d'Aliel - Le grand éveil",
    author: 'Sara Schneider',
    coverUrl:
      '/books_pictures/les_enfants_daliel_tome_1_le_grand_eveil-1301631-264-432.jpg',
    pages: 411,
    genre: ['Fantasy'],
    saga: "Les enfants d'Aliel",
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 10,
  },
  {
    title: "Les Enfants d'Aliel - Le cheval de feu",
    author: 'Sara Schneider',
    coverUrl:
      '/books_pictures/les_enfants_daliel_tome_2_le_cheval_de_feu-1235625-264-432.jpg',
    pages: 411,
    genre: ['Fantasy'],
    saga: "Les enfants d'Aliel",
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '2020-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 10,
  },
  {
    title: "Les Enfants d'Aliel - Mâchoires d'écume",
    author: 'Sara Schneider',
    coverUrl:
      '/books_pictures/les_enfants_daliel_tome_3_machoires_decume-1347405-264-432.jpg',
    pages: 411,
    genre: ['Fantasy'],
    saga: "Les enfants d'Aliel",
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '2021-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 10,
  },
  {
    title: "Les Enfants d'Aliel - Le porteur d'espoir",
    author: 'Sara Schneider',
    coverUrl:
      '/books_pictures/les_enfants_daliel_tome_4_le_porteur_despoir-1497527-264-432.jpg',
    pages: 411,
    genre: ['Fantasy'],
    saga: "Les enfants d'Aliel",
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '2022-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 10,
  },
  {
    title: "Les Enfants d'Aliel - Ciel de cendres",
    author: 'Sara Schneider',
    coverUrl:
      '/books_pictures/les_enfants_daliel_tome_5_ciel_de_cendres-5009301-264-432.jpg',
    pages: 411,
    genre: ['Fantasy'],
    saga: "Les enfants d'Aliel",
    sagaOrder: 5,
    sagaFinished: true,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 10,
  },
  {
    title: 'Serpent & Dove, tome 1',
    author: 'Shelby Mahurin',
    coverUrl: '/books_pictures/b357fb7318fa.jpg',
    pages: 524,
    genre: ['Fantasy'],
    saga: 'Serpent & Dove',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2019-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Cinquième saison',
    author: 'N.K. Jemisin',
    coverUrl: '/books_pictures/terre_fracturee_tome_1_la_cinquieme_saison.jpg',
    pages: 576,
    genre: ['Fantasy', 'Science Fiction'],
    saga: 'Les livres de la terre fracturée',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '2019-08-28',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Porte de cristal',
    author: 'N.K. Jemisin',
    coverUrl: '/books_pictures/terre_fracturee_tome_2_la_porte_de_cristal.jpg',
    pages: 512,
    genre: ['Fantasy', 'Science Fiction'],
    saga: 'Les livres de la terre fracturée',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '2019-10-09',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Cieux pétrifiés',
    author: 'N.K. Jemisin',
    coverUrl: '/books_pictures/terre_fracturee_tome_3_les_cieux_petrifies.jpg',
    pages: 512,
    genre: ['Fantasy', 'Science Fiction'],
    saga: 'Les livres de la terre fracturée',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '2020-03-11',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Curious Tides, tome 1 : De la Lune et des Marées',
    author: 'Pascale Lacelle',
    coverUrl:
      '/books_pictures/curious-tides-tome-1-de-la-lune-et-des-marees-5348193.jpg',
    pages: 635,
    genre: ['Fantasy'],
    saga: 'Curious Tides',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2023-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Le Prieuré de l'Oranger",
    author: 'Samantha Shannon',
    coverUrl: '/books_pictures/81TvPzzeYGL._AC_UF1000,1000_QL80_.jpg',
    pages: 1024,
    genre: ['Fantasy'],
    saga: "Le Prieuré de l'Oranger",
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Un jour de nuit tombée',
    author: 'Samantha Shannon',
    coverUrl: '/books_pictures/813Tp3wtlML.jpg',
    pages: 1150,
    genre: ['Fantasy'],
    saga: "Le Prieuré de l'Oranger",
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '2023-02-28',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Heartless Hunter, tome 1',
    author: 'Kristen Ciccarelli',
    coverUrl: '/books_pictures/2febefc31a11.jpg',
    pages: 410,
    genre: ['Fantasy'],
    saga: 'Heartless Hunter',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Whisperwicks, tome 1 : Le Labyrinthe sans fin',
    author: 'Jordan Lees',
    coverUrl: '/books_pictures/db98512afe18.jpg',
    pages: 448,
    genre: ['Fantasy'],
    saga: 'Les Whisperwicks',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2024-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: "Divines Rivalités (Lettres d'enchantement, #1)",
    author: 'Rebecca Ross',
    coverUrl: '/books_pictures/142dad6b7fac.jpg',
    pages: 416,
    genre: ['Fantasy', 'Romance'],
    saga: "Lettres d'enchantement",
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2024-05-02',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: "Impitoyables Serments (Lettres d'enchantement, #2)",
    author: 'Rebecca Ross',
    coverUrl: '/books_pictures/906ae43e1b02.jpg',
    pages: 510,
    genre: ['Fantasy', 'Romance'],
    saga: "Lettres d'enchantement",
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '2024-11-28',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: "Féroce Déférence (Lettres d'enchantement, #0)",
    author: 'Rebecca Ross',
    coverUrl:
      '/books_pictures/lettres-denchantement-tome-0-feroce-deference-5811970.jpg',
    genre: ['Fantasy', 'Romance'],
    saga: "Lettres d'enchantement",
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '2026-01-05',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
    pages: 320,
  },
  {
    title: "All of us villains, tome 1 : Le tournoi d'Ilvernath",
    author: 'C. L. Herman',
    coverUrl: '/books_pictures/38a009b7c88c.jpg',
    pages: 432,
    genre: ['Fantasy'],
    saga: 'All of us villains',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2025-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Les Brûleurs d'Or, tome 1 : Les apprentis de Mortcelieu",
    author: 'Alice Parriat',
    coverUrl: '/books_pictures/e88f84d01def.jpg',
    pages: 500,
    genre: ['Fantasy'],
    saga: "Les Brûleurs d'Or",
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2025-01-01',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Sorrowsong University, tome 1 : Nightshade',
    author: 'Autumn Woods',
    coverUrl: '/books_pictures/a0f67070a875.jpg',
    pages: 416,
    genre: ['Fantasy'],
    saga: 'Sorrowsong University',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2025-01-01',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "À la recherche de l'esprit renard, tome 1 : Albans",
    author: 'Alix Naudot Guillerm',
    coverUrl: '/books_pictures/451f4745a8a1.jpg',
    pages: 415,
    genre: ['Fantasy'],
    saga: "À la recherche de l'esprit renard",
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '2025-04-03',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Nom du Vent',
    author: 'Patrick Rothfuss',
    coverUrl: '/books_pictures/nom-vent.jpg',
    pages: 420,
    genre: ['Fantasy'],
    saga: 'Chronique du Tueur de Roi',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Peur du Sage (1/2)',
    author: 'Patrick Rothfuss',
    coverUrl: '/books_pictures/peur-sage-1.jpg',
    pages: 576,
    genre: ['Fantasy'],
    saga: 'Chronique du Tueur de Roi',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Peur du Sage (2/2)',
    author: 'Patrick Rothfuss',
    coverUrl: '/books_pictures/peur-sage-2.jpg',
    pages: 576,
    genre: ['Fantasy'],
    saga: 'Chronique du Tueur de Roi',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Empire Ultime",
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/L-Empire-Ultime-Fils-des-Brumes.jpg',
    pages: 616,
    genre: ['Fantasy'],
    saga: 'Fils des Brumes',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Le puits de l'Ascension",
    author: 'Brandon Sanderson',
    coverUrl:
      '/books_pictures/fils_des_brumes_tome_2_le_puits_de_lascension-997086-264-432.jpg',
    pages: 1080,
    genre: ['Fantasy'],
    saga: 'Fils des Brumes',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Héros des Siècles',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/Le-Heros-des-siecles-Fils-des-brumes.jpg',
    pages: 1032,
    genre: ['Fantasy'],
    saga: 'Fils des Brumes',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Voie des Ombres',
    author: 'Brent Weeks',
    coverUrl: '/books_pictures/voie-ombres.jpg',
    pages: 552,
    genre: ['Fantasy'],
    saga: "L'Ange de la Nuit",
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Choix des Ombres',
    author: 'Brent Weeks',
    coverUrl:
      '/books_pictures/lange_de_la_nuit_tome_2_le_choix_des_ombres-52796-264-432.jpg',
    pages: 704,
    genre: ['Fantasy'],
    saga: "L'Ange de la Nuit",
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Au-delà des Ombres',
    author: 'Brent Weeks',
    coverUrl:
      '/books_pictures/lange_de_la_nuit_tome_3_au_dela_des_ombres-1170772-264-432.jpg',
    pages: 720,
    genre: ['Fantasy'],
    saga: "L'Ange de la Nuit",
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Trône du Dragon',
    author: 'Tad Williams',
    coverUrl:
      '/books_pictures/larcane_des_epees_tome_1_le_trone_du_dragon-1161-264-432.jpg',
    pages: 448,
    genre: ['Fantasy'],
    saga: "L'Arcane des Epées",
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Le Roi de l'Orage",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/9782266170147-475x500-1.webp',
    pages: 480,
    genre: ['Fantasy'],
    saga: "L'Arcane des Epées",
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "La Maison de l'Ancêtre",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/9782266169660_1_75.jpg',
    pages: 448,
    genre: ['Fantasy'],
    saga: "L'Arcane des Epées",
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "La Pierre de l'Adieu",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/71am-Hy+7QL._AC_UF1000,1000_QL80_.jpg',
    pages: 442,
    genre: ['Fantasy'],
    saga: "L'Arcane des Epées",
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Livre du Nécromant',
    author: 'Tad Williams',
    coverUrl:
      '/books_pictures/CVT_cvt_LArcane-des-Epees-T5-le-Livre-du-Necromant_8686.webp',
    pages: 448,
    genre: ['Fantasy'],
    saga: "L'Arcane des Epées",
    sagaOrder: 5,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Cri de Camaris',
    author: 'Tad Williams',
    coverUrl: '/books_pictures/libriweb (1).jpg',
    pages: 448,
    genre: ['Fantasy'],
    saga: "L'Arcane des Epées",
    sagaOrder: 6,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Ombre de la Roue",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/9782266196796-475x500-1.webp',
    pages: 544,
    genre: ['Fantasy'],
    saga: "L'Arcane des Epées",
    sagaOrder: 7,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "La Tour de l'Ange Vert",
    author: 'Tad Williams',
    coverUrl:
      '/books_pictures/CVT_cvt_LArcane-des-Epees-T8-la-Tour-de-lAnge-Vert_1326.webp',
    pages: 576,
    genre: ['Fantasy'],
    saga: "L'Arcane des Epées",
    sagaOrder: 8,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Apprenti Assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal.jpg',
    pages: 510,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: "L'Assassin du Roi",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/50_9782290383353_1_75.jpg',
    pages: 416,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'La Nef du Crépuscule',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/B17ujV8KQ3L._UF1000,1000_QL80_.jpg',
    pages: 416,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le Poison de la Vengeance',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/71tHCd+juBL._AC_UF1000,1000_QL80_.jpg',
    pages: 352,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'La Voie Magique',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal (1).jpg',
    pages: 384,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 5,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'La Reine Solitaire',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290383315.jpg',
    pages: 384,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 6,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le Prophète Blanc',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290383360.jpg',
    pages: 411,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 7,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'La Secte Maudite',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal (2).jpg',
    pages: 445,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 8,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Les Secrets de Castelcerf',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/B1toxBHfsJL._UF1000,1000_QL80_.jpg',
    pages: 471,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 9,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Serments et Deuils',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/B1lUlSj6qbL._UF1000,1000_QL80_.jpg',
    pages: 300,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 10,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le Dragon des Glaces',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/B1q-2ak7erL._UF1000,1000_QL80_.jpg',
    pages: 381,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 11,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: "L'Homme Noir",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal (3).jpg',
    pages: 327,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 12,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Adieux et Retrouvailles',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal (4).jpg',
    pages: 378,
    genre: ['Fantasy'],
    saga: "L'Assassin Royal",
    sagaOrder: 13,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Le Don de Mort',
    author: 'Anna Triss',
    coverUrl: '/books_pictures/don-de-mort.jpg',
    pages: 864,
    genre: ['Fantasy'],
    saga: 'La Guilde des Ombres',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Grande Traque',
    author: 'Anna Triss',
    coverUrl: '/books_pictures/grande-traque.jpg',
    pages: 864,
    genre: ['Fantasy'],
    saga: 'La Guilde des Ombres',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Don de Vie',
    author: 'Anna Triss',
    coverUrl: '/books_pictures/don-de-vie.jpg',
    pages: 822,
    genre: ['Fantasy'],
    saga: 'La Guilde des Ombres',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Etoile de Feu",
    author: 'Anna Triss',
    coverUrl: '/books_pictures/etoile-de-feu.jpg',
    pages: 976,
    genre: ['Fantasy'],
    saga: 'La Guilde des Ombres',
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Guerre Céleste',
    author: 'Anna Triss',
    coverUrl: '/books_pictures/guerre-celeste.jpg',
    pages: 816,
    genre: ['Fantasy'],
    saga: 'La Guilde des Ombres',
    sagaOrder: 5,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Dixième Prophétie',
    author: 'Anna Triss',
    coverUrl: '/books_pictures/dixieme-prophetie.jpg',
    pages: 1176,
    genre: ['Fantasy'],
    saga: 'La Guilde des Ombres',
    sagaOrder: 6,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Les Fiancés de l'Hiver",
    author: 'Christelle Dabos',
    coverUrl: '/books_pictures/gallimardj065376-2013.jpg',
    pages: 528,
    genre: ['Fantasy'],
    saga: 'La Passe-Miroir',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'Les Disparus du Clairdelune',
    author: 'Christelle Dabos',
    coverUrl: '/books_pictures/9782070661985_1_75.jpg',
    pages: 560,
    genre: ['Fantasy'],
    saga: 'La Passe-Miroir',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'La Mémoire de Babel',
    author: 'Christelle Dabos',
    coverUrl: '/books_pictures/unnamed.jpg',
    pages: 496,
    genre: ['Fantasy'],
    saga: 'La Passe-Miroir',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },
  {
    title: 'La Tempête des Echos',
    author: 'Christelle Dabos',
    coverUrl: '/books_pictures/La-Pae-miroir.jpg',
    pages: 576,
    genre: ['Fantasy'],
    saga: 'La Passe-Miroir',
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'France',
    selectDisplayOrder: 15,
  },

  {
    title: "L'Enfant de Poussière",
    author: 'Patrick K. Dewdney',
    coverUrl: '/books_pictures/41INjyFCoVL._SX195_.jpg',
    pages: 800,
    genre: ['Fantasy'],
    saga: 'Le Cycle de Syffe',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Peste et la Vigne',
    author: 'Patrick K. Dewdney',
    coverUrl: '/books_pictures/La-peste-et-la-vigne.jpg',
    pages: 720,
    genre: ['Fantasy'],
    saga: 'Le Cycle de Syffe',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Chiens et la Charrue',
    author: 'Patrick K. Dewdney',
    coverUrl: '/books_pictures/Les-chiens-et-la-charrue.jpg',
    pages: 784,
    genre: ['Fantasy'],
    saga: 'Le Cycle de Syffe',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Maison des Veilleurs',
    author: 'Patrick K. Dewdney',
    coverUrl: '/books_pictures/71Kz3M-hJAL._UF1000,1000_QL80_.jpg',
    pages: 656,
    genre: ['Fantasy'],
    saga: 'Le Cycle de Syffe',
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Le Fou et l'Assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290403303_1_75.jpg',
    pages: 384,
    genre: ['Fantasy'],
    saga: "Le Fou et l'Assassin",
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: "La Fille de l'Assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/La-fille-de-l-aain.jpg',
    pages: 384,
    genre: ['Fantasy'],
    saga: "Le Fou et l'Assassin",
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'En Quête de Vengeance',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290403341-475x500-1.webp',
    pages: 462,
    genre: ['Fantasy'],
    saga: "Le Fou et l'Assassin",
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: "Le Retour de l'Assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290403327-475x500-1.jpg',
    pages: 450,
    genre: ['Fantasy'],
    saga: "Le Fou et l'Assassin",
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: "Sur les Rives de l'Art",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/Sur-les-rives-de-l-Art.jpg',
    pages: 528,
    genre: ['Fantasy'],
    saga: "Le Fou et l'Assassin",
    sagaOrder: 5,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: "Le Destin de l'Assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/Le-destin-de-l-aain.jpg',
    pages: 672,
    genre: ['Fantasy'],
    saga: "Le Fou et l'Assassin",
    sagaOrder: 6,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 15,
  },
  {
    title: 'Les Jardins de la Lune',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/jardins-lune.jpg',
    pages: 1024,
    genre: ['Fantasy'],
    saga: 'Le Livre des Martyrs',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Portes de la Maison des Morts',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/portes-maison-morts.jpg',
    pages: 1344,
    genre: ['Fantasy'],
    saga: 'Le Livre des Martyrs',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Souvenirs de la Glace',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/souvenirs-glace.webp',
    pages: 1440,
    genre: ['Fantasy'],
    saga: 'Le Livre des Martyrs',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Maison des Chaînes',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/maison-chaines.jpg',
    pages: 1312,
    genre: ['Fantasy'],
    saga: 'Le Livre des Martyrs',
    sagaOrder: 4,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Marées de Minuit',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/marees-minuit.jpg',
    pages: 1184,
    genre: ['Fantasy'],
    saga: 'Le Livre des Martyrs',
    sagaOrder: 5,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Osseleurs',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/osseleurs.jpg',
    pages: 1408,
    genre: ['Fantasy'],
    saga: 'Le Livre des Martyrs',
    sagaOrder: 6,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'Canada',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Souffle du Moissonneur',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/souffle-moissonneur.jpg',
    pages: 1440,
    genre: ['Fantasy'],
    saga: 'Le Livre des Martyrs',
    sagaOrder: 7,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'Canada',
    selectDisplayOrder: 0,
  },
  {
    title: "Le royaume de Pierre d'Angle, tome 1 : L'art du naufrage",
    author: 'Mark Lawrence',
    coverUrl: '/books_pictures/9782072999123-475x500-1.webp',
    pages: 416,
    genre: ['Fantasy'],
    saga: "Le royaume de Pierre d'Angle",
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Compagnie Noire',
    author: 'Glen Cook',
    coverUrl:
      '/books_pictures/les_annales_de_la_compagnie_noire_tome_1_la_compagnie_noire-727468-264-432.jpg',
    pages: 379,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Château Noir',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/chateau-noir.jpg',
    pages: 413,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Rose Blanche',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/rose-blanche.jpg',
    pages: 445,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Jeux d'Ombres",
    author: 'Glen Cook',
    coverUrl:
      '/books_pictures/les_annales_de_la_compagnie_noire_tome_4_jeux_dombres-1006907-264-432.jpg',
    pages: 377,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 4,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Rêves d'Acier",
    author: 'Glen Cook',
    coverUrl:
      '/books_pictures/les_annales_de_la_compagnie_noire_tome_5_reves_dacier-1006909-264-432.jpg',
    pages: 411,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 5,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "La Pointe d'Argent",
    author: 'Glen Cook',
    coverUrl: '/books_pictures/compagnie-noire-6-pointe-argent.jpg',
    pages: 411,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 6,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Saisons Funestes',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/compagnie-noire-7-saisons-funestes.jpg',
    pages: 410,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 7,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Elle est les Ténèbres - Part. 1',
    author: 'Glen Cook',
    coverUrl:
      '/books_pictures/les_annales_de_la_compagnie_noire_tome_8_elle_est_les_tenebres_i-1006897-264-432.jpg',
    pages: 315,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 8,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Elle est les Ténèbres - Part. 2',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/compagnie-noire-9-elle-tenebres-2.jpg',
    pages: 412,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 9,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Eau Dort - Part. 1",
    author: 'Glen Cook',
    coverUrl: '/books_pictures/eau-dort-1.jpg',
    pages: 314,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 10,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Eau Dort - Part. 2",
    author: 'Glen Cook',
    coverUrl: '/books_pictures/eau-dort-2.jpg',
    pages: 319,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 11,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Soldats de Pierre - Part. 1',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/soldats-pierre-1.jpg',
    pages: 379,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 12,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Soldats de Pierre - Part. 2',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/soldats-pierre-2.jpg',
    pages: 379,
    genre: ['Fantasy'],
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 13,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },

  {
    title: 'Les annales du Disque-Monde, tome 1 : La huitième couleur',
    author: 'Terry Pratchett',
    coverUrl: '/books_pictures/9782266211819_1_75.jpg',
    pages: 288,
    genre: ['Fantasy'],
    saga: 'Les annales du Disque-Monde',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Voie des Rois (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/81pXYzQn+8L.jpg',
    pages: 768,
    genre: ['Fantasy'],
    saga: 'Les Archives de Roshar',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Voie des Rois (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/9782253191247_1_75.jpg',
    pages: 799,
    genre: ['Fantasy'],
    saga: 'Les Archives de Roshar',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le livre des Radieux (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/81EE84gozJL._AC_UF1000,1000_QL80_.jpg',
    pages: 896,
    genre: ['Fantasy'],
    saga: 'Les Archives de Roshar',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Livre des Radieux (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/livre-radieux-2.jpg',
    pages: 774,
    genre: ['Fantasy'],
    saga: 'Les Archives de Roshar',
    sagaOrder: 4,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Justicière (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/813UwoQCTXL.jpg',
    pages: 864,
    genre: ['Fantasy'],
    saga: 'Les Archives de Roshar',
    sagaOrder: 5,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Justicière (2/2)',
    author: 'Brandon Sanderson',
    coverUrl:
      '/books_pictures/justiciere-brandon-sanderson-les-archives-de-roshar-tome-3-partie-2.jpg',
    pages: 864,
    genre: ['Fantasy'],
    saga: 'Les Archives de Roshar',
    sagaOrder: 6,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Rythme de Guerre (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/81slChiIC6L.jpg',
    pages: 736,
    genre: ['Fantasy'],
    saga: 'Les Archives de Roshar',
    sagaOrder: 7,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Eclat de l'Aube",
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/eclat-aube.jpg',
    pages: 320,
    genre: ['Fantasy'],
    saga: 'Les Archives de Roshar',
    sagaOrder: 8.5,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Rythme de Guerre (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/1_metadata-image-51642058.jpeg',
    pages: 832,
    genre: ['Fantasy'],
    saga: 'Les Archives de Roshar',
    sagaOrder: 8,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Feu de la Sorcière',
    author: 'James Clemens',
    coverUrl: '/books_pictures/feu-sorciere.jpg',
    pages: 581,
    genre: ['Fantasy'],
    saga: 'Les Bannis et les Proscrits',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Foudres de la Sorcière',
    author: 'James Clemens',
    coverUrl: '/books_pictures/foudres-sorciere.jpg',
    pages: 632,
    genre: ['Fantasy'],
    saga: 'Les Bannis et les Proscrits',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Guerre de la Sorcière',
    author: 'James Clemens',
    coverUrl: '/books_pictures/guerre-sorciere.jpg',
    pages: 794,
    genre: ['Fantasy'],
    saga: 'Les Bannis et les Proscrits',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Portail de la Sorcière',
    author: 'James Clemens',
    coverUrl: '/books_pictures/portail-sorciere.jpg',
    pages: 595,
    genre: ['Fantasy'],
    saga: 'Les Bannis et les Proscrits',
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Etoile de la Sorcière",
    author: 'James Clemens',
    coverUrl: '/books_pictures/etoile-sorciere.jpg',
    pages: 600,
    genre: ['Fantasy'],
    saga: 'Les Bannis et les Proscrits',
    sagaOrder: 5,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },

  {
    title: 'La Sorcière Captive',
    author: 'Melissa Caruso',
    coverUrl: '/books_pictures/81xvgxW2aXL._AC_UF1000,1000_QL80_.jpg',
    pages: 576,
    genre: ['Fantasy'],
    saga: 'Les Faucons de Raverra',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Héritière Rebelle",
    author: 'Melissa Caruso',
    coverUrl: '/books_pictures/81ayZbT8cVL.jpg',
    pages: 736,
    genre: ['Fantasy'],
    saga: 'Les Faucons de Raverra',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Empire Libéré",
    author: 'Melissa Caruso',
    coverUrl: '/books_pictures/81F4mKgR4iL._AC_UF1000,1000_QL80_.jpg',
    pages: 704,
    genre: ['Fantasy'],
    saga: 'Les Faucons de Raverra',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Maîtres Enlumineurs',
    author: 'Robert Jackson Bennett',
    coverUrl:
      '/books_pictures/les_maitres_enlumineurs_tome_1-1482893-264-432.jpg',
    pages: 768,
    genre: ['Fantasy'],
    saga: 'Les Maîtres Enlumineurs',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Retour du Hiérophante',
    author: 'Robert Jackson Bennett',
    coverUrl: '/books_pictures/retour-hierophante.jpg',
    pages: 736,
    genre: ['Fantasy'],
    saga: 'Les Maîtres Enlumineurs',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Terres Closes',
    author: 'Robert Jackson Bennett',
    coverUrl: '/books_pictures/terres-closes.jpg',
    pages: 832,
    genre: ['Fantasy'],
    saga: 'Les Maîtres Enlumineurs',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "Les Princes d'Ambre - Cycle 1",
    author: 'Roger Zelazny',
    coverUrl: '/books_pictures/81q5MDrRD5L._AC_UF1000,1000_QL80_.jpg',
    pages: 640,
    genre: ['Fantasy'],
    saga: "Les Princes d'Ambre",
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Palais Adamantin',
    author: 'Stephen Deas',
    coverUrl:
      '/books_pictures/les_rois_dragons_tome_1_le_palais_adamantin-151096-264-432.jpg',
    pages: 320,
    genre: ['Fantasy'],
    saga: 'Les Rois-Dragons',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Roi des Cimes',
    author: 'Stephen Deas',
    coverUrl: '/books_pictures/roi-cimes.jpg',
    pages: 480,
    genre: ['Fantasy'],
    saga: 'Les Rois-Dragons',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Ordre des Ecailleux",
    author: 'Stephen Deas',
    coverUrl: '/books_pictures/ordre-ecailleux.webp',
    pages: 448,
    genre: ['Fantasy'],
    saga: 'Les Rois-Dragons',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'Royaume-Uni',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Mensonges de Locke Lamora',
    author: 'Scott Lynch',
    coverUrl: '/books_pictures/images.jpg',
    pages: 608,
    genre: ['Fantasy'],
    saga: 'Les Salauds Gentilshommes',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Des Horizons Rouge Sang',
    author: 'Scott Lynch',
    coverUrl: '/books_pictures/817mO9uCDEL._UF1000,1000_QL80_.jpg',
    pages: 639,
    genre: ['Fantasy'],
    saga: 'Les Salauds Gentilshommes',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'La République des Voleurs',
    author: 'Scott Lynch',
    coverUrl: '/books_pictures/9791028117948_1_75.jpg',
    pages: 672,
    genre: ['Fantasy'],
    saga: 'Les Salauds Gentilshommes',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "N'oublie Jamais",
    author: 'Jay Kristoff',
    coverUrl: '/books_pictures/n-oublie-jamais.jpg',
    pages: 768,
    genre: ['Fantasy'],
    saga: 'Nevernight',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Grands Jeux',
    author: 'Jay Kristoff',
    coverUrl: '/books_pictures/grands-jeux-kristoff.jpg',
    pages: 800,
    genre: ['Fantasy'],
    saga: 'Nevernight',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Aube Obscure",
    author: 'Jay Kristoff',
    coverUrl: '/books_pictures/aube-obscure.jpg',
    pages: 800,
    genre: ['Fantasy'],
    saga: 'Nevernight',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Tuer la Reine',
    author: 'Jennifer Estep',
    coverUrl: '/books_pictures/71lmtW2SGuL._AC_UF1000,1000_QL80_.jpg',
    pages: 465,
    genre: ['Fantasy'],
    saga: "Une Couronne d'Epines",
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Défendre le Prince',
    author: 'Jennifer Estep',
    coverUrl: '/books_pictures/81hqx4l8WSL._UF1000,1000_QL80_.jpg',
    pages: 464,
    genre: ['Fantasy'],
    saga: "Une Couronne d'Epines",
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Écraser le roi',
    author: 'Jennifer Estep',
    coverUrl: '/books_pictures/81mj9OqmjiL.jpg',
    pages: 470,
    genre: ['Fantasy'],
    saga: "Une Couronne d'Epines",
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: "L'Alliage de la Justice",
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/libriweb.jpg',
    pages: 456,
    genre: ['Fantasy'],
    saga: 'Wax et Wayne',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Jeux de Masques',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/71xSe0x62eL._UF1000,1000_QL80_.jpg',
    pages: 576,
    genre: ['Fantasy'],
    saga: 'Wax et Wayne',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Les Bracelets des Larmes',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/71mv6VCdFbL.jpg',
    pages: 800,
    genre: ['Fantasy'],
    saga: 'Wax et Wayne',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Métal Perdu',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/metal-perdu.jpg',
    pages: 704,
    genre: [],
    saga: 'Wax et Wayne',
    sagaOrder: 4,
    sagaFinished: true,
    releaseDate: '',
    description: '',
    countryOrigin: 'États-Unis',
    selectDisplayOrder: 0,
  },
  {
    title: 'Rougemuraille tome 1',
    author: 'Brian Jacques',
    coverUrl: '/books_pictures/f90c6d64a331.jpg',
    pages: 504,
    genre: [],
    saga: 'Rougemuraille',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Rougemuraille tome 2',
    author: 'Brian Jacques',
    coverUrl: '/books_pictures/bd2f6455ed7a.jpg',
    pages: 525,
    genre: [],
    saga: 'Rougemuraille',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Rougemuraille tome 3',
    author: 'Brian Jacques',
    coverUrl: '/books_pictures/68a23d659360.jpg',
    pages: 488,
    genre: [],
    saga: 'Rougemuraille',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Rougemuraille tome 4',
    author: 'Brian Jacques',
    coverUrl: '/books_pictures/29eed076a224.jpg',
    pages: 500,
    genre: [],
    saga: 'Rougemuraille',
    sagaOrder: 4,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Rougemuraille tome 5',
    author: 'Brian Jacques',
    coverUrl: '/books_pictures/54b942885f77.jpg',
    pages: 328,
    genre: [],
    saga: 'Rougemuraille',
    sagaOrder: 5,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Rougemuraille tome 6',
    author: 'Brian Jacques',
    coverUrl: '/books_pictures/baea228eed55.jpg',
    pages: 429,
    genre: [],
    saga: 'Rougemuraille',
    sagaOrder: 6,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le royaume de Tobin, tome 1',
    author: 'Lynn Flewelling',
    coverUrl:
      '/books_pictures/le-royaume-de-tobin-tome-1-les-jumeaux-264751.jpg',
    pages: 336,
    genre: [],
    saga: 'Le royaume de Tobin',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le royaume de Tobin, tome 2',
    author: 'Lynn Flewelling',
    coverUrl: '/books_pictures/6f2b417a45dd.jpg',
    pages: 304,
    genre: [],
    saga: 'Le royaume de Tobin',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le royaume de Tobin, tome 3',
    author: 'Lynn Flewelling',
    coverUrl: '/books_pictures/cbc32a6a324f.jpg',
    pages: 352,
    genre: [],
    saga: 'Le royaume de Tobin',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le royaume de Tobin, tome 4',
    author: 'Lynn Flewelling',
    coverUrl: '/books_pictures/aff3033d3507.webp',
    pages: 384,
    genre: [],
    saga: 'Le royaume de Tobin',
    sagaOrder: 4,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le royaume de Tobin, tome 5',
    author: 'Lynn Flewelling',
    coverUrl: '/books_pictures/a6a99e267f4c.jpg',
    pages: 400,
    genre: [],
    saga: 'Le royaume de Tobin',
    sagaOrder: 5,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le royaume de Tobin, tome 6',
    author: 'Lynn Flewelling',
    coverUrl: '/books_pictures/01996604-8de6-7ce3-906c-5835bb310fb7.jpg',
    pages: 416,
    genre: [],
    saga: 'Le royaume de Tobin',
    sagaOrder: 6,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La couronne des 7 royaumes, tome 1',
    author: 'David B. Coe',
    coverUrl: '/books_pictures/eeb54ba64188.jpg',
    pages: 624,
    genre: [],
    saga: 'La couronne des 7 royaumes',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La couronne des 7 royaumes, tome 2',
    author: 'David B. Coe',
    coverUrl: '/books_pictures/30fc54eff0de.jpg',
    pages: 624,
    genre: [],
    saga: 'La couronne des 7 royaumes',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La couronne des 7 royaumes, tome 3',
    author: 'David B. Coe',
    coverUrl: '/books_pictures/5e195f6d9cb7.jpg',
    pages: 640,
    genre: [],
    saga: 'La couronne des 7 royaumes',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La couronne des 7 royaumes, tome 4',
    author: 'David B. Coe',
    coverUrl: '/books_pictures/df646beb01c1.jpg',
    pages: 608,
    genre: [],
    saga: 'La couronne des 7 royaumes',
    sagaOrder: 4,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La couronne des 7 royaumes, tome 5',
    author: 'David B. Coe',
    coverUrl: '/books_pictures/319e1dd77ca5.webp',
    pages: 624,
    genre: [],
    saga: 'La couronne des 7 royaumes',
    sagaOrder: 5,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La couronne des 7 royaumes, tome 6',
    author: 'David B. Coe',
    coverUrl: '/books_pictures/ad1e4b0385f4.jpg',
    pages: 640,
    genre: [],
    saga: 'La couronne des 7 royaumes',
    sagaOrder: 6,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La couronne des 7 royaumes, tome 7',
    author: 'David B. Coe',
    coverUrl: '/books_pictures/24e7ba64a30a.jpg',
    pages: 608,
    genre: [],
    saga: 'La couronne des 7 royaumes',
    sagaOrder: 7,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La couronne des 7 royaumes, tome 8',
    author: 'David B. Coe',
    coverUrl: '/books_pictures/75d9c6594228.jpg',
    pages: 640,
    genre: [],
    saga: 'La couronne des 7 royaumes',
    sagaOrder: 8,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La couronne des 7 royaumes, tome 9',
    author: 'David B. Coe',
    coverUrl: '/books_pictures/3b4e6412aa34.jpg',
    pages: 608,
    genre: [],
    saga: 'La couronne des 7 royaumes',
    sagaOrder: 9,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La couronne des 7 royaumes, tome 10',
    author: 'David B. Coe',
    coverUrl: '/books_pictures/062eea802be4.jpg',
    pages: 640,
    genre: [],
    saga: 'La couronne des 7 royaumes',
    sagaOrder: 10,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le clan des otoris, tome 1',
    author: 'Lian Hearn',
    coverUrl: '/books_pictures/45a36a2432f3.jpg',
    pages: 370,
    genre: [],
    saga: 'Le clan des Otori',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le clan des otoris, tome 2',
    author: 'Lian Hearn',
    coverUrl: '/books_pictures/d706218f2d20.jpg',
    pages: 384,
    genre: [],
    saga: 'Le clan des Otori',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le clan des otoris, tome 3',
    author: 'Lian Hearn',
    coverUrl: '/books_pictures/ef740664920a.jpg',
    pages: 416,
    genre: [],
    saga: 'Le clan des Otori',
    sagaOrder: 3,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Chroniques des temps Obscurs, tome 1',
    author: 'Michelle Paver',
    coverUrl: '/books_pictures/7e17bc306444.jpg',
    pages: 256,
    genre: [],
    saga: 'Chroniques des temps Obscurs',
    sagaOrder: 1,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'Chroniques des temps Obscurs, tome 2',
    author: 'Michelle Paver',
    coverUrl: '/books_pictures/f1559ec7749d.jpg',
    pages: 288,
    genre: [],
    saga: 'Chroniques des temps Obscurs',
    sagaOrder: 2,
    sagaFinished: false,
    releaseDate: '',
    description: '',
    countryOrigin: '',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Guilde des Magiciens',
    author: 'Trudi Canavan',
    coverUrl: '/books_pictures/4245b1e53e50.jpg',
    pages: 392,
    genre: [],
    saga: 'La Trilogie du Magicien Noir',
    sagaOrder: 1,
    sagaFinished: true,
    releaseDate: '2001-10-24',
    description: '',
    countryOrigin: 'Australie',
    selectDisplayOrder: 0,
  },
  {
    title: 'La Novice',
    author: 'Trudi Canavan',
    coverUrl: '/books_pictures/37d8b7bcc956.jpg',
    pages: 507,
    genre: [],
    saga: 'La Trilogie du Magicien Noir',
    sagaOrder: 2,
    sagaFinished: true,
    releaseDate: '2008-06-11',
    description: '',
    countryOrigin: 'Australie',
    selectDisplayOrder: 0,
  },
  {
    title: 'Le Haut Seigneur',
    author: 'Trudi Canavan',
    coverUrl: '/books_pictures/c06306d5411d.jpg',
    pages: 591,
    genre: [],
    saga: 'La Trilogie du Magicien Noir',
    sagaOrder: 3,
    sagaFinished: true,
    releaseDate: '2008-05-22',
    description: '',
    countryOrigin: 'Australie',
    selectDisplayOrder: 0,
  },
];
