import { UserMovie } from '../../../../models/movie-model';

export const ronanCinemaMovies: UserMovie[] = [
  {
    title: 'Mickey 17',
    director: 'Bong Joon-ho',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2025-01-31',
    lastViewedDate: '2025-01-31',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Le Comte de Monte-Cristo',
    director: 'Alexandre de La Patellière, Matthieu Delaporte',
    rating: 5,
    timesWatched: 3,
    firstViewedDate: '2024-06-28',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Challengers',
    director: 'Luca Guadagnino',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2024-04-26',
    lastViewedDate: '2024-04-26',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Gran Turismo',
    director: 'Neill Blomkamp',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '2023-08-25',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Oppenheimer',
    director: 'Christopher Nolan',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2023-07-21',
    lastViewedDate: '2023-07-21',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Barbie',
    director: 'Greta Gerwig',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2023-07-21',
    lastViewedDate: '2023-07-21',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Creed III',
    director: 'Michael B. Jordan',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2023-03-03',
    lastViewedDate: '2023-03-03',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Babylon',
    director: 'Damien Chazelle',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2022-12-23',
    lastViewedDate: '2022-12-23',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Bullet Train',
    director: 'David Leitch',
    rating: 4,
    timesWatched: 2,
    firstViewedDate: '2022-08-05',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Everything Everywhere All at Once',
    director: 'Daniel Kwan, Daniel Scheinert',
    rating: 4.5,
    timesWatched: 1,
    firstViewedDate: '2022-03-25',
    lastViewedDate: '2022-03-25',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Free Guy',
    director: 'Shawn Levy',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2021-08-13',
    lastViewedDate: '2021-08-13',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Thunderbolts',
    director: 'Jake Schreier',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-05-02',
    lastViewedDate: '2025-05-02',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Tenet',
    director: 'Christopher Nolan',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '2020-09-03',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Joker',
    director: 'Todd Phillips',
    rating: 4,
    timesWatched: 2,
    firstViewedDate: '2019-10-04',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Aladdin',
    director: 'Guy Ritchie',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2019-05-24',
    lastViewedDate: '2019-05-24',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Alita: Battle Angel',
    director: 'Robert Rodriguez',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '2019-02-14',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'A Star Is Born',
    director: 'Bradley Cooper',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2018-10-05',
    lastViewedDate: '2018-10-05',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Ready Player One',
    director: 'Steven Spielberg',
    rating: 5,
    timesWatched: 5,
    firstViewedDate: '2018-03-29',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Astérix & Obélix : Mission Cléopâtre',
    director: 'Alain Chabat',
    rating: 5,
    timesWatched: 20,
    firstViewedDate: '2002-01-30',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Kingsman: The Golden Circle',
    director: 'Matthew Vaughn',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '2017-09-22',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "The Hitman's Bodyguard",
    director: 'Patrick Hughes',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '2017-08-18',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "Comment c'est loin",
    director: 'Orelsan',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '2015-12-09',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Creed',
    director: 'Ryan Coogler',
    rating: 4,
    timesWatched: 10,
    firstViewedDate: '2015-11-25',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'The Visit',
    director: 'M. Night Shyamalan',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2015-09-11',
    lastViewedDate: '2015-09-11',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Pixels',
    director: 'Chris Columbus',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2015-07-24',
    lastViewedDate: '2015-07-24',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Interstellar',
    director: 'Christopher Nolan',
    rating: 5,
    timesWatched: 5,
    firstViewedDate: '2014-11-07',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Birdman',
    director: 'Alejandro G. Iñárritu',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '2014-10-17',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Lucy',
    director: 'Luc Besson',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2014-07-25',
    lastViewedDate: '2014-07-25',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Elysium',
    director: 'Neill Blomkamp',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2013-08-09',
    lastViewedDate: '2013-08-09',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Pacific Rim',
    director: 'Guillermo del Toro',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '2013-07-12',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Yes Man',
    director: 'Peyton Reed',
    rating: 4,
    timesWatched: 10,
    firstViewedDate: '2008-12-19',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Drive',
    director: 'Nicolas Winding Refn',
    rating: 2.5,
    timesWatched: 2,
    firstViewedDate: '2011-09-16',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },

  {
    title: 'Avengers: Infinity War',
    director: 'Anthony Russo, Joe Russo',
    rating: 4,
    timesWatched: 15,
    firstViewedDate: '2018-04-27',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Avengers: Endgame',
    director: 'Anthony Russo, Joe Russo',
    rating: 4,
    timesWatched: 15,
    firstViewedDate: '2019-04-26',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Captain America: Brave New World',
    director: 'Julius Onah',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-02-14',
    lastViewedDate: '2025-02-14',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Iron Man 3',
    director: 'Shane Black',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '2013-05-03',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Thor',
    director: 'Kenneth Branagh',
    rating: 3.5,
    timesWatched: 6,
    firstViewedDate: '2011-05-06',
    lastViewedDate: '2026-01-20',
    seenAtCinema: false,
    owned: true,
  },
  {
    title: 'Thor: The Dark World',
    director: 'Alan Taylor',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '2013-11-08',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Thor: Ragnarok',
    director: 'Taika Waititi',
    rating: 2,
    timesWatched: 3,
    firstViewedDate: '2017-11-03',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Captain Marvel',
    director: 'Anna Boden, Ryan Fleck',
    rating: 2,
    timesWatched: 2,
    firstViewedDate: '2019-03-08',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Shang-Chi et la Légende des Dix Anneaux',
    director: 'Destin Daniel Cretton',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '2021-09-03',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Doctor Strange',
    director: 'Scott Derrickson',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '2016-11-04',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Black Panther',
    director: 'Ryan Coogler',
    rating: 3.5,
    timesWatched: 5,
    firstViewedDate: '2018-02-16',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Ant-Man',
    director: 'Peyton Reed',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '2015-07-17',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Spider-Man: Homecoming',
    director: 'Jon Watts',
    rating: 2.5,
    timesWatched: 5,
    firstViewedDate: '2017-07-07',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Spider-Man: Far From Home',
    director: 'Jon Watts',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '2019-07-02',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Black Widow',
    director: 'Cate Shortland',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2021-07-09',
    lastViewedDate: '2021-07-09',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Deadpool et Wolverine',
    director: 'Shawn Levy',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2024-07-26',
    lastViewedDate: '2024-07-26',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Green Lantern',
    director: 'Martin Campbell',
    rating: 2.5,
    timesWatched: 5,
    firstViewedDate: '2011-06-17',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'The Dark Knight Rises',
    director: 'Christopher Nolan',
    rating: 5,
    timesWatched: 5,
    firstViewedDate: '2012-07-20',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'The Batman',
    director: 'Matt Reeves',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '2022-03-04',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Shazam!',
    director: 'David F. Sandberg',
    rating: 2,
    timesWatched: 2,
    firstViewedDate: '2019-04-05',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Aquaman',
    director: 'James Wan',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '2018-12-21',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Black Adam',
    director: 'Jaume Collet-Serra',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2022-10-21',
    lastViewedDate: '2022-10-21',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Suicide Squad',
    director: 'David Ayer',
    rating: 2,
    timesWatched: 3,
    firstViewedDate: '2016-08-05',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Man of Steel',
    director: 'Zack Snyder',
    rating: 5,
    timesWatched: 10,
    firstViewedDate: '2013-06-14',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Superman',
    director: 'James Gunn',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2025-07-11',
    lastViewedDate: '2025-07-11',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Wonder Woman',
    director: 'Patty Jenkins',
    rating: 4,
    timesWatched: 5,
    firstViewedDate: '2017-06-02',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'The Flash',
    director: 'Andy Muschietti',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2023-06-16',
    lastViewedDate: '2023-06-16',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Birds of Prey',
    director: 'Cathy Yan',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2020-02-07',
    lastViewedDate: '2020-02-07',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Deadpool',
    director: 'Tim Miller',
    rating: 4,
    timesWatched: 5,
    firstViewedDate: '2016-02-12',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Deadpool 2',
    director: 'David Leitch',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '2018-05-18',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'The Wolverine',
    director: 'James Mangold',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '2013-07-26',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Logan',
    director: 'James Mangold',
    rating: 4,
    timesWatched: 5,
    firstViewedDate: '2017-03-03',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'X-Men : Days of Future Past',
    director: 'Bryan Singer',
    rating: 2.5,
    timesWatched: 5,
    firstViewedDate: '2014-05-23',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Venom',
    director: 'Ruben Fleischer',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2018-10-05',
    lastViewedDate: '2018-10-05',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Spider-Man 2',
    director: 'Sam Raimi',
    rating: 4.5,
    timesWatched: 15,
    firstViewedDate: '2004-06-30',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Spider-Man 3',
    director: 'Sam Raimi',
    rating: 4,
    timesWatched: 15,
    firstViewedDate: '2007-05-04',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'The Amazing Spider-Man',
    director: 'Marc Webb',
    rating: 3,
    timesWatched: 10,
    firstViewedDate: '2012-07-03',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Kick-Ass 2',
    director: 'Jeff Wadlow',
    rating: 4,
    timesWatched: 5,
    firstViewedDate: '2013-08-16',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Ghost Rider',
    director: 'Mark Steven Johnson',
    rating: 2,
    timesWatched: 10,
    firstViewedDate: '2007-02-16',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'La La Land',
    director: 'Damien Chazelle',
    rating: 5,
    timesWatched: 10,
    firstViewedDate: '2016-12-09',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Dragons 2',
    director: 'Dean DeBlois',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '2014-06-13',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Spider-Man: Into the Spider-Verse',
    director: 'Bob Persichetti, Peter Ramsey, Rodney Rothman',
    rating: 5,
    timesWatched: 10,
    firstViewedDate: '2018-12-14',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Vaiana',
    director: 'Ron Clements, John Musker',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '2016-11-23',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Vice-Versa',
    director: 'Pete Docter',
    rating: 4,
    timesWatched: 2,
    firstViewedDate: '2015-06-19',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Arthur et les Minimoys',
    director: 'Luc Besson',
    rating: 3.5,
    timesWatched: 10,
    firstViewedDate: '2006-12-13',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Les Indestructibles 2',
    director: 'Brad Bird',
    rating: 4,
    timesWatched: 2,
    firstViewedDate: '2018-06-15',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Toy Story 3',
    director: 'Lee Unkrich',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '2010-06-18',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Megamind',
    director: 'Tom McGrath',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '2010-11-05',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Solo: A Star Wars Story',
    director: 'Ron Howard',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '2018-05-25',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Fast & Furious 6',
    director: 'Justin Lin',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '2013-05-24',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Fast & Furious Presents: Hobbs & Shaw',
    director: 'David Leitch',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2019-08-02',
    lastViewedDate: '2019-08-02',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Terminator Genisys',
    director: 'Alan Taylor',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2015-07-01',
    lastViewedDate: '2015-07-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Dune',
    director: 'Denis Villeneuve',
    rating: 4,
    timesWatched: 2,
    firstViewedDate: '2021-10-22',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Jack Reacher',
    director: 'Christopher McQuarrie',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2012-12-21',
    lastViewedDate: '2012-12-21',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Glass',
    director: 'M. Night Shyamalan',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2019-01-18',
    lastViewedDate: '2019-01-18',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Creed II',
    director: 'Steven Caple Jr.',
    rating: 5,
    timesWatched: 10,
    firstViewedDate: '2018-11-21',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Taken 2',
    director: 'Olivier Megaton',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '2012-10-05',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Taken 3',
    director: 'Olivier Megaton',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2015-01-09',
    lastViewedDate: '2015-01-09',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Transformers',
    director: 'Michael Bay',
    rating: 3.5,
    timesWatched: 15,
    firstViewedDate: '2007-07-03',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'RED',
    director: 'Robert Schwentke',
    rating: 3.5,
    timesWatched: 3,
    firstViewedDate: '2010-10-15',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'RED 2',
    director: 'Dean Parisot',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '2013-07-19',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: "Ocean's Eight",
    director: 'Gary Ross',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '2018-06-08',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Avatar',
    director: 'James Cameron',
    rating: 4,
    timesWatched: 5,
    firstViewedDate: '2009-12-18',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Wonka',
    director: 'Paul King',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2023-12-15',
    lastViewedDate: '2023-12-15',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "Donjons & Dragons : L'Honneur des voleurs",
    director: 'John Francis Daley, Jonathan Goldstein',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2023-03-31',
    lastViewedDate: '2023-03-31',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Elvis',
    director: 'Baz Luhrmann',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2022-06-24',
    lastViewedDate: '2022-06-24',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Cruella',
    director: 'Craig Gillespie',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2021-05-28',
    lastViewedDate: '2021-05-28',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: '1917',
    director: 'Sam Mendes',
    rating: 4.5,
    timesWatched: 1,
    firstViewedDate: '2019-12-25',
    lastViewedDate: '2019-12-25',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Jurassic World: Fallen Kingdom',
    director: 'J.A. Bayona',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2018-06-22',
    lastViewedDate: '2018-06-22',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Tomb Raider',
    director: 'Roar Uthaug',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '2018-03-16',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'The Greatest Showman',
    director: 'Michael Gracey',
    rating: 3.5,
    timesWatched: 5,
    firstViewedDate: '2017-12-20',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Warcraft',
    director: 'Duncan Jones',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '2016-06-10',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Zootopie',
    director: 'Byron Howard, Rich Moore',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '2016-03-04',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Jurassic World',
    director: 'Colin Trevorrow',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2015-06-12',
    lastViewedDate: '2015-06-12',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Titanic',
    director: 'James Cameron',
    rating: 5,
    timesWatched: 10,
    firstViewedDate: '1997-12-19',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Avatar : De feu et de cendres',
    director: 'James Cameron',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2025-12-17',
    lastViewedDate: '2025-12-17',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Zootopie 2',
    director: 'Jared Bush, Byron Howard',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2025-11-26',
    lastViewedDate: '2025-11-26',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Wicked: For Good',
    director: 'Jon M. Chu',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-11-19',
    lastViewedDate: '2025-11-19',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Running Man',
    director: 'Edgar Wright',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2025-11-19',
    lastViewedDate: '2025-11-19',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Insaisissables 3',
    director: 'Ruben Fleischer',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2025-11-12',
    lastViewedDate: '2025-11-12',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'TRON : Ares',
    director: 'Joachim Rønning',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2025-10-08',
    lastViewedDate: '2025-10-08',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'A Big Bold Beautiful Journey',
    director: 'Kogonada',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2025-10-01',
    lastViewedDate: '2025-10-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'One Battle After Another',
    director: 'Paul Thomas Anderson',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2025-01-01',
    lastViewedDate: '2025-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: "Conjuring : L'Heure du jugement",
    director: 'Michael Chaves',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2025-09-10',
    lastViewedDate: '2025-09-10',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Smashing Machine',
    director: 'Benny Safdie',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-10-29',
    lastViewedDate: '2025-10-29',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Jay Kelly',
    director: 'Noah Baumbach',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2025-01-01',
    lastViewedDate: '2025-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Adieu Jean-Pat',
    director: 'Cécilia Rouaud',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2025-09-03',
    lastViewedDate: '2025-09-03',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Pris au piège',
    director: 'Darren Aronofsky',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-08-27',
    lastViewedDate: '2025-08-27',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Évanouis',
    director: 'Zach Cregger',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-08-06',
    lastViewedDate: '2025-08-06',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Jurassic World : Renaissance',
    director: 'Gareth Edwards',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-07-04',
    lastViewedDate: '2025-07-04',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'F1',
    director: 'Joseph Kosinski',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-01-01',
    lastViewedDate: '2025-01-01',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Dragons',
    director: 'Dean DeBlois',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2025-06-11',
    lastViewedDate: '2025-06-11',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Le Son des souvenirs',
    director: 'Oliver Hermanus',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-02-25',
    lastViewedDate: '2025-02-25',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: "The Party's Over!",
    director: 'Antony Cordier',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2025-01-01',
    lastViewedDate: '2025-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Highest 2 Lowest',
    director: 'Spike Lee',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-01-01',
    lastViewedDate: '2025-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Alpha',
    director: 'Julia Ducournau',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-01-01',
    lastViewedDate: '2025-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'The Phoenician Scheme',
    director: 'Wes Anderson',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2025-01-01',
    lastViewedDate: '2025-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Exit 8',
    director: 'Genki Kawamura',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2025-01-01',
    lastViewedDate: '2025-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Eddington',
    director: 'Ari Aster',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2025-01-01',
    lastViewedDate: '2025-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Partir un jour',
    director: 'Amélie Bonnin',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-05-14',
    lastViewedDate: '2025-05-14',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Karate Kid: Legends',
    director: 'Jonathan Entwistle',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2025-01-01',
    lastViewedDate: '2025-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Mission: Impossible – The Final Reckoning',
    director: 'Christopher McQuarrie',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-05-21',
    lastViewedDate: '2025-05-21',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Last Bullet',
    director: 'Guillaume Pierret',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-01-01',
    lastViewedDate: '2025-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Train Dreams',
    director: 'Clint Bentley',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2025-11-07',
    lastViewedDate: '2025-11-07',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Un parfait inconnu',
    director: 'James Mangold',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2025-01-29',
    lastViewedDate: '2025-01-29',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'The Lord of the Rings: The War of the Rohirrim',
    director: 'Kenji Kamiyama',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2024-01-01',
    lastViewedDate: '2024-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Vaiana 2',
    director: 'David G. Derrick Jr., Jason Hand, Dana Ledoux Miller',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-11-27',
    lastViewedDate: '2024-11-27',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Nosferatu',
    director: 'Robert Eggers',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2024-12-25',
    lastViewedDate: '2024-12-25',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Juré n°2',
    director: 'Clint Eastwood',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-10-30',
    lastViewedDate: '2024-10-30',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Loups-Garous',
    director: 'François Uzan',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2024-10-23',
    lastViewedDate: '2024-10-23',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Caddo Lake',
    director: 'Celine Held, Logan George',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2024-01-01',
    lastViewedDate: '2024-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Heretic',
    director: 'Scott Beck, Bryan Woods',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2024-01-01',
    lastViewedDate: '2024-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Life of Chuck',
    director: 'Mike Flanagan',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-06-11',
    lastViewedDate: '2025-06-11',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'We Live in Time',
    director: 'John Crowley',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2024-01-01',
    lastViewedDate: '2024-01-01',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Joker : Folie à Deux',
    director: 'Todd Phillips',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2024-10-02',
    lastViewedDate: '2024-10-02',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Beetlejuice Beetlejuice',
    director: 'Tim Burton',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-09-11',
    lastViewedDate: '2024-09-11',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Trap',
    director: 'M. Night Shyamalan',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2024-01-01',
    lastViewedDate: '2024-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Twisters',
    director: 'Lee Isaac Chung',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2024-07-17',
    lastViewedDate: '2024-07-17',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Fly Me to the Moon',
    director: 'Greg Berlanti',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-01-01',
    lastViewedDate: '2024-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Kingdom of the Planet of the Apes',
    director: 'Wes Ball',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-01-01',
    lastViewedDate: '2024-01-01',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'A Little Something Extra',
    director: 'Artus',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-01-01',
    lastViewedDate: '2024-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Ghostbusters: Frozen Empire',
    director: 'Gil Kenan',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-01-01',
    lastViewedDate: '2024-01-01',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Civil War',
    director: 'Alex Garland',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-04-17',
    lastViewedDate: '2024-04-17',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'The Fall Guy',
    director: 'David Leitch',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-05-01',
    lastViewedDate: '2024-05-01',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Monkey Man',
    director: 'Dev Patel',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-04-17',
    lastViewedDate: '2024-04-17',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Kung Fu Panda 4',
    director: 'Mike Mitchell, Stephanie Ma Stine',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2024-01-01',
    lastViewedDate: '2024-01-01',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Code 8 : Partie II',
    director: 'Jeff Chan',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2024-02-28',
    lastViewedDate: '2024-02-28',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Aquaman et le Royaume perdu',
    director: 'James Wan',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2023-12-20',
    lastViewedDate: '2023-12-20',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Tout sauf toi',
    director: 'Will Gluck',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2024-01-24',
    lastViewedDate: '2024-01-24',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Iron Claw',
    director: 'Sean Durkin',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-01-24',
    lastViewedDate: '2024-01-24',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Godzilla Minus One',
    director: 'Takashi Yamazaki',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2023-01-01',
    lastViewedDate: '2023-01-01',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Cinq nuits chez Freddy',
    director: 'Emma Tammi',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2023-11-08',
    lastViewedDate: '2023-11-08',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'The Creator',
    director: 'Gareth Edwards',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2023-09-27',
    lastViewedDate: '2023-09-27',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'The Killer',
    director: 'David Fincher',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2023-10-27',
    lastViewedDate: '2023-10-27',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Ferrari',
    director: 'Michael Mann',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-03-08',
    lastViewedDate: '2024-03-08',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Blue Beetle',
    director: 'Angel Manuel Soto',
    rating: 1.5,
    timesWatched: 1,
    firstViewedDate: '2023-08-16',
    lastViewedDate: '2023-08-16',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Le Manoir hanté',
    director: 'Justin Simien',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2023-07-26',
    lastViewedDate: '2023-07-26',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Mission: Impossible – Dead Reckoning Partie 1',
    director: 'Christopher McQuarrie',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2023-07-12',
    lastViewedDate: '2023-07-12',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Le Challenge',
    director: 'Gene Stupnitsky',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2023-06-21',
    lastViewedDate: '2023-06-21',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Indiana Jones and the Dial of Destiny',
    director: 'James Mangold',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2023-01-01',
    lastViewedDate: '2023-01-01',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'AKA',
    director: 'Morgan S. Dalibert',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2023-04-28',
    lastViewedDate: '2023-04-28',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Air',
    director: 'Ben Affleck',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2023-04-05',
    lastViewedDate: '2023-04-05',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Scream VI',
    director: 'Matt Bettinelli-Olpin, Tyler Gillett',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2023-03-08',
    lastViewedDate: '2023-03-08',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "Astérix et Obélix : L'Empire du Milieu",
    director: 'Guillaume Canet',
    rating: 1,
    timesWatched: 1,
    firstViewedDate: '2023-02-01',
    lastViewedDate: '2023-02-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Balle perdue 2',
    director: 'Guillaume Pierret',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2022-11-10',
    lastViewedDate: '2022-11-10',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Le Menu',
    director: 'Mark Mylod',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2022-11-23',
    lastViewedDate: '2022-11-23',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Athena',
    director: 'Romain Gavras',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2022-01-01',
    lastViewedDate: '2022-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'The Gray Man',
    director: 'Anthony Russo, Joe Russo',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2022-07-22',
    lastViewedDate: '2022-07-22',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Le Monstre des mers',
    director: 'Chris Williams',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2022-07-08',
    lastViewedDate: '2022-07-08',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'The Night of the 12th',
    director: 'Dominik Moll',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2022-01-01',
    lastViewedDate: '2022-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Uncharted',
    director: 'Ruben Fleischer',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2022-02-16',
    lastViewedDate: '2022-02-16',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Scream',
    director: 'Matt Bettinelli-Olpin, Tyler Gillett',
    rating: 4.5,
    timesWatched: 1,
    firstViewedDate: '2022-01-12',
    lastViewedDate: '2022-01-12',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Super-héros malgré lui',
    director: 'Philippe Lacheau',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2022-02-02',
    lastViewedDate: '2022-02-02',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: "Conjuring : Sous l'emprise du diable",
    director: 'Michael Chaves',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2021-06-09',
    lastViewedDate: '2021-06-09',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'The Woman in the Window',
    director: 'Joe Wright',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2021-01-01',
    lastViewedDate: '2021-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Army of the Dead',
    director: 'Zack Snyder',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2021-05-21',
    lastViewedDate: '2021-05-21',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Sonic the Hedgehog',
    director: 'Jeff Fowler',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2020-01-01',
    lastViewedDate: '2020-01-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Jumanji: Next Level',
    director: 'Jake Kasdan',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2019-12-04',
    lastViewedDate: '2019-12-04',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Code 8',
    director: 'Jeff Chan',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2019-12-13',
    lastViewedDate: '2019-12-13',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Men in Black: International',
    director: 'F. Gary Gray',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2019-06-12',
    lastViewedDate: '2019-06-12',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Godzilla: King of the Monsters',
    director: 'Michael Dougherty',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2019-01-01',
    lastViewedDate: '2019-01-01',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Crazy Rich Asians',
    director: 'Jon M. Chu',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2018-11-07',
    lastViewedDate: '2018-11-07',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Sans un bruit',
    director: 'John Krasinski',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2018-06-20',
    lastViewedDate: '2018-06-20',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'The Babysitter',
    director: 'McG',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2017-10-13',
    lastViewedDate: '2017-10-13',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: "Assassin's Creed",
    director: 'Justin Kurzel',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2016-12-21',
    lastViewedDate: '2016-12-21',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Les Trolls',
    director: 'Mike Mitchell, Walt Dohrn',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2016-10-19',
    lastViewedDate: '2016-10-19',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Moonlight',
    director: 'Barry Jenkins',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2017-02-01',
    lastViewedDate: '2017-02-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Tarzan',
    director: 'David Yates',
    rating: 4.5,
    timesWatched: 1,
    firstViewedDate: '2016-07-06',
    lastViewedDate: '2016-07-06',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Teenage Mutant Ninja Turtles: Out of the Shadows',
    director: 'Dave Green',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2016-06-29',
    lastViewedDate: '2016-06-29',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Money Monster',
    director: 'Jodie Foster',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2016-05-12',
    lastViewedDate: '2016-05-12',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Five',
    director: 'Igor Gotesman',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2016-08-31',
    lastViewedDate: '2016-08-31',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Steve Jobs',
    director: 'Danny Boyle',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2016-02-03',
    lastViewedDate: '2016-02-03',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Ted 2',
    director: 'Seth MacFarlane',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2015-08-05',
    lastViewedDate: '2015-08-05',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Magic Mike XXL',
    director: 'Gregory Jacobs',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2015-07-08',
    lastViewedDate: '2015-07-08',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Dope',
    director: 'Rick Famuyiwa',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2015-11-04',
    lastViewedDate: '2015-11-04',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Dracula Untold',
    director: 'Gary Shore',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2014-10-01',
    lastViewedDate: '2014-10-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Step Up: All In',
    director: 'Trish Sie',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2014-08-08',
    lastViewedDate: '2014-08-08',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Godzilla',
    director: 'Gareth Edwards',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2014-05-14',
    lastViewedDate: '2014-05-14',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'The Raid 2',
    director: 'Gareth Evans',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2014-07-23',
    lastViewedDate: '2014-07-23',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Out of the Furnace',
    director: 'Scott Cooper',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2014-01-15',
    lastViewedDate: '2014-01-15',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Mama',
    director: 'Andrés Muschietti',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2013-05-15',
    lastViewedDate: '2013-05-15',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Cloud Atlas',
    director: 'Lana Wachowski, Lilly Wachowski, Tom Tykwer',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2013-03-13',
    lastViewedDate: '2013-03-13',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Un monstre à Paris',
    director: 'Bibo Bergeron',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2011-10-12',
    lastViewedDate: '2011-10-12',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Raiponce',
    director: 'Byron Howard, Nathan Greno',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2010-12-01',
    lastViewedDate: '2010-12-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Insidious',
    director: 'James Wan',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2011-06-15',
    lastViewedDate: '2011-06-15',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Le Chat Potté 2 : La Dernière Quête',
    director: 'Joel Crawford',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2022-12-21',
    lastViewedDate: '2022-12-21',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Top Gun : Maverick',
    director: 'Joseph Kosinski',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2022-05-27',
    lastViewedDate: '2022-05-27',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Les 4 fantastiques',
    director: 'Matt Shakman',
    rating: 4.5,
    timesWatched: 1,
    firstViewedDate: '2025-07-25',
    lastViewedDate: '2025-07-25',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'La femme de ménage',
    director: 'Paul Feig',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2025-12-24',
    lastViewedDate: '2025-12-24',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Valerian and the City of a Thousand Planets',
    director: 'Luc Besson',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2017-07-21',
    lastViewedDate: '2017-07-21',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Le Labyrinthe : La Terre Brûlée',
    director: 'Wes Ball',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2015-09-18',
    lastViewedDate: '2015-09-18',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'La rage au ventre',
    director: 'Antoine Fuqua',
    rating: 4,
    timesWatched: 5,
    firstViewedDate: '2015-07-24',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Diversion',
    director: 'Glenn Ficarra, John Requa',
    rating: 4.5,
    timesWatched: 5,
    firstViewedDate: '2015-02-27',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Kingsman : Services Secrets',
    director: 'Matthew Vaughn',
    rating: 3.5,
    timesWatched: 10,
    firstViewedDate: '2015-02-13',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Robocop',
    director: 'José Padilha',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2014-02-12',
    lastViewedDate: '2014-02-12',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Avengers',
    director: 'Joss Whedon',
    rating: 4,
    timesWatched: 16,
    firstViewedDate: '2012-05-04',
    lastViewedDate: '2026-01-28',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Captain America : First Avenger',
    director: 'Joe Johnston',
    rating: 3,
    timesWatched: 15,
    firstViewedDate: '2011-07-22',
    lastViewedDate: '2026-01-25',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Captain America : Civil War',
    director: 'Anthony Russo, Joe Russo',
    rating: 4,
    timesWatched: 15,
    firstViewedDate: '2016-05-06',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Thor : Love & Thunder',
    director: 'Taika Waititi',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2022-07-08',
    lastViewedDate: '2022-07-08',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Les Marvels',
    director: 'Nia DaCosta',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2023-11-10',
    lastViewedDate: '2023-11-10',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Doctor Strange dans le Multivers de la Folie',
    director: 'Sam Raimi',
    rating: 3.5,
    timesWatched: 2,
    firstViewedDate: '2022-05-06',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Black Panther : Wakanda pour Toujours',
    director: 'Ryan Coogler',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2022-11-11',
    lastViewedDate: '2022-11-11',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Spider-Man : No Way Home',
    director: 'Jon Watts',
    rating: 4,
    timesWatched: 5,
    firstViewedDate: '2021-12-17',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'The Dark Knight : Le Chevalier Noir',
    director: 'Christopher Nolan',
    rating: 4,
    timesWatched: 15,
    firstViewedDate: '2008-07-18',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'X-Men : Apocalypse',
    director: 'Bryan Singer',
    rating: 2,
    timesWatched: 3,
    firstViewedDate: '2016-05-27',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'X-Men :Dark Phoenix',
    director: 'Simon Kinberg',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2019-06-07',
    lastViewedDate: '2019-06-07',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Dragons 3: Le monde perdu',
    director: 'Dean DeBlois',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2019-02-22',
    lastViewedDate: '2019-02-22',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Super Mario Bros. le Film',
    director: 'Aaron Horvath, Michael Jelenic',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2023-04-05',
    lastViewedDate: '2023-04-05',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Harry Potter et le prince de sang-mêlé',
    director: 'David Yates',
    rating: 3.5,
    timesWatched: 15,
    firstViewedDate: '2009-07-15',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Harry Potter et les reliques de la mort - partie 1',
    director: 'David Yates',
    rating: 4,
    timesWatched: 15,
    firstViewedDate: '2010-11-19',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Star Wars : Épisode 3 - La revanche des Sith',
    director: 'George Lucas',
    rating: 4.5,
    timesWatched: 20,
    firstViewedDate: '2005-05-19',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Star Wars : Episode 7 - Le réveil de la Force',
    director: 'J.J. Abrams',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '2015-12-18',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Star Wars : Episode 8 - Le dernier Jedi',
    director: 'Rian Johnson',
    rating: 3.5,
    timesWatched: 5,
    firstViewedDate: '2017-12-15',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Rogue One : A Star Wars Story',
    director: 'Gareth Edwards',
    rating: 2.5,
    timesWatched: 5,
    firstViewedDate: '2016-12-16',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Dune : Partie 2',
    director: 'Denis Villeneuve',
    rating: 5,
    timesWatched: 3,
    firstViewedDate: '2024-03-01',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'John Wick: Chapter 3 - Parabellum',
    director: 'Chad Stahelski',
    rating: 4,
    timesWatched: 2,
    firstViewedDate: '2019-05-17',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Le Labyrinthe 2 : Le remède mortel',
    director: 'Wes Ball',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2018-01-26',
    lastViewedDate: '2018-01-26',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Hunger Games',
    director: 'Gary Ross',
    rating: 4,
    timesWatched: 5,
    firstViewedDate: '2012-03-23',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Hunger Games : La Révolte - Partie 1',
    director: 'Francis Lawrence',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '2014-11-21',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Transformers 2 : La Revanche',
    director: 'Michael Bay',
    rating: 2.5,
    timesWatched: 10,
    firstViewedDate: '2009-06-24',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Twilight : Chapitre 4 - Révélation - Partie 1',
    director: 'Bill Condon',
    rating: 3.5,
    timesWatched: 10,
    firstViewedDate: '2011-11-18',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Green Book : Sur les routes du Sud',
    director: 'Peter Farrelly',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2019-01-23',
    lastViewedDate: '2019-01-23',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Hérédité',
    director: 'Ari Aster',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2018-06-13',
    lastViewedDate: '2018-06-13',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Life : Origine inconnue',
    director: 'Daniel Espinosa',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2017-04-19',
    lastViewedDate: '2017-04-19',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Mission : Impossible – Rogue Nation',
    director: 'Christopher McQuarrie',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2015-08-12',
    lastViewedDate: '2015-08-12',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Paranormal Activity 5 : Ghost Dimension',
    director: 'Gregory Plotkin',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2015-10-21',
    lastViewedDate: '2015-10-21',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Ninja Turtles',
    director: 'Jonathan Liebesman',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2014-10-15',
    lastViewedDate: '2014-10-15',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Vampires en toute intimité',
    director: 'Taika Waititi, Jemaine Clement',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2015-02-11',
    lastViewedDate: '2015-02-11',
    seenAtCinema: true,
    owned: false,
  },

  {
    title: 'One Piece Film Z',
    director: 'Tatsuya Nagamine',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2013-05-15',
    lastViewedDate: '2013-05-15',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Le Hobbit : Un voyage inattendu',
    director: 'Peter Jackson',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2012-12-14',
    lastViewedDate: '2012-12-14',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Phone Game',
    director: 'Joel Schumacher',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2002-09-10',
    lastViewedDate: '2002-09-10',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: "Avengers : L'Ère d'Ultron",
    director: 'Joss Whedon',
    rating: 4, // Avengers: Age of Ultron (2015) ★★★★
    timesWatched: 15,
    firstViewedDate: '2015-05-01',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "Captain America : Le Soldat de l'Hiver",
    director: 'Anthony Russo, Joe Russo',
    rating: 4,
    timesWatched: 15,
    firstViewedDate: '2014-04-04',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Les Gardiens de la Galaxie',
    director: 'James Gunn',
    rating: 4, // Guardians of the Galaxy (2014) ★★★★
    timesWatched: 10,
    firstViewedDate: '2014-08-01',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Les Gardiens de la Galaxie Vol. 2',
    director: 'James Gunn',
    rating: 4,
    timesWatched: 5,
    firstViewedDate: '2017-05-05',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Les Gardiens de la Galaxie Vol. 3',
    director: 'James Gunn',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2023-05-05',
    lastViewedDate: '2023-05-05',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Ant-Man et la Guêpe',
    director: 'Peyton Reed',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '2018-07-06',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Ant-Man et la Guêpe : Quantumania',
    director: 'Peyton Reed',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2023-02-17',
    lastViewedDate: '2023-02-17',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Les Éternels',
    director: 'Chloé Zhao',
    rating: 3, // Eternals (2021) ★★★
    timesWatched: 1,
    firstViewedDate: '2021-11-05',
    lastViewedDate: '2021-11-05',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "Batman v Superman : L'Aube de la Justice",
    director: 'Zack Snyder',
    rating: 3.5,
    timesWatched: 10,
    firstViewedDate: '2016-03-25',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "The Amazing Spider-Man : Le Destin d'un Héros",
    director: 'Marc Webb',
    rating: 4,
    timesWatched: 10,
    firstViewedDate: '2014-05-02',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Les 4 Fantastiques',
    director: 'Josh Trank',
    rating: 0.5, // Fantastic Four (2015) ★
    timesWatched: 5,
    firstViewedDate: '2015-08-07',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Sex Friends',
    director: 'Ivan Reitman',
    rating: 3, // No Strings Attached (2011) ★★★
    timesWatched: 5,
    firstViewedDate: '2011-02-16',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: "L'amour ouf",
    director: 'Claude Zidi Jr.',
    rating: 3.5, // Beating Hearts (2024) ★★★½
    timesWatched: 1,
    firstViewedDate: '2024-01-31',
    lastViewedDate: '2024-01-31',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Spider-Man : À Travers le Spider-Verse',
    director: 'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson',
    rating: 5,
    timesWatched: 3,
    firstViewedDate: '2023-06-02',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "Harry Potter à l'école des sorciers",
    director: 'Chris Columbus',
    rating: 3.5, // Harry Potter and the Philosopher's Stone (2001) ★★★½
    timesWatched: 20,
    firstViewedDate: '2001-11-16',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Harry Potter et la chambre des secrets',
    director: 'Chris Columbus',
    rating: 4,
    timesWatched: 20,
    firstViewedDate: '2002-11-15',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "Harry Potter et le prisonnier d'Azkaban",
    director: 'Alfonso Cuarón',
    rating: 4, // Harry Potter and the Prisoner of Azkaban (2004) ★★★★
    timesWatched: 20,
    firstViewedDate: '2004-06-04',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Harry Potter et la coupe de feu',
    director: 'Mike Newell',
    rating: 4, // Harry Potter and the Goblet of Fire (2005) ★★★★
    timesWatched: 20,
    firstViewedDate: '2005-11-18',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "Harry Potter et l'ordre du phénix",
    director: 'David Yates',
    rating: 3, // Harry Potter and the Order of the Phoenix (2007) ★★★
    timesWatched: 15,
    firstViewedDate: '2007-07-11',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Harry Potter et les reliques de la mort - partie 2',
    director: 'David Yates',
    rating: 4, // Harry Potter and the Deathly Hallows: Part 2 (2011) ★★★★
    timesWatched: 15,
    firstViewedDate: '2011-07-15',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "Star Wars : Episode 9 - L'ascension de Skywalker",
    director: 'J.J. Abrams',
    rating: 4.5,
    timesWatched: 3,
    firstViewedDate: '2019-12-20',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Fast & Furious 7',
    director: 'James Wan',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '2015-04-03',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Fast & Furious 9',
    director: 'Justin Lin',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2021-06-25',
    lastViewedDate: '2021-06-25',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Fast & Furious X',
    director: 'Louis Leterrier',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2023-05-19',
    lastViewedDate: '2023-05-19',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'John Wick : Chapitre 4',
    director: 'Chad Stahelski',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2023-03-24',
    lastViewedDate: '2023-03-24',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Les Animaux Fantastiques',
    director: 'David Yates',
    rating: 3, // Fantastic Beasts and Where to Find Them (2016) ★★★
    timesWatched: 3,
    firstViewedDate: '2016-11-18',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Les Animaux Fantastiques 2 : Les crimes de Grindelwald',
    director: 'David Yates',
    rating: 3, // Fantastic Beasts: The Crimes of Grindelwald (2018) ★★★
    timesWatched: 5,
    firstViewedDate: '2018-11-16',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Les Animaux Fantastiques 3 : Les Secrets de Dumbledore',
    director: 'David Yates',
    rating: 2, // Fantastic Beasts: The Secrets of Dumbledore (2022) ★★
    timesWatched: 1,
    firstViewedDate: '2022-04-15',
    lastViewedDate: '2022-04-15',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'James Bond : Mourir Peut Attendre',
    director: 'Cary Joji Fukunaga',
    rating: 4, // No Time to Die (2021) ★★★★
    timesWatched: 1,
    firstViewedDate: '2021-10-08',
    lastViewedDate: '2021-10-08',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Inssaisissables',
    director: 'Louis Leterrier',
    rating: 4, // Now You See Me (2013) ★★★★
    timesWatched: 5,
    firstViewedDate: '2013-05-31',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Transformers 3 : La Face Cachée de la Lune',
    director: 'Michael Bay',
    rating: 4, // Transformers: Dark of the Moon (2011) ★★★★
    timesWatched: 15,
    firstViewedDate: '2011-06-29',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "Transformers 4 : L'Âge de l'Extinction",
    director: 'Michael Bay',
    rating: 3, // Transformers: Age of Extinction (2014) ★★★
    timesWatched: 5,
    firstViewedDate: '2014-06-27',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Very Bad Trip 2',
    director: 'Todd Phillips',
    rating: 3, // The Hangover Part II (2011) ★★★
    timesWatched: 5,
    firstViewedDate: '2011-05-26',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Very Bad Trip 3',
    director: 'Todd Phillips',
    rating: 3, // The Hangover Part III (2013) ★★★
    timesWatched: 5,
    firstViewedDate: '2013-05-23',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Twilight : Chapitre 2 - Tentation',
    director: 'Chris Weitz',
    rating: 2.5, // The Twilight Saga: New Moon (2009) ★★½
    timesWatched: 10,
    firstViewedDate: '2009-11-20',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Twilight : Chapitre 3 - Hésitation',
    director: 'David Slade',
    rating: 3, // The Twilight Saga: Eclipse (2010) ★★★
    timesWatched: 10,
    firstViewedDate: '2010-06-30',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Twilight : Chapitre 4 - Révélation - Partie 2',
    director: 'Bill Condon',
    rating: 3, // The Twilight Saga: Breaking Dawn – Part 2 (2012) ★★★
    timesWatched: 5,
    firstViewedDate: '2012-11-16',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Underworld : Éveil',
    director: 'Måns Mårlind, Björn Stein',
    rating: 3, // Underworld: Awakening (2012) ★★★
    timesWatched: 1,
    firstViewedDate: '2012-01-20',
    lastViewedDate: '2012-01-20',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Les Bronzés 3 : Amis pour la Vie',
    director: 'Patrice Leconte',
    rating: 2.5, // French Fried Vacations 3: Friends Forever (2006) ★★½
    timesWatched: 3,
    firstViewedDate: '2006-01-25',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: "Avatar 2 : La Voie de l'Eau",
    director: 'James Cameron',
    rating: 4, // Avatar: The Way of Water (2022) ★★★★
    timesWatched: 2,
    firstViewedDate: '2022-12-16',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "The King's Man : Première mission",
    director: 'Matthew Vaughn',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2021-12-22',
    lastViewedDate: '2021-12-22',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'La Reine des neiges 2',
    director: 'Chris Buck, Jennifer Lee',
    rating: 3, // Frozen II (2019) ★★★
    timesWatched: 1,
    firstViewedDate: '2019-11-22',
    lastViewedDate: '2019-11-22',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Jumanji : Bienvenue dans la jungle',
    director: 'Jake Kasdan',
    rating: 3.5,
    timesWatched: 5,
    firstViewedDate: '2017-12-20',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Pirates des Caraïbes : La Vengeance de Salazar',
    director: 'Joachim Rønning, Espen Sandberg',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '2017-05-26',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },

  {
    title: 'Le Grinch',
    director: 'Ron Howard',
    rating: 4, // How the Grinch Stole Christmas (2000) ★★★★
    timesWatched: 15,
    firstViewedDate: '2000-11-17',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Le Grinch',
    director: 'Yarrow Cheney, Scott Mosier',
    rating: 3, // The Grinch (2018) ★★★
    timesWatched: 1,
    firstViewedDate: '2018-11-28',
    lastViewedDate: '2018-11-28',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'American Nightmare 4 : Les Origines',
    director: 'Gerard McMurray',
    rating: 2.5, // The First Purge (2018) ★★½
    timesWatched: 1,
    firstViewedDate: '2018-07-04',
    lastViewedDate: '2018-07-04',
    seenAtCinema: true,
    owned: false,
  },

  {
    title: 'La Planète des singes : Suprématie',
    director: 'Matt Reeves',
    rating: 4, // War for the Planet of the Apes (2017) ★★★★
    timesWatched: 1,
    firstViewedDate: '2017-08-02',
    lastViewedDate: '2017-08-02',
    seenAtCinema: true,
    owned: true,
  },

  {
    title: 'Lego Batman, le film',
    director: 'Chris McKay',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2017-02-08',
    lastViewedDate: '2017-02-08',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Nos pires voisins 2',
    director: 'Nicholas Stoller',
    rating: 3, // Neighbors 2: Sorority Rising (2016) ★★★
    timesWatched: 1,
    firstViewedDate: '2016-07-06',
    lastViewedDate: '2016-07-06',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Hunger Games : La Révolte, partie 2',
    director: 'Francis Lawrence',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2015-11-18',
    lastViewedDate: '2015-11-18',
    seenAtCinema: true,
    owned: false,
  },

  {
    title: 'À la poursuite de demain',
    director: 'Brad Bird',
    rating: 3, // Tomorrowland (2015) ★★★
    timesWatched: 1,
    firstViewedDate: '2015-05-20',
    lastViewedDate: '2015-05-20',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: "Dragon Ball Z : La Résurrection de 'F'",
    director: 'Tadayoshi Yamamuro',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2015-09-11',
    lastViewedDate: '2015-09-11',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Hunger Games : La Révolte, partie 1',
    director: 'Francis Lawrence',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2014-11-19',
    lastViewedDate: '2014-11-19',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Equalizer',
    director: 'Antoine Fuqua',
    rating: 3.5, // The Equalizer (2014) ★★★½
    timesWatched: 1,
    firstViewedDate: '2014-10-01',
    lastViewedDate: '2014-10-01',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: "La Planète des singes : l'affrontement",
    director: 'Matt Reeves',
    rating: 4, // Dawn of the Planet of the Apes (2014) ★★★★
    timesWatched: 1,
    firstViewedDate: '2014-07-30',
    lastViewedDate: '2014-07-30',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: "Transformers : L'Âge de l'extinction",
    director: 'Michael Bay',
    rating: 3, // Transformers: Age of Extinction (2014) ★★★
    timesWatched: 1,
    firstViewedDate: '2014-07-16',
    lastViewedDate: '2014-07-16',
    seenAtCinema: true,
    owned: true,
  },
  {
    title: 'Nos pires voisins',
    director: 'Nicholas Stoller',
    rating: 3.5, // Neighbors (2014) ★★★½
    timesWatched: 1,
    firstViewedDate: '2014-05-28',
    lastViewedDate: '2014-05-28',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Mister Babadook',
    director: 'Jennifer Kent',
    rating: 3, // The Babadook (2014) ★★★
    timesWatched: 1,
    firstViewedDate: '2014-07-30',
    lastViewedDate: '2014-07-30',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: "Hunger Games : L'Embrasement",
    director: 'Francis Lawrence',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2013-11-27',
    lastViewedDate: '2013-11-27',
    seenAtCinema: true,
    owned: false,
  },
  {
    title: 'Mindscape',
    director: 'Jorge Dorado',
    rating: 3, // Anna (2013) ★★★
    timesWatched: 1,
    firstViewedDate: '2014-06-11',
    lastViewedDate: '2014-06-11',
    seenAtCinema: true,
    owned: false,
  },

  {
    title: 'Mary',
    director: 'Marc Webb',
    rating: 3.5, // Gifted (2017) - not found in ratings list
    timesWatched: 1,
    firstViewedDate: '2017-09-13',
    lastViewedDate: '2017-09-13',
    seenAtCinema: true,
    owned: false,
  },
];
