import { UserMovies } from '../../../../models/movie-model';

export const ronanWatchlistMovies: UserMovies = [
  {
    title: 'La méthode Williams',
    director: 'Reinaldo Marcus Green',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Shaolin Soccer',
    director: 'Stephen Chow',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Mulholland Drive',
    director: 'David Lynch',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: "A l'aube du 6ème jour",
    director: 'Roger Spottiswoode',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Requiem for a Dream',
    director: 'Darren Aronofsky',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Nocturnal Animals',
    director: 'Tom Ford',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La soupe aux choux',
    director: 'Jean-Charles Tacchella',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Les oiseaux',
    director: 'Alfred Hitchcock',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Psychose',
    director: 'Alfred Hitchcock',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Citizen Kane',
    director: 'Orson Welles',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Babylon A.D',
    director: 'Mathieu Kassovitz',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Babel',
    director: 'Alejandro González Iñárritu',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Baby Sittor',
    director: 'Adam Shankman',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Speed',
    director: 'Jan de Bont',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Demolition',
    director: 'Jean-Marc Vallée',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Spaceballs',
    director: 'Mel Brooks',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Les Incorruptibles',
    director: 'Brian De Palma',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Commando',
    director: 'Mark L. Lester',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le flic de Beverly Hills',
    director: 'Martin Brest',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Speed Racer',
    director: 'Lana Wachowski, Lilly Wachowski',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La vague',
    director: 'Dennis Gansel',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Gone Baby Gone',
    director: 'Ben Affleck',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La chambre 1408',
    director: 'Mikael Håfström',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Trainspotting',
    director: 'Danny Boyle',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'The Blind Side',
    director: 'John Lee Hancock',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Majordome',
    director: 'Lee Daniels',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Cowboys & Aliens',
    director: 'Jon Favreau',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Good Morning, Vietnam',
    director: 'Barry Levinson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le dernier samaritain',
    director: 'Tony Scott',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Double Impact',
    director: 'Sheldon Lettich',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Les Affranchis',
    director: 'Martin Scorsese',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Nikita',
    director: 'Luc Besson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Cliffhanger',
    director: 'Renny Harlin',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le fugitif',
    director: 'Andrew Davis',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: "Le Joyeux Noël d'Harold et Kumar",
    director: 'Todd Strauss-Schulson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Écrire pour exister',
    director: 'Richard LaGravenese',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le nombre 23',
    director: 'Joel Schumacher',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Renaissances',
    director: 'Tarsem Singh',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Philadelphia',
    director: 'Jonathan Demme',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Sully',
    director: 'Clint Eastwood',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Pinocchio',
    director: 'Guillermo del Toro, Mark Gustafson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Blonde',
    director: 'Andrew Dominik',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Retour de Mary Poppins',
    director: 'Rob Marshall',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Mamma Mia! Here We Go Again',
    director: 'Ol Parker',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Paddington 2',
    director: 'Paul King',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Paddington',
    director: 'Paul King',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Big Eyes',
    director: 'Tim Burton',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'About Time',
    director: 'Richard Curtis',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Sweeney Todd : Le Diabolique Barbier de Fleet Street',
    director: 'Tim Burton',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Labyrinthe de Pan',
    director: 'Guillermo del Toro',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Marie Antoinette',
    director: 'Sofia Coppola',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Aviator',
    director: 'Martin Scorsese',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La Planète des singes',
    director: 'Tim Burton',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'A.I. Intelligence artificielle',
    director: 'Steven Spielberg',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Moulin Rouge !',
    director: 'Baz Luhrmann',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Billy Elliot',
    director: 'Stephen Daldry',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Fantasia 2000',
    director: 'James Algar, Gaëtan Brizzi',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: '10 bonnes raisons de te larguer',
    director: 'Gil Junger',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Gattaca',
    director: 'Andrew Niccol',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Face/Off',
    director: 'John Woo',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Roméo + Juliette',
    director: 'Baz Luhrmann',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'James et la Pêche géante',
    director: 'Henry Selick',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'GoldenEye',
    director: 'Martin Campbell',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Braveheart',
    director: 'Mel Gibson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Ace Ventura: Détective pour chiens et chats',
    director: 'Tom Shadyac',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'JFK',
    director: 'Oliver Stone',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La Famille Addams',
    director: 'Barry Sonnenfeld',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Ghost',
    director: 'Jerry Zucker',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Oliver et Compagnie',
    director: 'George Scribner',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Tombeau des lucioles',
    director: 'Isao Takahata',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Nausicaä de la Vallée du Vent',
    director: 'Hayao Miyazaki',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'The Blues Brothers',
    director: 'John Landis',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Halloween',
    director: 'John Carpenter',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Les Parapluies de Cherbourg',
    director: 'Jacques Demy',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Vacances romaines',
    director: 'William Wyler',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Chantons sous la pluie',
    director: 'Gene Kelly, Stanley Donen',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Orgueil et Préjugés',
    director: 'Joe Wright',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Rencontre avec Joe Black',
    director: 'Martin Brest',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Isi & Ossi',
    director: 'Oliver Kienle',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: "L'arme fatale 4",
    director: 'Richard Donner',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Predator 2',
    director: 'Stephen Hopkins',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Predators',
    director: 'Nimród Antal',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'The Predator',
    director: 'Shane Black',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Aliens',
    director: 'James Cameron',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Alien 3',
    director: 'David Fincher',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Alien : La Résurrection',
    director: 'Jean-Pierre Jeunet',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Alien vs. Predator : Requiem',
    director: 'Colin Strause, Greg Strause',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Rambo 3',
    director: 'Peter MacDonald',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'John Rambo',
    director: 'Sylvester Stallone',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Die Hard : Belle Journée pour Mourir',
    director: 'John Moore',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'James Bond: Meurs un autre jour',
    director: 'Lee Tamahori',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le cercle : The ring',
    director: 'Gore Verbinski',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Ava',
    director: 'Tate Taylor',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Lord of War',
    director: 'Andrew Niccol',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Serial Nocers',
    director: 'David Dobkin',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'True Lies',
    director: 'James Cameron',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La ligue des gentlemen extraordinaires',
    director: 'Stephen Norrington',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Waterworld',
    director: 'Kevin Reynolds',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Tango & Cash',
    director: 'Andrei Konchalovsky',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'The Running Man',
    director: 'Paul Michael Glaser',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Atonement',
    director: 'Joe Wright',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'The Worst Person in the World',
    director: 'Joachim Trier',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Novocaine',
    director: 'David Atkins',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Companion',
    director: 'Drew Hancock',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Nobody 2',
    director: 'Timo Tjahjanto',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Seul sur Mars',
    director: 'Ridley Scott',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Ennemi d\'Etat',
    director: 'Tony Scott',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Bad Boys Ride or Die',
    director: 'Adil El Arbi, Bilall Fallah',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Cobra',
    director: 'George P. Cosmatos',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Haute sécurité',
    director: 'Marco Brambilla',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Copland',
    director: 'James Mangold',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Rambo: Last Blood',
    director: 'Adrian Grunberg',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Expend4bles',
    director: 'Scott Waugh',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Jumeaux',
    director: 'Ivan Reitman',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Un flic à la maternelle',
    director: 'Ivan Reitman',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Junior',
    director: 'Ivan Reitman',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Dernier rempart',
    director: 'Rod Lurie',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Sabotage',
    director: 'David Ayer',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'L\'Armée des 12 singes',
    director: 'Terry Gilliam',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Sale Môme',
    director: 'Barry Levinson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Bandits',
    director: 'Barry Levinson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Mon voisin le tueur 2',
    director: 'Patrick Read Johnson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Slevin',
    director: 'Paul McGuigan',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Top Cops',
    director: 'David Twohy',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Clones',
    director: 'Jonathan Mostow',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Ace Ventura en Afrique',
    director: 'Steve Oedekerk',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Fous d\'Irène',
    director: 'Bobby Farrelly, Peter Farrelly',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Braqueurs amateurs',
    director: 'Les Mayfield',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Drôle de Noël de Scrooge',
    director: 'Robert Zemeckis',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'M. Popper et ses pingouins',
    director: 'Mark Waters',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Il faut sauver le soldat Ryan',
    director: 'Steven Spielberg',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Les Joueurs',
    director: 'John Dahl',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Les Frères Grimm',
    director: 'Terry Gilliam',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'True Grit',
    director: 'Joel Coen, Ethan Coen',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Green Zone',
    director: 'Paul Greengrass',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Stillwater',
    director: 'Tom McCarthy',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Légendes d\'automne',
    director: 'Edward Zwick',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Sleepers',
    director: 'Barry Levinson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Sept Ans au Tibet',
    director: 'Jean-Jacques Annaud',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Ennemis rapprochés',
    director: 'David O. Russell',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Spy game, jeu d\'espions',
    director: 'Tony Scott',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'L\'Assassinat de Jesse James par le lâche Robert Ford',
    director: 'Andrew Dominik',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Burn After Reading',
    director: 'Joel Coen, Ethan Coen',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le stratège',
    director: 'Bennett Miller',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'The Tree of Life',
    director: 'Terrence Malick',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Cogan - Killing Them Softly',
    director: 'Andrew Dominik',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: '12 Years a Slave',
    director: 'Steve McQueen',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'The Big Short',
    director: 'Adam McKay',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'War Machine',
    director: 'David Michôd',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Apollo 13',
    director: 'Ron Howard',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Il n\'est jamais trop tard',
    director: 'Tom Hanks',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Capitaine Phillips',
    director: 'Paul Greengrass',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Pont des espions',
    director: 'Steven Spielberg',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Pentagon Papers',
    director: 'Steven Spielberg',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Finch',
    director: 'Miguel Sapochnik',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Asteroid City',
    director: 'Wes Anderson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Here - Les plus belles années de notre vie',
    director: 'Robert Zemeckis',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Cocktail',
    director: 'Roger Donaldson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Jours de tonnerre',
    director: 'Tony Scott',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Jerry Maguire',
    director: 'Cameron Crowe',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Magnolia',
    director: 'Paul Thomas Anderson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Eyes Wide Shut',
    director: 'Stanley Kubrick',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Vanilla Sky',
    director: 'Cameron Crowe',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Walkyrie',
    director: 'Bryan Singer',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Rock Forever',
    director: 'Adam Shankman',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Gilbert Grape',
    director: 'Lasse Hallström',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Mensonges d\'État',
    director: 'Ridley Scott',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Les Noces rebelles',
    director: 'Sam Mendes',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'J. Edgar',
    director: 'Clint Eastwood',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'End of Watch',
    director: 'David Ayer',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Everest',
    director: 'Baltasar Kormákur',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Stronger',
    director: 'David Gordon Green',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Okja',
    director: 'Bong Joon-ho',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'The Covenant',
    director: 'Guy Ritchie',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Australia',
    director: 'Baz Luhrmann',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Reminiscence',
    director: 'Lisa Joy',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Max la Menace',
    director: 'Peter Segal',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Buried',
    director: 'Rodrigo Cortés',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Captives',
    director: 'Atom Egoyan',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Big Daddy',
    director: 'Dennis Dugan',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Punch-Drunk Love',
    director: 'Paul Thomas Anderson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Spaceman',
    director: 'Johan Renck',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Happy Gilmore',
    director: 'Dennis Dugan',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Empire du soleil',
    director: 'Steven Spielberg',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'L\'Île au trésor',
    director: 'Fraser Clarke Heston',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Shaft',
    director: 'John Singleton',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Capitaine Corelli',
    director: 'John Madden',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Règne du feu',
    director: 'Rob Bowman',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'The Machinist',
    director: 'Brad Anderson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La Promesse',
    director: 'Terry George',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Vice',
    director: 'Adam McKay',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'The Pale Blue Eye',
    director: 'Scott Cooper',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Deux Sœurs pour un roi',
    director: 'Justin Chadwick',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Hitchcock',
    director: 'Sacha Gervasi',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Moi, Tonya',
    director: 'Craig Gillespie',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Scandale',
    director: 'Jay Roach',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Hurlevent',
    director: 'Frances O\'Connor',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Jack',
    director: 'Francis Ford Coppola',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Docteur Patch',
    director: 'Christopher Nolan',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Amistad',
    director: 'Steven Spielberg',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Deep Impact',
    director: 'Mimi Leder',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Last Vegas',
    director: 'Jon Turteltaub',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Transcendance',
    director: 'Wally Pfister',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Braquage à l\'ancienne',
    director: 'Zach Braff',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'L\'impasse',
    director: 'Brian De Palma',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Vol au-dessus d\'un nid de coucou',
    director: 'Milos Forman',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Il était une fois en Amérique',
    director: 'Sergio Leone',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Bon, la brute et le truand',
    director: 'Sergio Leone',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Dictateur',
    director: 'Charlie Chaplin',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La Vie est belle',
    director: 'Roberto Benigni',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Apocalypse Now',
    director: 'Francis Ford Coppola',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Voyage au bout de l\'enfer',
    director: 'Michael Cimino',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Pianiste',
    director: 'Roman Polanski',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Je verrai toujours vos visages',
    director: 'Jeanne Herry',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Elephant Man',
    director: 'David Lynch',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Fenêtre sur cour',
    director: 'Alfred Hitchcock',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Barry Lyndon',
    director: 'Stanley Kubrick',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Vivre',
    director: 'Akira Kurosawa',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La Ruée vers l\'or',
    director: 'Charlie Chaplin',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Conte de la princesse Kaguya',
    director: 'Isao Takahata',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La Grande Vadrouille',
    director: 'Gérard Oury',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Sueurs froides',
    director: 'Alfred Hitchcock',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Barberousse',
    director: 'Akira Kurosawa',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La Mort aux trousses',
    director: 'Alfred Hitchcock',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La Vie est belle',
    director: 'Frank Capra',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Danse avec les loups',
    director: 'Kevin Costner',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Casino',
    director: 'Martin Scorsese',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Et pour quelques dollars de plus',
    director: 'Sergio Leone',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Lawrence d\'Arabie',
    director: 'David Lean',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'M le Maudit',
    director: 'Fritz Lang',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Je veux manger ton pancréas',
    director: 'Shin\'ichirô Ushijima',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Nom de la Rose',
    director: 'Jean-Jacques Annaud',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Mad Max',
    director: 'George Miller',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Mad Max 2',
    director: 'George Miller',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La Passion du Christ',
    director: 'Mel Gibson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Jackie',
    director: 'Pablo Larraín',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Annihilation',
    director: 'Alex Garland',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Les Filles du docteur March',
    director: 'Greta Gerwig',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Ma mère, Dieu et Sylvie Vartan',
    director: 'Sylvie Audcoeur',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La French',
    director: 'Cédric Jimenez',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Un homme à la hauteur',
    director: 'Laurent Tirard',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La vie d\'Adèle',
    director: 'Abdellatif Kechiche',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Un singe en hiver',
    director: 'Henri Verneuil',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Steak',
    director: 'Charles Nemes',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Tempête de Boulettes Géantes',
    director: 'Phil Lord, Christopher Miller',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Horton',
    director: 'Jimmy Hayward, Steve Martino',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'One Piece : Gold',
    director: 'Hiroaki Miyamoto',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'One Piece: Stampede',
    director: 'Takashi Otsuka',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Fantasia',
    director: 'James Algar, Samuel Armstrong',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Anastasia',
    director: 'Don Bluth, Gary Goldman',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Ponyo',
    director: 'Hayao Miyazaki',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Coraline',
    director: 'Henry Selick',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Arrietty, le petit monde des chapardeurs',
    director: 'Hiromasa Yonebayashi',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Bubble',
    director: 'Tetsurō Araki',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Hollywood',
    director: 'Ryan Murphy',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Bohemian Rhapsody',
    director: 'Bryan Singer',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Lion',
    director: 'Garth Davis',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Minuit à Paris',
    director: 'Woody Allen',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Little White Lies',
    director: 'Guillaume Canet',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Lovely Bones',
    director: 'Peter Jackson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: '27 Robes',
    director: 'Anne Fletcher',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'P.S. I Love You',
    director: 'Richard LaGravenese',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Les déstreuses aventures des Orphelins Baudelaire',
    director: 'Brad Silberling',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Village',
    director: 'M. Night Shyamalan',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Comme Cendrillon',
    director: 'Mark Rosman',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Lolita malgré moi',
    director: 'Mark Waters',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'The Others',
    director: 'Alejandro Amenábar',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'La Revanche d\'une blonde',
    director: 'Robert Luketic',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Le Journal de Bridget Jones',
    director: 'Sharon Maguire',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'People We Meet on Vacation',
    director: 'Brett Haley',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Nos coeurs meurtris',
    director: 'Elizabeth Allen Rosenbaum',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Rush Hour 2',
    director: 'Brett Ratner',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Rush Hour 3',
    director: 'Brett Ratner',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
];
