import { UserBook } from '../../../../models/book-model';

export const masterofmadnessBooks: UserBook[] = [
  {
    title: 'The Shining',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Hauts de Hurlevent',
    author: 'Emily Brontë',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Frankenstein',
    author: 'Mary Shelley',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Portrait de Dorian Gray',
    author: 'Oscar Wilde',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Ferme des animaux',
    author: 'George Orwell',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: '1984',
    author: 'George Orwell',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Dracula',
    author: 'Bram Stoker',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Une vie',
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 2,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Madame Bovary',
    author: 'Gustave Flaubert',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 3,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Bel-Ami',
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Candide',
    author: 'Voltaire',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Carrie',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Tristan et Iseult',
    author: 'René Louis',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Voyage au bout de la nuit',
    author: 'Louis-Ferdinand Céline',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Petit Prince',
    author: 'Antoine de Saint-Exupéry',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Le Seigneur des Anneaux Tome 1 : La Communauté de l'Anneau",
    author: 'J.R.R. Tolkien',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Contemplations',
    author: 'Victor Hugo',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le bourgeois Gentilshommes',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les fourberies de Scapin',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 5,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'avare",
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 3,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Tartuffe',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 2,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les précieuses ridicules',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Misanthrope',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Cid',
    author: 'Corneille',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 2,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le mariage de Figaro',
    author: 'Beaumarchais',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Gargantua',
    author: 'François Rabelais',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Antigone',
    author: 'Jean Anouilh',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 2,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Lancelot ou le Chevalier de la charrette',
    author: 'Chrétien de Troyes',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Yvain ou le Chevalier au lion',
    author: 'Chrétien de Troyes',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Perceval ou le Conte du Graal',
    author: 'Chrétien de Troyes',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'étranger",
    author: 'Albert Camus',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Enfant de Poussière",
    author: 'Patrick K. Dewdney',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Peste et la Vigne',
    author: 'Patrick K. Dewdney',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Chiens et la Charrue',
    author: 'Patrick K. Dewdney',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Maison des Veilleurs',
    author: 'Patrick K. Dewdney',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'épée de la providence (The Witcher, #2)",
    author: 'Andrzej Sapkowski',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le dernier voeu (The Witcher, #1)',
    author: 'Andrzej Sapkowski',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Les ténèbres (Journal d'un vampire, #2)",
    author: 'L.J. Smith',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Le réveil (Journal d'un vampire, #1)",
    author: 'L.J. Smith',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Harry Potter à l'école des sorciers",
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 5,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Harry Potter et la Chambre des secrets',
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 5,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Harry Potter et le Prisonnier d'Azkaban",
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 4,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Harry Potter et la Coupe de feu',
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 4,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Harry Potter et l'Ordre du Phénix",
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 4,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Harry Potter et le Prince de sang-mêlé',
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 4,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Harry Potter et les Reliques de la Mort',
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 4,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Fascination',
    author: 'Stephenie Meyer',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Tentation',
    author: 'Stephenie Meyer',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Hésitation',
    author: 'Stephenie Meyer',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Révélation',
    author: 'Stephenie Meyer',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les liaisons dangereuses',
    author: 'Pierre Choderlos de Laclos',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les piliers de la terre',
    author: 'Ken Follett',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Horla',
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 5,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Cyrano de Bergerac',
    author: 'Edmond Rostand',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 4,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Hamlet',
    author: 'William Shakespeare',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Pélléas et Mélisande',
    author: 'Maurice Maeterlinck',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Pierre et Jean',
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Mont-Oriol',
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Fort comme la mort',
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Notre Cœur',
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Maison Tellier',
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Inutile Beauté",
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Au soleil',
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Sur l'eau",
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Vie errante',
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Contes de la bécasse',
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Education sentimentale",
    author: 'Gustave Flaubert',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 3,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Salammbô',
    author: 'Gustave Flaubert',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Trois contes',
    author: 'Gustave Flaubert',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Bouvard et Pécuchet',
    author: 'Gustave Flaubert',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Dictionnaire des idées reçues',
    author: 'Gustave Flaubert',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Thérèse Raquin',
    author: 'Émile Zola',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Fortune des Rougon',
    author: 'Émile Zola',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Curée',
    author: 'Émile Zola',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Ventre de Paris',
    author: 'Émile Zola',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Bête humaine',
    author: 'Émile Zola',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Joyland',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Salem',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Simetierre',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Misery',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Ligne verte',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La peau sur les os',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: '22/11/63',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Docteur Sleep',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Marche ou crève',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 3,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Running man',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Mr. Mercedes',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Carnets noirs',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Fin de ronde',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Père Goriot',
    author: 'Honoré de Balzac',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 2,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "La Fille aux yeux d'or",
    author: 'Honoré de Balzac',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'À rebours',
    author: 'Joris-Karl Huysmans',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 2,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Drageoir aux épices',
    author: 'Joris-Karl Huysmans',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Soirées de Médan',
    author: 'Émile Zola',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Travailleurs de la mer',
    author: 'Victor Hugo',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Ruy Blas',
    author: 'Victor Hugo',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Petits Poèmes en prose',
    author: 'Charles Baudelaire',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 2,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Fleurs du Mal',
    author: 'Charles Baudelaire',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 4,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Fêtes galantes',
    author: 'Paul Verlaine',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 5,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Poèmes saturniens',
    author: 'Paul Verlaine',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Romances sans paroles',
    author: 'Paul Verlaine',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Une saison en enfer',
    author: 'Arthur Rimbaud',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Illuminations',
    author: 'Arthur Rimbaud',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Méditations poétiques',
    author: 'Alphonse de Lamartine',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Diaboliques',
    author: "Barbey d'Aurevilly",
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Amours jaunes',
    author: 'Tristan Corbière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Naissance de la tragédie',
    author: 'Friedrich Nietzsche',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "La Vénus d'Ille",
    author: 'Prosper Mérimée',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Les Crimes de l'amour",
    author: 'Marquis de Sade',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Philosophie dans le boudoir',
    author: 'Marquis de Sade',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Rêveries du promeneur solitaire',
    author: 'Jean-Jacques Rousseau',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Religieuse',
    author: 'Denis Diderot',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Salons',
    author: 'Denis Diderot',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Les Egarements du cœur et de l'esprit",
    author: 'Crébillon fils',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Atala',
    author: 'François-René de Chateaubriand',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Souffrances du jeune Werther',
    author: 'Johann Wolfgang von Goethe',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Manon Lescaut',
    author: 'Abbé Prévost',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Après m'avoir fait tant mourir",
    author: 'Théophile de Viau',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Fables',
    author: 'Jean de La Fontaine',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Amours de Psyché et de Cupidon',
    author: 'Jean de La Fontaine',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Contes',
    author: 'Charles Perrault',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Autre monde",
    author: 'Cyrano de Bergerac',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Médecin volant',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Médecin malgré lui',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'George Dandin',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Avare",
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Dom Juan',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 3,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Médée',
    author: 'Pierre Corneille',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Menteur',
    author: 'Pierre Corneille',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Illusion comique",
    author: 'Pierre Corneille',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Phèdre',
    author: 'Jean Racine',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 4,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Iphigénie',
    author: 'Jean Racine',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Britannicus',
    author: 'Jean Racine',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Bérénice',
    author: 'Jean Racine',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Pour un nouveau roman',
    author: 'Alain Robbe-Grillet',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Gommes',
    author: 'Alain Robbe-Grillet',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Djinn',
    author: 'Alain Robbe-Grillet',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Jalousie',
    author: 'Alain Robbe-Grillet',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Modification',
    author: 'Michel Butor',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Emploi du temps",
    author: 'Michel Butor',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Petite histoire de la littérature française',
    author: 'Michel Butor',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Choses',
    author: 'Georges Perec',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Passacaille',
    author: 'Robert Pinget',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Aurélien',
    author: 'Louis Aragon',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Bestiaire',
    author: 'Guillaume Apollinaire',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Alcools',
    author: 'Guillaume Apollinaire',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Poèmes à Lou',
    author: 'Guillaume Apollinaire',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Calligrammes',
    author: 'Guillaume Apollinaire',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Eau et les Rêves",
    author: 'Gaston Bachelard',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Le degré zéro de l'écriture",
    author: 'Roland Barthes',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Fragments d'un discours amoureux",
    author: 'Roland Barthes',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Autobiographie des objets',
    author: 'François Bon',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 2,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Sortie d'usine",
    author: 'François Bon',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Tous les matins du monde',
    author: 'Pascal Quignard',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Soleils des indépendances',
    author: 'Ahmadou Kourouma',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Allah n'est pas obligé",
    author: 'Ahmadou Kourouma',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Cahier d'un retour au pays natal",
    author: 'Aimé Césaire',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Texaco',
    author: 'Patrick Chamoiseau',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Solibo magnifique',
    author: 'Patrick Chamoiseau',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Pays rêvé, Pays réel',
    author: 'Édouard Glissant',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Lettre à la femme aimée au sujet de la mort',
    author: 'Siméon',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Petite éloge de la poésie',
    author: 'Siméon',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Du côté de chez Swan',
    author: 'Marcel Proust',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Etoile d'Alger",
    author: 'Aziz Chouaki',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Nedjma',
    author: 'Kateb Yacine',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le cercle des représailles',
    author: 'Kateb Yacine',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Pour un oui ou pour un non',
    author: 'Nathalie Sarraute',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Juste la fin du monde',
    author: 'Jean-Luc Lagarce',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Roberto Zucco',
    author: 'Bernard-Marie Koltès',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Ronce-Rose',
    author: 'Éric Chevillard',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Oreille rouge',
    author: 'Éric Chevillard',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Aurais-je été résistant ou bourreau ?',
    author: 'Pierre Bayard',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Huis clos',
    author: 'Jean-Paul Sartre',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Mots',
    author: 'Jean-Paul Sartre',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Je suis un écrivain japonais',
    author: 'Dany Laferrière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Nous, l'Europe banquet des peuples",
    author: 'Laurent Gaudé',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Chien 51',
    author: 'Laurent Gaudé',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Zem',
    author: 'Laurent Gaudé',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Cahier de verdure',
    author: 'Philippe Jaccottet',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 2,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Eupalinos',
    author: 'Paul Valéry',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Connaissance de l'Est",
    author: 'Paul Claudel',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Clair-obscur',
    author: 'Jean Cocteau',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le parti pris des choses',
    author: 'Francis Ponge',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Terre et le sang',
    author: 'Mouloud Feraoun',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Fils du pauvre',
    author: 'Mouloud Feraoun',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Hirondelles de Kaboul',
    author: 'Yasmina Khadra',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Ce que le jour doit à la nuit',
    author: 'Yasmina Khadra',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Attentat",
    author: 'Yasmina Khadra',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Comme un roman',
    author: 'Daniel Pennac',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Fée Carabine',
    author: 'Daniel Pennac',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Des souris et des hommes',
    author: 'John Steinbeck',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Vipère au poing',
    author: 'Hervé Bazin',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Terrienne',
    author: 'Jean-Claude Mourlevat',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Noire – la vie méconnue de Claudette Colvin',
    author: 'Tania de Montaigne',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Ravage',
    author: 'René Barjavel',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Rue Darwin',
    author: 'Boualem Sansal',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Arthur Rimbaud le voleur de feu',
    author: 'Véronique Cohen-Scali',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Ça t'apprendra à vivre",
    author: 'Jeanne Benameur',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Terrier',
    author: 'Franz Kafka',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Peau noire masques blancs',
    author: 'Frantz Fanon',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Je m'en vais",
    author: 'Jean Echenoz',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'En salle',
    author: 'Cécile Baglin',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Et la terre se transmet comme la langue',
    author: 'Mahmoud Darwich',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Gravitations',
    author: 'Jules Supervielle',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Chevaliers du subjonctif',
    author: 'Erik Orsenna',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Grammaire est une chanson douce',
    author: 'Erik Orsenna',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Métamorphoses',
    author: 'Ovide',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Œdipe roi',
    author: 'Sophocle',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Histoire d'un voyage fait en la terre du Brésil",
    author: 'Jean de Léry',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Regrets',
    author: 'Joachim du Bellay',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Adolescence clémentine",
    author: 'Clément Marot',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Journal d'un vampire (tomes 3 à 11)",
    author: 'Lisa J. Smith',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Oscar Pill (tomes 1 à 5)',
    author: 'Eli Anderson',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Assistant du vampire (tomes 1 à 4)",
    author: 'Darren Shan',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Bilbo le Hobbit',
    author: 'J.R.R. Tolkien',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Un amour pour rien',
    author: 'Jean d\'Ormesson',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Bientôt les vivants',
    author: 'Amina Damerdji',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
];
