import { UserBook } from '../../../../models/book-model';

export const marinaBooks: UserBook[] = [
  {
    title: 'Charlie et la Chocolaterie',
    author: 'Roald Dahl',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Dracula',
    author: 'Bram Stoker',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Candide',
    author: 'Voltaire',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Gatsby le magnifique',
    author: 'F. Scott Fitzgerald',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'L\'Odyssée',
    author: 'Homère',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Roméo et Juliette',
    author: 'William Shakespeare',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Don Quichotte',
    author: 'Miguel de Cervantes',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le meilleur des mondes',
    author: 'Aldous Huxley',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Petit Prince',
    author: 'Antoine de Saint-Exupéry',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Un palais d\'épines et de roses',
    author: 'Sarah J. Maas',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les sortceliers',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le livre interdit',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Dans le piège de Magister',
    author: 'Sophie Audouin-Mamikonian',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La peste',
    author: 'Albert Camus',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les fourberies de Scapin',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'L\'avare',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Tartuffe',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Monde de Narnia (Tome 1) Le Neveu du Magicien',
    author: 'C.S. Lewis',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Monde de Narnia (Tome 2) Le Lion, la Sorcière blanche et l\'Armoire magique',
    author: 'C.S. Lewis',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Et ils meurent tous les deux à la fin',
    author: 'Adam Silvera',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Hunger Games',
    author: 'Suzanne Collins',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'L\'Embrasement',
    author: 'Suzanne Collins',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Révolte',
    author: 'Suzanne Collins',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Ballade du serpent et de l\'oiseau chanteur',
    author: 'Suzanne Collins',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Lever de soleil sur la moisson',
    author: 'Suzanne Collins',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Harry Potter à l\'école des sorciers',
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Harry Potter et la Chambre des secrets',
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Harry Potter et le Prisonnier d\'Azkaban',
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Harry Potter et la Coupe de feu',
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Harry Potter et l\'Ordre du Phénix',
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Harry Potter et le Prince de sang-mêlé',
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Harry Potter et les Reliques de la Mort',
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Harry Potter et l\'Enfant maudit',
    author: 'J.K. Rowling',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Fascination',
    author: 'Stephenie Meyer',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Tentation',
    author: 'Stephenie Meyer',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Hésitation',
    author: 'Stephenie Meyer',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Révélation',
    author: 'Stephenie Meyer',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Midnight Sun',
    author: 'Stephenie Meyer',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Voleur de foudre',
    author: 'Rick Riordan',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Mer des monstres',
    author: 'Rick Riordan',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Sort du titan',
    author: 'Rick Riordan',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Bataille du labyrinthe',
    author: 'Rick Riordan',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Dernier Olympien',
    author: 'Rick Riordan',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Labyrinthe',
    author: 'James Dashner',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La femme de ménage',
    author: 'Freida McFadden',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les secrets de la femme de ménage',
    author: 'Freida McFadden',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les Trois Mousquetaires',
    author: 'Alexandre Dumas',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Blackwater I : La crue',
    author: 'Michael McDowell',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Blackwater II : La digue',
    author: 'Michael McDowell',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Blackwater III : La maison',
    author: 'Michael McDowell',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Blackwater IV : La guerre',
    author: 'Michael McDowell',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Blackwater V : La fortune',
    author: 'Michael McDowell',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Blackwater VI : Pluie',
    author: 'Michael McDowell',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Un palais de colère et de brume',
    author: 'Sarah J. Maas',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Un palais de cendres et de ruines',
    author: 'Sarah J. Maas',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Un palais de glace et de lumière',
    author: 'Sarah J. Maas',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Un palais de flammes d\'argent',
    author: 'Sarah J. Maas',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Joyland',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Marche ou crève',
    author: 'Stephen King',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Contes',
    author: 'Charles Perrault',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Dom Juan',
    author: 'Molière',
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
];
