import { BaseComic } from '../../../models/comic-model';

export const baseComics: BaseComic[] = [
  {
    title: 'Watchmen',
    designer: 'Alan Moore',
    writer: 'Alan Moore',
    coverUrl: '/comics_pictures/watchmen.jpg',
    pages: 416,
    genre: 'Super-héros',
  },
  {
    title: "Justice League : Crise d'identité",
    designer: 'Brad Meltzer - Rags Morales',
    writer: 'Brad Meltzer - Rags Morales',
    coverUrl: '/comics_pictures/justice-league-crise-d-rsquo-identite.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: "Justice League : La Ligue de Justice d'Amérique",
    designer: 'Johns - Kindt - Finch',
    writer: 'Johns - Kindt - Finch',
    coverUrl: '/comics_pictures/81UBDmKsKIL._UF1000,1000_QL80_.jpg',
    genre: 'Super-héros',
    pages: 0,
  },
  {
    title: 'Justice League : La Guerre des Ligues',
    designer: 'Johns - Lemire - Reis - Mahnke',
    writer: 'Johns - Lemire - Reis - Mahnke',
    coverUrl: '/comics_pictures/Couv_226147.jpg',
    pages: 296,
    genre: 'Super-héros',
  },
  {
    title: 'Justice League : Le Règne du Mal - 1re partie',
    designer: 'Johns - Finch - Reis - Mahnke',
    writer: 'Johns - Finch - Reis - Mahnke',
    coverUrl: '/comics_pictures/Couv_229800.jpg',
    pages: 224,
    genre: 'Super-héros',
  },
  {
    title: 'Justice League : Le Règne du Mal - 2e partie',
    designer: 'Johns - Finch - Reis - Mahnke',
    writer: 'Johns - Finch - Reis - Mahnke',
    coverUrl: '/comics_pictures/Couv_234873.jpg',
    pages: 208,
    genre: 'Super-héros',
  },
  {
    title: "Justice League : La Ligue d'Injustice",
    designer: 'Johns - Fabok - Reis - Mahnke',
    writer: 'Johns - Fabok - Reis - Mahnke',
    coverUrl: '/comics_pictures/Couv_258120.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Justice League : La Guerre de Darkseid - 1re partie',
    designer: 'Johns - Fabok',
    writer: 'Johns - Fabok',
    coverUrl: '/comics_pictures/Couv_392549.jpg',
    pages: 144,
    genre: 'Super-héros',
  },
  {
    title: 'Justice League : La Guerre de Darkseid - 2e partie',
    designer: 'Johns - Fabok - Manapul',
    writer: 'Johns - Fabok - Manapul',
    coverUrl: '/comics_pictures/Couv_290427.jpg',
    pages: 200,
    genre: 'Super-héros',
  },
  {
    title: 'Superman : Requiem',
    designer: 'Peter J. Tomasi - Mikel Janin - Doug Mahnke',
    writer: 'Peter J. Tomasi - Mikel Janin - Doug Mahnke',
    coverUrl: '/comics_pictures/superman-8211-requiem.jpg',
    pages: 200,
    genre: 'Super-héros',
  },
  {
    title: 'Superman : Président Lex Luthor',
    designer: 'DeMatteis - Kelly - Loeb - Schultz',
    writer: 'DeMatteis - Kelly - Loeb - Schultz',
    coverUrl:
      '/comics_pictures/superman-president-lex-luthor-8211-edition-speciale-fnac.jpg',
    pages: 264,
    genre: 'Super-héros',
  },
  {
    title: 'Red Son',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/superman-red-son-edition-black-label.jpg',
    pages: 144,
    genre: 'Super-héros',
  },
  {
    title: 'Brisé',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_257713.jpg',
    pages: 112,
    genre: 'Super-héros',
  },
  {
    title: 'Amère Victoire - 1re partie',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_422741.jpg',
    pages: 204,
    genre: 'Super-héros',
  },
  {
    title: 'Amère Victoire - 2e partie',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_425400.jpg',
    pages: 204,
    genre: 'Super-héros',
  },
  {
    title: "L'autre terre",
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/autre-terre-tome-1.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'À Rome...',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_222294.jpg',
    pages: 160,
    genre: 'Super-héros',
  },
  {
    title: 'Pour demain - 1re partie',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_289242.jpg',
    pages: 160,
    genre: 'Super-héros',
  },
  {
    title: 'Pour demain - 2e partie',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_291173.jpg',
    pages: 176,
    genre: 'Super-héros',
  },
  {
    title: 'La splendeur du Pingouin',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/la-splendeur-du-pingouin.jpg',
    pages: 144,
    genre: 'Super-héros',
  },
  {
    title: "L'odyssée du mal",
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/91iFXgr4tjL._AC_UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Un deuil dans la famille',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/batman-un-deuil-dans-la-famille.jpg',
    pages: 296,
    genre: 'Super-héros',
  },
  {
    title: 'Aux origines',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/30_9782365770439_1_75.jpg',
    pages: 176,
    genre: 'Super-héros',
  },
  {
    title: 'Couple mythique',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_276636.jpg',
    pages: 148,
    genre: 'Super-héros',
  },
  {
    title: 'Légendes',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Le deuil de la famille',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/batman-tome-3-le-deuil-de-la-famille.jpg',
    pages: 164,
    genre: 'Super-héros',
  },
  {
    title: 'La mort de Superman',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/412mQSGSUaL._AC_UF1000,1000_QL80_.jpg',
    pages: 528,
    genre: 'Super-héros',
  },
  {
    title: 'Pièges et trapèzes',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_175489.jpg',
    pages: 160,
    genre: 'Super-héros',
  },
  {
    title: "D'entre les ombres",
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_301744.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'La révolte des lascars',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_245351.jpg',
    pages: 176,
    genre: 'Super-héros',
  },
  {
    title: 'Brainiac',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl:
      '/comics_pictures/superman-brainiac-8211-edition-speciale-fnac.jpg',
    pages: 128,
    genre: 'Super-héros',
  },
  {
    title: "Les patients d'Arkham",
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/les-patients-d-rsquo-arkham.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Guerre au gorille',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_255397.jpg',
    pages: 160,
    genre: 'Super-héros',
  },
  {
    title: "Le trône d'Atlantide",
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_214887.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'La balade de Lobo',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/balade-de-lobo-la.jpg',
    pages: 208,
    genre: 'Super-héros',
  },
  {
    title: 'Sur la route',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/bdg-306514_1_75.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'La République de demain',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/s-l1200.jpg',
    pages: 160,
    genre: 'Super-héros',
  },
  {
    title: 'Luthor',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/912fD3KZUiL.jpg',
    pages: 144,
    genre: 'Super-héros',
  },
  {
    title: 'Dans les bas-fonds',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_311835.jpg',
    pages: 144,
    genre: 'Super-héros',
  },
  {
    title: 'Green Arrow - Année Un',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/green-arrow-annee-un.jpg',
    pages: 160,
    genre: 'Super-héros',
  },
  {
    title: 'Killing Joke',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/killing-joke.jpg',
    pages: 72,
    genre: 'Super-héros',
  },
  {
    title: 'Machine à tuer',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_220903.jpg',
    pages: 208,
    genre: 'Super-héros',
  },
  {
    title: 'Origines secrètes',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/superman-origines-secretes-2009.jpg',
    pages: 232,
    genre: 'Super-héros',
  },
  {
    title: 'Année un',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/batman-annee-un.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Un long Halloween - 1re partie',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_421406.jpg',
    pages: 204,
    genre: 'Super-héros',
  },
  {
    title: 'Un long Halloween - 2e partie',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_278424.jpg',
    pages: 204,
    genre: 'Super-héros',
  },
  {
    title: 'Année un - 1re partie',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/injustice-annee-un-1ere-partie.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Année un - 2e partie',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_279860.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Robin - Année Un',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/robin-annee-un.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'La naissance du démon',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_281595.jpg',
    pages: 194,
    genre: 'Super-héros',
  },
  {
    title: "L'odyssée - 1re partie",
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_283165.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: "L'odyssée - 2e partie",
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_283166.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'La fille de Batman',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Élégie',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_311072.jpg',
    pages: 240,
    genre: 'Super-héros',
  },
  {
    title: 'La revanche de Bane',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/batman-la-revanche-de-bane.jpg',
    pages: 160,
    genre: 'Super-héros',
  },
  {
    title: 'Dieux et mortels',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/wonder-woman-dieux-et-mortels-tome-1.jpg',
    pages: 384,
    genre: 'Super-héros',
  },
  {
    title: 'Kingdom Come',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/kingdom-come-8212-nouvelle-edition.jpg',
    pages: 336,
    genre: 'Super-héros',
  },
  {
    title: 'Peur abyssale',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_173354.jpg',
    pages: 144,
    genre: 'Super-héros',
  },
  {
    title: 'Rassemblement',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_242962.jpg',
    pages: 232,
    genre: 'Super-héros',
  },
  {
    title: 'Secrets et origines',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Cité brisée',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/batman-cite-brisee.jpg',
    pages: 264,
    genre: 'Super-héros',
  },
  {
    title: 'Complètement marteau',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_250811.jpg',
    pages: 232,
    genre: 'Super-héros',
  },
  {
    title: 'Empereur Joker - 1re partie',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/Couv_319753.jpg',
    pages: 128,
    genre: 'Super-héros',
  },
  {
    title: 'Empereur Joker - 2e partie',
    designer: 'DC Comics',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/1163577522_L.avif',
    pages: 128,
    genre: 'Super-héros',
  },
  {
    title: 'Transmetropolitan - Tome 1',
    designer: 'Warren Ellis - Darick Robertson',
    writer: 'Warren Ellis - Darick Robertson',
    coverUrl: '/comics_pictures/transmetropolitan-tome-1.jpg',
    pages: 300,
    genre: 'Super-héros',
  },
  {
    title: 'Transmetropolitan - Tome 2',
    designer: 'Warren Ellis - Darick Robertson',
    writer: 'Warren Ellis - Darick Robertson',
    coverUrl: '/comics_pictures/transmetropolitan-tome-2.jpg',
    pages: 320,
    genre: 'Super-héros',
  },
  {
    title: 'Transmetropolitan - Tome 3',
    designer: 'Warren Ellis - Darick Robertson',
    writer: 'Warren Ellis - Darick Robertson',
    coverUrl: '/comics_pictures/transmetropolitan-tome-3.jpg',
    pages: 296,
    genre: 'Super-héros',
  },
  {
    title: 'Transmetropolitan - Tome 4',
    designer: 'Warren Ellis - Darick Robertson',
    writer: 'Warren Ellis - Darick Robertson',
    coverUrl:
      '/comics_pictures/urban-comics-nomad-transmetropolitan-tome-4.jpg',
    pages: 296,
    genre: 'Super-héros',
  },
  {
    title: 'Transmetropolitan - Tome 5',
    designer: 'Warren Ellis - Darick Robertson',
    writer: 'Warren Ellis - Darick Robertson',
    coverUrl: '/comics_pictures/transmetropolitan-tome-5.jpg',
    pages: 400,
    genre: 'Super-héros',
  },
  {
    title: 'Y, le Dernier Homme - Tome 1',
    designer: 'Brian K. Vaughan - Pia Guerra',
    writer: 'Brian K. Vaughan - Pia Guerra',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 256,
    genre: 'Super-héros',
  },
  {
    title: 'Y, le Dernier Homme - Tome 2',
    designer: 'Brian K. Vaughan - Pia Guerra',
    writer: 'Brian K. Vaughan - Pia Guerra',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 256,
    genre: 'Super-héros',
  },
  {
    title: 'Y, le Dernier Homme - Tome 3',
    designer: 'Brian K. Vaughan - Pia Guerra',
    writer: 'Brian K. Vaughan - Pia Guerra',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 256,
    genre: 'Super-héros',
  },
  {
    title: 'Y, le Dernier Homme - Tome 4',
    designer: 'Brian K. Vaughan - Pia Guerra',
    writer: 'Brian K. Vaughan - Pia Guerra',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 256,
    genre: 'Super-héros',
  },
  {
    title: 'Y, le Dernier Homme - Tome 5',
    designer: 'Brian K. Vaughan - Pia Guerra',
    writer: 'Brian K. Vaughan - Pia Guerra',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 256,
    genre: 'Super-héros',
  },
  {
    title: 'Y, le Dernier Homme - Tome 6',
    designer: 'Brian K. Vaughan - Pia Guerra',
    writer: 'Brian K. Vaughan - Pia Guerra',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 256,
    genre: 'Super-héros',
  },
  {
    title: 'Fables - Tome 1',
    designer: 'Bill Willingham - Mark Buckingham',
    writer: 'Bill Willingham - Mark Buckingham',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Fables - Tome 2',
    designer: 'Bill Willingham - Mark Buckingham',
    writer: 'Bill Willingham - Mark Buckingham',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 432,
    genre: 'Super-héros',
  },
  {
    title: 'Fables - Tome 3',
    designer: 'Bill Willingham - Mark Buckingham',
    writer: 'Bill Willingham - Mark Buckingham',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 432,
    genre: 'Super-héros',
  },
  {
    title: 'Fables - Tome 4',
    designer: 'Bill Willingham - Mark Buckingham',
    writer: 'Bill Willingham - Mark Buckingham',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 432,
    genre: 'Super-héros',
  },
  {
    title: 'Fables - Tome 5',
    designer: 'Bill Willingham - Mark Buckingham',
    writer: 'Bill Willingham - Mark Buckingham',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 432,
    genre: 'Super-héros',
  },
  {
    title: 'Preacher - Tome 1',
    designer: 'Garth Ennis - Steve Dillon',
    writer: 'Garth Ennis - Steve Dillon',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 392,
    genre: 'Super-héros',
  },
  {
    title: 'Preacher - Tome 2',
    designer: 'Garth Ennis - Steve Dillon',
    writer: 'Garth Ennis - Steve Dillon',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 392,
    genre: 'Super-héros',
  },
  {
    title: 'Preacher - Tome 3',
    designer: 'Garth Ennis - Steve Dillon',
    writer: 'Garth Ennis - Steve Dillon',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 392,
    genre: 'Super-héros',
  },
  {
    title: 'Preacher - Tome 4',
    designer: 'Garth Ennis - Steve Dillon',
    writer: 'Garth Ennis - Steve Dillon',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 392,
    genre: 'Super-héros',
  },
  {
    title: 'Batman White Knight',
    designer: 'Sean Murphy',
    writer: 'Sean Murphy',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 240,
    genre: 'Super-héros',
  },
  {
    title: 'Top 10',
    designer: 'Alan Moore - Gene Ha - Zander Cannon',
    writer: 'Alan Moore - Gene Ha - Zander Cannon',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Les seigneurs de Bagdad',
    designer: 'Garth Ennis - Brian K. Vaughan - Niko Henrichon',
    writer: 'Garth Ennis - Brian K. Vaughan - Niko Henrichon',
    coverUrl:
      '/comics_pictures/testurban-comics-nomad-les-seigneurs-de-bagdad.jpg',
    pages: 144,
    genre: 'Super-héros',
  },
  {
    title: 'Hellblazer : Dépendance mortelle',
    designer: 'Garth Ennis - William Simpson',
    writer: 'Garth Ennis - William Simpson',
    coverUrl:
      '/comics_pictures/urban-comics-nomad-hellblazer-dependance-mortelle-garth-ennis.jpg',
    pages: 416,
    genre: 'Super-héros',
  },
  {
    title: 'All-Star Superman',
    designer: 'Grant Morrison - Frank Quitely',
    writer: 'Grant Morrison - Frank Quitely',
    coverUrl: '/comics_pictures/all-star-superman.jpg',
    pages: 300,
    genre: 'Super-héros',
  },
  {
    title: 'Superman : Up in the Sky',
    designer: 'Tom King - Andy Kubert',
    writer: 'Tom King - Andy Kubert',
    coverUrl: '/comics_pictures/81oWRTbEIaL._AC_UF1000,1000_QL80_.jpg',
    pages: 184,
    genre: 'Super-héros',
  },
  {
    title: 'Superman : Écrase le Klan',
    designer: 'Gene Luen Yang - Gurihiru',
    writer: 'Gene Luen Yang - Gurihiru',
    coverUrl: '/comics_pictures/superman-ecrase-le-klan.jpg',
    pages: 248,
    genre: 'Super-héros',
  },
  {
    title: 'Superman : Les Origines',
    designer: 'Mark Waid - Leinil Francis Yu',
    writer: 'Mark Waid - Leinil Francis Yu',
    coverUrl: '/comics_pictures/superman-les-origines.jpg',
    pages: 352,
    genre: 'Super-héros',
  },
  {
    title: 'Superman : American Alien',
    designer: 'Max Landis',
    writer: 'Max Landis',
    coverUrl: '/comics_pictures/superman-american-alien-nomad.jpg',
    pages: 224,
    genre: 'Super-héros',
  },
  {
    title: 'Batman : Tueur né',
    designer: 'Peter J. Tomasi - Patrick Gleason',
    writer: 'Peter J. Tomasi - Patrick Gleason',
    coverUrl:
      '/comics_pictures/urban-comics-nomad-batman-amp-robin-8211-tueur-ne.jpg',
    pages: 208,
    genre: 'Super-héros',
  },
  {
    title: 'DCeased',
    designer: 'Tom Taylor - Trevor Hairsine - Stefano Gaudiano',
    writer: 'Tom Taylor - Trevor Hairsine - Stefano Gaudiano',
    coverUrl: '/comics_pictures/dceased.jpg',
    pages: 224,
    genre: 'Super-héros',
  },
  {
    title: 'Mister Miracle',
    designer: 'Tom King - Mitch Gerads',
    writer: 'Tom King - Mitch Gerads',
    coverUrl: '/comics_pictures/81H792QVGgL.jpg',
    pages: 320,
    genre: 'Super-héros',
  },
  {
    title: 'Fables - Tome 6',
    designer: 'Bill Willingham - Mark Buckingham',
    writer: 'Bill Willingham - Mark Buckingham',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 432,
    genre: 'Fantastique',
  },
  {
    title: 'Fables - Tome 7',
    designer: 'Bill Willingham - Mark Buckingham',
    writer: 'Bill Willingham - Mark Buckingham',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 432,
    genre: 'Fantastique',
  },
  {
    title: 'Fables - Tome 8',
    designer: 'Bill Willingham - Mark Buckingham',
    writer: 'Bill Willingham - Mark Buckingham',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 432,
    genre: 'Fantastique',
  },
  {
    title: 'Fables - Tome 9',
    designer: 'Bill Willingham - Mark Buckingham',
    writer: 'Bill Willingham - Mark Buckingham',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 432,
    genre: 'Fantastique',
  },
  {
    title: 'Flashpoint : Édition 10 ans',
    designer: 'Geoff Johns - Andy Kubert',
    writer: 'Geoff Johns - Andy Kubert',
    coverUrl: '/comics_pictures/flashpoint-edition-10-ans.jpg',
    pages: 176,
    genre: 'Super-héros',
  },
  {
    title: "Batman : L'énigme de Red Hood",
    designer: 'Judd Winick - Shane Davis - Jeremy Haun',
    writer: 'Judd Winick - Shane Davis - Jeremy Haun',
    coverUrl: '/comics_pictures/batman-8211-l-rsquo-enigme-de-red-hood.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Absolute Superman',
    designer: 'Jason Aaron - Rafa Sandoval',
    writer: 'Jason Aaron - Rafa Sandoval',
    coverUrl: '/comics_pictures/absolute-superman-tome-1.jpg',
    pages: 144,
    genre: 'Super-héros',
  },
  {
    title: 'Absolute Batman',
    designer: 'Scott Snyder - Nick Dragotta',
    writer: 'Scott Snyder - Nick Dragotta',
    coverUrl:
      '/comics_pictures/absolute-batman-tome-1-edition-pulp-rsquo-s.jpg',
    pages: 184,
    genre: 'Super-héros',
  },
  {
    title: 'Absolute Justice League Unlimited',
    designer: 'Mark Waid - Dan Mora',
    writer: 'Mark Waid - Dan Mora',
    coverUrl: '/comics_pictures/justice-league-unlimited-tome-1.jpg',
    pages: 160,
    genre: 'Super-héros',
  },
  {
    title: 'Superman : Dark Prophecy',
    designer: 'Joshua Williamson - Dan Mora',
    writer: 'Joshua Williamson - Dan Mora',
    coverUrl: '/comics_pictures/superman-dark-prophecy-tome-1.jpg',
    pages: 352,
    genre: 'Super-héros',
  },
  {
    title: 'Crisis on Infinite Earths',
    designer: 'Marv Wolfman - George Perez',
    writer: 'Marv Wolfman - George Perez',
    coverUrl: '/comics_pictures/81AH2uqPEOL._AC_UF1000,1000_QL80_.jpg',
    pages: 544,
    genre: 'Super-héros',
  },
  {
    title: 'Supergirl : Woman of Tomorrow',
    designer: 'Tom King - Bilquis Evely',
    writer: 'Tom King - Bilquis Evely',
    coverUrl: '/comics_pictures/supergirl-woman-of-tomorrow-tp-168602.webp',
    pages: 224,
    genre: 'Super-héros',
  },
  {
    title: 'Superman : Lost',
    designer: 'Christopher Priest - Carlo Pagulayan',
    writer: 'Christopher Priest - Carlo Pagulayan',
    coverUrl: '/comics_pictures/superman-lost.jpg',
    pages: 248,
    genre: 'Super-héros',
  },
  {
    title: 'Dark Knights of Steel : Au loin',
    designer: 'Tom Taylor - Yasmine Putri',
    writer: 'Tom Taylor - Yasmine Putri',
    coverUrl: '/comics_pictures/album-cover-large-52610.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Dark Knights of Steel : La guerre des trois royaumes',
    designer: 'Tom Taylor - Yasmine Putri',
    writer: 'Tom Taylor - Yasmine Putri',
    coverUrl: '/comics_pictures/Couv_497600.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Dark Knights of Steel : Allwinter',
    designer: 'Kristoff - Tirso',
    writer: 'Kristoff - Tirso',
    coverUrl: '/comics_pictures/dark-knights-of-steel-allwinter.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Joker : The Winning Card',
    designer: 'Tom King - Mitch Gerads',
    writer: 'Tom King - Mitch Gerads',
    coverUrl: '/comics_pictures/joker-the-winning-card.jpg',
    pages: 112,
    genre: 'Super-héros',
  },
  {
    title: 'Batman : Damned',
    designer: 'Brian Azzarello - Lee Bermejo',
    writer: 'Brian Azzarello - Lee Bermejo',
    coverUrl: '/comics_pictures/81kN2LAxV5L._AC_UF1000,1000_QL80_.jpg',
    pages: 176,
    genre: 'Super-héros',
  },
  {
    title: 'DC Universe Rebirth',
    designer: 'Geoff Johns',
    writer: 'Geoff Johns',
    coverUrl: '/comics_pictures/dc-univers-rebirth.jpg',
    pages: 592,
    genre: 'Super-héros',
  },
  {
    title: 'Batman : Trois Jokers',
    designer: 'Geoff Johns - Jason Fabok',
    writer: 'Geoff Johns - Jason Fabok',
    coverUrl: '/comics_pictures/trois-jokers.jpg',
    pages: 176,
    genre: 'Super-héros',
  },
  {
    title: 'Batman : Imposter',
    designer: 'Mattson Tomlin - Andrea Sorrentino',
    writer: 'Mattson Tomlin - Andrea Sorrentino',
    coverUrl: '/comics_pictures/batman-imposter.jpg',
    pages: 176,
    genre: 'Super-héros',
  },
  {
    title: 'Batman Rebirth - Tome 1',
    designer: 'Tom King - David Finch',
    writer: 'Tom King - David Finch',
    coverUrl: '/comics_pictures/batman-rebirth-1.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Batman Rebirth - Tome 2',
    designer: 'Tom King - Mikel Janin - Mitch Gerads',
    writer: 'Tom King - Mikel Janin - Mitch Gerads',
    coverUrl: '/comics_pictures/9791026810940_1_75.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Batman Metal - Tome 1',
    designer: 'Scott Snyder - Greg Capullo - John Romita Jr. - Lee',
    writer: 'Scott Snyder - Greg Capullo - John Romita Jr. - Lee',
    coverUrl: '/comics_pictures/batman-metal-tome-1.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Batman Metal - Tome 2',
    designer: 'Scott Snyder - Greg Capullo - Mikel Janin',
    writer: 'Scott Snyder - Greg Capullo - Mikel Janin',
    coverUrl: '/comics_pictures/batman-metal-tome-2.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Batman Noël',
    designer: 'Lee Bermejo',
    writer: 'Lee Bermejo',
    coverUrl: '/comics_pictures/71wO+4XWvaL._AC_UF1000,1000_QL80_.jpg',
    pages: 112,
    genre: 'Super-héros',
  },
  {
    title: 'Batman : Le cœur de silence',
    designer: 'Paul Dini - Dustin Nguyen',
    writer: 'Paul Dini - Dustin Nguyen',
    coverUrl: '/comics_pictures/81QDOwXimKL._AC_UF1000,1000_QL80_.jpg',
    pages: 184,
    genre: 'Super-héros',
  },
  {
    title: 'Batman : Terre-un',
    designer: 'Geoff Johns - Gary Frank',
    writer: 'Geoff Johns - Gary Frank',
    coverUrl: '/comics_pictures/batman-terre-1.jpg',
    pages: 464,
    genre: 'Super-héros',
  },
  {
    title: 'Batman : Sombre reflet',
    designer: 'Scott Snyder - Jock',
    writer: 'Scott Snyder - Jock',
    coverUrl: '/comics_pictures/Urban-Comics-Nomad-Batman-Sombre-Reflet.jpg',
    pages: 296,
    genre: 'Super-héros',
  },
  {
    title: 'Batman : Année Zéro',
    designer: 'Scott Snyder - Greg Capullo',
    writer: 'Scott Snyder - Greg Capullo',
    coverUrl: '/comics_pictures/batman-annee-zero.jpg',
    pages: 400,
    genre: 'Super-héros',
  },
  {
    title: 'Batman : Curse of the White Knight',
    designer: 'Sean Murphy',
    writer: 'Sean Murphy',
    coverUrl: '/comics_pictures/batman-8211-curse-of-the-white-knight.jpg',
    pages: 272,
    genre: 'Super-héros',
  },
  {
    title: 'Green Lantern - Tome 1',
    designer: 'Geoff Johns - Ivan Reis',
    writer: 'Geoff Johns - Ivan Reis',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Green Lantern - Tome 2',
    designer: 'Geoff Johns - Ivan Reis',
    writer: 'Geoff Johns - Ivan Reis',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Green Lantern - Tome 3',
    designer: 'Geoff Johns - Ivan Reis',
    writer: 'Geoff Johns - Ivan Reis',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Batman Anthologie',
    designer: 'Collectif',
    writer: 'Collectif',
    coverUrl: '/comics_pictures/batman-anthologie.jpg',
    pages: 368,
    genre: 'Super-héros',
  },
  {
    title: 'DC Comics Anthologie',
    designer: 'Collectif',
    writer: 'Collectif',
    coverUrl: '/comics_pictures/dc-comics-anthologie.jpg',
    pages: 288,
    genre: 'Super-héros',
  },
  {
    title: 'Batman Beyond : The White Knight',
    designer: 'Sean Murphy',
    writer: 'Sean Murphy',
    coverUrl: '/comics_pictures/batman-beyond-the-white-knight.jpg',
    pages: 264,
    genre: 'Super-héros',
  },
  {
    title: 'Batman : Bane',
    designer: 'David Finch, Mikel Janin',
    writer: 'Tom King',
    coverUrl: '/comics_pictures/batman-vs-bane.jpg',
    pages: 224,
    genre: 'Super-héros',
  },
  {
    title: 'Batman : Deathstroke',
    designer: 'Carlo Pagulayan',
    writer: 'Christopher Priest',
    coverUrl: '/comics_pictures/batman-vs-deathstroke.jpg',
    pages: 200,
    genre: 'Super-héros',
  },
  {
    title: 'Batman : Le Pingouin',
    designer: 'Jayson Fabok',
    writer: 'John Layman',
    coverUrl: '/comics_pictures/batman-vs-le-pingouin.jpg',
    pages: 240,
    genre: 'Super-héros',
  },
  {
    title: "Batman : L'asile d'Arkham",
    designer: 'Ryan Sook',
    writer: 'Dan Slott',
    coverUrl: '/comics_pictures/9791026827269_1_75.jpg',
    pages: 144,
    genre: 'Super-héros',
  },
  {
    title: 'Joker : Mauvaises fréquentations',
    designer: 'Lee Bermejo, Doug Mahnke',
    writer: 'Brian Azzarello, Ed Brubaker',
    coverUrl: '/comics_pictures/joker-8211-mauvaises-frequentations.jpg',
    pages: 192,
    genre: 'Super-héros',
  },
  {
    title: 'Harley Quinn Rebirth',
    designer: 'John Timms',
    writer: 'Amanda Conner, Jimmy Palmiotti',
    coverUrl: '/comics_pictures/harley-quinn-rebirth.jpg',
    pages: 224,
    genre: 'Super-héros',
  },
  {
    title: 'Les sirènes de Gotham',
    designer: 'Guillem March',
    writer: 'Paul Dini',
    coverUrl: '/comics_pictures/les-sirenes-de-gotham.jpg',
    pages: 192,
    genre: 'Super-héros',
  },
  {
    title: 'Justice League : Forever Evil',
    designer: 'David Finch, Ivan Reis',
    writer: 'Geoff Johns',
    coverUrl: '/comics_pictures/justice-league-forever-evil.jpg',
    pages: 424,
    genre: 'Super-héros',
  },
  {
    title: 'Suicide Squad Rebirth',
    designer: 'Jim Lee',
    writer: 'Rob Williams',
    coverUrl: '/comics_pictures/suicide-squad-rebirth.jpg',
    pages: 200,
    genre: 'Super-héros',
  },
  {
    title: 'Justice League vs Suicide Squad',
    designer: 'Jayson Fabok, Tony Daniel',
    writer: 'Joshua Williamson',
    coverUrl: '/comics_pictures/justice-league-vs-suicide-squad.jpg',
    pages: 272,
    genre: 'Super-héros',
  },
  {
    title: 'Superman Anthologie',
    designer: 'Collectif',
    writer: 'Collectif',
    coverUrl: '/comics_pictures/superman-anthologie.jpg',
    pages: 320,
    genre: 'Super-héros',
  },
  {
    title: 'Superman : Identité secrète',
    designer: 'Kurt Busiek - Stuart Immonen',
    writer: 'Kurt Busiek - Stuart Immonen',
    coverUrl: '/comics_pictures/superman-identite-secrete.jpg',
    pages: 208,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man',
    designer: 'J. Michael Straczynski - John Romita Jr.',
    writer: 'J. Michael Straczynski - John Romita Jr.',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : Bleu',
    designer: 'Jeph Loeb - Tim Sale',
    writer: 'Jeph Loeb - Tim Sale',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Venom : Rex',
    designer: 'Mike Costa - Gerardo Sandoval',
    writer: 'Mike Costa - Gerardo Sandoval',
    coverUrl: '/comics_pictures/81fKW3DNYEL.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Wolverine : Les origines',
    designer: 'Paul Jenkins - Andy Kubert',
    writer: 'Paul Jenkins - Andy Kubert',
    coverUrl: '/comics_pictures/Wolverine-les-origines.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Thor : La déesse du tonnerre',
    designer: 'Jason Aaron - Russell Dauterman',
    writer: 'Jason Aaron - Russell Dauterman',
    coverUrl: '/comics_pictures/Couv_453769.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Ultimates : Super-humain',
    designer: 'Mark Millar - Bryan Hitch',
    writer: 'Mark Millar - Bryan Hitch',
    coverUrl: '/comics_pictures/9782809499278_1_75.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Thanos : Thanos gagne',
    designer: 'Donny Cates - Geoff Shaw',
    writer: 'Donny Cates - Geoff Shaw',
    coverUrl: '/comics_pictures/8103CpXxHuL._AC_UF1000,1000_QL80_.jpg',
    pages: 184,
    genre: 'Super-héros',
  },
  {
    title: 'Immortal Hulk : Ou est-il des deux ?',
    designer: 'Al Ewing - Joe Bennett',
    writer: 'Al Ewing - Joe Bennett',
    coverUrl: '/comics_pictures/1507-1.jpg',
    pages: 128,
    genre: 'Super-héros',
  },
  {
    title: 'Captain Marvel : La vie de Captain Marvel',
    designer: 'Kelly Thompson - Carmen Carnero',
    writer: 'Kelly Thompson - Carmen Carnero',
    coverUrl: '/comics_pictures/81Ti-OJv84L._AC_UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Hawkeye : Ma vie est une arme',
    designer: 'Matt Fraction - David Aja',
    writer: 'Matt Fraction - David Aja',
    coverUrl: '/comics_pictures/34_9782809499315_1_75.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Daredevil : Jaune',
    designer: 'Jeph Loeb - Tim Sale',
    writer: 'Jeph Loeb - Tim Sale',
    coverUrl: '/comics_pictures/daredevil-jaune-must-have.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Cosmic Ghost Rider : Bébé Thanos doit mourir',
    designer: 'Donny Cates - Dylan Burnett',
    writer: 'Donny Cates - Dylan Burnett',
    coverUrl: '/comics_pictures/46_9791039115605_1_75.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Deadpool : Massacre',
    designer: 'Cullen Bunn - Dalibor Talajic',
    writer: 'Cullen Bunn - Dalibor Talajic',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Marvel Zombies : La famine',
    designer: 'Robert Kirkman - Sean Phillips',
    writer: 'Robert Kirkman - Sean Phillips',
    coverUrl: '/comics_pictures/71n-NKeWz3L._AC_UF894,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: "Spider-Man : L'empire",
    designer: 'Kaare Andrews',
    writer: 'Kaare Andrews',
    coverUrl: '/comics_pictures/spider-man-reign-marvel-multiverse.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : Spider-Geddon',
    designer: 'Christos Gage - Jorge Molina',
    writer: 'Christos Gage - Jorge Molina',
    coverUrl: '/comics_pictures/spider-geddon-marvel-multiverse.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Avengers : Les origines',
    designer: 'Joe Casey - Phil Noto',
    writer: 'Joe Casey - Phil Noto',
    coverUrl: '/comics_pictures/71Ww2qOe9zL._AC_UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Avengers : Les nuits de Wundagore',
    designer: 'Collectif',
    writer: 'Collectif',
    coverUrl:
      '/comics_pictures/les-nuits-de-wundagore-avengers-anniversaire.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Avengers : État de siège',
    designer: 'Brian Michael Bendis - Olivier Coipel',
    writer: 'Brian Michael Bendis - Olivier Coipel',
    coverUrl: '/comics_pictures/81IGmr3cZaL._AC_UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Avengers : Ultron Unlimited',
    designer: 'Kurt Busiek - George Perez',
    writer: 'Kurt Busiek - George Perez',
    coverUrl: '/comics_pictures/avengers-ultron-unlimited-must-have.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Avengers : Dark Avengers',
    designer: 'Brian Michael Bendis - Mike Deodato Jr.',
    writer: 'Brian Michael Bendis - Mike Deodato Jr.',
    coverUrl: '/comics_pictures/71zg80WW9IL._AC_UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Avengers : Le monde des Avengers',
    designer: 'Collectif',
    writer: 'Collectif',
    coverUrl: '/comics_pictures/81HpuMhV-eL._AC_UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: "Captain America : Le soldat de l'hiver",
    designer: 'Ed Brubaker - Steve Epting',
    writer: 'Ed Brubaker - Steve Epting',
    coverUrl: '/comics_pictures/captain-america-le-soldat-de-l-hiver.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Les Gardiens de la Galaxie',
    designer: 'Brian Michael Bendis - Steve McNiven',
    writer: 'Brian Michael Bendis - Steve McNiven',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Thor : Renaissance',
    designer: 'J. Michael Straczynski - Olivier Coipel',
    writer: 'J. Michael Straczynski - Olivier Coipel',
    coverUrl: '/comics_pictures/thor-renaissance-must-have.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Thanos : La quête de Thanos',
    designer: 'Jim Starlin - Ron Lim',
    writer: 'Jim Starlin - Ron Lim',
    coverUrl: '/comics_pictures/917392BsdxL._AC_UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Venom vs Carnage : Un enfant est né',
    designer: 'Peter Milligan - Clayton Crain',
    writer: 'Peter Milligan - Clayton Crain',
    coverUrl: '/comics_pictures/81EYeE5evbL._AC_UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Deadpool : Il faut soigner le soldat Wilson',
    designer: 'Gerry Duggan - Brian Posehn - Declan Shalvey',
    writer: 'Gerry Duggan - Brian Posehn - Declan Shalvey',
    coverUrl:
      '/comics_pictures/deadpool-il-faut-soigner-le-soldat-wilson-deluxe.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: "Wolverine : L'arme X",
    designer: 'Barry Windsor-Smith',
    writer: 'Barry Windsor-Smith',
    coverUrl:
      '/comics_pictures/wolverine-l-arme-x-autres-histoires-marvel-poche.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: "Spider-Man : N'est plus !",
    designer: 'Stan Lee - John Romita',
    writer: 'Stan Lee - John Romita',
    coverUrl:
      '/comics_pictures/Spider-Man-T01-Spider-Man-n-est-plus-La-collection-anniversaire-2022.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : La saga du Rédempteur',
    designer: 'Sal Buscema, Rich Buckler',
    writer: 'Peter David',
    coverUrl: '/comics_pictures/43_9791039106160_1_75.jpg',
    pages: 176,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : La naissance de Venom',
    designer: 'David Michelinie - Todd McFarlane',
    writer: 'David Michelinie - Todd McFarlane',
    coverUrl: '/comics_pictures/31_9791039106184_1_75.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : Révélations',
    designer: 'Romita Jr., John',
    writer: 'Straczynski, Joe Michaël',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 112,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : Apprentissage',
    designer: 'Bagley, Mark',
    writer: 'Bendis, Brian Michael',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 152,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : Le cauchemar',
    designer: 'Ramos, Humberto',
    writer: 'Jenkins, Paul',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 112,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : Spider-Men',
    designer: 'Brian Michael Bendis - Sara Pichelli',
    writer: 'Brian Michael Bendis - Sara Pichelli',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'The Boys : Ça va faire très mal !',
    designer: 'Garth Ennis - Darick Robertson',
    writer: 'Garth Ennis - Darick Robertson',
    coverUrl: '/comics_pictures/81zBxNJ7qYL.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'The Boys : Ça va saigner !',
    designer: 'Garth Ennis - Darick Robertson',
    writer: 'Garth Ennis - Darick Robertson',
    coverUrl: '/comics_pictures/81SpONNfbUL._AC_UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'The Boys : Dit comme ça...',
    designer: 'Garth Ennis - Darick Robertson',
    writer: 'Garth Ennis - Darick Robertson',
    coverUrl: '/comics_pictures/55_9782809455397_1_75.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'The Boys : Croire',
    designer: 'Garth Ennis - Darick Robertson',
    writer: 'Garth Ennis - Darick Robertson',
    coverUrl: '/comics_pictures/9791039130837_1_75.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'The Boys : Le fils du boulanger',
    designer: 'Garth Ennis - Darick Robertson',
    writer: 'Garth Ennis - Darick Robertson',
    coverUrl: '/comics_pictures/81sPG51YO4L._UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'The Boys : On ne prend plus de gants',
    designer: 'Garth Ennis - Darick Robertson',
    writer: 'Garth Ennis - Darick Robertson',
    coverUrl: '/comics_pictures/9791039134507.webp',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'The Boys : Chère Becky',
    designer: 'Garth Ennis - Darick Robertson',
    writer: 'Garth Ennis - Darick Robertson',
    coverUrl: '/comics_pictures/81UD0XWE1jS._UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Kick-Ass - Tome 1',
    designer: 'Mark Millar - John Romita Jr.',
    writer: 'Mark Millar - John Romita Jr.',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Kick-Ass - Tome 2',
    designer: 'Mark Millar - John Romita Jr.',
    writer: 'Mark Millar - John Romita Jr.',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Kick-Ass - Tome 3',
    designer: 'Mark Millar - John Romita Jr.',
    writer: 'Mark Millar - John Romita Jr.',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Avengers : La séparation',
    designer: 'Brian Michael Bendis - David Finch',
    writer: 'Brian Michael Bendis - David Finch',
    coverUrl: '/comics_pictures/libriweb.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Daredevil : End of Days',
    designer: 'Brian Michael Bendis - David Mack',
    writer: 'Brian Michael Bendis - David Mack',
    coverUrl: '/comics_pictures/daredevil-end-of-days-must-have.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Les Guerres Secrètes',
    designer: 'Jim Shooter - Mike Zeck - Bob Layton',
    writer: 'Jim Shooter - Mike Zeck - Bob Layton',
    coverUrl: '/comics_pictures/Les-Guerres-Secretes.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'World War Hulk',
    designer: 'Greg Pak - John Romita Jr.',
    writer: 'Greg Pak - John Romita Jr.',
    coverUrl: '/comics_pictures/world-war-hulk-must-have.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : Le retour du Bouffon Vert',
    designer: 'J. M. DeMatteis - Mike Zeck - Bob McLeod',
    writer: 'J. M. DeMatteis - Mike Zeck - Bob McLeod',
    coverUrl: '/comics_pictures/81h8JPLCtOL.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'House of M',
    designer: 'Brian Michael Bendis - Olivier Coipel',
    writer: 'Brian Michael Bendis - Olivier Coipel',
    coverUrl: '/comics_pictures/71PNwypK26L._AC_UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Uncanny Avengers : Nouvelle Union',
    designer: 'Cassaday, John -Coipel, Olivier',
    writer: 'Remender, Rick',
    coverUrl: '/comics_pictures/52_9782809489309_1_75.jpg',
    pages: 128,
    genre: 'Super-héros',
  },
  {
    title: "Thanos : L'ascension",
    designer: 'Bianchi, Simone',
    writer: 'Aaron, Jason',
    coverUrl: '/comics_pictures/ascension-de-thanos.jpg',
    pages: 96,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : La dernière chasse de Kraven',
    designer: 'J. M. DeMatteis - Mike Zeck - Bob McLeod',
    writer: 'J. M. DeMatteis - Mike Zeck - Bob McLeod',
    coverUrl: '/comics_pictures/36_9782809496673_1_75.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: "Thanos : Le gant de l'infini",
    designer: 'Jim Starlin - George Perez - Ron Lim',
    writer: 'Jim Starlin - George Perez - Ron Lim',
    coverUrl: '/comics_pictures/omnibus-le-gant-de-l-infini.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: "Thanos : La guerre de l'infini",
    designer: 'Jim Starlin - Ron Lim',
    writer: 'Jim Starlin - Ron Lim',
    coverUrl: '/comics_pictures/thanos-guerre-infini.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: "Thanos : La croisade de l'infini",
    designer: 'Jim Starlin - Ron Lim',
    writer: 'Jim Starlin - Ron Lim',
    coverUrl: '/comics_pictures/FGRNO00619_0.webp',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'La mort de Wolverine',
    designer: 'Charles Soule - Steve McNiven',
    writer: 'Charles Soule - Steve McNiven',
    coverUrl: '/comics_pictures/la-mort-de-wolverine-must-have.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Wolverine : Old Man Logan',
    designer: 'Mark Millar - Steve McNiven',
    writer: 'Mark Millar - Steve McNiven',
    coverUrl: '/comics_pictures/wolverine-old-man-logan-deluxe.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : Spider-Verse',
    designer: 'Dan Slott - Olivier Coipel',
    writer: 'Dan Slott - Olivier Coipel',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : De père en fils',
    designer: 'J. J. Abrams - Sara Pichelli',
    writer: 'J. J. Abrams - Sara Pichelli',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Avengers',
    designer: 'Heinberg - Cheung',
    writer: 'Heinberg - Cheung',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Daredevil - Tome 1',
    designer: 'McKenzie - Miller',
    writer: 'McKenzie - Miller',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Daredevil - Tome 2',
    designer: 'Miller',
    writer: 'Miller',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Daredevil - Tome 3',
    designer: 'Miller',
    writer: 'Miller',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Daredevil - Tome 4',
    designer: 'Miller - Mazzucchelli - Romita Jr',
    writer: 'Miller - Mazzucchelli - Romita Jr',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : 11 septembre 2001',
    designer: 'Inconnu',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : Son of M',
    designer: 'Roy Allan Martinez',
    writer: 'David Hine',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : La vraie saga du clone',
    designer: 'Nauck Todd',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 144,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : Tandem',
    designer: 'Romita Jr., John',
    writer: 'Straczynski, Joe Michaël',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 96,
    genre: 'Super-héros',
  },
  {
    title: "Spider-Man : L'attaque",
    designer: 'Inconnu',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Civil War',
    designer: 'Mark Millar - Steve McNiven',
    writer: 'Mark Millar - Steve McNiven',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Planet Hulk',
    designer: 'Greg Pak - Carlo Pagulayan',
    writer: 'Greg Pak - Carlo Pagulayan',
    coverUrl: '/comics_pictures/planete-hulk.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Avengers vs X-Men',
    designer:
      'Brian Michael Bendis - Jason Aaron - Ed Brubaker - Matt Fraction - Jonathan Hickman - John Romita Jr.',
    writer:
      'Brian Michael Bendis - Jason Aaron - Ed Brubaker - Matt Fraction - Jonathan Hickman - John Romita Jr.',
    coverUrl: '/comics_pictures/91JVr+CBSEL._AC_UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Infinity',
    designer: 'Jonathan Hickman - Jim Cheung - Jerome Opeña - Dustin Weaver',
    writer: 'Jonathan Hickman - Jim Cheung - Jerome Opeña - Dustin Weaver',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Secret Wars',
    designer: 'Jonathan Hickman - Esad Ribic',
    writer: 'Jonathan Hickman - Esad Ribic',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Marvel Icons',
    designer: 'Inconnu',
    writer: 'Inconnu',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man Noir : Cinquante nuances de noir',
    designer: 'David Hine - Fabrice Sapolsky - Carmine Di Giandomenico',
    writer: 'David Hine - Fabrice Sapolsky - Carmine Di Giandomenico',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'X-Men : House of X / Powers of X',
    designer: 'Jonathan Hickman - Pepe Larraz - R. B. Silva',
    writer: 'Jonathan Hickman - Pepe Larraz - R. B. Silva',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Astonishing X-Men : Surdoués',
    designer: 'Joss Whedon - John Cassaday',
    writer: 'Joss Whedon - John Cassaday',
    coverUrl: '/comics_pictures/astonishing-x-men-surdoues-must-have.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Astonishing X-Men : Invincible',
    designer: 'Joss Whedon - John Cassaday',
    writer: 'Joss Whedon - John Cassaday',
    coverUrl: '/comics_pictures/91maIYwDmJL._AC_UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Spider-Man : Spider-Island',
    designer: 'Dan Slott - Humberto Ramos',
    writer: 'Dan Slott - Humberto Ramos',
    coverUrl: '/comics_pictures/spider-man-spider-island.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Fantastic Four : Face aux fantômes',
    designer: 'Collectif',
    writer: 'Collectif',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: "Fantastic Four : L'histoire d'une vie",
    designer: 'Mark Russell - Sean Izaakse',
    writer: 'Mark Russell - Sean Izaakse',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: "Fantastic Four : L'appel des cendres",
    designer: 'Collectif',
    writer: 'Collectif',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Fantastic Four : Coup de force',
    designer: 'Collectif',
    writer: 'Collectif',
    coverUrl: '/comics_pictures/test.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: "Wolverine : Ennemi d'État",
    designer: 'Mark Millar - John Romita Jr.',
    writer: 'Mark Millar - John Romita Jr.',
    coverUrl: '/comics_pictures/wolverine-ennemi-d-etat-must-have.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
  {
    title: 'Secret Wars : La fin des temps',
    designer: 'Collectif',
    writer: 'Collectif',
    coverUrl: '/comics_pictures/A1FBfdg5mWL._UF1000,1000_QL80_.jpg',
    pages: 0,
    genre: 'Super-héros',
  },
];
