import { UserMovie } from '../../../../models/movie-model';

export const williamMovies: UserMovie[] = [
  {
    title: 'Cars',
    director: 'John Lasseter',
    rating: 0,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
  },
  {
    title: 'Cars 2',
    director: 'John Lasseter, Brad Lewis',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '2025-11-23',
    lastViewedDate: '2025-11-23',
  },
  {
    title: 'Cars 3',
    director: 'Brian Fee',
    rating: 0,
    timesWatched: 6,
    firstViewedDate: '',
    lastViewedDate: '',
  },
  {
    title: 'Planes',
    director: 'Klay Hall',
    rating: 0,
    timesWatched: 2,
    firstViewedDate: '2025-08-14',
    lastViewedDate: '2025-08-14',
  },
  {
    title: 'Planes 2',
    director: 'Roberts Gannaway',
    rating: 0,
    timesWatched: 4,
    firstViewedDate: '2025-09-14',
    lastViewedDate: '2025-09-14',
  },
  {
    title: 'Le monde de Nemo',
    director: 'Andrew Stanton',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '2025-09-23',
    lastViewedDate: '2025-09-23',
  },
  {
    title: 'Le monde de Dory',
    director: 'Andrew Stanton, Angus MacLane',
    rating: 0,
    timesWatched: 2,
    firstViewedDate: '2025-10-23',
    lastViewedDate: '2025-10-23',
  },
];
