import { UserBook } from '../../../../models/book-model';

export const lauralReadListBooks: UserBook[] = [
  {
    title: 'Les Hauts de Hurlevent',
    author: 'Emily Brontë',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Procès',
    author: 'Franz Kafka',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Cent ans de solitude',
    author: 'Gabriel García Márquez',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Hamlet',
    author: 'William Shakespeare',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Le dernier jour d'un condamné",
    author: 'Victor Hugo',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'Histoire sans fin",
    author: 'Michael Ende',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Orgueil et Préjugés',
    author: 'Jane Austen',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Raison et sentiments',
    author: 'Jane Austen',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'homme invisible",
    author: 'H.G. Wells',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'The Invisible Life of Addie LaRue',
    author: 'V.E. Schwab',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Player One',
    author: 'Ernest Cline',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Battle Royale',
    author: 'Kōshun Takami',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le fantôme de Canterville',
    author: 'Oscar Wilde',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Naissance de la tragédie',
    author: 'Friedrich Nietzsche',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les Rêveries du promeneur solitaire',
    author: 'Jean-Jacques Rousseau',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les Souffrances du jeune Werther',
    author: 'Johann Wolfgang von Goethe',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Peau noire masques blancs',
    author: 'Frantz Fanon',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Défier la nuit',
    author: 'Angèle Guissicca',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Maison sous la Maison',
    author: 'Émilie Chazerand',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Fille-Renard et la merveilleuse Boutique-sur-Pattes (1)',
    author: 'Andy Sagar',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Hotel Magnifique',
    author: 'Emily J. Taylor',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'En bons pères de famille',
    author: 'Rose Lamy',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le livre qui brisa le monde',
    author: 'Mark Lawrence',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le problème à trois corps',
    author: 'Liu Cixin',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les disparus du phare de Tévennec',
    author: 'Aricia Favalli',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Comte de Monte-Cristo',
    author: 'Alexandre Dumas',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Bel-Ami',
    author: 'Guy de Maupassant',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Métamorphose',
    author: 'Franz Kafka',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La voleuse de livres',
    author: 'Markus Zusak',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le rouge et le noir',
    author: 'Stendhal',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les Dents de la mer',
    author: 'Peter Benchley',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Mary Poppins',
    author: 'Pamela L. Travers',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Gatsby le magnifique',
    author: 'F. Scott Fitzgerald',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Je suis une légende',
    author: 'Richard Matheson',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Anna Karénine',
    author: 'Léon Tolstoï',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Jurassic Park',
    author: 'Michael Crichton',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La chronique des Bridgerton : La reine Charlotte',
    author: 'Julia Quinn',
    firstReadDate: '',
    lastReadDate: '',
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
];
