import { UserMovies } from '../../../../models/movie-model';

export const guillaumeWatchlistMovies: UserMovies = [
  {
    title: 'The Gentlemen',
    director: 'Guy Ritchie',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Cruella',
    director: 'Craig Gillespie',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Pokémon : Détective Pikachu',
    director: 'Rob Letterman',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'The Greatest Showman',
    director: 'Michael Gracey',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Le Crime de l\'Orient-Express',
    director: 'Kenneth Branagh',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'About Time',
    director: 'Richard Curtis',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Sherlock Holmes',
    director: 'Guy Ritchie',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Là-haut',
    director: 'Pete Docter',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'L\'Étrange Histoire de Benjamin Button',
    director: 'David Fincher',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Constantine',
    director: 'Francis Lawrence',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Aviator',
    director: 'Martin Scorsese',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'La Planète au trésor',
    director: 'Ron Clements, John Musker',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Insomnia',
    director: 'Christopher Nolan',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Atlantis : L\'Empire perdu',
    director: 'Gary Trousdale, Kirk Wise',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Moulin Rouge !',
    director: 'Baz Luhrmann',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Titanic',
    director: 'James Cameron',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Gattaca',
    director: 'Andrew Niccol',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'The Blues Brothers',
    director: 'John Landis',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Vice-Versa 2',
    director: 'Kelsey Mann',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Borat',
    director: 'Larry Charles',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Furiosa',
    director: 'George Miller',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Mad Max: Fury Road',
    director: 'George Miller',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Atonement',
    director: 'Joe Wright',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'The Worst Person in the World',
    director: 'Joachim Trier',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'L\'amour au présent',
    director: 'John Crowley',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Sinners',
    director: 'Ryan Coogler',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Novocaine',
    director: 'David Atkins',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Companion',
    director: 'Drew Hancock',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Princess Cursed in Time',
    director: 'Petr Kubík',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Predestination',
    director: 'Michael Spierig, Peter Spierig',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Triangle',
    director: 'Christopher Smith',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Looper',
    director: 'Rian Johnson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Philadelphia',
    director: 'Jonathan Demme',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Sully',
    director: 'Clint Eastwood',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Seul sur Mars',
    director: 'Ridley Scott',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Uncut Gems',
    director: 'Josh Safdie, Benny Safdie',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Once Upon a Time in Hollywood',
    director: 'Quentin Tarantino',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'À tous les garçons que j\'ai aimés',
    director: 'Susan Johnson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Avatar : De feu et de cendres',
    director: 'James Cameron',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Le Robot sauvage',
    director: 'Chris Sanders',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Running Man',
    director: 'Edgar Wright',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'The Whale',
    director: 'Darren Aronofsky',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Les Nouveaux Mutants',
    director: 'Josh Boone',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  },
  {
    title: 'Ballerina',
    director: 'Len Wiseman',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
  }
];
