import { UserMovies } from '../../../../models/movie-model';

export const guillaumeMoviesPage2: UserMovies = [
  {
    title: 'Chaos Walking',
    director: 'Doug Liman',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2021-10-16',
    lastViewedDate: '2021-10-16',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Love and Monsters',
    director: 'Michael Matthews',
    rating: 3.75,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '2025-03-16',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Tenet',
    director: 'Christopher Nolan',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2022-11-07',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Ava',
    director: 'Tate Taylor',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2020-12-07',
    lastViewedDate: '2020-12-07',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Mulan',
    director: 'Niki Caro',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Palm Springs',
    director: 'Max Barbakow',
    rating: 4,
    timesWatched: 5,
    firstViewedDate: '2022-02-10',
    lastViewedDate: '2024-02-10',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Guns Akimbo',
    director: 'Jason Lei Howden',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2020-06-28',
    lastViewedDate: '2020-06-28',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Joker',
    director: 'Todd Phillips',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2019-10-04',
    lastViewedDate: '2019-10-04',
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Evasion 3',
    director: 'John Herzfeld',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2020-05-14',
    lastViewedDate: '2020-05-14',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Aladdin',
    director: 'Guy Ritchie',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Alita: Battle Angel',
    director: 'Robert Rodriguez',
    rating: 3.75,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Le chant du loup',
    director: 'Antonin Baudry',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2024-10-07',
    lastViewedDate: '2024-10-07',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Bird Box',
    director: 'Susanne Bier',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2019-06-03',
    lastViewedDate: '2019-06-03',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'A Star Is Born',
    director: 'Bradley Cooper',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2022-10-27',
    lastViewedDate: '2022-10-27',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Evasion 2: Hades',
    director: 'Steven C. Miller',
    rating: 2.75,
    timesWatched: 1,
    firstViewedDate: '2020-05-14',
    lastViewedDate: '2020-05-14',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Ready Player One',
    director: 'Steven Spielberg',
    rating: 5,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },

  {
    title: 'E.T. the Extra-Terrestrial',
    director: 'Steven Spielberg',
    rating: 3.75,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'La soupe aux choux',
    director: 'Jean-Charles Tacchella',
    rating: 3.25,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'The Shining',
    director: 'Stanley Kubrick',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: "L'aile ou la cuisse",
    director: 'Claude Zidi',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Taxi Driver',
    director: 'Martin Scorsese',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2016-03-07',
    lastViewedDate: '2016-03-07',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: "L'exorciste",
    director: 'William Friedkin',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Les aventures de Rabbi Jacob',
    director: 'Gérard Oury',
    rating: 2.75,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'La Folie des grandeurs',
    director: 'Gérard Oury',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Oscar',
    director: 'Édouard Molinaro',
    rating: 4,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Fantomas',
    director: 'André Hunebelle',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Le Gendarme de Saint-Tropez',
    director: 'Jean Girault',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Les oiseaux',
    director: 'Alfred Hitchcock',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Psychose',
    director: 'Alfred Hitchcock',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2019-05-08',
    lastViewedDate: '2019-05-08',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: '12 hommes en colère',
    director: 'Sidney Lumet',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2024-12-03',
    lastViewedDate: '2024-12-03',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Citizen Kane',
    director: 'Orson Welles',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Les temps modernes',
    director: 'Charles Chaplin',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Babylon A.D',
    director: 'Mathieu Kassovitz',
    rating: 3.25,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: "Maman je m'occupe des méchants",
    director: 'Raja Gosnell',
    rating: 4,
    timesWatched: 20,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Yamakasi',
    director: 'Julien Seri',
    rating: 4.75,
    timesWatched: 40,
    firstViewedDate: '',
    lastViewedDate: '2025-02-05',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Jackie chan dans le bronx',
    director: 'Stanley Tong Gwai-Lai',
    rating: 3.25,
    timesWatched: 30,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'DodgeBall: Même pas mal',
    director: 'Rawson Marshall Thurber',
    rating: 3.75,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Garfield',
    director: 'Peter Hewitt',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Harold & Kumar Go to White Castle',
    director: 'Danny Leiner',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'The Day After Tomorrow',
    director: 'Roland Emmerich',
    rating: 4.75,
    timesWatched: 30,
    firstViewedDate: '',
    lastViewedDate: '2025-02-28',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Van Helsing',
    director: 'Stephen Sommers',
    rating: 3.25,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Man on Fire',
    director: 'Tony Scott',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Shaun of the Dead',
    director: 'Edgar Wright',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Les choristes',
    director: 'Christophe Barratier',
    rating: 3.75,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'EuroTrip',
    director: 'Jeff Schaffer',
    rating: 3.5,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Les 11 commandements',
    director: 'François Desagnat, Thomas Sorriaux',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'RRRrrrr!!!',
    director: 'Alain Chabat',
    rating: 3.75,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Saw',
    director: 'James Wan',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: "L'effet papillon",
    director: 'Eric Bress, J. Mackye Gruber',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Oldboy',
    director: 'Park Chan-wook',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Bruce tout-puissant',
    director: 'Tom Shadyac',
    rating: 4.25,
    timesWatched: 30,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Moi, Cesar, 10 ans et demi, 1m39',
    director: 'Richard Berry',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'En sursis',
    director: 'Andrzej Bartkowiak',
    rating: 3.75,
    timesWatched: 30,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'La Beuze',
    director: 'Éric Rochant',
    rating: 2.5,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Ong Bak',
    director: 'Prachya Pinkaew',
    rating: 3.75,
    timesWatched: 20,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Arrête-moi si tu peux',
    director: 'Steven Spielberg',
    rating: 4.25,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Equilibrium',
    director: 'Kurt Wimmer',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2023-01-25',
    lastViewedDate: '2023-01-25',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Opération antisèche',
    director: 'Andrew Gurland',
    rating: 3.25,
    timesWatched: 15,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: '28 jours plus tard',
    director: 'Danny Boyle',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Le cercle : The ring',
    director: 'Gore Verbinski',
    rating: 2.75,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Phone Game',
    director: 'Joel Schumacher',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Minority Report',
    director: 'Steven Spielberg',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Calculs Meurtriers',
    director: 'Barbet Schroeder',
    rating: 3.75,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: true,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Panic Room',
    director: 'David Fincher',
    rating: 3.5,
    timesWatched: 2,
    firstViewedDate: '2018-05-08',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Rollerball',
    director: 'John McTiernan',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Dommage Collateral',
    director: 'Andrew Davis',
    rating: 3.25,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Astérix et Cléopâtre',
    director: 'René Goscinny, Albert Uderzo',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Astérix et Obélix contre César',
    director: 'Claude Zidi',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Astérix & Obélix : Mission Cléopâtre',
    director: 'Alain Chabat',
    rating: 5,
    timesWatched: 50,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Astérix aux Jeux Olympiques',
    director: 'Frédéric Forestier, Thomas Langmann',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: "L'Associé du diable",
    director: 'Taylor Hackford',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Le Cinquième Élément',
    director: 'Luc Besson',
    rating: 3.5,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'American Beauty',
    director: 'Sam Mendes',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2016-02-03',
    lastViewedDate: '2016-02-03',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Sixième Sens',
    director: 'M. Night Shyamalan',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Wild Wild West',
    director: 'Barry Sonnenfeld',
    rating: 3.5,
    timesWatched: 20,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Sex intentions',
    director: 'Roger Kumble',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Armageddon',
    director: 'Michael Bay',
    rating: 4.5,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '2026-01-15',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'The Truman Show',
    director: 'Peter Weir',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Godzilla',
    director: 'Roland Emmerich',
    rating: 3.5,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'Mon voisin le tueur',
    director: 'Jonathan Lynn',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
  {
    title: 'La Ligne Verte',
    director: 'Frank Darabont',
    rating: 4.25,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
  },
];
