import { UserMovies } from '../../../../models/movie-model';

export const guillaumeMoviesPage3: UserMovies = [
  {
    title: "Kingsman : Le Cercle d'or",
    director: 'Matthew Vaughn',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Death Note',
    director: 'Adam Wingard',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2017-08-25',
    lastViewedDate: '2017-08-25',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Death Note (2006)',
    director: 'Shusuke Kaneko',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Death Note : The Last Name',
    director: 'Shusuke Kaneko',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Mon beau-père et moi',
    director: 'Jay Roach',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Hitman & Bodyguard',
    director: 'Patrick Hughes',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2017-08-28',
    lastViewedDate: '2017-08-28',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Valérian et la Cité des Mille Planètes',
    director: 'Luc Besson',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2023-03-31',
    lastViewedDate: '2023-03-31',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Atomic Blonde',
    director: 'David Leitch',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2021-01-18',
    lastViewedDate: '2021-01-18',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Baby Driver',
    director: 'Edgar Wright',
    rating: 4.25,
    timesWatched: 5,
    firstViewedDate: '2018-05-23',
    lastViewedDate: '2025-09-05',
    otherSeenDates: ['2022-07-30'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Aftermath',
    director: 'Elliott Lester',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2020-05-12',
    lastViewedDate: '2020-05-12',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Il a Déjà Tes Yeux',
    director: 'Lucien Jean-Baptiste',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2020-11-19',
    lastViewedDate: '2020-11-19',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Swiss Army Man',
    director: 'Dan Kwan, Daniel Scheinert',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2017-07-02',
    lastViewedDate: '2017-07-02',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: "Comment c'est loin",
    director: 'Orelsan',
    rating: 3.25,
    timesWatched: 2,
    firstViewedDate: '2015-12-15',
    lastViewedDate: '2018-12-22',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Creed',
    director: 'Ryan Coogler',
    rating: 4,
    timesWatched: 2,
    firstViewedDate: '2015-11-30',
    lastViewedDate: '2015-11-30',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Demolition',
    director: 'Jean-Marc Vallée',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2019-05-30',
    lastViewedDate: '2019-05-30',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Derrière nos écrans de fumée',
    director: 'Jeff Orlowski',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2020-09-22',
    lastViewedDate: '2020-09-22',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'The Visit',
    director: 'M. Night Shyamalan',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2015-09-16',
    lastViewedDate: '2015-09-11',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Le Labyrinthe 2 : La Terre Brûlée',
    director: 'Wes Ball',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Room',
    director: 'Lenny Abrahamson',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2019-06-29',
    lastViewedDate: '2019-06-29',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Pixels',
    director: 'Chris Columbus',
    rating: 3.25,
    timesWatched: 3,
    firstViewedDate: '2015-07-29',
    lastViewedDate: '2022-12-20',
    otherSeenDates: ['2018-10-18'],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'La rage au ventre',
    director: 'Antoine Fuqua',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2023-05-11',
    lastViewedDate: '2023-05-11',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Diversion',
    director: 'Glenn Ficarra, John Requa',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2025-01-10',
    lastViewedDate: '2025-01-10',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Cinquante Nuances de Grey',
    director: 'Sam Taylor-Johnson',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2015-02-14',
    lastViewedDate: '2015-02-14',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Knock Knock',
    director: 'Eli Roth',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2025-03-21',
    lastViewedDate: '2025-03-21',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Kingsman : Services Secrets',
    director: 'Matthew Vaughn',
    rating: 4.5,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '2024-10-26',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Interstellar',
    director: 'Christopher Nolan',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2014-11-15',
    lastViewedDate: '2014-11-15',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Gone Girl',
    director: 'David Fincher',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Birdman',
    director: 'Alejandro G. Iñárritu',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Lucy',
    director: 'Luc Besson',
    rating: 4.5,
    timesWatched: 3,
    firstViewedDate: '2014-10-02',
    lastViewedDate: '2014-10-02',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Le médaillon',
    director: 'Gordon Chan',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Smoking',
    director: 'Kevin Donovan',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Brice de Nice',
    director: 'James Huth',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '2005-02-07',
    lastViewedDate: '2005-02-07',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'La guerre des mondes',
    director: 'Steven Spielberg',
    rating: 3.5,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'La ligue des gentlemen extraordinaires',
    director: 'Stephen Norrington',
    rating: 3.75,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '2025-10-07',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'La tour Montparnasse infernale',
    director: 'Charles Nemes',
    rating: 3.5,
    timesWatched: 20,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2019-05-08'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Spaceballs',
    director: 'Mel Brooks',
    rating: 3.5,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Les Incorruptibles',
    director: 'Brian De Palma',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2010-10-10',
    lastViewedDate: '2010-10-10',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Dirty Dancing',
    director: 'Emile Ardolino',
    rating: 3.5,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Over the Top : Le bras de fer',
    director: 'Menahem Golan',
    rating: 3.5,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Commando',
    director: 'Mark L. Lester',
    rating: 3.25,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Le flic de Beverly Hills',
    director: 'Martin Brest',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Karate Kid',
    director: 'John G. Avildsen',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Scarface',
    director: 'Brian De Palma',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'The Dead Zone',
    director: 'David Cronenberg',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'À la Recherche du Bonheur',
    director: 'Gabriele Muccino',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2020-06-27'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Hors de Prix',
    director: 'Pierre Salvadori',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: '300',
    director: 'Zack Snyder',
    rating: 2.75,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Blood Diamond',
    director: 'Edward Zwick',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-05-08',
    lastViewedDate: '2025-05-08',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Le Prestige',
    director: 'Christopher Nolan',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2020-10-11',
    lastViewedDate: '2020-10-11',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Les Infiltrés',
    director: 'Martin Scorsese',
    rating: 3.75,
    timesWatched: 2,
    firstViewedDate: '2017-09-07',
    lastViewedDate: '2017-09-07',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Admis à tout prix',
    director: 'Steve Pink',
    rating: 3.5,
    timesWatched: 15,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2020-04-05'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Nos Jours heureux',
    director: 'Éric Toledano, Olivier Nakache',
    rating: 4.75,
    timesWatched: 31,
    firstViewedDate: '',
    lastViewedDate: '2025-07-11',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques'],
  },
  {
    title: "Le Diable s'Habille en Prada",
    director: 'David Frankel',
    rating: 4,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Babel',
    director: 'Alejandro González Iñárritu',
    rating: 2.75,
    timesWatched: 1,
    firstViewedDate: '2009-11-10',
    lastViewedDate: '2009-11-10',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: "De l'autre côté du lit",
    director: 'Peyton Reed',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Da Vinci Code',
    director: 'Ron Howard',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2021-11-02',
    lastViewedDate: '2021-11-02',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Camping',
    director: 'Fabien Onteniente',
    rating: 2.75,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Volver',
    director: 'Pedro Almodóvar',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2009-09-09',
    lastViewedDate: '2009-09-09',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Incontrôlable',
    director: 'Raffy Shart',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'V pour Vendetta',
    director: 'James McTeigue',
    rating: 5,
    timesWatched: 20,
    firstViewedDate: '',
    lastViewedDate: '2025-05-20',
    otherSeenDates: ['2020-03-17'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques'],
  },
  {
    title: 'King Kong',
    director: 'Peter Jackson',
    rating: 4,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '2025-04-17',
    otherSeenDates: ['2018-02-01', '2024-10-17'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Nanny McPhee',
    director: 'Kirk Jones',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2005-10-26',
    lastViewedDate: '2005-10-26',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Lord of War',
    director: 'Andrew Niccol',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2023-05-05',
    lastViewedDate: '2023-05-05',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Serenity',
    director: 'Joss Whedon',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2016-05-23',
    lastViewedDate: '2016-05-23',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: "L'honneur du dragon",
    director: 'Prachya Pinkaew',
    rating: 2.75,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: '40 Ans, Toujours Puceau',
    director: 'Judd Apatow',
    rating: 2.75,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Sous haute pression',
    director: 'Wes Craven',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-06-06',
    lastViewedDate: '2025-06-06',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Serial Nocers',
    director: 'David Dobkin',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Charlie et la Chocolaterie',
    director: 'Tim Burton',
    rating: 4,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Mr. & Mrs. Smith',
    director: 'Doug Liman',
    rating: 3.75,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2020-07-27'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'The Descent',
    director: 'Neil Marshall',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Baby Sittor',
    director: 'Adam Shankman',
    rating: 3.25,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Million Dollar Baby',
    director: 'Clint Eastwood',
    rating: 3.5,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Leon',
    director: 'Luc Besson',
    rating: 4,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'The Mask',
    director: 'Chuck Russell',
    rating: 4.5,
    timesWatched: 25,
    firstViewedDate: "",
    lastViewedDate: "",
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: "",
    borrowed: "",
    loaned: "",
    inList: ["Mes classiques"],
  },
  {
    title: 'True Lies',
    director: 'James Cameron',
    rating: 3.5,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Forrest Gump',
    director: 'Robert Zemeckis',
    rating: 4.75,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques'],
  },
  {
    title: 'Speed',
    director: 'Jan de Bont',
    rating: 4,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Pulp Fiction',
    director: 'Quentin Tarantino',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'La cité de la peur',
    director: 'Alain Berbérian',
    rating: 3.25,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Mrs. Doubtfire',
    director: 'Chris Columbus',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Le Dîner de Cons',
    director: 'Francis Veber',
    rating: 4.25,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques'],
  },
  {
    title: 'Code mercury',
    director: 'Harold Becker',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2018-04-22',
    lastViewedDate: '2018-04-22',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'The Big Lebowski',
    director: 'Joel Coen, Ethan Coen',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2023-06-04',
    lastViewedDate: '2023-06-04',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Will Hunting',
    director: 'Gus Van Sant',
    rating: 4.5,
    timesWatched: 15,
    firstViewedDate: '',
    lastViewedDate: '2023-02-16',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques'],
  },
];
