import { UserMovies } from '../../../../models/movie-model';

export const guillaumeMoviesLove: UserMovies = [
  {
    title: 'Mon inconnue',
    director: 'Hugo Gélin',
    rating: 4.5,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2025-07-18'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: 'The Princess Switch',
    director: 'Mike Rohl',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-12-29',
    lastViewedDate: '2024-12-29',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Petits coups montés',
    director: 'Claire Scanlon',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2023-01-16',
    lastViewedDate: '2023-01-16',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Demain est un autre jour',
    director: 'Liz W. Garcia',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-04-15',
    lastViewedDate: '2025-04-15',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: 'Champagne Problems',
    director: 'Mark Steven Johnson',
    rating: 2.25,
    timesWatched: 1,
    firstViewedDate: '2025-11-27',
    lastViewedDate: '2025-11-27',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Charlie, les filles lui disent merci',
    director: 'Mark Helfrich',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Le Chasseur de primes',
    director: 'Andy Tennant',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'People We Meet on Vacation',
    director: 'Brett Haley',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2026-01-15',
    lastViewedDate: '2026-01-15',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: 'Tout le Bleu du Ciel',
    director: 'João Canijo',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-03-03',
    lastViewedDate: '2025-03-03',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Nos coeurs meurtris',
    director: 'Elizabeth Allen Rosenbaum',
    rating: 4.25,
    timesWatched: 5,
    firstViewedDate: '2022-09-19',
    lastViewedDate: '2025-07-19',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: 'Au plaisir de se faire trahir',
    director: 'Diego Freitas',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2024-09-30',
    lastViewedDate: '2024-09-30',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: "La Probabilité statistique de l'amour au premier regard",
    director: 'Vanessa Caswill',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-01-19',
    lastViewedDate: '2025-01-19',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Ce sera toi',
    director: 'Alauda Ruiz de Azúa',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2024-06-28',
    lastViewedDate: '2024-06-28',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Hello, adieu, et nous au milieu',
    director: 'Michael Lewen',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2022-10-31',
    lastViewedDate: '2022-10-31',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Un Accord Parfait',
    director: 'Stuart McDonald',
    rating: 3.5,
    timesWatched: 3,
    firstViewedDate: '2023-11-09',
    lastViewedDate: '2023-11-09',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: 'The In-between',
    director: 'Arie Posin',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2022-04-10',
    lastViewedDate: '2022-04-10',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'À Travers Ma Fenêtre',
    director: 'Marçal Forés',
    rating: 2.75,
    timesWatched: 1,
    firstViewedDate: '2022-11-05',
    lastViewedDate: '2022-11-05',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Love Hard',
    director: 'Hernán Jiménez',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2022-10-30',
    lastViewedDate: '2022-10-30',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: "L'Amour complexe",
    director: 'Steven Tsuchida',
    rating: 2.75,
    timesWatched: 1,
    firstViewedDate: '2021-08-08',
    lastViewedDate: '2021-08-08',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'La Belle et la Bête',
    director: 'Bill Condon',
    rating: 3.5,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Un choix',
    director: 'Ross Katz',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '2025-02-26',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: "L'agence",
    director: 'George Nolfi',
    rating: 3.75,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2018-01-07'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Un jour',
    director: 'Lone Scherfig',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-10-23',
    lastViewedDate: '2024-10-23',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Sex Friends',
    director: 'Ivan Reitman',
    rating: 3.75,
    timesWatched: 20,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2023-02-14'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques', 'Mes romances'],
  },
  {
    title: 'Love & autres drogues',
    director: 'Edward Zwick',
    rating: 4,
    timesWatched: 20,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques', 'Mes romances'],
  },
  {
    title: 'Sexy Dance',
    director: 'Anne Fletcher',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Sexy Dance 2',
    director: 'Jon M. Chu',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Sexy Dance 3D',
    director: 'Jon M. Chu',
    rating: 3.75,
    timesWatched: 15,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2018-09-19'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques'],
  },
  {
    title: "L'Arnacœur",
    director: 'Pascal Chaumeil',
    rating: 4,
    timesWatched: 20,
    firstViewedDate: '2010-03-22',
    lastViewedDate: '2010-03-22',
    otherSeenDates: ['2023-01-13'],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: 'Remember Me',
    director: 'Allen Coulter',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2025-04-22',
    lastViewedDate: '2025-04-22',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: "Valentine's Day",
    director: 'Garry Marshall',
    rating: 3.25,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'La proposition',
    director: 'Anne Fletcher',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: '17 ans encore',
    director: 'Burr Steers',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: '(500) Jours Ensemble',
    director: 'Marc Webb',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Jackpot',
    director: 'Tom Vaughan',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: 'Juno',
    director: 'Jason Reitman',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Orgueil et Préjugés',
    director: 'Joe Wright',
    rating: 3.25,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2023-11-27'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Match Point',
    director: 'Woody Allen',
    rating: 3.75,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2019-10-19'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Hitch : Expert en Séduction',
    director: 'Andy Tennant',
    rating: 4.25,
    timesWatched: 30,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2024-07-24'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques', 'Mes romances'],
  },
  {
    title: 'Des étoiles plein les yeux',
    director: 'Forest Whitaker',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-01-10',
    lastViewedDate: '2025-01-10',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Eternal Sunshine of the Spotless Mind',
    director: 'Michel Gondry',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2019-06-18',
    lastViewedDate: '2019-06-18',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'The Girl Next Door',
    director: 'Luke Greenfield',
    rating: 3.5,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2016-12-20'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques', 'Mes romances'],
  },
  {
    title: 'Amour & Amnésie',
    director: 'Peter Segal',
    rating: 4.25,
    timesWatched: 30,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2016-07-19'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques', 'Mes romances'],
  },
  {
    title: 'Love Actually',
    director: 'Richard Curtis',
    rating: 3.5,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2020-12-29'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: "Le temps d'un automne",
    director: 'Adam Shankman',
    rating: 4,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: 'Pearl Harbor',
    director: 'Michael Bay',
    rating: 4.25,
    timesWatched: 1,
    firstViewedDate: '2022-11-03',
    lastViewedDate: '2022-11-03',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: 'Ce que Veulent les Femmes',
    director: 'Nancy Meyers',
    rating: 3.75,
    timesWatched: 20,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2025-11-27'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques', 'Mes romances'],
  },
  {
    title: 'Coup de foudre à Notting Hill',
    director: 'Roger Michell',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Rencontre avec Joe Black',
    director: 'Martin Brest',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2025-05-15',
    lastViewedDate: '2025-05-15',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Pretty Woman',
    director: 'Garry Marshall',
    rating: 4,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: "L'Amour puissance mille",
    director: 'Filip Zylber',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2022-10-31',
    lastViewedDate: '2022-10-31',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'La La Land',
    director: 'Damien Chazelle',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2019-02-13',
    lastViewedDate: '2019-02-13',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: "L'amour ouf",
    director: 'Gilles Lellouche',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-04-31',
    lastViewedDate: '2025-04-31',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'The Princess Switch : Switched Again',
    director: 'Mike Rohl',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2024-12-30',
    lastViewedDate: '2024-12-30',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Holidate',
    director: 'John Whitesell',
    rating: 2.75,
    timesWatched: 1,
    firstViewedDate: '2020-11-08',
    lastViewedDate: '2020-11-08',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Rich in Love',
    director: 'Bruno Garotti',
    rating: 3.25,
    timesWatched: 2,
    firstViewedDate: '2025-02-22',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
  },
  {
    title: 'Isi & Ossi',
    director: 'Oliver Kienle',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2022-11-14',
    lastViewedDate: '2022-11-14',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Last Christmas',
    director: 'Paul Feig',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2023-01-16',
    lastViewedDate: '2023-01-16',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: '40 jours et 40 nuits',
    director: 'Michael Lehmann',
    rating: 3.5,
    timesWatched: 15,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques', 'Mes romances'],
  },
  {
    title: 'Coup de foudre à Manhattan',
    director: 'Wayne Wang',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-11-28',
    lastViewedDate: '2025-11-28',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Love again: un peu, beaucoup, passionnément',
    director: 'James C. Strouse',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2026-01-12',
    lastViewedDate: '2026-01-12',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Honey',
    director: 'Billie Woodruff',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'Meilleures ennemies',
    director: 'Gary Winick',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2017-06-27',
    lastViewedDate: '2017-06-27',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: true,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
  {
    title: 'La règle de novembre',
    director: 'Mike Elliott',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2016-12-20',
    lastViewedDate: '2016-12-20',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
  },
];
