import { UserMovies } from '../../../../models/movie-model';

export const guillaumeMoviesPage4: UserMovies = [
  {
    title: 'Maléfique',
    director: 'Robert Stromberg',
    rating: 2.75,
    timesWatched: 1,
    firstViewedDate: '2014-06-15',
    lastViewedDate: '2014-06-15',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Zack et Miri font un porno',
    director: 'Kevin Smith',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Jeune et jolie',
    director: 'François Ozon',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Germinal',
    director: 'Claude Berri',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Edge of Tomorrow',
    director: 'Doug Liman',
    rating: 4.5,
    timesWatched: 10,
    firstViewedDate: '2014-06-11',
    lastViewedDate: '2014-06-11',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques'],
    lastUpdated: '',
  },
  {
    title: 'Robocop',
    director: 'José Padilha',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Le Loup de Wall Street',
    director: 'Martin Scorsese',
    rating: 4.25,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2021-07-12'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'La Vie Rêvée de Walter Mitty',
    director: 'Ben Stiller',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2023-09-13',
    lastViewedDate: '2023-09-13',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Prisoners',
    director: 'Denis Villeneuve',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2024-03-05',
    lastViewedDate: '2024-03-05',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Gravity',
    director: 'Alfonso Cuarón',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Elysium',
    director: 'Neill Blomkamp',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Le Majordome',
    director: 'Lee Daniels',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Evasion',
    director: 'Mikael Håfström',
    rating: 3.25,
    timesWatched: 2,
    firstViewedDate: '2020-05-11',
    lastViewedDate: '2020-05-11',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Pacific Rim',
    director: 'Guillermo del Toro',
    rating: 2.75,
    timesWatched: 1,
    firstViewedDate: '2013-07-30',
    lastViewedDate: '2013-07-30',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'World War Z',
    director: 'Marc Forster',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'The Conjuring : Les Dossiers Warren',
    director: 'James Wan',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2013-07-24',
    lastViewedDate: '2013-07-24',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'After Earth',
    director: 'M. Night Shyamalan',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2013-05-31',
    lastViewedDate: '2013-05-31',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'No pain no gain',
    director: 'Michael Bay',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Oblivion',
    director: 'Joseph Kosinski',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Django Unchained',
    director: 'Quentin Tarantino',
    rating: 3.75,
    timesWatched: 2,
    firstViewedDate: '2012-12-25',
    lastViewedDate: '2012-12-25',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Les seigneurs',
    director: 'Olivier Dahan',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2012-09-30',
    lastViewedDate: '2012-09-30',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Dredd',
    director: 'Pete Travis',
    rating: 2.75,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Expendables 2',
    director: 'Simon West',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'The Dictator',
    director: 'Larry Charles',
    rating: 3.25,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2018-04-15'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'The Lucky One',
    director: 'Scott Hicks',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2022-10-17',
    lastViewedDate: '2022-10-17',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes romances'],
    lastUpdated: '',
  },
  {
    title: 'Prometheus',
    director: 'Ridley Scott',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: '21 Jump Street',
    director: 'Phil Lord, Christopher Miller',
    rating: 3.5,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Target',
    director: 'McG',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Chronicle',
    director: 'Josh Trank',
    rating: 3.75,
    timesWatched: 3,
    firstViewedDate: '2012-02-30',
    lastViewedDate: '2012-02-30',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Time Out',
    director: 'Andrew Niccol',
    rating: 4.75,
    timesWatched: 15,
    firstViewedDate: '',
    lastViewedDate: '2025-04-28',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques', 'Mes romances'],
    lastUpdated: '',
  },
  {
    title: 'Double vice',
    director: 'André van Duren',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2023-05-22',
    lastViewedDate: '2023-05-22',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Footloose',
    director: 'Craig Brewer',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2022-10-28',
    lastViewedDate: '2022-10-28',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Real Steel',
    director: 'Shawn Levy',
    rating: 3.5,
    timesWatched: 10,
    firstViewedDate: '2011-10-12',
    lastViewedDate: '2025-02-07',
    otherSeenDates: ['2024-07-26'],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Intouchables',
    director: 'Olivier Nakache, Éric Toledano',
    rating: 5,
    timesWatched: 15,
    firstViewedDate: "2011-11-06",
    lastViewedDate: "2011-11-06",
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: "",
    borrowed: '',
    loaned: '',
    inList: ["Mes classiques", "Films d'écureuil"],
    lastUpdated: '',
  },
  {
    title: 'Warrior',
    director: "Gavin O'Connor",
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-02-09',
    lastViewedDate: '2024-02-09',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Never Back Down 2: The Beatdown',
    director: 'Michael Jai White',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'The Raid',
    director: 'Gareth Evans',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Cowboys & Aliens',
    director: 'Jon Favreau',
    rating: 2.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Tango & Cash',
    director: 'Andrei Konchalovsky',
    rating: 3.25,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Le cercle des poètes disparus',
    director: 'Peter Weir',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Kickboxer',
    director: 'Mark DiSalle, David Worth',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Qui veut la peau de Roger Rabbit',
    director: 'Robert Zemeckis',
    rating: 3.75,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Bloodsport',
    director: 'Newt Arnold',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Good Morning, Vietnam',
    director: 'Barry Levinson',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'The Running Man',
    director: 'Paul Michael Glaser',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'RoboCop',
    director: 'Paul Verhoeven',
    rating: 3.5,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'RoboCop 2',
    director: 'Irvin Kershner',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'RoboCop 3',
    director: 'Fred Dekker',
    rating: 3.5,
    timesWatched: 8,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Prédictions',
    director: 'Alex Proyas',
    rating: 3.25,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'I Love You Phillip Morris',
    director: 'Glenn Ficarra, John Requa',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Sept Vies',
    director: 'Gabriele Muccino',
    rating: 3.75,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Yes Man',
    director: 'Peyton Reed',
    rating: 3.25,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Gran Torino',
    director: 'Clint Eastwood',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Ong Bak 2',
    director: 'Tony Jaa',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "L'Œil du mal",
    director: 'D.J. Caruso',
    rating: 4.5,
    timesWatched: 15,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2018-11-11', '2020-12-07'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques'],
    lastUpdated: '',
  },
  {
    title: 'Slumdog Millionaire',
    director: 'Danny Boyle',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2017-04-11',
    lastViewedDate: '2017-04-11',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Course à la mort',
    director: 'Paul W.S. Anderson',
    rating: 3.5,
    timesWatched: 15,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2017-04-29'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Voyage au Centre de la Terre',
    director: 'Eric Brevig',
    rating: 3.75,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '2025-01-11',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Wanted : Choisis ton Destin',
    director: 'Timur Bekmambetov',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '2008-07-02',
    lastViewedDate: '2008-07-02',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Rien que pour vos cheveux',
    director: 'Dennis Dugan',
    rating: 3.25,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Speed Racer',
    director: 'Lana Wachowski, Lilly Wachowski',
    rating: 3.25,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'La vague',
    director: 'Dennis Gansel',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2010-02-11',
    lastViewedDate: '2010-02-11',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Never Back Down',
    director: 'Jeff Wadlow',
    rating: 4,
    timesWatched: 20,
    firstViewedDate: '2008-02-07',
    lastViewedDate: '2022-02-07',
    otherSeenDates: ['2019-09-05'],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques'],
    lastUpdated: '',
  },
  {
    title: 'Jumper',
    director: 'Doug Liman',
    rating: 3.5,
    timesWatched: 2,
    firstViewedDate: '2016-02-28',
    lastViewedDate: '2021-04-30',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Je Suis une Légende',
    director: 'Francis Lawrence',
    rating: 3.75,
    timesWatched: 5,
    firstViewedDate: '2007-12-19',
    lastViewedDate: '2020-12-19',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Paranormal Activity',
    director: 'Oren Peli',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Gone Baby Gone',
    director: 'Ben Affleck',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-06-05',
    lastViewedDate: '2024-06-05',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Into the Wild',
    director: 'Sean Penn',
    rating: 3.5,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'La chambre 1408',
    director: 'Mikael Håfström',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Evan tout-puissant',
    director: 'Tom Shadyac',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'No Country for Old Men',
    director: 'Joel Coen, Ethan Coen',
    rating: 2.75,
    timesWatched: 1,
    firstViewedDate: '2025-04-09',
    lastViewedDate: '2025-04-09',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: '28 Semaines Plus Tard',
    director: 'Juan Carlos Fresnadillo',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Dangereuse séduction',
    director: 'James Foley',
    rating: 3.5,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '2024-05-17',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Paranoïak',
    director: 'D.J. Caruso',
    rating: 3.5,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: ['2020-05-28'],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Supergrave',
    director: 'Greg Mottola',
    rating: 2.5,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Zodiac',
    director: 'David Fincher',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2016-03-02',
    lastViewedDate: '2016-03-02',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Prémonitions',
    director: 'Mennan Yapo',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2020-05-17',
    lastViewedDate: '2020-05-17',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: "L'effaceur",
    director: 'Chuck Russell',
    rating: 3.75,
    timesWatched: 15,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'La quête',
    director: 'Jean-Claude Van Damme',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Trainspotting',
    director: 'Danny Boyle',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Jumanji',
    director: 'Joe Johnston',
    rating: 3,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Seven',
    director: 'David Fincher',
    rating: 4,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Waterworld',
    director: 'Kevin Reynolds',
    rating: 3,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Piège à grande vitesse',
    director: 'Geoff Murphy',
    rating: 3.25,
    timesWatched: 15,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Judge Dredd',
    director: 'Danny Cannon',
    rating: 3.5,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'The Usual Suspects',
    director: 'Bryan Singer',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2016-03-16',
    lastViewedDate: '2016-03-16',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Street Fighter',
    director: 'Steven E. de Souza',
    rating: 2.75,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
  {
    title: 'Un indien dans la ville',
    director: 'Hervé Palud',
    rating: 3.5,
    timesWatched: 10,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: ['Mes classiques'],
    lastUpdated: '',
  },
  {
    title: 'Dumb & Dumber',
    director: 'Peter Farrelly, Bobby Farrelly',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
];
