import { UserMovies } from '../../../../models/movie-model';

export const guillaumeMoviesPage1: UserMovies = [
  {
    title: 'I, Robot',
    director: 'Alex Proyas',
    rating: 5,
    timesWatched: 30,
    firstViewedDate: '',
    lastViewedDate: '2025-05-10',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Mickey 17',
    director: 'Bong Joon-ho',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-01-31',
    lastViewedDate: '2025-01-31',
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Carry-On',
    director: 'Jaume Collet-Serra',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2024-11-15',
    lastViewedDate: '2024-11-15',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Le Comte de Monte-Cristo',
    director: 'Alexandre de La Patellière, Matthieu Delaporte',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2024-06-28',
    lastViewedDate: '2024-06-28',
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Challengers',
    director: 'Luca Guadagnino',
    rating: 2,
    timesWatched: 1,
    firstViewedDate: '2025-04-26',
    lastViewedDate: '2025-04-26',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Road House',
    director: 'Doug Liman',
    rating: 3.75,
    timesWatched: 5,
    firstViewedDate: '2024-03-21',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Damsel',
    director: 'Juan Carlos Fresnadillo',
    rating: 3.5,
    timesWatched: 2,
    firstViewedDate: '2024-03-24',
    lastViewedDate: '2024-03-24',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Sly',
    director: 'Thom Zimny',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2023-11-10',
    lastViewedDate: '2023-11-10',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Gran Turismo',
    director: 'Neill Blomkamp',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2024-07-27',
    lastViewedDate: '2024-07-27',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Oppenheimer',
    director: 'Christopher Nolan',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2023-07-21',
    lastViewedDate: '2023-07-21',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Barbie',
    director: 'Greta Gerwig',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-01-18',
    lastViewedDate: '2025-01-18',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Arnold',
    director: 'Lesley Chilcott',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2023-09-03',
    lastViewedDate: '2023-09-03',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Creed III',
    director: 'Michael B. Jordan',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Babylon',
    director: 'Damien Chazelle',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2023-08-25',
    lastViewedDate: '2023-08-25',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Le Chat Potté 2 : La Dernière Quête',
    director: 'Joel Crawford',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2024-03-13',
    lastViewedDate: '2024-03-13',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: "L'École du Bien et du Mal",
    director: 'Paul Feig',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2022-10-21',
    lastViewedDate: '2022-10-21',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Samaritan',
    director: 'Julius Avery',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2022-08-26',
    lastViewedDate: '2022-08-26',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Prey',
    director: 'Dan Trachtenberg',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2022-08-05',
    lastViewedDate: '2022-08-05',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Bullet Train',
    director: 'David Leitch',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2024-03-19',
    lastViewedDate: '2024-03-19',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Le haut du panier',
    director: 'Jeremiah Zagar',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2022-12-19',
    lastViewedDate: '2022-12-19',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Top Gun : Maverick',
    director: 'Joseph Kosinski',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2023-07-05',
    lastViewedDate: '2023-07-05',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Everything Everywhere All at Once',
    director: 'Daniel Kwan, Daniel Scheinert',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'The Adam Project',
    director: 'Shawn Levy',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2022-03-11',
    lastViewedDate: '2022-03-11',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: "Don't look up, déni cosmique",
    director: 'Adam McKay',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2025-05-24',
    lastViewedDate: '2025-05-24',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Red Notice',
    director: 'Rawson Marshall Thurber',
    rating: 3.25,
    timesWatched: 3,
    firstViewedDate: '2021-12-03',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'The Guilty',
    director: 'Antoine Fuqua',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2024-05-08',
    lastViewedDate: '2024-05-08',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'La méthode Williams',
    director: 'Reinaldo Marcus Green',
    rating: 4.25,
    timesWatched: 1,
    firstViewedDate: '2025-01-25',
    lastViewedDate: '2025-01-25',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Free Guy',
    director: 'Shawn Levy',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2021-08-13',
    lastViewedDate: '2021-08-13',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Jolt',
    director: 'Tanya Wexler',
    rating: 3.75,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'The Terminal',
    director: 'Steven Spielberg',
    rating: 3.75,
    timesWatched: 3,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Tanguy',
    director: 'Étienne Chatiliez',
    rating: 3.25,
    timesWatched: 2,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'The One',
    director: 'James Wong',
    rating: 3.5,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Wasabi',
    director: 'Gérard Krawczyk',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Training Day',
    director: 'Antoine Fuqua',
    rating: 3.25,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Shaolin Soccer',
    director: 'Stephen Chow',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Mulholland Drive',
    director: 'David Lynch',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Replicant',
    director: 'Ringo Lam',
    rating: 3,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Battle Royale',
    director: 'Kinji Fukasaku',
    rating: 2.75,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Miss Détective',
    director: 'Donald Petrie',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2020-05-16',
    lastViewedDate: '2020-05-16',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: "A l'aube du 6ème jour",
    director: 'Roger Spottiswoode',
    rating: 3.75,
    timesWatched: 5,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Memento',
    director: 'Christopher Nolan',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Snatch',
    director: 'Guy Ritchie',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Requiem for a Dream',
    director: 'Darren Aronofsky',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Gladiator',
    director: 'Ridley Scott',
    rating: 3.25,
    timesWatched: 2,
    firstViewedDate: '2024-10-01',
    lastViewedDate: '2024-10-01',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Rebel Ridge',
    director: 'Jeremy Saulnier',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2024-09-06',
    lastViewedDate: '2024-09-06',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: '84 m²',
    director: 'Kim Tae-joon',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2025-08-18',
    lastViewedDate: '2025-08-18',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Brick',
    director: 'Philip Koch',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2025-07-15',
    lastViewedDate: '2025-07-15',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'La carte qui mène à toi',
    director: 'Lasse Hallström',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2025-07-13',
    lastViewedDate: '2025-07-13',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Les 4 fantastiques',
    director: 'Matt Shakman',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2025-07-27',
    lastViewedDate: '2025-07-27',
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Premier contact',
    director: 'Denis Villeneuve',
    rating: 4.25,
    timesWatched: 1,
    firstViewedDate: '2025-07-08',
    lastViewedDate: '2025-07-08',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Sexe entre amis',
    director: 'Will Gluck',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-07-22',
    lastViewedDate: '2025-07-22',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Source Code',
    director: 'Duncan Jones',
    rating: 4,
    timesWatched: 1,
    firstViewedDate: '2025-09-01',
    lastViewedDate: '2025-09-01',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Le témoin amoureux',
    director: 'Paul Weiland',
    rating: 2.5,
    timesWatched: 1,
    firstViewedDate: '2025-07-04',
    lastViewedDate: '2025-07-04',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Une femme en jeu',
    director: 'Anna Kendrick',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-08-19',
    lastViewedDate: '2025-08-19',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Lettres à Juliette',
    director: 'Gary Winick',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-10-30',
    lastViewedDate: '2025-10-30',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'My Oxford Year',
    director: 'Sarah Treem',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-10-30',
    lastViewedDate: '2025-10-30',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Ordinary Angels',
    director: 'Jon Gunn',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2025-10-28',
    lastViewedDate: '2025-10-28',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'French Lover',
    director: 'Nina Rives',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-10-10',
    lastViewedDate: '2025-10-10',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Thunderbolts',
    director: 'Jake Schreier',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-10-20',
    lastViewedDate: '2025-10-20',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Le silence des agneaux',
    director: 'Jonathan Demme',
    rating: 3.5,
    timesWatched: 1,
    firstViewedDate: '2025-10-29',
    lastViewedDate: '2025-10-29',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Maintenance Required',
    director: 'Lacey Uhlemeyer',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2025-10-13',
    lastViewedDate: '2025-10-13',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Nocturnal Animals',
    director: 'Tom Ford',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2025-09-25',
    lastViewedDate: '2025-09-25',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Superman',
    director: 'Richard Donner',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Superman II',
    director: 'Richard Lester',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2025-09-10',
    lastViewedDate: '2025-09-10',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Superman Returns',
    director: 'Bryan Singer',
    rating: 3.75,
    timesWatched: 1,
    firstViewedDate: '2025-09-10',
    lastViewedDate: '2025-09-10',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Enemy',
    director: 'Denis Villeneuve',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2025-09-08',
    lastViewedDate: '2025-09-08',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Forever My Girl',
    director: 'Bethany Ashton Wolf',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2025-08-28',
    lastViewedDate: '2025-08-28',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Dans tes rêves',
    director: 'Denis Thybaud',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2013-03-02',
    lastViewedDate: '2013-03-02',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'La femme de ménage',
    director: 'Paul Feig',
    rating: 3.25,
    timesWatched: 1,
    firstViewedDate: '2026-01-02',
    lastViewedDate: '2026-01-02',
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
  {
    title: 'Eaux profondes',
    director: 'Adrian Lyne',
    rating: 3,
    timesWatched: 1,
    firstViewedDate: '2026-01-03',
    lastViewedDate: '2026-01-03',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },

  {
    title: 'Nobody',
    director: 'Ilya Naishuller',
    rating: 4.25,
    timesWatched: 1,
    firstViewedDate: '2026-02-01',
    lastViewedDate: '2026-02-01',
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
  },
];
