import { UserMovie } from '../../../../models/movie-model';

export const guillaumeWatchlistMovies: UserMovie[] = [
  {
    title: 'The Gentlemen',
    director: 'Guy Ritchie',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Cruella',
    director: 'Craig Gillespie',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Pokémon : Détective Pikachu',
    director: 'Rob Letterman',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'The Greatest Showman',
    director: 'Michael Gracey',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: "Le Crime de l'Orient-Express",
    director: 'Kenneth Branagh',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'About Time',
    director: 'Richard Curtis',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Sherlock Holmes',
    director: 'Guy Ritchie',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Là-haut',
    director: 'Pete Docter',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: "L'Étrange Histoire de Benjamin Button",
    director: 'David Fincher',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Constantine',
    director: 'Francis Lawrence',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Aviator',
    director: 'Martin Scorsese',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'La Planète au trésor',
    director: 'Ron Clements, John Musker',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Insomnia',
    director: 'Christopher Nolan',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: "Atlantis : L'Empire perdu",
    director: 'Gary Trousdale, Kirk Wise',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Moulin Rouge !',
    director: 'Baz Luhrmann',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Titanic',
    director: 'James Cameron',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Gattaca',
    director: 'Andrew Niccol',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'The Blues Brothers',
    director: 'John Landis',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Vice-Versa 2',
    director: 'Kelsey Mann',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Borat',
    director: 'Larry Charles',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Furiosa',
    director: 'George Miller',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Mad Max: Fury Road',
    director: 'George Miller',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Atonement',
    director: 'Joe Wright',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'The Worst Person in the World',
    director: 'Joachim Trier',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: "L'amour au présent",
    director: 'John Crowley',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Sinners',
    director: 'Ryan Coogler',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Novocaine',
    director: 'David Atkins',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Companion',
    director: 'Drew Hancock',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Princess Cursed in Time',
    director: 'Petr Kubík',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Predestination',
    director: 'Michael Spierig, Peter Spierig',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Triangle',
    director: 'Christopher Smith',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Looper',
    director: 'Rian Johnson',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Philadelphia',
    director: 'Jonathan Demme',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Sully',
    director: 'Clint Eastwood',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Nobody',
    director: 'Ilya Naishuller',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Seul sur Mars',
    director: 'Ridley Scott',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Uncut Gems',
    director: 'Josh Safdie, Benny Safdie',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
  {
    title: 'Once Upon a Time in Hollywood',
    director: 'Quentin Tarantino',
    rating: 0,
    timesWatched: 0,
    firstViewedDate: '',
    lastViewedDate: '',
    seenAtCinema: false,
  },
];
