import { BaseSerie } from '../../../models/serie-model';

export const baseSeries2: BaseSerie[] = [
  {
    title: 'Chernobyl',
    director: 'Craig Mazin',
    actors: [
      { name: 'Jared Harris' },
      { name: 'Stellan Skarsgård' },
      { name: 'Emily Watson' },
    ],
    coverUrl: '/series_pictures/356fcafc5be7.jpg',
    releaseDate: '2019-05-06',
    endDate: '2019-06-03',
    genre: ['Drama', 'History', 'Thriller'],
    seasonsData: [{ seasonNumber: 1, nbEpisodes: 5, totalLength: 330 }],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Les Soprano',
    director: 'David Chase',
    actors: [
      { name: 'James Gandolfini' },
      { name: 'Edie Falco' },
      { name: 'Lorraine Bracco' },
    ],
    coverUrl: '/series_pictures/85da0bc71bcb.jpg',
    releaseDate: '1999-01-10',
    endDate: '2007-06-10',
    genre: ['Crime', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 2, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 3, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 4, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 5, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 6, nbEpisodes: 21, totalLength: 1260 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Dark',
    director: 'Baran bo Odar',
    actors: [
      { name: 'Louis Hofmann' },
      { name: 'Lisa Vicari' },
      { name: 'Oliver Masucci' },
    ],
    coverUrl: '/series_pictures/03b61be783db.jpg',
    releaseDate: '2017-12-01',
    endDate: '2020-06-27',
    genre: ['Crime', 'Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 2, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 3, nbEpisodes: 8, totalLength: 480 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Allemagne',
  },
  {
    title: 'La Quatrième dimension',
    director: 'Rod Serling',
    actors: [
      { name: 'Rod Serling' },
      { name: 'William Shatner' },
      { name: 'Burgess Meredith' },
    ],
    coverUrl: '/series_pictures/d35c611c9422.jpg',
    releaseDate: '1959-10-02',
    endDate: '1964-04-17',
    genre: ['Fantasy', 'Horror', 'Sci-Fi'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 36, totalLength: 900 },
      { seasonNumber: 2, nbEpisodes: 29, totalLength: 725 },
      { seasonNumber: 3, nbEpisodes: 37, totalLength: 925 },
      { seasonNumber: 4, nbEpisodes: 18, totalLength: 450 },
      { seasonNumber: 5, nbEpisodes: 36, totalLength: 900 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Better Call Saul',
    director: 'Vince Gilligan, Peter Gould',
    actors: [
      { name: 'Bob Odenkirk' },
      { name: 'Rhea Seehorn' },
      { name: 'Jonathan Banks' },
    ],
    coverUrl: '/series_pictures/aada5eb25a01.jpg',
    releaseDate: '2015-02-08',
    endDate: '2022-08-15',
    genre: ['Crime', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 4, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 5, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 6, nbEpisodes: 13, totalLength: 780 },
    ],
    description: '',
    fromEntity: null,
    saga: 'Breaking Bad',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Seinfeld',
    director: 'Larry David, Jerry Seinfeld',
    actors: [
      { name: 'Jerry Seinfeld' },
      { name: 'Julia Louis-Dreyfus' },
      { name: 'Jason Alexander' },
    ],
    coverUrl: '/series_pictures/88e7d3cf013b.jpg',
    releaseDate: '1989-07-05',
    endDate: '1998-05-14',
    genre: ['Comedy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 5, totalLength: 125 },
      { seasonNumber: 2, nbEpisodes: 12, totalLength: 300 },
      { seasonNumber: 3, nbEpisodes: 23, totalLength: 575 },
      { seasonNumber: 4, nbEpisodes: 24, totalLength: 600 },
      { seasonNumber: 5, nbEpisodes: 22, totalLength: 550 },
      { seasonNumber: 6, nbEpisodes: 24, totalLength: 600 },
      { seasonNumber: 7, nbEpisodes: 24, totalLength: 600 },
      { seasonNumber: 8, nbEpisodes: 22, totalLength: 550 },
      { seasonNumber: 9, nbEpisodes: 24, totalLength: 600 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Cowboy Bebop',
    director: 'Shinichirō Watanabe',
    actors: [
      { name: 'Kōichi Yamadera' },
      { name: 'Megumi Hayashibara' },
      { name: 'Unshō Ishizuka' },
    ],
    coverUrl: '/series_pictures/0081579bd8d9.jpg',
    releaseDate: '1998-04-03',
    endDate: '1999-04-24',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    seasonsData: [{ seasonNumber: 1, nbEpisodes: 26, totalLength: 650 }],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Japon',
  },
  {
    title: 'True Detective',
    director: 'Nic Pizzolatto',
    actors: [
      { name: 'Matthew McConaughey' },
      { name: 'Woody Harrelson' },
      { name: 'Colin Farrell' },
    ],
    coverUrl: '/series_pictures/4ce5e734cc63.jpg',
    releaseDate: '2014-01-12',
    endDate: '2024-02-18',
    genre: ['Crime', 'Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 2, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 3, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 4, nbEpisodes: 6, totalLength: 360 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Fargo',
    director: 'Noah Hawley',
    actors: [
      { name: 'Billy Bob Thornton' },
      { name: 'Martin Freeman' },
      { name: 'Ewan McGregor' },
    ],
    coverUrl: '/series_pictures/07bb7ee19482.jpg',
    releaseDate: '2014-04-15',
    endDate: '2024-01-16',
    genre: ['Crime', 'Drama', 'Thriller'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 4, nbEpisodes: 11, totalLength: 660 },
      { seasonNumber: 5, nbEpisodes: 10, totalLength: 600 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Dans leur regard',
    director: 'Ava DuVernay',
    actors: [
      { name: 'Asante Blackk' },
      { name: 'Caleel Harris' },
      { name: 'Ethan Herisse' },
    ],
    coverUrl: '/series_pictures/cd4c1ec78eb2.jpg',
    releaseDate: '2019-05-31',
    endDate: '2019-05-31',
    genre: ['Drama', 'History'],
    seasonsData: [{ seasonNumber: 1, nbEpisodes: 4, totalLength: 240 }],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'BoJack Horseman',
    director: 'Raphael Bob-Waksberg',
    actors: [
      { name: 'Will Arnett' },
      { name: 'Alison Brie' },
      { name: 'Aaron Paul' },
    ],
    coverUrl: '/series_pictures/738ca5b4e5b2.jpg',
    releaseDate: '2014-08-22',
    endDate: '2020-01-31',
    genre: ['Animation', 'Comedy', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 2, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 3, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 4, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 5, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 6, nbEpisodes: 16, totalLength: 480 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Vinland Saga',
    director: 'Shūhei Yabuta',
    actors: [
      { name: 'Yūto Uemura' },
      { name: 'Kenshō Ono' },
      { name: 'Akio Ōtsuka' },
    ],
    coverUrl: '/series_pictures/6b0e844fb438.jpg',
    releaseDate: '2019-07-08',
    endDate: '2023-06-20',
    genre: ['Action', 'Adventure', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 24, totalLength: 600 },
      { seasonNumber: 2, nbEpisodes: 24, totalLength: 600 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Japon',
  },
  {
    title: 'Narcos',
    director: 'Chris Brancato, Carlo Bernard, Doug Miro',
    actors: [
      { name: 'Wagner Moura' },
      { name: 'Pedro Pascal' },
      { name: 'Boyd Holbrook' },
    ],
    coverUrl: '/series_pictures/e94ab9042bf1.jpg',
    releaseDate: '2015-08-28',
    endDate: '2017-09-01',
    genre: ['Biography', 'Crime', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 600 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Berserk',
    director: 'Naohito Takahashi',
    actors: [
      { name: 'Nobutoshi Canna' },
      { name: 'Akiko Yajima' },
      { name: 'Toshiyuki Morikawa' },
    ],
    coverUrl: '/series_pictures/aeda6de4f6f7.jpg',
    releaseDate: '1997-10-08',
    endDate: '1998-04-01',
    genre: ['Action', 'Adventure', 'Fantasy'],
    seasonsData: [{ seasonNumber: 1, nbEpisodes: 25, totalLength: 625 }],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Japon',
  },
  {
    title: 'Peaky Blinders',
    director: 'Steven Knight',
    actors: [
      { name: 'Cillian Murphy' },
      { name: 'Helen McCrory' },
      { name: 'Paul Anderson' },
    ],
    coverUrl: '/series_pictures/5154827c5368.jpg',
    releaseDate: '2013-09-12',
    endDate: '2022-04-03',
    genre: ['Crime', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 6, totalLength: 360 },
      { seasonNumber: 2, nbEpisodes: 6, totalLength: 360 },
      { seasonNumber: 3, nbEpisodes: 6, totalLength: 360 },
      { seasonNumber: 4, nbEpisodes: 6, totalLength: 360 },
      { seasonNumber: 5, nbEpisodes: 6, totalLength: 360 },
      { seasonNumber: 6, nbEpisodes: 6, totalLength: 360 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Royaume-Uni',
  },
  {
    title: 'FlashForward',
    director: 'Brannon Braga, David S. Goyer',
    actors: [
      { name: 'Joseph Fiennes' },
      { name: 'John Cho' },
      { name: 'Sonya Walger' },
    ],
    coverUrl: '/series_pictures/2adb55884219.jpg',
    releaseDate: '2009-09-24',
    endDate: '2010-05-27',
    genre: ['Drama', 'Mystery', 'Sci-Fi'],
    seasonsData: [{ seasonNumber: 1, nbEpisodes: 22, totalLength: 1320 }],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Mad Men',
    director: 'Matthew Weiner',
    actors: [
      { name: 'Jon Hamm' },
      { name: 'Elisabeth Moss' },
      { name: 'January Jones' },
    ],
    coverUrl: '/series_pictures/f359223a7d5c.jpg',
    releaseDate: '2007-07-19',
    endDate: '2015-05-17',
    genre: ['Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 2, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 3, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 4, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 5, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 6, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 7, nbEpisodes: 14, totalLength: 840 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Dr House',
    director: 'David Shore',
    actors: [
      { name: 'Hugh Laurie' },
      { name: 'Lisa Edelstein' },
      { name: 'Omar Epps' },
    ],
    coverUrl: '/series_pictures/aa5d07d7be7b.webp',
    releaseDate: '2004-11-16',
    endDate: '2012-05-21',
    genre: ['Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 2, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 3, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 4, nbEpisodes: 16, totalLength: 960 },
      { seasonNumber: 5, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 6, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 7, nbEpisodes: 23, totalLength: 1380 },
      { seasonNumber: 8, nbEpisodes: 23, totalLength: 1380 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Engrenages',
    director: 'Alexandra Clert, Guy-Patrick Sainderichin',
    actors: [
      { name: 'Caroline Proust' },
      { name: 'Grégory Fitoussi' },
      { name: 'Thierry Godard' },
    ],
    coverUrl: '/series_pictures/cc461eaa649c.jpg',
    releaseDate: '2005-12-13',
    endDate: '2020-02-03',
    genre: ['Crime', 'Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 2, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 3, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 4, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 5, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 6, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 7, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 8, nbEpisodes: 10, totalLength: 600 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'France',
  },
  {
    title: 'X-Files : Aux frontières du réel',
    director: 'Chris Carter',
    actors: [
      { name: 'David Duchovny' },
      { name: 'Gillian Anderson' },
      { name: 'Mitch Pileggi' },
    ],
    coverUrl:
      'https://assets.diverto.tv/media/remote/aHR0cHM6Ly9pbWFnZS50bWRiLm9yZy90L3AvL29yaWdpbmFsLy9lUDRPUzU3Z2JxaU9JdlZBbkNzOFQ0cno1dDQuanBn?fit=contain&fm=webp&s=06773be4c37048a0d1ae6863a8bf5fe7',
    releaseDate: '1993-09-10',
    endDate: '2018-03-21',
    genre: ['Drama', 'Mystery', 'Sci-Fi'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 2, nbEpisodes: 25, totalLength: 1500 },
      { seasonNumber: 3, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 4, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 5, nbEpisodes: 20, totalLength: 1200 },
      { seasonNumber: 6, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 7, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 8, nbEpisodes: 21, totalLength: 1260 },
      { seasonNumber: 9, nbEpisodes: 20, totalLength: 1200 },
      { seasonNumber: 10, nbEpisodes: 6, totalLength: 360 },
      { seasonNumber: 11, nbEpisodes: 10, totalLength: 600 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'The Crown',
    director: 'Peter Morgan',
    actors: [
      { name: 'Claire Foy' },
      { name: 'Olivia Colman' },
      { name: 'Imelda Staunton' },
    ],
    coverUrl: '/series_pictures/7c1771a76fd7.jpg',
    releaseDate: '2016-11-04',
    endDate: '2023-12-14',
    genre: ['Biography', 'Drama', 'History'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 4, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 5, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 6, nbEpisodes: 10, totalLength: 600 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Royaume-Uni',
  },
  {
    title: 'Mr. Bean',
    director: 'John Howard Davies, John Birkin',
    actors: [
      { name: 'Rowan Atkinson' },
      { name: 'Matilda Ziegler' },
      { name: 'Robin Driscoll' },
    ],
    coverUrl: '/series_pictures/298ae6fd51e8.jpg',
    releaseDate: '1990-01-01',
    endDate: '1995-12-15',
    genre: ['Comedy', 'Family'],
    seasonsData: [{ seasonNumber: 1, nbEpisodes: 14, totalLength: 210 }],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Royaume-Uni',
  },
  {
    title: 'Cyberpunk: Edgerunners',
    director: 'Hiroyuki Imaishi',
    actors: [{ name: 'KENN' }, { name: 'Aoi Yūki' }, { name: 'Zach Aguilar' }],
    coverUrl: '/series_pictures/32f74cf2b7b0.jpg',
    releaseDate: '2022-09-13',
    endDate: '2022-09-13',
    genre: ['Action', 'Animation', 'Sci-Fi'],
    seasonsData: [{ seasonNumber: 1, nbEpisodes: 10, totalLength: 300 }],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Japon',
  },
  {
    title: 'Archer',
    director: 'Adam Reed',
    actors: [
      { name: 'H. Jon Benjamin' },
      { name: 'Aisha Tyler' },
      { name: 'Judy Greer' },
    ],
    coverUrl: '/series_pictures/71317ec8ee95.jpg',
    releaseDate: '2009-09-17',
    endDate: '2023-12-17',
    genre: ['Action', 'Animation', 'Comedy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 220 },
      { seasonNumber: 2, nbEpisodes: 13, totalLength: 286 },
      { seasonNumber: 3, nbEpisodes: 13, totalLength: 286 },
      { seasonNumber: 4, nbEpisodes: 13, totalLength: 286 },
      { seasonNumber: 5, nbEpisodes: 13, totalLength: 286 },
      { seasonNumber: 6, nbEpisodes: 13, totalLength: 286 },
      { seasonNumber: 7, nbEpisodes: 10, totalLength: 220 },
      { seasonNumber: 8, nbEpisodes: 8, totalLength: 176 },
      { seasonNumber: 9, nbEpisodes: 8, totalLength: 176 },
      { seasonNumber: 10, nbEpisodes: 9, totalLength: 198 },
      { seasonNumber: 11, nbEpisodes: 8, totalLength: 176 },
      { seasonNumber: 12, nbEpisodes: 8, totalLength: 176 },
      { seasonNumber: 13, nbEpisodes: 8, totalLength: 176 },
      { seasonNumber: 14, nbEpisodes: 12, totalLength: 264 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Stargate SG-1',
    director: 'Brad Wright, Jonathan Glassner',
    actors: [
      { name: 'Richard Dean Anderson' },
      { name: 'Michael Shanks' },
      { name: 'Amanda Tapping' },
    ],
    coverUrl: '/series_pictures/62acfa84c2f3.jpg',
    releaseDate: '1997-07-27',
    endDate: '2007-03-13',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 22, totalLength: 968 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 968 },
      { seasonNumber: 3, nbEpisodes: 22, totalLength: 968 },
      { seasonNumber: 4, nbEpisodes: 22, totalLength: 968 },
      { seasonNumber: 5, nbEpisodes: 22, totalLength: 968 },
      { seasonNumber: 6, nbEpisodes: 22, totalLength: 968 },
      { seasonNumber: 7, nbEpisodes: 22, totalLength: 968 },
      { seasonNumber: 8, nbEpisodes: 20, totalLength: 880 },
      { seasonNumber: 9, nbEpisodes: 20, totalLength: 880 },
      { seasonNumber: 10, nbEpisodes: 20, totalLength: 880 },
    ],
    description: '',
    fromEntity: null,
    saga: 'Stargate',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'La Ligue des justiciers',
    director: 'Butch Lukic, Dan Riba',
    actors: [
      { name: 'Kevin Conroy' },
      { name: 'Maria Canals-Barrera' },
      { name: 'Phil LaMarr' },
    ],
    coverUrl: '/series_pictures/eedf3fb65d02.jpg',
    releaseDate: '2001-11-17',
    endDate: '2004-05-29',
    genre: ['Action', 'Animation', 'Adventure'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 26, totalLength: 572 },
      { seasonNumber: 2, nbEpisodes: 26, totalLength: 572 },
    ],
    description: '',
    fromEntity: null,
    saga: 'DC Comics',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Mr. Robot',
    director: 'Sam Esmail',
    actors: [
      { name: 'Rami Malek' },
      { name: 'Christian Slater' },
      { name: 'Carly Chaikin' },
    ],
    coverUrl: '/series_pictures/bbff488ed391.jpg',
    releaseDate: '2015-06-24',
    endDate: '2019-12-22',
    genre: ['Crime', 'Drama', 'Thriller'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 2, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 4, nbEpisodes: 13, totalLength: 780 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Twin Peaks',
    director: 'David Lynch, Mark Frost',
    actors: [
      { name: 'Kyle MacLachlan' },
      { name: 'Sherilyn Fenn' },
      { name: 'Mädchen Amick' },
    ],
    coverUrl: '/series_pictures/ae11d64b563a.jpg',
    releaseDate: '1990-04-08',
    endDate: '2017-09-03',
    genre: ['Crime', 'Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 3, nbEpisodes: 18, totalLength: 1080 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Doctor Who',
    director: 'Sydney Newman, C. E. Webber, Donald Wilson',
    actors: [
      { name: 'Christopher Eccleston' },
      { name: 'David Tennant' },
      { name: 'Jodie Whittaker' },
    ],
    coverUrl: '/series_pictures/8d736ded9224.jpg',
    releaseDate: '2005-03-26',
    endDate: '2023-12-09',
    genre: ['Adventure', 'Drama', 'Sci-Fi'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 2, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 3, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 4, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 5, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 6, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 7, nbEpisodes: 15, totalLength: 900 },
      { seasonNumber: 8, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 9, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 10, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 11, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 12, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 13, nbEpisodes: 8, totalLength: 480 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Royaume-Uni',
  },
  {
    title: 'Yellowstone',
    director: 'Taylor Sheridan, John Linson',
    actors: [
      { name: 'Kevin Costner' },
      { name: 'Luke Grimes' },
      { name: 'Kelly Reilly' },
    ],
    coverUrl: '/series_pictures/ac7b5036eedb.jpg',
    releaseDate: '2018-06-20',
    endDate: '2024-12-22',
    genre: ['Drama', 'Western'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 9, totalLength: 540 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 4, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 5, nbEpisodes: 14, totalLength: 840 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Silicon Valley',
    director: 'Mike Judge, John Altschuler, Dave Krinsky',
    actors: [
      { name: 'Thomas Middleditch' },
      { name: 'T.J. Miller' },
      { name: 'Josh Brener' },
    ],
    coverUrl: '/series_pictures/bd59dabd4718.jpg',
    releaseDate: '2014-04-06',
    endDate: '2019-12-08',
    genre: ['Comedy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 240 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 300 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 300 },
      { seasonNumber: 4, nbEpisodes: 10, totalLength: 300 },
      { seasonNumber: 5, nbEpisodes: 10, totalLength: 300 },
      { seasonNumber: 6, nbEpisodes: 7, totalLength: 210 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'House of Cards',
    director: 'Beau Willimon',
    actors: [
      { name: 'Kevin Spacey' },
      { name: 'Robin Wright' },
      { name: 'Kate Mara' },
    ],
    coverUrl: '/series_pictures/d2448abc3040.jpg',
    releaseDate: '2013-02-01',
    endDate: '2018-11-02',
    genre: ['Drama', 'Thriller'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 2, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 3, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 4, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 5, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 6, nbEpisodes: 8, totalLength: 480 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Rome',
    director: 'Bruno Heller, William J. MacDonald, John Milius',
    actors: [
      { name: 'Kevin McKidd' },
      { name: 'Ray Stevenson' },
      { name: 'Polly Walker' },
    ],
    coverUrl: '/series_pictures/2e3f4c42bf1b.jpg',
    releaseDate: '2005-08-28',
    endDate: '2007-03-25',
    genre: ['Action', 'Drama', 'History'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 600 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Downton Abbey',
    director: 'Julian Fellowes',
    actors: [
      { name: 'Hugh Bonneville' },
      { name: 'Michelle Dockery' },
      { name: 'Maggie Smith' },
    ],
    coverUrl: '/series_pictures/9fd698e8a6b3.jpg',
    releaseDate: '2010-09-26',
    endDate: '2015-12-25',
    genre: ['Drama', 'Romance'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 7, totalLength: 420 },
      { seasonNumber: 2, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 3, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 4, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 5, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 6, nbEpisodes: 9, totalLength: 540 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Royaume-Uni',
  },
  {
    title: 'Star Trek : La nouvelle génération',
    director: 'Gene Roddenberry',
    actors: [
      { name: 'Patrick Stewart' },
      { name: 'Jonathan Frakes' },
      { name: 'Brent Spiner' },
    ],
    coverUrl: '/series_pictures/e957a489eeeb.jpg',
    releaseDate: '1987-09-28',
    endDate: '1994-05-23',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 25, totalLength: 1100 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 968 },
      { seasonNumber: 3, nbEpisodes: 26, totalLength: 1144 },
      { seasonNumber: 4, nbEpisodes: 26, totalLength: 1144 },
      { seasonNumber: 5, nbEpisodes: 26, totalLength: 1144 },
      { seasonNumber: 6, nbEpisodes: 26, totalLength: 1144 },
      { seasonNumber: 7, nbEpisodes: 26, totalLength: 1144 },
    ],
    description: '',
    fromEntity: null,
    saga: 'Star Trek',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Invincible',
    director: 'Robert Kirkman',
    actors: [
      { name: 'Steven Yeun' },
      { name: 'J.K. Simmons' },
      { name: 'Sandra Oh' },
    ],
    coverUrl: '/series_pictures/ed292bcc92da.jpg',
    releaseDate: '2021-03-26',
    endDate: '2025-03-13',
    genre: ['Action', 'Animation', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 2, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 3, nbEpisodes: 8, totalLength: 480 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'True Blood',
    director: 'Alan Ball',
    actors: [
      { name: 'Anna Paquin' },
      { name: 'Stephen Moyer' },
      { name: 'Alexander Skarsgård' },
    ],
    coverUrl: '/series_pictures/c8240cf17439.jpg',
    releaseDate: '2008-09-07',
    endDate: '2014-08-24',
    genre: ['Drama', 'Fantasy', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 2, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 3, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 4, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 5, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 6, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 7, nbEpisodes: 10, totalLength: 600 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Buffy contre les vampires',
    director: 'Joss Whedon',
    actors: [
      { name: 'Sarah Michelle Gellar' },
      { name: 'Nicholas Brendon' },
      { name: 'Alyson Hannigan' },
    ],
    coverUrl: '/series_pictures/47c9972417d9.jpg',
    releaseDate: '1997-03-10',
    endDate: '2003-05-20',
    genre: ['Action', 'Drama', 'Fantasy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 3, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 4, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 5, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 6, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 7, nbEpisodes: 22, totalLength: 1320 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'The IT Crowd',
    director: 'Graham Linehan',
    actors: [
      { name: "Chris O'Dowd" },
      { name: 'Richard Ayoade' },
      { name: 'Katherine Parkinson' },
    ],
    coverUrl: '/series_pictures/d333e66436fe.jpg',
    releaseDate: '2006-02-03',
    endDate: '2013-09-27',
    genre: ['Comedy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 6, totalLength: 180 },
      { seasonNumber: 2, nbEpisodes: 6, totalLength: 180 },
      { seasonNumber: 3, nbEpisodes: 6, totalLength: 180 },
      { seasonNumber: 4, nbEpisodes: 6, totalLength: 180 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Royaume-Uni',
  },
  {
    title: 'Entourage',
    director: 'Doug Ellin',
    actors: [
      { name: 'Adrian Grenier' },
      { name: 'Kevin Connolly' },
      { name: 'Jeremy Piven' },
    ],
    coverUrl: '/series_pictures/77202ac65589.jpg',
    releaseDate: '2004-07-18',
    endDate: '2011-09-11',
    genre: ['Comedy', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 240 },
      { seasonNumber: 2, nbEpisodes: 14, totalLength: 420 },
      { seasonNumber: 3, nbEpisodes: 20, totalLength: 600 },
      { seasonNumber: 4, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 5, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 6, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 7, nbEpisodes: 10, totalLength: 300 },
      { seasonNumber: 8, nbEpisodes: 8, totalLength: 240 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Futurama',
    director: 'Matt Groening, David X. Cohen',
    actors: [
      { name: 'Billy West' },
      { name: 'Katey Sagal' },
      { name: 'John DiMaggio' },
    ],
    coverUrl: '/series_pictures/a2dbad47eac6.jpg',
    releaseDate: '1999-03-28',
    endDate: '2023-09-04',
    genre: ['Animation', 'Comedy', 'Sci-Fi'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 13, totalLength: 286 },
      { seasonNumber: 2, nbEpisodes: 19, totalLength: 418 },
      { seasonNumber: 3, nbEpisodes: 15, totalLength: 330 },
      { seasonNumber: 4, nbEpisodes: 18, totalLength: 396 },
      { seasonNumber: 5, nbEpisodes: 16, totalLength: 352 },
      { seasonNumber: 6, nbEpisodes: 26, totalLength: 572 },
      { seasonNumber: 7, nbEpisodes: 26, totalLength: 572 },
      { seasonNumber: 8, nbEpisodes: 10, totalLength: 220 },
      { seasonNumber: 9, nbEpisodes: 10, totalLength: 220 },
      { seasonNumber: 10, nbEpisodes: 10, totalLength: 220 },
      { seasonNumber: 11, nbEpisodes: 10, totalLength: 220 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Homeland',
    director: 'Howard Gordon, Alex Gansa',
    actors: [
      { name: 'Claire Danes' },
      { name: 'Damian Lewis' },
      { name: 'Mandy Patinkin' },
    ],
    coverUrl: '/series_pictures/3adc81fa3b6c.jpg',
    releaseDate: '2011-10-02',
    endDate: '2020-04-26',
    genre: ['Crime', 'Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 2, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 3, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 4, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 5, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 6, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 7, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 8, nbEpisodes: 12, totalLength: 720 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Queer as Folk',
    director: 'Ron Cowen, Daniel Lipman',
    actors: [
      { name: 'Gale Harold' },
      { name: 'Randy Harrison' },
      { name: 'Hal Sparks' },
    ],
    coverUrl: '/series_pictures/b50c317f1826.jpg',
    releaseDate: '2000-12-03',
    endDate: '2005-08-07',
    genre: ['Drama', 'Romance'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 2, nbEpisodes: 20, totalLength: 1200 },
      { seasonNumber: 3, nbEpisodes: 14, totalLength: 840 },
      { seasonNumber: 4, nbEpisodes: 14, totalLength: 840 },
      { seasonNumber: 5, nbEpisodes: 13, totalLength: 780 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Big Little Lies',
    director: 'David E. Kelley',
    actors: [
      { name: 'Reese Witherspoon' },
      { name: 'Nicole Kidman' },
      { name: 'Shailene Woodley' },
    ],
    coverUrl: '/series_pictures/64bb07f540d5.png',
    releaseDate: '2017-02-19',
    endDate: '2019-07-21',
    genre: ['Crime', 'Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 7, totalLength: 420 },
      { seasonNumber: 2, nbEpisodes: 7, totalLength: 420 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Scrubs',
    director: 'Bill Lawrence',
    actors: [
      { name: 'Zach Braff' },
      { name: 'Sarah Chalke' },
      { name: 'Donald Faison' },
    ],
    coverUrl: '/series_pictures/665435adb197.jpg',
    releaseDate: '2001-10-02',
    endDate: '2010-03-17',
    genre: ['Comedy', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 24, totalLength: 528 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 484 },
      { seasonNumber: 3, nbEpisodes: 22, totalLength: 484 },
      { seasonNumber: 4, nbEpisodes: 25, totalLength: 550 },
      { seasonNumber: 5, nbEpisodes: 24, totalLength: 528 },
      { seasonNumber: 6, nbEpisodes: 22, totalLength: 484 },
      { seasonNumber: 7, nbEpisodes: 11, totalLength: 242 },
      { seasonNumber: 8, nbEpisodes: 19, totalLength: 418 },
      { seasonNumber: 9, nbEpisodes: 13, totalLength: 286 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: '24 heures chrono',
    director: 'Joel Surnow, Robert Cochran',
    actors: [
      { name: 'Kiefer Sutherland' },
      { name: 'Mary Lynn Rajskub' },
      { name: 'Carlos Bernard' },
    ],
    coverUrl: '/series_pictures/1e7b35230c0a.jpg',
    releaseDate: '2001-11-06',
    endDate: '2014-07-14',
    genre: ['Action', 'Crime', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 2, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 3, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 4, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 5, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 6, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 7, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 8, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 9, nbEpisodes: 12, totalLength: 720 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Ozark',
    director: 'Bill Dubuque, Mark Williams',
    actors: [
      { name: 'Jason Bateman' },
      { name: 'Laura Linney' },
      { name: 'Julia Garner' },
    ],
    coverUrl: '/series_pictures/a75406d8f258.jpg',
    releaseDate: '2017-07-21',
    endDate: '2022-04-29',
    genre: ['Crime', 'Drama', 'Thriller'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 4, nbEpisodes: 14, totalLength: 840 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Westworld',
    director: 'Jonathan Nolan, Lisa Joy',
    actors: [
      { name: 'Evan Rachel Wood' },
      { name: 'Thandiwe Newton' },
      { name: 'Jeffrey Wright' },
    ],
    coverUrl: '/series_pictures/863f351f8bb9.jpg',
    releaseDate: '2016-10-02',
    endDate: '2022-08-14',
    genre: ['Drama', 'Mystery', 'Sci-Fi'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 3, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 4, nbEpisodes: 8, totalLength: 480 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'LOST : Les disparus',
    director: 'J.J. Abrams, Damon Lindelof, Carlton Cuse',
    actors: [
      { name: 'Matthew Fox' },
      { name: 'Evangeline Lilly' },
      { name: 'Josh Holloway' },
    ],
    coverUrl: '/series_pictures/5b90f393595c.png',
    releaseDate: '2004-09-22',
    endDate: '2010-05-23',
    genre: ['Adventure', 'Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 25, totalLength: 1500 },
      { seasonNumber: 2, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 3, nbEpisodes: 23, totalLength: 1380 },
      { seasonNumber: 4, nbEpisodes: 14, totalLength: 840 },
      { seasonNumber: 5, nbEpisodes: 17, totalLength: 1020 },
      { seasonNumber: 6, nbEpisodes: 18, totalLength: 1080 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Prison Break',
    director: 'Paul Scheuring',
    actors: [
      { name: 'Wentworth Miller' },
      { name: 'Dominic Purcell' },
      { name: 'Sarah Wayne Callies' },
    ],
    coverUrl: '/series_pictures/3048c62038bf.jpg',
    releaseDate: '2005-08-29',
    endDate: '2017-05-30',
    genre: ['Action', 'Crime', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 3, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 4, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 5, nbEpisodes: 9, totalLength: 540 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Californication',
    director: 'Tom Kapinos',
    actors: [
      { name: 'David Duchovny' },
      { name: 'Natascha McElhone' },
      { name: 'Evan Handler' },
    ],
    coverUrl: '/series_pictures/eba6cecc74d8.jpg',
    releaseDate: '2007-08-13',
    endDate: '2014-06-29',
    genre: ['Comedy', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 2, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 3, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 4, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 5, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 6, nbEpisodes: 12, totalLength: 360 },
      { seasonNumber: 7, nbEpisodes: 12, totalLength: 360 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Dix pour cent',
    director: 'Fanny Herrero',
    actors: [
      { name: 'Camille Cottin' },
      { name: 'Thibault de Montalembert' },
      { name: 'Grégory Montel' },
    ],
    coverUrl: '/series_pictures/77d2407491a5.jpg',
    releaseDate: '2015-10-14',
    endDate: '2020-11-04',
    genre: ['Comedy', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 6, totalLength: 360 },
      { seasonNumber: 2, nbEpisodes: 6, totalLength: 360 },
      { seasonNumber: 3, nbEpisodes: 6, totalLength: 360 },
      { seasonNumber: 4, nbEpisodes: 6, totalLength: 360 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'France',
  },
  {
    title: 'Chuck',
    director: 'Josh Schwartz, Chris Fedak',
    actors: [
      { name: 'Zachary Levi' },
      { name: 'Yvonne Strahovski' },
      { name: 'Adam Baldwin' },
    ],
    coverUrl: '/series_pictures/01fca2c39e5c.jpg',
    releaseDate: '2007-09-24',
    endDate: '2012-01-27',
    genre: ['Action', 'Comedy', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 3, nbEpisodes: 19, totalLength: 1140 },
      { seasonNumber: 4, nbEpisodes: 24, totalLength: 1440 },
      { seasonNumber: 5, nbEpisodes: 13, totalLength: 780 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Skins',
    director: 'Bryan Elsley, Jamie Brittain',
    actors: [
      { name: 'Nicholas Hoult' },
      { name: 'Kaya Scodelario' },
      { name: 'Hannah Murray' },
    ],
    coverUrl: '/series_pictures/ed303428a3ea.jpg',
    releaseDate: '2007-01-25',
    endDate: '2013-08-05',
    genre: ['Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 9, totalLength: 540 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 4, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 5, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 6, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 7, nbEpisodes: 6, totalLength: 360 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Royaume-Uni',
  },
  {
    title: 'Trigun',
    director: 'Satoshi Nishimura',
    actors: [
      { name: 'Tomokazu Seki' },
      { name: 'Hiroyuki Yoshino' },
      { name: 'Satsuki Yukino' },
    ],
    coverUrl: '/series_pictures/80fee1f3b947.jpg',
    releaseDate: '1998-04-01',
    endDate: '1998-09-30',
    genre: ['Action', 'Animation', 'Sci-Fi'],
    seasonsData: [{ seasonNumber: 1, nbEpisodes: 26, totalLength: 650 }],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Japon',
  },
  {
    title: 'Code Quantum',
    director: 'Donald P. Bellisario',
    actors: [
      { name: 'Scott Bakula' },
      { name: 'Dean Stockwell' },
      { name: 'Deborah Pratt' },
    ],
    coverUrl: '/series_pictures/da74fb185529.jpg',
    releaseDate: '1989-03-26',
    endDate: '1993-05-05',
    genre: ['Action', 'Adventure', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 3, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 4, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 5, nbEpisodes: 22, totalLength: 1320 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Il était une fois... La vie',
    director: 'Albert Barillé',
    actors: [
      { name: 'Roger Carel' },
      { name: 'Gilles Laurent' },
      { name: 'Marie-Laure Beneston' },
    ],
    coverUrl: '/series_pictures/de6b1657bf93.jpg',
    releaseDate: '1987-09-14',
    endDate: '1988-04-06',
    genre: ['Animation', 'Family', 'Education'],
    seasonsData: [{ seasonNumber: 1, nbEpisodes: 26, totalLength: 650 }],
    description: '',
    fromEntity: null,
    saga: 'Il était une fois',
    countryOrigin: 'France',
  },
  {
    title: 'Sex Education',
    director: 'Laurie Nunn',
    actors: [
      { name: 'Asa Butterfield' },
      { name: 'Gillian Anderson' },
      { name: 'Ncuti Gatwa' },
    ],
    coverUrl: '/series_pictures/0aabd6ad5d0c.jpg',
    releaseDate: '2019-01-11',
    endDate: '2023-09-21',
    genre: ['Comedy', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 2, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 3, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 4, nbEpisodes: 8, totalLength: 480 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Royaume-Uni',
  },
  {
    title: 'Euphoria',
    director: 'Sam Levinson',
    actors: [
      { name: 'Zendaya' },
      { name: 'Hunter Schafer' },
      { name: 'Jacob Elordi' },
    ],
    coverUrl: '/series_pictures/d45e7f46d205.jpg',
    releaseDate: '2019-06-16',
    endDate: '2024-05-19',
    genre: ['Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 2, nbEpisodes: 8, totalLength: 480 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Peacemaker',
    director: 'James Gunn',
    actors: [
      { name: 'John Cena' },
      { name: 'Danielle Brooks' },
      { name: 'Freddie Stroma' },
    ],
    coverUrl: '/series_pictures/36c0ae0fb7be.jpg',
    releaseDate: '2022-01-13',
    endDate: '2022-02-17',
    genre: ['Action', 'Comedy', 'Sci-Fi'],
    seasonsData: [{ seasonNumber: 1, nbEpisodes: 8, totalLength: 480 }],
    description: '',
    fromEntity: null,
    saga: 'DC Comics',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'McGyver',
    director: 'Lee David Zlotoff',
    actors: [
      { name: 'Richard Dean Anderson' },
      { name: 'Dana Elcar' },
      { name: 'Bruce McGill' },
    ],
    coverUrl:
      '/series_pictures/7779fd16a5b2.jpg',
    releaseDate: '1985-09-29',
    endDate: '1992-04-25',
    genre: ['Action', 'Adventure'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 22, totalLength: 1056 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 1056 },
      { seasonNumber: 3, nbEpisodes: 20, totalLength: 960 },
      { seasonNumber: 4, nbEpisodes: 19, totalLength: 912 },
      { seasonNumber: 5, nbEpisodes: 18, totalLength: 864 },
      { seasonNumber: 6, nbEpisodes: 21, totalLength: 1008 },
      { seasonNumber: 7, nbEpisodes: 14, totalLength: 672 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Murder',
    director: 'Peter Nowalk',
    actors: [
      { name: 'Viola Davis' },
      { name: 'Billy Brown' },
      { name: 'Jack Falahee' },
    ],
    coverUrl:
      '/series_pictures/b84eb712a5d0.jpg',
    releaseDate: '2014-09-25',
    endDate: '2020-05-14',
    genre: ['Crime', 'Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 15, totalLength: 675 },
      { seasonNumber: 2, nbEpisodes: 15, totalLength: 675 },
      { seasonNumber: 3, nbEpisodes: 18, totalLength: 810 },
      { seasonNumber: 4, nbEpisodes: 15, totalLength: 675 },
      { seasonNumber: 5, nbEpisodes: 15, totalLength: 675 },
      { seasonNumber: 6, nbEpisodes: 15, totalLength: 675 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Family Guy',
    director: 'Seth MacFarlane',
    actors: [
      { name: 'Seth MacFarlane' },
      { name: 'Alex Borstein' },
      { name: 'Mila Kunis' },
    ],
    coverUrl:
      '/series_pictures/904738e4a8e5.jpg',
    releaseDate: '1999-01-31',
    endDate: '',
    genre: ['Animation', 'Comedy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 20, totalLength: 440 },
      { seasonNumber: 2, nbEpisodes: 20, totalLength: 440 },
      { seasonNumber: 3, nbEpisodes: 20, totalLength: 440 },
      { seasonNumber: 4, nbEpisodes: 20, totalLength: 440 },
      { seasonNumber: 5, nbEpisodes: 20, totalLength: 440 },
      { seasonNumber: 6, nbEpisodes: 20, totalLength: 440 },
      { seasonNumber: 7, nbEpisodes: 20, totalLength: 440 },
      { seasonNumber: 8, nbEpisodes: 20, totalLength: 440 },
      { seasonNumber: 9, nbEpisodes: 20, totalLength: 440 },
      { seasonNumber: 10, nbEpisodes: 20, totalLength: 440 },
      { seasonNumber: 11, nbEpisodes: 20, totalLength: 440 },
      { seasonNumber: 12, nbEpisodes: 20, totalLength: 440 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Bates Motel',
    director: 'Carlton Cuse, Kerry Ehrin',
    actors: [
      { name: 'Vera Farmiga' },
      { name: 'Freddie Highmore' },
      { name: 'Max Thieriot' },
    ],
    coverUrl:
      '/series_pictures/fc69f638c59b.jpg',
    releaseDate: '2013-03-18',
    endDate: '2017-04-24',
    genre: ['Drama', 'Horror', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 500 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 500 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 500 },
      { seasonNumber: 4, nbEpisodes: 10, totalLength: 500 },
      { seasonNumber: 5, nbEpisodes: 10, totalLength: 500 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Misfits',
    director: 'Howard Overman',
    actors: [
      { name: 'Nathan Stewart-Jarrett' },
      { name: 'Joseph Gilgun' },
      { name: 'Iwan Rheon' },
    ],
    coverUrl:
      '/series_pictures/da3c199536a1.jpg',
    releaseDate: '2009-11-12',
    endDate: '2013-12-11',
    genre: ['Comedy', 'Drama', 'Fantasy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 6, totalLength: 360 },
      { seasonNumber: 2, nbEpisodes: 7, totalLength: 420 },
      { seasonNumber: 3, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 4, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 5, nbEpisodes: 8, totalLength: 480 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Royaume-Uni',
  },
  {
    title: 'NCIS',
    director: 'Donald P. Bellisario',
    actors: [
      { name: 'Mark Harmon' },
      { name: 'Pauley Perrette' },
      { name: 'Michael Weatherly' },
    ],
    coverUrl:
      '/series_pictures/5cc91aa9b418.jpg',
    releaseDate: '2003-09-23',
    endDate: '',
    genre: ['Crime', 'Drama', 'Action'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 2, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 3, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 4, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 5, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 6, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 7, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 8, nbEpisodes: 24, totalLength: 1080 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Wakfu',
    director: 'Anthony Roux',
    actors: [
      { name: 'Geneviève Doang' },
      { name: 'Thomas Guitard' },
      { name: 'Adeline Chetail' },
    ],
    coverUrl:
      '/series_pictures/8b763cc9467e.jpg',
    releaseDate: '2008-10-30',
    endDate: '',
    genre: ['Animation', 'Adventure', 'Fantasy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 26, totalLength: 650 },
      { seasonNumber: 2, nbEpisodes: 26, totalLength: 650 },
      { seasonNumber: 3, nbEpisodes: 13, totalLength: 325 },
      { seasonNumber: 4, nbEpisodes: 13, totalLength: 325 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'France',
  },
  {
    title: 'Godfather of Harlem',
    director: 'Chris Brancato, Paul Eckstein',
    actors: [
      { name: 'Forest Whitaker' },
      { name: 'Nigel Thatch' },
      { name: 'Ilfenesh Hadera' },
    ],
    coverUrl:
      '/series_pictures/904945330521.jpg',
    releaseDate: '2019-09-29',
    endDate: '',
    genre: ['Crime', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 600 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'La traque dans le sang',
    director: 'Kim Joo-hwan',
    actors: [
      { name: 'Woo Do-hwan' },
      { name: 'Lee Sang-yi' },
      { name: 'Park Sung-woong' },
    ],
    coverUrl:
      '/series_pictures/9548f6958cb1.jpg',
    releaseDate: '2023-06-09',
    endDate: '',
    genre: ['Action', 'Crime', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 2, nbEpisodes: 7, totalLength: 420 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Corée du Sud',
  },
  {
    title: 'Lie to Me',
    director: 'Samuel Baum',
    actors: [
      { name: 'Tim Roth' },
      { name: 'Kelli Williams' },
      { name: 'Brendan Hines' },
    ],
    coverUrl:
      '/series_pictures/1812efd4dafd.jpg',
    releaseDate: '2009-01-21',
    endDate: '2011-01-31',
    genre: ['Crime', 'Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 13, totalLength: 780 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 1320 },
      { seasonNumber: 3, nbEpisodes: 13, totalLength: 780 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Looney Tunes Cartoon',
    director: 'Pete Browngardt',
    actors: [
      { name: 'Eric Bauza' },
      { name: 'Bob Bergen' },
      { name: 'Jeff Bergman' },
    ],
    coverUrl:
      '/series_pictures/680f6168b27b.jpg',
    releaseDate: '2020-05-27',
    endDate: '',
    genre: ['Animation', 'Comedy', 'Family'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 200 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 200 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 200 },
      { seasonNumber: 4, nbEpisodes: 9, totalLength: 180 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Tom & Jerry',
    director: 'William Hanna, Joseph Barbera',
    actors: [
      { name: 'William Hanna' },
      { name: 'Joseph Barbera' },
      { name: 'June Foray' },
    ],
    coverUrl:
      '/series_pictures/a1cc2045ca0a.jpg',
    releaseDate: '1940-02-10',
    endDate: '',
    genre: ['Animation', 'Comedy', 'Family'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 26, totalLength: 390 },
      { seasonNumber: 2, nbEpisodes: 26, totalLength: 390 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Bip Bip & Le Coyotte',
    director: 'Chuck Jones',
    actors: [
      { name: 'Mel Blanc' },
      { name: 'Paul Julian' },
      { name: 'June Foray' },
    ],
    coverUrl:
      '/series_pictures/11dbbebf9bf5.jpg',
    releaseDate: '1966-09-17',
    endDate: '1973-09-01',
    genre: ['Animation', 'Comedy', 'Family'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 16, totalLength: 240 },
      { seasonNumber: 2, nbEpisodes: 16, totalLength: 240 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'La famille Addams',
    director: 'David Levy',
    actors: [
      { name: 'John Astin' },
      { name: 'Carolyn Jones' },
      { name: 'Jackie Coogan' },
    ],
    coverUrl:
      '/series_pictures/7ba5f61e0af1.jpg',
    releaseDate: '1964-09-18',
    endDate: '1966-04-08',
    genre: ['Comedy', 'Family', 'Fantasy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 34, totalLength: 850 },
      { seasonNumber: 2, nbEpisodes: 30, totalLength: 750 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Good Doctor',
    director: 'David Shore',
    actors: [
      { name: 'Freddie Highmore' },
      { name: 'Hill Harper' },
      { name: 'Richard Schiff' },
    ],
    coverUrl:
      '/series_pictures/3c79fdc660b5.jpg',
    releaseDate: '2017-09-25',
    endDate: '2024-05-21',
    genre: ['Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 3, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 4, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 5, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 6, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 7, nbEpisodes: 22, totalLength: 990 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Scooby-Doo',
    director: 'Joe Ruby, Ken Spears',
    actors: [
      { name: 'Don Messick' },
      { name: 'Casey Kasem' },
      { name: 'Frank Welker' },
    ],
    coverUrl:
      '/series_pictures/e832ef89e817.jpg',
    releaseDate: '1969-09-13',
    endDate: '1978-10-28',
    genre: ['Animation', 'Comedy', 'Family'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 17, totalLength: 425 },
      { seasonNumber: 2, nbEpisodes: 8, totalLength: 200 },
      { seasonNumber: 3, nbEpisodes: 16, totalLength: 400 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Ranma 1/2',
    director: 'Rumiko Takahashi',
    actors: [
      { name: 'Kappei Yamaguchi' },
      { name: 'Megumi Hayashibara' },
      { name: 'Noriko Hidaka' },
    ],
    coverUrl: '/series_pictures/7849c7837269.jpg',
    releaseDate: '1989-04-15',
    endDate: '1992-09-16',
    genre: ['Animation', 'Action', 'Comedy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 18, totalLength: 450 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 550 },
      { seasonNumber: 3, nbEpisodes: 22, totalLength: 550 },
      { seasonNumber: 4, nbEpisodes: 24, totalLength: 600 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Japon',
  },
  {
    title: 'Le laboratoire de Dexter',
    director: 'Genndy Tartakovsky',
    actors: [
      { name: 'Christine Cavanaugh' },
      { name: 'Allison Moore' },
      { name: 'Kath Soucie' },
    ],
    coverUrl:
      '/series_pictures/e2d53b52a8dc.jpg',
    releaseDate: '1996-04-28',
    endDate: '2003-11-20',
    genre: ['Animation', 'Comedy', 'Family'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 13, totalLength: 286 },
      { seasonNumber: 2, nbEpisodes: 39, totalLength: 858 },
      { seasonNumber: 3, nbEpisodes: 35, totalLength: 770 },
      { seasonNumber: 4, nbEpisodes: 35, totalLength: 770 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Marco Polo',
    director: 'John Fusco',
    actors: [
      { name: 'Lorenzo Richelmy' },
      { name: 'Benedict Wong' },
      { name: 'Joan Chen' },
    ],
    coverUrl:
      '/series_pictures/78d98be5d81f.jpg',
    releaseDate: '2014-12-12',
    endDate: '2016-07-01',
    genre: ['Adventure', 'Drama', 'History'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 600 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Kengan Ashura',
    director: 'Seiji Kishi',
    actors: [
      { name: 'Kaiji Tang' },
      { name: 'Erika Harlacher' },
      { name: 'Todd Haberkorn' },
    ],
    coverUrl:
      '/series_pictures/873a958f9c44.jpg',
    releaseDate: '2019-07-31',
    endDate: '',
    genre: ['Animation', 'Action', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 12, totalLength: 288 },
      { seasonNumber: 2, nbEpisodes: 12, totalLength: 288 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Japon',
  },
  {
    title: 'American Horror Story',
    director: 'Ryan Murphy, Brad Falchuk',
    actors: [
      { name: 'Sarah Paulson' },
      { name: 'Evan Peters' },
      { name: 'Jessica Lange' },
    ],
    coverUrl:
      '/series_pictures/5b85b6fc1724.jpg',
    releaseDate: '2011-10-05',
    endDate: '',
    genre: ['Drama', 'Horror', 'Thriller'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 2, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 3, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 4, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 5, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 6, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 7, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 8, nbEpisodes: 12, totalLength: 720 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Santa Clarita Diet',
    director: 'Victor Fresco',
    actors: [
      { name: 'Drew Barrymore' },
      { name: 'Timothy Olyphant' },
      { name: 'Liv Hewson' },
    ],
    coverUrl:
      '/series_pictures/d1c61031a650.jpg',
    releaseDate: '2017-02-03',
    endDate: '2019-03-29',
    genre: ['Comedy', 'Horror'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 10, totalLength: 500 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 500 },
      { seasonNumber: 3, nbEpisodes: 10, totalLength: 500 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Les frères Scott',
    director: 'Mark Schwahn',
    actors: [
      { name: 'Chad Michael Murray' },
      { name: 'James Lafferty' },
      { name: 'Hilarie Burton' },
    ],
    coverUrl:
      '/series_pictures/eba3b892327d.jpg',
    releaseDate: '2003-09-23',
    endDate: '2012-04-04',
    genre: ['Drama', 'Romance', 'Sport'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 3, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 4, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 5, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 6, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 7, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 8, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 9, nbEpisodes: 22, totalLength: 990 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Bones',
    director: 'Hart Hanson',
    actors: [
      { name: 'Emily Deschanel' },
      { name: 'David Boreanaz' },
      { name: 'Michaela Conlin' },
    ],
    coverUrl:
      '/series_pictures/e0f2b7ae88cf.jpg',
    releaseDate: '2005-09-13',
    endDate: '2017-03-28',
    genre: ['Crime', 'Drama', 'Comedy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 2, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 3, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 4, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 5, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 6, nbEpisodes: 24, totalLength: 1080 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Alice in borderland',
    director: 'Shinsuke Sato',
    actors: [
      { name: 'Kento Yamazaki' },
      { name: 'Tao Tsuchiya' },
      { name: 'Nijirô Murakami' },
    ],
    coverUrl:
      '/series_pictures/3244cebe575f.jpg',
    releaseDate: '2020-12-10',
    endDate: '',
    genre: ['Action', 'Drama', 'Sci-Fi'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 2, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 3, nbEpisodes: 8, totalLength: 480 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'Japon',
  },
  {
    title: 'Once Upon a Time',
    director: 'Edward Kitsis, Adam Horowitz',
    actors: [
      { name: 'Ginnifer Goodwin' },
      { name: 'Jennifer Morrison' },
      { name: 'Lana Parrilla' },
    ],
    coverUrl:
      '/series_pictures/271ad4a03d2b.jpg',
    releaseDate: '2011-10-23',
    endDate: '2018-05-18',
    genre: ['Adventure', 'Drama', 'Fantasy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 3, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 4, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 5, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 6, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 7, nbEpisodes: 22, totalLength: 990 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Young Sheldon',
    director: 'Chuck Lorre, Steven Molaro',
    actors: [
      { name: 'Iain Armitage' },
      { name: 'Zoe Perry' },
      { name: 'Lance Barber' },
    ],
    coverUrl:
      '/series_pictures/bb37ff6d1aee.jpg',
    releaseDate: '2017-09-25',
    endDate: '2024-05-16',
    genre: ['Comedy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 22, totalLength: 495 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 495 },
      { seasonNumber: 3, nbEpisodes: 22, totalLength: 495 },
      { seasonNumber: 4, nbEpisodes: 22, totalLength: 495 },
      { seasonNumber: 5, nbEpisodes: 22, totalLength: 495 },
      { seasonNumber: 6, nbEpisodes: 22, totalLength: 495 },
      { seasonNumber: 7, nbEpisodes: 22, totalLength: 495 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Les Experts',
    director: 'Anthony E. Zuiker',
    actors: [
      { name: 'William Petersen' },
      { name: 'Marg Helgenberger' },
      { name: 'George Eads' },
    ],
    coverUrl:
      '/series_pictures/e776ad28527f.jpg',
    releaseDate: '2000-10-06',
    endDate: '2015-09-27',
    genre: ['Crime', 'Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 2, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 3, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 4, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 5, nbEpisodes: 24, totalLength: 1080 },
      { seasonNumber: 6, nbEpisodes: 24, totalLength: 1080 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Borgia',
    director: 'Tom Fontana',
    actors: [
      { name: 'John Doman' },
      { name: 'Mark Ryder' },
      { name: 'Isolda Dychauk' },
    ],
    coverUrl:
      '/series_pictures/413740a8e651.jpg',
    releaseDate: '2011-04-04',
    endDate: '2014-11-18',
    genre: ['Drama', 'History'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 2, nbEpisodes: 12, totalLength: 720 },
      { seasonNumber: 3, nbEpisodes: 14, totalLength: 840 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'France',
  },
  {
    title: 'Les Désastreuses aventures des orphelins Baudelaire',
    director: 'Barry Sonnenfeld, Mark Hudis',
    actors: [
      { name: 'Neil Patrick Harris' },
      { name: 'Patrick Warburton' },
      { name: 'Malina Weissman' },
    ],
    coverUrl:
      '/series_pictures/b3cdf300c701.jpg',
    releaseDate: '2017-01-13',
    endDate: '2019-01-01',
    genre: ['Adventure', 'Comedy', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 480 },
      { seasonNumber: 2, nbEpisodes: 10, totalLength: 600 },
      { seasonNumber: 3, nbEpisodes: 7, totalLength: 420 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Scandal',
    director: 'Shonda Rhimes',
    actors: [
      { name: 'Kerry Washington' },
      { name: 'Darby Stanchfield' },
      { name: 'Katie Lowes' },
    ],
    coverUrl:
      '/series_pictures/7b2d3781a0c6.jpg',
    releaseDate: '2012-04-05',
    endDate: '2018-04-19',
    genre: ['Drama', 'Thriller'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 3, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 4, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 5, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 6, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 7, nbEpisodes: 22, totalLength: 990 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Poupée russe',
    director: 'Leslye Headland, Natasha Lyonne, Amy Poehler',
    actors: [
      { name: 'Natasha Lyonne' },
      { name: 'Charlie Barnett' },
      { name: 'Greta Lee' },
    ],
    coverUrl:
      '/series_pictures/b7d27675461b.jpg',
    releaseDate: '2019-02-01',
    endDate: '2022-04-27',
    genre: ['Comedy', 'Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 8, totalLength: 240 },
      { seasonNumber: 2, nbEpisodes: 8, totalLength: 240 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Hé Arnold !',
    director: 'Craig Bartlett',
    actors: [
      { name: 'Francesca Marie Smith' },
      { name: 'Jamil Walker Smith' },
      { name: 'Spencer Klein' },
    ],
    coverUrl:
      '/series_pictures/3d475d155cb3.jpg',
    releaseDate: '1996-10-07',
    endDate: '2004-06-28',
    genre: ['Animation', 'Comedy', 'Drama'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 20, totalLength: 500 },
      { seasonNumber: 2, nbEpisodes: 20, totalLength: 500 },
      { seasonNumber: 3, nbEpisodes: 20, totalLength: 500 },
      { seasonNumber: 4, nbEpisodes: 20, totalLength: 500 },
      { seasonNumber: 5, nbEpisodes: 20, totalLength: 500 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Alias',
    director: 'J.J. Abrams',
    actors: [
      { name: 'Jennifer Garner' },
      { name: 'Michael Vartan' },
      { name: 'Victor Garber' },
    ],
    coverUrl:
      '/series_pictures/ba706c731a92.jpg',
    releaseDate: '2001-09-30',
    endDate: '2006-05-22',
    genre: ['Action', 'Drama', 'Mystery'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 3, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 4, nbEpisodes: 22, totalLength: 990 },
      { seasonNumber: 5, nbEpisodes: 22, totalLength: 990 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Deux flics à Miami',
    director: 'Anthony Yerkovich',
    actors: [
      { name: 'Don Johnson' },
      { name: 'Philip Michael Thomas' },
      { name: 'Saundra Santiago' },
    ],
    coverUrl:
      '/series_pictures/ac7c0b7adfa2.jpg',
    releaseDate: '1984-09-16',
    endDate: '1989-05-21',
    genre: ['Crime', 'Drama', 'Thriller'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 22, totalLength: 1100 },
      { seasonNumber: 2, nbEpisodes: 22, totalLength: 1100 },
      { seasonNumber: 3, nbEpisodes: 22, totalLength: 1100 },
      { seasonNumber: 4, nbEpisodes: 22, totalLength: 1100 },
      { seasonNumber: 5, nbEpisodes: 22, totalLength: 1100 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Stargate : Universe',
    director: 'Robert C. Cooper, Brad Wright',
    actors: [
      { name: 'Robert Carlyle' },
      { name: 'Louis Ferreira' },
      { name: 'Brian J. Smith' },
    ],
    coverUrl:
      '/series_pictures/dbff25252b53.jpg',
    releaseDate: '2009-10-02',
    endDate: '2011-05-09',
    genre: ['Drama', 'Sci-Fi'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 20, totalLength: 1200 },
      { seasonNumber: 2, nbEpisodes: 20, totalLength: 1200 },
    ],
    description: '',
    fromEntity: null,
    saga: 'Stargate',
    countryOrigin: 'États-Unis',
  },
  {
    title: 'Fais pas ci, fais pas ça',
    director: 'Pascal Lièvre, Camille Chamoux',
    actors: [
      { name: 'Valérie Bonneton' },
      { name: 'Guilaine Londez' },
      { name: 'Liliane Rovère' },
    ],
    coverUrl:
      '/series_pictures/b90a75b929f0.jpg',
    releaseDate: '2006-10-09',
    endDate: '2017-02-06',
    genre: ['Comedy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 4, totalLength: 200 },
      { seasonNumber: 2, nbEpisodes: 4, totalLength: 200 },
      { seasonNumber: 3, nbEpisodes: 4, totalLength: 200 },
      { seasonNumber: 4, nbEpisodes: 4, totalLength: 200 },
      { seasonNumber: 5, nbEpisodes: 4, totalLength: 200 },
      { seasonNumber: 6, nbEpisodes: 4, totalLength: 200 },
      { seasonNumber: 7, nbEpisodes: 4, totalLength: 200 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'France',
  },
  {
    title: 'SODA',
    director: 'Kyan Khojandi, Ramzy Bedia',
    actors: [
      { name: 'Kyan Khojandi' },
      { name: 'Alice Isaaz' },
      { name: 'Laurent Capelluto' },
    ],
    coverUrl: '/series_pictures/9b51c14eaaf2.jpg',
    releaseDate: '2011-07-05',
    endDate: '2014-11-04',
    genre: ['Comedy'],
    seasonsData: [
      { seasonNumber: 1, nbEpisodes: 35, totalLength: 700 },
      { seasonNumber: 2, nbEpisodes: 35, totalLength: 700 },
      { seasonNumber: 3, nbEpisodes: 35, totalLength: 700 },
      { seasonNumber: 4, nbEpisodes: 35, totalLength: 700 },
    ],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'France',
  },
  {
    title: 'Peepoodo & The Super Fuck Friends',
    director: 'Balak, Michaël Sanlaville, Vivien Bruneau',
    actors: [
      { name: 'Monsieur Poulpe' },
      { name: 'Frédéric Molas' },
      { name: 'Guillaume Pley' },
    ],
    coverUrl:
      '/series_pictures/581468ad1dc0.jpg',
    releaseDate: '2018-07-16',
    endDate: '',
    genre: ['Animation', 'Comedy'],
    seasonsData: [{ seasonNumber: 1, nbEpisodes: 18, totalLength: 180 }],
    description: '',
    fromEntity: null,
    saga: '',
    countryOrigin: 'France',
  },
];
