const rawData = [
  { title: 'Titre', artist: 'Artiste', duration: '' },
  { title: 'Time', artist: 'Hans Zimmer', duration: '4:35' },
  { title: 'Cornfield Chase', artist: 'Hans Zimmer', duration: '2:06' },
  { title: 'Day One', artist: 'Hans Zimmer', duration: '3:19' },
  {
    title: 'The Breaking of the Fellowship (feat. "In Dreams")',
    artist: 'Howard Shore, Edward Ross',
    duration: '7:20',
  },
  {
    title: 'Theme From Jurassic Park',
    artist: 'John Williams',
    duration: '3:27',
  },
  { title: "Hedwig's Theme", artist: 'John Williams', duration: '5:09' },
  {
    title: 'Back To The Future: Back To The Future - From "Back To The Future"',
    artist: 'Alan Silvestri',
    duration: '3:30',
  },
  { title: 'Autobots', artist: 'Steve Jablonsky', duration: '2:33' },
  {
    title: 'No Sacrifice, No Victory',
    artist: 'Steve Jablonsky',
    duration: '2:57',
  },
  { title: 'The Batman Theme', artist: 'Danny Elfman', duration: '2:38' },
  {
    title: 'Spider-Man 2 Main Title',
    artist: 'Danny Elfman',
    duration: '3:21',
  },
  { title: 'End Credits', artist: 'Danny Elfman', duration: '1:54' },
  { title: 'Main Title', artist: 'Ramin Djawadi', duration: '1:46' },
  { title: 'Finale', artist: 'Ramin Djawadi', duration: '2:31' },
  { title: 'The Avengers', artist: 'Alan Silvestri', duration: '2:03' },
  {
    title: 'Becoming one of "The People" Becoming one with Neytiri',
    artist: 'James Horner',
    duration: '7:43',
  },
  { title: 'Arrival to Earth', artist: 'Steve Jablonsky', duration: '5:26' },
  { title: 'Concerning Hobbits', artist: 'Howard Shore', duration: '2:55' },
  { title: 'Light of the Seven', artist: 'Ramin Djawadi', duration: '9:49' },
  { title: "Lily's Theme", artist: 'Alexandre Desplat', duration: '2:28' },
  { title: 'Death of Cedric', artist: 'Patrick Doyle', duration: '1:56' },
  {
    title: 'Dumbledore\'s Farewell ("Harry Potter & The Half-Blood Prince")',
    artist: 'Nicholas Hooper',
    duration: '2:22',
  },
  {
    title: "Ezio's Family",
    artist: "Jesper Kyd, Assassin's Creed",
    duration: '3:57',
  },
  {
    title: "Uncharted, Drake's Fortune: Nate's Theme",
    artist: 'Greg Edmonson, Andrew Skeet, London Philharmonic Orchestra',
    duration: '1:52',
  },
  {
    title:
      'The Fellowship Reunited (feat. Sir James Galway, Viggo Mortensen and Renée Fleming)',
    artist: 'Howard Shore',
    duration: '12:18',
  },
  { title: 'Dream Is Collapsing', artist: 'Hans Zimmer', duration: '2:23' },
  { title: 'Iron Man 3', artist: 'Brian Tyler', duration: '2:23' },
  { title: "I'm Big", artist: 'Steve Jablonsky', duration: '2:20' },
  { title: "Rey's Theme", artist: 'John Williams', duration: '3:11' },
  { title: 'Day One', artist: 'Hans Zimmer', duration: '3:19' },
  {
    title: 'A Dark Knight',
    artist: 'Hans Zimmer, James Newton Howard',
    duration: '16:15',
  },
  {
    title: 'My Enemy',
    artist: 'Hans Zimmer, The Magnificent Six, Pharrell Williams, Johnny Marr',
    duration: '8:17',
  },

  { title: 'Titre', artist: 'Artiste', duration: '' },
  { title: "Hedwig's Theme", artist: 'John Williams', duration: '5:09' },
  {
    title: 'Back To The Future: Back To The Future - From "Back To The Future"',
    artist: 'Alan Silvestri',
    duration: '3:30',
  },
  { title: 'Autobots', artist: 'Steve Jablonsky', duration: '2:33' },
  {
    title: 'No Sacrifice, No Victory',
    artist: 'Steve Jablonsky',
    duration: '2:57',
  },
  { title: 'The Batman Theme', artist: 'Danny Elfman', duration: '2:38' },
  {
    title: 'Spider-Man 2 Main Title',
    artist: 'Danny Elfman',
    duration: '3:21',
  },
  { title: 'End Credits', artist: 'Danny Elfman', duration: '1:54' },
  { title: 'Main Title', artist: 'Ramin Djawadi', duration: '1:46' },
  { title: 'Finale', artist: 'Ramin Djawadi', duration: '2:31' },
  { title: 'The Avengers', artist: 'Alan Silvestri', duration: '2:03' },
  {
    title: 'Becoming one of "The People" Becoming one with Neytiri',
    artist: 'James Horner',
    duration: '7:43',
  },
  { title: 'Arrival to Earth', artist: 'Steve Jablonsky', duration: '5:26' },
  { title: 'Concerning Hobbits', artist: 'Howard Shore', duration: '2:55' },
  { title: 'Light of the Seven', artist: 'Ramin Djawadi', duration: '9:49' },
  { title: "Lily's Theme", artist: 'Alexandre Desplat', duration: '2:28' },
  { title: 'Death of Cedric', artist: 'Patrick Doyle', duration: '1:56' },
  {
    title: 'Dumbledore\'s Farewell ("Harry Potter & The Half-Blood Prince")',
    artist: 'Nicholas Hooper',
    duration: '2:22',
  },
  {
    title: "Ezio's Family",
    artist: "Jesper Kyd, Assassin's Creed",
    duration: '3:57',
  },
  {
    title: "Uncharted, Drake's Fortune: Nate's Theme",
    artist: 'Greg Edmonson, Andrew Skeet, London Philharmonic Orchestra',
    duration: '1:52',
  },
  {
    title:
      'The Fellowship Reunited (feat. Sir James Galway, Viggo Mortensen and Renée Fleming)',
    artist: 'Howard Shore',
    duration: '12:18',
  },
  { title: 'Dream Is Collapsing', artist: 'Hans Zimmer', duration: '2:23' },
  { title: 'Iron Man 3', artist: 'Brian Tyler', duration: '2:23' },
  { title: "I'm Big", artist: 'Steve Jablonsky', duration: '2:20' },
  { title: "Rey's Theme", artist: 'John Williams', duration: '3:11' },
  { title: 'Day One', artist: 'Hans Zimmer', duration: '3:19' },
  {
    title: 'A Dark Knight',
    artist: 'Hans Zimmer, James Newton Howard',
    duration: '16:15',
  },
  {
    title: 'My Enemy',
    artist: 'Hans Zimmer, The Magnificent Six, Pharrell Williams, Johnny Marr',
    duration: '8:17',
  },
  { title: 'Sacrifice', artist: 'Blake Neely', duration: '4:52' },
  {
    title: 'Flight',
    artist: 'Hans Zimmer, Nick Glennie-Smith, Junkie XL, Atli Örvarsson',
    duration: '4:08',
  },
  { title: 'Adagio in D Minor', artist: 'John Murphy', duration: '4:09' },
  { title: 'Heroes', artist: 'Danny Elfman', duration: '2:07' },
  {
    title: 'The Fastest Man Alive - Always Late',
    artist: 'Blake Neely',
    duration: '3:05',
  },
  { title: "At Wit's End", artist: 'Hans Zimmer', duration: '8:05' },
  { title: 'Up Is Down', artist: 'Hans Zimmer', duration: '2:42' },
  { title: 'One Day', artist: 'Hans Zimmer', duration: '4:01' },
  { title: 'Tennessee', artist: 'Hans Zimmer', duration: '3:39' },
  {
    title: 'Now We Are Free',
    artist:
      'Lisa Gerrard, Klaus Badelt, Hans Zimmer, Gavin Greenaway, The Lyndhurst Orchestra, Bruce Fowler, Yvonne S. Moriarty, Walt Fowler, Ladd McIntosh, Elizabeth Finch',
    duration: '4:14',
  },
  {
    title: 'Jake enters his avatar world',
    artist: 'James Horner',
    duration: '5:24',
  },
  { title: 'Infinite White', artist: 'Steve Jablonsky', duration: '3:58' },
  {
    title: 'Anakin vs. Obi-Wan',
    artist: 'John Williams, London Voices, London Symphony Orchestra',
    duration: '3:57',
  },
  {
    title: 'Washington Ending / Raiders March',
    artist: 'John Williams, London Symphony Orchestra',
    duration: '6:51',
  },
  { title: 'Prologue', artist: 'John Williams', duration: '2:10' },
  {
    title: 'Main Title - Alternate',
    artist: 'Alan Silvestri',
    duration: '3:54',
  },
  {
    title: 'Pacific Rim (feat. Tom Morello)',
    artist: 'Ramin Djawadi, Tom Morello',
    duration: '4:55',
  },
  {
    title: 'Misty Mountains',
    artist: 'Richard Armitage, The Dwarf Cast',
    duration: '1:39',
  },
  { title: "You're a Creed", artist: 'Ludwig Göransson', duration: '4:26' },
  {
    title: 'Main Title',
    artist: 'John Paesano, Braden Kimball',
    duration: '1:04',
  },
  {
    title: 'Further',
    artist: 'Brian Tyler, Serena McKinney',
    duration: '4:04',
  },
  { title: "Nate's Theme 3.0", artist: 'Greg Edmonson', duration: '1:47' },
  { title: "A Thief's End", artist: 'Henry Jackman', duration: '1:54' },

  { title: 'Titre', artist: 'Artiste', duration: '' },
  {
    title: 'A Dark Knight',
    artist: 'Hans Zimmer, James Newton Howard',
    duration: '16:15',
  },
  {
    title: 'My Enemy',
    artist: 'Hans Zimmer, The Magnificent Six, Pharrell Williams, Johnny Marr',
    duration: '8:17',
  },
  { title: 'Sacrifice', artist: 'Blake Neely', duration: '4:52' },
  {
    title: 'Flight',
    artist: 'Hans Zimmer, Nick Glennie-Smith, Junkie XL, Atli Örvarsson',
    duration: '4:08',
  },
  { title: 'Adagio in D Minor', artist: 'John Murphy', duration: '4:09' },
  { title: 'Heroes', artist: 'Danny Elfman', duration: '2:07' },
  {
    title: 'The Fastest Man Alive - Always Late',
    artist: 'Blake Neely',
    duration: '3:05',
  },
  { title: "At Wit's End", artist: 'Hans Zimmer', duration: '8:05' },
  { title: 'Up Is Down', artist: 'Hans Zimmer', duration: '2:42' },
  { title: 'One Day', artist: 'Hans Zimmer', duration: '4:01' },
  { title: 'Tennessee', artist: 'Hans Zimmer', duration: '3:39' },
  {
    title: 'Now We Are Free',
    artist:
      'Lisa Gerrard, Klaus Badelt, Hans Zimmer, Gavin Greenaway, The Lyndhurst Orchestra, Bruce Fowler, Yvonne S. Moriarty, Walt Fowler, Ladd McIntosh, Elizabeth Finch',
    duration: '4:14',
  },
  {
    title: 'Jake enters his avatar world',
    artist: 'James Horner',
    duration: '5:24',
  },
  { title: 'Infinite White', artist: 'Steve Jablonsky', duration: '3:58' },
  {
    title: 'Anakin vs. Obi-Wan',
    artist: 'John Williams, London Voices, London Symphony Orchestra',
    duration: '3:57',
  },
  {
    title: 'Washington Ending / Raiders March',
    artist: 'John Williams, London Symphony Orchestra',
    duration: '6:51',
  },
  { title: 'Prologue', artist: 'John Williams', duration: '2:10' },
  {
    title: 'Main Title - Alternate',
    artist: 'Alan Silvestri',
    duration: '3:54',
  },
  {
    title: 'Pacific Rim (feat. Tom Morello)',
    artist: 'Ramin Djawadi, Tom Morello',
    duration: '4:55',
  },
  {
    title: 'Misty Mountains',
    artist: 'Richard Armitage, The Dwarf Cast',
    duration: '1:39',
  },
  { title: "You're a Creed", artist: 'Ludwig Göransson', duration: '4:26' },
  {
    title: 'Main Title',
    artist: 'John Paesano, Braden Kimball',
    duration: '1:04',
  },
  {
    title: 'Further',
    artist: 'Brian Tyler, Serena McKinney',
    duration: '4:04',
  },
  { title: "Nate's Theme 3.0", artist: 'Greg Edmonson', duration: '1:47' },
  { title: "A Thief's End", artist: 'Henry Jackman', duration: '1:54' },
  { title: 'Emma', artist: 'Steven Price', duration: '2:35' },
  {
    title: 'Into the Water',
    artist:
      'Alberto Iglesias, Nicholas Dodd, American Federation of Musicians, London Voices',
    duration: '3:59',
  },
  { title: 'Davy Jones', artist: 'Hans Zimmer', duration: '3:15' },
  { title: 'The Son of Flynn', artist: 'Daft Punk', duration: '1:35' },
  { title: '', artist: '', duration: '-:--' },
  { title: 'Soldiers', artist: 'Kyle Dixon & Michael Stein', duration: '2:09' },
  { title: 'The Born King', artist: 'Daniel Pemberton', duration: '2:30' },
  { title: 'Truth', artist: 'Ramin Djawadi', duration: '3:31' },
  { title: 'Goodbye Brother', artist: 'Ramin Djawadi', duration: '3:07' },
  {
    title: 'What Is Dead May Never Die',
    artist: 'Ramin Djawadi',
    duration: '2:07',
  },
  { title: 'Winter Is Here', artist: 'Ramin Djawadi', duration: '2:54' },
  { title: 'Master of War', artist: 'Ramin Djawadi', duration: '4:49' },
  { title: 'Portals', artist: 'Alan Silvestri', duration: '3:17' },
  { title: 'Porch', artist: 'Alan Silvestri', duration: '0:58' },
  { title: 'Even for You', artist: 'Alan Silvestri', duration: '2:16' },
  { title: 'Becoming the Tomb Raider', artist: 'Junkie XL', duration: '7:15' },
  { title: 'Endings', artist: 'Vince Pope', duration: '1:54' },
  {
    title:
      'Beautiful Lie (From "Batman v Superman: Dawn of Justice" Soundtrack)',
    artist: 'Hans Zimmer, Junkie XL',
    duration: '3:47',
  },
  { title: 'I Have To Try', artist: 'Blake Neely', duration: '4:56' },
  {
    title: "Hope (Xavier's Theme)",
    artist: 'John Ottman, Jeffrey Schindler, American Federation of Musicians',
    duration: '4:48',
  },
  { title: 'Sons of Odin', artist: 'Patrick Doyle', duration: '1:48' },
  { title: 'Gonna Fly Now', artist: 'Bill Conti', duration: '2:50' },
  {
    title: 'The Final Bell - From The "Rocky" Soundtrack',
    artist: 'Bill Conti',
    duration: '1:54',
  },
  {
    title: "The Vikings are Told of Ragnar's Death",
    artist: 'Trevor Morris, Steve Tavaglione',
    duration: '2:06',
  },
  { title: 'Motorball', artist: 'Junkie XL', duration: '5:14' },
  {
    title: 'Hymn to the Sea (From "Titanic" Soundtrack)',
    artist: 'James Horner',
    duration: '6:25',
  },
  {
    title: 'Runaway (HBO® Westworld)',
    artist: 'Ramin Djawadi',
    duration: '2:48',
  },
  {
    title: 'The Tower (Bonus Track)',
    artist: 'Ramin Djawadi',
    duration: '2:33',
  },
  { title: 'Winter Has Come', artist: 'Ramin Djawadi', duration: '3:14' },
  {
    title: "The Birth of the Twins and Padmé's Destiny",
    artist: 'John Williams, London Symphony Orchestra, London Voices',
    duration: '3:37',
  },
  {
    title:
      'Across the Stars (Love Theme from "Star Wars: Attack of the Clones")',
    artist: 'John Williams, London Symphony Orchestra',
    duration: '5:31',
  },
  {
    title: 'Duel of the Fates',
    artist: 'John Williams, London Symphony Orchestra',
    duration: '4:14',
  },
  { title: 'Dragonborn', artist: 'Jeremy Soule', duration: '3:55' },
  {
    title: 'Theme from Superman - Concert Version',
    artist: 'John Williams',
    duration: '4:24',
  },
  {
    title: 'Echoes of the Roman Ruins',
    artist: "Jesper Kyd, Assassin's Creed",
    duration: '2:51',
  },
  {
    title: 'City of Rome',
    artist: "Jesper Kyd, Assassin's Creed",
    duration: '5:32',
  },
  {
    title: "Assassin's Creed III Main Theme",
    artist: "Lorne Balfe, Assassin's Creed",
    duration: '3:06',
  },
  {
    title: "Assassin's Creed IV Black Flag Main Theme",
    artist: "Brian Tyler, Assassin's Creed",
    duration: '2:13',
  },
  {
    title: 'The Ends of the Earth',
    artist: "Brian Tyler, Assassin's Creed",
    duration: '2:53',
  },
  {
    title: 'The Bottle of Solitude',
    artist: "Chris Tilton, Assassin's Creed",
    duration: '3:52',
  },
  { title: 'Harnessing Anger', artist: 'Blake Neely', duration: '2:04' },

  { title: 'Titre', artist: 'Artiste', duration: '' },
  { title: 'Endings', artist: 'Vince Pope', duration: '1:54' },
  {
    title:
      'Beautiful Lie (From "Batman v Superman: Dawn of Justice" Soundtrack)',
    artist: 'Hans Zimmer, Junkie XL',
    duration: '3:47',
  },
  { title: 'I Have To Try', artist: 'Blake Neely', duration: '4:56' },
  {
    title: "Hope (Xavier's Theme)",
    artist: 'John Ottman, Jeffrey Schindler, American Federation of Musicians',
    duration: '4:48',
  },
  { title: 'Sons of Odin', artist: 'Patrick Doyle', duration: '1:48' },
  { title: 'Gonna Fly Now', artist: 'Bill Conti', duration: '2:50' },
  {
    title: 'The Final Bell - From The "Rocky" Soundtrack',
    artist: 'Bill Conti',
    duration: '1:54',
  },
  {
    title: "The Vikings are Told of Ragnar's Death",
    artist: 'Trevor Morris, Steve Tavaglione',
    duration: '2:06',
  },
  { title: 'Motorball', artist: 'Junkie XL', duration: '5:14' },
  {
    title: 'Hymn to the Sea (From "Titanic" Soundtrack)',
    artist: 'James Horner',
    duration: '6:25',
  },
  {
    title: 'Runaway (HBO® Westworld)',
    artist: 'Ramin Djawadi',
    duration: '2:48',
  },
  {
    title: 'The Tower (Bonus Track)',
    artist: 'Ramin Djawadi',
    duration: '2:33',
  },
  { title: 'Winter Has Come', artist: 'Ramin Djawadi', duration: '3:14' },
  {
    title: "The Birth of the Twins and Padmé's Destiny",
    artist: 'John Williams, London Symphony Orchestra, London Voices',
    duration: '3:37',
  },
  {
    title:
      'Across the Stars (Love Theme from "Star Wars: Attack of the Clones")',
    artist: 'John Williams, London Symphony Orchestra',
    duration: '5:31',
  },
  {
    title: 'Duel of the Fates',
    artist: 'John Williams, London Symphony Orchestra',
    duration: '4:14',
  },
  { title: 'Dragonborn', artist: 'Jeremy Soule', duration: '3:55' },
  {
    title: 'Theme from Superman - Concert Version',
    artist: 'John Williams',
    duration: '4:24',
  },
  {
    title: 'Echoes of the Roman Ruins',
    artist: "Jesper Kyd, Assassin's Creed",
    duration: '2:51',
  },
  {
    title: 'City of Rome',
    artist: "Jesper Kyd, Assassin's Creed",
    duration: '5:32',
  },
  {
    title: "Assassin's Creed III Main Theme",
    artist: "Lorne Balfe, Assassin's Creed",
    duration: '3:06',
  },
  {
    title: "Assassin's Creed IV Black Flag Main Theme",
    artist: "Brian Tyler, Assassin's Creed",
    duration: '2:13',
  },
  {
    title: 'The Ends of the Earth',
    artist: "Brian Tyler, Assassin's Creed",
    duration: '2:53',
  },
  {
    title: 'The Bottle of Solitude',
    artist: "Chris Tilton, Assassin's Creed",
    duration: '3:52',
  },
  { title: 'Harnessing Anger', artist: 'Blake Neely', duration: '2:04' },
  { title: 'If You Were Flying', artist: 'James Shearman', duration: '2:55' },
  {
    title: 'Winds of Cyrene',
    artist: "Sarah Schachner, Assassin's Creed",
    duration: '4:07',
  },
  {
    title: 'Moonlight on the Nile',
    artist: "Sarah Schachner, Assassin's Creed",
    duration: '1:39',
  },
  {
    title: "Ezio's Family - Origins Version",
    artist: "Sarah Schachner, Assassin's Creed",
    duration: '2:23',
  },
  {
    title: "She'll Kill You",
    artist: 'Kyle Dixon & Michael Stein',
    duration: '2:05',
  },
  { title: 'Mountains', artist: 'Hans Zimmer', duration: '3:39' },
  { title: 'Coward', artist: 'Hans Zimmer', duration: '8:26' },
  {
    title: 'Legend of the Eagle Bearer (Main Theme)',
    artist: "The Flight, Assassin's Creed, Mike Georgiades",
    duration: '3:53',
  },
  {
    title: 'Sentinel Prime (From "Transformers: Dark of the Moon")',
    artist: 'London Music Works',
    duration: '3:10',
  },
  {
    title: 'It\'s Our Fight (From "Transformers: Dark of the Moon")',
    artist: 'London Music Works',
    duration: '6:37',
  },
  {
    title: 'Our Final Hope (From "Transformers: Dark of the Moon")',
    artist: 'London Music Works',
    duration: '3:41',
  },
  { title: 'Gandalf the White', artist: 'Howard Shore', duration: '6:47' },
  {
    title: 'Théoden King / "The Funeral of Théodred" (feat. Miranda Otto)',
    artist: 'Howard Shore, Miranda Otto',
    duration: '6:12',
  },
  {
    title: 'One of the Dúnedain / "Evenstar" (feat. Isabel Bayrakdarian)',
    artist: 'Howard Shore, Isabel Bayrakdarian',
    duration: '7:13',
  },
  { title: "Aragorn's Return", artist: 'Howard Shore', duration: '2:11' },
  {
    title: 'Where Is the Horse and the Rider?',
    artist: 'Howard Shore',
    duration: '6:15',
  },
  { title: 'Sacrifice', artist: 'Steve Jablonsky', duration: '6:46' },
  { title: 'Purity of Heart', artist: 'Steve Jablonsky', duration: '3:34' },
  { title: 'Seglass Ni Tonday', artist: 'Steve Jablonsky', duration: '6:27' },
  { title: 'Cogman Sings', artist: 'Steve Jablonsky', duration: '2:09' },
  { title: 'I Had My Moment', artist: 'Steve Jablonsky', duration: '2:29' },
  {
    title: 'Did You Forget Who I Am',
    artist: 'Steve Jablonsky',
    duration: '1:56',
  },
  { title: 'We Have to Go', artist: 'Steve Jablonsky', duration: '5:48' },
  { title: 'Sir Edmund Burton', artist: 'Steve Jablonsky', duration: '4:10' },
  { title: 'Inner Demon', artist: 'Nick Arundel', duration: '2:01' },
  { title: 'Spread the Word', artist: 'James Newton Howard', duration: '4:01' },
  {
    title: 'Wands into the Earth',
    artist: 'James Newton Howard',
    duration: '4:04',
  },
  {
    title: "Leta's Theme - Solo Piano",
    artist: 'James Newton Howard',
    duration: '2:04',
  },
  {
    title: 'The Grace of Undómiel (feat. Renée Fleming)',
    artist: 'Howard Shore, Renée Fleming',
    duration: '6:21',
  },
  { title: 'Flight from Edoras', artist: 'Howard Shore', duration: '2:18' },
  { title: 'The Siege of Gondor', artist: 'Howard Shore', duration: '9:01' },
  { title: 'Back Together', artist: 'Mark Mothersbaugh', duration: '1:53' },
  { title: 'The Kiss', artist: 'Mark Mothersbaugh', duration: '1:28' },
  { title: 'Over Hill', artist: 'Howard Shore', duration: '3:41' },
  {
    title: 'The Forest River - Extended Version',
    artist: 'Howard Shore',
    duration: '5:10',
  },
  { title: 'Sons Of Durin', artist: 'Howard Shore', duration: '4:24' },
  { title: 'Courage And Wisdom', artist: 'Howard Shore', duration: '5:10' },
  {
    title: 'Ironfoot - Extended Version',
    artist: 'Howard Shore',
    duration: '6:11',
  },
  {
    title: 'The Legend of Excalibur',
    artist: 'Daniel Pemberton',
    duration: '2:43',
  },
  {
    title: 'Sixteen Hundred Men (From "1917" Soundtrack)',
    artist: 'Thomas Newman',
    duration: '6:32',
  },
  {
    title: 'Come Back to Us (From "1917" Soundtrack)',
    artist: 'Thomas Newman',
    duration: '5:39',
  },
  { title: 'Kizuna', artist: 'Yasuharu Takanashi', duration: '2:34' },
  {
    title: 'FAIRY TAIL Main Theme',
    artist: 'Yasuharu Takanashi',
    duration: '2:32',
  },
  { title: 'Dragon Slayer', artist: 'Yasuharu Takanashi', duration: '1:59' },
  { title: "Mirajane's Theme", artist: 'Yasuharu Takanashi', duration: '1:50' },
  { title: 'Shukumei', artist: 'Yasuharu Takanashi', duration: '2:51' },
  { title: 'Kanashiki Kako', artist: 'Yasuharu Takanashi', duration: '2:13' },
  { title: 'Saigo no Mahou', artist: 'Yasuharu Takanashi', duration: '1:35' },
  {
    title: 'Fairy Tail Main Theme - Slow ver.',
    artist: 'Yasuharu Takanashi',
    duration: '2:34',
  },
  {
    title: 'Tsuioku - Mezameru Tamashii -',
    artist: 'Yasuharu Takanashi',
    duration: '3:10',
  },
  { title: 'Seigi no Chikara', artist: 'Yasuharu Takanashi', duration: '2:07' },
  { title: 'A Normal Life', artist: 'Henry Jackman', duration: '1:17' },
  { title: 'The Brothers Drake', artist: 'Henry Jackman', duration: '1:55' },
  { title: 'Epilogue', artist: 'Henry Jackman', duration: '3:17' },
  { title: 'The Lane Family', artist: 'Marco Beltrami', duration: '2:47' },
  {
    title: 'Days Gone (From "Days Gone" Soundtrack)',
    artist: 'Nathan Whitehead',
    duration: '3:41',
  },
  {
    title: 'We\'ve All Done Things (From "Days Gone" Soundtrack)',
    artist: 'Nathan Whitehead',
    duration: '3:36',
  },
  {
    title: 'Light One Candle (From "Days Gone" Soundtrack)',
    artist: 'Nathan Whitehead',
    duration: '1:59',
  },
  {
    title: 'Why We Fight (From "Days Gone" Soundtrack)',
    artist: 'Nathan Whitehead',
    duration: '2:37',
  },
  {
    title: 'The Path of the Wind - Instrumental',
    artist: 'Joe Hisaishi',
    duration: '3:16',
  },
  { title: "Caesar's Home", artist: 'Patrick Doyle', duration: '2:40' },
  { title: 'Paradise Found', artist: 'Michael Giacchino', duration: '5:35' },
  { title: 'Power', artist: 'Joseph Trapanese', duration: '6:01' },
  { title: 'Taken', artist: 'Hans Zimmer', duration: '3:35' },
  { title: "Idyll's End", artist: 'Hans Zimmer', duration: '6:40' },
  { title: 'Red Warrior', artist: 'Hans Zimmer', duration: '3:56' },
  { title: 'Power Rangers Theme', artist: 'Brian Tyler', duration: '4:22' },
  {
    title: 'Seek Those Who Are Worthy',
    artist: 'Brian Tyler',
    duration: '2:49',
  },
  { title: "It's Morphing Time!", artist: 'Brian Tyler', duration: '3:20' },

  { title: 'Titre', artist: 'Artiste', duration: '' },
  { title: 'Dragon Slayer', artist: 'Yasuharu Takanashi', duration: '1:59' },
  { title: "Mirajane's Theme", artist: 'Yasuharu Takanashi', duration: '1:50' },
  { title: 'Shukumei', artist: 'Yasuharu Takanashi', duration: '2:51' },
  { title: 'Kanashiki Kako', artist: 'Yasuharu Takanashi', duration: '2:13' },
  { title: 'Saigo no Mahou', artist: 'Yasuharu Takanashi', duration: '1:35' },
  {
    title: 'Fairy Tail Main Theme - Slow ver.',
    artist: 'Yasuharu Takanashi',
    duration: '2:34',
  },
  {
    title: 'Tsuioku - Mezameru Tamashii -',
    artist: 'Yasuharu Takanashi',
    duration: '3:10',
  },
  { title: 'Seigi no Chikara', artist: 'Yasuharu Takanashi', duration: '2:07' },
  { title: 'A Normal Life', artist: 'Henry Jackman', duration: '1:17' },
  { title: 'The Brothers Drake', artist: 'Henry Jackman', duration: '1:55' },
  { title: 'Epilogue', artist: 'Henry Jackman', duration: '3:17' },
  { title: 'The Lane Family', artist: 'Marco Beltrami', duration: '2:47' },
  {
    title: 'Days Gone (From "Days Gone" Soundtrack)',
    artist: 'Nathan Whitehead',
    duration: '3:41',
  },
  {
    title: 'We\'ve All Done Things (From "Days Gone" Soundtrack)',
    artist: 'Nathan Whitehead',
    duration: '3:36',
  },
  {
    title: 'Light One Candle (From "Days Gone" Soundtrack)',
    artist: 'Nathan Whitehead',
    duration: '1:59',
  },
  {
    title: 'Why We Fight (From "Days Gone" Soundtrack)',
    artist: 'Nathan Whitehead',
    duration: '2:37',
  },
  {
    title: 'The Path of the Wind - Instrumental',
    artist: 'Joe Hisaishi',
    duration: '3:16',
  },
  { title: "Caesar's Home", artist: 'Patrick Doyle', duration: '2:40' },
  { title: 'Paradise Found', artist: 'Michael Giacchino', duration: '5:35' },
  { title: 'Power', artist: 'Joseph Trapanese', duration: '6:01' },
  { title: 'Taken', artist: 'Hans Zimmer', duration: '3:35' },
  { title: "Idyll's End", artist: 'Hans Zimmer', duration: '6:40' },
  { title: 'Red Warrior', artist: 'Hans Zimmer', duration: '3:56' },
  { title: 'Power Rangers Theme', artist: 'Brian Tyler', duration: '4:22' },
  {
    title: 'Seek Those Who Are Worthy',
    artist: 'Brian Tyler',
    duration: '2:49',
  },
  { title: "It's Morphing Time!", artist: 'Brian Tyler', duration: '3:20' },
  { title: "Let's Ride", artist: 'Brian Tyler', duration: '2:20' },
  { title: 'This Is What Matters', artist: 'Brian Tyler', duration: '2:05' },
  {
    title: 'Kingdom Of Atlantis',
    artist: 'Rupert Gregson-Williams',
    duration: '3:26',
  },
  {
    title: 'Swimming Lessons',
    artist: 'Rupert Gregson-Williams',
    duration: '3:03',
  },
  {
    title: 'What Could Be Greater Than A King?',
    artist: 'Rupert Gregson-Williams',
    duration: '5:23',
  },
  {
    title: 'He Commands The Sea',
    artist: 'Rupert Gregson-Williams',
    duration: '3:34',
  },
  { title: 'The Team Leaves', artist: 'Daniel Pemberton', duration: '1:57' },
  { title: 'This Spark in You', artist: 'Daniel Pemberton', duration: '2:10' },
  { title: 'Saying Goodbye', artist: 'Daniel Pemberton', duration: '1:49' },
  { title: 'Shoulder Touch', artist: 'Daniel Pemberton', duration: '2:33' },
  { title: 'Aftermath', artist: 'Daniel Pemberton', duration: '1:26' },
  { title: 'Spider-Man', artist: 'John Paesano', duration: '3:26' },
  { title: 'The Golden Age', artist: 'John Paesano', duration: '3:06' },
  { title: 'City of Hope', artist: 'John Paesano', duration: '1:42' },
  { title: 'Worlds Colliding', artist: 'John Paesano', duration: '4:48' },
  { title: 'Responsibility', artist: 'John Paesano', duration: '3:15' },
  { title: 'Behind the Mask', artist: 'John Paesano', duration: '2:19' },
  { title: "Don't Give Up", artist: 'John Paesano', duration: '4:10' },
  {
    title: "New York's Only Spider-Man",
    artist: 'John Paesano',
    duration: '2:53',
  },
  { title: 'Make It Right', artist: 'John Paesano', duration: '5:57' },
  { title: "Won't Give Up", artist: 'John Paesano', duration: '2:21' },
  {
    title: 'If You Love These People',
    artist: 'Hans Zimmer, Nick Glennie-Smith, Junkie XL, Atli Örvarsson',
    duration: '3:02',
  },
  {
    title: 'Tornado',
    artist: 'Hans Zimmer, Nick Glennie-Smith, Junkie XL, Atli Örvarsson',
    duration: '2:46',
  },
  {
    title:
      'Is She With You? (From "Batman v Superman: Dawn of Justice" Soundtrack)',
    artist: 'Hans Zimmer, Junkie XL',
    duration: '5:46',
  },
  { title: 'A Hunter Gathers', artist: 'Junkie XL', duration: '7:56' },
  { title: 'No Dog, No Master', artist: 'Junkie XL', duration: '8:13' },
  {
    title: 'Superman Rising, Pt. 1 / A Book of Hours',
    artist: 'Junkie XL',
    duration: '2:40',
  },
  { title: 'Beyond Good and Evil', artist: 'Junkie XL', duration: '4:24' },
  { title: 'Flight Is Our Nature', artist: 'Junkie XL', duration: '1:54' },
  {
    title: 'Superman Rising, Pt. 2 / Immovable',
    artist: 'Junkie XL',
    duration: '1:55',
  },
  { title: 'At the Speed of Force', artist: 'Junkie XL', duration: '4:20' },
  {
    title: 'An Eternal Reoccurrence of Change',
    artist: 'Junkie XL',
    duration: '1:44',
  },
  { title: 'We Slay Ourselves', artist: 'Junkie XL', duration: '5:52' },
  {
    title: "The Foundation Theme (from Zack Snyder's Justice League)",
    artist: 'Junkie XL',
    duration: '2:07',
  },
  { title: 'Overture', artist: 'Daft Punk', duration: '2:28' },
  { title: 'Outlands', artist: 'Daft Punk', duration: '2:42' },
  { title: 'Solar Sailer', artist: 'Daft Punk', duration: '2:42' },
  { title: 'Disc Wars', artist: 'Daft Punk', duration: '4:11' },
  { title: 'Flynn Lives', artist: 'Daft Punk', duration: '3:22' },
  { title: 'Encom Part II', artist: 'Daft Punk', duration: '2:16' },
  { title: 'Daredevil', artist: 'John Paesano', duration: '1:41' },
  {
    title: 'Drink Up Me Hearties Yo Ho',
    artist: 'Hans Zimmer',
    duration: '4:31',
  },
  {
    title: 'Laptop Breaks / Home Movies',
    artist: 'Mark Mothersbaugh',
    duration: '3:43',
  },
  {
    title: 'Hiding In The Woods',
    artist: 'Mark Mothersbaugh',
    duration: '2:36',
  },
  { title: 'The Throne', artist: 'Junkie XL', duration: '2:10' },
  { title: 'Betrayed', artist: 'James Newton Howard', duration: '4:34' },
  {
    title: 'The Druun Close In',
    artist: 'James Newton Howard',
    duration: '2:58',
  },
  { title: 'Return', artist: 'James Newton Howard', duration: '4:58' },
  {
    title: 'The Next Screen (Bonus)',
    artist: 'Jeff Russo, Jordan Gagne',
    duration: '2:42',
  },
  { title: 'How to Find the Good Ones', artist: 'Dan Romer', duration: '5:14' },
  { title: 'Go Find Out for Me', artist: 'Dan Romer', duration: '1:39' },
  {
    title: 'Eptesicus',
    artist: 'James Newton Howard, Hans Zimmer',
    duration: '4:20',
  },
  {
    title: "I'm Spider-Man",
    artist: 'Hans Zimmer, The Magnificent Six, Pharrell Williams, Johnny Marr',
    duration: '1:04',
  },
  {
    title: "I'm Moving to England",
    artist: 'Hans Zimmer, The Magnificent Six, Pharrell Williams, Johnny Marr',
    duration: '1:03',
  },
  {
    title: 'I Chose You',
    artist: 'Hans Zimmer, The Magnificent Six, Pharrell Williams, Johnny Marr',
    duration: '1:34',
  },
  {
    title: "You're That Spider Guy",
    artist: 'Hans Zimmer, The Magnificent Six, Pharrell Williams, Johnny Marr',
    duration: '5:30',
  },
  {
    title: 'Raquel y Sergio Juntos',
    artist: 'Ivan M. Lacamara',
    duration: '2:26',
  },
  { title: 'La Vida de Raquel', artist: 'Ivan M. Lacamara', duration: '1:46' },
  { title: 'Spider Training', artist: 'Daniel Pemberton', duration: '1:23' },
  {
    title: 'My Name is.. Peter B. Parker',
    artist: 'Daniel Pemberton',
    duration: '0:52',
  },
  {
    title: 'Spider-Man: No Way Home - Trailer Music - Cover Version',
    artist: 'Cinescore',
    duration: '3:17',
  },
  {
    title: 'Spider-Man Loves You',
    artist: 'Daniel Pemberton',
    duration: '1:51',
  },
  { title: 'Main Title', artist: 'Danny Elfman', duration: '3:29' },
  { title: 'At Long Last, Love', artist: 'Danny Elfman', duration: '2:55' },
  {
    title: 'Geralt of Rivia',
    artist: 'Sonya Belousova, Giona Ostinelli',
    duration: '1:52',
  },
  {
    title: 'The Time of Axe and Sword Is Now',
    artist:
      'Sonya Belousova, Giona Ostinelli, Declan de Barra, Lindsay Deutsch',
    duration: '4:56',
  },
  {
    title: 'The Knight Who Was Taught to Save Dragons',
    artist: 'Sonya Belousova, Giona Ostinelli, Rodion Belousov',
    duration: '5:05',
  },
  {
    title: 'The Law of Surprise',
    artist: 'Sonya Belousova, Giona Ostinelli',
    duration: '4:30',
  },

  { title: 'Titre', artist: 'Artiste', duration: '' },
  {
    title: 'Hiding In The Woods',
    artist: 'Mark Mothersbaugh',
    duration: '2:36',
  },
  { title: 'The Throne', artist: 'Junkie XL', duration: '2:10' },
  { title: 'Betrayed', artist: 'James Newton Howard', duration: '4:34' },
  {
    title: 'The Druun Close In',
    artist: 'James Newton Howard',
    duration: '2:58',
  },
  { title: 'Return', artist: 'James Newton Howard', duration: '4:58' },
  {
    title: 'The Next Screen (Bonus)',
    artist: 'Jeff Russo, Jordan Gagne',
    duration: '2:42',
  },
  { title: 'How to Find the Good Ones', artist: 'Dan Romer', duration: '5:14' },
  { title: 'Go Find Out for Me', artist: 'Dan Romer', duration: '1:39' },
  {
    title: 'Eptesicus',
    artist: 'James Newton Howard, Hans Zimmer',
    duration: '4:20',
  },
  {
    title: "I'm Spider-Man",
    artist: 'Hans Zimmer, The Magnificent Six, Pharrell Williams, Johnny Marr',
    duration: '1:04',
  },
  {
    title: "I'm Moving to England",
    artist: 'Hans Zimmer, The Magnificent Six, Pharrell Williams, Johnny Marr',
    duration: '1:03',
  },
  {
    title: 'I Chose You',
    artist: 'Hans Zimmer, The Magnificent Six, Pharrell Williams, Johnny Marr',
    duration: '1:34',
  },
  {
    title: "You're That Spider Guy",
    artist: 'Hans Zimmer, The Magnificent Six, Pharrell Williams, Johnny Marr',
    duration: '5:30',
  },
  {
    title: 'Raquel y Sergio Juntos',
    artist: 'Ivan M. Lacamara',
    duration: '2:26',
  },
  { title: 'La Vida de Raquel', artist: 'Ivan M. Lacamara', duration: '1:46' },
  { title: 'Spider Training', artist: 'Daniel Pemberton', duration: '1:23' },
  {
    title: 'My Name is.. Peter B. Parker',
    artist: 'Daniel Pemberton',
    duration: '0:52',
  },
  {
    title: 'Spider-Man: No Way Home - Trailer Music - Cover Version',
    artist: 'Cinescore',
    duration: '3:17',
  },
  {
    title: 'Spider-Man Loves You',
    artist: 'Daniel Pemberton',
    duration: '1:51',
  },
  { title: 'Main Title', artist: 'Danny Elfman', duration: '3:29' },
  { title: 'At Long Last, Love', artist: 'Danny Elfman', duration: '2:55' },
  {
    title: 'Geralt of Rivia',
    artist: 'Sonya Belousova, Giona Ostinelli',
    duration: '1:52',
  },
  {
    title: 'The Time of Axe and Sword Is Now',
    artist:
      'Sonya Belousova, Giona Ostinelli, Declan de Barra, Lindsay Deutsch',
    duration: '4:56',
  },
  {
    title: 'The Knight Who Was Taught to Save Dragons',
    artist: 'Sonya Belousova, Giona Ostinelli, Rodion Belousov',
    duration: '5:05',
  },
  {
    title: 'The Law of Surprise',
    artist: 'Sonya Belousova, Giona Ostinelli',
    duration: '4:30',
  },
  {
    title: "Here's Your Destiny",
    artist: 'Sonya Belousova, Giona Ostinelli',
    duration: '3:48',
  },
  {
    title: 'Arachnoverture - from "Spider-Man: No Way Home" Soundtrack',
    artist: 'Michael Giacchino',
    duration: '10:06',
  },
  { title: "Deal's Changed", artist: 'Arcane', duration: '1:14' },
  { title: 'Revenge', artist: 'Arcane', duration: '3:11' },
  { title: 'The Bridge', artist: 'Arcane, Ray Chen', duration: '1:42' },
  { title: "She's Back", artist: 'Arcane', duration: '1:10' },
  {
    title: 'Fallout',
    artist: 'Arcane, League of Legends, Ray Chen',
    duration: '2:21',
  },
  { title: 'The Batman', artist: 'Michael Giacchino', duration: '6:47' },
  {
    title: 'Destroying the Castle',
    artist: 'Kyle Dixon & Michael Stein',
    duration: '1:48',
  },
  {
    title: 'Top Gun Anthem - From "Top Gun" Original Soundtrack',
    artist: 'Harold Faltermeyer, Steve Stevens',
    duration: '4:13',
  },
  {
    title: 'Run Up HIll Win',
    artist:
      'Dan Deacon, London Contemporary Orchestra, Royal Scottish National Orchestra',
    duration: '3:04',
  },
  {
    title: 'Prelude: The Atlas March',
    artist:
      'Tom Tykwer, Johnny Klimek, Reinhold Heil, MDR Rundfunkchor, MDR Leipzig Radio Symphony Orchestra, Kristjan Järvi',
    duration: '1:15',
  },
  {
    title: 'All Boundaries Are Conventions',
    artist:
      'Tom Tykwer, Johnny Klimek, Reinhold Heil, MDR Rundfunkchor, MDR Leipzig Radio Symphony Orchestra, Kristjan Järvi',
    duration: '2:38',
  },
  {
    title: 'Cloud Atlas Finale',
    artist:
      'Tom Tykwer, Johnny Klimek, Reinhold Heil, MDR Rundfunkchor, MDR Leipzig Radio Symphony Orchestra, Kristjan Järvi',
    duration: '4:17',
  },
  { title: 'Elden Ring', artist: 'Tsukasa Saitoh', duration: '1:38' },
  { title: 'Erdtree Avatar', artist: 'Tai Tomisawa', duration: '3:06' },
  { title: 'Why Do We Fall?', artist: 'Hans Zimmer', duration: '2:02' },
  {
    title: 'PRINCE (Les princes de la ville)',
    artist: 'GENER8ION',
    duration: '2:21',
  },
  { title: 'ASSAULT', artist: 'GENER8ION', duration: '4:06' },
  { title: 'ORION', artist: 'GENER8ION', duration: '3:28' },
  {
    title: 'The Prince That Was Promised',
    artist: 'Ramin Djawadi',
    duration: '4:34',
  },
  { title: 'The Green Dress', artist: 'Ramin Djawadi', duration: '2:50' },
  {
    title: 'The Crown of Jaehaerys',
    artist: 'Ramin Djawadi',
    duration: '3:19',
  },
  { title: 'Destiny', artist: 'Ramin Djawadi', duration: '2:56' },
  { title: 'Aemond Rides Vhagar', artist: 'Ramin Djawadi', duration: '3:10' },
  { title: 'The Inquisitor', artist: 'Kevin Kiner', duration: '3:44' },
  { title: 'Soldiers Are Here', artist: 'Kevin Kiner', duration: '4:51' },
  { title: 'Dooku vs Yaddle', artist: 'Kevin Kiner', duration: '3:15' },
  { title: 'Crossing Over', artist: 'Theophany', duration: '1:17' },
  {
    title: 'Befriending Spirits',
    artist: 'Theophany, Emiko Sarasawati Susilo, Dewa Ayu Larassanti',
    duration: '2:22',
  },
  {
    title: "Leia's News/Light of the Force - Medley",
    artist: 'John Williams',
    duration: '3:21',
  },
  { title: 'Fields', artist: 'Theophany', duration: '1:50' },
  { title: 'Hana', artist: 'Theophany', duration: '2:04' },
  {
    title: "Adira's Spirit Dive",
    artist:
      'Theophany, ROZEN, Emiko Sarasawati Susilo, Dewa Ayu Larassanti, Gamelan Cudamani',
    duration: '5:20',
  },
  {
    title: 'Mountain Shrine',
    artist: 'Theophany, ROZEN, Emiko Sarasawati Susilo, Dewa Ayu Larassanti',
    duration: '3:33',
  },
  { title: 'Pandora', artist: 'James Horner', duration: '3:17' },
  { title: "Buckbeak's Flight", artist: 'John Williams', duration: '2:08' },
  {
    title: 'Wakanda',
    artist: 'Ludwig Göransson, Baaba Maal',
    duration: '2:20',
  },
  { title: 'Phambili', artist: 'Ludwig Göransson', duration: '2:31' },
  { title: 'Ancestral Plane', artist: 'Ludwig Göransson', duration: '4:27' },
  { title: 'Past/Present Suite', artist: 'Nicholas Britell', duration: '3:44' },
  { title: 'Climb!', artist: 'Nicholas Britell', duration: '2:29' },
  {
    title: 'Niamos! (Galaxy Mix)',
    artist: 'Nicholas Britell',
    duration: '1:08',
  },
  {
    title:
      'God of War Ragnarök (From "God of War Ragnarök" Soundtrack) (feat. Eivør)',
    artist: 'Bear McCreary, Eivør',
    duration: '4:34',
  },
  {
    title: 'Svartalfheim (From "God of War Ragnarök" Soundtrack) (feat. Eivør)',
    artist: 'Bear McCreary, Eivør',
    duration: '5:13',
  },
  {
    title: 'The Hidden Beast (From "God of War Ragnarök" Soundtrack)',
    artist: 'Bear McCreary',
    duration: '4:11',
  },
  {
    title:
      'Remembering Faye (From "God of War Ragnarök" Soundtrack) (feat. Eivør)',
    artist: 'Bear McCreary, Eivør',
    duration: '2:40',
  },
  {
    title: 'Ragnarök (From "God of War Ragnarök" Soundtrack)',
    artist: 'Bear McCreary',
    duration: '5:14',
  },
  {
    title: 'The All-Father (From "God of War Ragnarök" Soundtrack)',
    artist: 'Bear McCreary',
    duration: '3:53',
  },
  {
    title: 'Raeb\'s Lament (From "God of War Ragnarök" Soundtrack)',
    artist: 'Bear McCreary',
    duration: '4:24',
  },
  {
    title: 'Letting Go (From "God of War Ragnarök" Soundtrack)',
    artist: 'Bear McCreary',
    duration: '9:25',
  },
  {
    title: 'One Way Out - Parts 5-7',
    artist: 'Nicholas Britell',
    duration: '1:50',
  },
  {
    title: 'One Way Out - Part 8',
    artist: 'Nicholas Britell',
    duration: '2:23',
  },
  {
    title: 'My Name Is Kino Loy',
    artist: 'Nicholas Britell',
    duration: '4:15',
  },
  { title: 'Eulogy', artist: 'Nicholas Britell', duration: '4:16' },
  {
    title: 'Cassian Will Find Us',
    artist: 'Nicholas Britell',
    duration: '2:32',
  },
  {
    title: 'The Rebellion Suite',
    artist: 'Nicholas Britell',
    duration: '3:59',
  },
  {
    title: 'Assassins Creed Theme',
    artist: "Lorne Balfe, Assassin's Creed",
    duration: '4:43',
  },
  {
    title: "Manny and Nellie's Theme",
    artist: 'Justin Hurwitz',
    duration: '0:53',
  },
  { title: "Ain't Life Grand", artist: 'Justin Hurwitz', duration: '1:38' },
  {
    title: 'Run It Suite (From "Creed III" Score) - Vocal Version',
    artist: 'Joseph Shirley',
    duration: '4:22',
  },
  {
    title: 'Training Montage (From "Creed III" Score)',
    artist: 'Joseph Shirley, Baby Rose',
    duration: '7:39',
  },
  {
    title: 'Round 12 (From "Creed III" Score)',
    artist: 'Joseph Shirley',
    duration: '4:42',
  },
  {
    title: "You've Made Your Choice",
    artist: 'Peter Murray, Hogwarts Legacy',
    duration: '1:39',
  },
  {
    title: "Niamh's Lullaby",
    artist: "chuck e. myers 'sea', Hogwarts Legacy",
    duration: '1:39',
  },
  {
    title: 'Tribute',
    artist: 'J Scott Rakozy, Hogwarts Legacy',
    duration: '2:44',
  },
  {
    title: 'It Really Is Good to Have Friends',
    artist: 'John Murphy',
    duration: '2:26',
  },
  { title: 'Into the Light', artist: 'John Murphy', duration: '4:29' },
  { title: 'Mantis and the Abelisk', artist: 'John Murphy', duration: '1:10' },

  { title: 'Titre', artist: 'Artiste', duration: '' },
  { title: 'Past/Present Suite', artist: 'Nicholas Britell', duration: '3:44' },
  { title: 'Climb!', artist: 'Nicholas Britell', duration: '2:29' },
  {
    title: 'Niamos! (Galaxy Mix)',
    artist: 'Nicholas Britell',
    duration: '1:08',
  },
  {
    title:
      'God of War Ragnarök (From "God of War Ragnarök" Soundtrack) (feat. Eivør)',
    artist: 'Bear McCreary, Eivør',
    duration: '4:34',
  },
  {
    title: 'Svartalfheim (From "God of War Ragnarök" Soundtrack) (feat. Eivør)',
    artist: 'Bear McCreary, Eivør',
    duration: '5:13',
  },
  {
    title: 'The Hidden Beast (From "God of War Ragnarök" Soundtrack)',
    artist: 'Bear McCreary',
    duration: '4:11',
  },
  {
    title:
      'Remembering Faye (From "God of War Ragnarök" Soundtrack) (feat. Eivør)',
    artist: 'Bear McCreary, Eivør',
    duration: '2:40',
  },
  {
    title: 'Ragnarök (From "God of War Ragnarök" Soundtrack)',
    artist: 'Bear McCreary',
    duration: '5:14',
  },
  {
    title: 'The All-Father (From "God of War Ragnarök" Soundtrack)',
    artist: 'Bear McCreary',
    duration: '3:53',
  },
  {
    title: 'Raeb\'s Lament (From "God of War Ragnarök" Soundtrack)',
    artist: 'Bear McCreary',
    duration: '4:24',
  },
  {
    title: 'Letting Go (From "God of War Ragnarök" Soundtrack)',
    artist: 'Bear McCreary',
    duration: '9:25',
  },
  {
    title: 'One Way Out - Parts 5-7',
    artist: 'Nicholas Britell',
    duration: '1:50',
  },
  {
    title: 'One Way Out - Part 8',
    artist: 'Nicholas Britell',
    duration: '2:23',
  },
  {
    title: 'My Name Is Kino Loy',
    artist: 'Nicholas Britell',
    duration: '4:15',
  },
  { title: 'Eulogy', artist: 'Nicholas Britell', duration: '4:16' },
  {
    title: 'Cassian Will Find Us',
    artist: 'Nicholas Britell',
    duration: '2:32',
  },
  {
    title: 'The Rebellion Suite',
    artist: 'Nicholas Britell',
    duration: '3:59',
  },
  {
    title: 'Assassins Creed Theme',
    artist: "Lorne Balfe, Assassin's Creed",
    duration: '4:43',
  },
  {
    title: "Manny and Nellie's Theme",
    artist: 'Justin Hurwitz',
    duration: '0:53',
  },
  { title: "Ain't Life Grand", artist: 'Justin Hurwitz', duration: '1:38' },
  {
    title: 'Run It Suite (From "Creed III" Score) - Vocal Version',
    artist: 'Joseph Shirley',
    duration: '4:22',
  },
  {
    title: 'Training Montage (From "Creed III" Score)',
    artist: 'Joseph Shirley, Baby Rose',
    duration: '7:39',
  },
  {
    title: 'Round 12 (From "Creed III" Score)',
    artist: 'Joseph Shirley',
    duration: '4:42',
  },
  {
    title: "You've Made Your Choice",
    artist: 'Peter Murray, Hogwarts Legacy',
    duration: '1:39',
  },
  {
    title: "Niamh's Lullaby",
    artist: "chuck e. myers 'sea', Hogwarts Legacy",
    duration: '1:39',
  },
  {
    title: 'Tribute',
    artist: 'J Scott Rakozy, Hogwarts Legacy',
    duration: '2:44',
  },
  {
    title: 'It Really Is Good to Have Friends',
    artist: 'John Murphy',
    duration: '2:26',
  },
  { title: 'Into the Light', artist: 'John Murphy', duration: '4:29' },
  { title: 'Mantis and the Abelisk', artist: 'John Murphy', duration: '1:10' },
  { title: 'Use Your Heart Boy', artist: 'John Murphy', duration: '0:53' },
  { title: 'The High Evolutionary', artist: 'John Murphy', duration: '2:56' },
  { title: 'Who We Are', artist: 'John Murphy', duration: '2:20' },
  { title: 'Did That Look Cool?', artist: 'John Murphy', duration: '2:44' },
  { title: 'All Life Has Meaning', artist: 'John Murphy', duration: '2:01' },
  {
    title: 'Spider-Woman (Gwen Stacy)',
    artist: 'Daniel Pemberton',
    duration: '3:06',
  },
  { title: 'Rio and Miles', artist: 'Daniel Pemberton', duration: '4:24' },
  {
    title: 'Welcome to Nueva York (Earth-928)',
    artist: 'Daniel Pemberton',
    duration: '1:43',
  },
  {
    title: 'Nueva York Train Chase',
    artist: 'Daniel Pemberton',
    duration: '5:58',
  },
  { title: 'Falling Apart', artist: 'Daniel Pemberton', duration: '8:23' },
  {
    title: 'Under the Clocktower',
    artist: 'Daniel Pemberton',
    duration: '2:55',
  },
  { title: 'Canon Event', artist: 'Daniel Pemberton', duration: '7:09' },
  { title: 'I Beat Them All', artist: 'Daniel Pemberton', duration: '2:28' },
  {
    title: 'Nick Fury (Main Title Theme) - From "Secret Invasion"',
    artist: 'Kris Bowers',
    duration: '2:03',
  },
  {
    title: 'None Shall Live',
    artist: 'Two Steps from Hell, Thomas Bergersen',
    duration: '2:19',
  },
  { title: 'Jim Transforms', artist: 'Tim Davies', duration: '5:51' },
  { title: 'The Wedding', artist: 'Daniel Licht', duration: '2:27' },
  {
    title: 'We Are!',
    artist: 'Sonya Belousova, Giona Ostinelli',
    duration: '1:58',
  },
  {
    title: "I'm Gonna Be King Of The Pirates / We Are!",
    artist: 'Sonya Belousova, Giona Ostinelli',
    duration: '4:26',
  },
  {
    title: 'A Hundred Million Berry',
    artist: 'Sonya Belousova, Giona Ostinelli',
    duration: '2:35',
  },
  {
    title: 'Not Sailors, We Are Pirates',
    artist: 'Sonya Belousova, Giona Ostinelli',
    duration: '2:34',
  },
  {
    title: 'The Going Merry',
    artist: 'Sonya Belousova, Giona Ostinelli',
    duration: '1:44',
  },
  {
    title: 'Gum Gum Battle Axe',
    artist: 'Sonya Belousova, Giona Ostinelli',
    duration: '2:19',
  },
  {
    title: 'I Have My Friends',
    artist: 'Sonya Belousova, Giona Ostinelli',
    duration: '2:51',
  },
  {
    title: 'Can You Hear The Music',
    artist: 'Ludwig Göransson',
    duration: '1:50',
  },
  {
    title: 'Gravity Swallows Light',
    artist: 'Ludwig Göransson',
    duration: '3:30',
  },
  { title: 'Standby', artist: 'Hans Zimmer', duration: '6:11' },
  { title: 'Missile Launch', artist: 'Hans Zimmer', duration: '3:01' },
  { title: 'Prayer', artist: 'Hans Zimmer', duration: '2:47' },
  { title: 'TVA Title Card', artist: 'Natalie Holt', duration: '1:38' },
  { title: 'One Shot', artist: 'Natalie Holt', duration: '2:50' },
  {
    title: 'Ahsoka - End Credits - From "Ahsoka"',
    artist: 'Kevin Kiner',
    duration: '3:43',
  },
  { title: 'The Tour', artist: 'James Newton Howard', duration: '5:56' },
  {
    title: 'The Hanging Tree - From "The Hunger Games: Mockingjay" Soundtraclk',
    artist: 'James Newton Howard, Jennifer Lawrence',
    duration: '3:38',
  },
  {
    title: "Anakin's Betrayal",
    artist: 'John Williams, London Symphony Orchestra',
    duration: '4:05',
  },
  {
    title: 'A Plague Tale Requiem',
    artist:
      'Olivier Deriviere, Eric Maria Couturier, Estonian Philharmonic Chamber Choir',
    duration: '4:00',
  },
  {
    title: 'No Turning Back',
    artist: 'Olivier Deriviere, Eric Maria Couturier',
    duration: '4:20',
  },
  {
    title: 'Siblings',
    artist: 'Olivier Deriviere, Eric Maria Couturier, Giani Caserotto',
    duration: '1:35',
  },
  {
    title: 'Brother',
    artist:
      'Olivier Deriviere, Eric Maria Couturier, Jeanne Dorche, Octantrion',
    duration: '4:07',
  },
  {
    title: 'A Time of Quiet Between the Storms',
    artist: 'Hans Zimmer',
    duration: '4:21',
  },
  { title: 'Kiss the Ring', artist: 'Hans Zimmer', duration: '3:12' },
  { title: 'Mercédès', artist: 'Jérôme Rebotier', duration: '1:58' },
  { title: 'Le trésor', artist: 'Jérôme Rebotier', duration: '3:56' },
  { title: 'Edmond et Mercédès', artist: 'Jérôme Rebotier', duration: '3:09' },
  {
    title: 'Haydée supplie Albert',
    artist: 'Jérôme Rebotier',
    duration: '1:39',
  },
  {
    title: 'Albert rejoint Haydée',
    artist: 'Jérôme Rebotier',
    duration: '2:34',
  },
  { title: 'Main Title', artist: 'Trevor Jones', duration: '1:44' },
  { title: 'The Kiss', artist: 'Trevor Jones', duration: '2:49' },
  {
    title: 'Deploying Rescue Transmitter',
    artist: 'Kris Bowers',
    duration: '0:47',
  },
  { title: 'Hatching', artist: 'Kris Bowers', duration: '1:03' },
  { title: 'I Could Use a Boost', artist: 'Kris Bowers', duration: '3:07' },
  { title: 'Task Complete', artist: 'Kris Bowers', duration: '1:51' },
  {
    title: 'I Have Everything I Need',
    artist: 'Kris Bowers',
    duration: '1:29',
  },
  { title: 'You Don’t Have To', artist: 'Kris Bowers', duration: '3:05' },
  { title: 'Roz’s Story', artist: 'Kris Bowers', duration: '2:03' },
  { title: "Sevika's Speech", artist: 'Arcane', duration: '1:37' },
  { title: 'Blisters and Bedrock', artist: 'Arcane', duration: '2:11' },
  { title: "That's Not Vander", artist: 'Arcane', duration: '1:33' },
  { title: 'A Big Distraction', artist: 'Arcane', duration: '1:20' },
  {
    title: 'Vow (feat. Ray Chen)',
    artist: 'Arcane, Ray Chen',
    duration: '1:04',
  },
  { title: 'Agony', artist: 'Arcane', duration: '1:44' },
  { title: "Tell Me There's a Chance", artist: 'Arcane', duration: '1:38' },
  {
    title: 'You Will Never Be a Passenger',
    artist: 'Arcane',
    duration: '1:26',
  },
  { title: 'Desperate Measures', artist: 'Arcane', duration: '2:30' },
  { title: 'The Price of Ambition', artist: 'Arcane', duration: '3:12' },

  { title: 'Titre', artist: 'Artiste', duration: '' },
  { title: 'Standby', artist: 'Hans Zimmer', duration: '6:11' },
  { title: 'Missile Launch', artist: 'Hans Zimmer', duration: '3:01' },
  { title: 'Prayer', artist: 'Hans Zimmer', duration: '2:47' },
  { title: 'TVA Title Card', artist: 'Natalie Holt', duration: '1:38' },
  { title: 'One Shot', artist: 'Natalie Holt', duration: '2:50' },
  {
    title: 'Ahsoka - End Credits - From "Ahsoka"',
    artist: 'Kevin Kiner',
    duration: '3:43',
  },
  { title: 'The Tour', artist: 'James Newton Howard', duration: '5:56' },
  {
    title: 'The Hanging Tree - From "The Hunger Games: Mockingjay" Soundtraclk',
    artist: 'James Newton Howard, Jennifer Lawrence',
    duration: '3:38',
  },
  {
    title: "Anakin's Betrayal",
    artist: 'John Williams, London Symphony Orchestra',
    duration: '4:05',
  },
  {
    title: 'A Plague Tale Requiem',
    artist:
      'Olivier Deriviere, Eric Maria Couturier, Estonian Philharmonic Chamber Choir',
    duration: '4:00',
  },
  {
    title: 'No Turning Back',
    artist: 'Olivier Deriviere, Eric Maria Couturier',
    duration: '4:20',
  },
  {
    title: 'Siblings',
    artist: 'Olivier Deriviere, Eric Maria Couturier, Giani Caserotto',
    duration: '1:35',
  },
  {
    title: 'Brother',
    artist:
      'Olivier Deriviere, Eric Maria Couturier, Jeanne Dorche, Octantrion',
    duration: '4:07',
  },
  {
    title: 'A Time of Quiet Between the Storms',
    artist: 'Hans Zimmer',
    duration: '4:21',
  },
  { title: 'Kiss the Ring', artist: 'Hans Zimmer', duration: '3:12' },
  { title: 'Mercédès', artist: 'Jérôme Rebotier', duration: '1:58' },
  { title: 'Le trésor', artist: 'Jérôme Rebotier', duration: '3:56' },
  { title: 'Edmond et Mercédès', artist: 'Jérôme Rebotier', duration: '3:09' },
  {
    title: 'Haydée supplie Albert',
    artist: 'Jérôme Rebotier',
    duration: '1:39',
  },
  {
    title: 'Albert rejoint Haydée',
    artist: 'Jérôme Rebotier',
    duration: '2:34',
  },
  { title: 'Main Title', artist: 'Trevor Jones', duration: '1:44' },
  { title: 'The Kiss', artist: 'Trevor Jones', duration: '2:49' },
  {
    title: 'Deploying Rescue Transmitter',
    artist: 'Kris Bowers',
    duration: '0:47',
  },
  { title: 'Hatching', artist: 'Kris Bowers', duration: '1:03' },
  { title: 'I Could Use a Boost', artist: 'Kris Bowers', duration: '3:07' },
  { title: 'Task Complete', artist: 'Kris Bowers', duration: '1:51' },
  {
    title: 'I Have Everything I Need',
    artist: 'Kris Bowers',
    duration: '1:29',
  },
  { title: 'You Don’t Have To', artist: 'Kris Bowers', duration: '3:05' },
  { title: 'Roz’s Story', artist: 'Kris Bowers', duration: '2:03' },
  { title: "Sevika's Speech", artist: 'Arcane', duration: '1:37' },
  { title: 'Blisters and Bedrock', artist: 'Arcane', duration: '2:11' },
  { title: "That's Not Vander", artist: 'Arcane', duration: '1:33' },
  { title: 'A Big Distraction', artist: 'Arcane', duration: '1:20' },
  {
    title: 'Vow (feat. Ray Chen)',
    artist: 'Arcane, Ray Chen',
    duration: '1:04',
  },
  { title: 'Agony', artist: 'Arcane', duration: '1:44' },
  { title: "Tell Me There's a Chance", artist: 'Arcane', duration: '1:38' },
  {
    title: 'You Will Never Be a Passenger',
    artist: 'Arcane',
    duration: '1:26',
  },
  { title: 'Desperate Measures', artist: 'Arcane', duration: '2:30' },
  { title: 'The Price of Ambition', artist: 'Arcane', duration: '3:12' },
  {
    title: 'I Promised You (feat. Ray Chen)',
    artist: 'Arcane, Ray Chen',
    duration: '3:21',
  },
  {
    title: 'The Bridge (Reprise) (feat. Ray Chen, Kelci Hahn)',
    artist: 'Arcane, Ray Chen, Kelci Hahn',
    duration: '1:05',
  },
  {
    title: 'Funeral (feat. Andrew Kierszenbaum)',
    artist: 'Arcane, Andrew Kierszenbaum',
    duration: '2:26',
  },
  {
    title: 'Honor Him',
    artist: 'Hans Zimmer, Gavin Greenaway, The Lyndhurst Orchestra',
    duration: '1:19',
  },
  { title: "La valse d'Amélie", artist: 'Yann Tiersen', duration: '2:15' },
  {
    title: "Comptine d'un autre été, l'après-midi",
    artist: 'Yann Tiersen',
    duration: '2:20',
  },
  { title: 'Returning Home', artist: 'John Paesano', duration: '2:04' },
  { title: 'The Murdocks', artist: 'John Paesano', duration: '2:38' },
  { title: 'End Credits', artist: 'John Paesano', duration: '1:06' },
  { title: 'Subway Feels', artist: 'John Paesano', duration: '2:37' },
  { title: 'Passion and Danger', artist: 'Michael Suby', duration: '1:45' },
  {
    title: "L'uomo dell'armonica",
    artist: 'Ennio Morricone',
    duration: '3:29',
  },
  {
    title: "Marvel's Daredevil: Born Again Main Theme",
    artist: 'The Newton Brothers',
    duration: '1:49',
  },
  {
    title: "I Was Hoping It'd Be You",
    artist: 'Lorne Balfe',
    duration: '1:41',
  },
  { title: 'Ponte Dei Conzafelzi', artist: 'Lorne Balfe', duration: '2:19' },
  { title: 'Meet Ben', artist: 'The Name, Clément Libes', duration: '3:36' },
  { title: "L'aveu", artist: 'Clément Libes', duration: '1:43' },
  {
    title: 'Test Driving Toothless (from How to Train Your Dragon)',
    artist: 'John Powell',
    duration: '3:03',
  },
  {
    title: 'Alicia',
    artist: 'Lorien Testard, Alice Duport-Percier',
    duration: '2:50',
  },
  {
    title: 'Lumière',
    artist: 'Lorien Testard, Alice Duport-Percier',
    duration: '3:42',
  },
  {
    title: 'Spring Meadows - Éveil',
    artist: 'Lorien Testard',
    duration: '2:46',
  },
  {
    title: 'The Fantastic Four: First Steps Main Theme Extended Version',
    artist: 'Michael Giacchino',
    duration: '4:10',
  },
  {
    title: "Une vie à t'aimer",
    artist: 'Lorien Testard, Alice Duport-Percier, Victor Borba',
    duration: '11:00',
  },
  { title: 'Gustave', artist: 'Lorien Testard', duration: '3:48' },
  {
    title: 'Clair-Obscur',
    artist: 'Lorien Testard, Alice Duport-Percier',
    duration: '3:39',
  },
  {
    title: 'We Lost',
    artist: 'Lorien Testard, Alice Duport-Percier, Victor Borba',
    duration: '8:33',
  },
  {
    title: 'Lumière - Lumière à l’Aube',
    artist: 'Lorien Testard',
    duration: '3:52',
  },
  {
    title: 'Lost Voice',
    artist: 'Lorien Testard, Alice Duport-Percier',
    duration: '2:33',
  },
  {
    title: 'Aline',
    artist: 'Lorien Testard, Alice Duport-Percier',
    duration: '2:35',
  },
  {
    title: 'Paintress',
    artist: 'Lorien Testard, Alice Duport-Percier',
    duration: '8:50',
  },
  {
    title: "L'Amour d'une Mère",
    artist: 'Lorien Testard, Alice Duport-Percier',
    duration: '4:00',
  },
  {
    title: 'Aux Lendemains non Écrits',
    artist: 'Lorien Testard, Alice Duport-Percier',
    duration: '4:02',
  },
  {
    title: 'Maelle',
    artist: 'Lorien Testard, Alice Duport-Percier',
    duration: '2:50',
  },
  {
    title: 'World Map - Déchire la Toile',
    artist: 'Lorien Testard, Alice Duport-Percier',
    duration: '3:02',
  },
  { title: 'Promentory', artist: 'Trevor Jones', duration: '6:13' },
  {
    title: 'The Winner Is',
    artist: 'DeVotchKa, Mychael Danna',
    duration: '3:04',
  },
  { title: 'Change The World', artist: 'Daniel Pemberton', duration: '5:09' },
  { title: 'The Skylab Plan', artist: 'Daniel Pemberton', duration: '5:01' },
  { title: 'Revenge', artist: 'Daniel Pemberton', duration: '9:38' },
  {
    title: 'The Nature Of People',
    artist: 'Daniel Pemberton',
    duration: '4:04',
  },
];

const seen = new Set<string>();
const normalizeValue = (value?: string) => (value ?? '').trim();

export const data = rawData.filter((item) => {
  const title = normalizeValue(item?.title);
  const artist = normalizeValue(item?.artist);
  const duration = normalizeValue(item?.duration);

  if (!title || !artist || !duration) return false;
  if (title === 'Titre' && artist === 'Artiste') return false;
  if (duration === '-:--') return false;

  const key = `${title.toLowerCase()}|${artist.toLowerCase()}|${duration}`;
  if (seen.has(key)) return false;
  seen.add(key);

  return true;
});
