import { UserComics } from '../../../../models/comic-model';

export const guillaumeReadListComics: UserComics = [
  {
    title: 'Brainiac',
    writer: 'Inconnu',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Killing Joke',
    writer: 'Inconnu',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Kingdom Come',
    writer: 'Inconnu',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Absolute Batman',
    writer: 'Scott Snyder',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'World War Hulk',
    writer: 'Greg Pak',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Wolverine : Old Man Logan',
    writer: 'Mark Millar',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
];
