import { UserSerie } from '../../../../models/serie-model';

export const lauralSeries: UserSerie[] = [
  {
    title: "Le Jeu de la Dame",
    director: "Scott Frank",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 4.5,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "13 Reasons Why",
    director: "Brian Yorkey",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 4,
      watching: false,
      seasonTimesWatched: 3,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 3,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 4,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Game of Thrones",
    director: "David Benioff, D.B. Weiss",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 3,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 4,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 5,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 6,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 7,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 8,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: true,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Sons of Anarchy",
    director: "Kurt Sutter",
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      }
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "The Punisher",
    director: "Steve Lightfoot",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 4.5,
      watching: false,
      seasonTimesWatched: 3,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 4,
      watching: false,
      seasonTimesWatched: 3,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "La Chronique des Bridgerton",
    director: "Chris Van Dusen",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 3.5,
      watching: false,
      seasonTimesWatched: 4,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 3.75,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 3,
      seasonRating: 4,
      watching: false,
      seasonTimesWatched: 3,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 4,
      seasonRating: 2,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Atypical",
    director: "Robia Rashid",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 4,
      watching: false,
      seasonTimesWatched: 3,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 4,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 3,
      seasonRating: 4,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 4,
      seasonRating: 4,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "La Casa de Papel",
    director: "Álex Pina",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 3,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 4,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Misfits",
    director: "Howard Overman",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 3,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 4,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 5,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Mercredi",
    director: "Tim Burton",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Montre jamais ça à personne",
    director: "Hugo Benamozig, David Caviglioli",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 4,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Big Little Lies",
    director: "David E. Kelley",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 4.25,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 4.25,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Sex Education",
    director: "Laurie Nunn",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 4.75,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 3,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 4,
      seasonRating: 2.5,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Murder",
    director: "Peter Nowalk",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 3,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 4,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 5,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 6,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Hé Arnold !",
    director: "Craig Bartlett",
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      }
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "Ginny & Georgia",
    director: "Sarah Lampert",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 3,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Élite",
    director: "Carlos Montero, Darío Madrona",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 3,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 2,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 4,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 5,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 6,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 7,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 8,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "DAHMER : Monstre : L'histoire de Jeffrey Dahmer",
    director: "Ryan Murphy, Ian Brennan",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 4.5,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Nouvelle École",
    director: "Sylvain Pearl, Stan Bertheux",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 3,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 4,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "The End of the F***ing World",
    director: "Jonathan Entwistle",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    },
    {
      seasonNumber: 2,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "La chute de la maison Usher",
    director: "Mike Flanagan",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 3,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "The Haunting of Hill House",
    director: "Mike Flanagan",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 1,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Mon petit renne",
    director: "Richard Gadd",
    seasons: [
    {
      seasonNumber: 1,
      seasonRating: 0,
      watching: false,
      seasonTimesWatched: 0,
      firstViewedDate: "",
      lastViewedDate: "",
      otherViewedDates: [],
    }
  ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },

  {
    title: "Pokémon",
    director: "Satoshi Tajiri",
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 8,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 9,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 10,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 11,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 12,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 13,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 14,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 15,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 16,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 17,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 18,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 19,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 20,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 21,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 22,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 23,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 24,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      }
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "Les Aventures de Tintin",
    director: "Stéphane Bernasconi",
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        watching: false,
        seasonTimesWatched: 0,
        firstViewedDate: "",
        lastViewedDate: "",
        otherViewedDates: [],
      }
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
];
