import { UserBook } from '../../../../models/book-model';

export const clemenceBooks: UserBook[] = [
  {
    title: "Ne tirez pas sur l'oiseau moqueur",
    author: "Harper Lee",
    firstReadDate: "",
    lastReadDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },

  {
    title: "Les Hauts de Hurlevent",
    author: "Emily Brontë",
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },

  {
    title: "1984",
    author: "George Orwell",
    firstReadDate: '',
    lastReadDate: '',
    rating: 5,
    readTimes: 2,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },

  {
    title: "Gatsby le magnifique",
    author: "F. Scott Fitzgerald",
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },

  {
    title: "Le Portrait de Dorian Gray",
    author: "Oscar Wilde",
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Anna Karénine",
    author: "Léon Tolstoï",
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Le rouge et le noir",
    author: "Stendhal",
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Les Hirondelles de Kaboul",
    author: "Yasmina Khadra",
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Ce que le jour doit à la nuit",
    author: "Yasmina Khadra",
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Des souris et des hommes",
    author: "John Steinbeck",
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Millénium, Tome 1 : Les hommes qui n'aimaient pas les femmes",
    author: "Stieg Larsson",
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Millénium, Tome 2 : La fille qui rêvait d'un bidon d'essence et d'une allumette",
    author: "Stieg Larsson",
    firstReadDate: '',
    lastReadDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: '',
    loaned: '',
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
];
