import { Quizz, EntityType } from '../../models/quizz-model';

export const quizzsGuillaume: Quizz[] = [
  {
    creator: 'Guillaume',
    entityType: EntityType.MOVIE,
    entityTitle: 'I, Robot',
    level: 1,
    questions: [
      {
        id: 1,
        title: 'Combien existe t-il de lois pour la robotique?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['3'],
      },
      {
        id: 2,
        title: "Qui joue l'acteur principal? Donnez le nom de famille.",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Smith'],
      },
      {
        id: 3,
        title: 'Complétez : Excusez-moi, je suis allergique aux :',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Bobards'],
      },
      {
        id: 4,
        title: 'Quel est le prénom du personnage principal?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Del'],
      },
      {
        id: 5,
        title: 'Quel animal Del sauve t-il de la destruction de la maison?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Chat'],
      },
      {
        id: 6,
        title:
          'Quel est le nom du programme informatique qui gère tout chez USR? En abrégé et en majuscules.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['VIKI'],
      },
      {
        id: 7,
        title: 'Comment se prénomme le NS-5 défectueux?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Sonny'],
      },
      {
        id: 8,
        title:
          'Complétez : Ce sont des converse All-Star millésime ... certifiées.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['2004'],
      },
      {
        id: 9,
        title:
          'Les deux domaines de prédilection du Dr. Calvin sont la robotique de pointe et la ...?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Psychiatrie'],
      },
      {
        id: 10,
        title:
          'A quelle heure était initialement prévue la destruction de la maison du Dr. Lanning?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['8'],
      },
      {
        id: 11,
        title: 'Complétez : Je ne pouvais pas le détruire, il était trop : ...',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Unique'],
      },
      {
        id: 12,
        title:
          'Combien de robots représentent la production journalière de chez USR pour les NS-5?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['1000'],
      },
      {
        id: 13,
        title: 'De quelle couleur est le "sang" du robot?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Gris'],
      },
      {
        id: 14,
        title: 'Quelle est la marque de la voiture de Spooner?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Audi'],
      },
      {
        id: 15,
        title:
          'Quel acteur joue le rôle du jeune qui demande la voiture de Spooner? Donnez le nom de famille.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['LaBeouf'],
      },
      {
        id: 16,
        title: "Complétez : Est-ce qu'un robot peut écrire une ... ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Symphonie'],
      },
      {
        id: 17,
        title: 'Combien Sarah avait-elle de pourcents de chances de survie?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['11'],
      },
      {
        id: 18,
        title: 'Quel était le métier que Sarah voulait faire?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Dentiste'],
      },
      {
        id: 19,
        title:
          "Comment s'appelle le garçon qui avait frappé Del au CM2? Donnez le nom de famille.",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Murphy'],
      },
      {
        id: 20,
        title:
          "Complétez : Vous avez déjà vécu une journée normale? - Ouais, une fois. C'était un ....",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Jeudi'],
      },
    ],
  },
  {
    creator: 'Guillaume',
    entityType: EntityType.MANGA,
    entityTitle: 'Bleach',
    level: 1,
    questions: [
      {
        id: 1,
        title:
          "Comment s'appelle la shinigami qui donne ses pouvoirs à Ichigo?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Rukia'],
      },
      {
        id: 2,
        title: 'Quel est le nom de famille de Renji?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Abarai'],
      },
      {
        id: 3,
        title: "Quel numéro d'Espada porte Grimmjow?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['6'],
      },
      {
        id: 4,
        title:
          'Qui Ichigo bat-il après Renji lors de son arrivée dans la Soul Society? Donnez le nom de famille.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Kenpachi'],
      },
      {
        id: 5,
        title: "Comment s'appelle la seconde catégorie des Hollow?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Adjuchas'],
      },
      {
        id: 6,
        title:
          'Quel numéro de technique de Hado Aizen utilise t-il face à Komamura pour le battre dans la Soul Society?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['90'],
      },
      {
        id: 7,
        title: "Quel est le nom du zanpakuto d'Hitsugaya?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Hyourinmaru'],
      },
      {
        id: 8,
        title:
          'Combien de sens le Bankai de Tosen fait-il perdre à celui qui est touché?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['3'],
      },
      {
        id: 9,
        title: "Quelle est la forme que l'espada primera exerce sur la mort?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Solitude'],
      },
      {
        id: 10,
        title: "Comment s'appelle la grande soeur de Nanao?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Lisa'],
      },
      {
        id: 11,
        title: 'Combien de jours Kisuke a t-il mit pour apprendre le bankai?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['3'],
      },
      {
        id: 12,
        title:
          "Lorsque Kurotsuchi administre a l'ocho espada son tranquilisant, combien d'années ressent-il pour 1 seconde écoulée dans le monde réel?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['100'],
      },
      {
        id: 13,
        title:
          "Quel mot rajoute Byakuya à son sabre lorsqu'il passe en Bankai?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Kageyoshi'],
      },
      {
        id: 14,
        title: 'De quel clan Genju fait-il partie?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Shiba'],
      },
      {
        id: 15,
        title: "Qui est le propriétaire d'Ashizo Guijizo? Donnez le prénom.",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Mayuri'],
      },
      {
        id: 16,
        title: "De quelle division Urahara était-il capitaine à l'époque?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['12'],
      },
      {
        id: 17,
        title:
          "Quand il se passe une année normale, combien s'en écoule t-il dans le Dangai?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['2000'],
      },
      {
        id: 18,
        title:
          "Quelle est le nom de l'attaque qu'Ichigo utilise lorsqu'il devient le Getsuga?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Mugetsu'],
      },
      {
        id: 19,
        title:
          'Le fullbringer qui possède le "Jackpot Knuckle" s\'appelle : ... ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Shishigawara'],
      },
      {
        id: 20,
        title:
          'Par quel numéro de chapitre commence le "Turn back the pendulum" ? Sans mettre de "-" devant.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['108'],
      },
    ],
  },
  {
    creator: 'Guillaume',
    entityType: EntityType.MANGA,
    entityTitle: 'Dragon Ball',
    level: 1,
    questions: [
      {
        id: 1,
        title:
          "Comment s'appelle le garçon qui s'entraine avec Sengoku chez Tortue Géniale ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Krilin'],
      },
      {
        id: 2,
        title: 'Le rival de Sangoku est :',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Vegeta'],
      },
      {
        id: 3,
        title:
          'Quel est le nom donné aux haricots magiques qui permettent de soigner toutes les blessures? Au singulier.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Senzu'],
      },
      {
        id: 4,
        title: "Comment s'appelle le fils de Vegeta?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Trunks'],
      },
      {
        id: 5,
        title: 'Combien de cyborgs Cell doit-il absorber pour être parfait?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['2'],
      },
      {
        id: 6,
        title:
          'Quel numéro de Cyborg meurt devant Sangohan, après lui avoir conseillé de se mettre en colère?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['16'],
      },
      {
        id: 7,
        title: 'Quel est le nom du peuple de Radditz ? Au singulier.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Saiyen'],
      },
      {
        id: 8,
        title: 'Combien de stades Sengoku peut-il passer à la fin du manga?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['3'],
      },
      {
        id: 9,
        title: "Barta pense être l'être le plus ... de l'univers.",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Rapide'],
      },
      {
        id: 10,
        title: "Comment s'appelle le sorcier qui ressucite Boubou?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Babidi'],
      },
      {
        id: 11,
        title: "Comment s'appelle le dragon de Namek?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Porunga'],
      },
      {
        id: 12,
        title: "Combien Freezer a d'évolutions?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['3'],
      },
      {
        id: 13,
        title:
          "Combien gagne t-on lorsqu'on gagne le tournoi des arts martiaux?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['1000000'],
      },
      {
        id: 14,
        title: 'Dans les Hors-Séries, qui est le super saiyen légendaire?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Broly'],
      },
      {
        id: 15,
        title:
          'Quel nom choisit le tout-puissant pour participer au tournoi des arts martiaux?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Shen'],
      },
      {
        id: 16,
        title:
          "A combien de G au maximum Sengoku s'entraine t-il avant d'aller sur Namek?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['100'],
      },
      {
        id: 17,
        title:
          'Avec qui Sengoku a t-il envisagé de fusionner après Sangohan et avant Vegeta contre Majin Boo?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Satan'],
      },
      {
        id: 18,
        title: "Quel est le nom du métal le plus solide de l'univers?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Katshin'],
      },
      {
        id: 19,
        title:
          'Dans le manga, quelle est la puissance à laquelle arrive Sengoku contre Ginue? Sans espaces.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['180000'],
      },
      {
        id: 20,
        title: 'Contre qui se bat Gogeta, dans les hors-séries?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Janemba'],
      },
    ],
  },
  {
    creator: 'Guillaume',
    entityType: EntityType.MANGA,
    entityTitle: 'Death Note',
    level: 1,
    questions: [
      {
        id: 1,
        title:
          "Combien de secondes faut-il pour faire mourir quelqu'un d'une crise cardiaque, sans renseigner de conditions, à l'aide du Death Note?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['40'],
      },
      {
        id: 2,
        title:
          'Comment s\'appelle le shinigami de Misa? Sans mettre de "u" à la fin.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Rem'],
      },
      {
        id: 3,
        title: 'Quel est le fruit préféré de Ryuk? Au singulier.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Pomme'],
      },
      {
        id: 4,
        title:
          'Quel est le réel nom de famille de celle qui se fait appeler Shoko Maki',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Misora'],
      },
      {
        id: 5,
        title: "Combien y'avait t-il d'agents du FBI envoyés au Japon?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['12'],
      },
      {
        id: 6,
        title:
          "Quel est le faux nom de famille des Yagami lorsqu'ils enquêtent avec L?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Asahi'],
      },
      {
        id: 7,
        title: "Combien y'avait t-il de caméras chez Raito installées par L?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['64'],
      },
      {
        id: 8,
        title:
          'Terminez : "L, le sait-tu, que le dieu de la mort ne mange que des pommes, et qu\'il a les mains : ... . Attention aux accords"',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Rouges'],
      },
      {
        id: 9,
        title:
          "Comment s'appelle celui qui présentait le Royaume de Kira avant d'être tué? Donnez le nom de famille.",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Demegawa'],
      },
      {
        id: 10,
        title:
          "Quelle lettre Near utilise t-il pour désigner le Kira qui agit dans l'ombre?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['X'],
      },
      {
        id: 11,
        title: 'Ryuuzaki a 3 identités de détective. L, Coyle et : ... ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Deneuve'],
      },
      {
        id: 12,
        title: 'Quel est le vrai prénom de Near?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Nate'],
      },
      {
        id: 13,
        title:
          'Dans quelle magazine Misa a t-elle fait ses débuts de mannequinat?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Eighteen'],
      },
      {
        id: 14,
        title:
          'A quel idéogramme correspond la syllabe "Ya" dans Yagami? Sans articles.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Nuit'],
      },
      {
        id: 15,
        title:
          'A quel dieu de la mort appartenait le second Death Note de Ryuk? Sans accents',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Sido'],
      },
      {
        id: 16,
        title:
          "Combien Ryuuzaki perd t-il de sa capacité d'analyse s'il ne s'assoie pas comme il le veut? En pourcentages.",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['40'],
      },
      {
        id: 17,
        title: 'Combien de jours Sojiro Yagami est-il resté emprisonné par L?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['50'],
      },
      {
        id: 18,
        title: "Comment s'appellait le directeur de la Wammy's House?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Roger'],
      },
      {
        id: 19,
        title:
          'Complétez : Ooi, Higuchi, Hatori, Kida, Shimura, Takahashi, Mido, : ...',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Namikawa'],
      },
      {
        id: 20,
        title: 'Quel est le vrai nom de famille de L?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Lawliet'],
      },
    ],
  },
  {
    creator: 'Guillaume',
    entityType: EntityType.SERIE,
    entityTitle: 'How I Met Your Mother',
    level: 1,
    questions: [
      {
        id: 1,
        title: 'Combien y a-t-il de personnages principaux?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['5'],
      },
      {
        id: 2,
        title: 'Quel est le pays natif de Robin?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Canada'],
      },
      {
        id: 3,
        title: "Le blond du groupe s'appelle :",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Barney'],
      },
      {
        id: 4,
        title: "Qui a abandonné Ted devant l'autel?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Stella'],
      },
      {
        id: 5,
        title: 'Dans quelle saison Ted et Robin sortent-ils ensemble?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['2'],
      },
      {
        id: 6,
        title: "Qui est l'inventeur du mec à poil?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Barney'],
      },
      {
        id: 7,
        title:
          'En abrégé, dans quelle entreprise Barney, Marshall et Ted se retrouvent-ils à travailler ensemble?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['GNB'],
      },
      {
        id: 8,
        title: 'Quel est le métier du sosie de Ted?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Acteur'],
      },
      {
        id: 9,
        title:
          "Comment s'appelle la fille qui couche avec Ted lorsqu'il siffle 5 dragons rouges?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Blah Blah'],
      },
      {
        id: 10,
        title:
          'Quel numéro Barney réservait-il à un top model sur sa liste de conquêtes?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['31'],
      },
      {
        id: 11,
        title:
          'Combien de séances faut-il à Stella pour effacer le tatouage de Ted?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['6'],
      },
      {
        id: 12,
        title:
          "En quelle couleur Ted s'est-il teint les cheveux durant un épisode?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Bleu'],
      },
      {
        id: 13,
        title: 'Le tatouage de Ted est une estampille de :',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Papillon'],
      },
      {
        id: 14,
        title: 'Qui dit toujours le mot : Littéralement ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Robin'],
      },
      {
        id: 15,
        title: 'Quel est le titre honorifique du mari de Zoé?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Capitaine', 'Captain'],
      },
      {
        id: 16,
        title: "Dans quelle saison se trouve l'épisode : Robin 101?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['5'],
      },
      {
        id: 17,
        title: 'Selon les CGSG, les bottes rouges de Ted ont-elles la classe?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Non'],
      },
      {
        id: 18,
        title: 'Complétez : On devrait acheter un ...',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Bateau'],
      },
      {
        id: 19,
        title: "Complétez : Et on l'appellerait ...",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Le Bro Code', 'Bro Code'],
      },
      {
        id: 20,
        title:
          'Le groupe a parfois un type de conversation spéciale. De quel type est-il?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Bro talk', 'Conversation de mecs'],
      },
    ],
  },
  {
    creator: 'Guillaume',
    entityType: EntityType.MANGA,
    entityTitle: 'Kenshin le Vagabond',
    level: 1,
    questions: [
      {
        id: 1,
        title: 'Quel nom Sanosuké donne-t-il à son zanbato?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Zanbatou'],
      },
      {
        id: 2,
        title: 'Combien de membre(s) des 10 sabres Yahiko bat-il?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['1'],
      },
      {
        id: 3,
        title: 'Quel est le nom du rival assassin de Kenshin à Kyoto?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Shishio'],
      },
      {
        id: 4,
        title: 'Quel est le véritable prénom de Kenshin?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Shinta'],
      },
      {
        id: 5,
        title: 'Complétez : Le sabre est une arme, le kendo est un art de ...',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['vivre'],
      },
      {
        id: 6,
        title: "Combien le dragon de l'école Hiten Mitsurugi a-t-il de têtes?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['9'],
      },
      {
        id: 7,
        title: "Quel nom de famille Saitô a-t-il emprunté dans l'ère Meiji?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Fujita'],
      },
      {
        id: 8,
        title:
          'Combien de semaine(s) Sanosuké met-il pour apprendre le double coup?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['2'],
      },
      {
        id: 9,
        title:
          'À quel âge un Kenjutsuka est-il considéré comme un homme? Écrivez juste le nombre.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['15'],
      },
      {
        id: 10,
        title:
          'De qui Kenshin tient-il son sabre à lame inversée, donnez le prénom?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Hiko'],
      },
      {
        id: 11,
        title:
          "Quel est l'animal récurrent dans les attaques de l'école Hiten Mitsurugi?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Dragon'],
      },
      {
        id: 12,
        title:
          'Combien de fois Raijuta et Kenshin doivent-ils suspendre leur combat?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['2'],
      },
      {
        id: 13,
        title: "Comment s'appelait la femme de Kenshin, donnez le prénom?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Tomoe'],
      },
      {
        id: 14,
        title:
          'Comment Sôjirô a-t-il appelé son propre style de technique batto?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Shukuchi'],
      },
      {
        id: 15,
        title:
          "Qui est le rival de Yahiko dans l'école du sabre qui protège la vie, donnez le prénom?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Henya'],
      },
      {
        id: 16,
        title: "Quel type de Gatotsu représente l'attaque ultime de Saitô?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Zéro', 'Zero'],
      },
      {
        id: 17,
        title:
          "Comment s'appelle la position de sabre que Kenshin prend face à Hannya?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Hirazuki'],
      },
      {
        id: 18,
        title: 'Les Shinsen Gumi étaient aussi appelés les loups de ...?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Mibu'],
      },
      {
        id: 19,
        title:
          "Lorsque Kenshin croit Kaoru morte, il s'exile dans le quartier des ...?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['plaisirs', 'prostituées'],
      },
      {
        id: 20,
        title: 'Le parfum de Tomoe était l\'essence de "..." blanc.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['fleur', 'prunier'],
      },
    ],
  },
  {
    creator: 'Guillaume',
    entityType: EntityType.GAME,
    entityTitle: 'Pokémon Bleu',
    level: 1,
    questions: [
      {
        id: 1,
        title: "Combien Salamèche a-t-il d'évolutions?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['2'],
      },
      {
        id: 2,
        title: 'Combien la 1ère génération compte-t-elle de pokémons?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['151'],
      },
      {
        id: 3,
        title: 'Quel est le type de Steelix?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Acier', 'Sol'],
      },
      {
        id: 4,
        title: 'Quel est le légume que porte Canarticho?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Oignon'],
      },
      {
        id: 5,
        title: 'Quelle est la pré-évolution de Lippoutou?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Lippouti'],
      },
      {
        id: 6,
        title: 'Complétez cette liste : Elechtor, Sulfura, ...',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Artikodin'],
      },
      {
        id: 7,
        title:
          "Combien y a-t-il d'attaques de type électrique qui font des dégâts dans la première génération?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['9'],
      },
      {
        id: 8,
        title: "Comment s'appelle la pré-évolution de Rhinoféros?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Rhinocorne'],
      },
      {
        id: 9,
        title:
          "Comment s'appelle l'attaque ultime de feu dans la première génération?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Déflagration'],
      },
      {
        id: 10,
        title: 'À quel niveau rencontre-t-on Mewtwo dans la grotte?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['70'],
      },
      {
        id: 11,
        title: 'Combien Mew a-t-il de clones?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['1'],
      },
      {
        id: 12,
        title:
          'Combien de pokémons doivent être échangés pour pouvoir évoluer dans la première génération?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['5'],
      },
      {
        id: 13,
        title:
          'Quelle est la CT que donne Giovanni? Attention aux accents éventuels.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Séisme'],
      },
      {
        id: 14,
        title: "Quel niveau a Pikachu lorsqu'on rencontre Red au mont Argent?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['81'],
      },
      {
        id: 15,
        title: 'Quel est le nom du 7ème badge?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Âme', 'Ame'],
      },
      {
        id: 16,
        title:
          "Quel type de ball permet d'attraper plus facilement des pokémons aquatiques, dans la 2ème génération?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Filet'],
      },
      {
        id: 17,
        title: "Quelle est l'évolution finale de Chuchmur?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Brouhabam'],
      },
      {
        id: 18,
        title: 'Quelle attaque contient la CT50?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Clonage', 'Triplattaque'],
      },
      {
        id: 19,
        title: "Comment s'appelle la fille du prof Chen?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Sara', 'Flora'],
      },
    ],
  },
  {
    creator: 'Guillaume',
    entityType: EntityType.SERIE,
    entityTitle: 'Les Simpsons',
    level: 1,
    questions: [
      {
        id: 1,
        title: "Comment s'appelle la sœur de Lisa?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Maggie'],
      },
      {
        id: 2,
        title: "Quelle est la marque de bière qu'Homer adore?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Duff'],
      },
      {
        id: 3,
        title:
          "Sans l'épisode où Marge construit des œuvres avec des bâtonnets, Homer est un vendeur de ... Au pluriel.",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Glaces'],
      },
      {
        id: 4,
        title: 'Dans le film, quel animal Homer adopte-t-il?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Cochon'],
      },
      {
        id: 5,
        title: "Comment s'appelle le plus grand des fils de Flanders?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Todd', 'Toad'],
      },
      {
        id: 6,
        title: 'Qui est le riche milliardaire de Springfield?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Burns'],
      },
      {
        id: 7,
        title:
          'Que possède Tahiti Bob de plus grand que la moyenne, ce qui le rend facilement reconnaissable? Au pluriel et sans article.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Pieds'],
      },
      {
        id: 8,
        title:
          "Complétez : Hou, Kebab d'agneau ! Hou, Kebab de poulet ! Hou, Kebab de :",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Feu'],
      },
      {
        id: 9,
        title: "Quelle langue Milhouse apprend-il à Lisa lors d'un épisode?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Italien'],
      },
      {
        id: 10,
        title:
          'Le syndrome que certaines personnes attrapent à Jérusalem est le syndrome du :',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Messie'],
      },
      {
        id: 11,
        title:
          "Avec qui Edna est-elle sortie lorsqu'elle est arrivée à Springfield pour enseigner?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Moe'],
      },
      {
        id: 12,
        title:
          "Dans quel numéro d'horror show Homer mange-t-il un chewing-gum de l'espace?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['17'],
      },
      {
        id: 13,
        title:
          "Qu'a-t-on volé au serpent pour qu'il décide de devenir un criminel? Sans article.",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Trésor'],
      },
      {
        id: 14,
        title: 'Dans quelle saison se trouve la Ned Zone?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['16'],
      },
      {
        id: 15,
        title:
          "De quel type de sauce est composée la sucette qui contient la clé des menottes d'Homer lorsque celui-ci se fait enlever par Patty et Selma?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Chili'],
      },
      {
        id: 16,
        title:
          "Quel est le prénom de l'homme qui a été élu chef de classe à la place d'Homer en terminale?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Vance'],
      },
      {
        id: 17,
        title:
          "Dans quelle saison revoyons-nous la thérapeute d'Homer du film?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['22'],
      },
      {
        id: 18,
        title:
          'Quel sport Homer et Marge se mettent-ils à pratiquer en compagnie de Skinner et de sa mère?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Curling'],
      },
      {
        id: 19,
        title: 'Marge avait-elle déjà rencontré Homer avant le lycée?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Oui'],
      },
      {
        id: 20,
        title:
          "Quelle est la couleur du peignoir de Bart lorsqu'il se veut playboy après avoir lu les magazines de son père?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Violet'],
      },
    ],
  },
  {
    creator: 'Guillaume',
    entityType: EntityType.SERIE,
    entityTitle: 'South Park',
    level: 1,
    questions: [
      {
        id: 1,
        title: "Comment s'appelle le frère de Kyle?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Ike'],
      },
      {
        id: 2,
        title: "Comment s'appelle le personnage qui meurt tout le temps?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Kenny'],
      },
      {
        id: 3,
        title:
          "D'après Kyle, combien y a-t-il d'attardés dans leur bande de 4?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['3'],
      },
      {
        id: 4,
        title: 'Cartman est incarcéré après avoir commis un crime de ...?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['haine'],
      },
      {
        id: 5,
        title: 'À quel fast-food Cartman est-il accro?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['KFC', 'Kentucky Fried Chicken'],
      },
      {
        id: 6,
        title: "Comment s'appelle le blond toujours super stressé?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Butters'],
      },
      {
        id: 7,
        title:
          "Quel est le surnom que Cartman se donne lorsqu'il est surveillant de couloir?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Caporal', 'Corporal'],
      },
      {
        id: 8,
        title:
          "Terminez cette phrase : Je m'appelle Brad, et je viens dénoncer un crime ...",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['de haine', 'haine'],
      },
      {
        id: 9,
        title: "Combien y a-t-il d'épisodes d'Imagination Land?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['3'],
      },
      {
        id: 10,
        title: 'La bête est moitié Ours, moitié Porc, moitié ...?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Homme'],
      },
      {
        id: 11,
        title: 'Quel est le mot en M?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Merde'],
      },
      {
        id: 12,
        title:
          "Quel personnage Cartman rencontre-t-il lorsqu'il veut faire déprogrammer les Griffins? Ne donner que le prénom.",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Ted'],
      },
      {
        id: 13,
        title:
          'Quel pseudonyme emprunte Kenny sous son identité de super-héros? Sans accent.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Mysterion'],
      },
      {
        id: 14,
        title: 'Quel est, vulgairement, le métier de la mère de Cartman?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Pute', 'Prostituée'],
      },
      {
        id: 15,
        title:
          'Stan et ses amis se sont fait doucher, puis ils ont douché en retour, alors ça va ... !',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['bien', 'ça va'],
      },
      {
        id: 16,
        title: 'Quel est le métier de Randy?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Géologue'],
      },
      {
        id: 17,
        title: "Quelle saison contient l'épisode Guitar Zéro?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['12'],
      },
      {
        id: 18,
        title: 'Quel est le prénom du vrai père de Cartman?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Jack'],
      },
      {
        id: 19,
        title:
          "Combien de fois le mot Merde est-il dit dans l'épisode qui lui est consacré?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['162'],
      },
      {
        id: 20,
        title:
          'Dans quoi Cartman a-t-il fait manger à Scott Tenorman ses parents?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Chili'],
      },
    ],
  },
  {
    creator: 'Guillaume',
    entityType: EntityType.SERIE,
    entityTitle: 'Yu Yu Hakusho',
    level: 1,
    questions: [
      {
        id: 1,
        title: "Quel est le type d'énergie qu'utilise Yusuke? Au féminin.",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Astrale'],
      },
      {
        id: 2,
        title: "Comment s'appelle celui qui possède le troisième œil?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Hiei'],
      },
      {
        id: 3,
        title:
          "Combien de membres combattants contient l'équipe Urameshi dans les arts martiaux de l'ombre?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['5'],
      },
      {
        id: 4,
        title:
          "Comment s'appelle le démon qui vole les techniques des grands maîtres avant de les tuer?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Rando'],
      },
      {
        id: 5,
        title: "Comment s'appelle celui qui maîtrise l'énergie divine?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Sensui'],
      },
      {
        id: 6,
        title: 'De quelle couleur est le feu du seigneur des ténèbres de Hiei?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Noir'],
      },
      {
        id: 7,
        title: "Complétez : La fleur, c'est le cerisier. L'homme, c'est ... .",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Kuwabara'],
      },
      {
        id: 8,
        title: 'Toguro est un monstre de classe :',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['B'],
      },
      {
        id: 9,
        title: "Quel est le nom de l'ancienne identité de Kurama?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Yoko'],
      },
      {
        id: 10,
        title:
          'Quelle nouvelle technique de type astrale utilise Yusuke face à Jin?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Vague'],
      },
      {
        id: 11,
        title: 'Combien de personnages différents composent Sensui?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['7'],
      },
      {
        id: 12,
        title: 'De quel élément Toya est-il le maître?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Glace'],
      },
      {
        id: 13,
        title: 'Quel est le nom du vrai père de Yusuke?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Raizen'],
      },
      {
        id: 14,
        title: 'Quel est le nom de famille de Keiko?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Yukimura'],
      },
      {
        id: 15,
        title:
          "Combien de fois Kuwabara se fait-il envoyer balader face aux légendes de l'enfer?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['2'],
      },
      {
        id: 16,
        title: "Quel adjectif Suzuki désire-t-il qu'on mette devant son nom?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Sublime'],
      },
      {
        id: 17,
        title: 'En combien Suzaku se démultiplie-t-il?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['7'],
      },
      {
        id: 18,
        title:
          "De quelle race est l'ancêtre de Yusuke qui lui permet une renaissance sous cette même forme?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Mazoku'],
      },
      {
        id: 19,
        title:
          "De quelle couleur est l'animal qui est le reflet de l'âme de Yusuke? Donnez la couleur au masculin singulier.",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Bleu'],
      },
      {
        id: 20,
        title:
          'Combien de milliards Mr. Saito mise-t-il sur la victoire des intrus face aux frères Toguro?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['60000', '60'],
      },
    ],
  },
  {
    creator: 'Guillaume',
    entityType: EntityType.GAME,
    entityTitle: 'The Legend of Zelda: Ocarina of Time',
    level: 1,
    questions: [
      {
        id: 1,
        title: "Comment s'appelle le héros?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Link'],
      },
      {
        id: 2,
        title: 'Combien y a-t-il de déesses?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['3'],
      },
      {
        id: 3,
        title: 'Quel est le nom du méchant récurrent?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Ganon', 'Ganondorf'],
      },
      {
        id: 4,
        title:
          "Quel est le nom célèbre à travers les Zelda de l'attaque tournante à l'épée?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Tourbillon', 'Spin Attack'],
      },
      {
        id: 5,
        title: 'Quel objet permet au héros de vaincre Volvagia, en un mot?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Marteau', 'Hammer'],
      },
      {
        id: 6,
        title: 'Quel est le nom donné au peuple du désert, au singulier?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Gerudo'],
      },
      {
        id: 7,
        title: "Quel est le nom de l'ennemi principal de Minish Cap?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Vaati'],
      },
      {
        id: 8,
        title: 'Combien y a-t-il de flacons dans Ocarina of Time?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['4'],
      },
      {
        id: 9,
        title:
          'Au bout de combien de Skulltulas tuées obtient-on des missiles?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['50'],
      },
      {
        id: 10,
        title: 'Combien y a-t-il de types de flèches dans The Wind Waker?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['3'],
      },
      {
        id: 11,
        title:
          "Dans Skyward Sword, comment s'appelle le boss que l'on combat dans 2 temples différents?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Ghirahim'],
      },
      {
        id: 12,
        title: 'Combien y a-t-il de mélodies jouables dans The Wind Waker?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['4', '5'],
      },
      {
        id: 13,
        title: "Quel est le nom de l'épée la plus puissante dans OOT?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Lame de Légende', 'Épée de Légende'],
      },
      {
        id: 14,
        title:
          "Quel est en un mot l'objet récupéré à la tour du Jugement dans Twilight Princess?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Sceptre', 'Dominion Rod'],
      },
      {
        id: 15,
        title: 'Combien y a-t-il de médaillons dans OOT?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['6'],
      },
      {
        id: 16,
        title:
          'Quel est le nom donné aux chevaliers en armure dans TWW, au singulier?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Darknut', 'Chevalier'],
      },
      {
        id: 17,
        title: "Comment s'appelle l'île marchande de The Wind Waker?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Île du Vent', 'Windfall'],
      },
      {
        id: 18,
        title: 'Dans OOT, Ganondorf est appelé comme le Seigneur du/des :',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Ténèbres'],
      },
      {
        id: 19,
        title: 'Quel est le nom donné aux figurines de The Wind Waker?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Statues', 'Figurines'],
      },
      {
        id: 20,
        title:
          "Dans ALTTP, les bottes permettant d'aller plus vite sont les bottes de : ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Pégase'],
      },
    ],
  },
  {
    creator: 'Guillaume',
    entityType: EntityType.BD,
    entityTitle: 'Le Donjon de Naheulbeuk',
    level: 1,
    questions: [
      {
        id: 1,
        title:
          "Avant l'arrivée du ménestrel, le groupe est composé de : Nain, Elfe, Ranger, Ogre, Magicienne, Voleur et : ... ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Barbare'],
      },
      {
        id: 2,
        title: "La robe de l'archimage a une fonction : ... ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Chauffante'],
      },
      {
        id: 3,
        title: "Complétez : Hum, c'est bon d'offrir son corps à la : ... ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Nature'],
      },
      {
        id: 4,
        title:
          'De quelle couleur est la statuette de Gladoflera? Au masculin singulier.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Vert'],
      },
      {
        id: 5,
        title:
          "Quelle est la réponse à cette énigme : \"Jamais je ne suis loin de mon autre jumelle, on m'associe souvent au parfum vomitif, d'une partie du corps qui n'est pas vraiment belle, localisée fort loin de l'organe olfactif.\" ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Chaussette'],
      },
      {
        id: 6,
        title: 'Combien de jambes le nain de la légende a-t-il?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['9'],
      },
      {
        id: 7,
        title: 'De quel niveau est le ménestrel?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['3'],
      },
      {
        id: 8,
        title:
          "D'après l'écriteau devant l'arbre des pendus, combien de voleurs de boudins ont été pendus à ce même endroit?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['287'],
      },
      {
        id: 9,
        title: "Combien de pièces d'or coûte la couronne de Promfio?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['6000'],
      },
      {
        id: 10,
        title:
          'Lorsque la magicienne passe niveau 2, elle obtient le contrôle mental des : ... ? Au pluriel.',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Rongeurs'],
      },
      {
        id: 11,
        title:
          "Quel niveau faut-il à l'elfe pour utiliser l'arc que lui donne la reine des elfes?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['6'],
      },
      {
        id: 12,
        title: 'Combien de bras a le Golbarg?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['4'],
      },
      {
        id: 13,
        title:
          "Complétez le trou : \"Je vois le genre ! Équipé des moufles à 3 doigts, on utilise l'arc pour tuer des moineaux. On les fait cuire avec les pics à brochettes en faisant un feu dans la boîte à sucre avec des débris de ski nautique et on les mange avec les fourchettes du .................. . On essuie nos bouches pleines de baves avec l'essuie-tout magique, ensuite de quoi l'elfe s'enduit avec la fiole de baume à la con. Puis elle exécute une danse autour du feu avec les chaussons shtarbés et le collier en dent d'ours tout en agitant l'épée gonflable, et pour finir on se pend avec la corde trop courte parce qu'on est toujours perdus et qu'on est ridicule !\"",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Poulpe'],
      },
      {
        id: 14,
        title:
          "Combien les gardiens de la porte à Shnafon demandent-ils de pièces d'or aux aventuriers pour pouvoir entrer?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['4'],
      },
      {
        id: 15,
        title: 'Le point faible de Xandar est la : ... .',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Musique'],
      },
      {
        id: 16,
        title:
          "L'animal dont les globzouls sont les plus proches est le : ... .",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Singe'],
      },
      {
        id: 17,
        title: 'Que signifie "Shlagvuk" ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Manger'],
      },
      {
        id: 18,
        title: 'De quel niveau est le mage Gontrand?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['12'],
      },
      {
        id: 19,
        title: 'Sur quoi le paladin a-t-il choisi son dieu?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Catalogue'],
      },
      {
        id: 20,
        title: "La couette de l'oubli célèbre le retour de :",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Dlul'],
      },
    ],
  },
  {
    creator: 'Guillaume',
    entityType: EntityType.BOOK,
    entityTitle: "Harry Potter à l'école des sorciers",
    level: 1,
    questions: [
      {
        id: 1,
        title: "Comment s'appelle Celui-Dont-On-Ne-Doit-Pas-Prononcer-Le-Nom ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Voldemort'],
      },
      {
        id: 2,
        title: 'Dans quelle maison le Choixpeau envoie-t-il Neville Londubat ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Gryffondor'],
      },
      {
        id: 3,
        title: 'Quelle formule permet de faire venir à soi un objet ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Accio'],
      },
      {
        id: 4,
        title: 'Complétez : Diggory, Delacour, Potter, ... ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Krum'],
      },
      {
        id: 5,
        title: "A.D signifie en fait : L'Armée de ... ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Dumbledore'],
      },
      {
        id: 6,
        title: "Quelle formule permet d'utiliser le sortilège de l'Impérium ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Imperio', 'Impero'],
      },
      {
        id: 7,
        title:
          "Comment s'appelle le gobelin qui conduit Harry à la salle des coffres dans le premier tome ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Gripsec'],
      },
      {
        id: 8,
        title:
          'Quel était le prénom de celui qui a donné son nom à la maison Serpentard ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Salazar'],
      },
      {
        id: 9,
        title:
          'Sur les 3 sortilèges impardonnables, combien Harry en a-t-il déjà utilisé ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['2'],
      },
      {
        id: 10,
        title: 'De quel frère Peverell Harry est-il le descendant ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Ignotus', 'Ignitus'],
      },
      {
        id: 11,
        title: 'Dans combien de tomes voit-on de vrais Détraqueurs ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['4'],
      },
      {
        id: 12,
        title:
          'Quel surnom Peeves donne-t-il à Voldemort dans sa chanson lorsque celui-ci est finalement vaincu ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Voldy'],
      },
      {
        id: 13,
        title:
          "Qui était directeur de Poudlard à l'époque où Dumbledore était professeur de métamorphose ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Dippet'],
      },
      {
        id: 14,
        title:
          "Dans l'ordre chronologique, à quelle maison appartient le 5ème Horcruxe détruit ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Serdaigle'],
      },
      {
        id: 15,
        title: 'Quel est le 4ème prénom de Dumbledore ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Brian', 'Bryan'],
      },
      {
        id: 16,
        title:
          'Dans quel pays Voldemort avait-il caché le diadème de Serdaigle ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Albanie'],
      },
      {
        id: 17,
        title:
          "Combien de gallions Harry reçoit-il lorsqu'il gagne le tournoi des 3 sorciers ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['1000'],
      },
      {
        id: 18,
        title: 'En anglais, comment se traduit "Serpentard" ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Slytherin', 'Syltherin'],
      },
      {
        id: 19,
        title: 'En quel animal James Potter pouvait-il se changer ?',
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Cerf'],
      },
      {
        id: 20,
        title: "Quel était alors son surnom à l'époque ?",
        multipleChoice: false,
        proposedAnswers: [],
        acceptedAnswers: ['Cornedrue', 'Cornedru'],
      },
    ],
  },
];
