import { UserManga } from '../../../../models/manga-model';

export const hikenMangas: UserManga[] = [
  {
    title: "Naruto",
    author: "Masashi Kishimoto",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Kingdom",
    author: "Yasuhisa Hara",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "My Hero Academia",
    author: "Horikoshi Kouhei",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Black Clover",
    author: "Tabata Yuuki",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Dandadan",
    author: "Yukinobu Tatsu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Dragon Ball",
    author: "Akira Toriyama",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Dragon Ball Super",
    author: "Akira Toriyama, Toyotarou",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Kuroko No Basket",
    author: "Tadatoshi Fujimaki",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Reborn",
    author: "Akira Amano",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Magi The Labyrinth of Magic",
    author: "Ohtaka Shinobu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fullmetal Alchemist",
    author: "Hiromu Arakawa",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Gamble fish",
    author: "Aoyama Hiromi",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Nanatsu No Taizai",
    author: "Suzuki Nakaba",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Shaman king",
    author: "Hiroyuki Takei",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "One Piece",
    author: "Eiichirō Oda",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Toriko",
    author: "Shimabukuro Mitsutoshi",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Worst",
    author: "Hiroshi Takahashi",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Death Note",
    author: "Takeshi Obata",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Hunter X Hunter",
    author: "Yoshihiro Togashi",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Beelzebub",
    author: "Ryūhei Tamura",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "L'attaque des titans",
    author: "Isayama Hajime",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Gamaran",
    author: "Yōsuke Nakamaru",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "The Breaker",
    author: "Jeon Geuk-Jin",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "The Breaker : New Waves",
    author: "Jeon Geuk-Jin",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Yu-Gi-Oh!",
    author: "Kazuki Takahashi",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Bleach",
    author: "Tite Kubo",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Crows",
    author: "Hiroshi Takahashi",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "The Promised Neverland",
    author: "Kaiu Shirai",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Demon Slayer",
    author: "Koyoharu Gotouge",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "JoJo's Bizarre Adventure",
    author: "Hirohiko Araki",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Chainsaw Man",
    author: "Tatsuki Fujimoto",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Berserk",
    author: "Kentaro Miura",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Gantz",
    author: "Hiroya Oku",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Soul Eater",
    author: "Atsushi Ōkubo",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Sakamoto Days",
    author: "Yuto Suzuki",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Vinland Saga",
    author: "Makoto Yukimura",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Alice in Borderland",
    author: "Haro Aso",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fairy Tail",
    author: "Hiro Mashima",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Jujutsu Kaisen",
    author: "Gege Akutami",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "D.Gray-man",
    author: "Katsura Hoshino",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Übel Blatt",
    author: "Etorouji Shiono",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Zatchbell (Konjiki no Gash !!)",
    author: "Makoto Raiku",
    readDate: "",
    rating: 3.5,
    readTimes: 2,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  }
];
