import { UserBooks } from '../../../../models/book-model';

export const kevinReadListBooks: UserBooks = [
  {
    title: "Jeux d'Ombres",
    author: 'Glen Cook',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 2,
    wantToReadAgain: false,
  },
  {
    title: "Rêves d'Acier",
    author: 'Glen Cook',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 2,
    wantToReadAgain: false,
  },
  {
    title: "La Pointe d'Argent",
    author: 'Glen Cook',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },
  {
    title: 'Saisons Funestes',
    author: 'Glen Cook',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },
  {
    title: 'Elle est les Ténèbres - Part. 1',
    author: 'Glen Cook',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },
  {
    title: 'Elle est les Ténèbres - Part. 2',
    author: 'Glen Cook',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },
  {
    title: "L'Eau Dort - Part. 1",
    author: 'Glen Cook',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },
  {
    title: "L'Eau Dort - Part. 2",
    author: 'Glen Cook',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },
  {
    title: 'Les Soldats de Pierre - Part. 1',
    author: 'Glen Cook',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },
  {
    title: 'La Voie des Ombres',
    author: 'Brent Weeks',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 2,
    wantToReadAgain: false,
  },
  {
    title: 'Le Prisme Noir',
    author: 'Brent Weeks',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 2,
    wantToReadAgain: false,
  },
  {
    title: 'Les Soldats de Pierre - Part. 2',
    author: 'Glen Cook',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },

  {
    title: 'Le Nom du Vent',
    author: 'Patrick Rothfuss',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 3,
    wantToReadAgain: false,
  },

  {
    title: 'La Peur du Sage (2/2)',
    author: 'Patrick Rothfuss',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 3,
    wantToReadAgain: false,
  },

  {
    title: 'Le Choix des Ombres',
    author: 'Brent Weeks',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },

  {
    title: 'Au-delà des Ombres',
    author: 'Brent Weeks',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },

  {
    title: 'Le Palais Adamantin',
    author: 'Stephen Deas',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 3,
    wantToReadAgain: false,
  },

  {
    title: 'Le Roi des Cimes',
    author: 'Stephen Deas',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 3,
    wantToReadAgain: false,
  },

  {
    title: "L'Ordre des Ecailleux",
    author: 'Stephen Deas',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 3,
    wantToReadAgain: false,
  },

  {
    title: 'Le Feu de la Sorcière',
    author: 'James Clemens',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },

  {
    title: 'Les Foudres de la Sorcière',
    author: 'James Clemens',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },

  {
    title: 'La Guerre de la Sorcière',
    author: 'James Clemens',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },

  {
    title: 'Le Portail de la Sorcière',
    author: 'James Clemens',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },

  {
    title: "L'Etoile de la Sorcière",
    author: 'James Clemens',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },

  {
    title: 'Le Couteau Aveuglant',
    author: 'Brent Weeks',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },

  {
    title: "L'Oeil Brisé",
    author: 'Brent Weeks',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },

  {
    title: 'Le Miroir de Sang',
    author: 'Brent Weeks',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },

  {
    title: 'Le Blanc Incandescent (1/2)',
    author: 'Brent Weeks',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },

  {
    title: 'Le Blanc Incandescent (2/2)',
    author: 'Brent Weeks',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
  },
];
