import { BadgeDefinition, BADGES_IMAGE_PATH } from '../../models/badge-model';

export const BOOKS_BADGE_DEFINITIONS: BadgeDefinition[] = [
  {
    id: 'petit-lecteur',
    name: 'Petit lecteur',
    description: 'Avoir lu au moins 50 livres',
    image: `${BADGES_IMAGE_PATH}/books/Bella_Swan.png`,
    threshold: 50,
  },
  {
    id: 'graine-lecteur',
    name: 'Graine de lecteur',
    description: 'Avoir lu au moins 100 livres',
    image: `${BADGES_IMAGE_PATH}/books/Will_Hunting.png`,
    threshold: 100,
  },
  {
    id: 'lecteur-assidu',
    name: 'Lecteur assidu',
    description: 'Avoir lu au moins 150 livres',
    image: `${BADGES_IMAGE_PATH}/books/John_Keating.png`,
    threshold: 150,
  },
  {
    id: 'lecteur-chevronne',
    name: 'Lecteur chevronné',
    description: 'Avoir lu au moins 200 livres',
    image: `${BADGES_IMAGE_PATH}/books/Tyrion_Lannister.png`,
    threshold: 200,
  },
  {
    id: 'lecteur-passionne',
    name: 'Lecteur passionné',
    description: 'Avoir lu au moins 250 livres',
    image: `${BADGES_IMAGE_PATH}/books/Belle.png`,
    threshold: 250,
  },
  {
    id: 'lecteur-veteran',
    name: 'Lecteur vétéran',
    description: 'Avoir lu au moins 300 livres',
    image: `${BADGES_IMAGE_PATH}/books/Harlan.png`,
    threshold: 300,
  },
  {
    id: 'rat-bibliotheque',
    name: 'Rat de bibliothèque',
    description: 'Avoir lu au moins 350 livres',
    image: `${BADGES_IMAGE_PATH}/books/Hermione_Granger.png`,
    threshold: 350,
  },
  {
    id: 'amoureux-lecture',
    name: 'Amoureux de la lecture',
    description: 'Avoir lu au moins 400 livres',
    image: `${BADGES_IMAGE_PATH}/books/Liesel_Meminger.png`,
    threshold: 400,
  },
  {
    id: 'maitre-lecteur',
    name: 'Maître lecteur',
    description: 'Avoir lu au moins 450 livres',
    image: `${BADGES_IMAGE_PATH}/books/Carlisle_Cullen.webp`,
    threshold: 450,
  },
  {
    id: 'doyen-lecteurs',
    name: 'Doyen des lecteurs',
    description: 'Avoir lu au moins 500 livres',
    image: `${BADGES_IMAGE_PATH}/books/Albus_Dumbledore.png`,
    threshold: 500,
  },
  // ——— Fantasy (livres)
  {
    id: 'sorcelier',
    name: 'Sorcelier',
    description: 'Avoir lu au moins 15 livres de fantasy',
    image: `${BADGES_IMAGE_PATH}/books/Tara_Duncan.png`,
    threshold: 15,
  },
  {
    id: 'demi-dieu',
    name: 'Demi-dieu',
    description: 'Avoir lu au moins 30 livres de fantasy',
    image: `${BADGES_IMAGE_PATH}/books/Percy_Jackson.png`,
    threshold: 30,
  },
  {
    id: 'reine-dragons',
    name: 'Reine des dragons',
    description: 'Avoir lu au moins 50 livres de fantasy',
    image: `${BADGES_IMAGE_PATH}/books/Daenerys.png`,
    threshold: 50,
  },
  {
    id: 'elu-prophetie',
    name: 'Elu de la prophetie',
    description: 'Avoir lu au moins 80 livres de fantasy',
    image: `${BADGES_IMAGE_PATH}/books/Harry_Potter.png`,
    threshold: 80,
  },
  {
    id: 'seigneur-fantasy',
    name: 'Seigneur de la fantasy',
    description: 'Avoir lu au moins 100 livres de fantasy',
    image: `${BADGES_IMAGE_PATH}/books/Sauron.jpg`,
    threshold: 100,
  },
  // ——— Romance (livres)
  {
    id: 'petit-beguin-books',
    name: 'Petit béguin',
    description: 'Avoir lu au moins 15 livres de romance',
    image: `${BADGES_IMAGE_PATH}/books/Hazel_et_Gus.png`,
    threshold: 15,
  },
  {
    id: 'lover-books',
    name: 'Lover',
    description: 'Avoir lu au moins 30 livres de romance',
    image: `${BADGES_IMAGE_PATH}/books/Jamie_et_London.png`,
    threshold: 30,
  },
  {
    id: 'ames-soeurs',
    name: 'Âmes-sœurs',
    description: 'Avoir lu au moins 50 livres de romance',
    image: `${BADGES_IMAGE_PATH}/books/Bella_et_Edward.png`,
    threshold: 50,
  },
  {
    id: 'amour-a-travers-la-mort',
    name: "L'amour absolu",
    description: 'Avoir lu au moins 80 livres de romance',
    image: `${BADGES_IMAGE_PATH}/books/Romeo_et_Juliette.png`,
    threshold: 80,
  },
  {
    id: 'icone-romance',
    name: 'Icône de la romance',
    description: 'Avoir lu au moins 100 livres de romance',
    image: `${BADGES_IMAGE_PATH}/books/Elizabeth_et_Darcy.png`,
    threshold: 100,
  },
  // ——— Science-fiction (livres)
  {
    id: 'marche-vers-l-inconnu',
    name: "En marche vers l'inconnu",
    description: 'Avoir lu au moins 15 livres de science-fiction',
    image: `${BADGES_IMAGE_PATH}/books/La_Horde_Du_Contrevent.png`,
    threshold: 15,
  },
  {
    id: 'guerrier-omniscient',
    name: 'Guerrier omniscient',
    description: 'Avoir lu au moins 30 livres de science-fiction',
    image: `${BADGES_IMAGE_PATH}/books/Dune.png`,
    threshold: 30,
  },
  {
    id: 'explorateur-profondeurs',
    name: 'Explorateur des profondeurs',
    description: 'Avoir lu au moins 50 livres de science-fiction',
    image: `${BADGES_IMAGE_PATH}/books/Nautilus.png`,
    threshold: 50,
  },
  {
    id: 'survivant-invasion',
    name: "Survivant de l'invasion",
    description: 'Avoir lu au moins 80 livres de science-fiction',
    image: `${BADGES_IMAGE_PATH}/books/Guerre_des_Mondes.png`,
    threshold: 80,
  },
  {
    id: 'architecte-psychohistoire',
    name: 'Architecte de la psychohistoire',
    description: 'Avoir lu au moins 100 livres de science-fiction',
    image: `${BADGES_IMAGE_PATH}/books/Fondation.png`,
    threshold: 100,
  },
  // ——— Policier (livres)
  {
    id: 'amateur-polars',
    name: 'Amateur de polars',
    description: 'Avoir lu au moins 15 livres de policier',
    image: `${BADGES_IMAGE_PATH}/books/Millenium.png`,
    threshold: 15,
  },
  {
    id: 'enqueteur-verite',
    name: 'Enquêteur de la vérité',
    description: 'Avoir lu au moins 30 livres de policier',
    image: `${BADGES_IMAGE_PATH}/books/Da_Vinci_Code.png`,
    threshold: 30,
  },
  {
    id: 'artiste-evasion',
    name: "Artiste de l'évasion",
    description: 'Avoir lu au moins 50 livres de policier',
    image: `${BADGES_IMAGE_PATH}/books/Arsene_Lupin.png`,
    threshold: 50,
  },
  {
    id: 'maitre-mystere',
    name: 'Maître du mystère',
    description: 'Avoir lu au moins 80 livres de policier',
    image: `${BADGES_IMAGE_PATH}/books/Ils_Etaient_Dix.png`,
    threshold: 80,
  },
  {
    id: 'genie-deduction',
    name: 'Génie de la déduction',
    description: 'Avoir lu au moins 100 livres de policier',
    image: `${BADGES_IMAGE_PATH}/books/Sherlock_Holmes.png`,
    threshold: 100,
  },
  // ——— Nonfiction (livres)
  {
    id: 'lecteur-curieux-nonfiction',
    name: 'Lecteur curieux',
    description: 'Avoir lu au moins 15 livres de nonfiction',
    image: `${BADGES_IMAGE_PATH}/books/Anne_Frank.png`,
    threshold: 15,
  },
  {
    id: 'chercheur-savoir',
    name: 'Chercheur du savoir',
    description: 'Avoir lu au moins 30 livres de nonfiction',
    image: `${BADGES_IMAGE_PATH}/books/Nelson_Mandela.png`,
    threshold: 30,
  },
  {
    id: 'precurseur-progres',
    name: 'Précurseur du progrès',
    description: 'Avoir lu au moins 50 livres de nonfiction',
    image: `${BADGES_IMAGE_PATH}/books/Simone_Veil.png`,
    threshold: 50,
  },
  {
    id: 'icone-changement',
    name: 'Icône du changement',
    description: 'Avoir lu au moins 80 livres de nonfiction',
    image: `${BADGES_IMAGE_PATH}/books/Martin_Luther_King.png`,
    threshold: 80,
  },
  {
    id: 'sage-humanite',
    name: "Sage de l'humanité",
    description: 'Avoir lu au moins 100 livres de nonfiction',
    image: `${BADGES_IMAGE_PATH}/books/Gandhi.png`,
    threshold: 100,
  },
  // ——— Aventure (livres)
  {
    id: 'explorateur',
    name: 'Explorateur',
    description: 'Avoir lu au moins 15 livres d’aventure',
    image: `${BADGES_IMAGE_PATH}/books/Alice_Au_Pays_Des_Merveilles.png`,
    threshold: 15,
  },
  {
    id: 'moussaillon-flots',
    name: 'Moussaillon des flots',
    description: 'Avoir lu au moins 30 livres d’aventure',
    image: `${BADGES_IMAGE_PATH}/books/Ile_Au_Tresor.png`,
    threshold: 30,
  },
  {
    id: 'grand-voyageur-livres',
    name: 'Grand voyageur',
    description: 'Avoir lu au moins 50 livres d’aventure',
    image: `${BADGES_IMAGE_PATH}/books/Le_Tour_Du_Monde_En_80_Jours.png`,
    threshold: 50,
  },
  {
    id: 'ubiquiste-monde',
    name: 'Ubiquiste du monde',
    description: 'Avoir lu au moins 80 livres d’aventure',
    image: `${BADGES_IMAGE_PATH}/books/Le_Comte_De_Monte_Cristo.png`,
    threshold: 80,
  },
  {
    id: 'aventurier-legendaire',
    name: 'Aventurier légendaire',
    description: 'Avoir lu au moins 100 livres d’aventure',
    image: `${BADGES_IMAGE_PATH}/books/Odyssee.png`,
    threshold: 100,
  },
];
