import { UserBds } from '../../../../models/bd-model';

export const guillaumeBds: UserBds = [
  {
    writer: 'Stephane Jourdain',
    title: "L'Arnaque des nouveaux pères",
    readDate: '2024-11-11',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: 'Thibault',
  },
  {
    title: 'CommitStrip : Rise of The Coders',
    writer: 'Etienne Issartial',
    readDate: '2016-11-11',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "L'Élève Ducobu - Tome 1 - Un copieur sachant copier !",
    writer: 'Godi',
    readDate: '2005-07-12',
    rating: 3.5,
    readTimes: 5,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "L'Élève Ducobu - Tome 3 - Les réponses ou la vie ?",
    writer: 'Godi',
    readDate: '2005-08-03',
    rating: 3.5,
    readTimes: 5,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "L'Élève Ducobu - Tome 6 - Un amour de potache",
    writer: 'Godi',
    readDate: '2006-01-20',
    rating: 3.5,
    readTimes: 5,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "L'Élève Ducobu - Tome 10 - Miss Dix sur Dix",
    writer: 'Godi',
    readDate: '2007-04-08',
    rating: 3.5,
    readTimes: 5,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "L'Élève Ducobu - Tome 12 - 280 de Q.I. !",
    writer: 'Godi',
    readDate: '2008-02-14',
    rating: 3.5,
    readTimes: 5,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Titeuf - Tome 1 - Dieux, le sexe, et les bretelles',
    writer: 'Zep',
    readDate: '2003-06-01',
    rating: 3.5,
    readTimes: 5,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "Titeuf - Tome 2 - L'amour, c'est po propre !",
    writer: 'Zep',
    readDate: '2003-08-15',
    rating: 3.5,
    readTimes: 15,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Titeuf - Tome 3 - Ça épate les filles !',
    writer: 'Zep',
    readDate: '2004-01-10',
    rating: 3.5,
    readTimes: 15,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "Titeuf - Tome 4 - C'est pô juste...",
    writer: 'Zep',
    readDate: '2004-05-22',
    rating: 3.5,
    readTimes: 15,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Titeuf - Tome 5 - Le derrière des choses',
    writer: 'Zep',
    readDate: '2004-09-01',
    rating: 3.5,
    readTimes: 15,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Titeuf - Tome 6 - Tchô, monde cruel !',
    writer: 'Zep',
    readDate: '2005-03-18',
    rating: 3.5,
    readTimes: 5,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Titeuf - Tome 7 - Le miracle de la vie',
    writer: 'Zep',
    readDate: '2005-11-05',
    rating: 3.5,
    readTimes: 15,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Titeuf - Tome 8 - Lâchez-moi le slip !',
    writer: 'Zep',
    readDate: '2006-07-20',
    rating: 3.5,
    readTimes: 10,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Titeuf - Tome 9 - La loi du préau',
    writer: 'Zep',
    readDate: '2007-01-12',
    rating: 3.5,
    readTimes: 10,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
];
