import { UserSeries } from '../../../../models/serie-model';

export const cassandreSeries: UserSeries = [
  {
    title: 'One Piece',
    director: 'Eiichiro Oda',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 8,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 9,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 10,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 11,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 12,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 13,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 14,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 15,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 16,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 17,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 18,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 19,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 20,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 21,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 22,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Dandadan',
    director: 'Yukinobu Tatsu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Dragon Ball Z',
    director: 'Akira Toriyama',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 8,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 9,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 10,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 11,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Dragon Ball GT',
    director: 'Akira Toriyama',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Puella Magi Madoka Magica',
    director: 'Akiyuki Shinbo',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 10,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Shokugeki no Soma (Food Wars)',
    director: 'Yūto Tsukuda',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Beelzebub',
    director: 'Ryūhei Tamura',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Bleach',
    director: 'Tite Kubo',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 8,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 9,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 10,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 11,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 12,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 13,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 14,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 15,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 16,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 17,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Jujutsu Kaisen',
    director: 'Gege Akutami',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "JoJo's Bizarre Adventure",
    director: 'Hirohiko Araki',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Demon Slayer',
    director: 'Koyoharu Gotouge',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Spy x Family',
    director: 'Tatsuya Endo',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "Les Mystérieuses Cités d'Or",
    director: 'Bernard Deyriès',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Magical Dorémi',
    director: 'Junichi Sato',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "Les carnets de l'apothicaire",
    director: 'Natsu Hyuuga',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Code Lyoko',
    director: 'Thomas Romain, Tania Palumbo',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 10,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 10,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 10,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 10,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Totally Spies',
    director: 'Vincent Chalvon-Demersay, David Michel',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Les super nanas',
    director: 'Craig McCracken',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 8,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 9,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 10,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 11,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "Les zinzins de l'espace",
    director: 'Jean-Yves Raimbaud',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 8,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 9,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 10,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 11,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Le marsupilami',
    director: 'André Franquin',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Oggy et les cafards',
    director: 'Jean-Yves Raimbaud',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "Bob l'éponge",
    director: 'Stephen Hillenburg',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Les Tortues Ninja',
    director: 'Kevin Eastman, Peter Laird',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 8,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 9,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 10,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 11,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Princesse Sarah',
    director: 'Frances Hodgson Burnett',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Pokémon',
    director: 'Satoshi Tajiri',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 8,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 9,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 10,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 11,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 12,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 13,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 14,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 15,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 16,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 17,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 18,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 19,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 20,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 21,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 22,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 23,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 24,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Marcelino',
    director: 'José María Sánchez-Silva',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Nicky Larson',
    director: 'Kenji Kodama',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Yu-Gi-Oh!',
    director: 'Kunihisa Sugishima',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 8,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Death Note',
    director: 'Tetsurō Araki',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 10,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Soul Eater',
    director: 'Takuya Igarashi',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Full Metal Alchemist',
    director: 'Seiji Mizushima',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Fullmetal Alchemist: Brotherhood',
    director: 'Yasuhiro Irie',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 2,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 2,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: "L'Attaque des Titans",
    director: 'Tetsurô Araki',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'One Punch Man',
    director: 'Shingo Natsume, Chikara Sakurai',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Arcane',
    director: 'Pascal Charrue, Arnaud Delord',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },

  {
    title: 'Galactik Football',
    director: 'Charles Barrez, Vincent Vandelli',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 5,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 5,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 1,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Code Geass',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'GTO : Great Teacher Onizuka',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Psycho-Pass',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Your Lie in April',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Sword Art Online',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Tokyo Ghoul',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Fairy Tail',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 8,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 9,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Fate/zero',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Fate Stay Night',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Fate Apocrypha',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Fate Grand Order',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Fate Unlimited blade works',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'RWBY',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 6,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 7,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 8,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 9,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Elfen Lied',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Angel Beats!',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Charlotte',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Clannad',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Mirai Nikki',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Durarara!!',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Nana',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Black Butler',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Violet Evergarden',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'The Promised Neverland',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Death Parade',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Magia record',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Gambling School',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Oshi no Ko',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Another',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Solo Leveling',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Tower of god',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Noblesse',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Beyblade',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'High school of the dead',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Deadman Wonderland',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Danganronpa',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "Darwin's Game",
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Toriko',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Aggretsuko',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Sailor Moon',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 4,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 5,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Fruit Basket',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 2,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
      {
        seasonNumber: 3,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Guilty Crown',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Sakura chasseuse de cartes',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Hamtaro',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Higurashi no naku koro ni',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Umineko no naku koro ni',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Romeo X Juliet',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Jeanne et Serge',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Toradora !',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Tonari no Kaibutsu-kun',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Maid sama',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'My happy marriage',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Yakuza fiancee',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Si je suis la vilaine, autant mater le boss final',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'winx club',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'magical girl raising project',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'wish upon the pleiades',
    director: 'Inconnu',
    seasons: [
      {
        seasonNumber: 1,
        seasonRating: 0,
        seasonTimesWatched: 0,
        lastViewedDate: '',
      },
    ],
    owned: false,
    watchPriority: 1,
    wantToWatchAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
];
