import { UserGame } from '../../../../models/game-model';

export const ronanGames: UserGame[] = [
  {
    title: 'Call of Duty 4: Modern Warfare',
    editor: 'Infinity Ward',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Call of Duty: Modern Warfare 2',
    editor: 'Infinity Ward',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Call of Duty: Black Ops',
    editor: 'Treyarch',
    rating: 4,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 100,
    platined: true,
    owned: false,
  },
  {
    title: 'Call of Duty: Modern Warfare 3',
    editor: 'Infinity Ward',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Call of Duty: Black Ops II',
    editor: 'Treyarch',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 50,
    platined: false,
    owned: false,
  },
  {
    title: 'Call of Duty: Black Ops III',
    editor: 'Treyarch',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 213,
    platined: false,
    owned: false,
  },
  {
    title: 'Call of Duty: Black Ops 4',
    editor: 'Treyarch',
    rating: 2.5,
    timesFinished: 0,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Call of Duty: Black Ops Cold War',
    editor: 'Treyarch',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 60,
    platined: false,
    owned: false,
  },
  {
    title: 'Call of Duty: Black Ops 6',
    editor: 'Treyarch',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 30,
    platined: false,
    owned: false,
  },
  {
    title: 'One Piece: Pirate Warriors',
    editor: 'Omega Force',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 20,
    platined: true,
    owned: false,
  },
  {
    title: 'Naruto: Ultimate Ninja Storm',
    editor: 'CyberConnect2',
    rating: 4,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 15,
    platined: false,
    owned: false,
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm 2',
    editor: 'CyberConnect2',
    rating: 4.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm 3',
    editor: 'CyberConnect2',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 20,
    platined: true,
    owned: false,
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm 4',
    editor: 'CyberConnect2',
    rating: 4.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 20,
    platined: true,
    owned: false,
  },
  {
    title: 'Infamous',
    editor: 'Sucker Punch Productions',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 20,
    platined: true,
    owned: false,
  },
  {
    title: 'Infamous 2',
    editor: 'Sucker Punch Productions',
    rating: 3,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Infamous: Second Son',
    editor: 'Sucker Punch Productions',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Infamous: First Light',
    editor: 'Sucker Punch Productions',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'The Amazing Spider-Man',
    editor: 'Beenox',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Marvel's Spider-Man",
    editor: 'Insomniac Games',
    rating: 4,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Marvel's Spider-Man: Miles Morales",
    editor: 'Insomniac Games',
    rating: 4,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Marvel's Spider-Man 2",
    editor: 'Insomniac Games',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'BioShock Infinite',
    editor: 'Irrational Games',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Watch Dogs',
    editor: 'Ubisoft',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Dragon Ball Z: Budokai 3',
    editor: 'Dimps',
    rating: 4,
    timesFinished: 5,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 15,
    platined: false,
    owned: false,
  },
  {
    title: 'South Park: Le Bâton de la Vérité',
    editor: 'Obsidian Entertainment',
    rating: 4,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'God of War',
    editor: 'Santa Monica Studio',
    rating: 4,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'God of War Ragnarök',
    editor: 'Santa Monica Studio',
    rating: 4.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Hogwarts Legacy',
    editor: 'Avalanche Software',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Grand Theft Auto: Liberty City Stories',
    editor: 'Rockstar Games',
    rating: 3.5,
    timesFinished: 0,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Star Wars: Le Pouvoir de la Force',
    editor: 'LucasArts',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Lego Star Wars',
    editor: 'LucasArts',
    rating: 0,
    timesFinished: 0,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Wii Sports',
    editor: 'Nintendo',
    rating: 4,
    timesFinished: 0,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'A Plague Tale : Innocence',
    editor: 'Asobo Studio',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'A Plague Tale : Requiem',
    editor: 'Asobo Studio',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'A Way Out',
    editor: 'Hazelight Studios',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Anthem',
    editor: 'BioWare',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: "Assassin's Creed II",
    editor: 'Ubisoft',
    rating: 4,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 15,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed : Brotherhood",
    editor: 'Ubisoft',
    rating: 4.5,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed : Revelations",
    editor: 'Ubisoft',
    rating: 3.5,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed III",
    editor: 'Ubisoft',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed Liberation Remastered",
    editor: 'Ubisoft',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed III Remastered",
    editor: 'Ubisoft',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed IV : Black Flag",
    editor: 'Ubisoft',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 15,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed Rogue",
    editor: 'Ubisoft',
    rating: 3,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed Unity",
    editor: 'Ubisoft',
    rating: 3,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed Syndicate",
    editor: 'Ubisoft',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 15,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed Origins",
    editor: 'Ubisoft',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed Odyssey",
    editor: 'Ubisoft',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed Valhalla",
    editor: 'Ubisoft',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed Mirage",
    editor: 'Ubisoft',
    rating: 2,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Assassin's Creed Shadows",
    editor: 'Ubisoft',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Astro's Playroom",
    editor: 'Sony Interactive Entertainment',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Avatar : Frontiers of Pandora',
    editor: 'Ubisoft',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Batman: Arkham Asylum',
    editor: 'Rocksteady Studios',
    rating: 4.5,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Batman: Arkham City',
    editor: 'Rocksteady Studios',
    rating: 4.5,
    timesFinished: 5,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Batman: Arkham Knight',
    editor: 'Rocksteady Studios',
    rating: 4,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Batman: Arkham Origins',
    editor: 'WB Games Montréal',
    rating: 4,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Battlefield 4',
    editor: 'EA DICE',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'BioShock Remastered (Complete Edition)',
    editor: '2K Games',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Black Myth : Wukong',
    editor: 'Game Science',
    rating: 2.5,
    timesFinished: 0,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 30,
    platined: false,
    owned: false,
  },
  {
    title: 'Call of Duty : Modern Warfare Remastered',
    editor: 'Infinity Ward',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Clair Obscur : Expedition 33',
    editor: 'Sandfall Interactive',
    rating: 5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Cyberpunk 2077',
    editor: 'CD Projekt Red',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 20,
    platined: true,
    owned: false,
  },
  {
    title: 'Darksiders',
    editor: 'Vigil Games',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 10,
    platined: false,
    owned: false,
  },
  {
    title: 'Darksiders II Deathinitive Edition',
    editor: 'Vigil Games',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Days Gone',
    editor: 'Bend Studio',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 10,
    platined: true,
    owned: false,
  },
  {
    title: 'Deliver Us The Moon',
    editor: 'KeokeN Interactive',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 4,
    platined: true,
    owned: false,
  },
  {
    title: 'Detroit : Become Human',
    editor: 'Quantic Dream',
    rating: 4.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 8,
    platined: false,
    owned: false,
  },
  {
    title: 'Dishonored : Definitive Edition',
    editor: 'Arkane Studios',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Dishonored 2',
    editor: 'Arkane Studios',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'DmC Devil May Cry : Definitive Edition',
    editor: 'Ninja Theory',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 8,
    platined: false,
    owned: false,
  },
  {
    title: 'Dragon Ball Raging Blast 2',
    editor: 'Spike',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 5,
    platined: false,
    owned: false,
  },
  {
    title: 'Elden Ring',
    editor: 'FromSoftware',
    rating: 4.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 75,
    platined: true,
    owned: false,
  },
  {
    title: 'Far Cry 3',
    editor: 'Ubisoft',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 25,
    platined: true,
    owned: false,
  },
  {
    title: 'Far Cry 4',
    editor: 'Ubisoft',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Fist of the North Star : Ken's Rage",
    editor: 'Koei Tecmo',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Ghost of Tsushima',
    editor: 'Sucker Punch Productions',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'God of War III',
    editor: 'Santa Monica Studio',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Gotham Knights',
    editor: 'WB Games Montréal',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Gran Turismo 7',
    editor: 'Polyphony Digital',
    rating: 4,
    timesFinished: 0,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 20,
    platined: false,
    owned: false,
  },
  {
    title: 'Grand Theft Auto V',
    editor: 'Rockstar Games',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 15,
    platined: false,
    owned: false,
  },
  {
    title: 'Heavy Rain',
    editor: 'Quantic Dream',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Hitman',
    editor: 'IO Interactive',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Horizon Zero Dawn',
    editor: 'Guerrilla Games',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Horizon Forbidden West',
    editor: 'Guerrilla Games',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Indiana Jones et le Cercle Ancien',
    editor: 'MachineGames',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 30,
    platined: true,
    owned: false,
  },
  {
    title: 'Injustice : Les Dieux sont Parmi Nous',
    editor: 'NetherRealm Studios',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 30,
    platined: false,
    owned: false,
  },
  {
    title: 'Injustice : Les Dieux sont Parmi Nous - Ultimate Edition',
    editor: 'NetherRealm Studios',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Injustice 2',
    editor: 'NetherRealm Studios',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Kena : Bridge of Spirits',
    editor: 'Ember Lab',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Killzone Shadow Fall',
    editor: 'Guerrilla Games',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: "La Terre du Milieu : L'Ombre du Mordor",
    editor: 'Monolith Productions',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "La Terre du Milieu : L'Ombre de la Guerre",
    editor: 'Monolith Productions',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Life is Strange',
    editor: 'Dontnod Entertainment',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Mafia : The Old Country',
    editor: 'Hangar 13',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Mafia III : Definitive Edition',
    editor: 'Hangar 13',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: "Marvel's Guardians of the Galaxy",
    editor: 'Eidos-Montréal',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 12,
    platined: true,
    owned: false,
  },
  {
    title: 'Naruto Shippuden : Ultimate Ninja Storm Generations',
    editor: 'CyberConnect2',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Operation : Tango',
    editor: 'Clever Plays',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Prince of Persia : Les Sables Oubliés',
    editor: 'Ubisoft',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Qui es-tu?',
    editor: 'Inconnu',
    rating: 3.5,
    timesFinished: 5,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Ratchet & Clank : Rift Apart',
    editor: 'Insomniac Games',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Red Dead Redemption',
    editor: 'Rockstar Games',
    rating: 4.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Red Dead Redemption 2',
    editor: 'Rockstar Games',
    rating: 4.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 50,
    platined: false,
    owned: false,
  },
  {
    title: 'Resident Evil 7 : Biohazard',
    editor: 'Capcom',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Returnal',
    editor: 'Housemarque',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Rise of the Tomb Raider',
    editor: 'Crystal Dynamics',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 5,
    platined: false,
    owned: false,
  },
  {
    title: 'Shadow of the Tomb Raider',
    editor: 'Crystal Dynamics',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: "Le Seigneur des Anneaux : La Quête d'Aragorn",
    editor: 'Turbine',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'SSX',
    editor: 'EA Sports',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Star Wars : Battlefront II',
    editor: 'EA DICE',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Star Wars Jedi : Fallen Order',
    editor: 'Respawn Entertainment',
    rating: 4,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Star Wars Jedi : Survivor',
    editor: 'Respawn Entertainment',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Star Wars : Le Pouvoir de la Force II',
    editor: 'LucasArts',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Tekken 6',
    editor: 'Bandai Namco',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Tekken Revolution',
    editor: 'Bandai Namco',
    rating: 0,
    timesFinished: 0,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'The Elder Scrolls V : Skyrim',
    editor: 'Bethesda Game Studios',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'The Last of Us',
    editor: 'Naughty Dog',
    rating: 4,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'The Last of Us Part II',
    editor: 'Naughty Dog',
    rating: 4.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'The Order : 1886',
    editor: 'Ready at Dawn',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: "Tom Clancy's The Division",
    editor: 'Massive Entertainment',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Tomb Raider : Definitive Edition',
    editor: 'Crystal Dynamics',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 8,
    platined: false,
    owned: false,
  },
  {
    title: 'Titanfall 2',
    editor: 'Respawn Entertainment',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: "Uncharted : Drake's Fortune",
    editor: 'Naughty Dog',
    rating: 4.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Uncharted 2 : Among Thieves',
    editor: 'Naughty Dog',
    rating: 4.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Uncharted 2 : Among Thieves Remastered',
    editor: 'Naughty Dog',
    rating: 4.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: "Uncharted 3 : L'illusion de Drake",
    editor: 'Naughty Dog',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 8,
    platined: false,
    owned: false,
  },
  {
    title: "Uncharted 3 : L'Illusion de Drake Remastered",
    editor: 'Naughty Dog',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 8,
    platined: false,
    owned: false,
  },
  {
    title: "Uncharted 4 : A Thief's End",
    editor: 'Naughty Dog',
    rating: 5,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Uncharted : Legacy of Thieves Collection',
    editor: 'Naughty Dog',
    rating: 5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: true,
    owned: false,
  },
  {
    title: 'Watch Dogs 2',
    editor: 'Ubisoft',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'The Witcher 3 : Wild Hunt',
    editor: 'CD Projekt Red',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Wolfenstein : The New Order',
    editor: 'MachineGames',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Tetris',
    editor: 'Nintendo',
    rating: 3,
    timesFinished: 0,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 15,
    platined: false,
    owned: false,
  },
  {
    title: 'Super Mario 2',
    editor: 'Nintendo',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Pokémon Émeraude',
    editor: 'Game Freak',
    rating: 0,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Dragon Ball Z: Budokai 2',
    editor: 'Dimps',
    rating: 0,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Dragon Ball Z: Budokai Tenkaichi 2',
    editor: 'Spike',
    rating: 0,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Need for Speed: Most Wanted',
    editor: 'Electronic Arts',
    rating: 0,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Pokémon Bleu',
    editor: 'Game Freak',
    rating: 0,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Teenage Mutant Hero Turtles: Fall of the Foot Clan',
    editor: 'Konami',
    rating: 4,
    timesFinished: 4,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Double Dragon',
    editor: 'Nintendo',
    rating: 3,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Pokemon Jaune',
    editor: 'Nintendo',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Bomberman GB',
    editor: 'Nintendo',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Harry Potter et La Chambre des Secrets',
    editor: 'Electronic Arts',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: "Harry Potter à l'école des sorciers",
    editor: 'Electronic Arts',
    rating: 3.5,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Harry Potter et La Coupe de Feu',
    editor: 'Electronic Arts',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Pokemon version Ruby',
    editor: 'Nintendo',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Sonic Advance',
    editor: 'Sega',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Star Wars III - La Revanche des Siths',
    editor: 'Ubisoft',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Spider-Man 3',
    editor: 'Activision',
    rating: 3.5,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Les Urbz - Les Sims in the City',
    editor: 'Electronic Arts',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Star Wars : Flight of the Falcon',
    editor: 'Ubisoft',
    rating: 1.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Custom Robo Arena',
    editor: 'Nintendo',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Animal Crossing : Wild World',
    editor: 'Nintendo',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Arthur et les Minimoys',
    editor: 'Atari',
    rating: 3,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Assassin’s Creed Altaïr Chronicles',
    editor: 'Ubisoft',
    rating: 2.5,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Assassin’s Creed II : Discovery',
    editor: 'Ubisoft',
    rating: 3,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Astérix aux Jeux Olympiques',
    editor: 'Atari',
    rating: 2.5,
    timesFinished: 10,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Call of Duty 4 : Modern Warfare',
    editor: 'Activision',
    rating: 3,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Dragon Ball Z: Harukanaru Densetsu',
    editor: 'Atari',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Dragon Ball Z: Supersonic Warriors 2',
    editor: 'Atari',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Eragon',
    editor: 'Vivendi',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'FIFA 10',
    editor: 'Electronic Arts',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
  {
    title: 'Dragon Quest IX : Les Sentinelles du Firmament',
    editor: 'Nintendo',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Galactick Football',
    editor: 'Ubisoft',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Grand Theft Auto: Chinatown Wars',
    editor: 'Rockstar',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Guitar Hero: On Tour',
    editor: 'Activision',
    rating: 4,
    timesFinished: 4,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Harry Potter et la Coupe de Feu',
    editor: 'Electronic Arts',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: "Harry Potter et l'Ordre du Phénix",
    editor: 'Electronic Arts',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Harry Potter et le Prince de Sang Mêlé',
    editor: 'Electronic Arts',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Iron Man',
    editor: 'Sega',
    rating: 2,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Jump Ultimate Stars',
    editor: 'Nintendo',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Zelda Phantom Hourglass',
    editor: 'Nintendo',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Lego Batman',
    editor: 'Warner',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'LEGO Indiana Jones',
    editor: 'LucasArts',
    rating: 4,
    timesFinished: 4,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'LEGO Star Wars : The Complete Saga',
    editor: 'LucasArts',
    rating: 4,
    timesFinished: 5,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Mario & Sonic aux Jeux Olympiques',
    editor: 'Sega',
    rating: 3,
    timesFinished: 4,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Mario & Sonic JO Hiver',
    editor: 'Sega',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Mario Kart DS',
    editor: 'Nintendo',
    rating: 4,
    timesFinished: 10,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Mario Party DS',
    editor: 'Nintendo',
    rating: 4,
    timesFinished: 10,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Mario Slam Basketball',
    editor: 'Nintendo',
    rating: 3.5,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Naruto Shippuden: Ninja Council 4',
    editor: 'Ubisoft',
    rating: 3.5,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Naruto: Ninja Destiny 2',
    editor: 'Takara Tomy',
    rating: 3,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Naruto: Ninja Council 3',
    editor: 'Takara Tomy',
    rating: 3,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Naruto : Ninja Destiny',
    editor: 'Takara Tomy',
    rating: 3,
    timesFinished: 4,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Need for Speed : Most Wanted',
    editor: 'Electronic Arts',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Need for Speed : Nitro',
    editor: 'Electronic Arts',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Ninja Gaiden: Dragon Sword',
    editor: 'Tecmo',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Nintendogs',
    editor: 'Nintendo',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 1,
    platined: false,
    owned: false,
  },

  {
    title: "Pirates des Caraïbes: Jusqu'au Bout du Monde",
    editor: 'Disney',
    rating: 3.5,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Star Wars : Le Pouvoir de la Force',
    editor: 'LucasArts',
    rating: 3.5,
    timesFinished: 3,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Trackmania DS',
    editor: 'Ubisoft',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Transformers : The Game',
    editor: 'Activision',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'X-Men Origins: Wolverine',
    editor: 'Activision',
    rating: 3,
    timesFinished: 2,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Marvel Nemesis: Rise of the Imperfects',
    editor: 'Electronic Arts',
    rating: 2.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: "Programme d'entraînement cérébral du Dr Kawashima",
    editor: 'Nintendo',
    rating: 3,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 5,
    platined: false,
    owned: false,
  },

  {
    title: 'Professeur Layton et la Boite de Pandore',
    editor: 'Nintendo',
    rating: 3.5,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },

  {
    title: 'Saints Row 2',
    editor: 'THQ',
    rating: 4,
    timesFinished: 1,
    timesFinishedHundredPercent: 0,
    additionnalEstimatedTime: 0,
    platined: false,
    owned: false,
  },
];
