import { UserBooks } from '../../../../models/book-model';

export const guillaumeBooks: UserBooks = [
  {
    title: 'Une enfance en nORd',
    author: 'Marion Cuerq',
    firstReadDate: '2025-05-13',
    lastReadDate: '2025-05-13',
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Les liaisons dangereuses',
    author: 'Eny Heli',
    firstReadDate: '2025-06-19',
    lastReadDate: '2025-06-19',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Castel Boy',
    author: 'Eny Heli',
    firstReadDate: '2026-01-27',
    lastReadDate: '',
    rating: 5,
    readTimes: 2,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'En bons pères de famille',
    author: 'Rose Lamy',
    firstReadDate: '2025-05-15',
    lastReadDate: '2025-05-15',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: "Où va l'argent des pauvres",
    author: 'Denis Colombi',
    firstReadDate: '2025-01-01',
    lastReadDate: '2025-01-01',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Les tout-petits face aux écrans',
    author: 'Dr Anne-Lise Ducanda',
    firstReadDate: '2023-10-16',
    lastReadDate: '2023-10-16',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Les serres sous le velours noir',
    author: 'Charlène Ferlay',
    firstReadDate: '2025-01-14',
    lastReadDate: '2025-01-14',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: "Ne tirez pas sur l'oiseau moqueur",
    author: 'Harper Lee',
    firstReadDate: '2024-03-11',
    lastReadDate: '2024-03-11',
    rating: 3,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Les Hauts de Hurlevent',
    author: 'Emily Brontë',
    firstReadDate: '2024-02-24',
    lastReadDate: '2024-02-24',
    rating: 2.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Voyage au centre de la terre',
    author: 'Jules Verne',
    firstReadDate: '2024-01-10',
    lastReadDate: '2024-01-10',
    rating: 4,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Le tour du monde en 80 jours',
    author: 'Jules Verne',
    firstReadDate: '2025-03-18',
    lastReadDate: '2025-03-18',
    rating: 4,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Vingt Mille Lieues sous les mers',
    author: 'Jules Verne',
    firstReadDate: '2024-12-18',
    lastReadDate: '2024-12-18',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: "L'Île mystérieuse",
    author: 'Jules Verne',
    firstReadDate: '2025-06-23',
    lastReadDate: '2025-06-23',
    rating: 4,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'De la Terre à la Lune',
    author: 'Jules Verne',
    firstReadDate: '2025-03-16',
    lastReadDate: '2025-03-16',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Le Comte de Monte-Cristo',
    author: 'Alexandre Dumas',
    firstReadDate: '2024-04-30',
    lastReadDate: '2024-04-30',
    rating: 5,
    readTimes: 2,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Frankenstein',
    author: 'Mary Shelley',
    firstReadDate: '2024-05-16',
    lastReadDate: '2024-05-16',
    rating: 2.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Le Portrait de Dorian Gray',
    author: 'Oscar Wilde',
    firstReadDate: '2024-01-07',
    lastReadDate: '2024-01-07',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'La Ferme des animaux',
    author: 'George Orwell',
    firstReadDate: '2024-06-12',
    lastReadDate: '2024-06-12',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Orgueil et Préjugés',
    author: 'Jane Austen',
    firstReadDate: '2024-01-03',
    lastReadDate: '2024-01-03',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: '1984',
    author: 'George Orwell',
    firstReadDate: '2024-01-17',
    lastReadDate: '2024-01-17',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Fondation',
    author: 'Isaac Asimov',
    firstReadDate: '2025-01-15',
    lastReadDate: '2025-01-15',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    firstReadDate: '2024-02-15',
    lastReadDate: '2024-02-15',
    rating: 2.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Miss Marple au club du mardi',
    author: 'Agatha Christie',
    firstReadDate: '2025-03-10',
    lastReadDate: '2025-03-10',
    rating: 3,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: "L'Affaire Protheroe",
    author: 'Agatha Christie',
    firstReadDate: '2025-05-10',
    lastReadDate: '2025-05-10',
    rating: 3,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: "Le crime de l'Orient Express",
    author: 'Agatha Christie',
    firstReadDate: '2024-09-30',
    lastReadDate: '2024-09-30',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Mort sur le Nil',
    author: 'Agatha Christie',
    firstReadDate: '2024-02-10',
    lastReadDate: '2024-02-10',
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Ils étaient dix',
    author: 'Agatha Christie',
    firstReadDate: '2024-02-19',
    lastReadDate: '2024-02-19',
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Le Meurtre de Roger Ackroyd',
    author: 'Agatha Christie',
    firstReadDate: '2025-03-06',
    lastReadDate: '2025-03-06',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Meurtre en Mésopotamie',
    author: 'Agatha Christie',
    firstReadDate: '2025-04-25',
    lastReadDate: '2025-04-25',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Cinq petits cochons',
    author: 'Agatha Christie',
    firstReadDate: '2025-03-04',
    lastReadDate: '2025-03-04',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Dracula',
    author: 'Bram Stoker',
    firstReadDate: '2024-03-15',
    lastReadDate: '2024-03-15',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    firstReadDate: '2024-02-07',
    lastReadDate: '2024-02-07',
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Une vie',
    author: 'Guy de Maupassant',
    firstReadDate: '2024-10-02',
    lastReadDate: '2024-10-02',
    rating: 1,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'La tête sur les épaules',
    author: 'Henri Troyat',
    firstReadDate: '2024-02-25',
    lastReadDate: '2024-02-25',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'La Nuit des temps',
    author: 'René Barjavel',
    firstReadDate: '2024-06-12',
    lastReadDate: '2024-06-12',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'La Horde du Contrevent',
    author: 'Alain Damasio',
    firstReadDate: '2024-07-18',
    lastReadDate: '2024-07-18',
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Madame Bovary',
    author: 'Gustave Flaubert',
    firstReadDate: '2024-04-10',
    lastReadDate: '2024-04-10',
    rating: 1,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Bel-Ami',
    author: 'Guy de Maupassant',
    firstReadDate: '2024-03-05',
    lastReadDate: '2024-03-05',
    rating: 3,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Résister',
    author: 'Salomé Saqué',
    firstReadDate: '2024-11-15',
    lastReadDate: '2024-11-15',
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Le coût de la virilité',
    author: 'Lucile Peytavin',
    firstReadDate: '2024-12-11',
    lastReadDate: '2024-12-11',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Sois jeune et tais-toi',
    author: 'Salomé Saqué',
    firstReadDate: '2024-12-26',
    lastReadDate: '2024-12-26',
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: "L'Île au trésor",
    author: 'Robert Louis Stevenson',
    firstReadDate: '2025-03-13',
    lastReadDate: '2025-03-13',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Faites-les lire !',
    author: 'Michel Desmurget',
    firstReadDate: '2023-12-10',
    lastReadDate: '2023-12-10',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Candide',
    author: 'Voltaire',
    firstReadDate: '2011-03-10',
    lastReadDate: '2011-03-10',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Carrie',
    author: 'Stephen King',
    firstReadDate: '2025-07-09',
    lastReadDate: '2025-07-09',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Désolation',
    author: 'Stephen King',
    firstReadDate: '2016-07-09',
    lastReadDate: '2016-07-09',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: "L'étrange cas du docteur Jekyll et de Mr. Hyde",
    author: 'Robert Louis Stevenson',
    firstReadDate: '2025-07-11',
    lastReadDate: '2025-07-11',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: "L'ordinatueur",
    author: 'Christian Grenier',
    firstReadDate: '2004-01-28',
    lastReadDate: '2004-01-28',
    rating: 3.5,
    readTimes: 3,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'La Potion magique de Georges Bouillon',
    author: 'Roald Dahl',
    firstReadDate: '2003-01-28',
    lastReadDate: '2003-01-28',
    rating: 3.5,
    readTimes: 3,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Gatsby le magnifique',
    author: 'F. Scott Fitzgerald',
    firstReadDate: '2025-08-11',
    lastReadDate: '2025-08-11',
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'La guerre des mondes',
    author: 'H.G. Wells',
    firstReadDate: '2025-08-21',
    lastReadDate: '2025-08-21',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'La machine à explorer le temps',
    author: 'H.G. Wells',
    firstReadDate: '2025-08-31',
    lastReadDate: '2025-08-31',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: "L'homme invisible",
    author: 'H.G. Wells',
    firstReadDate: '2025-09-04',
    lastReadDate: '2025-09-04',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'La photo qui tue',
    author: 'Anthony Horowitz',
    firstReadDate: '2004-04-31',
    lastReadDate: '2004-04-31',
    rating: 3.25,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Les pages de notre amour',
    author: 'Nicholas Sparks',
    firstReadDate: '2025-09-06',
    lastReadDate: '2025-09-06',
    rating: 4.75,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'À tout jamais',
    author: 'Nicholas Sparks',
    firstReadDate: '2025-09-07',
    lastReadDate: '2025-09-07',
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Le porte bonheur',
    author: 'Nicholas Sparks',
    firstReadDate: '2025-09-09',
    lastReadDate: '2025-09-09',
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Memento mori',
    author: 'Eny Heli',
    firstReadDate: '2025-09-11',
    lastReadDate: '2026-01-11',
    rating: 4.5,
    readTimes: 2,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Un choix',
    author: 'Nicholas Sparks',
    firstReadDate: '2025-09-23',
    lastReadDate: '2025-09-23',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Viridia: Les racines du pouvoir',
    author: 'Aricia Favalli',
    firstReadDate: '2025-09-24',
    lastReadDate: '2025-09-24',
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Alchemised',
    author: 'SenLinYu',
    firstReadDate: '2025-10-11',
    lastReadDate: '2025-10-11',
    rating: 4.75,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: true,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Une seconde chance',
    author: 'Nicholas Sparks',
    firstReadDate: '2025-11-03',
    lastReadDate: '2025-11-03',
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: "L'Iliade",
    author: 'Homère',
    firstReadDate: '2025-12-24',
    lastReadDate: '2025-12-24',
    rating: 3.25,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: "L'Odyssée",
    author: 'Homère',
    firstReadDate: '2025-12-02',
    lastReadDate: '2025-12-02',
    rating: 3.75,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Adam',
    author: 'Eny Heli',
    firstReadDate: '2025-12-06',
    lastReadDate: '2026-03-08',
    rating: 4.5,
    readTimes: 2,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },

  {
    title: 'Là où chantent les écrevisses',
    author: 'Delia Owens',
    firstReadDate: '2025-12-26',
    lastReadDate: '2025-12-26',
    rating: 4.75,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Roméo et Juliette',
    author: 'William Shakespeare',
    firstReadDate: '2026-01-04',
    lastReadDate: '2026-01-04',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'La brute',
    author: 'Guy des Cars',
    firstReadDate: '2026-01-07',
    lastReadDate: '2026-01-07',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'The Dead zone',
    author: 'Stephen King',
    firstReadDate: '2026-01-17',
    lastReadDate: '2026-01-17',
    rating: 3.75,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },

  {
    title: 'Le Parfum',
    author: 'Patrick Süskind',
    firstReadDate: '2026-01-20',
    lastReadDate: '2026-01-20',
    rating: 5,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Les piliers de la terre',
    author: 'Ken Follett',
    firstReadDate: '2026-01-31',
    lastReadDate: '2026-01-31',
    rating: 2.75,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },

  {
    title: 'La fille du train',
    author: 'Paula Hawkins',
    firstReadDate: '2026-02-06',
    lastReadDate: '2026-02-06',
    rating: 3.75,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },

  {
    title: 'Faust',
    author: 'Johann Wolfgang von Goethe',
    firstReadDate: '2026-02-12',
    lastReadDate: '2026-02-12',
    rating: 2.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },

  {
    title: "Les Fiancés de l'Hiver",
    author: 'Christelle Dabos',
    firstReadDate: '2026-02-13',
    lastReadDate: '2026-02-13',
    rating: 4,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },

  {
    title: 'Les Disparus du Clairdelune',
    author: 'Christelle Dabos',
    firstReadDate: '2026-02-15',
    lastReadDate: '2026-02-15',
    rating: 5,
    readTimes: 1,
    owned: false,
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },

  {
    title: 'La Mémoire de Babel',
    author: 'Christelle Dabos',
    firstReadDate: '2026-02-17',
    lastReadDate: '2026-02-17',
    rating: 3.75,
    readTimes: 1,
    owned: false,
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },

  {
    title: 'La Tempête des Echos',
    author: 'Christelle Dabos',
    firstReadDate: '2026-02-21',
    lastReadDate: '2026-02-21',
    rating: 4.25,
    readTimes: 1,
    owned: false,
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },

  {
    title: 'Il était une fois: Tome 1 : Mon premier baiser',
    author: 'Chlore Smythe, Juliette Pierce',
    firstReadDate: '2026-02-22',
    lastReadDate: '2026-02-22',
    rating: 4,
    readTimes: 1,
    owned: false,
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },

  {
    title: 'Il était une fois: Tome 2 : Mon dernier amour',
    author: 'Chlore Smythe, Juliette Pierce',
    firstReadDate: '2026-02-24',
    lastReadDate: '2026-02-24',
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },

  {
    title: 'Numéro quatre',
    author: 'Pittacus Lore',
    firstReadDate: '2026-02-27',
    lastReadDate: '2026-02-27',
    rating: 4,
    readTimes: 1,
    owned: false,
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },

  {
    title: 'Tartuffe',
    author: 'Molière',
    firstReadDate: '2011-02-01',
    lastReadDate: '2011-02-01',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Cid',
    author: 'Corneille',
    firstReadDate: '2011-09-01',
    lastReadDate: '2011-09-01',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'L\'Aiguille creuse',
    author: 'Maurice Leblanc',
    firstReadDate: '2024-10-30',
    lastReadDate: '2024-10-30',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
];
