import { UserBooks } from '../../../../models/book-model';

export const guillaumeReadlistBooks: UserBooks = [
  {
    title: "Crime et châtiment",
    author: "Fiodor Dostoïevski",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Les liaisons dangereuses",
    author: "Pierre Choderlos de Laclos",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Les filles du Docteur March",
    author: "Louisa May Alcott",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Circe",
    author: "Madeline Miller",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le chant d'Achille",
    author: "Madeline Miller",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Dark Shores",
    author: "Danielle L. Jensen",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le Horla",
    author: "Guy de Maupassant",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "L'écume des jours",
    author: "Boris Vian",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Notre-Dame de Paris",
    author: "Victor Hugo",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le roi de fer",
    author: "Maurice Druon",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le vicomte de Bragelonne",
    author: "Alexandre Dumas",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "La reine Margot",
    author: "Alexandre Dumas",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le Trône de fer, L'Intégrale Tome 4",
    author: "George R.R. Martin",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le Trône de fer, L'Intégrale Tome 5",
    author: "George R.R. Martin",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Robinson Crusoe",
    author: "Daniel Defoe",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Cyrano de Bergerac",
    author: "Edmond Rostand",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Où vont les larmes quand elles sèchent",
    author: "Baptiste Beaulieu",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Autour de la Lune",
    author: "Jules Verne",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Les deux tours",
    author: "J.R.R. Tolkien",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le retour du roi",
    author: "J.R.R. Tolkien",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Leçons de chimie",
    author: "Bonnie Garmus",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Gagner la guerre",
    author: "Jean-Philippe Jaworski",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "L'enfer",
    author: "Dante Alighieri",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "L'epopée de Gilgamesh",
    author: "Anonyme",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Hamlet",
    author: "William Shakespeare",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Macbeth",
    author: "William Shakespeare",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "La dernière chanson",
    author: "Nicholas Sparks",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Fais un voeu",
    author: "Nicholas Sparks",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Au rythme de ton souffle",
    author: "Nicholas Sparks",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Un havre de paix",
    author: "Nicholas Sparks",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "L'amour aux temps du choléra",
    author: "Gabriel García Márquez",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Tout le bleu du ciel",
    author: "Melissa Da Costa",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Don Quichotte",
    author: "Miguel de Cervantes",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Autant en emporte le vent",
    author: "Margaret Mitchell",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Les Mille et Une Nuits",
    author: "Anonymous",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Anna Karénine",
    author: "Léon Tolstoï",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "L'espace d'un an",
    author: "Becky Chambers",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Princess Bride",
    author: "William Goldman",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "La Maison des feuilles",
    author: "Mark Z. Danielewski",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "La Révoltée",
    author: "Guy des Cars",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "L'impure",
    author: "Guy des Cars",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Un raccourci dans le temps",
    author: "Madeleine L'Engle",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Les voyages de Gulliver",
    author: "Jonathan Swift",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Rien qu'un surhomme",
    author: "Olaf Stapledon",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le Souffle de la Hyène",
    author: "Pierre Bottero",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le Journal d'Anne Frank",
    author: "Anne Frank",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Eragon (Eragon, #1)",
    author: "Christopher Paolini",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "La Dame aux camélias",
    author: "Alexandre Dumas fils",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "L'Alchimiste",
    author: "Paulo Coelho",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Nous",
    author: "Christelle Dabos",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le dernier voeu (The Witcher, #1)",
    author: "Andrzej Sapkowski",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "La vague",
    author: "Todd Strasser",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "La carte qui mène jusqu'à toi",
    author: "Joseph Monninger",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Emma",
    author: "Jane Austen",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "La Métamorphose",
    author: "Franz Kafka",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Sa majesté des mouches",
    author: "William Golding",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Des fleurs pour Algernon",
    author: "Daniel Keyes",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le dernier jour d'un condamné",
    author: "Victor Hugo",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "20 ans après",
    author: "Alexandre Dumas",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Othello",
    author: "William Shakespeare",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "La psy",
    author: "Freida McFadden",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le Talentueux M. Ripley",
    author: "Patricia Highsmith",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Millénium, Tome 1 : Les hommes qui n'aimaient pas les femmes",
    author: "Stieg Larsson",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Sublimes: La Chimère",
    author: "Emma Schütz",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "La faucheuse tome 1",
    author: "Neal Shusterman",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: "Marina",
    loaned: "",
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "King's Game",
    author: "Nobuaki Kanazawa",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: "Marina",
    loaned: "",
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "La Vérité sur l'Affaire Harry Quebert",
    author: "Joël Dicker",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le Procès",
    author: "Franz Kafka",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Demain est un autre jour",
    author: "May Angeli",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Divergente : Raconté par Quatre",
    author: "Veronica Roth",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le prestige",
    author: "Christopher Priest",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Chroniques martiennes",
    author: "Ray Bradbury",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Les Montagnes hallucinées",
    author: "H.P. Lovecraft",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le problème à trois corps",
    author: "Liu Cixin",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "King Kong Théorie",
    author: "Virginie Despentes",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Les Aventures de Sherlock Holmes",
    author: "Arthur Conan Doyle",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Les Mémoires de Sherlock Holmes",
    author: "Arthur Conan Doyle",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le Retour de Sherlock Holmes",
    author: "Arthur Conan Doyle",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Son dernier coup d'archet",
    author: "Arthur Conan Doyle",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Les Archives de Sherlock Holmes",
    author: "Arthur Conan Doyle",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Les Griffes et les Crocs",
    author: "Jo Walton",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Becoming",
    author: "Michelle Obama",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Une terre promise",
    author: "Barack Obama",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le manuscrit inachevé",
    author: "Franck Thilliez",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Raison et sentiments",
    author: "Jane Austen",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Casino Royale",
    author: "Ian Fleming",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le mystère de la chambre jaune",
    author: "Gaston Leroux",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Féroce Déférence (Lettres d'enchantement, #0)",
    author: "Rebecca Ross",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: "Lucile",
    loaned: "",
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le jeu de la dame",
    author: "Walter Tevis",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "The Way I Used to Be",
    author: "Amber Smith",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le capitalisme patriarcal",
    author: "Silvia Federici",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 0,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Borderline: Une vie au bord du gouffre",
    author: "Catherine S. Danemark et Michel Kummer",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: true,
    readTimes: 0,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "King's Game Spiral",
    author: "Nobuaki Kanazawa",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Je t'ai aimé dans une autre vie",
    author: "David Arnold",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "L'Invitée surprise",
    author: "Alison Espach",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Pourquoi Trump ne mange pas de Tofu",
    author: "Suzanne Zaccour",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "On n'a qu'une vie ! : Conseils pour souffler, déculpabiliser et (re)prendre du plaisir",
    author: "Pr Laurent Karila",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: true,
    borrowed: "",
    loaned: "",
    readPriority: 3,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Le Démon et mademoiselle Prym",
    author: "Paulo Coelho",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  },
  {
    title: "Vingt-quatre heures de la vie d'une femme",
    author: "Stefan Zweig",
    firstReadDate: "",
    lastReadDate: "",
    otherReadDates: [],
    rating: 0,
    reading: false,
    readTimes: 1,
    owned: false,
    borrowed: "",
    loaned: "",
    readPriority: 2,
    wantToReadAgain: false,
    ratingComment: "",
  }
];
