import { UserBooks } from '../../../../models/book-model';

export const guillaumeReadlistBooks: UserBooks = [
  {
    title: 'Crime et chatiment',
    author: 'Fiodor Dostoïevski',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Les liaisons dangereuses',
    author: 'Pierre Choderlos de Laclos',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Les filles du Docteur March',
    author: 'Louisa May Alcott',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Circe',
    author: 'Madeline Miller',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: "Le chant d'Achille",
    author: 'Madeline Miller',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Dark Shores',
    author: 'Danielle L. Jensen',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Le Horla',
    author: 'Guy de Maupassant',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: "L'écume des jours",
    author: 'Boris Vian',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Notre-Dame de Paris',
    author: 'Victor Hugo',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Le roi de fer',
    author: 'Maurice Druon',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Le vicomte de Bragelonne',
    author: 'Alexandre Dumas',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'La reine Margot',
    author: 'Alexandre Dumas',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 2,
  },
  {
    title: 'Le trone de fer intégrale 4',
    author: 'George R.R. Martin',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Le trone de fer intégrale 5',
    author: 'George R.R. Martin',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Robinson Crusoe',
    author: 'Daniel Defoe',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: false,
    readPriority: 1,
  },
  {
    title: 'Cyrano de Bergerac',
    author: 'Edmond Rostand',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 3,
  },
  {
    title: 'Où vont les larmes quand elles sèchent',
    author: 'Virginie Grimaldi',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Cinq semaines en ballon',
    author: 'Jules Verne',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: false,
    readPriority: 1,
  },
  {
    title: 'Autour de la Lune',
    author: 'Jules Verne',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Les deux tours',
    author: 'J.R.R. Tolkien',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Le retour du roi',
    author: 'J.R.R. Tolkien',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Leçons de chimie',
    author: 'Bonnie Garmus',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Gagner la guerre',
    author: 'Jean-Philippe Jaworski',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: "L'enfer",
    author: 'Dante Alighieri',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: "L'epopée de Gilgamesh",
    author: 'Anonyme',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Hamlet',
    author: 'William Shakespeare',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: false,
    readPriority: 1,
  },
  {
    title: 'Macbeth',
    author: 'William Shakespeare',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: false,
    readPriority: 1,
  },
  {
    title: 'La Controverse de Valladolid',
    author: 'Jean-Claude Carrière',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: false,
    readPriority: 1,
  },
  {
    title: 'La dernière chanson',
    author: 'Nicholas Sparks',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Fais un voeu',
    author: 'Nicholas Sparks',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
  {
    title: 'Au rythme de ton souffle',
    author: 'Nicholas Sparks',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 2,
  },
  {
    title: 'Un havre de paix',
    author: 'Nicholas Sparks',
    readDate: '',
    rating: 0,
    readTimes: 0,
    owned: true,
    readPriority: 1,
  },
];
