import { UserMangas } from '../../../../models/manga-model';

export const ronanReadListMangas: UserMangas = [
  {
    title: 'Kingdom',
    author: 'Yasuhisa Hara',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Black Clover',
    author: 'Tabata Yuuki',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'OnePunch-Man',
    author: 'Yûsuke Murata',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Slam Dunk',
    author: 'Takehiko Inoue',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Reborn',
    author: 'Akira Amano',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Yu Yu Hakusho',
    author: 'Yoshihiro Togashi',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Haikyū!!',
    author: 'Haruichi Furudate',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'The Promised Neverland',
    author: 'Kaiu Shirai',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Hajime no Ippo',
    author: 'George Morikawa',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Jujutsu Kaisen',
    author: 'Gege Akutami',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Vagabond',
    author: 'Takehiko Inoue',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Ken le Survivant',
    author: 'Yoshihiro Togashi',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
];
