import { UserMovie } from '../../../../models/movie-model';

export const masterofmadnessMovies: UserMovie[] = [
  {
    title: 'Damsel',
    director: 'Juan Carlos Fresnadillo',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Snatch',
    director: 'Guy Ritchie',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le silence des agneaux',
    director: 'Jonathan Demme',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Garfield',
    director: 'Peter Hewitt',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les 11 commandements',
    director: 'François Desagnat, Thomas Sorriaux',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le Murder Club du jeudi',
    director: 'Chris Columbus',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Bienvenue à Marly-Gomont',
    director: 'Julien Rambaldi',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Mulan',
    director: 'Niki Caro',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Joker',
    director: 'Todd Phillips',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Aladdin',
    director: 'Guy Ritchie',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'La soupe aux choux',
    director: 'Jean-Charles Tacchella',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "L'aile ou la cuisse",
    director: 'Claude Zidi',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les aventures de Rabbi Jacob',
    director: 'Gérard Oury',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'La Folie des grandeurs',
    director: 'Gérard Oury',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Fantomas',
    director: 'André Hunebelle',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le Gendarme de Saint-Tropez',
    director: 'Jean Girault',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Astérix et Obélix contre César',
    director: 'Claude Zidi',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Astérix & Obélix : Mission Cléopâtre',
    director: 'Alain Chabat',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Astérix aux Jeux Olympiques',
    director: 'Frédéric Forestier, Thomas Langmann',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'American Beauty',
    director: 'Sam Mendes',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Charlie et la Chocolaterie',
    director: 'Tim Burton',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'The Mask',
    director: 'Chuck Russell',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le Dîner de Cons',
    director: 'Francis Veber',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Kingsman : Services Secrets',
    director: 'Matthew Vaughn',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Death Note',
    director: 'Adam Wingard',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "Comment c'est loin",
    director: 'Orelsan',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Brice de Nice',
    director: 'James Huth',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'La tour Montparnasse infernale',
    director: 'Charles Nemes',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Dirty Dancing',
    director: 'Emile Ardolino',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Scarface',
    director: 'Brian De Palma',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Gran Torino',
    director: 'Clint Eastwood',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Je Suis une Légende',
    director: 'Francis Lawrence',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Into the Wild',
    director: 'Sean Penn',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Expendables : Unité Spéciale',
    director: 'Sylvester Stallone',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Fatal',
    director: 'Michaël Youn',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le Choc des Titans',
    director: 'Louis Leterrier',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Alice au Pays des Merveilles',
    director: 'Tim Burton',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Percy Jackson : Le Voleur de Foudre',
    director: 'Chris Columbus',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Mr. Nobody',
    director: 'Jaco Van Dormael',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le Loup de Wall Street',
    director: 'Martin Scorsese',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'The Conjuring : Les Dossiers Warren',
    director: 'James Wan',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Intouchables',
    director: 'Olivier Nakache, Éric Toledano',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les Affranchis',
    director: 'Martin Scorsese',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Jurassic Park',
    director: 'Steven Spielberg',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les visiteurs',
    director: 'Jean-Marie Poiré',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "20 ans d'écart",
    director: 'David Moreau',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Walter',
    director: 'Varante Soudjian',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Bright',
    director: 'David Ayer',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'La Grande Muraille',
    director: 'Zhang Yimou',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Pan',
    director: 'Joe Wright',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: '47 Ronin',
    director: 'Carl Rinsch',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "Braquage à l'ancienne",
    director: 'Zach Braff',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'La Mort aux trousses',
    director: 'Alfred Hitchcock',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'La Colère des Titans',
    director: 'Jonathan Liebesman',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Neuilly, sa mère !',
    director: 'Gabriel Julien-Laferrière',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'La Haine',
    director: 'Mathieu Kassovitz',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les trois frères',
    director: 'Didier Bourdon',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "Qu'est-ce qu'on a fait au bon dieu ?",
    director: 'Philippe de Chauveron',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "Bienvenue chez les Ch'tis",
    director: 'Dany Boon',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les Beaux Gosses',
    director: 'Riad Sattouf',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'La vérité si je mens !',
    director: 'Thomas Gilou',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Longlegs',
    director: 'Osgood Perkins',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les Mondes de Ralph',
    director: 'Rich Moore',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Encanto',
    director: 'Jared Bush, Byron Howard',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Cars',
    director: 'John Lasseter',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Vaiana',
    director: 'Ron Clements, John Musker',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les Nouveaux Héros',
    director: 'Don Hall, Chris Williams',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Moi, Moche et Méchant',
    director: 'Pierre Coffin, Chris Renaud',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Moi, Moche et Méchant 2',
    director: 'Pierre Coffin, Chris Renaud',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les Cinq Légendes',
    director: 'Peter Ramsey',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "L'Âge de Glace",
    director: 'Chris Wedge, Carlos Saldanha',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "L'Âge de Glace 2",
    director: 'Carlos Saldanha',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "L'Âge de Glace 3 : Le Temps des Dinosaures",
    director: 'Carlos Saldanha',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "L'Âge de Glace 4 : La Dérive des Continents",
    director: 'Steve Martino, Mike Thurmeier',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Arthur et les Minimoys',
    director: 'Luc Besson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Arthur et la Vengeance de Maltazard',
    director: 'Luc Besson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Arthur 3 : La Guerre des Deux Mondes',
    director: 'Luc Besson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Monstres contre Aliens',
    director: 'Rob Letterman, Conrad Vernon',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Kung Fu Panda',
    director: 'Mark Osborne, John Stevenson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les Simpson, le Film',
    director: 'David Silverman',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Ratatouille',
    director: 'Brad Bird',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Shrek',
    director: 'Andrew Adamson, Vicky Jenson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Shrek 2',
    director: 'Andrew Adamson, Kelly Asbury, Conrad Vernon',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les Indestructibles',
    director: 'Brad Bird',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le monde de Nemo',
    director: 'Andrew Stanton',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Monstres et Cie',
    director: 'Pete Docter',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Toy Story',
    director: 'John Lasseter',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Toy Story 2',
    director: 'John Lasseter',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Toy Story 3',
    director: 'Lee Unkrich',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Tarzan',
    director: 'Chris Buck, Kevin Lima',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Mulan',
    director: 'Tony Bancroft, Barry Cook',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Hercule',
    director: 'Ron Clements, John Musker',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Pocahontas',
    director: 'Mike Gabriel, Eric Goldberg',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le Roi Lion',
    director: 'Roger Allers, Rob Minkoff',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Aladdin',
    director: 'Ron Clements, John Musker',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'La petite sirène',
    director: 'Ron Clements, John Musker',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Peter Pan',
    director: 'Clyde Geronimi, Wilfred Jackson, Hamilton Luske',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Pinocchio',
    director:
      'Norman Ferguson, T. Hee, Wilfred Jackson, Jack Kinney, Hamilton Luske, Bill Roberts, Ben Sharpsteen',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Megamind',
    director: 'Tom McGrath',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'One Piece Film: Strong World',
    director: 'Munehisa Sakai',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'One Piece Film Z',
    director: 'Tatsuya Nagamine',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'One Piece : Gold',
    director: 'Hiroaki Miyamoto',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'One Piece: Stampede',
    director: 'Takashi Otsuka',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'One Piece Film: Red',
    director: 'Gorō Taniguchi',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Élémentaire',
    director: 'Peter Sohn',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Blanche-Neige et les Sept Nains',
    director: 'David Hand',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Cendrillon',
    director: 'Clyde Geronimi, Wilfred Jackson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Bambi',
    director: 'David Hand',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Dumbo',
    director: 'Ben Sharpsteen',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Alice au pays des merveilles',
    director: 'Clyde Geronimi, Wilfred Jackson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'La Belle au bois dormant',
    director: 'Clyde Geronimi',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'La Belle et le Clochard',
    director: 'Clyde Geronimi, Wilfred Jackson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le Livre de la jungle',
    director: 'Wolfgang Reitherman',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "L'Étrange Noël de monsieur Jack",
    director: 'Henry Selick',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le retour de Jafar',
    director: 'Toby Shelton, Tad Stones',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le Bossu de Notre-Dame',
    director: 'Gary Trousdale, Kirk Wise',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les 101 Dalmatiens',
    director: 'Stephen Herek',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Anastasia',
    director: 'Don Bluth, Gary Goldman',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le Monde magique de la Belle et la Bête',
    director: 'Bob Kline',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "Kuzco, l'Empereur mégalo",
    director: 'Mark Dindal',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: "Atlantide : L'Empire perdu",
    director: 'Gary Trousdale, Kirk Wise',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Lilo et Stitch',
    director: 'Dean DeBlois, Chris Sanders',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'La Planète au trésor',
    director: 'Ron Clements, John Musker',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Frère des ours',
    director: 'Aaron Blaise, Robert Walker',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les Noces funèbres',
    director: 'Tim Burton, Mike Johnson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Madagascar',
    director: 'Eric Darnell, Tom McGrath',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Madagascar 2',
    director: 'Eric Darnell, Tom McGrath',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Là-haut',
    director: 'Pete Docter',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Rio',
    director: 'Carlos Saldanha',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Raiponce',
    director: 'Byron Howard, Nathan Greno',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Kung Fu Panda 2',
    director: 'Jennifer Yuh Nelson',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Le Chat Potté',
    director: 'Chris Miller',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Hôtel Transylvanie',
    director: 'Genndy Tartakovsky',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Monstres Academy',
    director: 'Dan Scanlon',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Coco',
    director: 'Lee Unkrich',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Les Sous-doués',
    director: 'Claude Zidi',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Case départ',
    director: "Lionel Steketee, Fabrice Éboué, Thomas N'Gijol",
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Batman',
    director: 'Tim Burton',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Batman Begins',
    director: 'Christopher Nolan',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'The Dark Knight : Le Chevalier Noir',
    director: 'Christopher Nolan',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'The Dark Knight Rises',
    director: 'Christopher Nolan',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Black Adam',
    director: 'Jaume Collet-Serra',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Suicide Squad',
    director: 'David Ayer',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },

  {
    title: 'Frankenstein',
    director: 'Guillermo del Toro',
    rating: 0,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: false,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    borrowed: '',
    loaned: '',
    inList: [],
    lastUpdated: '',
  },
];
