import { UserMovie } from '../../../../models/movie-model';

export const lauralMovies: UserMovie[] = [
  {
    title: "Harry Potter à l'école des sorciers",
    director: "Chris Columbus",
    rating: 4.5,
    timesWatched: 30,
    firstViewedDate: "2001-12-24",
    lastViewedDate: "",
    otherSeenDates: [],
    seenAtCinema: true,
    owned: true,
    wantToSeeAgain: false,
    watchPriority: 0,
    ratingComment: "",
    inList: [],
    borrowed: "",
    loaned: "",
  },

  {
    title: "Harry Potter et le prisonnier d'Azkaban",
    director: "Alfonso Cuarón",
    rating: 4.5,
    timesWatched: 30,
    firstViewedDate: "2004-06-07",
    lastViewedDate: "",
    otherSeenDates: [],
    seenAtCinema: true,
    owned: true,
    wantToSeeAgain: false,
    watchPriority: 0,
    ratingComment: "",
    inList: [],
    borrowed: "",
    loaned: "",
  },

  {
    title: "Harry Potter et la coupe de feu",
    director: "Mike Newell",
    rating: 4.75,
    timesWatched: 30,
    firstViewedDate: "2005-11-30",
    lastViewedDate: "",
    otherSeenDates: [],
    seenAtCinema: true,
    owned: true,
    wantToSeeAgain: false,
    watchPriority: 0,
    ratingComment: "",
    inList: [],
    borrowed: "",
    loaned: "",
  },

  {
    title: "Harry Potter et l'ordre du phénix",
    director: "David Yates",
    rating: 4,
    timesWatched: 30,
    firstViewedDate: "2007-07-30",
    lastViewedDate: "",
    otherSeenDates: [],
    seenAtCinema: true,
    owned: true,
    wantToSeeAgain: false,
    watchPriority: 0,
    ratingComment: "",
    inList: [],
    borrowed: "",
    loaned: "",
  },

  {
    title: "Harry Potter et le prince de sang-mêlé",
    director: "David Yates",
    rating: 4,
    timesWatched: 30,
    firstViewedDate: "2009-07-30",
    lastViewedDate: "",
    otherSeenDates: [],
    seenAtCinema: true,
    owned: true,
    wantToSeeAgain: false,
    watchPriority: 0,
    ratingComment: "",
    inList: [],
    borrowed: "",
    loaned: "",
  },

  {
    title: "Harry Potter et les reliques de la mort - partie 1",
    director: "David Yates",
    rating: 4.75,
    timesWatched: 30,
    firstViewedDate: "2010-11-30",
    lastViewedDate: "",
    otherSeenDates: [],
    seenAtCinema: true,
    owned: true,
    wantToSeeAgain: false,
    watchPriority: 0,
    ratingComment: "",
    inList: [],
    borrowed: "",
    loaned: "",
  },

  {
    title: "Harry Potter et les reliques de la mort - partie 2",
    director: "David Yates",
    rating: 4.5,
    timesWatched: 1,
    firstViewedDate: '',
    lastViewedDate: '',
    otherSeenDates: [],
    seenAtCinema: true,
    owned: false,
    wantToSeeAgain: false,
    watchPriority: 1,
    ratingComment: '',
    inList: [],
    borrowed: '',
    loaned: '',
  },
];
