import { UserComics } from '../../../../models/comic-model';

export const ronanComics: UserComics = [
  {
    title: "Watchmen",
    writer: "Alan Moore",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Justice League : Crise d'identité",
    writer: "Brad Meltzer",
    readDate: "2023-04-23",
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Justice League : La Ligue de Justice d'Amérique",
    writer: "Johns",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Justice League : La Guerre des Ligues",
    writer: "Johns",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Justice League : Le Règne du Mal - 1re partie",
    writer: "Johns",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Justice League : Le Règne du Mal - 2e partie",
    writer: "Johns",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Justice League : La Ligue d'Injustice",
    writer: "Johns",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Justice League : La Guerre de Darkseid - 1re partie",
    writer: "Johns",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Justice League : La Guerre de Darkseid - 2e partie",
    writer: "Johns",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Superman : Requiem",
    writer: "Peter J. Tomasi",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Superman : Président Lex Luthor",
    writer: "DeMatteis",
    readDate: "",
    rating: 2.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Red Son",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Brisé",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Amère Victoire - 1re partie",
    writer: "Inconnu",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Amère Victoire - 2e partie",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "L'autre terre",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "À Rome...",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Pour demain - 1re partie",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Pour demain - 2e partie",
    writer: "Inconnu",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "La splendeur du Pingouin",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "L'odyssée du mal",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Un deuil dans la famille",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Aux origines",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Couple mythique",
    writer: "Inconnu",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Légendes",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Le deuil de la famille",
    writer: "Inconnu",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "La mort de Superman",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Pièges et trapèzes",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "D'entre les ombres",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "La révolte des lascars",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Brainiac",
    writer: "Inconnu",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Les patients d'Arkham",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Guerre au gorille",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Le trône d'Atlantide",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "La balade de Lobo",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Sur la route",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "La République de demain",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Luthor",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Dans les bas-fonds",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Green Arrow - Année Un",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Killing Joke",
    writer: "Inconnu",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Machine à tuer",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Origines secrètes",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Année un",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Un long Halloween - 1re partie",
    writer: "Inconnu",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Un long Halloween - 2e partie",
    writer: "Inconnu",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Année un - 1re partie",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Année un - 2e partie",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Robin - Année Un",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "La naissance du démon",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "L'odyssée - 1re partie",
    writer: "Inconnu",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "L'odyssée - 2e partie",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "La fille de Batman",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Élégie",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "La revanche de Bane",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Dieux et mortels",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Kingdom Come",
    writer: "Inconnu",
    readDate: "",
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Peur abyssale",
    writer: "Inconnu",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Rassemblement",
    writer: "Inconnu",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Secrets et origines",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Cité brisée",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Complètement marteau",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Empereur Joker - 1re partie",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Empereur Joker - 2e partie",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Transmetropolitan - Tome 1",
    writer: "Warren Ellis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Transmetropolitan - Tome 2",
    writer: "Warren Ellis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Transmetropolitan - Tome 3",
    writer: "Warren Ellis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Transmetropolitan - Tome 4",
    writer: "Warren Ellis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Transmetropolitan - Tome 5",
    writer: "Warren Ellis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Y, le Dernier Homme - Tome 1",
    writer: "Brian K. Vaughan",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Y, le Dernier Homme - Tome 2",
    writer: "Brian K. Vaughan",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Y, le Dernier Homme - Tome 3",
    writer: "Brian K. Vaughan",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Y, le Dernier Homme - Tome 4",
    writer: "Brian K. Vaughan",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Y, le Dernier Homme - Tome 5",
    writer: "Brian K. Vaughan",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Y, le Dernier Homme - Tome 6",
    writer: "Brian K. Vaughan",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fables - Tome 1",
    writer: "Bill Willingham",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fables - Tome 2",
    writer: "Bill Willingham",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fables - Tome 3",
    writer: "Bill Willingham",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fables - Tome 4",
    writer: "Bill Willingham",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fables - Tome 5",
    writer: "Bill Willingham",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Preacher - Tome 1",
    writer: "Garth Ennis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Preacher - Tome 2",
    writer: "Garth Ennis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Preacher - Tome 3",
    writer: "Garth Ennis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Preacher - Tome 4",
    writer: "Garth Ennis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman White Knight",
    writer: "Sean Murphy",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Top 10",
    writer: "Alan Moore",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Les seigneurs de Bagdad",
    writer: "Garth Ennis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Hellblazer : Dépendance mortelle",
    writer: "Garth Ennis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "All-Star Superman",
    writer: "Grant Morrison",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Superman : Up in the Sky",
    writer: "Tom King",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Superman : Écrase le Klan",
    writer: "Gene Luen Yang",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Superman : Les Origines",
    writer: "Mark Waid",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Superman : American Alien",
    writer: "Max Landis",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : Tueur né",
    writer: "Peter J. Tomasi",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "DCeased",
    writer: "Tom Taylor",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Mister Miracle",
    writer: "Tom King",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fables - Tome 6",
    writer: "Bill Willingham",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fables - Tome 7",
    writer: "Bill Willingham",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fables - Tome 8",
    writer: "Bill Willingham",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fables - Tome 9",
    writer: "Bill Willingham",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Flashpoint : Édition 10 ans",
    writer: "Geoff Johns",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : L'énigme de Red Hood",
    writer: "Judd Winick",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Absolute Superman",
    writer: "Jason Aaron",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Absolute Batman",
    writer: "Scott Snyder",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Absolute Justice League Unlimited",
    writer: "Mark Waid",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Superman : Dark Prophecy",
    writer: "Joshua Williamson",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Crisis on Infinite Earths",
    writer: "Marv Wolfman",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Supergirl : Woman of Tomorrow",
    writer: "Tom King",
    readDate: "2026-04-03",
    rating: 3.75,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Superman : Lost",
    writer: "Christopher Priest",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Dark Knights of Steel : Au loin",
    writer: "Tom Taylor",
    readDate: "",
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Dark Knights of Steel : La guerre des trois royaumes",
    writer: "Tom Taylor",
    readDate: "",
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Dark Knights of Steel : Allwinter",
    writer: "Kristoff",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Joker : The Winning Card",
    writer: "Tom King",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : Damned",
    writer: "Brian Azzarello",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "DC Universe Rebirth",
    writer: "Geoff Johns",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : Trois Jokers",
    writer: "Geoff Johns",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : Imposter",
    writer: "Mattson Tomlin",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman Rebirth - Tome 1",
    writer: "Tom King",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman Rebirth - Tome 2",
    writer: "Tom King",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman Metal - Tome 1",
    writer: "Scott Snyder",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman Metal - Tome 2",
    writer: "Scott Snyder",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman Noël",
    writer: "Lee Bermejo",
    readDate: "",
    rating: 2.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : Le cœur de silence",
    writer: "Paul Dini",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : Terre-un",
    writer: "Geoff Johns",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : Sombre reflet",
    writer: "Scott Snyder",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : Année Zéro",
    writer: "Scott Snyder",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : Curse of the White Knight",
    writer: "Sean Murphy",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Green Lantern - Tome 1",
    writer: "Geoff Johns",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Green Lantern - Tome 2",
    writer: "Geoff Johns",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Green Lantern - Tome 3",
    writer: "Geoff Johns",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman Anthologie",
    writer: "Collectif",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "DC Comics Anthologie",
    writer: "Collectif",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman Beyond : The White Knight",
    writer: "Sean Murphy",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : Bane",
    writer: "Tom King",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : Deathstroke",
    writer: "Christopher Priest",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : Le Pingouin",
    writer: "John Layman",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Batman : L'asile d'Arkham",
    writer: "Dan Slott",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Joker : Mauvaises fréquentations",
    writer: "Brian Azzarello, Ed Brubaker",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Harley Quinn Rebirth",
    writer: "Amanda Conner, Jimmy Palmiotti",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Les sirènes de Gotham",
    writer: "Paul Dini",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Justice League : Forever Evil",
    writer: "Geoff Johns",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Suicide Squad Rebirth",
    writer: "Rob Williams",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Justice League vs Suicide Squad",
    writer: "Joshua Williamson",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Superman Anthologie",
    writer: "Collectif",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Superman : Identité secrète",
    writer: "Kurt Busiek",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man",
    writer: "J. Michael Straczynski",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : Bleu",
    writer: "Jeph Loeb",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Venom : Rex",
    writer: "Mike Costa",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Wolverine : Les origines",
    writer: "Paul Jenkins",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Thor : La déesse du tonnerre",
    writer: "Jason Aaron",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Ultimates : Super-humain",
    writer: "Mark Millar",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Thanos : Thanos gagne",
    writer: "Donny Cates",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Immortal Hulk : Ou est-il des deux ?",
    writer: "Al Ewing",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Captain Marvel : La vie de Captain Marvel",
    writer: "Kelly Thompson",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Hawkeye : Ma vie est une arme",
    writer: "Matt Fraction",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Daredevil : Jaune",
    writer: "Jeph Loeb",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Cosmic Ghost Rider : Bébé Thanos doit mourir",
    writer: "Donny Cates",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Deadpool : Massacre",
    writer: "Cullen Bunn",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Marvel Zombies : La famine",
    writer: "Robert Kirkman",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : L'empire",
    writer: "Kaare Andrews",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : Spider-Geddon",
    writer: "Christos Gage",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Avengers : Les origines",
    writer: "Joe Casey",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Avengers : Les nuits de Wundagore",
    writer: "Collectif",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Avengers : État de siège",
    writer: "Brian Michael Bendis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Avengers : Ultron Unlimited",
    writer: "Kurt Busiek",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Avengers : Dark Avengers",
    writer: "Brian Michael Bendis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Avengers : Le monde des Avengers",
    writer: "Collectif",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Captain America : Le soldat de l'hiver",
    writer: "Ed Brubaker",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Les Gardiens de la Galaxie",
    writer: "Brian Michael Bendis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Thor : Renaissance",
    writer: "J. Michael Straczynski",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Thanos : La quête de Thanos",
    writer: "Jim Starlin",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Venom vs Carnage : Un enfant est né",
    writer: "Peter Milligan",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Deadpool : Il faut soigner le soldat Wilson",
    writer: "Gerry Duggan",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Wolverine : L'arme X",
    writer: "Barry Windsor-Smith",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : N'est plus !",
    writer: "Stan Lee",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : La saga du Rédempteur",
    writer: "Peter David",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : La naissance de Venom",
    writer: "David Michelinie",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : Révélations",
    writer: "Straczynski, Joe Michaël",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : Apprentissage",
    writer: "Bendis, Brian Michael",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : Le cauchemar",
    writer: "Jenkins, Paul",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : Spider-Men",
    writer: "Brian Michael Bendis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "The Boys : Ça va faire très mal !",
    writer: "Garth Ennis",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "The Boys : Ça va saigner !",
    writer: "Garth Ennis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "The Boys : Dit comme ça...",
    writer: "Garth Ennis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "The Boys : Croire",
    writer: "Garth Ennis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "The Boys : Le fils du boulanger",
    writer: "Garth Ennis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "The Boys : On ne prend plus de gants",
    writer: "Garth Ennis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "The Boys : Chère Becky",
    writer: "Garth Ennis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Kick-Ass - Tome 1",
    writer: "Mark Millar",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Kick-Ass - Tome 2",
    writer: "Mark Millar",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Kick-Ass - Tome 3",
    writer: "Mark Millar",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Avengers : La séparation",
    writer: "Brian Michael Bendis",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Daredevil : End of Days",
    writer: "Brian Michael Bendis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Les Guerres Secrètes",
    writer: "Jim Shooter",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "World War Hulk",
    writer: "Greg Pak",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : Le retour du Bouffon Vert",
    writer: "J. M. DeMatteis",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "House of M",
    writer: "Brian Michael Bendis",
    readDate: "",
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Uncanny Avengers : Nouvelle Union",
    writer: "Remender, Rick",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Thanos : L'ascension",
    writer: "Aaron, Jason",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : La dernière chasse de Kraven",
    writer: "J. M. DeMatteis",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Thanos : Le gant de l'infini",
    writer: "Jim Starlin",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Thanos : La guerre de l'infini",
    writer: "Jim Starlin",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Thanos : La croisade de l'infini",
    writer: "Jim Starlin",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "La mort de Wolverine",
    writer: "Charles Soule",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Wolverine : Old Man Logan",
    writer: "Mark Millar",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : Spider-Verse",
    writer: "Dan Slott",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : De père en fils",
    writer: "J. J. Abrams",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Avengers",
    writer: "Heinberg",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Daredevil - Tome 1",
    writer: "McKenzie",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Daredevil - Tome 2",
    writer: "Miller",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Daredevil - Tome 3",
    writer: "Miller",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Daredevil - Tome 4",
    writer: "Miller",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : 11 septembre 2001",
    writer: "Inconnu",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : Son of M",
    writer: "David Hine",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : La vraie saga du clone",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : Tandem",
    writer: "Straczynski, Joe Michaël",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : L'attaque",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Civil War",
    writer: "Mark Millar",
    readDate: "",
    rating: 4.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Planet Hulk",
    writer: "Greg Pak",
    readDate: "",
    rating: 3.5,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Avengers vs X-Men",
    writer: "Brian Michael Bendis",
    readDate: "",
    rating: 4,
    readTimes: 3,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Infinity",
    writer: "Jonathan Hickman",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Secret Wars",
    writer: "Jonathan Hickman",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Marvel Icons",
    writer: "Inconnu",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man Noir : Cinquante nuances de noir",
    writer: "David Hine",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "X-Men : House of X / Powers of X",
    writer: "Jonathan Hickman",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Astonishing X-Men : Surdoués",
    writer: "Joss Whedon",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Astonishing X-Men : Invincible",
    writer: "Joss Whedon",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Spider-Man : Spider-Island",
    writer: "Dan Slott",
    readDate: "",
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fantastic Four : Face aux fantômes",
    writer: "Collectif",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fantastic Four : L'histoire d'une vie",
    writer: "Mark Russell",
    readDate: "",
    rating: 4,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fantastic Four : L'appel des cendres",
    writer: "Collectif",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Fantastic Four : Coup de force",
    writer: "Collectif",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Wolverine : Ennemi d'État",
    writer: "Mark Millar",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  },
  {
    title: "Secret Wars : La fin des temps",
    writer: "Collectif",
    readDate: "",
    rating: 0,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: "",
    borrowed: "",
    loaned: "",
  }
];
