import { UserBook } from '../../../../models/book-model';

export const dantesBooks: UserBook[] = [
  {
    title: 'Charlie et la Chocolaterie',
    author: 'Roald Dahl',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'The Shining',
    author: 'Stephen King',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Hauts de Hurlevent',
    author: 'Emily Brontë',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Voyage au centre de la terre',
    author: 'Jules Verne',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le tour du monde en 80 jours',
    author: 'Jules Verne',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Vingt Mille Lieues sous les mers',
    author: 'Jules Verne',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'Île mystérieuse",
    author: 'Jules Verne',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'De la Terre à la Lune',
    author: 'Jules Verne',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Comte de Monte-Cristo',
    author: 'Alexandre Dumas',
    readDate: '',
    rating: 5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Frankenstein',
    author: 'Mary Shelley',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Portrait de Dorian Gray',
    author: 'Oscar Wilde',
    readDate: '',
    rating: 2,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Ferme des animaux',
    author: 'George Orwell',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Orgueil et Préjugés',
    author: 'Jane Austen',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Emma',
    author: 'Jane Austen',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: '1984',
    author: 'George Orwell',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Miss Marple au club du mardi',
    author: 'Agatha Christie',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Le crime de l'Orient Express",
    author: 'Agatha Christie',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Mort sur le Nil',
    author: 'Agatha Christie',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Ils étaient dix',
    author: 'Agatha Christie',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Cinq petits cochons',
    author: 'Agatha Christie',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Une vie',
    author: 'Guy de Maupassant',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Nuit des temps',
    author: 'René Barjavel',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Madame Bovary',
    author: 'Gustave Flaubert',
    readDate: '',
    rating: 2,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Résister',
    author: 'Salomé Saqué',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'Île au trésor",
    author: 'Robert Louis Stevenson',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Candide',
    author: 'Voltaire',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'étrange cas du docteur Jekyll et de Mr. Hyde",
    author: 'Robert Louis Stevenson',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Potion magique de Georges Bouillon',
    author: 'Roald Dahl',
    readDate: '',
    rating: 2,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Gatsby le magnifique',
    author: 'F. Scott Fitzgerald',
    readDate: '',
    rating: 2,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'homme invisible",
    author: 'H.G. Wells',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'Iliade",
    author: 'Homère',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'Odyssée",
    author: 'Homère',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Là où chantent les écrevisses',
    author: 'Delia Owens',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Roméo et Juliette',
    author: 'William Shakespeare',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Don Quichotte',
    author: 'Miguel de Cervantes',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Faust',
    author: 'Johann Wolfgang von Goethe',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les Mille et Une Nuits',
    author: 'Anonymous',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Anna Karénine',
    author: 'Léon Tolstoï',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Le Journal d'Anne Frank",
    author: 'Anne Frank',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Da Vinci Code',
    author: 'Dan Brown',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Martin Eden',
    author: 'Jack London',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Sa majesté des mouches',
    author: 'William Golding',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Couleur des sentiments',
    author: 'Kathryn Stockett',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les raisins de la colère',
    author: 'John Steinbeck',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Vieil Homme et la Mer',
    author: 'Ernest Hemingway',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Lettre d'une inconnue",
    author: 'Stefan Zweig',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Dame aux camélias',
    author: 'Alexandre Dumas fils',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Tristan et Iseult',
    author: 'René Louis',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Moby Dick',
    author: 'Herman Melville',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'À la recherche du temps perdu',
    author: 'Marcel Proust',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'attrape-cœurs",
    author: 'J.D. Salinger',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Voyage au bout de la nuit',
    author: 'Louis-Ferdinand Céline',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Petit Prince',
    author: 'Antoine de Saint-Exupéry',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les Misérables',
    author: 'Victor Hugo',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Croc-Blanc',
    author: 'Jack London',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Le Trône de fer, L'Intégrale Tome 1",
    author: 'George R.R. Martin',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Le Trône de fer, L'Intégrale Tome 2",
    author: 'George R.R. Martin',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Le Trône de fer, L'Intégrale Tome 3",
    author: 'George R.R. Martin',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Le Seigneur des Anneaux Tome 1 : La Communauté de l'Anneau",
    author: 'J.R.R. Tolkien',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les deux tours',
    author: 'J.R.R. Tolkien',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le retour du roi',
    author: 'J.R.R. Tolkien',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'étranger",
    author: 'Albert Camus',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Croc-Blanc',
    author: 'Jack London',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Planète des singes',
    author: 'Pierre Boulle',
    readDate: '',
    rating: 2,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Harry Potter à l'école des sorciers",
    author: 'J.K. Rowling',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Harry Potter et la Chambre des secrets',
    author: 'J.K. Rowling',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Harry Potter et le Prisonnier d'Azkaban",
    author: 'J.K. Rowling',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Harry Potter et la Coupe de feu',
    author: 'J.K. Rowling',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Harry Potter et l'Ordre du Phénix",
    author: 'J.K. Rowling',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Harry Potter et le Prince de sang-mêlé',
    author: 'J.K. Rowling',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Harry Potter et les Reliques de la Mort',
    author: 'J.K. Rowling',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "Harry Potter et l'Enfant maudit",
    author: 'J.K. Rowling',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Une étude en rouge',
    author: 'Arthur Conan Doyle',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Signe des quatre',
    author: 'Arthur Conan Doyle',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Chien des Baskerville',
    author: 'Arthur Conan Doyle',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La vallée de la peur',
    author: 'Arthur Conan Doyle',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les Trois Mousquetaires',
    author: 'Alexandre Dumas',
    readDate: '',
    rating: 5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Louve de France',
    author: 'Maurice Druon',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Lis et le Lion',
    author: 'Maurice Druon',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Loi des mâles',
    author: 'Maurice Druon',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Reine étranglée',
    author: 'Maurice Druon',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les Poisons de la Couronne',
    author: 'Maurice Druon',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Quand un roi perd la France',
    author: 'Maurice Druon',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Crime et chatiment',
    author: 'Fiodor Dostoïevski',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les liaisons dangereuses',
    author: 'Pierre Choderlos de Laclos',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les piliers de la terre',
    author: 'Ken Follett',
    readDate: '',
    rating: 5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Horla',
    author: 'Guy de Maupassant',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'écume des jours",
    author: 'Boris Vian',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Notre-Dame de Paris',
    author: 'Victor Hugo',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le roi de fer',
    author: 'Maurice Druon',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le vicomte de Bragelonne',
    author: 'Alexandre Dumas',
    readDate: '',
    rating: 5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La reine Margot',
    author: 'Alexandre Dumas',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le trone de fer intégrale 4',
    author: 'George R.R. Martin',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le trone de fer intégrale 5',
    author: 'George R.R. Martin',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Robinson Crusoe',
    author: 'Daniel Defoe',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Cyrano de Bergerac',
    author: 'Edmond Rostand',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Parfum',
    author: 'Patrick Süskind',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Cinq semaines en ballon',
    author: 'Jules Verne',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Autour de la Lune',
    author: 'Jules Verne',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'enfer",
    author: 'Dante Alighieri',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: "L'epopée de Gilgamesh",
    author: 'Anonyme',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Hamlet',
    author: 'William Shakespeare',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Macbeth',
    author: 'William Shakespeare',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les voyages de Gulliver',
    author: 'Jonathan Swift',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Le Procès',
    author: 'Franz Kafka',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'La Métamorphose',
    author: 'Franz Kafka',
    readDate: '',
    rating: 2,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Guerre et Paix',
    author: 'Léon Tolstoï',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },

  {
    title: 'Les Frères Karamazov',
    author: 'Fiodor Dostoïevski',
    readDate: '',
    rating: 2,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Autant en emporte le vent',
    author: 'Margaret Mitchell',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Bel-Ami',
    author: 'Guy de Maupassant',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Les filles du Docteur March',
    author: 'Louisa May Alcott',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: true,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: false,
  },
  {
    title: 'Le Château des Papes : Les Intriguants',
    author: 'Inconnu',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Château des Papes II : Les bâtisseurs',
    author: 'Inconnu',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Château des Papes III : Les Impétueux',
    author: 'Inconnu',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'No Pasaran le jeu',
    author: 'Christian Lehmann',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Passeur',
    author: 'Lois Lowry',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Délivrez-nous du mal',
    author: 'Romain Sardou',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Pardonnez nos offenses',
    author: 'Romain Sardou',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'éclat de dieu ou le roman du temps",
    author: 'Romain Sardou',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Un homme averti ne vaut rien',
    author: 'Romain Sardou',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Quitte Rome ou meurs',
    author: 'Romain Sardou',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'America I : La treizième colonie',
    author: 'Romain Sardou',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'America II : La main rouge',
    author: 'Romain Sardou',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Le dernier jour d'un condamné",
    author: 'Victor Hugo',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Hernani',
    author: 'Victor Hugo',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Cromwell',
    author: 'Victor Hugo',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Lucrèce Borgia',
    author: 'Victor Hugo',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les châtiments',
    author: 'Victor Hugo',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Contemplations',
    author: 'Victor Hugo',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Orientales',
    author: 'Victor Hugo',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La peste',
    author: 'Albert Camus',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le bourgeois Gentilshommes',
    author: 'Molière',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les fourberies de Scapin',
    author: 'Molière',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'avare",
    author: 'Molière',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'école des femmes",
    author: 'Molière',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'école des maris",
    author: 'Molière',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Tartuffe',
    author: 'Molière',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les précieuses ridicules',
    author: 'Molière',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Misanthrope',
    author: 'Molière',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Cid',
    author: 'Corneille',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le mariage de Figaro',
    author: 'Beaumarchais',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le barbier de Seville',
    author: 'Beaumarchais',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'autre Tartuffe ou la mère coupable",
    author: 'Beaumarchais',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: '20 ans après',
    author: 'Alexandre Dumas',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Collier de la reine',
    author: 'Alexandre Dumas',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Fille du marquis',
    author: 'Alexandre Dumas',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Un Monde sans fin',
    author: 'Ken Follett',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Une Colonne de feu',
    author: 'Ken Follett',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les armes de la lumière',
    author: 'Ken Follett',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Le crépuscule et l'aube",
    author: 'Ken Follett',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La chute des géants',
    author: 'Ken Follett',
    readDate: '',
    rating: 5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'hiver du monde",
    author: 'Ken Follett',
    readDate: '',
    rating: 5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Aux portes de l'éternité",
    author: 'Ken Follett',
    readDate: '',
    rating: 5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Cercle des jours',
    author: 'Ken Follett',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Anges et démons',
    author: 'Dan Brown',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Symbole Perdu',
    author: 'Dan Brown',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Inferno',
    author: 'Dan Brown',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Origine',
    author: 'Dan Brown',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Secret des secrets',
    author: 'Dan Brown',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Forteresse Digitale',
    author: 'Dan Brown',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Deception Point',
    author: 'Dan Brown',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "La Vérité sur l'Affaire Harry Quebert",
    author: 'Joël Dicker',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Livre des Baltimore',
    author: 'Joël Dicker',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Affaire Alaska Sanders",
    author: 'Joël Dicker',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La chambre 622',
    author: 'Joël Dicker',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les derniers de nos pères',
    author: 'Joël Dicker',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Pantagruel',
    author: 'François Rabelais',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Gargantua',
    author: 'François Rabelais',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le rouge et le noir',
    author: 'Stendhal',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'De grandes espérances',
    author: 'Charles Dickens',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Oliver Twist',
    author: 'Charles Dickens',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le nom de la rose',
    author: 'Umberto Eco',
    readDate: '',
    rating: 4.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les oiseaux se cachent pour mourir',
    author: 'Colleen McCullough',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Mon bel Orange',
    author: 'José Mauro de Vasconcelos',
    readDate: '',
    rating: 5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "La promesse de l'aube",
    author: 'Romain Gary',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Aventures de Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Mémoires de Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Retour de Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Son dernier coup d'archet",
    author: 'Arthur Conan Doyle',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Archives de Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Arsène Lupin, gentleman cambrioleur',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Arsène Lupin contre Herlock Sholmès',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Aiguille creuse",
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 4,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "La double vie d'Arsène Lupin",
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Les trois crimes d'Arsène Lupin",
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Bouchon de cristal',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Les Confidences d'Arsène Lupin",
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Éclat d'obus",
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Le Triangle d'or",
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Île aux trente cercueils",
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Dents du tigre',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Les Huit Coups de l'horloge",
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Comtesse de Cagliostro',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Demoiselle aux yeux verts',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Le Cabochon d'émeraude suivi de L'Homme à la peau de bique",
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Agence Barnett et Cie",
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Demeure mystérieuse',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Barre-y-va',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Femme aux deux sourires',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Victor, de la Brigade mondaine',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 2,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Cagliostro se venge',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "Le Dernier Amour d'Arsène Lupin",
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: "L'Arrestation d'Arsène Lupin",
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Les Trois Yeux',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Le Formidable Événement',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'Dorothée, danseuse de corde',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 2.5,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
  {
    title: 'La Vie extravagante de Balthazar',
    author: 'Maurice Leblanc',
    readDate: '',
    rating: 3,
    readTimes: 1,
    owned: false,
    borrowed: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
  },
];
