import { UserBd } from '../../../../models/bd-model';

export const marinaBds: UserBd[] = [
  {
    title: 'Astérix le Gaulois',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "La Serpe d'or",
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix et les Goths',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix gladiateur',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "Le Tour de Gaule d'Astérix",
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix et Cléopâtre',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Le Combat des chefs',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix chez les Bretons',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix et les Normands',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix légionnaire',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Le Bouclier arverne',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix aux Jeux olympiques',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix et le chaudron',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix en Hispanie',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'La Zizanie',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix chez les Helvètes',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Le Domaine des dieux',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Les Lauriers de César',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Le Devin',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix en Corse',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Le Cadeau de César',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'La Grande Traversée',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Obélix et Compagnie',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix chez les Belges',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Le Grand Fossé',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "L'Odyssée d'Astérix",
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "Le Fils d'Astérix",
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix chez Rahàzade',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'La Rose et le Glaive',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "La Galère d'Obélix",
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix et Latraviata',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Astérix et la Rentrée gauloise',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Le ciel lui tombe sur la tête',
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "L'Anniversaire d'Astérix et Obélix - Le Livre d'or",
    writer: 'René Goscinny',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Les Nombrils - Tome 1 - Pour qui tu te prends ?',
    writer: 'Dubuc et Delaf',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Les Nombrils - Tome 2 - Sale temps pour les moches',
    writer: 'Dubuc et Delaf',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "Les Nombrils - Tome 3 - Les liens de l'amitié",
    writer: 'Dubuc et Delaf',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Les Nombrils - Tome 4 - Duel de belles',
    writer: 'Dubuc et Delaf',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "Les Nombrils - Tome 5 - Un couple d'enfer",
    writer: 'Dubuc et Delaf',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Les Nombrils - Tome 6 - Un été trop mortel',
    writer: 'Dubuc et Delaf',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Les Nombrils - Tome 7 - Un bonheur presque parfait',
    writer: 'Dubuc et Delaf',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "Les Nombrils - Tome 8 - Ex, drague et rock'n'roll !",
    writer: 'Dubuc et Delaf',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Les vacheries des nombrils - Tome 1 - Vachement copines',
    writer: 'Dubuc et Delaf',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Les vacheries des nombrils - Tome 2 - Une fille en or',
    writer: 'Dubuc et Delaf',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Lou! - Journal Infime',
    writer: 'Julien Neel',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Lou! - Mortebouse',
    writer: 'Julien Neel',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Lou! - Le Cimetière des autobus',
    writer: 'Julien Neel',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Lou! - Idylles',
    writer: 'Julien Neel',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Lou! - Laser ninja',
    writer: 'Julien Neel',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: "Lou! - L'Âge de cristal",
    writer: 'Julien Neel',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Lou! - La Cabane',
    writer: 'Julien Neel',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
  {
    title: 'Lou! - En route vers de nouvelles aventures !',
    writer: 'Julien Neel',
    readDate: '',
    rating: 0,
    readTimes: 1,
    owned: false,
    readPriority: 1,
    wantToReadAgain: false,
    ratingComment: '',
    borrowed: '',
    loaned: '',
  },
];
